{'class': [],
 'func': [],
 'import': ['__builtin__'],
 'var': [{'name': 'CHAT_RGB_COMMAND', 'type': 'tuple', 'value': (167, 255, 212)},
         {'name': 'CHAT_RGB_GUILD', 'type': 'tuple', 'value': (253, 255, 124)},
         {'name': 'CHAT_RGB_INFO', 'type': 'tuple', 'value': (255, 200, 200)},
         {'name': 'CHAT_RGB_NOTICE', 'type': 'tuple', 'value': (255, 230, 186)},
         {'name': 'CHAT_RGB_PARTY', 'type': 'tuple', 'value': (0, 255, 228)},
         {'name': 'CHAT_RGB_SHOUT', 'type': 'tuple', 'value': (167, 255, 212)},
         {'name': 'CHAT_RGB_TALK', 'type': 'tuple', 'value': (255, 255, 255)},
         {'name': 'CHAT_RGB_WHISPER', 'type': 'tuple', 'value': (74, 225, 74)},
         {'name': 'CHR_NAME_RGB_EMPIRE_MOB', 'type': 'tuple', 'value': (235, 22, 9)},
         {'name': 'CHR_NAME_RGB_EMPIRE_NPC', 'type': 'tuple', 'value': (122, 231, 93)},
         {'name': 'CHR_NAME_RGB_EMPIRE_PC_A', 'type': 'tuple', 'value': (157, 0, 0)},
         {'name': 'CHR_NAME_RGB_EMPIRE_PC_B', 'type': 'tuple', 'value': (222, 160, 47)},
         {'name': 'CHR_NAME_RGB_EMPIRE_PC_C', 'type': 'tuple', 'value': (23, 30, 138)},
         {'name': 'CHR_NAME_RGB_MOB', 'type': 'tuple', 'value': (235, 22, 9)},
         {'name': 'CHR_NAME_RGB_NPC', 'type': 'tuple', 'value': (122, 231, 93)},
         {'name': 'CHR_NAME_RGB_PARTY', 'type': 'tuple', 'value': (128, 192, 255)},
         {'name': 'CHR_NAME_RGB_PC', 'type': 'tuple', 'value': (255, 215, 76)},
         {'name': 'CHR_NAME_RGB_PK', 'type': 'tuple', 'value': (180, 100, 0)},
         {'name': 'CHR_NAME_RGB_PVP', 'type': 'tuple', 'value': (238, 54, 223)},
         {'name': 'CHR_NAME_RGB_TARGET_VICTIM', 'type': 'tuple', 'value': (255, 0, 127)},
         {'name': 'CHR_NAME_RGB_WARP', 'type': 'tuple', 'value': (136, 218, 241)},
         {'name': 'CHR_NAME_RGB_WAYPOINT', 'type': 'tuple', 'value': (255, 255, 255)},
         {'name': 'TITLE_RGB_EVIL_1', 'type': 'tuple', 'value': (207, 117, 0)},
         {'name': 'TITLE_RGB_EVIL_2', 'type': 'tuple', 'value': (235, 83, 0)},
         {'name': 'TITLE_RGB_EVIL_3', 'type': 'tuple', 'value': (227, 0, 0)},
         {'name': 'TITLE_RGB_EVIL_4', 'type': 'tuple', 'value': (255, 0, 0)},
         {'name': 'TITLE_RGB_GOOD_1', 'type': 'tuple', 'value': (155, 155, 255)},
         {'name': 'TITLE_RGB_GOOD_2', 'type': 'tuple', 'value': (92, 110, 255)},
         {'name': 'TITLE_RGB_GOOD_3', 'type': 'tuple', 'value': (0, 144, 255)},
         {'name': 'TITLE_RGB_GOOD_4', 'type': 'tuple', 'value': (0, 204, 255)},
         {'name': 'TITLE_RGB_NORMAL', 'type': 'tuple', 'value': (255, 255, 255)},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'colorInfo'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
