{'class': [],
 'func': [{'args': ['vnum', 'subType'], 'defaults': [], 'name': 'GET_ACCESSORY_MATERIAL_VNUM'},
          {'args': ['vnum', 'subType'], 'defaults': [0], 'name': 'GET_BELT_MATERIAL_VNUM'},
          {'args': [], 'defaults': [], 'name': 'GET_CAMERA_MAX_DISTANCE_INDEX'},
          {'args': [], 'defaults': [], 'name': 'GET_CHRNAME_COLOR_INDEX'},
          {'args': [], 'defaults': [], 'name': 'GET_FOG_LEVEL_INDEX'},
          {'args': [], 'defaults': [], 'name': 'GET_ITEM_QUESTION_DIALOG_STATUS'},
          {'args': [], 'defaults': [], 'name': 'GET_VIEW_OTHER_EMPIRE_PLAYER_TARGET_BOARD'},
          {'args': ['itemVnum'], 'defaults': [], 'name': 'IS_AUTO_POTION'},
          {'args': ['itemVnum'], 'defaults': [], 'name': 'IS_AUTO_POTION_HP'},
          {'args': ['itemVnum'], 'defaults': [], 'name': 'IS_AUTO_POTION_SP'},
          {'args': ['itemVnum'], 'defaults': [], 'name': 'IS_PET_ITEM'},
          {'args': ['index'], 'defaults': [], 'name': 'SET_CAMERA_MAX_DISTANCE_INDEX'},
          {'args': ['index'], 'defaults': [], 'name': 'SET_CHRNAME_COLOR_INDEX'},
          {'args': [], 'defaults': [], 'name': 'SET_DEFAULT_CAMERA_MAX_DISTANCE'},
          {'args': [], 'defaults': [], 'name': 'SET_DEFAULT_CHRNAME_COLOR'},
          {'args': [], 'defaults': [], 'name': 'SET_DEFAULT_CONVERT_EMPIRE_LANGUAGE_ENABLE'},
          {'args': [], 'defaults': [], 'name': 'SET_DEFAULT_FOG_LEVEL'},
          {'args': [], 'defaults': [], 'name': 'SET_DEFAULT_USE_ITEM_WEAPON_TABLE_ATTACK_BONUS'},
          {'args': [], 'defaults': [], 'name': 'SET_DEFAULT_USE_SKILL_EFFECT_ENABLE'},
          {'args': ['index'], 'defaults': [], 'name': 'SET_FOG_LEVEL_INDEX'},
          {'args': ['flag'], 'defaults': [], 'name': 'SET_ITEM_QUESTION_DIALOG_STATUS'},
          {'args': [], 'defaults': [], 'name': 'SET_TWO_HANDED_WEAPON_ATT_SPEED_DECREASE_VALUE'},
          {'args': ['index'], 'defaults': [], 'name': 'SET_VIEW_OTHER_EMPIRE_PLAYER_TARGET_BOARD'}],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'chrmgrm2g', '__builtin__', 'item'],
 'var': [{'name': 'ACCESSORY_MATERIAL_LIST', 'type': 'list', 'value': [50623, 50624, 50625, 50626, 50627, 50628, 50629, 50630, 50631, 50632, 50633, 50634, 50635, 50636, 50637, 50638, 50639]},
         {'name': 'ADD_DEF_BONUS_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'ARMOR_SPECULAR_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'CAMERA_MAX_DISTANCE', 'type': 'float', 'value': 2500.0},
         {'name': 'CAMERA_MAX_DISTANCE_LIST', 'type': 'list', 'value': [2500.0, 3500.0]},
         {'name': 'CAMERA_MAX_DISTANCE_LONG', 'type': 'float', 'value': 3500.0},
         {'name': 'CAMERA_MAX_DISTANCE_SHORT', 'type': 'float', 'value': 2500.0},
         {'name': 'CHRNAME_COLOR_INDEX', 'type': 'int', 'value': 0},
         {'name': 'CONSOLE_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'CONVERT_EMPIRE_LANGUAGE_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'ENVIRONMENT_NIGHT', 'type': 'str', 'value': 'd:/ymir work/environment/moonlight04.msenv'},
         {'name': 'ERROR_METIN_STONE', 'type': 'int', 'value': 28960},
         {'name': 'EXPANDED_COMBO_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'FOG_LEVEL', 'type': 'float', 'value': 4800.0},
         {'name': 'FOG_LEVEL0', 'type': 'float', 'value': 4800.0},
         {'name': 'FOG_LEVEL1', 'type': 'float', 'value': 9600.0},
         {'name': 'FOG_LEVEL2', 'type': 'float', 'value': 12800.0},
         {'name': 'FOG_LEVEL_LIST', 'type': 'list', 'value': [4800.0, 9600.0, 12800.0]},
         {'name': 'GUILD_MONEY_PER_GSP', 'type': 'int', 'value': 100},
         {'name': 'GUILD_WAR_TYPE_SELECT_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'HAIR_COLOR_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'HIGH_PRICE', 'type': 'int', 'value': 500000},
         {'name': 'IN_GAME_SHOP_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'JewelAccessoryInfos', 'type': 'list', 'value': [[50634, 14420, 16220, 17220], [50635, 14500, 16500, 17500], [50636, 14520, 16520, 17520], [50637, 14540, 16540, 17540], [50638, 14560, 16560, 17560], [50639, 14570, 16570, 0]]},
         {'name': 'KEEP_ACCOUNT_CONNETION_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'LOGIN_COUNT_LIMIT_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'MIDDLE_PRICE', 'type': 'int', 'value': 50000},
         {'name': 'MINIMAP_POSITIONINFO_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'PVPMODE_ACCELKEY_DELAY', 'type': 'float', 'value': 0.5},
         {'name': 'PVPMODE_ACCELKEY_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'PVPMODE_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'PVPMODE_PROTECTED_LEVEL', 'type': 'int', 'value': 15},
         {'name': 'SEQUENCE_PACKET_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'SUB2_LOADING_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'TWO_HANDED_WEAPON_ATT_SPEED_DECREASE_VALUE', 'type': 'int', 'value': 10},
         {'name': 'USE_ITEM_WEAPON_TABLE_ATTACK_BONUS', 'type': 'int', 'value': 0},
         {'name': 'USE_SKILL_EFFECT_UPGRADE_ENABLE', 'type': 'int', 'value': 1},
         {'name': 'VIEW_OTHER_EMPIRE_PLAYER_TARGET_BOARD', 'type': 'int', 'value': 1},
         {'name': 'WEAPON_SPECULAR_ENABLE', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'constInfo'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'isItemQuestionDialog', 'type': 'int', 'value': 0}]}
