{'class': [],
 'func': [{'args': ['path'], 'defaults': [], 'name': 'RegisterEmotionAnis'}, {'args': [], 'defaults': [], 'name': 'RegisterEmotionIcons'}, {'args': [], 'defaults': [], 'name': 'ReloadEmotionDict'}, {'args': ['mode', 'path'], 'defaults': [], 'name': '__RegisterSharedEmotionAnis'}],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'chrmgrm2g', 'chr', 'localeInfo', '__builtin__'],
 'var': [{'name': 'ANI_DICT',
          'type': 'dict',
          'value': {306: 'clap.msa',
                    307: 'cheers_1.msa',
                    308: 'cheers_2.msa',
                    309: 'kiss_with_warrior.msa',
                    310: 'kiss_with_assassin.msa',
                    311: 'kiss_with_sura.msa',
                    312: 'kiss_with_shaman.msa',
                    313: 'kiss_with_wolfman.msa',
                    314: 'french_kiss_with_warrior.msa',
                    315: 'french_kiss_with_assassin.msa',
                    316: 'french_kiss_with_sura.msa',
                    317: 'french_kiss_with_shaman.msa',
                    318: 'french_kiss_with_wolfman.msa',
                    319: 'slap_hit.msa',
                    320: 'slap_hit.msa',
                    321: 'slap_hit.msa',
                    322: 'slap_hit.msa',
                    323: 'slap_hit.msa',
                    324: 'slap_hurt.msa',
                    325: 'slap_hurt.msa',
                    326: 'slap_hurt.msa',
                    327: 'slap_hurt.msa',
                    328: 'slap_hurt.msa',
                    330: 'dance_1.msa',
                    331: 'dance_2.msa',
                    332: 'dance_3.msa',
                    333: 'dance_4.msa',
                    334: 'dance_5.msa',
                    335: 'dance_6.msa',
                    347: 'congratulation.msa',
                    348: 'forgive.msa',
                    349: 'angry.msa',
                    350: 'attractive.msa',
                    351: 'sad.msa',
                    352: 'shy.msa',
                    353: 'cheerup.msa',
                    354: 'banter.msa',
                    355: 'joy.msa',
                    356: 'pushup.msa',
                    357: 'dance_7.msa',
                    358: 'exercise.msa',
                    359: 'doze.msa',
                    360: 'selfie.msa',
                    361: 'charging.msa',
                    362: 'nosay.msa',
                    363: 'weather1.msa',
                    364: 'weather2.msa',
                    365: 'weather3.msa',
                    366: 'hungry.msa',
                    367: 'siren.msa',
                    368: 'letter.msa',
                    369: 'call.msa',
                    370: 'celebration.msa',
                    371: 'alcohol.msa',
                    372: 'busy.msa',
                    373: 'whirl.msa'}},
         {'name': 'EMOTION_ALCOHOL', 'type': 'int', 'value': 116},
         {'name': 'EMOTION_ANGRY', 'type': 'int', 'value': 4},
         {'name': 'EMOTION_ATTRACTIVE', 'type': 'int', 'value': 5},
         {'name': 'EMOTION_BANTER', 'type': 'int', 'value': 9},
         {'name': 'EMOTION_BUSY', 'type': 'int', 'value': 117},
         {'name': 'EMOTION_CALL', 'type': 'int', 'value': 114},
         {'name': 'EMOTION_CELEBRATION', 'type': 'int', 'value': 115},
         {'name': 'EMOTION_CHARGING', 'type': 'int', 'value': 106},
         {'name': 'EMOTION_CHEERS_1', 'type': 'int', 'value': 11},
         {'name': 'EMOTION_CHEERS_2', 'type': 'int', 'value': 12},
         {'name': 'EMOTION_CHEERUP', 'type': 'int', 'value': 8},
         {'name': 'EMOTION_CLAP', 'type': 'int', 'value': 1},
         {'name': 'EMOTION_CONGRATULATION', 'type': 'int', 'value': 2},
         {'name': 'EMOTION_DANCE_1', 'type': 'int', 'value': 13},
         {'name': 'EMOTION_DANCE_2', 'type': 'int', 'value': 14},
         {'name': 'EMOTION_DANCE_3', 'type': 'int', 'value': 15},
         {'name': 'EMOTION_DANCE_4', 'type': 'int', 'value': 16},
         {'name': 'EMOTION_DANCE_5', 'type': 'int', 'value': 17},
         {'name': 'EMOTION_DANCE_6', 'type': 'int', 'value': 18},
         {'name': 'EMOTION_DANCE_7', 'type': 'int', 'value': 102},
         {'name': 'EMOTION_DICT',
          'type': 'dict',
          'value': {1: {'name': 'Taps', 'target': 0},
                    2: {'name': 'Gratul\xe1ci\xf3', 'target': 0},
                    3: {'name': 'Megbocs\xe1t\xe1s', 'target': 0},
                    4: {'name': 'M\xe9rges', 'target': 0},
                    5: {'name': 'Cs\xe1b\xedt\xe1s', 'target': 0},
                    6: {'name': 'Szomor\xfa', 'target': 0},
                    7: {'name': 'Elutas\xedt\xe1s', 'target': 0},
                    8: {'name': '\xdcnnepel', 'target': 0},
                    9: {'name': 'G\xfanyos', 'target': 0},
                    10: {'name': '\xd6r\xf6m', 'target': 0},
                    11: {'name': '\xdcnnepel 1', 'target': 0},
                    12: {'name': '\xdcnnepel 2', 'target': 0},
                    13: {'name': 'T\xe1nc 1', 'target': 0},
                    14: {'name': 'T\xe1nc 2', 'target': 0},
                    15: {'name': 'T\xe1nc 3', 'target': 0},
                    16: {'name': 'T\xe1nc 4', 'target': 0},
                    17: {'name': 'T\xe1nc 5', 'target': 0},
                    18: {'name': 'Gumsan Style', 'target': 0},
                    51: {'name': 'Cs\xf3k', 'target': 1},
                    52: {'name': 'Nyelves cs\xf3k', 'target': 1},
                    53: {'name': '\xdct\xe9s', 'target': 1},
                    101: {'name': 'Fekv\xf5t\xe1masz', 'target': 0},
                    102: {'name': 'Szamba', 'target': 0},
                    103: {'name': 'Bemeleg\xedt\xe9s', 'target': 0},
                    104: {'name': 'Elb\xf3biskol', 'target': 0},
                    105: {'name': 'Szelfi', 'target': 0},
                    106: {'name': 'T\xf6lt\xe9s', 'target': 0},
                    107: {'name': 'Sz\xf3hoz sem jut', 'target': 0},
                    108: {'name': 'Napsug\xe1r', 'target': 0},
                    109: {'name': 'Sziv\xe1rv\xe1ny', 'target': 0},
                    110: {'name': 'Hold', 'target': 0},
                    111: {'name': '\xc9hes', 'target': 0},
                    112: {'name': 'Szir\xe9na', 'target': 0},
                    113: {'name': 'Szerelmes lev\xe9l', 'target': 0},
                    114: {'name': 'H\xedv\xe1s', 'target': 0},
                    115: {'name': 'Parti', 'target': 0},
                    116: {'name': 'Eg\xe9szs\xe9gedre!', 'target': 0},
                    117: {'name': 'Stressz', 'target': 0},
                    118: {'name': 'Zavarodott', 'target': 0},
                    119: {'name': 'Sung Mahi tornya', 'target': 0}}},
         {'name': 'EMOTION_DOZE', 'type': 'int', 'value': 104},
         {'name': 'EMOTION_EXERCISE', 'type': 'int', 'value': 103},
         {'name': 'EMOTION_FORGIVE', 'type': 'int', 'value': 3},
         {'name': 'EMOTION_FRENCH_KISS', 'type': 'int', 'value': 52},
         {'name': 'EMOTION_HUNGRY', 'type': 'int', 'value': 111},
         {'name': 'EMOTION_JOY', 'type': 'int', 'value': 10},
         {'name': 'EMOTION_KISS', 'type': 'int', 'value': 51},
         {'name': 'EMOTION_LETTER', 'type': 'int', 'value': 113},
         {'name': 'EMOTION_NOSAY', 'type': 'int', 'value': 107},
         {'name': 'EMOTION_PUSH_UP', 'type': 'int', 'value': 101},
         {'name': 'EMOTION_SAD', 'type': 'int', 'value': 6},
         {'name': 'EMOTION_SELFIE', 'type': 'int', 'value': 105},
         {'name': 'EMOTION_SHY', 'type': 'int', 'value': 7},
         {'name': 'EMOTION_SIREN', 'type': 'int', 'value': 112},
         {'name': 'EMOTION_SLAP', 'type': 'int', 'value': 53},
         {'name': 'EMOTION_SMH', 'type': 'int', 'value': 119},
         {'name': 'EMOTION_WEATHER_1', 'type': 'int', 'value': 108},
         {'name': 'EMOTION_WEATHER_2', 'type': 'int', 'value': 109},
         {'name': 'EMOTION_WEATHER_3', 'type': 'int', 'value': 110},
         {'name': 'EMOTION_WHIRL', 'type': 'int', 'value': 118},
         {'name': 'ICON_DICT',
          'type': 'dict',
          'value': {1: 'd:/ymir work/ui/game/windows/emotion_clap.sub',
                    2: 'icon/action/congratulation.tga',
                    3: 'icon/action/forgive.tga',
                    4: 'icon/action/angry.tga',
                    5: 'icon/action/attractive.tga',
                    6: 'icon/action/sad.tga',
                    7: 'icon/action/shy.tga',
                    8: 'icon/action/cheerup.tga',
                    9: 'icon/action/banter.tga',
                    10: 'icon/action/joy.tga',
                    11: 'd:/ymir work/ui/game/windows/emotion_cheers_1.sub',
                    12: 'd:/ymir work/ui/game/windows/emotion_cheers_2.sub',
                    13: 'icon/action/dance1.tga',
                    14: 'icon/action/dance2.tga',
                    15: 'icon/action/dance3.tga',
                    16: 'icon/action/dance4.tga',
                    17: 'icon/action/dance5.tga',
                    18: 'icon/action/dance6.tga',
                    51: 'd:/ymir work/ui/game/windows/emotion_kiss.sub',
                    52: 'd:/ymir work/ui/game/windows/emotion_french_kiss.sub',
                    53: 'd:/ymir work/ui/game/windows/emotion_slap.sub',
                    101: 'icon/action/pushup.tga',
                    102: 'icon/action/dance7.tga',
                    103: 'icon/action/exercise.tga',
                    104: 'icon/action/doze.tga',
                    105: 'icon/action/selfie.tga',
                    106: 'icon/action/charging.tga',
                    107: 'icon/action/nosay.tga',
                    108: 'icon/action/weather1.tga',
                    109: 'icon/action/weather2.tga',
                    110: 'icon/action/weather3.tga',
                    111: 'icon/action/hungry.tga',
                    112: 'icon/action/siren.tga',
                    113: 'icon/action/letter.tga',
                    114: 'icon/action/call.tga',
                    115: 'icon/action/celebration.tga',
                    116: 'icon/action/alcohol.tga',
                    117: 'icon/action/busy.tga',
                    118: 'icon/action/whirl.tga',
                    119: 'icon/action/sungmahee_tower.tga'}},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'emotion'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
