{'class': [{'class': [],
            'func': [{'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'ActivateSkillSlot'},
                     {'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'ActivateSlot'},
                     {'args': ['self', 'type', 'idx'], 'defaults': [], 'name': 'AddExchangeItemSlotIndex'},
                     {'args': ['self', 'add', 'type', 'time', 'value'], 'defaults': [], 'name': 'AddMistsIslandMessage'},
                     {'args': ['self', 'byType', 'dwDuration'], 'defaults': [], 'name': 'AddSpecialActionSlot'},
                     {'args': ['self', 'answer'], 'defaults': [], 'name': 'AnswerGuildInvite'},
                     {'args': ['self', 'answer'], 'defaults': [], 'name': 'AnswerPartyInvite'},
                     {'args': ['self', 'type', 'chattype'], 'defaults': [], 'name': 'AppendChat'},
                     {'args': ['self', 'vnum', 'count'], 'defaults': [], 'name': 'AppendMaterialToRefineDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'AskGuildName'},
                     {'args': ['self'], 'defaults': [], 'name': 'AskMallPassword'},
                     {'args': ['self'], 'defaults': [], 'name': 'AskSafeboxPassword'},
                     {'args': ['self', 'emotionIndex'], 'defaults': [], 'name': 'BINARY_ActEmotion'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'BINARY_AppendNotifyMessage'},
                     {'args': ['self', 'isEnable', 'isButtonShow'], 'defaults': [], 'name': 'BINARY_BettingGuildWar_SetObserverMode'},
                     {'args': ['self', 'observerCount'], 'defaults': [], 'name': 'BINARY_BettingGuildWar_UpdateObserverCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_CleanMissionMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_Cube_Close'},
                     {'args': ['self', 'npcVNUM'], 'defaults': [], 'name': 'BINARY_Cube_Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_Cube_Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_DragonSoulGiveQuilification'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'BINARY_DragonSoulRefineWindow_Open'},
                     {'args': ['self', 'reason', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'BINARY_DragonSoulRefineWindow_RefineFail'},
                     {'args': ['self', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'BINARY_DragonSoulRefineWindow_RefineSucceed'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'BINARY_GuildWar_OnEnd'},
                     {'args': ['self', 'guildID', 'warType', 'winType', 'ScoreType', 'TimeType', 'DeclearTargetName'], 'defaults': [], 'name': 'BINARY_GuildWar_OnRecvDeclare'},
                     {'args': ['self', 'gainGuildID', 'opponentGuildID', 'point', 'winpoint'], 'defaults': [], 'name': 'BINARY_GuildWar_OnRecvPoint'},
                     {'args': ['self', 'guildID'], 'defaults': [], 'name': 'BINARY_GuildWar_OnSendDeclare'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'BINARY_GuildWar_OnStart'},
                     {'args': ['self', 'areaID'], 'defaults': [], 'name': 'BINARY_Guild_EnterGuildArea'},
                     {'args': ['self', 'areaID'], 'defaults': [], 'name': 'BINARY_Guild_ExitGuildArea'},
                     {'args': ['self', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'BINARY_Highlight_Item'},
                     {'args': ['self', 'name', 'lovePoint'], 'defaults': [], 'name': 'BINARY_LoverInfo'},
                     {'args': ['self', 'type', 'pointIdx', 'value', 'duration'], 'defaults': [], 'name': 'BINARY_NEW_AddAffect'},
                     {'args': ['self', 'type', 'pointIdx'], 'defaults': [], 'name': 'BINARY_NEW_RemoveAffect'},
                     {'args': ['self', 'type', 'point_type', 'value', 'duration'], 'defaults': [], 'name': 'BINARY_NEW_UpdateAffect'},
                     {'args': ['self', 'msg', 'timeout', 'pid'], 'defaults': [], 'name': 'BINARY_OnQuestConfirm'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_OpenAtlasWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_OpenSelectItemWindowEx'},
                     {'args': ['self', 'vid', 'text', 'type'], 'defaults': [], 'name': 'BINARY_PrivateShop_Appear'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'BINARY_PrivateShop_Disappear'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_RefreshChatWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_RefreshSelectItemWindowEx'},
                     {'args': ['self', 'line'], 'defaults': [], 'name': 'BINARY_ServerCommand_Run'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': 'BINARY_SetBigControlMessage'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': 'BINARY_SetBigMessage'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'BINARY_SetEnvironment'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': 'BINARY_SetMissionMessage'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': 'BINARY_SetSubMissionMessage'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': 'BINARY_SetTipMessage'},
                     {'args': ['self', 'str', 'hp', 'move', 'immune'], 'defaults': [], 'name': 'BINARY_SungMaAttr'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'BINARY_UpdateLovePoint'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BNWProcess'},
                     {'args': ['self', 'category', 'type', 'data'], 'defaults': [None], 'name': 'BattleRoyaleProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelGuildName'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'CatchKingProcess'},
                     {'args': ['self', 'skillSlotNumber'], 'defaults': [], 'name': 'ChangeCurrentSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangePKMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckFocus'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearAffects'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'ClientTimerProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGemShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGuildBuildingDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseTargetBoard'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'CloseTargetBoardIfDifferent'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseGuildBank'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseMall'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseSafebox'},
                     {'args': ['self'], 'defaults': [], 'name': 'ConfirmGuildName'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'DeactivateSkillSlot'},
                     {'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'DeactivateSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteGuild'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteMainCharacter'},
                     {'args': ['self', 'url', 'onoff'], 'defaults': [], 'name': 'DutchAuctionWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndExchange'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndShop'},
                     {'args': ['self', 'item_vnum', 'msg', 'enough_count'], 'defaults': [], 'name': 'ExInvenItemUseMsg'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'ExitBattleField'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'ExitBattleFieldOnDead'},
                     {'args': ['self'], 'defaults': [], 'name': 'ExitParty'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'FlowerEventProcess'},
                     {'args': ['self', 'slotindex', 'enable'], 'defaults': [], 'name': 'GemShopSlotAdd'},
                     {'args': ['self', 'slotindex', 'enable'], 'defaults': [], 'name': 'GemShopSlotBuy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Gift_Show'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'GuildProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide12ziTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideClock'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideName'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'HidewWndGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitSkillCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'LanguageChange'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MailBoxProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameAttendanceRequestRewardList'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'MiniGameAttendanceSetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameEnd'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'MiniGameRumiSetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'MonsterCardAchievRefresh'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MonsterCardIllustrationFail'},
                     {'args': ['self'], 'defaults': [], 'name': 'MonsterCardIllustrationRefresh'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MonsterCardMissionFail'},
                     {'args': ['self', 'cashItem', 'tabCnt'], 'defaults': [], 'name': 'MyPrivShopOpen'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'NextBeadUpdateTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAcceptAddFriend'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'OnBlockMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCannotMining'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCannotPickItem'},
                     {'args': ['self', 'vid', 'type'], 'defaults': [], 'name': 'OnCannotShotError'},
                     {'args': ['self', 'vid', 'type'], 'defaults': [], 'name': 'OnCannotUseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangePKMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseAddFriendQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDenyAddFriend'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnFishingFailure'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnFishingGameStart'},
                     {'args': ['self', 'isFish', 'fishName'], 'defaults': [], 'name': 'OnFishingNotify'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnFishingNotifyUnknown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnFishingStopGame'},
                     {'args': ['self', 'isFish', 'fishName'], 'defaults': [], 'name': 'OnFishingSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnFishingWrongPlace'},
                     {'args': ['self', 'openDlg', 'mapidx'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDown'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyUp'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'OnMessengerAddFriendQuestion'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseMiddleButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseMiddleButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseRightButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseRightButtonUp'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'OnPickBattlePoint'},
                     {'args': ['self', 'cheque'], 'defaults': [], 'name': 'OnPickCheque'},
                     {'args': ['self', 'gem'], 'defaults': [], 'name': 'OnPickGem'},
                     {'args': ['self', 'medal_of_honor'], 'defaults': [], 'name': 'OnPickMedalOfHonor'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnPickMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self', 'mode', 'name', 'line'], 'defaults': [], 'name': 'OnRecvWhisper'},
                     {'args': ['self', 'mode', 'name', 'line'], 'defaults': [], 'name': 'OnRecvWhisperError'},
                     {'args': ['self', 'mode', 'name', 'line'], 'defaults': [], 'name': 'OnRecvWhisperSystemMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnSafeBoxError'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OnShopError'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'open'], 'defaults': [], 'name': 'OpenElectricFieldOnScreenImage'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'OpenEquipmentDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGemShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildBankInfo'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'OpenGuildBankWindow'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OpenGuildDragonLairRanking'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': 'OpenGuildGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenKeyChangeWindow'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'OpenMallWindow'},
                     {'args': ['self', 'time', 'mapIdx'], 'defaults': [], 'name': 'OpenMiniBossTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenPShopSearchDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenPShopSearchDialogCash'},
                     {'args': ['self', 'skin', 'idx'], 'defaults': [], 'name': 'OpenQuestWindow'},
                     {'args': ['self', 'type', 'category'], 'defaults': [], 'name': 'OpenRankingBoard'},
                     {'args': ['self', 'targetItemPos', 'nextGradeItemVnum', 'cost', 'prob', 'type', 'apply_random_list', 'src_vnum'], 'defaults': [], 'name': 'OpenRefineDialog'},
                     {'args': ['self', 'mapidx'], 'defaults': [], 'name': 'OpenRestartDialog'},
                     {'args': ['self', 'vid', 'itemcount'], 'defaults': [], 'name': 'OpenReviveDialog'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'OpenSafeboxWindow'},
                     {'args': ['self', 'vid', 'window_type', 'slotIdx'], 'defaults': [], 'name': 'OpenSelectAttrDialog'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OpenSkillbookCombinationDialog'},
                     {'args': ['self', 'yellowmark', 'greenmark', 'yellowreward', 'greenreward', 'goldreward'], 'defaults': [], 'name': 'OpenUI12zi'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'OpenUserSituationShow'},
                     {'args': ['self', 'type', 'state'], 'defaults': [], 'name': 'OpenWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'PartyHealReady'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'PartyMatchResult'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'PartyProcess'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'PassiveAttrProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'PetAffectShowerRefresh'},
                     {'args': ['self', 'slotIndex', 'byType'], 'defaults': [], 'name': 'PetAttrChangeResult'},
                     {'args': ['self', 'byType'], 'defaults': [], 'name': 'PetAttrDetermineResult'},
                     {'args': ['self', 'index', 'value'], 'defaults': [], 'name': 'PetEvolInfo'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'PetFeedReuslt'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'PetFlashEvent'},
                     {'args': ['self', 'command', 'window', 'pos'], 'defaults': [], 'name': 'PetHatchingWindowCommand'},
                     {'args': ['self', 'command', 'srcWindow', 'srcPos', 'dstWindow', 'dstPos'], 'defaults': [], 'name': 'PetNameChangeWindowCommand'},
                     {'args': ['self', 'slot', 'index', 'gold'], 'defaults': [], 'name': 'PetSkillUpgradeDlgOpen'},
                     {'args': ['self', 'msg', 'message_type'], 'defaults': [None], 'name': 'PopupMessage'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'PremiumPrivateShopProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReciveMission'},
                     {'args': ['self', 'guildID', 'guildName'], 'defaults': [], 'name': 'RecvGuildInviteQuestion'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RecvWhisper'},
                     {'args': ['self', 'type', 'refine_type', 'data'], 'defaults': [], 'name': 'RefineElementProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefineFailedMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefineSuceededMessage'},
                     {'args': ['self', 'currentFloor', 'jumpCount', 'limitTime', 'elapseTime'], 'defaults': [], 'name': 'Refresh12ziTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAcceWindow'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'RefreshAccumulateCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAlignment'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshEquipment'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshExchange'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGemShopWIndow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBank'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBankInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPageBankGold'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBoardPage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'RefreshGuildDragonLairRanking'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageGradeComboBox'},
                     {'args': ['self', 'issearch'], 'defaults': [], 'name': 'RefreshGuildRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildWarInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshInGameEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMall'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMessenger'},
                     {'args': ['self', 'type', 'time', 'hp', 'maxCount', 'count', 'gemPoint', 'gemCount'], 'defaults': [], 'name': 'RefreshMiniBossInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMissionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshPShopSearchDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshPassiveAttrJobSlot'},
                     {'args': ['self', 'quest_type', 'quest_index'], 'defaults': [], 'name': 'RefreshQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSafebox'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSafeboxMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshShopItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStamina'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RefreshTargetBoardByName'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'RefreshTargetBoardByVID'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshUserSituation'},
                     {'args': ['self', 'iIndex'], 'defaults': [], 'name': 'RemoveQuickSlotIndex'},
                     {'args': ['self', 'affectType'], 'defaults': [], 'name': 'RemoveSetItemAffect'},
                     {'args': ['self', 'iIndex'], 'defaults': [], 'name': 'RemoveSpecialActionSlot'},
                     {'args': ['self', 'answer'], 'defaults': [], 'name': 'RequestDropItem'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'ResetAffect'},
                     {'args': ['self', 'coin_type'], 'defaults': [], 'name': 'ResetUsablePoint'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'RouletteProcess'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'src_pos', 'src_index', 'src_color', 'src_number', 'dst_pos', 'dst_index', 'dst_color', 'dst_number'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self', 'slotIndex', 'coolTime'], 'defaults': [], 'name': 'RunUseSkillEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'SafeboxChangePassword'},
                     {'args': ['self'], 'defaults': [], 'name': 'SaveScreen'},
                     {'args': ['self'], 'defaults': [], 'name': 'ScrollOnOff'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'SetAffect'},
                     {'args': ['self', 'slotindex', 'cooltime'], 'defaults': [], 'name': 'SetAutoCooltime'},
                     {'args': ['self', 'leftOpen', 'leftEnd'], 'defaults': [], 'name': 'SetBattleFieldLeftTime'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'SetBeadCount'},
                     {'args': ['self', 'vid', 'slotIndex', 'attrIndex', 'type', 'value'], 'defaults': [], 'name': 'SetEquipmentDialogAttr'},
                     {'args': ['self', 'vid', 'slotIndex', 'vnum', 'count', 'dwChangeLookVnum', 'refine_element', 'apply_random_list', 'setValue'], 'defaults': [], 'name': 'SetEquipmentDialogItem'},
                     {'args': ['self', 'vid', 'slotIndex', 'socketIndex', 'value'], 'defaults': [], 'name': 'SetEquipmentDialogSocket'},
                     {'args': ['self', 'second'], 'defaults': [], 'name': 'SetGuildDragonLairFistGuildText'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGuildDragonLiarStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGuildDragonLiarSuccess'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self', 'vid', 'hp', 'hpMax'], 'defaults': [], 'name': 'SetHPAllianceTargetBoard'},
                     {'args': ['self', 'vid', 'hpPercentage'], 'defaults': [], 'name': 'SetHPTargetBoard'},
                     {'args': ['self', 'temple', 'score', 'rank', 'end_time'], 'defaults': [], 'name': 'SetMistsIslandInfo'},
                     {'args': ['self', 'vid', 'name'], 'defaults': [], 'name': 'SetPCTargetBoard'},
                     {'args': ['self', 'pet_window_type'], 'defaults': [], 'name': 'SetPetWindowType'},
                     {'args': ['self', 'Price'], 'defaults': [], 'name': 'SetShopSellingPrice'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show12ziJumpButton'},
                     {'args': ['self', 'second'], 'defaults': [], 'name': 'ShowClock'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowConsole'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowCostumeInventory'},
                     {'args': ['self', 'dwItemVnum', 'byItemCount', 'iNeedMoney', 'wSlotIndex'], 'defaults': [], 'name': 'ShowLuckyBoxWindow'},
                     {'args': ['self', 'mapName', 'x', 'y'], 'defaults': [], 'name': 'ShowMapName'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowName'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowQuestButton'},
                     {'args': ['self', 'element_enchants_dict'], 'defaults': [], 'name': 'ShowTargetElementEnchant'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'ShowWndGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartExchange'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartGame'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartPointReset'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'StartShop'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'SungmaheeTowerProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleDebugInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDebugInfo'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'WorldBossProcess'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'YutnoriProcess'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__2017RamaDanEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceAbsorbDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceCombineDialog'},
                     {'args': ['self', 'answer'], 'defaults': [], 'name': '__AnswerPartyRequest'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoLoginOff'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoOff'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoOn'},
                     {'args': ['self', 'enable', 'start', 'end'], 'defaults': [], 'name': '__BattleFieldEventInfo'},
                     {'args': ['self', 'open'], 'defaults': [], 'name': '__BattleFieldEventOpen'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__BattleFieldInfo'},
                     {'args': ['self', 'open'], 'defaults': [], 'name': '__BattleFieldOpen'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__BattleRoyale'},
                     {'args': ['self'], 'defaults': [], 'name': '__BuildDebugInfo'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__ChangeWindowOpen'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckRedDragonLairRanking'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__Check_Guild_War'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearApplicant'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearApplicantGuild'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearGuildRanking'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearGuildRedDragonLairRanking'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseGuildDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__Console_Enable'},
                     {'args': ['self'], 'defaults': [], 'name': '__DayMode_OnCompleteChangeToDark'},
                     {'args': ['self'], 'defaults': [], 'name': '__DayMode_OnCompleteChangeToLight'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__DayMode_Update'},
                     {'args': ['self', 'attachedType', 'attachedItemIndex', 'attachedItemSlotPos', 'attachedItemCount'], 'defaults': [], 'name': '__DropItem'},
                     {'args': ['self', 'attachedType', 'attachedMoney'], 'defaults': [], 'name': '__DropMoney'},
                     {'args': ['self'], 'defaults': [], 'name': '__EnableTestServerFlag'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__FishEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__FlowerEvent'},
                     {'args': ['self', 'state', 'running_time', 'map_index', 'pos_x', 'pos_y', 'interval_sec'], 'defaults': [], 'name': '__GuildSiteAuctionNotice'},
                     {'args': ['self', 'abndon_time', 'interval_sec'], 'defaults': [], 'name': '__GuildSiteTaxInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__GuildWar_CloseAskDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__GuildWar_OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__GuildWar_OnDecline'},
                     {'args': ['self', 'guildID', 'warType', 'winType', 'ScoreType', 'TimeType'], 'defaults': [], 'name': '__GuildWar_OpenAskDialog'},
                     {'args': ['self', 'guildID1', 'memberCount1', 'guildID2', 'memberCount2', 'observerCount'], 'defaults': [], 'name': '__GuildWar_UpdateMemberCount'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__Halloween_Box'},
                     {'args': ['self'], 'defaults': [], 'name': '__Horse_HideState'},
                     {'args': ['self', 'level', 'health', 'battery'], 'defaults': [], 'name': '__Horse_UpdateState'},
                     {'args': ['self', 'url'], 'defaults': [], 'name': '__InGameShop_Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsShowName'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsXMasMap'},
                     {'args': ['self'], 'defaults': [], 'name': '__ItemCombinationDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__ItemMall_Open'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__LateSummerEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoginLover'},
                     {'args': ['self'], 'defaults': [], 'name': '__LogoutLover'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoverDivorce'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoverFar'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoverNear'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniBossDungeon'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameBNW'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameCatchKing'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameOkey'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameOkeyNormal'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameYutnori'},
                     {'args': ['slef', 'enable'], 'defaults': [], 'name': '__MistsIsland'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MonsterBack'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__NotifyError'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenAttr67AddDlg'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__OpenAuraWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenMyShopDecoWnd'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__PRESERVE_DayMode_Update'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__PartyMatchOff'},
                     {'args': ['self'], 'defaults': [], 'name': '__PartyRequestDenied'},
                     {'args': ['self', 'vid', 'name'], 'defaults': [], 'name': '__PartyRequestQuestion'},
                     {'args': ['self', 'flag', 'filename'], 'defaults': [], 'name': '__PlayMusic'},
                     {'args': ['self'], 'defaults': [], 'name': '__ProcessPreservedServerCommand'},
                     {'args': ['self', 'attachedType', 'attachedItemIndex', 'attachedItemSlotPos', 'attachedItemCount', 'dstChrID'], 'defaults': [], 'name': '__PutItem'},
                     {'args': ['self', 'attachedType', 'attachedMoney', 'dstChrID', 'cheque'], 'defaults': [], 'name': '__PutMoney'},
                     {'args': ['self', 'OnOff'], 'defaults': [], 'name': '__PvPOnOff'},
                     {'args': ['self', 'OnOff'], 'defaults': [], 'name': '__PvPTournamentAutoSet'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': '__RefineFailedTypeMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefineSoulFailedMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefineSoulSuceededMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshTargetBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__RestartDialog_Close'},
                     {'args': ['self', 'pageIndex'], 'defaults': [], 'name': '__SelectQuickPage'},
                     {'args': ['self', 'itemVNum', 'itemCount', 'itemInvenType'], 'defaults': [1], 'name': '__SendDropItemPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__ServerCommand_Build'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__SetCreate'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetEnvironment'},
                     {'args': ['self', 'channelNumber', 'mapIndex'], 'defaults': [], 'name': '__SeverInfo'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__SummerEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__ThreeWay_SafeZone_Enable'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__ValentineEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__WorldBoss'},
                     {'args': ['self'], 'defaults': [], 'name': '__XMasBoom_Boom'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__XMasBoom_Enable'},
                     {'args': ['self'], 'defaults': [], 'name': '__XMasBoom_Update'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__XMasSnow_Enable'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__XMasSong_Enable'},
                     {'args': ['self', 'grade'], 'defaults': [], 'name': '__XMasTree_Enable'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'game'}, {'name': '__qualname__', 'type': 'str', 'value': 'GameWindow'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['chatm2g',
            'app',
            'uiPrivateShopBuilder',
            'dbg',
            'm2netm2g',
            'playerm2g2',
            'battleRoyaleMgr',
            'skill',
            'uiMapNameShower',
            'constInfo',
            'grp',
            'uiPhaseCurtain',
            'interfaceModule',
            'chr',
            'systemSetting',
            'chrmgrm2g',
            'messenger',
            'mouseModule',
            'uiTarget',
            'uiKeyChange',
            'musicInfo',
            'localeInfo',
            'uiCommon',
            'snd',
            'consoleModule',
            'exchange',
            '__builtin__',
            'uiGuildPopup',
            'effect',
            'ime',
            'quest',
            'playerSettingModule',
            'background',
            'wndMgr',
            'uiAffectShower',
            'guild',
            'textTail',
            'debugInfo',
            'uiCharacter',
            'item',
            'uiPlayerGauge',
            'ui',
            'stringCommander',
            'os',
            'uiGuildBank'],
 'var': [{'name': 'REFINE_FAIL_DEL_ITEM', 'type': 'int', 'value': 1},
         {'name': 'REFINE_FAIL_GRADE_DOWN', 'type': 'int', 'value': 0},
         {'name': 'REFINE_FAIL_KEEP_GRADE', 'type': 'int', 'value': 2},
         {'name': 'REFINE_FAIL_MAX', 'type': 'int', 'value': 3},
         {'name': 'SCREENSHOT_CWDSAVE', 'type': 'bool', 'value': True},
         {'name': 'SCREENSHOT_DIR', 'type': 'NoneType', 'value': None},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'game'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'cameraDistance', 'type': 'float', 'value': 1550.0},
         {'name': 'cameraHeight', 'type': 'float', 'value': 100.0},
         {'name': 'cameraPitch', 'type': 'float', 'value': 27.0},
         {'name': 'cameraRotation', 'type': 'float', 'value': 0.0},
         {'name': 'testAlignment', 'type': 'int', 'value': 0}]}
