{'class': [{'class': [],
            'func': [{'args': ['self', 'type'], 'defaults': [], 'name': 'AcceDialogOpen'},
                     {'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'ActivateSlot'},
                     {'args': ['self', 'type', 'idx'], 'defaults': [], 'name': 'AddExchangeItemSlotIndex'},
                     {'args': ['self', 'pid', 'name', 'mapIdx', 'channel'], 'defaults': [], 'name': 'AddPartyMember'},
                     {'args': ['self', 'byType', 'dwDuration'], 'defaults': [], 'name': 'AddSpecialActionSlot'},
                     {'args': ['self', 'vid', 'text', 'type'], 'defaults': [], 'name': 'AppearPrivateShop'},
                     {'args': ['self', 'vnum', 'count'], 'defaults': [], 'name': 'AppendMaterialToRefineDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'AskMallPassword'},
                     {'args': ['self'], 'defaults': [], 'name': 'AskSafeboxPassword'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': 'AttachInvenItemToOtherWindowSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Attendance'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'AuraDialogOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'AutoOff'},
                     {'args': ['self'], 'defaults': [], 'name': 'AutoOn'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_OpenAtlasWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_OpenSelectItemWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_OpenSelectItemWindowEx'},
                     {'args': ['self'], 'defaults': [], 'name': 'BINARY_RefreshSelectItemWindowEx'},
                     {'args': ['self', 'flag', 'isbuttonshow'], 'defaults': [], 'name': 'BINARY_SetObserverMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'BUILD_CloseWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'BUILD_OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'BUILD_OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'BUILD_OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'BUILD_OpenWindow'},
                     {'args': ['self', 'areaID'], 'defaults': [], 'name': 'BULID_EnterGuildArea'},
                     {'args': ['self', 'areaID'], 'defaults': [], 'name': 'BULID_ExitGuildArea'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'CatchKingProcess'},
                     {'args': ['self', 'distributionMode'], 'defaults': [], 'name': 'ChangePartyParameter'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'ChangeWindowOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseCubeWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseDlgQuestionWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseDragonSoulRefineWindow'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'CloseEquipmentDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseFishingGameWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGemShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGuildRankWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseHelpWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePointResetDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePrivateShopInputNameDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseRestartDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseShopDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseWbWindow'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'CloseWhisperDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseGuildBank'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseMall'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseSafebox'},
                     {'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'DeactivateSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteGuild'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteMainCharacter'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'DisappearPrivateShop'},
                     {'args': ['self', 'deck'], 'defaults': [], 'name': 'DragonSoulActivate'},
                     {'args': ['self'], 'defaults': [], 'name': 'DragonSoulDeactivate'},
                     {'args': ['self'], 'defaults': [], 'name': 'DragonSoulGiveQuilification'},
                     {'args': ['self', 'deck'], 'defaults': [], 'name': 'DragonSoulKeySelect'},
                     {'args': ['self', 'grade'], 'defaults': [], 'name': 'DragonSoulSetGrade'},
                     {'args': ['self', 'url', 'onoff'], 'defaults': [], 'name': 'DutchAuctionWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EmptyFunction'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndExchange'},
                     {'args': ['self', 'item_vnum', 'msg', 'enough_count'], 'defaults': [], 'name': 'ExInvenItemUseMsg'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'ExitBattleField'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'ExitBattleFieldOnDead'},
                     {'args': ['self'], 'defaults': [], 'name': 'ExitParty'},
                     {'args': ['self', 'reason', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'FailDragonSoulRefine'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'FindMProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'FishingCannotOpenChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'FishingHitEffect'},
                     {'args': ['self', 'mouseX', 'mouseY'], 'defaults': [], 'name': 'FishingMissEffect'},
                     {'args': ['self', 'x', 'y', 'delay'], 'defaults': [], 'name': 'FishingWaveEffect'},
                     {'args': ['self', 'slotindex', 'enable'], 'defaults': [], 'name': 'GemShopSlotAdd'},
                     {'args': ['self', 'slotindex', 'enable'], 'defaults': [], 'name': 'GemShopSlotBuy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetAutoStartonoff'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetDragonLairType'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetOnTopWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide12ziTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAllQuestButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAllWhisperButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAllWindows'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideGuildWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideMiniMapInGameEventButton'},
                     {'args': ['self', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'Highligt_Item'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsEditLineFocus'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'IsGameMasterName'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsHideUiMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpenChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShowDlgQuestionWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ItemCombinationDialogOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'LanguageChange'},
                     {'args': ['self', 'pid', 'vid', 'mapIdx', 'channel'], 'defaults': [], 'name': 'LinkPartyMember'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MailBoxProcess'},
                     {'args': ['self', 'hyperlink'], 'defaults': [], 'name': 'MakeHyperlinkTooltip'},
                     {'args': ['self'], 'defaults': [], 'name': 'MakeInterface'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'MakeWhisperButton'},
                     {'args': ['self', 'onTopWnd', 'index'], 'defaults': [], 'name': 'MarkUnusableDSInvenSlotOnTopWnd'},
                     {'args': ['self', 'onTopWnd', 'InvenSlot'], 'defaults': [], 'name': 'MarkUnusableInvenSlotOnTopWnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameAttendanceRequestRewardList'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'MiniGameAttendanceSetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameEnd'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameOkey'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'MiniGameRumiSetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameStart'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MiniMapMailProcess'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'MinimizeWhisperDialog'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MonsterCardIllustrationFail'},
                     {'args': ['self'], 'defaults': [], 'name': 'MonsterCardIllustrationRefresh'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MonsterCardMissionFail'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'NextBeadUpdateTime'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'OnBlockMode'},
                     {'args': ['self', 'skillSlotNumber'], 'defaults': [], 'name': 'OnChangeCurrentSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangePKMode'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnEndGuildWar'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self', 'gainGuildID', 'opponentGuildID', 'point', 'winpoint'], 'defaults': [], 'name': 'OnRecvGuildWarPoint'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnStartGuildWar'},
                     {'args': ['self', 'slotIndex', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenAttr67AddDlg'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenCharacterWindowQuestPage'},
                     {'args': ['self', 'state'], 'defaults': [], 'name': 'OpenCharacterWindowWithState'},
                     {'args': ['self', 'npcVnum'], 'defaults': [], 'name': 'OpenCubeWindow'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OpenDragonSoulRefineWindow'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'OpenEquipmentDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenFishingGameWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGemShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildBankInfo'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'OpenGuildBankWindow'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OpenGuildDragonLairRanking'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': 'OpenGuildGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildScoreWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenHelpWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenItemMall'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'OpenMallWindow'},
                     {'args': ['self', 'time', 'mapIdx'], 'defaults': [], 'name': 'OpenMiniBossTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenMyShopDecoWnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenPShopSearchDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenPShopSearchDialogCash'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenPointResetDialog'},
                     {'args': ['self', 'bCashItem', 'tabCnt'], 'defaults': [], 'name': 'OpenPrivateShopBuilder'},
                     {'args': ['self', 'bCashItem', 'tabCnt'], 'defaults': [], 'name': 'OpenPrivateShopInputNameDialog'},
                     {'args': ['self', 'skin', 'idx'], 'defaults': [], 'name': 'OpenQuestWindow'},
                     {'args': ['self', 'type', 'category'], 'defaults': [], 'name': 'OpenRankingBoardWindow'},
                     {'args': ['self', 'targetItemPos', 'nextGradeItemVnum', 'cost', 'prob', 'type'], 'defaults': [], 'name': 'OpenRefineDialog'},
                     {'args': ['self', 'mapidx'], 'defaults': [], 'name': 'OpenRestartDialog'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'OpenSafeboxWindow'},
                     {'args': ['self', 'vid', 'window_type', 'slotIdx'], 'defaults': [], 'name': 'OpenSelectAttrDialog'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'OpenShopDialog'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OpenSkillbookCombinationDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenSystemDialog'},
                     {'args': ['self', 'yellowmark', 'greenmark', 'yellowreward', 'greenreward', 'goldreward'], 'defaults': [], 'name': 'OpenUI12zi'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'OpenUserSituationShow'},
                     {'args': ['self', 'url'], 'defaults': [], 'name': 'OpenWebWindow'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'OpenWhisperDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenWhisperDialogWithoutTarget'},
                     {'args': ['self'], 'defaults': [], 'name': 'PartyHealReady'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'PartyMatchOff'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'PartyMatchResult'},
                     {'args': ['self'], 'defaults': [], 'name': 'PetAffectShowerRefresh'},
                     {'args': ['self', 'slotIndex', 'byType'], 'defaults': [], 'name': 'PetAttrChangeResult'},
                     {'args': ['self', 'byType'], 'defaults': [], 'name': 'PetAttrDetermineResult'},
                     {'args': ['self', 'index', 'value'], 'defaults': [], 'name': 'PetEvolInfo'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'PetFeedReuslt'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'PetFlashEvent'},
                     {'args': ['self', 'command', 'window', 'pos'], 'defaults': [], 'name': 'PetHatchingWindowCommand'},
                     {'args': ['self', 'affect_shower'], 'defaults': [], 'name': 'PetInfoBindAffectShower'},
                     {'args': ['self'], 'defaults': [], 'name': 'PetInformationActivate'},
                     {'args': ['self', 'command', 'srcWindow', 'srcPos', 'dstWindow', 'dstPos'], 'defaults': [], 'name': 'PetNameChangeWindowCommand'},
                     {'args': ['self', 'slot', 'index', 'gold'], 'defaults': [], 'name': 'PetSkillUpgradeDlgOpen'},
                     {'args': ['self', 'OnOff'], 'defaults': [], 'name': 'PvPTournamentAutoSet'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReciveMission'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RecvWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefrashBattleButton'},
                     {'args': ['self', 'currentFloor', 'jumpCount', 'limitTime', 'elapseTime'], 'defaults': [], 'name': 'Refresh12ziTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAcceWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAlignment'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAutoPositionSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAutoSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCubeWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshExchange'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGemShopWIndow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBank'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBankInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPageBankGold'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBoardPage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'RefreshGuildDragonLairRanking'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageGradeComboBox'},
                     {'args': ['self', 'issearch'], 'defaults': [], 'name': 'RefreshGuildRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildWarInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshInGameEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMall'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMarkInventoryBag'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMessenger'},
                     {'args': ['self', 'type', 'time', 'hp', 'maxCount', 'count', 'gemPoint', 'gemCount'], 'defaults': [], 'name': 'RefreshMiniBossInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMissionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshPShopSearchDialog'},
                     {'args': ['self', 'quest_type', 'quest_index'], 'defaults': [], 'name': 'RefreshQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSafebox'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSafeboxMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshServerInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshShopDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshShopItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStamina'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshUserSituation'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RegisterGameMasterName'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RegisterTemporaryWhisperDialog'},
                     {'args': ['self', 'pid'], 'defaults': [], 'name': 'RemovePartyMember'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'RemoveQuestDialog'},
                     {'args': ['self', 'iIndex'], 'defaults': [], 'name': 'RemoveQuickSlotIndex'},
                     {'args': ['self', 'iIndex'], 'defaults': [], 'name': 'RemoveSpecialActionSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetUsedBP'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'RouletteProcess'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self'], 'defaults': [], 'name': 'SafeboxChangePassword'},
                     {'args': ['self', 'dir', 'event'], 'defaults': [], 'name': 'SelectMouseButtonEvent'},
                     {'args': ['self', 'shower'], 'defaults': [], 'name': 'SetAffectShower'},
                     {'args': ['self', 'targetBoard'], 'defaults': [], 'name': 'SetAllianceTargetBoard'},
                     {'args': ['self', 'slotindex', 'cooltime'], 'defaults': [], 'name': 'SetAutoCooltime'},
                     {'args': ['self', 'leftOpen', 'leftEnd'], 'defaults': [], 'name': 'SetBattleFieldLeftTime'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'SetBeadCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChatFocus'},
                     {'args': ['self', 'vid', 'slotIndex', 'attrIndex', 'type', 'value'], 'defaults': [], 'name': 'SetEquipmentDialogAttr'},
                     {'args': ['self', 'vid', 'slotIndex', 'vnum', 'count', 'dwChangeLookVnum'], 'defaults': [], 'name': 'SetEquipmentDialogItem'},
                     {'args': ['self', 'vid', 'slotIndex', 'socketIndex', 'value'], 'defaults': [], 'name': 'SetEquipmentDialogSocket'},
                     {'args': ['self', 'second'], 'defaults': [], 'name': 'SetGuildDragonLairFistGuildText'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGuildDragonLiarStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGuildDragonLiarSuccess'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self', 'mapName'], 'defaults': [], 'name': 'SetMapName'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOkeyNormalBG'},
                     {'args': ['self', 'onTopWnd'], 'defaults': [], 'name': 'SetOnTopWindow'},
                     {'args': ['self', 'pet_window_type'], 'defaults': [], 'name': 'SetPetWindowType'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetUpWndMiniGame'},
                     {'args': ['self', 'bUse'], 'defaults': [], 'name': 'SetUseItemMode'},
                     {'args': ['self', 'targetBoard'], 'defaults': [], 'name': 'SettargetBoard'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show12ziJumpButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAllQuestButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAllWhisperButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAllWindows'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowCostumeInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowDefaultWindows'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowGift'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowGuildWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowInGameEvent'},
                     {'args': ['self', 'dwItemVnum', 'byItemCount', 'iNeedMoney', 'wSlotIndex'], 'defaults': [], 'name': 'ShowLuckyBoxWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowMiniMapInGameEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowQuestButton'},
                     {'args': ['self', 'btn'], 'defaults': [], 'name': 'ShowWhisperDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartExchange'},
                     {'args': ['self', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'SucceedDragonSoulRefine'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleAutoWindow'},
                     {'args': ['self', 'state'], 'defaults': [], 'name': 'ToggleCharacterWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleCharacterWindowStatusPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleChatLogWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleDragonSoulWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleDragonSoulWindowWithNoInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleExpandedButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleExpandedMoneyButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleGuildWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleHelpWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleInventoryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleMessenger'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleMiniMap'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleMonsterCardWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'TogglePartyMatchWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'TogglePetInformationWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleSystemDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'UnlinkAllPartyMember'},
                     {'args': ['self', 'pid'], 'defaults': [], 'name': 'UnlinkPartyMember'},
                     {'args': ['self', 'gulidID1', 'memberCount1', 'guildID2', 'memberCount2'], 'defaults': [], 'name': 'UpdateMemberCount'},
                     {'args': ['self', 'pid'], 'defaults': [], 'name': 'UpdatePartyMemberInfo'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'YutnoriProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeQuestButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeWhisperButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__CheckGameMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickQuestButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseGuildDialog'},
                     {'args': ['self', 'button'], 'defaults': [], 'name': '__DestroyWhisperButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__FindWhisperButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideWindows'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsChatOpen'},
                     {'args': ['self'], 'defaults': [], 'name': '__Make12ziRewardWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__Make12ziTimerWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBeadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeChatWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeCubeWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeDialogs'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeDutchWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeGameButtonWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeGuildWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeHelpWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeItemSelectWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeItemSelectWindowEx'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeMessengerWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeParty'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeQuestButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeTaskBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeTipBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeUICurtain'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeWebWindow'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__MakeWhisperButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__MakeWhisperDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeWindows'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickBuildButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickHelpButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickQuestButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSkillPlusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickStatusPlusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshQuestButton'},
                     {'args': ['self', 'wnds'], 'defaults': [], 'name': '__ShowWindows'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CHARACTER_SKILL_TAB', 'type': 'int', 'value': 2},
                    {'name': 'CHARACTER_STATUS_TAB', 'type': 'int', 'value': 1},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'Interface' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'interfaceModule'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'Interface'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'Interface' objects>}]}],
 'func': [],
 'import': ['shop',
            'uiBattleField',
            'miniMap',
            'uiDutchAuction',
            'uiNewInventory',
            'uiCommon',
            'chatm2g',
            'app',
            'uiFishingGame',
            'uiPrivateShopBuilder',
            'uiGameButton',
            'uiMyShopDecoration',
            'uiPrivateShop',
            'playerm2g2',
            'uiAcce',
            'uiRefine',
            'uiPrivateShopSearch',
            'ranking',
            'uiSelectAttr',
            'event',
            'uiRestart',
            'systemSetting',
            'constInfo',
            'uiSkillBookCombination',
            'uiDragonSoul',
            'uiselectitem',
            'uiInventory',
            'uiToolTip',
            'uiEquipmentDialog',
            'uiShop',
            'uiParty',
            'uiMessenger',
            'uiSystem',
            'uiChat',
            'uiMonsterCard',
            'uiGemShop',
            'uiScriptLocale',
            'uiSafebox',
            'localeInfo',
            'uiMailBox',
            'uiHelp',
            'uiQuest',
            'uiItemCombination',
            '__builtin__',
            'uiAuto',
            'uiCubeRenewal',
            'quest',
            'uiTip',
            'uiWhisper',
            'wndMgr',
            'uiPetInfo',
            'uiMiniMap',
            'uiExchange',
            'uiRankingBoard',
            'uiMiniGame',
            'uiAttr67Add',
            'uiLuckyBox',
            'guild',
            'uiGuild',
            'uiTaskBar',
            'uiGuildDragonLairRanking',
            'uiUserSituationNotice',
            'm2netm2g',
            'item',
            'uiPartyMatch',
            'uiChangeLook',
            'ui',
            'uiGuildBank',
            'uiMiniBossDungeon',
            'uiselectitemEx',
            'uiCharacter',
            'uiPointReset',
            'ui12zi',
            'uiAura'],
 'var': [{'name': 'IsQBHide', 'type': 'int', 'value': 0}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'interfaceModule'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
