{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introCreate'}, {'name': '__qualname__', 'type': 'str', 'value': 'CreateCharacterWindow.DescriptionBox'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introCreate'}, {'name': '__qualname__', 'type': 'str', 'value': 'CreateCharacterWindow.CharacterRenderer'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CancelCreate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CreateCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'DisableWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EmptyFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'EnableWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetSlotIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OnCreateFailure'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCreateSuccess'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': 'OverInStatButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutStatButton'},
                     {'args': ['self', 'msg', 'func'], 'defaults': [0], 'name': 'PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStat'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetStat'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__CheckCreateCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': '__DecreaseSlotIndex'},
                     {'args': ['self', 'page', 'slot'], 'defaults': [], 'name': '__GetSlotChrID'},
                     {'args': ['self'], 'defaults': [], 'name': '__IncreaseSlotIndex'},
                     {'args': ['self', 'page', 'slot', 'race'], 'defaults': [], 'name': '__MakeCharacter'},
                     {'args': ['self', 'gender'], 'defaults': [], 'name': '__SelectGender'},
                     {'args': ['self', 'shape'], 'defaults': [], 'name': '__SelectShape'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': '__SelectSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CREATE_STAT_POINT', 'type': 'int', 'value': 0},
                    {'name': 'DESCRIPTION_FILE_NAME', 'type': 'tuple', 'value': ('locale/br/jobdesc_warrior.txt', 'locale/br/jobdesc_assassin.txt', 'locale/br/jobdesc_sura.txt', 'locale/br/jobdesc_shaman.txt', 'locale/br/jobdesc_wolfman.txt')},
                    {'name': 'SLOT_ROTATION', 'type': 'tuple', 'value': ([135.0, 207.0, 279.0, 351.0, 63.0], [135.0, 225.0, 315.0, 45.0])},
                    {'name': 'START_STAT', 'type': 'tuple', 'value': ([4, 3, 6, 3], [3, 3, 4, 6], [3, 5, 5, 3], [4, 6, 3, 3], [6, 2, 2, 6], [4, 3, 6, 3], [3, 3, 4, 6], [3, 5, 5, 3], [4, 6, 3, 3])},
                    {'name': 'STAT_CON', 'type': 'int', 'value': 0},
                    {'name': 'STAT_DESCRIPTION', 'type': 'dict', 'value': {0: 'Aumenta HP, Defesa e Resist\xeancia.', 1: 'Aumenta MP, Atq. M\xe1gico e Prot. M\xe1gica.', 2: 'Aumenta o Ataque.', 3: 'Aumenta os \xedndices de acerto e evas\xe3o. '}},
                    {'name': 'STAT_DEX', 'type': 'int', 'value': 3},
                    {'name': 'STAT_INT', 'type': 'int', 'value': 1},
                    {'name': 'STAT_STR', 'type': 'int', 'value': 2},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'introCreate'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'CreateCharacterWindow'}]}],
 'func': [],
 'import': ['app', 'playerSettingModule', 'm2netm2g', 'networkModule', 'event', 'grp', 'uiToolTip', 'systemSetting', 'chr', 'uiScriptLocale', 'ui', 'localeInfo', 'math', 'snd', '__builtin__', 'wndMgr', 'musicInfo'],
 'var': [{'name': 'BASE_CHR_ID', 'type': 'int', 'value': 3},
         {'name': 'LOCALE_PATH', 'type': 'str', 'value': 'uiscript/1252_'},
         {'name': 'MAN', 'type': 'int', 'value': 0},
         {'name': 'PAGE_COUNT', 'type': 'int', 'value': 2},
         {'name': 'SHAPE0', 'type': 'int', 'value': 0},
         {'name': 'SHAPE1', 'type': 'int', 'value': 1},
         {'name': 'SLOT_COUNT', 'type': 'list', 'value': [5, 4]},
         {'name': 'WOMAN', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'introCreate'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
