{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseVideo'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadNextVideo'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introLogo'}, {'name': '__qualname__', 'type': 'str', 'value': 'LogoWindow'}, {'name': 'videoList', 'type': 'list', 'value': []}]}],
 'func': [],
 'import': ['snd', '__builtin__', 'app', 'uiScriptLocale', 'm2netm2g', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'introLogo'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
