{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClickExitButton'}, {'args': ['self'], 'defaults': [], 'name': 'ClickSelectButton'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introEmpire'}, {'name': '__qualname__', 'type': 'str', 'value': 'ReselectEmpireWindow'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introEmpire'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectEmpireWindow.DescriptionBox'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}, {'args': ['self', 'owner', 'arg'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introEmpire'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectEmpireWindow.EmpireButton'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClickExitButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickLeftButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickRightButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnOverInEmpire'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnOverOutEmpire'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnSelectEmpire'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateButtons'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDescriptionBox'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self', 'dict', 'curAlphaDict', 'destAlphaDict'], 'defaults': [], 'name': '__UpdateAlpha'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'EMPIRE_DESCRIPTION_TEXT_FILE_NAME', 'type': 'dict', 'value': {1: 'locale/br/empiredesc_a.txt', 2: 'locale/br/empiredesc_b.txt', 3: 'locale/br/empiredesc_c.txt'}},
                    {'name': 'EMPIRE_NAME', 'type': 'dict', 'value': {1: 'Shinsu', 2: 'Chunjo', 3: 'Jinno'}},
                    {'name': 'EMPIRE_NAME_COLOR', 'type': 'dict', 'value': {1: (0.745, 0, 0), 2: (0.8666, 0.6156, 0.1843), 3: (0.2235, 0.2549, 0.749)}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'introEmpire'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SelectEmpireWindow'}]}],
 'func': [],
 'import': ['event', '_weakref', 'snd', 'musicInfo', 'uiToolTip', '__builtin__', 'app', 'uiScriptLocale', 'dbg', 'systemSetting', 'm2netm2g', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': 'LOCALE_PATH', 'type': 'str', 'value': 'uiscript/1252_'}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'introEmpire'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
