{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introSelect'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectCharacterWindow.CharacterRenderer'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptInputName'},
                     {'args': ['self'], 'defaults': [], 'name': 'AcceptInputPrivateCode'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelInputName'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelInputPrivateCode'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CreateCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'DecreaseSlotIndex'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'DeleteCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'EmptyFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'ExitSelect'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'GetCharacterSlotID'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetSlotIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAllFlag'},
                     {'args': ['self'], 'defaults': [], 'name': 'IncreaseSlotIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitCharacterBoard'},
                     {'args': ['self'], 'defaults': [], 'name': 'InputPrivateCode'},
                     {'args': ['self', 'index', 'id', 'name', 'race', 'form', 'hair', 'acce'], 'defaults': [], 'name': 'MakeCharacter'},
                     {'args': ['self', 'id', 'name'], 'defaults': [], 'name': 'OnChangeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OnCreateFailure'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDeleteFailure'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'OnDeleteSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenChangeNameDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'PopupDeleteQuestion'},
                     {'args': ['self', 'msg', 'func'], 'defaults': [0], 'name': 'PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'RequestDeleteCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'SameLoginDisconnect'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectSlot'},
                     {'args': ['self', 'id'], 'defaults': [], 'name': 'SetEmpire'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartGame'},
                     {'args': ['self'], 'defaults': [], 'name': '__AreAllSlotEmpty'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadBoardDialog'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CHARACTER_TYPE_COUNT', 'type': 'int', 'value': 5},
                    {'name': 'EMPIRE_NAME', 'type': 'dict', 'value': {1: 'Shinsoo-Reich', 2: 'Chunjo-Reich', 3: 'Jinno-Reich'}},
                    {'name': 'SLOT_COUNT', 'type': 'int', 'value': 5},
                    {'name': 'SLOT_ROTATION', 'type': 'list', 'value': [135.0, 207.0, 279.0, 351.0, 63.0]},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'introSelect'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SelectCharacterWindow'}]}],
 'func': [],
 'import': ['uiNewInventory',
            'uiTarget',
            'app',
            'playerSettingModule',
            'm2netm2g',
            'networkModule',
            'uiMapNameShower',
            'grp',
            'uiInventory',
            'interfaceModule',
            'systemSetting',
            'chr',
            'uiScriptLocale',
            'ui',
            'localeInfo',
            'math',
            'uiCommon',
            'snd',
            'consoleModule',
            '__builtin__',
            'uiPlayerGauge',
            'wndMgr',
            'uiAffectShower',
            'uiTaskBar',
            'musicInfo',
            'uiCharacter'],
 'var': [{'name': 'ENABLE_ENGNUM_DELETE_CODE', 'type': 'bool', 'value': True},
         {'name': 'LEAVE_BUTTON_FOR_POTAL', 'type': 'bool', 'value': False},
         {'name': 'NOT_NEED_DELETE_CODE', 'type': 'bool', 'value': False},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'introSelect'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
