{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'playerX', 'playerY'], 'defaults': [], 'name': 'DEBUG_LoadData'},
                     {'args': ['self', 'playerX', 'playerY'], 'defaults': [], 'name': 'LoadData'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitData'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadAssassin'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadEnemy'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadGuildBuilding'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadMap'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadNPC'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadShaman'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadSkill'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadSound'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadSura'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWarrior'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWolfman'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterColor'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterDungeonMapName'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterEmotionIcon'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterSkill'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterTitleName'},
                     {'args': ['self', 'next'], 'defaults': [], 'name': '__SetNext'},
                     {'args': ['self', 'p'], 'defaults': [], 'name': '__SetProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartGame'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'introLoading'}, {'name': '__qualname__', 'type': 'str', 'value': 'LoadingWindow'}]}],
 'func': [],
 'import': ['emotion',
            'app',
            'dbg',
            'uiPickMoney',
            'm2netm2g',
            'playerm2g2',
            'uiRefine',
            'uiRestart',
            'constInfo',
            'uiToolTip',
            'uiShop',
            'uiAttachMetin',
            'uiMessenger',
            'uiSystem',
            'chrmgrm2g',
            'uiScriptLocale',
            'colorInfo',
            'ui',
            'localeInfo',
            'uiHelp',
            'uiOption',
            '__builtin__',
            'uiChat',
            'playerSettingModule',
            'background',
            'wndMgr',
            'uiExchange',
            'stringCommander',
            'uiPointReset',
            'uiWhisper'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'introLoading'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
