{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CancelEnterGame'},
                     {'args': ['self'], 'defaults': [], 'name': 'Connect'},
                     {'args': ['self'], 'defaults': [], 'name': 'Create'},
                     {'args': ['self'], 'defaults': [], 'name': 'CreatePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'EmptyFunction'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetConnectAddr'},
                     {'args': ['self'], 'defaults': [], 'name': 'SameLogin_SetLoginPhase'},
                     {'args': ['self', 'addr', 'port', 'account_addr', 'account_port'], 'defaults': [0, 0], 'name': 'SetConnectInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetCreateCharacterPhase'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGamePhase'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetLoadingPhase'},
                     {'args': ['self', 'id', 'pwd'], 'defaults': [], 'name': 'SetLoginInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetLoginPhase'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetLogoPhase'},
                     {'args': ['self', 'newPhaseWindow'], 'defaults': [], 'name': 'SetPhaseWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetReselectEmpirePhase'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetSelectCharacterPhase'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetSelectEmpirePhase'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'SetTestGamePhase'},
                     {'args': ['self'], 'defaults': [], 'name': '__ChangePhaseWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['original_function'], 'defaults': [], 'name': 'multi_language_decorator_setphase'}],
            'import': [],
            'var': [{'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'MainStream' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'networkModule'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MainStream'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'MainStream' objects>},
                    {'name': 'isChrData', 'type': 'int', 'value': 0}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'message_type'], 'defaults': [], 'name': 'CloseMessageType'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'Message', 'event', 'ButtonName', 'message_type'], 'defaults': [0, 'Cancelar', None], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'networkModule'}, {'name': '__qualname__', 'type': 'str', 'value': 'PopupDialog'}]}],
 'func': [{'args': ['wrapped', 'assigned', 'updated'], 'defaults': [('__module__', '__name__', '__doc__'), ('__dict__',)], 'name': 'wraps'}],
 'import': ['snd', '__builtin__', 'app', 'm2netm2g', 'dbg', 'uiPhaseCurtain', 'chr', 'playerm2g2', 'ui', 'playerSettingModule', 'background', 'chrmgrm2g', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'networkModule'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
