{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetUnitData'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'const_id', 'name', 'level', 'race', 'playtime', 'guildname', 'form', 'hair', 'acce', 'stat_str', 'stat_dex', 'stat_hth', 'stat_int', 'change_name'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'New_introSelect'}, {'name': '__qualname__', 'type': 'str', 'value': 'MyCharacters.MyUnit'}]}],
            'func': [{'args': ['self', 'slot'], 'defaults': [], 'name': 'GetChangeName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetEmptySlot'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'GetGuildNamePlayTime'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'GetJob'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMyCharacterCount'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'GetRace'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'GetStatPoint'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadCharacterData'},
                     {'args': ['self', 'slot', 'name', 'race', 'form', 'hair', 'acce'], 'defaults': [], 'name': 'MakeCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshData'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'SetChangeNameSuccess'},
                     {'args': ['self', 'last_playtime'], 'defaults': [], 'name': 'SetPriorityData'},
                     {'args': ['self', 'slot', 'race', 'guildname', 'playtime', 'pStr', 'pDex', 'pHth', 'pInt', 'changename'], 'defaults': [], 'name': 'SetSortingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'New_introSelect'}, {'name': '__qualname__', 'type': 'str', 'value': 'MyCharacters'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'New_introSelect'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectCharacterWindow.DescriptionBox'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'New_introSelect'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectCharacterWindow.CharacterRenderer'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptInputName'},
                     {'args': ['self'], 'defaults': [], 'name': 'AcceptInputPrivateCode'},
                     {'args': ['self'], 'defaults': [], 'name': 'All_ButtonInfoHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelInputName'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelInputPrivateCode'},
                     {'args': ['self', 'slot', 'name'], 'defaults': [], 'name': 'ChangeNameButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CreateCharacterButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'DisableWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EmptyFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'EnableWindow'},
                     {'args': ['self', 'event_type', 'slot'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'ExitButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'GetCharacterSlotPID'},
                     {'args': ['self', 'slot', 'name', 'level', 'real_slot'], 'defaults': [], 'name': 'InitDataSet'},
                     {'args': ['self'], 'defaults': [], 'name': 'InputPrivateCode'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'KeyInputUpDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self', 'slot', 'name'], 'defaults': [], 'name': 'OnChangeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OnCreateFailure'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDeleteFailure'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'OnDeleteSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenChangeNameDialog'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipETC'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'msg', 'func'], 'defaults': [0], 'name': 'PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStat'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetStat'},
                     {'args': ['self'], 'defaults': [], 'name': 'SameLoginDisconnect'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'SelectButton'},
                     {'args': ['self', 'empire_id'], 'defaults': [], 'name': 'SetEmpire'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetIllustrationInit'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESCRIPTION_FILE_NAME', 'type': 'tuple', 'value': ('locale/de/jobdesc_warrior.txt', 'locale/de/jobdesc_assassin.txt', 'locale/de/jobdesc_sura.txt', 'locale/de/jobdesc_shaman.txt', 'locale/de/jobdesc_wolfman.txt')},
                    {'name': 'DISC_FACE_PATH',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/bin/icon/face/warrior_m.tga',
                               1: 'd:/ymir work/bin/icon/face/assassin_w.tga',
                               2: 'd:/ymir work/bin/icon/face/sura_m.tga',
                               3: 'd:/ymir work/bin/icon/face/shaman_w.tga',
                               4: 'd:/ymir work/bin/icon/face/warrior_w.tga',
                               5: 'd:/ymir work/bin/icon/face/assassin_m.tga',
                               6: 'd:/ymir work/bin/icon/face/sura_w.tga',
                               7: 'd:/ymir work/bin/icon/face/shaman_m.tga',
                               8: 'd:/ymir work/bin/icon/face/wolfman_m.tga'}},
                    {'name': 'EMPIRE_NAME', 'type': 'dict', 'value': {1: 'Shinsoo-Reich', 2: 'Chunjo-Reich', 3: 'Jinno-Reich'}},
                    {'name': 'EMPIRE_NAME_COLOR', 'type': 'dict', 'value': {1: (0.745, 0, 0), 2: (0.8666, 0.6156, 0.1843), 3: (0.2235, 0.2549, 0.749)}},
                    {'name': 'JOB_LIST', 'type': 'dict', 'value': {0: 'Krieger', 1: 'Ninja', 2: 'Sura', 3: 'Schamane', 4: 'Lykaner'}},
                    {'name': 'RACE_FACE_PATH',
                     'type': 'dict',
                     'value': {0: 'D:/ymir work/ui/intro/public_intro/face/face_warrior_m_0',
                               1: 'D:/ymir work/ui/intro/public_intro/face/face_assassin_w_0',
                               2: 'D:/ymir work/ui/intro/public_intro/face/face_sura_m_0',
                               3: 'D:/ymir work/ui/intro/public_intro/face/face_shaman_w_0',
                               4: 'D:/ymir work/ui/intro/public_intro/face/face_warrior_w_0',
                               5: 'D:/ymir work/ui/intro/public_intro/face/face_assassin_m_0',
                               6: 'D:/ymir work/ui/intro/public_intro/face/face_sura_w_0',
                               7: 'D:/ymir work/ui/intro/public_intro/face/face_shaman_m_0',
                               8: 'D:/ymir work/ui/intro/public_intro/face/face_wolfman_m_0'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'New_introSelect'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SelectCharacterWindow'}]}],
 'func': [],
 'import': ['uiNewInventory',
            'uiTarget',
            'app',
            'playerSettingModule',
            'm2netm2g',
            'networkModule',
            'event',
            'uiMapNameShower',
            'grp',
            'uiInventory',
            'uiToolTip',
            'systemSetting',
            'chr',
            'uiScriptLocale',
            'musicInfo',
            'localeInfo',
            'uiCommon',
            'snd',
            'consoleModule',
            '__builtin__',
            'uiPlayerGauge',
            'wndMgr',
            'uiAffectShower',
            'uiTaskBar',
            'ui',
            'uiCharacter',
            'interfaceModule'],
 'var': [{'name': 'ENABLE_ENGNUM_DELETE_CODE', 'type': 'bool', 'value': True},
         {'name': 'JOB_ASSASSIN', 'type': 'int', 'value': 1},
         {'name': 'JOB_SHAMAN', 'type': 'int', 'value': 3},
         {'name': 'JOB_SURA', 'type': 'int', 'value': 2},
         {'name': 'JOB_WARRIOR', 'type': 'int', 'value': 0},
         {'name': 'JOB_WOLFMAN', 'type': 'int', 'value': 4},
         {'name': 'M2_INIT_VALUE', 'type': 'int', 'value': -1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'New_introSelect'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
