{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'New_introCreate'}, {'name': '__qualname__', 'type': 'str', 'value': 'CreateCharacterWindow.DescriptionBox'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'New_introCreate'}, {'name': '__qualname__', 'type': 'str', 'value': 'CreateCharacterWindow.CharacterRenderer'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CancelButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'CheckCreateCharacterName'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CreateCharacterButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'DisableWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EmptyFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'EnableWindow'},
                     {'args': ['self', 'event_type', 'slot'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': 'MakeCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'OnCreateFailure'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCreateSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'msg', 'func'], 'defaults': [0], 'name': 'PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStat'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetStat'},
                     {'args': ['self', 'gender'], 'defaults': [], 'name': 'SelectGender'},
                     {'args': ['self', 'job_id'], 'defaults': [], 'name': 'SelectJob'},
                     {'args': ['self', 'shape'], 'defaults': [], 'name': 'SelectShape'},
                     {'args': ['self', 'empire_id'], 'defaults': [], 'name': 'SetEmpire'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'stream'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESCRIPTION_FILE_NAME', 'type': 'tuple', 'value': ('locale/hu/jobdesc_warrior.txt', 'locale/hu/jobdesc_assassin.txt', 'locale/hu/jobdesc_sura.txt', 'locale/hu/jobdesc_shaman.txt', 'locale/hu/jobdesc_wolfman.txt')},
                    {'name': 'DISC_FACE_PATH',
                     'type': 'dict',
                     'value': {0: 'icon/face/warrior_m.tga', 1: 'icon/face/assassin_w.tga', 2: 'icon/face/sura_m.tga', 3: 'icon/face/shaman_w.tga', 4: 'icon/face/warrior_w.tga', 5: 'icon/face/assassin_m.tga', 6: 'icon/face/sura_w.tga', 7: 'icon/face/shaman_m.tga', 8: 'icon/face/wolfman_m.tga'}},
                    {'name': 'EMPIRE_NAME', 'type': 'dict', 'value': {1: 'Shinsoo birodalom', 2: 'Chunjo birodalom', 3: 'Jinno birodalom'}},
                    {'name': 'EMPIRE_NAME_COLOR', 'type': 'dict', 'value': {1: (0.745, 0, 0), 2: (0.8666, 0.6156, 0.1843), 3: (0.2235, 0.2549, 0.749)}},
                    {'name': 'LEN_JOBLIST', 'type': 'int', 'value': 5},
                    {'name': 'LEN_STATPOINT', 'type': 'int', 'value': 4},
                    {'name': 'M2JOBLIST', 'type': 'dict', 'value': {0: 'Harcos', 1: 'Nindzsa', 2: 'Sura', 3: 'S\xe1m\xe1n', 4: 'V\xe9rfarkas'}},
                    {'name': 'M2STATPOINT', 'type': 'tuple', 'value': ((4, 3, 6, 3), (3, 3, 4, 6), (3, 5, 5, 3), (4, 6, 3, 3), (6, 2, 2, 6))},
                    {'name': 'M2_CONST_ID', 'type': 'tuple', 'value': ((0, 4), (5, 1), (2, 6), (7, 3), (8, -1))},
                    {'name': 'M2_INIT_VALUE', 'type': 'int', 'value': -1},
                    {'name': 'RACE_FACE_PATH',
                     'type': 'dict',
                     'value': {0: 'D:/ymir work/ui/intro/public_intro/face/face_warrior_m_0',
                               1: 'D:/ymir work/ui/intro/public_intro/face/face_assassin_w_0',
                               2: 'D:/ymir work/ui/intro/public_intro/face/face_sura_m_0',
                               3: 'D:/ymir work/ui/intro/public_intro/face/face_shaman_w_0',
                               4: 'D:/ymir work/ui/intro/public_intro/face/face_warrior_w_0',
                               5: 'D:/ymir work/ui/intro/public_intro/face/face_assassin_m_0',
                               6: 'D:/ymir work/ui/intro/public_intro/face/face_sura_w_0',
                               7: 'D:/ymir work/ui/intro/public_intro/face/face_shaman_m_0',
                               8: 'D:/ymir work/ui/intro/public_intro/face/face_wolfman_m_0'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'New_introCreate'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'CreateCharacterWindow'}]}],
 'func': [],
 'import': ['app', 'playerSettingModule', 'm2netm2g', 'networkModule', 'event', 'grp', 'uiToolTip', 'systemSetting', 'chr', 'uiScriptLocale', 'musicInfo', 'localeInfo', 'snd', '__builtin__', 'wndMgr', 'ui'],
 'var': [{'name': 'MAN', 'type': 'int', 'value': 0},
         {'name': 'WOMAN', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'New_introCreate'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
