{'class': [{'class': [],
            'func': [{'args': ['self', 'line'], 'defaults': [], 'name': 'BINARY_ServerCommand_Run'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'Guild_War_Check'},
                     {'args': ['self'], 'defaults': [], 'name': 'PassGuildCommand'},
                     {'args': ['self'], 'defaults': [], 'name': 'PassGuildDragonCommand'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__2017RamaDanEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__AutoOff'},
                     {'args': ['self', 'enable', 'start', 'end'], 'defaults': [], 'name': '__BattleFieldEventInfo'},
                     {'args': ['self', 'open'], 'defaults': [], 'name': '__BattleFieldEventOpen'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__BattleFieldInfo'},
                     {'args': ['self', 'open'], 'defaults': [], 'name': '__BattleFieldOpen'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__BattleRoyale'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__DayMode_Update'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__FishEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__FlowerEvent'},
                     {'args': ['self', 'state', 'running_time', 'map_index', 'pos_x', 'pos_y', 'interval_sec'], 'defaults': [], 'name': '__GuildSiteAuctionNotice'},
                     {'args': ['self', 'abndon_time', 'interval_sec'], 'defaults': [], 'name': '__GuildSiteTaxInfo'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__Halloween_box_event'},
                     {'args': ['self'], 'defaults': [], 'name': '__ItemMall_Open'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__LateSummerEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniBossDungeon'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameBNW'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameCatchKing'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameOkeyEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameOkeyNormalEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MiniGameYutnori'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MistsIsland'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__MonsterBack'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__PartyMatchOff'},
                     {'args': ['self', 'line'], 'defaults': [], 'name': '__PreserveCommand'},
                     {'args': ['self'], 'defaults': [], 'name': '__ServerCommand_Build'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__SummerEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__ValentineEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': '__WorldBoss'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__XMasBoom_Enable'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__XMasSnow_Enable'},
                     {'args': ['self', 'grade'], 'defaults': [], 'name': '__XMasTree_Enable'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'ServerCommandParser' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'serverCommandParser'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ServerCommandParser'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'ServerCommandParser' objects>}]}],
 'func': [],
 'import': ['constInfo', '__builtin__', 'app', 'm2netm2g', 'stringCommander', 'background', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'serverCommandParser'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'parserWnd', 'type': 'ServerCommandParser', 'value': <serverCommandParser.ServerCommandParser object at 0x0AAB7330>}]}
