{'class': [{'class': [],
            'func': [{'args': ['self', 'line'], 'defaults': [], 'name': 'Run'}, {'args': ['self', 'cmd', 'callBackFunc'], 'defaults': [], 'name': 'SAFE_RegisterCallBack'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'stringCommander'}, {'name': '__qualname__', 'type': 'str', 'value': 'Analyzer'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': '__call__'}, {'args': ['self', 'cls', 'obj', 'func'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'stringCommander'}, {'name': '__qualname__', 'type': 'str', 'value': 'CallBackFunction.__noarg_call__'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': '__call__'}, {'args': ['self', 'cls', 'obj', 'func'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'stringCommander'}, {'name': '__qualname__', 'type': 'str', 'value': 'CallBackFunction.__arg_call__'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetArgumentCount'}, {'args': ['self'], 'defaults': [], 'name': '__call__'}, {'args': ['self', 'mfunc'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'stringCommander'}, {'name': '__qualname__', 'type': 'str', 'value': 'CallBackFunction'}]}],
 'func': [],
 'import': ['__builtin__', '_weakref'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'stringCommander'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
