{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}, {'args': ['self'], 'defaults': [], 'name': 'restore'}, {'args': ['self'], 'defaults': [], 'name': 'show'}, {'args': ['self', 'msg'], 'defaults': [], 'name': 'write'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'system'}, {'name': '__qualname__', 'type': 'str', 'value': 'LogBoxFile'}]},
           {'class': [],
            'func': [{'args': ['self', 'packfile'], 'defaults': [], 'name': '__init__'}, {'args': ['self'], 'defaults': [], 'name': 'next'}],
            'import': [],
            'var': [{'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'pack_file_iterator' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'system'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'pack_file_iterator'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'pack_file_iterator' objects>}]},
           {'class': [], 'func': [{'args': ['self', 'msg'], 'defaults': [], 'name': 'write'}], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'system'}, {'name': '__qualname__', 'type': 'str', 'value': 'TraceFile'}]},
           {'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__delattr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delattr__' of 'module' objects>},
                    {'name': '__dict__', 'type': 'member_descriptor', 'value': <member '__dict__' of 'module' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'module(name[, doc])\n\nCreate a module object.\nThe name must be a string; the optional doc argument can have any type.'},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'module' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'module' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'module' objects>},
                    {'name': '__setattr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setattr__' of 'module' objects>}]},
           {'class': [],
            'func': [{'args': ['self', 'filename', 'mode'], 'defaults': ['rb'], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': '__iter__'},
                     {'args': ['self', 'len'], 'defaults': [None], 'name': 'read'},
                     {'args': ['self'], 'defaults': [], 'name': 'readline'},
                     {'args': ['self'], 'defaults': [], 'name': 'readlines'}],
            'import': [],
            'var': [{'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'pack_file' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'system'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'pack_file'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'pack_file' objects>}]},
           {'class': [], 'func': [{'args': ['self', 'msg'], 'defaults': [], 'name': 'write'}], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'system'}, {'name': '__qualname__', 'type': 'str', 'value': 'TraceErrorFile'}]}],
 'func': [{'args': ['excTitle'], 'defaults': [], 'name': 'GetExceptionString'},
          {'args': ['name'], 'defaults': [], 'name': 'RunMainScript'},
          {'args': ['excTitle'], 'defaults': [], 'name': 'ShowException'},
          {'args': ['sFileName'], 'defaults': [], 'name': '__IsCompiledFile__'},
          {'args': ['sFileName'], 'defaults': [], 'name': '__LoadCompiledFile__'},
          {'args': ['sFileName'], 'defaults': [], 'name': '__LoadTextFile__'},
          {'args': ['name', 'globals', 'locals', 'fromlist', 'level'], 'defaults': [None, None, None, -1], 'name': '__hybrid_import'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__import__'},
          {'args': ['code', 'fqname'], 'defaults': [], 'name': '_process_result'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'chr'},
          {'args': ['fileName', 'dict'], 'defaults': [], 'name': 'execfile'},
          {'args': ['bad-module'], 'defaults': [], 'name': 'lambda1'},
          {'args': ['filename', 'mode'], 'defaults': ['rb'], 'name': 'open'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'open'},
          {'args': ['p'], 'defaults': [], 'name': 'splitext'}],
 'import': ['app', 'dbg', '__main__', 'imp', 'rootlib', '__builtin__', 'sys', '__builtin__', 'debugInfo', 'marshal', 'pack'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'system'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': 'loginMark', 'type': 'str', 'value': '-cs'}]}
