{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'NextBeadUpdateTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'SetBeadCount'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'ui12zi'}, {'name': '__qualname__', 'type': 'str', 'value': 'BeadWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextMission'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'PressJumpButton'},
                     {'args': ['self', 'currentFloor', 'jumpCount', 'limitTime', 'elapseTime'], 'defaults': [], 'name': 'Refresh12ziTimer'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show12ziJumpButton'},
                     {'args': ['self', 'time'], 'defaults': [], 'name': 'StartCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'ui12zi'}, {'name': '__qualname__', 'type': 'str', 'value': 'FloorLimitTimeWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self', 'TextColor'], 'defaults': [], 'name': 'SetTextColor'},
                     {'args': ['self', 'PosX', 'PosY'], 'defaults': [], 'name': 'SetTooltipPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'ui12zi'}, {'name': '__qualname__', 'type': 'str', 'value': 'MapTextToolTip'}]}],
 'func': [],
 'import': ['uiCommon', 'constInfo', 'background', 'grp', 'uiToolTip', '__builtin__', 'app', 'm2netm2g', 'systemSetting', 'chr', 'playerm2g2', 'ui', 'mouseModule', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'ui12zi'}, {'name': '__package__', 'type': 'NoneType', 'value': None}]}
