{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'description'], 'defaults': [], 'name': 'SetDescription'},
                     {'args': ['self', 'text', 'x', 'y'], 'defaults': [0, -19], 'name': 'SetToolTipText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__qualname__', 'type': 'str', 'value': 'GrowthPetImage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'OnUpdateLovePoint'},
                     {'args': ['self', 'name', 'lovePoint'], 'defaults': [], 'name': 'SetLoverInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FILE_DICT',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/pattern/LovePoint/01.dds', 1: 'd:/ymir work/ui/pattern/LovePoint/02.dds', 2: 'd:/ymir work/ui/pattern/LovePoint/02.dds', 3: 'd:/ymir work/ui/pattern/LovePoint/03.dds', 4: 'd:/ymir work/ui/pattern/LovePoint/04.dds', 5: 'd:/ymir work/ui/pattern/LovePoint/05.dds'}},
                    {'name': 'FILE_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/LovePoint/'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'LovePointImage'}]},
           {'class': [],
            'func': [{'args': ['self', 'affect_type', 'affect_value', 'duration'], 'defaults': [], 'name': 'AddMultiLineDescription'},
                     {'args': ['self', 'point_idx', 'description'], 'defaults': [], 'name': 'AddMultiLineMountUpgradeDescription'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetDescription'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMountUpgradeMultiDescriptionCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsSkillAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'point_idx'], 'defaults': [], 'name': 'RemoveMountUpgradeMultiDescription'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'SetAffect'},
                     {'args': ['self', 'isClocked'], 'defaults': [], 'name': 'SetClock'},
                     {'args': ['self', 'description'], 'defaults': [], 'name': 'SetDescription'},
                     {'args': ['self', 'duration'], 'defaults': [], 'name': 'SetDuration'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetSkillAffectFlag'},
                     {'args': ['self', 'text', 'x', 'y', 'adjust_line_height', 'line_height_distance'], 'defaults': [0, -19, False, 20], 'name': 'SetToolTipText'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateAutoPotionDescription'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDescription'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDescriptionMountUpgradeSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateMultiLineDescription'},
                     {'args': ['self', 'affect_type'], 'defaults': [550], 'name': 'UpdateSetItemDescription'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateDescription2'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__qualname__', 'type': 'str', 'value': 'AffectImage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'level', 'health', 'battery'], 'defaults': [], 'name': 'SetState'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__AppendText'},
                     {'args': ['self', 'level'], 'defaults': [], 'name': '__GetHorseGrade'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FILE_DICT',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               1: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               2: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               3: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               10: 'd:/ymir work/ui/pattern/HorseState/10.dds',
                               11: 'd:/ymir work/ui/pattern/HorseState/11.dds',
                               12: 'd:/ymir work/ui/pattern/HorseState/12.dds',
                               13: 'd:/ymir work/ui/pattern/HorseState/13.dds',
                               20: 'd:/ymir work/ui/pattern/HorseState/20.dds',
                               21: 'd:/ymir work/ui/pattern/HorseState/21.dds',
                               22: 'd:/ymir work/ui/pattern/HorseState/22.dds',
                               23: 'd:/ymir work/ui/pattern/HorseState/23.dds',
                               30: 'd:/ymir work/ui/pattern/HorseState/30.dds',
                               31: 'd:/ymir work/ui/pattern/HorseState/31.dds',
                               32: 'd:/ymir work/ui/pattern/HorseState/32.dds',
                               33: 'd:/ymir work/ui/pattern/HorseState/33.dds'}},
                    {'name': 'FILE_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/HorseState/'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'HorseImage'}]},
           {'class': [],
            'func': [{'args': ['self', 'type', 'pointIdx', 'value', 'duration', 'flag'], 'defaults': [None], 'name': 'BINARY_NEW_AddAffect'},
                     {'args': ['self', 'type', 'pointIdx'], 'defaults': [], 'name': 'BINARY_NEW_RemoveAffect'},
                     {'args': ['self', 'affect', 'point_idx'], 'defaults': [], 'name': 'BINARY_NEW_Remove_MountUpgrade_Passive_Skill_Affect'},
                     {'args': ['self', 'type', 'point_type', 'value', 'duration'], 'defaults': [], 'name': 'BINARY_NEW_UpdateAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearAffects'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearAllAffects'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearLoverState'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearPetSkillAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideLoverState'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'OnUpdateLovePoint'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'ResetAffect'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'SetAffect'},
                     {'args': ['self', 'level', 'health', 'battery'], 'defaults': [], 'name': 'SetHorseState'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetItemAffectCheck'},
                     {'args': ['self', 'name', 'lovePoint'], 'defaults': [], 'name': 'SetLoverInfo'},
                     {'args': ['self', 'index', 'affect'], 'defaults': [], 'name': 'SetPetSkillAffect'},
                     {'args': ['self', 'playTime'], 'defaults': [], 'name': 'SetPlayTime'},
                     {'args': ['self', 'str', 'hp', 'move', 'immune'], 'defaults': [], 'name': 'SetSungMaAffectImage'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowLoverState'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': '__AppendAffect'},
                     {'args': ['self', 'index', 'affect'], 'defaults': [], 'name': '__AppendPetSkillAffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeImageList'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': '__RemoveAffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'AFFECT_MAX_NUM', 'type': 'int', 'value': 32},
                    {'name': 'IMAGE_STEP', 'type': 'int', 'value': 25},
                    {'name': 'INFINITE_AFFECT_DURATION', 'type': 'int', 'value': 536870911},
                    {'name': 'MALL_DESC_IDX_START', 'type': 'int', 'value': 1000},
                    {'name': '_AffectShower__AFFECT_PASSIVE_JOB_DECK_DATA_DOWN_SLOT_IMG_INDEX', 'type': 'int', 'value': 2},
                    {'name': '_AffectShower__AFFECT_PASSIVE_JOB_DECK_DATA_SIZE', 'type': 'int', 'value': 3},
                    {'name': '_AffectShower__AFFECT_PASSIVE_JOB_DECK_DATA_UP_SLOT_IMG_INDEX', 'type': 'int', 'value': 1},
                    {'name': '_AffectShower__mount_upgrade_passive_skill', 'type': 'member_descriptor', 'value': <member '_AffectShower__mount_upgrade_passive_skill' of 'AffectShower' objects>},
                    {'name': '_AffectShower__other_world_affect_type', 'type': 'member_descriptor', 'value': <member '_AffectShower__other_world_affect_type' of 'AffectShower' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'AffectShower'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__other_world_affect_type', '__mount_upgrade_passive_skill')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdateAutoPotionImage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetPotionType'},
                     {'args': ['self'], 'defaults': [], 'name': '__Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FILE_PATH_HP', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/auto_hpgauge/'},
                    {'name': 'FILE_PATH_SP', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/auto_spgauge/'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'AutoPotionImage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'str', 'hp', 'move', 'immune'], 'defaults': [], 'name': 'SetSungmaValue'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'str', 'hp', 'move', 'immune'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'TITLE_COLOR', 'type': 'int', 'value': -923968}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__qualname__', 'type': 'str', 'value': 'SungMaAffectImage'}]}],
 'func': [],
 'import': ['app', 'playerm2g2', 'skill', 'grp', 'uiToolTip', 'chr', 'localeInfo', 'math', '__builtin__', 'item', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
