{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsSkillAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'SetAffect'},
                     {'args': ['self', 'isClocked'], 'defaults': [], 'name': 'SetClock'},
                     {'args': ['self', 'description'], 'defaults': [], 'name': 'SetDescription'},
                     {'args': ['self', 'duration'], 'defaults': [], 'name': 'SetDuration'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetSkillAffectFlag'},
                     {'args': ['self', 'text', 'x', 'y', 'adjust_line_height', 'line_height_distance'], 'defaults': [0, -19, False, 20], 'name': 'SetToolTipText'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateAutoPotionDescription'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDescription'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateSetItemDescription'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateDescription2'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__qualname__', 'type': 'str', 'value': 'AffectImage'}]},
           {'class': [],
            'func': [{'args': ['self', 'type', 'pointIdx', 'value', 'duration'], 'defaults': [], 'name': 'BINARY_NEW_AddAffect'},
                     {'args': ['self', 'type', 'pointIdx'], 'defaults': [], 'name': 'BINARY_NEW_RemoveAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearAffects'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearAllAffects'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearLoverState'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearPetSkillAffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideLoverState'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'OnUpdateLovePoint'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'ResetAffect'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': 'SetAffect'},
                     {'args': ['self', 'level', 'health', 'battery'], 'defaults': [], 'name': 'SetHorseState'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetItemAffectCheck'},
                     {'args': ['self', 'name', 'lovePoint'], 'defaults': [], 'name': 'SetLoverInfo'},
                     {'args': ['self', 'index', 'affect'], 'defaults': [], 'name': 'SetPetSkillAffect'},
                     {'args': ['self', 'playTime'], 'defaults': [], 'name': 'SetPlayTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowLoverState'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': '__AppendAffect'},
                     {'args': ['self', 'index', 'affect'], 'defaults': [], 'name': '__AppendPetSkillAffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeImageList'},
                     {'args': ['self', 'affect'], 'defaults': [], 'name': '__RemoveAffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'AFFECT_DATA_DICT',
                     'type': 'dict',
                     'value': {3: ('Poisoning', 'd:/ymir work/ui/skill/common/affect/poison.sub'),
                               4: ('Slow', 'd:/ymir work/ui/skill/common/affect/slow.sub'),
                               5: ('Daze', 'd:/ymir work/ui/skill/common/affect/stun.sub'),
                               11: ('Movement speed raised', 'd:/ymir work/ui/skill/common/affect/Increase_Move_Speed.sub'),
                               12: ('Attack speed raised', 'd:/ymir work/ui/skill/common/affect/Increase_Attack_Speed.sub'),
                               13: ('Fishing Marble is active', 'd:/ymir work/ui/skill/common/affect/fishmind.sub'),
                               14: ('Battle Flush', 'd:/ymir work/ui/skill/warrior/jeongwi_03.sub'),
                               15: ('Aura of the Sword', 'd:/ymir work/ui/skill/warrior/geomgyeong_03.sub'),
                               16: ('Strong Body', 'd:/ymir work/ui/skill/warrior/cheongeun_03.sub'),
                               17: ('Feather Walking', 'd:/ymir work/ui/skill/assassin/gyeonggong_03.sub'),
                               18: ('Camouflage', 'd:/ymir work/ui/skill/assassin/eunhyeong_03.sub'),
                               19: ('Enchanted Blade', 'd:/ymir work/ui/skill/sura/gwigeom_03.sub'),
                               20: ('Fear', 'd:/ymir work/ui/skill/sura/gongpo_03.sub'),
                               21: ('Enchanted Armour', 'd:/ymir work/ui/skill/sura/jumagap_03.sub'),
                               22: ('Blessing', 'd:/ymir work/ui/skill/shaman/hosin_03.sub'),
                               23: ('Reflect', 'd:/ymir work/ui/skill/shaman/boho_03.sub'),
                               24: ('Speed', 'd:/ymir work/ui/skill/shaman/kwaesok_03.sub'),
                               25: ('Dark Protection', 'd:/ymir work/ui/skill/sura/heuksin_03.sub'),
                               26: ('Ghost of the Flame', 'd:/ymir work/ui/skill/sura/muyeong_03.sub'),
                               28: ('Permanent Fire', 'd:/ymir work/ui/skill/sura/hwayeom_03.sub'),
                               29: ("Dragon's Aid", 'd:/ymir work/ui/skill/shaman/gicheon_03.sub'),
                               30: ('Attack +', 'd:/ymir work/ui/skill/shaman/jeungryeok_03.sub'),
                               32: ('Neutralize Spell', 'd:/ymir work/ui/skill/sura/pabeop_03.sub'),
                               33: ('Strong Body', 'd:/ymir work/ui/skill/warrior/cheongeun_03.sub'),
                               38: ('Dazing Attack', 'd:/ymir work/ui/skill/common/affect/powerfulstrike.sub'),
                               42: ('Bleeding', 'd:/ymir work/ui/skill/common/affect/poison.sub'),
                               43: ('Enchanted Blade', 'd:/ymir work/ui/skill/wolfman/red_possession_03.sub'),
                               44: ('Strong Body', 'd:/ymir work/ui/skill/wolfman/blue_possession_03.sub'),
                               152: (<cyfunction SA.<locals>.f at 0x083380E0>, 'd:/ymir work/ui/skill/common/affect/guildskill_blood.sub'),
                               153: (<cyfunction SA.<locals>.f at 0x08338088>, 'd:/ymir work/ui/skill/common/affect/guildskill_bless.sub'),
                               154: (<cyfunction SA.<locals>.f at 0x083381E8>, 'd:/ymir work/ui/skill/common/affect/guildskill_seonghwi.sub'),
                               155: (<cyfunction SA.<locals>.f at 0x08338030>, 'd:/ymir work/ui/skill/common/affect/guildskill_accel.sub'),
                               156: (<cyfunction SA.<locals>.f at 0x08338138>, 'd:/ymir work/ui/skill/common/affect/guildskill_bunno.sub'),
                               157: (<cyfunction SA.<locals>.f at 0x08338190>, 'd:/ymir work/ui/skill/common/affect/guildskill_jumun.sub'),
                               220: (<cyfunction SNA.<locals>.f at 0x0832A608>, 'd:/ymir work/ui/game/monster_card/poly_affect.sub'),
                               500: (<cyfunction SNA.<locals>.f at 0x08338660>, 'd:/ymir work/ui/skill/common/affect/exp_bonus.sub'),
                               501: (<cyfunction SNA.<locals>.f at 0x08338870>, 'd:/ymir work/ui/skill/common/affect/item_bonus.sub'),
                               502: (<cyfunction SNA.<locals>.f at 0x08338920>, 'd:/ymir work/ui/skill/common/affect/safebox.sub'),
                               503: (<cyfunction SNA.<locals>.f at 0x083384A8>, 'd:/ymir work/ui/skill/common/affect/autoloot.sub'),
                               504: (<cyfunction SNA.<locals>.f at 0x083386B8>, 'd:/ymir work/ui/skill/common/affect/fishmind.sub'),
                               505: (<cyfunction SNA.<locals>.f at 0x083388C8>, 'd:/ymir work/ui/skill/common/affect/marriage_fast.sub'),
                               506: (<cyfunction SNA.<locals>.f at 0x08338768>, 'd:/ymir work/ui/skill/common/affect/gold_bonus.sub'),
                               507: (<cyfunction SNA.<locals>.f at 0x08335BE0>, 'd:/ymir work/ui/skill/common/affect/auto_premium.sub'),
                               511: (<cyfunction SNA.<locals>.f at 0x083351E8>, 'd:/ymir work/ui/skill/common/affect/gold_premium.sub'),
                               512: (<cyfunction SNA.<locals>.f at 0x083358C8>, 'd:/ymir work/ui/skill/common/affect/gold_premium.sub'),
                               513: (<cyfunction SNA.<locals>.f at 0x08335920>, 'd:/ymir work/ui/skill/common/affect/gold_premium.sub'),
                               534: ('Remainder: %.2f%%', 'd:/ymir work/ui/pattern/auto_hpgauge/05.dds'),
                               535: ('Remainder: %.2f%%', 'd:/ymir work/ui/pattern/auto_spgauge/05.dds'),
                               541: (<cyfunction SNA.<locals>.f at 0x08335EA0>, 'd:/ymir work/ui/dragonsoul/buff_ds_sky1.tga'),
                               542: (<cyfunction SNA.<locals>.f at 0x08335EF8>, 'd:/ymir work/ui/dragonsoul/buff_ds_land1.tga'),
                               550: (<cyfunction SNA.<locals>.f at 0x0833D0E0>, 'd:/ymir work/ui/skill/common/affect/set_bonus.sub'),
                               551: (<cyfunction SA.<locals>.f at 0x08335FA8>, 'd:/ymir work/ui/skill/common/affect/exp_bonus.sub'),
                               552: (<cyfunction SNA.<locals>.f at 0x08335B88>, 'd:/ymir work/ui/skill/common/affect/att_slow.sub'),
                               553: (<cyfunction SNA.<locals>.f at 0x08338D98>, 'd:/ymir work/ui/skill/common/affect/pepsi_bonus.sub'),
                               556: (<cyfunction SNA.<locals>.f at 0x08335C38>, 'd:/ymir work/ui/public/battle/buff_battle_potion.sub'),
                               1040: (<cyfunction SA.<locals>.f at 0x0832ACE8>, 'd:/ymir work/ui/skill/common/affect/critical.sub'),
                               1041: (<cyfunction SA.<locals>.f at 0x08335240>, 'd:/ymir work/ui/skill/common/affect/gold_premium.sub'),
                               1114: (<cyfunction SNA.<locals>.f at 0x08338450>, 'd:/ymir work/ui/skill/common/affect/att_bonus.sub'),
                               1115: (<cyfunction SNA.<locals>.f at 0x08338558>, 'd:/ymir work/ui/skill/common/affect/def_bonus.sub'),
                               1116: (<cyfunction SA.<locals>.f at 0x083385B0>, 'd:/ymir work/ui/skill/common/affect/exp_bonus.sub'),
                               1117: (<cyfunction SA.<locals>.f at 0x083387C0>, 'd:/ymir work/ui/skill/common/affect/item_bonus.sub'),
                               1118: (<cyfunction SA.<locals>.f at 0x08338710>, 'd:/ymir work/ui/skill/common/affect/gold_bonus.sub'),
                               1119: (<cyfunction SA.<locals>.f at 0x083389D0>, 'd:/ymir work/ui/skill/common/affect/gold_premium.sub'),
                               1120: (<cyfunction SA.<locals>.f at 0x08338A80>, 'd:/ymir work/ui/skill/common/affect/gold_premium.sub'),
                               1125: (<cyfunction SA.<locals>.f at 0x08338608>, 'd:/ymir work/ui/skill/common/affect/EXP_Bonus_p_on.sub'),
                               1126: (<cyfunction SA.<locals>.f at 0x08338818>, 'd:/ymir work/ui/skill/common/affect/Item_Bonus_p_on.sub'),
                               1132: (<cyfunction SNA.<locals>.f at 0x08338450>, 'd:/ymir work/ui/skill/common/affect/att_bonus.sub')}},
                    {'name': 'AFFECT_MAX_NUM', 'type': 'int', 'value': 32},
                    {'name': 'IMAGE_STEP', 'type': 'int', 'value': 25},
                    {'name': 'INFINITE_AFFECT_DURATION', 'type': 'int', 'value': 536870911},
                    {'name': 'MALL_DESC_IDX_START', 'type': 'int', 'value': 1000},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'AffectShower'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'level', 'health', 'battery'], 'defaults': [], 'name': 'SetState'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__AppendText'},
                     {'args': ['self', 'level'], 'defaults': [], 'name': '__GetHorseGrade'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FILE_DICT',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               1: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               2: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               3: 'd:/ymir work/ui/pattern/HorseState/00.dds',
                               10: 'd:/ymir work/ui/pattern/HorseState/10.dds',
                               11: 'd:/ymir work/ui/pattern/HorseState/11.dds',
                               12: 'd:/ymir work/ui/pattern/HorseState/12.dds',
                               13: 'd:/ymir work/ui/pattern/HorseState/13.dds',
                               20: 'd:/ymir work/ui/pattern/HorseState/20.dds',
                               21: 'd:/ymir work/ui/pattern/HorseState/21.dds',
                               22: 'd:/ymir work/ui/pattern/HorseState/22.dds',
                               23: 'd:/ymir work/ui/pattern/HorseState/23.dds',
                               30: 'd:/ymir work/ui/pattern/HorseState/30.dds',
                               31: 'd:/ymir work/ui/pattern/HorseState/31.dds',
                               32: 'd:/ymir work/ui/pattern/HorseState/32.dds',
                               33: 'd:/ymir work/ui/pattern/HorseState/33.dds'}},
                    {'name': 'FILE_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/HorseState/'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'HorseImage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'description'], 'defaults': [], 'name': 'SetDescription'},
                     {'args': ['self', 'text', 'x', 'y'], 'defaults': [0, -19], 'name': 'SetToolTipText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__qualname__', 'type': 'str', 'value': 'GrowthPetImage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'OnUpdateLovePoint'},
                     {'args': ['self', 'name', 'lovePoint'], 'defaults': [], 'name': 'SetLoverInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FILE_DICT',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/pattern/LovePoint/01.dds', 1: 'd:/ymir work/ui/pattern/LovePoint/02.dds', 2: 'd:/ymir work/ui/pattern/LovePoint/02.dds', 3: 'd:/ymir work/ui/pattern/LovePoint/03.dds', 4: 'd:/ymir work/ui/pattern/LovePoint/04.dds', 5: 'd:/ymir work/ui/pattern/LovePoint/05.dds'}},
                    {'name': 'FILE_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/LovePoint/'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'LovePointImage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdateAutoPotionImage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetPotionType'},
                     {'args': ['self'], 'defaults': [], 'name': '__Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FILE_PATH_HP', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/auto_hpgauge/'},
                    {'name': 'FILE_PATH_SP', 'type': 'str', 'value': 'd:/ymir work/ui/pattern/auto_spgauge/'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAffectShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'AutoPotionImage'}]}],
 'func': [],
 'import': ['uiToolTip', '__builtin__', 'app', 'item', 'chr', 'playerm2g2', 'ui', 'skill', 'localeInfo', 'math'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiAffectShower'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
