{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'inven_slot'], 'defaults': [], 'name': 'CantAttachToAttrSlot'},
                     {'args': ['self', 'is_up_button_click'], 'defaults': [], 'name': 'ClickMaterialButton'},
                     {'args': ['self', 'is_up_button_click'], 'defaults': [], 'name': 'ClickSuppotButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInMaterialSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInRegistSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInSupportSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'SelectEmptyRegistSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'SelectEmptySupportSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'SelectItemRegistSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'SelectItemSupportSlot'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CalculateTotalSuccessPer'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckCantMouseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearData'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearMaterialSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearSupportSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAttrAddButton'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__RangeCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendAttr67AddPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetOnTopWindowNone'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAttr67Add'}, {'name': '__qualname__', 'type': 'str', 'value': 'Attr67AddWindow'}]}],
 'func': [],
 'import': ['uiCommon', 'uiToolTip', '__builtin__', 'app', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': 'MATERIAL_MAX_COUNT', 'type': 'int', 'value': 10},
         {'name': 'ROOT_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/attr6th7th/'},
         {'name': 'SUCCESS_PER_MATERIAL', 'type': 'float', 'value': 2.0},
         {'name': 'SUPPORT_MAX_COUNT', 'type': 'int', 'value': 5},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiAttr67Add'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
