{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self', 'slot', 'metin'], 'defaults': [], 'name': 'CanAttachMetin'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'metinItemWindow', 'metinItemPos', 'targetItemWindow', 'targetItemPos'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAttachMetin'}, {'name': '__qualname__', 'type': 'str', 'value': 'AttachMetinDialog'}]}],
 'func': [],
 'import': ['snd', '__builtin__', 'uiToolTip', 'dbg', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'app', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiAttachMetin'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
