{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetScriptFileName'}, {'args': ['self', 'parent', 'filename'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAuction'}, {'name': '__qualname__', 'type': 'str', 'value': 'AuctionWindow.PageWindow'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeListPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeRegisterPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeUniqueAuctionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiAuction'}, {'name': '__qualname__', 'type': 'str', 'value': 'AuctionWindow'}]}],
 'func': [],
 'import': ['__builtin__', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiAuction'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
