{'class': [{'class': [],
            'func': [{'args': ['self', 'slotindex'], 'defaults': [], 'name': 'AddAutoSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'AutoAllClear'},
                     {'args': ['self', 'onoff', 'type', 'number', 'command'], 'defaults': [False], 'name': 'AutoOnOff'},
                     {'args': ['self'], 'defaults': [], 'name': 'AutoPositionClear'},
                     {'args': ['self'], 'defaults': [], 'name': 'AutoSkillClear'},
                     {'args': ['self', 'cooltime'], 'defaults': [], 'name': 'CheckCooltimeText'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'EditLineKillFocus'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetAutoStartonoff'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'IsNumberic'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadAutoWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'slotindex'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'slotindex', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'slotindex'], 'defaults': [], 'name': 'OverActiveSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverSkillSlotOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReadAutoInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAutoPositionSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAutoSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SaveAutoInfo'},
                     {'args': ['self', 'slotindex'], 'defaults': [], 'name': 'SelectActiveSkillEmptySlot'},
                     {'args': ['self', 'slotindex'], 'defaults': [], 'name': 'SelectActiveSkillSlot'},
                     {'args': ['self', 'slotindex', 'cooltime'], 'defaults': [], 'name': 'SetAutoCooltime'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetCloseGame'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'AUTO_COOLTIME_MAX', 'type': 'int', 'value': 16},
                    {'name': 'AUTO_COOLTIME_POS_X', 'type': 'int', 'value': 4},
                    {'name': 'AUTO_COOLTIME_POS_Y', 'type': 'int', 'value': 4},
                    {'name': 'AUTO_ONOFF_ATTACK', 'type': 'int', 'value': 2},
                    {'name': 'AUTO_ONOFF_AUTO_RANGE', 'type': 'int', 'value': 5},
                    {'name': 'AUTO_ONOFF_POSITION', 'type': 'int', 'value': 4},
                    {'name': 'AUTO_ONOFF_SKILL', 'type': 'int', 'value': 3},
                    {'name': 'AUTO_ONOFF_START', 'type': 'int', 'value': 1},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAuto'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'AutoWindow'}]}],
 'func': [],
 'import': ['constInfo', 'guild', 'uiToolTip', '__builtin__', 'app', 'chr', 'chrmgrm2g', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'wndMgr', 'skill', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiAuto'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
