{'class': [{'class': [],
            'func': [{'args': ['self', 'is_on_off', 'type', 'number', 'command'], 'defaults': [0, 0, False], 'name': 'AutoOnOff'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetAutoStartonoff'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadAutoWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAutoPotionSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAutoSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                     {'args': ['self', 'slot_index', 'cool_time'], 'defaults': [], 'name': 'SetAutoCooltime'},
                     {'args': ['self', 'tooltip_item'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'tooltip_skill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__AddAutoSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoAllClear'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoPotionClear'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoSave'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoSkillClear'},
                     {'args': ['self', 'cool_time'], 'defaults': [], 'name': '__CheckCoolTimeText'},
                     {'args': ['self', 'title', 'desc_list'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__EditLineKillFocus'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__IsNumberic'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'type', 'number', 'command'], 'defaults': [False], 'name': '__OnClickAutoOnOffButton'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__OverActiveSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverSkillSlotOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__ReadAutoInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__SaveAutoInfo'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__SelectActiveSkillEmptySlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__SelectActiveSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'AUTO_COOLTIME_AE_BASE_POS_X', 'type': 'int', 'value': 239},
                    {'name': 'AUTO_COOLTIME_AE_BASE_POS_Y', 'type': 'int', 'value': 89},
                    {'name': 'AUTO_COOLTIME_AE_INTERVER_X', 'type': 'int', 'value': 38},
                    {'name': 'AUTO_COOLTIME_AE_INTERVER_Y', 'type': 'int', 'value': 54},
                    {'name': 'AUTO_COOLTIME_AE_SLOT_INTERVER_Y', 'type': 'int', 'value': 29},
                    {'name': 'AUTO_COOLTIME_MAX', 'type': 'int', 'value': 24},
                    {'name': 'AUTO_COOLTIME_POS_X', 'type': 'int', 'value': 6},
                    {'name': 'AUTO_COOLTIME_POS_Y', 'type': 'int', 'value': 4},
                    {'name': 'AUTO_GAUGE_BAR_WIDTH', 'type': 'int', 'value': 175},
                    {'name': 'AUTO_GAUGE_BAR_X', 'type': 'int', 'value': 18},
                    {'name': 'AUTO_GAUGE_BAR_Y', 'type': 'int', 'value': 329},
                    {'name': 'AUTO_GAUGE_WIDTH', 'type': 'int', 'value': 16},
                    {'name': 'AUTO_OFF_START_NUMBER', 'type': 'int', 'value': 1},
                    {'name': 'AUTO_ONOFF_ATTACK_NUMBER', 'type': 'int', 'value': 2},
                    {'name': 'AUTO_ONOFF_MAX', 'type': 'int', 'value': 7},
                    {'name': 'AUTO_ONOFF_POTION_NUMBER', 'type': 'int', 'value': 4},
                    {'name': 'AUTO_ONOFF_RANGE_NUMBER', 'type': 'int', 'value': 5},
                    {'name': 'AUTO_ONOFF_RESTART_NUMBER', 'type': 'int', 'value': 6},
                    {'name': 'AUTO_ONOFF_SKILL_NUMBER', 'type': 'int', 'value': 3},
                    {'name': 'AUTO_ON_START_NUMBER', 'type': 'int', 'value': 0},
                    {'name': 'AUTO_TOOLTIP_CLEAR_HEIGHT', 'type': 'int', 'value': 28},
                    {'name': 'AUTO_TOOLTIP_CLEAR_WIDTH', 'type': 'int', 'value': 66},
                    {'name': 'ITEM_REMAIN_TIME_MAX', 'type': 'int', 'value': 9999},
                    {'name': '_AutoWindow__auto_all_clear_button', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_all_clear_button' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_onoff_button_list', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_onoff_button_list' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_potion_clear_button', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_potion_clear_button' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_skill_clear_button', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_skill_clear_button' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_slot', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_slot' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_slot_index', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_slot_index' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_start_is_onoff', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_start_is_onoff' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_system_tooltip_list', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_system_tooltip_list' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_tooltip', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_tooltip' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_tooltip_button', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_tooltip_button' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__auto_tooltip_clear', 'type': 'member_descriptor', 'value': <member '_AutoWindow__auto_tooltip_clear' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__hackPunishmentPopupDialog', 'type': 'member_descriptor', 'value': <member '_AutoWindow__hackPunishmentPopupDialog' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__is_loaded', 'type': 'member_descriptor', 'value': <member '_AutoWindow__is_loaded' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__is_read', 'type': 'member_descriptor', 'value': <member '_AutoWindow__is_read' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__time_edit_list', 'type': 'member_descriptor', 'value': <member '_AutoWindow__time_edit_list' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__tooltip_item', 'type': 'member_descriptor', 'value': <member '_AutoWindow__tooltip_item' of 'AutoWindow' objects>},
                    {'name': '_AutoWindow__tooltip_skill', 'type': 'member_descriptor', 'value': <member '_AutoWindow__tooltip_skill' of 'AutoWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiAuto'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'AutoWindow'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__is_loaded',
                               '__is_read',
                               '__tooltip_skill',
                               '__tooltip_item',
                               '__auto_start_is_onoff',
                               '__time_edit_list',
                               '__auto_slot_index',
                               '__auto_onoff_button_list',
                               '__auto_slot',
                               '__auto_skill_clear_button',
                               '__auto_potion_clear_button',
                               '__auto_all_clear_button',
                               '__auto_tooltip_button',
                               '__auto_tooltip',
                               '__auto_system_tooltip_list',
                               '__auto_tooltip_clear',
                               '__hackPunishmentPopupDialog')}]}],
 'func': [],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'skill', 'uiToolTip', 'chr', 'chrmgrm2g', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'guild', 'item', 'ui', 'os'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiAuto'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
