{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReturnToTown'},
                     {'args': ['self', 'who_killed', 'personal_rank'], 'defaults': [], 'name': 'SetInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleDead'}]},
           {'class': [],
            'func': [{'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BattleRoyaleProcess'},
                     {'args': ['self', 'parent_window'], 'defaults': [None], 'name': 'CreateElectricFieldOnScreenImage'},
                     {'args': ['self', 'open', 'parent_window'], 'defaults': [], 'name': 'OpenElectricFieldOnScreenImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleInterface'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'alive_count', 'personal_kill_count'], 'defaults': [], 'name': 'SetInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleKillInfo'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleApplication.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ApplyBattleRoyale'},
                     {'args': ['self'], 'defaults': [], 'name': 'BattleRoyaleApplicated'},
                     {'args': ['self'], 'defaults': [], 'name': 'BattleRoyaleNotApplicated'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BattleRoyaleProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'BattleRoyaleStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'BattleRoyaleStartable'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelApplicationBattleRoyale'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickMainButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickRankingButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'ExitBattleRoyale'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'useSpecialItem'], 'defaults': [], 'name': 'OnStartBattleRoyale'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'StartBattleRoyale'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleApplication'}]},
           {'class': [], 'func': [{'args': ['self'], 'defaults': [], 'name': 'SetInfo'}], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleWinner'}]}],
 'func': [],
 'import': ['event', 'uiCommon', '__builtin__', 'chatm2g', 'app', 'uiScriptLocale', 'battleRoyaleMgr', 'm2netm2g', 'playerm2g2', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiBattleRoyale'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
