{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiBattleField'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleFieldWindow.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'DisableEnterButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'EnableEnterButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'EnterBattleField'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'ExitEvent'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'ExitOnDeadEvent'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'ExitOnDeadQuestion'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'ExitQuestion'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'btnText', 'text_len'], 'defaults': [0], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self', 'type', 'category'], 'defaults': [], 'name': 'RefreshRankingList'},
                     {'args': ['self', 'leftOpen', 'leftEnd'], 'defaults': [], 'name': 'SetBattleFieldLeftTime'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'SetNotice'},
                     {'args': ['self', 'point'], 'defaults': [], 'name': 'SetPoint'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': 'SetState'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__DescBattleField'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeRankingUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotCoverUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotUI'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': '__OnClickTabButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DEFAULT_DESC_Y', 'type': 'int', 'value': 7},
                    {'name': 'DESCRIPTION_FILE_NAME', 'type': 'str', 'value': 'locale/de/desc_battle_field.txt'},
                    {'name': 'M2EMPIREICON', 'type': 'dict', 'value': {0: 'd:/ymir work/ui/public/battle/empire_empty.sub', 1: 'd:/ymir work/ui/public/battle/empire_shinsu.sub', 2: 'd:/ymir work/ui/public/battle/empire_chunjo.sub', 3: 'd:/ymir work/ui/public/battle/empire_jinno.sub'}},
                    {'name': 'SHOW_LINE_COUNT_MAX', 'type': 'int', 'value': 18},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiBattleField'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BattleFieldWindow'}]}],
 'func': [],
 'import': ['event', 'ranking', 'uiCommon', '__builtin__', 'app', 'wndMgr', 'm2netm2g', 'playerm2g2', 'ui', 'uiToolTip', 'background', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiBattleField'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
