{'class': [{'class': [],
            'func': [{'args': ['self', 'emotionIndex'], 'defaults': [], 'name': 'ActEmotion'},
                     {'args': ['self', 'skillIndex', 'skillLevel', 'curStatPoint'], 'defaults': [], 'name': 'CanShowPlusButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'ClickSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetState'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideStatusPlusButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': 'OnPressedSlotButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnQuestScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotIndex', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAlignment'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCharacter'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillPlusPointLabel'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'SlotIndex'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'skillSlotIndex'], 'defaults': [], 'name': 'SelectSkill'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectSkillGroup'},
                     {'args': ['self', 'toolTipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': 'SetState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowStatusPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanUseHorseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanUseSkillNow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ClickEmotionSlot'},
                     {'args': ['self', 'skillSlot'], 'defaults': [], 'name': '__GetETCSkillRealSlotIndex'},
                     {'args': ['self', 'skillGrade', 'skillSlot'], 'defaults': [], 'name': '__GetRealSkillSlot'},
                     {'args': ['self', 'skillSlot'], 'defaults': [], 'name': '__GetSkillGradeFromSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetStatMinusPoint'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalAtkText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalDefText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalMagAtkText'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAlignmentToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideJobToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideStatToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsChangedHorseRidingSkillLevel'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickStatusMinusButton'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickStatusPlusButton'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': '__OnClickTabButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OverInEmotion'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': '__OverInStatButton'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': '__OverInStatMinusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutEmotion'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStatButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStatMinusButton'},
                     {'args': ['self', 'realSkillSlot'], 'defaults': [], 'name': '__RealSkillSlotToSourceSlot'},
                     {'args': ['self', 'name', 'slotCount'], 'defaults': [], 'name': '__RefreshSkillPage'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__RefreshSkillPlusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshStatusPlusButtonList'},
                     {'args': ['self', 'skillPage'], 'defaults': [], 'name': '__RestoreSlotCoolTime'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SelectEmotion'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SelectQuest'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SelectSkillGroup'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetEmotionSlot'},
                     {'args': ['self', 'mainJob', 'subJob'], 'defaults': [], 'name': '__SetJobText'},
                     {'args': ['self', 'race', 'group'], 'defaults': [], 'name': '__SetSkillGroupName'},
                     {'args': ['self', 'race', 'group', 'empire'], 'defaults': [0], 'name': '__SetSkillSlotData'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetSkillSlotEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowAlignmentToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowJobToolTip'},
                     {'args': ['self', 'statDesc'], 'defaults': [], 'name': '__ShowStatToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateQuestClock'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'ACTIVE_PAGE_SLOT_COUNT', 'type': 'int', 'value': 8},
                    {'name': 'PAGE_HORSE', 'type': 'int', 'value': 2},
                    {'name': 'PAGE_SLOT_COUNT', 'type': 'int', 'value': 12},
                    {'name': 'SKILL_GROUP_NAME_DICT', 'type': 'dict', 'value': {0: {1: 'K\xf6rper', 2: 'Mental'}, 1: {1: 'Klinge', 2: 'Bogen'}, 2: {1: 'Waffen', 2: 'Magie'}, 3: {1: 'Drachen', 2: 'Heilung'}, 4: {1: 'Instinkt', 2: 'N.A.'}}},
                    {'name': 'STAT_DESCRIPTION', 'type': 'dict', 'value': {'DEX': 'Erh\xf6ht Angriff und Ausweichen', 'HTH': 'Erh\xf6ht TP und Verteidigung', 'INT': 'Erh\xf6ht MP, Magie-Angriff und -Verteidig.', 'STR': 'Erh\xf6ht Angriffswert und Schaden'}},
                    {'name': 'STAT_MINUS_DESCRIPTION',
                     'type': 'dict',
                     'value': {'DEX-': 'Beweglichkeitsanpassung (Verbleibende Chance: %d)', 'HTH-': 'Vitalit\xe4tsanpassung (Verbleibende Chance: %d)', 'INT-': 'Intelligenzanpassung (Verbleibende Chance: %d)', 'STR-': 'St\xe4rkeanpassung (Verbleibende Chance: %d)'}},
                    {'name': 'SUPPORT_PAGE_SLOT_COUNT', 'type': 'int', 'value': 12},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'CharacterWindow'}]}],
 'func': [{'args': ['n'], 'defaults': [], 'name': 'unsigned32'}],
 'import': ['emotion', 'app', 'dbg', 'm2netm2g', 'playerm2g2', 'skill', 'constInfo', 'uiToolTip', 'chr', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'snd', '__builtin__', 'quest', 'playerSettingModule', 'wndMgr', 'ui'],
 'var': [{'name': 'FACE_IMAGE_DICT',
          'type': 'dict',
          'value': {0: 'icon/face/warrior_m.tga', 1: 'icon/face/assassin_w.tga', 2: 'icon/face/sura_m.tga', 3: 'icon/face/shaman_w.tga', 4: 'icon/face/warrior_w.tga', 5: 'icon/face/assassin_m.tga', 6: 'icon/face/sura_w.tga', 7: 'icon/face/shaman_m.tga', 8: 'icon/face/wolfman_m.tga'}},
         {'name': 'HIDE_SUPPORT_SKILL_POINT', 'type': 'bool', 'value': True},
         {'name': 'SHOW_LIMIT_SUPPORT_SKILL_LIST', 'type': 'list', 'value': [121, 122, 123, 124, 126, 127, 129, 128, 131, 137, 138, 139, 140, 132]},
         {'name': 'SHOW_ONLY_ACTIVE_SKILL', 'type': 'bool', 'value': False},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiCharacter'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
