{'class': [{'class': [],
            'func': [{'args': ['self', 'quest_type', 'quest_index', 'is_confirm', 'desc_data_list'], 'defaults': [], 'name': 'AddQuest'},
                     {'args': ['self', 'quest_type', 'quest_index'], 'defaults': [], 'name': 'DeleteQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnQuestScrollMove'},
                     {'args': ['self', 'pivot_y'], 'defaults': [0], 'name': 'Refresh'},
                     {'args': ['self', 'scroll_bar'], 'defaults': [], 'name': 'RegisterScrollBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateQuestGroup'},
                     {'args': ['self', 'quest_type'], 'defaults': [], 'name': '__IsCorrectQuestType'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self', 'A', 'B'], 'defaults': [], 'name': 'binary_search'},
                     {'args': ['self', 'a1', 'a2', 'b'], 'defaults': [], 'name': 'closer'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestGroupGroup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClickFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetQuestIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShowNewImg'},
                     {'args': ['self', 'is_confirm', 'desc_data_list'], 'defaults': [], 'name': 'UpdateQuest'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'quest_index', 'is_confirm', 'desc_data_list'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESC_WINDOW_HEIGHT', 'type': 'int', 'value': 15}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestDescGroup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': '__CreateObject'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestLineObject'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ChildHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChildShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'pivot_y'], 'defaults': [], 'name': 'RefreshPosition'},
                     {'args': ['self', 'pivot_y'], 'defaults': [], 'name': 'RefreshShowHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshShowItemList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSize'},
                     {'args': ['self', 'is_open'], 'defaults': [], 'name': 'SetOpen'},
                     {'args': ['self', 'root_parent'], 'defaults': [], 'name': 'SetRootParent'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'ListGroup'}]},
           {'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'HideNewImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideQuestExistImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowClosedImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowNewImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowOpendImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowQuestExistImg'},
                     {'args': ['self', 'quest_type'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'quest_type'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestLabelObject'},
                    {'name': 'quest_lable_expend_img_path_dict',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/quest_re/tabcolor_1_main.tga',
                               1: 'd:/ymir work/ui/quest_re/tabcolor_2_sub.tga',
                               2: 'd:/ymir work/ui/quest_re/tabcolor_3_levelup.tga',
                               3: 'd:/ymir work/ui/quest_re/tabcolor_4_event.tga',
                               4: 'd:/ymir work/ui/quest_re/tabcolor_5_collection.tga',
                               5: 'd:/ymir work/ui/quest_re/tabcolor_6_system.tga',
                               6: 'd:/ymir work/ui/quest_re/tabcolor_7_scroll.tga',
                               7: 'd:/ymir work/ui/quest_re/tabcolor_8_daily.tga'}}]},
           {'class': [],
            'func': [{'args': ['self', 'emotionIndex'], 'defaults': [], 'name': 'ActEmotion'},
                     {'args': ['self', 'byType', 'dwDuration'], 'defaults': [], 'name': 'AddSpecialActionSlot'},
                     {'args': ['self', 'skillIndex', 'skillLevel', 'curStatPoint'], 'defaults': [], 'name': 'CanShowPlusButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'ClickSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideStatusPlusButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': 'OnPressedSlotButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self', 'slotIndex', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAlignment'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCharacter'},
                     {'args': ['self', 'quest_type', 'quest_index'], 'defaults': [], 'name': 'RefreshQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillPlusPointLabel'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'iIndex'], 'defaults': [], 'name': 'RemoveSpecialActionSlot'},
                     {'args': ['self', 'SlotIndex'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'skillSlotIndex'], 'defaults': [], 'name': 'SelectSkill'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectSkillGroup'},
                     {'args': ['self', 'toolTipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': 'SetState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowStatusPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanUseHorseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanUseSkillNow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ClickEmotionSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickExpandButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMinimizeButton'},
                     {'args': ['self', 'skillSlot'], 'defaults': [], 'name': '__GetETCSkillRealSlotIndex'},
                     {'args': ['self', 'skillGrade', 'skillSlot'], 'defaults': [], 'name': '__GetRealSkillSlot'},
                     {'args': ['self', 'skillSlot'], 'defaults': [], 'name': '__GetSkillGradeFromSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetStatMinusPoint'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalAtkText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalDefText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalMagAtkText'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAlignmentToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideJobToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideStatToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitCharacterDetailsUIButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsChangedHorseRidingSkillLevel'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickStatusMinusButton'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickStatusPlusButton'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': '__OnClickTabButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OverInEmotion'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': '__OverInStatButton'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': '__OverInStatMinusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutEmotion'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStatButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStatMinusButton'},
                     {'args': ['self', 'realSkillSlot'], 'defaults': [], 'name': '__RealSkillSlotToSourceSlot'},
                     {'args': ['self', 'name', 'slot_count'], 'defaults': [], 'name': '__RefreshSkillPage'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__RefreshSkillPlusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshStatusPlusButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SelectEmotion'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SelectSkillGroup'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetEmotionSlot'},
                     {'args': ['self', 'mainJob', 'subJob'], 'defaults': [], 'name': '__SetJobText'},
                     {'args': ['self', 'race', 'group'], 'defaults': [], 'name': '__SetSkillGroupName'},
                     {'args': ['self', 'race', 'group', 'empire'], 'defaults': [0], 'name': '__SetSkillSlotData'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetSkillSlotEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowAlignmentToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowJobToolTip'},
                     {'args': ['self', 'statDesc'], 'defaults': [], 'name': '__ShowStatToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'ACTIVE_PAGE_SLOT_COUNT', 'type': 'int', 'value': 8},
                    {'name': 'PAGE_HORSE', 'type': 'int', 'value': 2},
                    {'name': 'PAGE_SLOT_COUNT', 'type': 'int', 'value': 12},
                    {'name': 'SUPPORT_PAGE_SLOT_COUNT', 'type': 'int', 'value': 12},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'CharacterWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AddQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckNewImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetQuestType'},
                     {'args': ['self', 'quest_index'], 'defaults': [], 'name': 'IsExistQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateQuest'},
                     {'args': ['self', 'x', 'y'], 'defaults': [0, 0], 'name': '__AddDummy'},
                     {'args': ['self', 'x', 'y'], 'defaults': [0, 0], 'name': '__AddLine'},
                     {'args': ['self', 'quest_type'], 'defaults': [], 'name': '__CreateLabelObject'},
                     {'args': ['self', 'quest_index'], 'defaults': [], 'name': '__DeleteQuest'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsShowNewImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'quest_type'], 'defaults': [], 'name': '__init__'},
                     {'args': ['original_function'], 'defaults': [], 'name': 'add_update_delete_quest_post_process'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestGroup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestDummyObject'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetItemCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetViewCount'},
                     {'args': ['self', 'pivot_y'], 'defaults': [0], 'name': 'Refresh'},
                     {'args': ['self', 'pivot_y'], 'defaults': [], 'name': 'RefreshPosition'},
                     {'args': ['self', 'pivot_y'], 'defaults': [], 'name': 'RefreshShowHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshShowItemList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSize'},
                     {'args': ['self', 'root_parent'], 'defaults': [], 'name': 'SetRootParent'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'ListItem'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetHeight'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideNewImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateQuestClock'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'quest_index', 'quest_data', 'is_create_new_img'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESC_WINDOW_HEIGHT', 'type': 'int', 'value': 15},
                    {'name': 'QUEST_DESC_TEXT_MAX_WIDTH', 'type': 'int', 'value': 202},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestDescObject'}]}],
 'func': [{'args': ['clock_name', 'last_time'], 'defaults': [], 'name': 'MakeStringQuestClock'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'},
          {'args': ['n'], 'defaults': [], 'name': 'unsigned32'},
          {'args': ['wrapped', 'assigned', 'updated'], 'defaults': [('__module__', '__name__', '__doc__'), ('__dict__',)], 'name': 'wraps'}],
 'import': ['emotion', 'chatm2g', 'app', 'dbg', 'm2netm2g', 'playerm2g2', 'skill', 'constInfo', 'uiToolTip', 'chr', 'uiCharacterDetails', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'snd', '__builtin__', 'quest', 'playerSettingModule', 'wndMgr', 'uiTaskBar', 'item', 'ui', 'grpText'],
 'var': [{'name': 'FACE_IMAGE_DICT',
          'type': 'dict',
          'value': {0: 'icon/face/warrior_m.tga', 1: 'icon/face/assassin_w.tga', 2: 'icon/face/sura_m.tga', 3: 'icon/face/shaman_w.tga', 4: 'icon/face/warrior_w.tga', 5: 'icon/face/assassin_m.tga', 6: 'icon/face/sura_w.tga', 7: 'icon/face/shaman_m.tga', 8: 'icon/face/wolfman_m.tga'}},
         {'name': 'HIDE_SUPPORT_SKILL_POINT', 'type': 'bool', 'value': True},
         {'name': 'QUEST_STRING_TYPE_CLOCK', 'type': 'int', 'value': 1},
         {'name': 'QUEST_STRING_TYPE_NORMAL', 'type': 'int', 'value': 0},
         {'name': 'SHOW_LIMIT_SUPPORT_SKILL_LIST', 'type': 'list', 'value': [121, 122, 123, 124, 126, 127, 129, 128, 131, 137, 138, 139, 140, 132]},
         {'name': 'SHOW_ONLY_ACTIVE_SKILL', 'type': 'bool', 'value': False},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiCharacter'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
