{'class': [{'class': [],
            'func': [{'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'AdjustPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'GetStatusValue'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshLabel'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'i'], 'defaults': [], 'name': '__ButtonOverIn'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': '__ButtonOverOut'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': '__EmptyLine'},
                     {'args': ['self', 'point_type'], 'defaults': [], 'name': '__GetCalcPercentPoint'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitPercentCalcDict'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self', 'point_type'], 'defaults': [], 'name': '__IsPercentCalcPoint'},
                     {'args': ['self', 'idx', 'text', 'value'], 'defaults': [], 'name': '__LabelLine'},
                     {'args': ['self', 'idx', 'text'], 'defaults': [], 'name': '__LabelTitleLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacterDetails'}, {'name': '__qualname__', 'type': 'str', 'value': 'CharacterDetailsUI'}]}],
 'func': [],
 'import': ['__builtin__', 'uiToolTip', 'item', 'playerm2g2', 'ui', 'wndMgr', 'app', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiCharacterDetails'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
