{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'KillChatFocus'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRefreshChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChatFocus'},
                     {'args': ['self', 'max'], 'defaults': [], 'name': 'SetChatMax'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetEscapeEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetReturnEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__Create'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CHAT_OUTLINE_COLOR', 'type': 'int', 'value': -1}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatInputSet'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatWindow.ChatBackBoard'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                                {'args': ['self', 'owner'], 'defaults': [], 'name': 'SetOwner'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatWindow.ChatButton'}]}],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsEditMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBoardEditState'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBoardViewState'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChatFocus'},
                     {'args': ['self', 'height'], 'defaults': [], 'name': 'SetHeight'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetOpenChatLogEvent'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'SetPosition'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetSendWhisperEvent'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshSizingBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterChatColorDict'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'hide_btnChatSizing'},
                     {'args': ['self'], 'defaults': [], 'name': 'show_btnChatSizing'}],
            'import': [],
            'var': [{'name': 'BOARD_END_COLOR', 'type': 'int', 'value': -872415232},
                    {'name': 'BOARD_MIDDLE_COLOR', 'type': 'int', 'value': 2130706432},
                    {'name': 'BOARD_START_COLOR', 'type': 'int', 'value': 0},
                    {'name': 'CHAT_OUTLINE_COLOR', 'type': 'int', 'value': -1},
                    {'name': 'CHAT_WINDOW_WIDTH', 'type': 'int', 'value': 600},
                    {'name': 'EDIT_LINE_HEIGHT', 'type': 'int', 'value': 25},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatWindow'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatLogWindow.ResizeButton'}]}],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnResize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleAllChatMode'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'ToggleChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateChatInputSet'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateScrollBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BLOCK_WIDTH', 'type': 'int', 'value': 32},
                    {'name': 'CHAT_LOG_WINDOW_MINIMUM_HEIGHT', 'type': 'int', 'value': 120},
                    {'name': 'CHAT_LOG_WINDOW_MINIMUM_WIDTH', 'type': 'int', 'value': 450},
                    {'name': 'CHAT_MODE_INDEX', 'type': 'tuple', 'value': (0, 3, 4, 6, 1, 2, 11)},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatLogWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetEvent'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUTTON_STATE_DOWN', 'type': 'int', 'value': 2},
                    {'name': 'BUTTON_STATE_OVER', 'type': 'int', 'value': 1},
                    {'name': 'BUTTON_STATE_UP', 'type': 'int', 'value': 0},
                    {'name': 'OUTLINE_COLOR', 'type': 'int', 'value': -1},
                    {'name': 'OVER_COLOR', 'type': 'int', 'value': 1291845631},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatModeButton'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeChatMode'},
                     {'args': ['self', 'text', 'idx'], 'defaults': [], 'name': 'CheckString'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'CheckWrongString'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetCurrentChatModeName'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'IsNumberic'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnIMEKeyDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMETab'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'RunCloseEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetEscapeEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetReturnEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetTabEvent'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'SetChatMode'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetTabEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckChatMark'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearChat'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextLastSentenceStack'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevLastSentenceStack'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__PushLastSentenceStack'},
                     {'args': ['self'], 'defaults': [], 'name': '__ResetChat'},
                     {'args': ['self', 'text', 'type'], 'defaults': [], 'name': '__SendChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendGuildChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendPartyChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendShoutChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendTalkingChatPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatLine'}]}],
 'func': [{'args': [], 'defaults': [], 'name': 'DestroyChatInputSetWindow'}, {'args': ['wnd'], 'defaults': [], 'name': 'InsertChatInputSetWindow'}, {'args': [], 'defaults': [], 'name': 'RefreshChatMode'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'ime', 'grp', 'systemSetting', 'colorInfo', 'localeInfo', '__builtin__', 'wndMgr', 'constInfo', 'ui'],
 'var': [{'name': 'ENABLE_INSULT_CHECK', 'type': 'bool', 'value': True},
         {'name': 'ENABLE_LAST_SENTENCE_STACK', 'type': 'bool', 'value': True},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiChat'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'chatInputSetList', 'type': 'list', 'value': [<uiChat.ChatInputSet object at 0x26460850>, <uiChat.ChatInputSet object at 0x2688E550>]}]}
