{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitMovableModeValues'},
                     {'args': ['self'], 'defaults': [], 'name': 'KillChatFocus'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRefreshChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChatFocus'},
                     {'args': ['self', 'max'], 'defaults': [], 'name': 'SetChatMax'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetEscapeEvent'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'SetMovableMode'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetReturnEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__Create'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CHAT_OUTLINE_COLOR', 'type': 'int', 'value': -1}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatInputSet'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatWindow.ChatBackBoard'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                                {'args': ['self', 'owner'], 'defaults': [], 'name': 'SetOwner'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatWindow.ChatButton'}]}],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseChat'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'DeleteExpandTabButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsEditMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBoardEditState'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBoardViewState'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshChatWindow'},
                     {'args': ['self', 'index', 'pos_x', 'pos_y'], 'defaults': [], 'name': 'SaveExpandWndPos'},
                     {'args': ['self', 'index', 'width', 'height'], 'defaults': [], 'name': 'SaveExpandWndSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChatFocus'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetExpandedBtnTitleName'},
                     {'args': ['self', 'height'], 'defaults': [], 'name': 'SetHeight'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetOpenChatLogEvent'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'SetPosition'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetSendWhisperEvent'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'ShowExpandTabButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__AddTabWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseExpandChatBtn'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateExpandChatWnd'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickDownExpandedBtn'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickUpExpandedBtn'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnMouseRightButtonUpExpandedBtn'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshSizingBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__RegisterChatColorDict'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetExpandBtn'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetExpandWnd'},
                     {'args': ['self'], 'defaults': [], 'name': '__SettingOptionWndOpen'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'hide_btnChatSizing'},
                     {'args': ['self'], 'defaults': [], 'name': 'show_btnChatSizing'}],
            'import': [],
            'var': [{'name': 'BOARD_END_COLOR', 'type': 'int', 'value': -872415232},
                    {'name': 'BOARD_MIDDLE_COLOR', 'type': 'int', 'value': 2130706432},
                    {'name': 'BOARD_START_COLOR', 'type': 'int', 'value': 0},
                    {'name': 'CHAT_OUTLINE_COLOR', 'type': 'int', 'value': -1},
                    {'name': 'CHAT_WINDOW_WIDTH', 'type': 'int', 'value': 600},
                    {'name': 'EDIT_LINE_HEIGHT', 'type': 'int', 'value': 25},
                    {'name': 'EDIT_LINE_HIDE_HEIGHT', 'type': 'int', 'value': 20},
                    {'name': '_ChatWindow__btn_add_chat', 'type': 'member_descriptor', 'value': <member '_ChatWindow__btn_add_chat' of 'ChatWindow' objects>},
                    {'name': '_ChatWindow__btn_setting', 'type': 'member_descriptor', 'value': <member '_ChatWindow__btn_setting' of 'ChatWindow' objects>},
                    {'name': '_ChatWindow__expand_ui_list', 'type': 'member_descriptor', 'value': <member '_ChatWindow__expand_ui_list' of 'ChatWindow' objects>},
                    {'name': '_ChatWindow__wnd_chat_setting', 'type': 'member_descriptor', 'value': <member '_ChatWindow__wnd_chat_setting' of 'ChatWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatWindow'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__wnd_chat_setting', '__btn_setting', '__btn_add_chat', '__expand_ui_list')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatLogWindow.ResizeButton'}]}],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnResize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshChatWindow'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleAllChatMode'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'ToggleChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateChatInputSet'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateScrollBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BLOCK_WIDTH', 'type': 'int', 'value': 32},
                    {'name': 'CHAT_LOG_WINDOW_MINIMUM_HEIGHT', 'type': 'int', 'value': 120},
                    {'name': 'CHAT_LOG_WINDOW_MINIMUM_WIDTH', 'type': 'int', 'value': 450},
                    {'name': 'CHAT_MODE_INDEX', 'type': 'tuple', 'value': (0, 3, 4, 6, 1, 2, 11)},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatLogWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'enable', 'title_name'], 'defaults': [], 'name': 'Clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitPos'},
                     {'args': ['self', 'load_data'], 'defaults': [], 'name': 'LoadData'},
                     {'args': ['self', 'key', 'file'], 'defaults': [], 'name': 'SaveData'},
                     {'args': ['self', 'enable', 'title_name'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChattingWindowData'}, {'name': '__slots__', 'type': 'tuple', 'value': ('chat_window_data',)}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetEvent'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUTTON_STATE_DOWN', 'type': 'int', 'value': 2},
                    {'name': 'BUTTON_STATE_OVER', 'type': 'int', 'value': 1},
                    {'name': 'BUTTON_STATE_UP', 'type': 'int', 'value': 0},
                    {'name': 'OUTLINE_COLOR', 'type': 'int', 'value': -1},
                    {'name': 'OVER_COLOR', 'type': 'int', 'value': 1291845631},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatModeButton'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeChatMode'},
                     {'args': ['self', 'text', 'idx'], 'defaults': [], 'name': 'CheckString'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'CheckWrongString'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetChatMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetCurrentChatModeName'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'IsNumberic'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnIMEKeyDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMETab'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenChat'},
                     {'args': ['self'], 'defaults': [], 'name': 'RunCloseEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetEscapeEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetReturnEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetTabEvent'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'SetChatMode'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetTabEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckChatMark'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearChat'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextLastSentenceStack'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevLastSentenceStack'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__PushLastSentenceStack'},
                     {'args': ['self'], 'defaults': [], 'name': '__ResetChat'},
                     {'args': ['self', 'text', 'type'], 'defaults': [], 'name': '__SendChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendGuildChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendPartyChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendShoutChatPacket'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__SendTalkingChatPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatLine'}]},
           {'class': [{'class': [{'class': [],
                                  'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'},
                                           {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                                           {'args': ['self'], 'defaults': [], 'name': 'Up'},
                                           {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                           {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
                                  'import': [],
                                  'var': [{'name': '_MouseReflector__is_down', 'type': 'member_descriptor', 'value': <member '_MouseReflector__is_down' of 'MouseReflector' objects>},
                                          {'name': '__doc__', 'type': 'NoneType', 'value': None},
                                          {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                                          {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox.MouseReflector'},
                                          {'name': '__slots__', 'type': 'tuple', 'value': ('__is_down',)}]}],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetCheck'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                                {'args': ['self'], 'defaults': [], 'name': 'SetCheck'},
                                {'args': ['self', 'check'], 'defaults': [], 'name': 'SetCheckForce'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/chat/chattingoption_check_box_off.sub'], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_CheckBox__event', 'type': 'member_descriptor', 'value': <member '_CheckBox__event' of 'CheckBox' objects>},
                               {'name': '_CheckBox__image', 'type': 'member_descriptor', 'value': <member '_CheckBox__image' of 'CheckBox' objects>},
                               {'name': '_CheckBox__is_check', 'type': 'member_descriptor', 'value': <member '_CheckBox__is_check' of 'CheckBox' objects>},
                               {'name': '_CheckBox__mouse_reflector', 'type': 'member_descriptor', 'value': <member '_CheckBox__mouse_reflector' of 'CheckBox' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'ChatSettingWindow.CheckBox'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__mouse_reflector', '__image', '__event', '__is_check')}]},
                      {'class': [],
                       'func': [{'args': ['self', 'title_name', 'index'], 'defaults': [], 'name': 'AppendChattingSettingList'},
                                {'args': ['self', 'except_locale'], 'defaults': [], 'name': 'AppendExceptList'},
                                {'args': ['self', 'except_locale', 'remove_locale'], 'defaults': [], 'name': 'AppendRemoveExceptList'},
                                {'args': ['self'], 'defaults': [], 'name': 'ClearCurData'},
                                {'args': ['self'], 'defaults': [], 'name': 'ClearList'},
                                {'args': ['self', 'is_show'], 'defaults': [], 'name': 'DropDownSelectShowHide'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetCurLocaleName'},
                                {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetCurText'},
                                {'args': ['self', 'button'], 'defaults': [], 'name': 'SetDropDownButton'},
                                {'args': ['self', 'enable'], 'defaults': [], 'name': 'SetDropDownButtonEnable'},
                                {'args': ['self', 'index'], 'defaults': [], 'name': 'SetDropDownChattingListSelect'},
                                {'args': ['self', 'local_key'], 'defaults': [], 'name': 'SetDropDownLanguageListSelect'},
                                {'args': ['self'], 'defaults': [], 'name': 'SetLocaleListFile'},
                                {'args': ['self', 'window'], 'defaults': [], 'name': 'SetMainWindow'},
                                {'args': ['self', 'window'], 'defaults': [], 'name': 'SetSelectPivotWindow'},
                                {'args': ['self'], 'defaults': [], 'name': 'SetSelectWindow'},
                                {'args': ['self'], 'defaults': [], 'name': '__AdjustSelectWindowPosition'},
                                {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                                {'args': ['self', 'index', 'key'], 'defaults': [], 'name': '__OnClickDropDownChattingListSelect'},
                                {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickDropDownLanguageListSelect'},
                                {'args': ['self'], 'defaults': [], 'name': '__OnClickDropDownListButton'},
                                {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickDropDownListButtonOver'},
                                {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickDropDownListButtonOverOut'},
                                {'args': ['self'], 'defaults': [], 'name': '__OnDropDownScroll'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent', 'is_language_select', 'type'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_DropDownList__chatting_setting_window', 'type': 'member_descriptor', 'value': <member '_DropDownList__chatting_setting_window' of 'DropDownList' objects>},
                               {'name': '_DropDownList__cur_locale_name', 'type': 'member_descriptor', 'value': <member '_DropDownList__cur_locale_name' of 'DropDownList' objects>},
                               {'name': '_DropDownList__cur_text', 'type': 'member_descriptor', 'value': <member '_DropDownList__cur_text' of 'DropDownList' objects>},
                               {'name': '_DropDownList__drop_down_button', 'type': 'member_descriptor', 'value': <member '_DropDownList__drop_down_button' of 'DropDownList' objects>},
                               {'name': '_DropDownList__drop_down_button_list', 'type': 'member_descriptor', 'value': <member '_DropDownList__drop_down_button_list' of 'DropDownList' objects>},
                               {'name': '_DropDownList__drop_down_item_list', 'type': 'member_descriptor', 'value': <member '_DropDownList__drop_down_item_list' of 'DropDownList' objects>},
                               {'name': '_DropDownList__drop_down_mouse_over_img', 'type': 'member_descriptor', 'value': <member '_DropDownList__drop_down_mouse_over_img' of 'DropDownList' objects>},
                               {'name': '_DropDownList__drop_down_scroll', 'type': 'member_descriptor', 'value': <member '_DropDownList__drop_down_scroll' of 'DropDownList' objects>},
                               {'name': '_DropDownList__drop_down_type', 'type': 'member_descriptor', 'value': <member '_DropDownList__drop_down_type' of 'DropDownList' objects>},
                               {'name': '_DropDownList__except_locale_list', 'type': 'member_descriptor', 'value': <member '_DropDownList__except_locale_list' of 'DropDownList' objects>},
                               {'name': '_DropDownList__is_drop_down_window_open', 'type': 'member_descriptor', 'value': <member '_DropDownList__is_drop_down_window_open' of 'DropDownList' objects>},
                               {'name': '_DropDownList__is_language_select', 'type': 'member_descriptor', 'value': <member '_DropDownList__is_language_select' of 'DropDownList' objects>},
                               {'name': '_DropDownList__main_window', 'type': 'member_descriptor', 'value': <member '_DropDownList__main_window' of 'DropDownList' objects>},
                               {'name': '_DropDownList__select_pivot_window', 'type': 'member_descriptor', 'value': <member '_DropDownList__select_pivot_window' of 'DropDownList' objects>},
                               {'name': '_DropDownList__select_scroll_diff', 'type': 'member_descriptor', 'value': <member '_DropDownList__select_scroll_diff' of 'DropDownList' objects>},
                               {'name': '_DropDownList__select_scroll_pos', 'type': 'member_descriptor', 'value': <member '_DropDownList__select_scroll_pos' of 'DropDownList' objects>},
                               {'name': '_DropDownList__select_window', 'type': 'member_descriptor', 'value': <member '_DropDownList__select_window' of 'DropDownList' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'ChatSettingWindow.DropDownList'},
                               {'name': '__slots__',
                                'type': 'tuple',
                                'value': ('__main_window',
                                          '__drop_down_item_list',
                                          '__drop_down_button',
                                          '__is_drop_down_window_open',
                                          '__select_pivot_window',
                                          '__select_window',
                                          '__drop_down_button_list',
                                          '__cur_text',
                                          '__drop_down_scroll',
                                          '__drop_down_mouse_over_img',
                                          '__select_scroll_pos',
                                          '__select_scroll_diff',
                                          '__chatting_setting_window',
                                          '__is_language_select',
                                          '__drop_down_type',
                                          '__cur_locale_name',
                                          '__except_locale_list')}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AddTabWindow'},
                     {'args': ['self', 'index', 'key'], 'defaults': [], 'name': 'ChangeDropDownChattingList'},
                     {'args': ['self', 'locale_name', 'type'], 'defaults': [], 'name': 'ChangeDropDownLanguageList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'DeleteExpandTabButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'GetExpandWndPos'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'GetExpandWndSize'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'GetTitleName'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'IsEnableIndex'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'IsShowExpanWnd'},
                     {'args': ['self', 'line_index'], 'defaults': [], 'name': 'OnEnableGeneral'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetCurrentChatOption'},
                     {'args': ['self', 'index', 'pos_x', 'pos_y'], 'defaults': [], 'name': 'SetExpandWndPos'},
                     {'args': ['self', 'index', 'width', 'height'], 'defaults': [], 'name': 'SetExpandWndSize'},
                     {'args': ['self', 'index', 'is_open'], 'defaults': [], 'name': 'SetShowExpanWnd'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadChattingOptionFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickLanguageOnOffButton'},
                     {'args': ['self', 'type', 'text'], 'defaults': [], 'name': '__OnClickPopUpSetting'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSave'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionPopupAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionPopupCancle'},
                     {'args': ['self'], 'defaults': [], 'name': '__SaveAndSettingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__SaveDefault'},
                     {'args': ['self'], 'defaults': [], 'name': '__SaveFile'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetCurIndex'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetCurrentLanguageText'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetLanguage'},
                     {'args': ['self', 'index', 'on_off'], 'defaults': [], 'name': '__SetLanguageOnOffButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__SettingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__TabNameSetting'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'chatui'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_ChatSettingWindow__chatting_window_data_list', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__chatting_window_data_list' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__check_box_list', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__check_box_list' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__cur_index', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__cur_index' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__current_language__change_window_index__question_button', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__current_language__change_window_index__question_button' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__drop_down_list', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__drop_down_list' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__language_onoff_button', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__language_onoff_button' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__language_onoff_value', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__language_onoff_value' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__question_popup', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__question_popup' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__question_type', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__question_type' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__tab_name_value', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__tab_name_value' of 'ChatSettingWindow' objects>},
                    {'name': '_ChatSettingWindow__wnd_chat', 'type': 'member_descriptor', 'value': <member '_ChatSettingWindow__wnd_chat' of 'ChatSettingWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatSettingWindow'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__drop_down_list', '__check_box_list', '__chatting_window_data_list', '__language_onoff_button', '__language_onoff_value', '__cur_index', '__question_popup', '__question_type', '__tab_name_value', '__wnd_chat', '__current_language__change_window_index__question_button')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiChat'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChatExpandWindow.ResizeButton'}]}],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnResize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshChatWindow'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetLoadSize'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self', 'title_name'], 'defaults': [], 'name': 'SetTitleName'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateScrollBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__Return'},
                     {'args': ['self'], 'defaults': [], 'name': '__SizingBtnLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'chatset', 'chat_window'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_ChatExpandWindow__btn_Close', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__btn_Close' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__btn_return', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__btn_return' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__btn_sizing', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__btn_sizing' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__chat_id', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__chat_id' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__chat_window', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__chat_window' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__img_center', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__img_center' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__img_left', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__img_left' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__img_right', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__img_right' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__interface', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__interface' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__scroll_bar', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__scroll_bar' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__scroll_bar_pos', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__scroll_bar_pos' of 'ChatExpandWindow' objects>},
                    {'name': '_ChatExpandWindow__title_name', 'type': 'member_descriptor', 'value': <member '_ChatExpandWindow__title_name' of 'ChatExpandWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChat'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChatExpandWindow'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__chat_id', '__btn_sizing', '__img_left', '__img_center', '__img_right', '__btn_Close', '__title_name', '__scroll_bar', '__scroll_bar_pos', '__chat_window', '__btn_return', '__interface')}]}],
 'func': [{'args': [], 'defaults': [], 'name': 'DestroyChatInputSetWindow'}, {'args': ['wnd'], 'defaults': [], 'name': 'InsertChatInputSetWindow'}, {'args': [], 'defaults': [], 'name': 'RefreshChatMode'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'battleRoyaleMgr', 'ime', 'grp', 'uiToolTip', 'systemSetting', 'uiScriptLocale', 'colorInfo', 'localeInfo', 'uiCommon', 'cPickle', '__builtin__', 'background', 'wndMgr', 'constInfo', 'ui', 'os'],
 'var': [{'name': 'BLOCK_WIDTH', 'type': 'int', 'value': 32},
         {'name': 'CHAT_EXPAND_WINDOW_DEFAULT_HEIGHT', 'type': 'int', 'value': 120},
         {'name': 'CHAT_EXPAND_WINDOW_DEFAULT_POS_X', 'type': 'int', 'value': 20},
         {'name': 'CHAT_EXPAND_WINDOW_DEFAULT_POS_Y', 'type': 'int', 'value': 20},
         {'name': 'CHAT_EXPAND_WINDOW_DEFAULT_WIDTH', 'type': 'int', 'value': 450},
         {'name': 'CHAT_EXPAND_WINDOW_MINIMUM_HEIGHT', 'type': 'int', 'value': 120},
         {'name': 'CHAT_EXPAND_WINDOW_MINIMUM_WIDTH', 'type': 'int', 'value': 225},
         {'name': 'CHECK_BOX_X_POS', 'type': 'int', 'value': 145},
         {'name': 'CHECK_BOX_X_POS_AE', 'type': 'int', 'value': 80},
         {'name': 'DROPDOWN_CHATTING', 'type': 'int', 'value': 1},
         {'name': 'DROPDOWN_LANGUAGE_1', 'type': 'int', 'value': 2},
         {'name': 'DROPDOWN_LANGUAGE_2', 'type': 'int', 'value': 3},
         {'name': 'DROPDOWN_LANGUAGE_3', 'type': 'int', 'value': 4},
         {'name': 'DROPDOWN_MAX', 'type': 'int', 'value': 5},
         {'name': 'DROP_DOWN_BTN_HEIGHT', 'type': 'int', 'value': 16},
         {'name': 'DROP_DOWN_SHOW_MAX', 'type': 'int', 'value': 5},
         {'name': 'ENABLE_INSULT_CHECK', 'type': 'bool', 'value': True},
         {'name': 'ENABLE_LAST_SENTENCE_STACK', 'type': 'bool', 'value': True},
         {'name': 'LIMIT_TOKEN_COUNT', 'type': 'int', 'value': 16},
         {'name': 'MAX_CHATTING_WINDOW', 'type': 'int', 'value': 10},
         {'name': 'OPTION_CHECKBOX_DICE', 'type': 'int', 'value': 7},
         {'name': 'OPTION_CHECKBOX_EXP_INFO', 'type': 'int', 'value': 8},
         {'name': 'OPTION_CHECKBOX_GUILD', 'type': 'int', 'value': 3},
         {'name': 'OPTION_CHECKBOX_INFO', 'type': 'int', 'value': 5},
         {'name': 'OPTION_CHECKBOX_ITEM_INFO', 'type': 'int', 'value': 9},
         {'name': 'OPTION_CHECKBOX_MONEY_INFO', 'type': 'int', 'value': 10},
         {'name': 'OPTION_CHECKBOX_NOTICE', 'type': 'int', 'value': 6},
         {'name': 'OPTION_CHECKBOX_PARTY', 'type': 'int', 'value': 2},
         {'name': 'OPTION_CHECKBOX_SHOUT', 'type': 'int', 'value': 4},
         {'name': 'OPTION_CHECKBOX_TALKING', 'type': 'int', 'value': 1},
         {'name': 'OPTION_EXPAND_WND_HEIGH', 'type': 'int', 'value': 20},
         {'name': 'OPTION_EXPAND_WND_POS_X', 'type': 'int', 'value': 17},
         {'name': 'OPTION_EXPAND_WND_POS_Y', 'type': 'int', 'value': 18},
         {'name': 'OPTION_EXPAND_WND_WIDTH', 'type': 'int', 'value': 19},
         {'name': 'OPTION_IS_ENABLE', 'type': 'int', 'value': 0},
         {'name': 'OPTION_IS_EXPAND_WND_OPEN', 'type': 'int', 'value': 16},
         {'name': 'OPTION_LANGUAGE_1', 'type': 'int', 'value': 12},
         {'name': 'OPTION_LANGUAGE_2', 'type': 'int', 'value': 13},
         {'name': 'OPTION_LANGUAGE_3', 'type': 'int', 'value': 14},
         {'name': 'OPTION_LANGUAGE_ONOFF', 'type': 'int', 'value': 11},
         {'name': 'OPTION_MAX', 'type': 'int', 'value': 21},
         {'name': 'OPTION_TITLE_NAME', 'type': 'int', 'value': 15},
         {'name': 'QUESTION_POPUP_CLEAR', 'type': 'int', 'value': 1},
         {'name': 'QUESTION_POPUP_NONE', 'type': 'int', 'value': 0},
         {'name': 'QUESTION_POPUP_SET_TITLE_NAME', 'type': 'int', 'value': 2},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiChat'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'chatInputSetList', 'type': 'list', 'value': [<uiChat.ChatInputSet object at 0x1A195B90>, <uiChat.ChatInputSet object at 0x1A5F95B0>]}]}
