{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshChangeLookWindow'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SendAccept'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CHANGELOOK_SLOT_LEFT', 'type': 'int', 'value': 0},
                    {'name': 'CHANGELOOK_SLOT_MAX', 'type': 'int', 'value': 2},
                    {'name': 'CHANGELOOK_SLOT_RIGHT', 'type': 'int', 'value': 1},
                    {'name': 'USE_CHANGELOOKWINDOW_LIMIT_RANGE', 'type': 'int', 'value': 500},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiChangeLook'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ChangeLookWindow'}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'uiPrivateShopBuilder', 'uiPickMoney', 'm2netm2g', 'playerm2g2', 'uiRefine', 'constInfo', 'grp', 'uiToolTip', 'uiAttachMetin', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'ime', 'wndMgr', 'item', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiChangeLook'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
