{'class': [{'class': [],
            'func': [{'args': ['self', 'key', 'PREV', 'NEXT', 'dict_delitem'], 'defaults': [0, 1, <slot wrapper '__delitem__' of 'dict' objects>], 'name': '__delitem__'},
                     {'args': ['self', 'other'], 'defaults': [], 'name': '__eq__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': '__iter__'},
                     {'args': ['self', 'other'], 'defaults': [], 'name': '__ne__'},
                     {'args': ['self'], 'defaults': [], 'name': '__reduce__'},
                     {'args': ['self', '_repr_running'], 'defaults': [{}], 'name': '__repr__'},
                     {'args': ['self'], 'defaults': [], 'name': '__reversed__'},
                     {'args': ['self', 'key', 'value', 'PREV', 'NEXT', 'dict_setitem'], 'defaults': [0, 1, <slot wrapper '__setitem__' of 'dict' objects>], 'name': '__setitem__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'copy'},
                     {'args': ['self'], 'defaults': [], 'name': 'items'},
                     {'args': ['self'], 'defaults': [], 'name': 'iteritems'},
                     {'args': ['self'], 'defaults': [], 'name': 'iterkeys'},
                     {'args': ['self'], 'defaults': [], 'name': 'itervalues'},
                     {'args': ['self'], 'defaults': [], 'name': 'keys'},
                     {'args': ['self', 'key', 'default'], 'defaults': [<object object at 0x0C531500>], 'name': 'pop'},
                     {'args': ['self', 'last'], 'defaults': [True], 'name': 'popitem'},
                     {'args': ['self', 'key', 'default'], 'defaults': [None], 'name': 'setdefault'},
                     {'args': ['self'], 'defaults': [], 'name': 'values'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewitems'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewkeys'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewvalues'}],
            'import': [],
            'var': [{'name': '_OrderedDict__marker', 'type': 'object', 'value': <object object at 0x0C531500>},
                    {'name': '_OrderedDict__update', 'type': 'instancemethod', 'value': <unbound method MutableMapping.update>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'OrderedDict' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'Dictionary that remembers insertion order'},
                    {'name': '__module__', 'type': 'str', 'value': 'collections'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'OrderedDict' objects>},
                    {'name': 'fromkeys', 'type': 'classmethod', 'value': <classmethod object at 0x0CFDAD90>},
                    {'name': 'update', 'type': 'instancemethod', 'value': <unbound method MutableMapping.update>}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'HEIGHT', 'type': 'int', 'value': 11},
                    {'name': 'WIDTH', 'type': 'int', 'value': 222},
                    {'name': '_QuestLineObject__line_image', 'type': 'member_descriptor', 'value': <member '_QuestLineObject__line_image' of 'QuestLineObject' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestLineObject'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__line_image',)}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'HEIGHT', 'type': 'int', 'value': 5}, {'name': 'WIDTH', 'type': 'int', 'value': 222}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestDummyObject'}]},
           {'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [],
            'func': [{'args': ['self', 'emotionIndex'], 'defaults': [], 'name': 'ActEmotion'},
                     {'args': ['self', 'byType', 'dwDuration'], 'defaults': [], 'name': 'AddSpecialActionSlot'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'skillIndex', 'skillLevel', 'curStatPoint'], 'defaults': [], 'name': 'CanShowPlusButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanUseHorseSkill'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'ClickSkillSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideConquerorStatusPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideStatusPlusButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'slot_number'], 'defaults': [], 'name': 'OnPressedSlotButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotIndex', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAlignment'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCharacter'},
                     {'args': ['self', 'quest_type', 'quest_index'], 'defaults': [], 'name': 'RefreshQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillPlusPointLabel'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'iIndex'], 'defaults': [], 'name': 'RemoveSpecialActionSlot'},
                     {'args': ['self', 'SlotIndex'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'skillSlotIndex'], 'defaults': [], 'name': 'SelectSkill'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectSkillGroup'},
                     {'args': ['self', 'toolTipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': 'SetState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowConquerorStatusPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowStatusPlusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanUseHorseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanUseSkillNow'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__ChangeLevelInfoButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ClickEmotionSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickExpandButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMinimizeButton'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__ControlConquerorUI'},
                     {'args': ['self', 'skillSlot'], 'defaults': [], 'name': '__GetETCSkillRealSlotIndex'},
                     {'args': ['self', 'skillGrade', 'skillSlot'], 'defaults': [], 'name': '__GetRealSkillSlot'},
                     {'args': ['self', 'skillSlot'], 'defaults': [], 'name': '__GetSkillGradeFromSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetStatMinusPoint'},
                     {'args': ['self', 'point_type', 'percent_point_type'], 'defaults': [], 'name': '__GetSungMaPointValuePer'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalAtkText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalDefText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetTotalMagAtkText'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAlignmentToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitCharacterDetailsUIButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsChangedHorseRidingSkillLevel'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickConquerorStatusPlusButton'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickStatusMinusButton'},
                     {'args': ['self', 'statusKey'], 'defaults': [], 'name': '__OnClickStatusPlusButton'},
                     {'args': ['self', 'stateKey'], 'defaults': [], 'name': '__OnClickTabButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OverInEmotion'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': '__OverInStatButton'},
                     {'args': ['self', 'stat'], 'defaults': [], 'name': '__OverInStatMinusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutEmotion'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStatButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStatMinusButton'},
                     {'args': ['self', 'realSkillSlot'], 'defaults': [], 'name': '__RealSkillSlotToSourceSlot'},
                     {'args': ['self', 'name', 'slot_count'], 'defaults': [], 'name': '__RefreshSkillPage'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__RefreshSkillPlusButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshStatusMinusButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshStatusPlusButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SelectEmotion'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SelectSkillGroup'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetEmotionSlot'},
                     {'args': ['self', 'race', 'group'], 'defaults': [], 'name': '__SetSkillGroupName'},
                     {'args': ['self', 'race', 'group', 'empire'], 'defaults': [0], 'name': '__SetSkillSlotData'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetSkillSlotEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowAlignmentToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowStatusMinusButtonList'},
                     {'args': ['self', 'desc'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self', 'desc'], 'defaults': [], 'name': '__ShowToolTipButton'},
                     {'args': ['self', 'event_type', 'text'], 'defaults': [], 'name': '__ShowToolTipImg'},
                     {'args': ['self', 'event_type'], 'defaults': [], 'name': '__TogglePassiveAttrWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__ToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'ACTIVE_PAGE_SLOT_COUNT', 'type': 'int', 'value': 9},
                    {'name': 'CONQUEROR_POINT_SHIFT_CLICK_LIMIT', 'type': 'int', 'value': 10},
                    {'name': 'PAGE_HORSE', 'type': 'int', 'value': 2},
                    {'name': 'PAGE_SLOT_COUNT', 'type': 'int', 'value': 12},
                    {'name': 'SUPPORT_PAGE_SLOT_COUNT', 'type': 'int', 'value': 18},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'CharacterWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AddDummy'},
                     {'args': ['self'], 'defaults': [], 'name': 'AddLine'},
                     {'args': ['self'], 'defaults': [], 'name': 'Arrange'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsConfirmed'},
                     {'args': ['self'], 'defaults': [], 'name': 'RemoveDummy'},
                     {'args': ['self'], 'defaults': [], 'name': 'RemoveLine'},
                     {'args': ['self', 'desc_list'], 'defaults': [], 'name': 'ReplaceDesc'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickQuest'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'quest_index', 'is_confirmed'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'WIDTH', 'type': 'int', 'value': 222},
                    {'name': '_QuestObject__desc_list', 'type': 'member_descriptor', 'value': <member '_QuestObject__desc_list' of 'QuestObject' objects>},
                    {'name': '_QuestObject__dummy', 'type': 'member_descriptor', 'value': <member '_QuestObject__dummy' of 'QuestObject' objects>},
                    {'name': '_QuestObject__is_confirmed', 'type': 'member_descriptor', 'value': <member '_QuestObject__is_confirmed' of 'QuestObject' objects>},
                    {'name': '_QuestObject__line', 'type': 'member_descriptor', 'value': <member '_QuestObject__line' of 'QuestObject' objects>},
                    {'name': '_QuestObject__new_image', 'type': 'member_descriptor', 'value': <member '_QuestObject__new_image' of 'QuestObject' objects>},
                    {'name': '_QuestObject__quest_index', 'type': 'member_descriptor', 'value': <member '_QuestObject__quest_index' of 'QuestObject' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestObject'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__new_image', '__line', '__dummy', '__quest_index', '__is_confirmed', '__desc_list')}]},
           {'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'GetColorImageFileName', 'type': 'classmethod', 'value': <classmethod object at 0x0D160450>},
                    {'name': 'GetQuestCategoryName', 'type': 'classmethod', 'value': <classmethod object at 0x0D160430>},
                    {'name': 'GetQuestCategoryTuple', 'type': 'classmethod', 'value': <classmethod object at 0x0D0332F0>},
                    {'name': 'IsCorrectQuestType', 'type': 'classmethod', 'value': <classmethod object at 0x0D160410>},
                    {'name': 'MakeQuestClockString', 'type': 'classmethod', 'value': <classmethod object at 0x0D160470>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'QuestCommonData' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestCommonData'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'QuestCommonData' objects>}]},
           {'class': [],
            'func': [{'args': ['self', 'quest_type'], 'defaults': [], 'name': 'ChildHeightChanged'},
                     {'args': ['self', 'quest_type', 'quest_index'], 'defaults': [], 'name': 'DeleteQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self', 'quest_type', 'quest_index', 'is_confirmed', 'desc_data_list'], 'defaults': [], 'name': 'ReplaceQuest'},
                     {'args': ['self', 'quest_type'], 'defaults': [], 'name': '__AdjustScrollPos'},
                     {'args': ['self'], 'defaults': [], 'name': '__Arrange'},
                     {'args': ['self', 'quest_type'], 'defaults': [], 'name': '__ArrangeAfter'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScrollEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'clipping_mask_window', 'scroll_object'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'SCROLL_STEP', 'type': 'int', 'value': 18},
                    {'name': '_QuestCategoryGroup__diff_height', 'type': 'member_descriptor', 'value': <member '_QuestCategoryGroup__diff_height' of 'QuestCategoryGroup' objects>},
                    {'name': '_QuestCategoryGroup__quest_category_dict', 'type': 'member_descriptor', 'value': <member '_QuestCategoryGroup__quest_category_dict' of 'QuestCategoryGroup' objects>},
                    {'name': '_QuestCategoryGroup__scroll', 'type': 'member_descriptor', 'value': <member '_QuestCategoryGroup__scroll' of 'QuestCategoryGroup' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestCategoryGroup'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__quest_category_dict', '__scroll', '__diff_height')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CheckNewImage'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReplaceQuest'},
                     {'args': ['self'], 'defaults': [], 'name': '__Arrange'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickLabel'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideNewImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideQuestExistImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowClosedImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowNewImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowOpendImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowQuestExistImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['original_function'], 'defaults': [], 'name': '__height_resize_post_process'},
                     {'args': ['self', 'clipping_mask_window', 'parent', 'quest_type'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'HEIGHT', 'type': 'int', 'value': 22},
                    {'name': 'WIDTH', 'type': 'int', 'value': 222},
                    {'name': '_QuestCategory__clipping_mask_window', 'type': 'member_descriptor', 'value': <member '_QuestCategory__clipping_mask_window' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__closed_image', 'type': 'member_descriptor', 'value': <member '_QuestCategory__closed_image' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__is_on', 'type': 'member_descriptor', 'value': <member '_QuestCategory__is_on' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__lable_image', 'type': 'member_descriptor', 'value': <member '_QuestCategory__lable_image' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__name_textline', 'type': 'member_descriptor', 'value': <member '_QuestCategory__name_textline' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__name_window', 'type': 'member_descriptor', 'value': <member '_QuestCategory__name_window' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__new_image', 'type': 'member_descriptor', 'value': <member '_QuestCategory__new_image' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__opened_image', 'type': 'member_descriptor', 'value': <member '_QuestCategory__opened_image' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__quest_dict', 'type': 'member_descriptor', 'value': <member '_QuestCategory__quest_dict' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__quest_exist_image', 'type': 'member_descriptor', 'value': <member '_QuestCategory__quest_exist_image' of 'QuestCategory' objects>},
                    {'name': '_QuestCategory__quest_type', 'type': 'member_descriptor', 'value': <member '_QuestCategory__quest_type' of 'QuestCategory' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestCategory'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__clipping_mask_window', '__lable_image', '__opened_image', '__closed_image', '__new_image', '__quest_exist_image', '__name_window', '__name_textline', '__quest_dict', '__quest_type', '__is_on')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnUpdate'}, {'args': ['self'], 'defaults': [], 'name': '__UpdateQuestClock'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent', 'quest_index', 'desc_data'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESC_TEXT_MAX_WIDTH', 'type': 'int', 'value': 202},
                    {'name': 'HEIGHT', 'type': 'int', 'value': 15},
                    {'name': 'WIDTH', 'type': 'int', 'value': 222},
                    {'name': '_QuestDescObject__contents_textline', 'type': 'member_descriptor', 'value': <member '_QuestDescObject__contents_textline' of 'QuestDescObject' objects>},
                    {'name': '_QuestDescObject__contents_window', 'type': 'member_descriptor', 'value': <member '_QuestDescObject__contents_window' of 'QuestDescObject' objects>},
                    {'name': '_QuestDescObject__quest_index', 'type': 'member_descriptor', 'value': <member '_QuestDescObject__quest_index' of 'QuestDescObject' objects>},
                    {'name': '_QuestDescObject__quest_string_type', 'type': 'member_descriptor', 'value': <member '_QuestDescObject__quest_string_type' of 'QuestDescObject' objects>},
                    {'name': '_QuestDescObject__quest_text', 'type': 'member_descriptor', 'value': <member '_QuestDescObject__quest_text' of 'QuestDescObject' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCharacter'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestDescObject'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__contents_window', '__contents_textline', '__quest_index', '__quest_string_type', '__quest_text')}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}, {'args': ['n'], 'defaults': [], 'name': 'unsigned32'}, {'args': ['wrapped', 'assigned', 'updated'], 'defaults': [('__module__', '__name__', '__doc__'), ('__dict__',)], 'name': 'wraps'}],
 'import': ['emotion', 'uiCommon', 'chatm2g', 'app', 'dbg', 'm2netm2g', 'playerm2g2', 'skill', 'event', 'constInfo', 'uiToolTip', 'chr', 'uiCharacterDetails', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'snd', '__builtin__', 'quest', 'playerSettingModule', 'wndMgr', 'uiTaskBar', 'mount', 'item', 'ui', 'grpText'],
 'var': [{'name': 'FACE_IMAGE_DICT',
          'type': 'dict',
          'value': {0: 'icon/face/warrior_m.tga', 1: 'icon/face/assassin_w.tga', 2: 'icon/face/sura_m.tga', 3: 'icon/face/shaman_w.tga', 4: 'icon/face/warrior_w.tga', 5: 'icon/face/assassin_m.tga', 6: 'icon/face/sura_w.tga', 7: 'icon/face/shaman_m.tga', 8: 'icon/face/wolfman_m.tga'}},
         {'name': 'HIDE_SUPPORT_SKILL_POINT', 'type': 'bool', 'value': True},
         {'name': 'SHOW_LIMIT_SUPPORT_SKILL_LIST', 'type': 'list', 'value': [121, 122, 123, 124, 126, 127, 129, 128, 131, 137, 138, 139, 140, 132, 133, 134, 246, 322]},
         {'name': 'SHOW_ONLY_ACTIVE_SKILL', 'type': 'bool', 'value': False},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiCharacter'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
