{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLineHeight'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextLineCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetButtonName'},
                     {'args': ['self', 'Height'], 'defaults': [], 'name': 'SetLineHeight'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'PopupDialog2'}]},
           {'class': [],
            'func': [{'args': ['self', 'text'], 'defaults': [], 'name': 'SetDescription1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetDescription2'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'InputDialogWithDescription2'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitMovableModeValues'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetBoardWidth'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'is_enable'], 'defaults': [], 'name': 'SetCheckWidth'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetFocus'},
                     {'args': ['self', 'length'], 'defaults': [], 'name': 'SetMax'},
                     {'args': ['self', 'length'], 'defaults': [], 'name': 'SetMaxLength'},
                     {'args': ['self', 'is_enable'], 'defaults': [], 'name': 'SetMovableEditLineMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetNumberMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetSecretMode'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetSlotWidth'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetTitle'},
                     {'args': ['self', 'bUse'], 'defaults': [True], 'name': 'SetUseCodePage'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'InputDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AutoControlSizeRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLineHeight'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextLineCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetButtonText'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetCancelEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetAcceptAutolSizeText'},
                     {'args': ['self', 'color'], 'defaults': [4288848546L], 'name': 'SetAcceptButtonDisable'},
                     {'args': ['self', 'color'], 'defaults': [4290953922L], 'name': 'SetAcceptButtonEnable'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetAcceptText'},
                     {'args': ['self', 'defaultWidth'], 'defaults': [], 'name': 'SetAutoControlSize'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetCancelAutolSizeText'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetCancelText'},
                     {'args': ['self', 'Height'], 'defaults': [], 'name': 'SetLineHeight'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUTTON_POS_Y', 'type': 'int', 'value': 40},
                    {'name': 'STEP_HEIGHT', 'type': 'int', 'value': 20},
                    {'name': 'TEXT_HEIGHT_BLANK_SPACE', 'type': 'int', 'value': 70},
                    {'name': 'TEXT_WIDTH_BLANK_SPACE', 'type': 'int', 'value': 50},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCommon'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestionDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClearRewardData'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRewardList'},
                     {'args': ['self'], 'defaults': [], 'name': 'ScrollShow'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetCalledWindow'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'reward_info'], 'defaults': [], 'name': 'SetRewardInfo'},
                     {'args': ['self', 'common_reward_vnum'], 'defaults': [], 'name': 'SetRewardInfoFromCommonRewardList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBarRewardListEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetScrollBar'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__SlotOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__SlotOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'REWARD_LIST_WIDTH_COUNT', 'type': 'int', 'value': 5},
                    {'name': 'SHOW_REWARD_LIMIT_COUNT', 'type': 'int', 'value': 25},
                    {'name': '_RewardListDialog__called_window', 'type': 'member_descriptor', 'value': <member '_RewardListDialog__called_window' of 'RewardListDialog' objects>},
                    {'name': '_RewardListDialog__cur_scroll_bar_Index__reward_slot_window', 'type': 'member_descriptor', 'value': <member '_RewardListDialog__cur_scroll_bar_Index__reward_slot_window' of 'RewardListDialog' objects>},
                    {'name': '_RewardListDialog__item_data_list', 'type': 'member_descriptor', 'value': <member '_RewardListDialog__item_data_list' of 'RewardListDialog' objects>},
                    {'name': '_RewardListDialog__scroll_bar__reward_tooltip', 'type': 'member_descriptor', 'value': <member '_RewardListDialog__scroll_bar__reward_tooltip' of 'RewardListDialog' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCommon'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RewardListDialog'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__cur_scroll_bar_Index__reward_slot_window', '__scroll_bar__reward_tooltip', '__item_data_list', '__called_window')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetTextSize1'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextSize2'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'QuestionDialog2'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLineHeight'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextLineCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetButtonName'},
                     {'args': ['self', 'Height'], 'defaults': [], 'name': 'SetLineHeight'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'layer'], 'defaults': ['UI'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'ExPopupDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AutoControlSizeRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'msg', 'timeout'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'defaultWidth'], 'defaults': [], 'name': 'SetAutoControlSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetCancelOnTimeOver'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': 'SetTimeOverMsg'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'QUEST_DIALOG_WITH_TIME_LIMIT_BUTTON_POS_Y', 'type': 'int', 'value': 40},
                    {'name': 'QUEST_DIALOG_WITH_TIME_LIMIT_REMAIN_TIME_POS_Y', 'type': 'int', 'value': 50},
                    {'name': 'QUEST_DIALOG_WITH_TIME_LIMIT_STEP_HEIGHT', 'type': 'int', 'value': 20},
                    {'name': 'QUEST_DIALOG_WITH_TIME_LIMIT_TEXT_HEIGHT_BLANK_SPACE', 'type': 'int', 'value': 90},
                    {'name': 'QUEST_DIALOG_WITH_TIME_LIMIT_TEXT_WIDTH_BLANK_SPACE', 'type': 'int', 'value': 50},
                    {'name': '_QuestionDialogWithTimeLimit__default_width', 'type': 'member_descriptor', 'value': <member '_QuestionDialogWithTimeLimit__default_width' of 'QuestionDialogWithTimeLimit' objects>},
                    {'name': '_QuestionDialogWithTimeLimit__is_auto_control_size', 'type': 'member_descriptor', 'value': <member '_QuestionDialogWithTimeLimit__is_auto_control_size' of 'QuestionDialogWithTimeLimit' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiCommon'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'QuestionDialogWithTimeLimit'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__is_auto_control_size', '__default_width')}]},
           {'class': [],
            'func': [{'args': ['self', 'text'], 'defaults': [], 'name': 'SetDescription'}, {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'InputDialogWithDescription'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLineHeight'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextLineCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'filename'], 'defaults': [], 'name': 'SetButtonDownVisual'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetButtonHorizontalAlignCenter'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetButtonName'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetButtonNameAutoSize'},
                     {'args': ['self', 'filename'], 'defaults': [], 'name': 'SetButtonOverVisual'},
                     {'args': ['self', 'filename'], 'defaults': [], 'name': 'SetButtonUpVisual'},
                     {'args': ['self', 'Height'], 'defaults': [], 'name': 'SetLineHeight'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'PopupDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLineHeight'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextLineCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetCancelEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetAcceptText'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetCancelText'},
                     {'args': ['self', 'Height'], 'defaults': [], 'name': 'SetLineHeight'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'layer'], 'defaults': ['UI'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'ExQuestionDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetCheque'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'cheque'], 'defaults': [], 'name': 'SetCheque'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetFocus'},
                     {'args': ['self', 'length'], 'defaults': [], 'name': 'SetMaxLength'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetMoneyHeaderText'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetTitle'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'SetValue'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickChequeEditLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickValueEditLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnValueUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__qualname__', 'type': 'str', 'value': 'MoneyInputDialog'}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'playerm2g2', 'ime', 'uiScriptLocale', 'localeInfo', '__builtin__', 'item', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiCommon'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
