{'class': [{'class': [],
            'func': [{'args': ['self', 'itemVnum', 'count'], 'defaults': [], 'name': 'AddCubeResultItem'},
                     {'args': ['self', 'itemIndex', 'orderIndex', 'itemVnum', 'itemCount'], 'defaults': [], 'name': 'AddMaterialInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'Clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearCubeResultItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetResultCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScrollResultList'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'itemTooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'gold', 'itemVnum', 'count'], 'defaults': [], 'name': 'UpdateInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAcceptButtonClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseButtonClick'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OnOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOverOutItem'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': '__OnSelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': '__OnSelectItemSlot'},
                     {'args': ['self', 'trash', 'resultIndex', 'materialIndex'], 'defaults': [], 'name': '__OnSelectMaterialSlot'},
                     {'args': ['self', 'trash', 'resultIndex'], 'defaults': [], 'name': '__OverInCubeResultSlot'},
                     {'args': ['self', 'trash', 'resultIndex', 'col'], 'defaults': [], 'name': '__OverInMaterialSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutMaterialSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCube'}, {'name': '__qualname__', 'type': 'str', 'value': 'CubeWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'itemVnum', 'count'], 'defaults': [], 'name': 'SetCubeResultItem'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseButtonClick'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OnOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCube'}, {'name': '__qualname__', 'type': 'str', 'value': 'CubeResultWindow'}]}],
 'func': [],
 'import': ['snd', 'grp', '__builtin__', 'uiToolTip', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'app', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiCube'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
