{'class': [{'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [],
            'func': [{'args': ['self', 'cube_item'], 'defaults': [], 'name': 'AddItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearItemList'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseMenu'},
                     {'args': ['self', 'group'], 'defaults': [None], 'name': 'GetRecentlyAddedDetailObject'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnListScrollMove'},
                     {'args': ['self', 'pivot_y'], 'defaults': [0], 'name': 'Refresh'},
                     {'args': ['self', 'scroll_bar'], 'defaults': [], 'name': 'RegisterScrollBar'},
                     {'args': ['self', 'list_index', 'selected'], 'defaults': [], 'name': 'SelectItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self', 'A', 'B'], 'defaults': [], 'name': 'binary_search'},
                     {'args': ['self', 'a1', 'a2', 'b'], 'defaults': [], 'name': 'closer'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'ItemCategoryGroup'}]},
           {'class': [],
            'func': [{'args': ['self', 'cube_item'], 'defaults': [], 'name': 'AddItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearItemList'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'cube_item'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'ItemDetailGroup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ShowClosedImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowOpendImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'item_category'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'ItemCategoryObject'}]},
           {'class': [],
            'func': [{'args': ['self', 'item_vnum', 'item_quantity'], 'defaults': [], 'name': 'ActivateItemSlot'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'ActivateSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearActivatedSlots'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearBeltImproveSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearCubeData'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseWithServerNotice'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'list_index'], 'defaults': [], 'name': 'GetPossibleMakeQuantity'},
                     {'args': ['self', 'npc_vnum'], 'defaults': [], 'name': 'LoadCubeData'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAcceptCubeMake'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenCubemakeQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCubeWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshPossibleMakeQuantity'},
                     {'args': ['self', 'list_index'], 'defaults': [], 'name': 'RefreshRewardQuantity'},
                     {'args': ['self', 'list_index'], 'defaults': [], 'name': 'RefreshSelectItem'},
                     {'args': ['self', 'list_index', 'selected'], 'defaults': [], 'name': 'SelectItem'},
                     {'args': ['self', 'inventory'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickCancelButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickMakeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickResultQuantity'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnResultQuantityAdd'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnResultQuantityChange'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnResultQuantitySub'},
                     {'args': ['self', 'material_idx'], 'defaults': [], 'name': '__OverInCubeMaterialSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverInCubeRewardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutCubeMaterialSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutCubeRewardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__SelectEmptySlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'CubeWindow'}]},
           {'class': [], 'func': [{'args': ['self'], 'defaults': [], 'name': '__init__'}], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'CubeItem'}]},
           {'class': [],
            'func': [{'args': ['self', 'item_text'], 'defaults': [], 'name': 'SetOneTextLine'},
                     {'args': ['self', 'quantity_text', 'item_text'], 'defaults': [], 'name': 'SetTwoTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowClosedImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowOpendImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'cubeItem'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'ItemObject'}]},
           {'class': [],
            'func': [{'args': ['self', 'cube_item'], 'defaults': [], 'name': 'AddItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChildShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearItemList'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickFunc'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseItemChild'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'item_category'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'ItemGroup'}]},
           {'class': [],
            'func': [{'args': ['self', 'select'], 'defaults': [], 'name': 'EnableItem'},
                     {'args': ['self', 'item_text'], 'defaults': [], 'name': 'SetOneTextLine'},
                     {'args': ['self', 'quantity_text', 'item_text'], 'defaults': [], 'name': 'SetTwoTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowDefaultImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowSelectedImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleSelect'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'cubeItem'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiCubeRenewal'}, {'name': '__qualname__', 'type': 'str', 'value': 'ItemDetailObject'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}, {'args': ['wrapped', 'assigned', 'updated'], 'defaults': [('__module__', '__name__', '__doc__'), ('__dict__',)], 'name': 'wraps'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'ime', 'grp', 'uiToolTip', 'mouseModule', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'wndMgr', 'item', 'ui', 'uiCharacter'],
 'var': [{'name': 'BELT_IMPROVE_ITEM_VNUM', 'type': 'tuple', 'value': (79605,)},
         {'name': 'COLOR_DEFAULT', 'type': 'long', 'value': 4291348680L},
         {'name': 'COLOR_SELECT', 'type': 'long', 'value': 4293121989L},
         {'name': 'MAX_BELT_IMPROVE_ITEM_QUANTITY', 'type': 'int', 'value': 40},
         {'name': 'MAX_MAKE_QUANTITY', 'type': 'int', 'value': 9999},
         {'name': 'MAX_MATERIAL_COUNT', 'type': 'int', 'value': 5},
         {'name': 'MAX_MATERIAL_QUANTITY', 'type': 'int', 'value': 999},
         {'name': 'ROOT_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/cube/'},
         {'name': 'USE_CUBE_DISTANCE', 'type': 'int', 'value': 1000},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiCubeRenewal'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
