{'class': [{'class': [],
            'func': [{'args': ['self', 'inven', 'itemCount'], 'defaults': [], 'name': 'AutoSetItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'reason', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'RefineFail'},
                     {'args': ['self', 'inven_type', 'inven_pos'], 'defaults': [], 'name': 'RefineSucceed'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'wndInventory', 'wndDragonSoul'], 'defaults': [], 'name': 'SetInventoryWindows'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__CanRefineGrade'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__CanRefineStep'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__CanRefineStrength'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__CheckCanRefine'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearResultItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__FlushRefineItemSlot'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__GetDragonSoulTypeInfo'},
                     {'args': ['self', 'itemVnum'], 'defaults': [0], 'name': '__GetEmptySlot'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__GetRefineGradeRecipe'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__GetRefineStepRecipe'},
                     {'args': ['self', 'itemVnum'], 'defaults': [], 'name': '__GetRefineStrengthInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__IsDragonSoul'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'ds_type', 'grade', 'step', 'strength'], 'defaults': [], 'name': '__MakeDragonSoulVnum'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OverInRefineItem'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OverInResultItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutItem'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': '__PopUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__PressDoRefineButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshRefineItemSlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': '__SelectRefineEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': '__SelectRefineItemSlot'},
                     {'args': ['self', 'inven', 'dstSlotIndex', 'itemCount'], 'defaults': [], 'name': '__SetItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__ToggleDownGradeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ToggleDownStepButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ToggleDownStrengthButton'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': '__ToggleUpButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DRAGON_SOUL_SLOT', 'type': 'int', 'value': 1},
                    {'name': 'DS_SUB_HEADER_DIC', 'type': 'dict', 'value': {0: 2, 1: 3, 2: 4}},
                    {'name': 'INVALID_DRAGON_SOUL_INFO', 'type': 'int', 'value': -1},
                    {'name': 'REFINE_STONE_SLOT', 'type': 'int', 'value': 0},
                    {'name': 'REFINE_TYPE_GRADE', 'type': 'int', 'value': 0},
                    {'name': 'REFINE_TYPE_STEP', 'type': 'int', 'value': 1},
                    {'name': 'REFINE_TYPE_STRENGTH', 'type': 'int', 'value': 2},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiDragonSoul'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'DragonSoulRefineWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ActivateButtonClick'},
                     {'args': ['self', 'deck'], 'defaults': [], 'name': 'ActivateDragonSoulByExtern'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelDlgQuestion'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeactivateDragonSoul'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'HighlightSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsDlgQuestionShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self', 'overSlotPos'], 'defaults': [], 'name': 'OverInEquipItem'},
                     {'args': ['self', 'overSlotPos'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutEquipItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBagSlotWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshEquipSlotWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'selectedSlot'], 'defaults': [], 'name': 'SelectEmptyEquipSlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'itemSlotIndex'], 'defaults': [], 'name': 'SelectEquipItemSlot'},
                     {'args': ['self', 'itemSlotIndex'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SellItem'},
                     {'args': ['self', 'kindIndex'], 'defaults': [], 'name': 'SetDSKindIndex'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetDeckPage'},
                     {'args': ['self', 'wndDragonSoulRefine'], 'defaults': [], 'name': 'SetDragonSoulRefineWindow'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetInventoryPage'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'bUse'], 'defaults': [], 'name': 'SetUseItemMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'window_type', 'slotIndex'], 'defaults': [], 'name': 'ShowToolTip'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseEquipItemSlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__Accept'},
                     {'args': ['self'], 'defaults': [], 'name': '__Accept_DS_Equip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CanActivateDeck'},
                     {'args': ['self'], 'defaults': [], 'name': '__Cancel'},
                     {'args': ['self', 'deck'], 'defaults': [], 'name': '__DeckButtonDown'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__EquipItem'},
                     {'args': ['self', 'pos'], 'defaults': [], 'name': '__GetEquipSlotPos'},
                     {'args': ['self'], 'defaults': [], 'name': '__HighlightSlot_ClearCurrentPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__HighlightSlot_RefreshCurrentPage'},
                     {'args': ['self', 'window_type', 'local_slot_pos'], 'defaults': [], 'name': '__InventoryLocalSlotPosToGlobalSlotPos'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self', 'srcItemInvenType', 'srcItemPos', 'dstItemInvenType', 'dstItemPos'], 'defaults': [], 'name': '__OpenQuestionDialog'},
                     {'args': ['self', 'Equip', 'srcItemPos', 'dstItemPos'], 'defaults': [], 'name': '__OpenQuestionDialog_DS_Equip'},
                     {'args': ['self', 'itemSlotPos'], 'defaults': [], 'name': '__SellItem'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos', 'srcItemCount'], 'defaults': [], 'name': '__SendMoveItemPacket'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__UseEquipItem'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__UseItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'KIND_TAP_TITLES', 'type': 'list', 'value': ['S\xe1rk\xe1nygy\xe9m\xe1nt', 'S\xe1rk\xe1nyrubin', 'S\xe1rk\xe1nyj\xe1de', 'S\xe1rk\xe1nyzaf\xedr', 'S\xe1rk\xe1nygr\xe1n\xe1t', 'S\xe1rk\xe1ny\xf3nix']},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiDragonSoul'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'DragonSoulWindow'}]}],
 'func': [],
 'import': ['uiNewInventory', 'chatm2g', 'app', 'uiPrivateShopBuilder', 'uiPickMoney', 'm2netm2g', 'playerm2g2', 'uiRefine', 'constInfo', 'grp', 'uiInventory', 'uiAttachMetin', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'ime', 'sys', 'item', 'ui'],
 'var': [{'name': 'ITEM_FLAG_APPLICABLE', 'type': 'int', 'value': 16384}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiDragonSoul'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
