{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseWhenOpenQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitWebPage'},
                     {'args': ['self', 'url'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenWhenOpenQuest'},
                     {'args': ['self'], 'defaults': [], 'name': 'RequestOpenDutchAuctionWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'WEB_IMG_HEIGHT', 'type': 'int', 'value': 98},
                    {'name': 'WEB_IMG_WIDTH', 'type': 'int', 'value': 98},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiDutchAuction'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'DutchAuctionWindow'}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'chatm2g', 'app', 'm2netm2g', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiDutchAuction'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
