{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCloseEvent'},
                     {'args': ['self', 'slotIndex', 'attrIndex', 'type', 'value'], 'defaults': [], 'name': 'SetEquipmentDialogAttr'},
                     {'args': ['self', 'slot_index', 'vnum', 'count', 'change_look_vnum', 'refine_element', 'apply_random_list', 'set_value'], 'defaults': [], 'name': 'SetEquipmentDialogItem'},
                     {'args': ['self', 'slotIndex', 'socketIndex', 'value'], 'defaults': [], 'name': 'SetEquipmentDialogSocket'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiEquipmentDialog'}, {'name': '__qualname__', 'type': 'str', 'value': 'EquipmentDialog'}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'chr', 'playerm2g2', 'ui'],
 'var': [{'name': 'TYPE_INDEX_APPLY_RANDOM', 'type': 'int', 'value': 7},
         {'name': 'TYPE_INDEX_ATTR', 'type': 'int', 'value': 3},
         {'name': 'TYPE_INDEX_CHANGE_LOOK', 'type': 'int', 'value': 5},
         {'name': 'TYPE_INDEX_ITEM_COUNT', 'type': 'int', 'value': 1},
         {'name': 'TYPE_INDEX_ITEM_VNUM', 'type': 'int', 'value': 0},
         {'name': 'TYPE_INDEX_RARE_ATTR', 'type': 'int', 'value': 4},
         {'name': 'TYPE_INDEX_REFINE_ELEMENT', 'type': 'int', 'value': 6},
         {'name': 'TYPE_INDEX_SET_VALUE', 'type': 'int', 'value': 8},
         {'name': 'TYPE_INDEX_SOCKET', 'type': 'int', 'value': 2},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiEquipmentDialog'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
