{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'MainLoop'}, {'args': ['self'], 'defaults': [], 'name': 'OnInit'}, {'args': ['self', 'title'], 'defaults': ['METIN2 UI TEST'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiEx'}, {'name': '__qualname__', 'type': 'str', 'value': 'App'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClearDictionary'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'GetChild'},
                     {'args': ['self', 'name', 'child'], 'defaults': [], 'name': 'InsertChild'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'IsChild'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadSkin'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'skinFileName'], 'defaults': [''], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiEx'}, {'name': '__qualname__', 'type': 'str', 'value': 'Window'}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'systemSetting', 'ui', 'mouseModule', 'wndMgr'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiEx'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
