{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'FlowerEventProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__ImgOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__ImgOverOut'},
                     {'args': ['self', 'shootType'], 'defaults': [], 'name': '__OnClickListExchangeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiFlowerEvent'}, {'name': '__qualname__', 'type': 'str', 'value': 'FlowerEvent'}]}],
 'func': [],
 'import': ['event', 'uiCommon', 'uiToolTip', '__builtin__', 'chatm2g', 'app', 'uiScriptLocale', 'm2netm2g', 'playerm2g2', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiFlowerEvent'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
