{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'FlowerEventGetItemMessage', 'type': 'classmethod', 'value': <classmethod object at 0x0B5B0090>},
                    {'name': 'FlowerEventMessage', 'type': 'classmethod', 'value': <classmethod object at 0x0B5B00B0>},
                    {'name': 'IsFlowerEventEnd', 'type': 'classmethod', 'value': <classmethod object at 0x0B5B00D0>},
                    {'name': '_FlowerEventUtil__FLOWER_EVENT_LOCA',
                     'type': 'dict',
                     'value': {0: 'Nincs n\xe1lad el\xe9g hajt\xe1s.',
                               1: 'Nincs el\xe9g helyed a lelt\xe1radban.',
                               2: 'Nincs n\xe1lad el\xe9g vir\xe1gmag.',
                               3: 'Vir\xe1gmagokat kapt\xe1l.',
                               4: 'Krizant\xe9m hajt\xe1sokat kapt\xe1l.',
                               5: 'Gy\xf6ngyvir\xe1g hajt\xe1sokat kapt\xe1l.',
                               6: 'N\xe1rcisz hajt\xe1sokat kapt\xe1l.',
                               7: 'Liliom hajt\xe1sokat kapt\xe1l.',
                               8: 'Napraforg\xf3 hajt\xe1sokat kapt\xe1l.',
                               9: 'Nem haszn\xe1lhatod ezt a t\xe1rgyat, mert m\xe1r a maxim\xe1lis mennyis\xe9g\xfb hajt\xe1s van n\xe1lad.'}},
                    {'name': '_FlowerEventUtil__GET_SHOOT_MESSAGE_TYPE', 'type': 'dict', 'value': {0: 3, 1: 4, 2: 5, 3: 6, 4: 7, 5: 8}},
                    {'name': '_FlowerEventUtil__GET_SHOOT_MESSAGE_TYPE__FLOWER_EVENT_LOCA', 'type': 'member_descriptor', 'value': <member '_FlowerEventUtil__GET_SHOOT_MESSAGE_TYPE__FLOWER_EVENT_LOCA' of 'FlowerEventUtil' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiFlowerEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'FlowerEventUtil'},
                    {'name': '__slots__', 'type': 'str', 'value': '__GET_SHOOT_MESSAGE_TYPE__FLOWER_EVENT_LOCA'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'InGameEventProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__ImgOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__ImgOverOut'},
                     {'args': ['self', 'shoot_type'], 'defaults': [], 'name': '__OnClickListExchangeButton'},
                     {'args': ['self', 'shoot_type', 'shoot_count'], 'defaults': [], 'name': '__SetFlowerEventInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiFlowerEvent'}, {'name': '__qualname__', 'type': 'str', 'value': 'FlowerEvent'}]}],
 'func': [],
 'import': ['event', 'uiCommon', 'uiToolTip', '__builtin__', 'chatm2g', 'app', 'uiScriptLocale', 'm2netm2g', 'playerm2g2', 'ui', 'wndMgr', 'ingameEventSystem', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiFlowerEvent'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
