{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'IsFootballEventEnd', 'type': 'classmethod', 'value': <classmethod object at 0x2D1D2850>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'FootballEventUtil' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiFootballEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'FootballEventUtil'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'FootballEventUtil' objects>}]}],
 'func': [],
 'import': ['event', 'uiCommon', 'exception', '__builtin__', 'chatm2g', 'app', 'item', 'playerm2g2', 'ui', 'footballEventModule', 'uiScriptLocale', 'ingameEventSystem', 'localeInfo', 'uiMiniGame'],
 'var': [{'name': 'FootballEvent', 'type': 'ABCMeta', 'value': <class 'uiFootballEvent.FootballEvent'>},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiFootballEvent'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
