{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptGuildWarEnter'},
                     {'args': ['self', 'fee'], 'defaults': [], 'name': 'AcceptMistsIslandWarp'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'popup_notice_window'], 'defaults': [], 'name': 'BindPopupNoticeWindow'},
                     {'args': ['self', 'is_blink'], 'defaults': [], 'name': 'BlinkPopupNoticeIcon'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckGameButton'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePopUpDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideBuildButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'HideButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideGuildWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HidePopupNoticeButtonAnimImage'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPopupNoticeIconBlink'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'name', 'event'], 'defaults': [], 'name': 'SetButtonEvent'},
                     {'args': ['self', 'isEnable', 'isButtonShow'], 'defaults': [], 'name': 'SetObserverMode'},
                     {'args': ['self', 'is_blink'], 'defaults': [], 'name': 'SetPopupNoticeIconBlink'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowBuildButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'ShowButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowGuildWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateButtonToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HidePopupNoticeButtonToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsSkillStat'},
                     {'args': ['self', 'filename'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MistsIslandWarp'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickExitObserver'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMouseOverInPopupNoticeAnimImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMouseOverInPopupNoticeBtn'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMouseOverOutPopupNoticeBtn'},
                     {'args': ['self'], 'defaults': [], 'name': '__RequestGuildWarEnter'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowPopupNoticeButtonAnimImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowPopupNoticeButtonToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'POPUP_NOTICE_BUTTON_TOOLTIP_GAP_NUMBER', 'type': 'int', 'value': 50},
                    {'name': 'WARP_MI_TIME', 'type': 'int', 'value': 30},
                    {'name': '_GameButtonWindow__game_button_tooltip', 'type': 'member_descriptor', 'value': <member '_GameButtonWindow__game_button_tooltip' of 'GameButtonWindow' objects>},
                    {'name': '_GameButtonWindow__interface', 'type': 'member_descriptor', 'value': <member '_GameButtonWindow__interface' of 'GameButtonWindow' objects>},
                    {'name': '_GameButtonWindow__is_popup_notice_btn_blink', 'type': 'member_descriptor', 'value': <member '_GameButtonWindow__is_popup_notice_btn_blink' of 'GameButtonWindow' objects>},
                    {'name': '_GameButtonWindow__popup_notice_icon_anim_img', 'type': 'member_descriptor', 'value': <member '_GameButtonWindow__popup_notice_icon_anim_img' of 'GameButtonWindow' objects>},
                    {'name': '_GameButtonWindow__popup_notice_window', 'type': 'member_descriptor', 'value': <member '_GameButtonWindow__popup_notice_window' of 'GameButtonWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGameButton'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GameButtonWindow'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__is_popup_notice_btn_blink', '__is_popup_notice_btn_blink', '__popup_notice_icon_anim_img', '__interface', '__game_button_tooltip', '__popup_notice_window')}]}],
 'func': [],
 'import': ['uiCommon', 'uiToolTip', '__builtin__', 'app', 'wndMgr', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiGameButton'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
