{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptGuildWarEnter'},
                     {'args': ['self', 'fee'], 'defaults': [], 'name': 'AcceptMistsIslandWarp'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckGameButton'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePopUpDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideBuildButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'HideButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideGuildWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'name', 'event'], 'defaults': [], 'name': 'SetButtonEvent'},
                     {'args': ['self', 'isEnable', 'isButtonShow'], 'defaults': [], 'name': 'SetObserverMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowBuildButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'ShowButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowGuildWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllGameButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsSkillStat'},
                     {'args': ['self', 'filename'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MistsIslandWarp'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickExitObserver'},
                     {'args': ['self'], 'defaults': [], 'name': '__RequestGuildWarEnter'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'WARP_MI_TIME', 'type': 'int', 'value': 30}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGameButton'}, {'name': '__qualname__', 'type': 'str', 'value': 'GameButtonWindow'}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'app', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiGameButton'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
