{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'slotindex', 'enable'], 'defaults': [], 'name': 'GemShopSlotAdd'},
                     {'args': ['self', 'slotindex', 'enable'], 'defaults': [], 'name': 'GemShopSlotBuy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGemShopWIndow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshItemSlot'},
                     {'args': ['self', 'slotindex'], 'defaults': [], 'name': 'SendBuyAccept'},
                     {'args': ['self'], 'defaults': [], 'name': 'SendRequestRefreshAccept'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'SlotAddQuestion'},
                     {'args': ['self'], 'defaults': [], 'name': 'SlotAddQuestionAccept'},
                     {'args': ['self'], 'defaults': [], 'name': 'SlotAddQuestionCancle'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'GEM_SHOP_ADD_ITEM_VNUM', 'type': 'int', 'value': 39064},
                    {'name': 'GEM_SHOP_REFRESH_ITEM_VNUM', 'type': 'int', 'value': 39063},
                    {'name': 'GEM_SHOP_SLOT_MAX', 'type': 'int', 'value': 9},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGemShop'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GemShopWindow'}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'uiPrivateShopBuilder', 'uiPickMoney', 'm2netm2g', 'playerm2g2', 'uiRefine', 'constInfo', 'grp', 'uiToolTip', 'uiAttachMetin', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'ime', 'wndMgr', 'item', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiGemShop'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
