{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self', 'remain_kill_count'], 'defaults': [], 'name': 'SetRemainMineTowerKillCount'},
                                {'args': ['self', 'remain_kill_count'], 'defaults': [], 'name': 'SetRemainStoneKillCount'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_SubBoard__remain_mine_tower_kill_count_text', 'type': 'member_descriptor', 'value': <member '_SubBoard__remain_mine_tower_kill_count_text' of 'SubBoard' objects>},
                               {'name': '_SubBoard__remain_stone_kill_count_text', 'type': 'member_descriptor', 'value': <member '_SubBoard__remain_stone_kill_count_text' of 'SubBoard' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandInformationBoard.SubBoard'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__remain_stone_kill_count_text', '__remain_mine_tower_kill_count_text')}]}],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'remain_kill_count'], 'defaults': [], 'name': 'SetRemainMineTowerKillCount'},
                     {'args': ['self', 'remain_kill_count'], 'defaults': [], 'name': 'SetRemainStoneKillCount'},
                     {'args': ['self', 'stage_num'], 'defaults': [], 'name': 'SetStageNumber'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'stage_num', 'end_time', 'limit_time'], 'defaults': [], 'name': 'ShowInformationBoard'},
                     {'args': ['self', 'is_show'], 'defaults': [], 'name': 'ShowSubBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickExitButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnExitDungeon'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverInStageTextWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutStageTextWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateStageNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_GoldenLandInformationBoard__dungeon_end_time', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__dungeon_end_time' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__dungeon_limit_time_sec', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__dungeon_limit_time_sec' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__exit_button', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__exit_button' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__exit_question_dialog', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__exit_question_dialog' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__interface', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__interface' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__is_requested_to_exit', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__is_requested_to_exit' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__remain_kill_count_window', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__remain_kill_count_window' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__stage_number', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__stage_number' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__stage_text', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__stage_text' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__stage_text_window', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__stage_text_window' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__stage_text_window_tooltip', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__stage_text_window_tooltip' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__time_gauge', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__time_gauge' of 'GoldenLandInformationBoard' objects>},
                    {'name': '_GoldenLandInformationBoard__time_text', 'type': 'member_descriptor', 'value': <member '_GoldenLandInformationBoard__time_text' of 'GoldenLandInformationBoard' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandInformationBoard'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__stage_number', '__dungeon_end_time', '__dungeon_limit_time_sec', '__is_requested_to_exit', '__stage_text_window', '__stage_text', '__stage_text_window_tooltip', '__time_gauge', '__time_text', '__exit_button', '__exit_question_dialog', '__remain_kill_count_window', '__interface')}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self', 'card_index', 'is_golden_fruit'], 'defaults': [], 'name': 'CardOpenResult'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshYellowFruitCount'},
                     {'args': ['self', 'need_yellow_fruit_count'], 'defaults': [], 'name': 'Reset'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'SetNeedYellowFruitCount'},
                     {'args': ['self', 'opened_card_flag', 'golden_fruit_card_in_opened_card_flag'], 'defaults': [], 'name': 'SetOpenedCardInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceptGoldenLandReset'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__AcceptOpenCard'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__ClickSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnEndFrameSuccessTextEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnResetButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenAllCardStepByStepProcess'},
                     {'args': ['self', 'opened_card_flag'], 'defaults': [], 'name': '__OpenedCardFlagToOpenedCardList'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__OverInCardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverInRewardItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutCardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutRewardItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__Refresh'},
                     {'args': ['self', 'item_vnum', 'item_count'], 'defaults': [], 'name': '__SetRewardItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowSuccessEffectAnimation'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CARD_GRID_SLOT_COLUMN_COUNT', 'type': 'int', 'value': 8},
                    {'name': 'CARD_GRID_SLOT_ROW_COUNT', 'type': 'int', 'value': 4},
                    {'name': 'CARD_OPEN_STEP_BY_STEP_INTERVAL_MSEC', 'type': 'int', 'value': 50},
                    {'name': '_FindGoldenFruit__card_slot', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__card_slot' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__find_card_question_dialog', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__find_card_question_dialog' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__golden_fruit_card_in_opened_card_flag', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__golden_fruit_card_in_opened_card_flag' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__interface', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__interface' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__is_found_all_golden_fruit', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__is_found_all_golden_fruit' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__is_opening_all_card_step_by_step', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__is_opening_all_card_step_by_step' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__is_waiting_animation_end', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__is_waiting_animation_end' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__need_yellow_fruit_count_text', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__need_yellow_fruit_count_text' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__open_pos_x', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__open_pos_x' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__open_pos_y', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__open_pos_y' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__opened_card', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__opened_card' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__opened_card_flag', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__opened_card_flag' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__over_in_slot_index', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__over_in_slot_index' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__prev_card_open_time', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__prev_card_open_time' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__reset_button', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__reset_button' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__reward_item_count', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__reward_item_count' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__reward_item_slot', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__reward_item_slot' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__reward_item_vnum', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__reward_item_vnum' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__step_by_step_card_index', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__step_by_step_card_index' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__success_firework_effect_1', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__success_firework_effect_1' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__success_firework_effect_2', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__success_firework_effect_2' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__success_firework_effect_3', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__success_firework_effect_3' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__success_text_effect', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__success_text_effect' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__tooltip_item', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__tooltip_item' of 'FindGoldenFruit' objects>},
                    {'name': '_FindGoldenFruit__yellow_fruit_count_text', 'type': 'member_descriptor', 'value': <member '_FindGoldenFruit__yellow_fruit_count_text' of 'FindGoldenFruit' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'FindGoldenFruit'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__reward_item_slot',
                               '__card_slot',
                               '__need_yellow_fruit_count_text',
                               '__yellow_fruit_count_text',
                               '__find_card_question_dialog',
                               '__success_firework_effect_1',
                               '__success_firework_effect_2',
                               '__success_firework_effect_3',
                               '__success_text_effect',
                               '__reset_button',
                               '__over_in_slot_index',
                               '__opened_card',
                               '__opened_card_flag',
                               '__golden_fruit_card_in_opened_card_flag',
                               '__reward_item_vnum',
                               '__reward_item_count',
                               '__is_found_all_golden_fruit',
                               '__is_waiting_animation_end',
                               '__is_opening_all_card_step_by_step',
                               '__step_by_step_card_index',
                               '__prev_card_open_time',
                               '__open_pos_x',
                               '__open_pos_y',
                               '__interface',
                               '__tooltip_item')}]},
           {'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'AppendChat', 'type': 'classmethod', 'value': <classmethod object at 0x1E276370>},
                    {'name': 'GetInformationBoardStageTextTooltip', 'type': 'classmethod', 'value': <classmethod object at 0x1E276330>},
                    {'name': 'GetInformationBoardStageTextTooltipCount', 'type': 'classmethod', 'value': <classmethod object at 0x1E276350>},
                    {'name': 'InitializeLoca', 'type': 'classmethod', 'value': <classmethod object at 0x1E276310>},
                    {'name': '_GoldenLandUtil__GOLDEN_LAND_LOCA',
                     'type': 'dict',
                     'value': {0: 'Elindult az \xd5si exped\xedci\xf3! Gy\xf5zd le az \xd5si \xf5rt, \xe9s utazz Aranyf\xf6ldre!',
                               1: 'Az \xd5si exped\xedci\xf3 v\xe9get \xe9rt.',
                               2: 'A k\xf6vetkez\xf5 szintre leszel teleport\xe1lva.',
                               3: 'Az o\xe1zisba leszel teleport\xe1lva.',
                               4: '\xd5si szobrok jelennek meg 10 m\xe1sodperc m\xfalva.',
                               5: 'A Karav\xe1n keresked\xf5n\xe9l t\xe1rgyakat v\xe1s\xe1rolhatsz.',
                               6: 'Az Aranyf\xf6ld\xf6n csak %d percig maradhatsz.',
                               7: 'Kapt\xe1l %d Keser\xfbbogy\xf3t.',
                               8: 'Kapt\xe1l %d Aranybogy\xf3t.',
                               9: 'Kapt\xe1l %d Keser\xfbbogy\xf3t. (Most %d van.)',
                               10: 'Nincs el\xe9g Keser\xfbbogy\xf3d.',
                               11: 'Nincs el\xe9g hely a lelt\xe1radban.',
                               12: 'Nem tudsz t\xf6bb Aranybogy\xf3t venni, mivel m\xe1r t\xfall\xe9pted a maximumot.',
                               13: 'Nincs el\xe9g Aranybogy\xf3d.',
                               14: 'Tal\xe1lt\xe1l egy Aranybogy\xf3 n\xe9gyzetet!',
                               15: '\xdagy t\xfbnik, ez nem egy Aranybogy\xf3 n\xe9gyzet volt.',
                               16: 'Megtal\xe1ltad az \xf6sszes Aranybogy\xf3 n\xe9gyzetet! A jutalmadat post\xe1n kereszt\xfcl fogod megkapni.',
                               17: 'Nincs n\xe1lad \xd5si vissza\xe1ll\xedt\xf3.',
                               18: 'Ezt m\xe1r vissza\xe1ll\xedtottad.',
                               19: 'A bel\xe9p\xe9seid sz\xe1ma \xe9s a j\xe1t\xe9kt\xe1bla vissza\xe1ll\xedt\xe1sra ker\xfclt.',
                               20: 'Most m\xe1r Bombabiztos vagy \xe9s v\xe9dett a k\xf6vetkez\xf5 Bomba toronyt\xf3l.',
                               21: 'A Bombabiztos b\xf3nusz megv\xe9dett \xe9s felhaszn\xe1l\xe1sra ker\xfclt. A Bomba tornyok ism\xe9t sebezhetnek t\xe9ged.'}},
                    {'name': '_GoldenLandUtil__INFORMATION_BOARD_STAGE_TEXT_TOOLTIP',
                     'type': 'dict',
                     'value': {1: '1. szint', 2: '2. szint', 3: '3. szint', 4: '4. szint (o\xe1zis)', 5: '5. szint', 6: '6. szint', 7: '7. szint', 8: '8. szint (o\xe1zis)', 9: '9. szint', 10: '10. szint', 11: '11. szint', 12: '12. szint (o\xe1zis)'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandUtil'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__INFORMATION_BOARD_STAGE_TEXT_TOOLTIP', '__GOLDEN_LAND_LOCA')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self', 'tree_fruit_count'], 'defaults': [], 'name': 'SetTreeFruitCount'},
                                {'args': ['self', 'yellow_fruit_count'], 'defaults': [], 'name': 'SetYellowFruitCount'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_SubBoard__tree_fruit_count_text', 'type': 'member_descriptor', 'value': <member '_SubBoard__tree_fruit_count_text' of 'SubBoard' objects>},
                               {'name': '_SubBoard__tree_fruit_icon_img', 'type': 'member_descriptor', 'value': <member '_SubBoard__tree_fruit_icon_img' of 'SubBoard' objects>},
                               {'name': '_SubBoard__yellow_fruit_count_text', 'type': 'member_descriptor', 'value': <member '_SubBoard__yellow_fruit_count_text' of 'SubBoard' objects>},
                               {'name': '_SubBoard__yellow_fruit_icon_img', 'type': 'member_descriptor', 'value': <member '_SubBoard__yellow_fruit_icon_img' of 'SubBoard' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandOasisShop.SubBoard'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__tree_fruit_icon_img', '__tree_fruit_count_text', '__yellow_fruit_icon_img', '__yellow_fruit_count_text')}]}],
            'func': [{'args': ['self', 'flag'], 'defaults': [], 'name': 'AnswerBuyItem'},
                     {'args': ['self', 'slot_pos'], 'defaults': [], 'name': 'AskBuyItem'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'slot_pos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'slot_pos'], 'defaults': [], 'name': 'UnselectItemSlot'},
                     {'args': ['self', 'slot_pos'], 'defaults': [], 'name': '__CanBuyMerch'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshSubBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'SHOP_MERCH_TOOLTIP_COLOR_DISABLE', 'type': 'int', 'value': -1738635},
                    {'name': 'SHOP_MERCH_TOOLTIP_COLOR_ENABLE', 'type': 'int', 'value': -4079167},
                    {'name': 'SHOP_MERCH_TOOLTIP_COLOR_TITLE', 'type': 'int', 'value': -923968},
                    {'name': 'YELLOW_FRUIT_SLOT_IMG', 'type': 'int', 'value': 200981848},
                    {'name': '_GoldenLandOasisShop__merch_info_by_pos', 'type': 'member_descriptor', 'value': <member '_GoldenLandOasisShop__merch_info_by_pos' of 'GoldenLandOasisShop' objects>},
                    {'name': '_GoldenLandOasisShop__sub_board', 'type': 'member_descriptor', 'value': <member '_GoldenLandOasisShop__sub_board' of 'GoldenLandOasisShop' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandOasisShop'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__sub_board', '__merch_info_by_pos')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'}, {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandEvent.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshTreeFruitCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshYellowFruitCount'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextDescriptionPage'},
                     {'args': ['self', 'tooltip_text'], 'defaults': [], 'name': '__OverInFruitImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutFruitImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_GoldenLandEvent__button_next', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__button_next' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__button_prev', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__button_prev' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__desc_board', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__desc_board' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__desc_box', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__desc_box' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__desc_index', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__desc_index' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__desc_line_count', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__desc_line_count' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__desc_y', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__desc_y' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__tooltip_fruit_image', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__tooltip_fruit_image' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__tree_fruit_count_text', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__tree_fruit_count_text' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__tree_fruit_slot', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__tree_fruit_slot' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__yellow_fruit_count_text', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__yellow_fruit_count_text' of 'GoldenLandEvent' objects>},
                    {'name': '_GoldenLandEvent__yellow_fruit_slot', 'type': 'member_descriptor', 'value': <member '_GoldenLandEvent__yellow_fruit_slot' of 'GoldenLandEvent' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandEvent'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__desc_board', '__desc_box', '__button_prev', '__button_next', '__tree_fruit_slot', '__yellow_fruit_slot', '__tree_fruit_count_text', '__yellow_fruit_count_text', '__tooltip_fruit_image', '__desc_index', '__desc_line_count', '__desc_y')}]},
           {'class': [],
            'func': [{'args': ['self', 'chat_type', 'message_type', 'data'], 'defaults': [None], 'name': 'AppendChat'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenFindGoldenFruit'},
                     {'args': ['self', 'stage_num', 'end_time', 'limit_time'], 'defaults': [], 'name': 'OpenGoldenLandInformationBoard'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'OpenGoldenLandOasisShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshFruitCountInfo'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_GoldenLandInterface__find_golden_fruit', 'type': 'member_descriptor', 'value': <member '_GoldenLandInterface__find_golden_fruit' of 'GoldenLandInterface' objects>},
                    {'name': '_GoldenLandInterface__golden_land_information_board', 'type': 'member_descriptor', 'value': <member '_GoldenLandInterface__golden_land_information_board' of 'GoldenLandInterface' objects>},
                    {'name': '_GoldenLandInterface__golden_land_oasis_shop', 'type': 'member_descriptor', 'value': <member '_GoldenLandInterface__golden_land_oasis_shop' of 'GoldenLandInterface' objects>},
                    {'name': '_GoldenLandInterface__hide_windows_when_quest_opened', 'type': 'member_descriptor', 'value': <member '_GoldenLandInterface__hide_windows_when_quest_opened' of 'GoldenLandInterface' objects>},
                    {'name': '_GoldenLandInterface__interface', 'type': 'member_descriptor', 'value': <member '_GoldenLandInterface__interface' of 'GoldenLandInterface' objects>},
                    {'name': '_GoldenLandInterface__tooltip_item', 'type': 'member_descriptor', 'value': <member '_GoldenLandInterface__tooltip_item' of 'GoldenLandInterface' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGoldenLand'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GoldenLandInterface'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__golden_land_information_board', '__golden_land_oasis_shop', '__find_golden_fruit', '__hide_windows_when_quest_opened', '__interface', '__tooltip_item')}]}],
 'func': [],
 'import': ['shop', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'event', 'goldenLand', 'constInfo', 'grp', 'uiToolTip', 'uiShop', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'grpImage', 'wndMgr', 'exception', 'item', 'ui'],
 'var': [{'name': 'EMPTY_ATTR_SLOT', 'type': 'list', 'value': [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0)]},
         {'name': 'EMPTY_METIN_SLOT', 'type': 'list', 'value': [0, 0, 0, 0, 0, 0]},
         {'name': 'GOLDEN_LAND_UI_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/golden_land/'},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiGoldenLand'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
