{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGradeName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGradeNumber'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'gradeNumber'], 'defaults': [], 'name': 'SetGradeNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChangeGradeNameDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'}, {'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': 'Up'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'MouseReflector'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'EditableTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'TEXT_LIMIT', 'type': 'int', 'value': 35}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'CommentSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self', 'allyGuildID', 'enemyGuildID'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'gainGuildID', 'opponetGuildID', 'point'], 'defaults': [], 'name': 'SetScore'},
                     {'args': ['self', 'guildID1', 'memberCount1', 'guildID2', 'memberCount2'], 'defaults': [], 'name': 'UpdateMemberCount'},
                     {'args': ['self', 'ID'], 'defaults': [], 'name': '__GetDataDict'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshName'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWarScoreBoard'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'page'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Build'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeWindowUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destory'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositioningMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'x', 'y', 'z'], 'defaults': [], 'name': 'SetBuildingPosition'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'SettleCurrentPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__AskExchangeTenth'},
                     {'args': ['self'], 'defaults': [], 'name': '__ChangeWindowOpen'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__CreateBuildInInstance'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__CreateInstance'},
                     {'args': ['self', 'race', 'x', 'y', 'rot'], 'defaults': [0.0], 'name': '__CreateWallBlock'},
                     {'args': ['self'], 'defaults': [], 'name': '__DeleteInstance'},
                     {'args': ['self'], 'defaults': [], 'name': '__DisablePCBlocker'},
                     {'args': ['self'], 'defaults': [], 'name': '__EnablePCBlocker'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetBuildInPosition'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__GetObjectSize'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialLog'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialPlywood'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialStone'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMoney'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsTenthEventObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LockCameraMoving'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeRotation'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnEnterPreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnLeavePreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBuildingList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectBuilding'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectCategory'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectPositioningMode'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__PopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__RestoreViewMode'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__SetBuildingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__TenthEventDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__UnlockCameraMoving'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUILDINGLIST_BASE_WIDTH', 'type': 'int', 'value': 135},
                    {'name': 'BUILDING_ALPHA', 'type': 'float', 'value': 0.55},
                    {'name': 'DISABLE_COLOR', 'type': 'int', 'value': -1738635},
                    {'name': 'ENABLE_COLOR', 'type': 'int', 'value': -4079167},
                    {'name': 'GUILD_CATEGORY_LIST', 'type': 'tuple', 'value': (('HEADQUARTER', 'Hauptgeb\xe4ude'), ('FACILITY', 'Nebengeb\xe4ude'), ('OBJECT', 'Objekte'))},
                    {'name': 'MODE_POSITIONING', 'type': 'int', 'value': 1},
                    {'name': 'MODE_PREVIEW', 'type': 'int', 'value': 2},
                    {'name': 'MODE_VIEW', 'type': 'int', 'value': 0},
                    {'name': 'START_INSTANCE_INDEX', 'type': 'int', 'value': 123450},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BuildGuildBuildingWindow'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetScriptFileName'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent', 'filename'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWindow.PageWindow'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGuildListDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePopUpDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteGuild'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'localPos'], 'defaults': [], 'name': 'GetMemberData'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildListDialogIsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildWarEnd'},
                     {'args': ['self', 'guildSelf', 'Oppguild'], 'defaults': [], 'name': 'GuildWarOppGuildNameSetting'},
                     {'args': ['self', 'gainGuildID', 'guildOpp', 'point', 'winpoint'], 'defaults': [], 'name': 'GuildWarScoreSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeGradeName'},
                     {'args': ['self', 'lineIndex', 'gradeNumber'], 'defaults': [], 'name': 'OnChangeMemberGrade'},
                     {'args': ['self', 'argIndex', 'argAuthority'], 'defaults': [], 'name': 'OnCheckAuthority'},
                     {'args': ['self', 'Text1', 'Text2', 'TitleBar', 'Event'], 'defaults': [], 'name': 'OnCreateGuildPopUp'},
                     {'args': ['self', 'Text'], 'defaults': [], 'name': 'OnCreatePopUp'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'OnDeleteComment'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnDeposit'},
                     {'args': ['self', 'lineIndex'], 'defaults': [], 'name': 'OnEnableGeneral'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnEndGuildWar'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGuildBaseDealButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGuildBaseDealVoteButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDownInBoardPage'},
                     {'args': ['self', 'exp'], 'defaults': [], 'name': 'OnOffer'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnOpenChangeGradeName'},
                     {'args': ['self', 'skillSlotIndex', 'type'], 'defaults': [], 'name': 'OnPickUpGuildSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPostComment'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRefreshComments'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScrollMemberLine'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnStartGuildWar'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OnUpGuildSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OnUseGuildSkill'},
                     {'args': ['self', 'slotNumber', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnWithdraw'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': 'OpenGuildGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildListDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildScoreWindow'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPageBankGold'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBoardPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageGradeComboBox'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageMemberList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberSelectBox'},
                     {'args': ['self', 'issearch'], 'defaults': [], 'name': 'RefreshGuildRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildWarInfoPage'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self', 'tooltipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseAllGuildMemberPageGradeComboBox'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__GetGuildBoardCommentData'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBoardPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAcceptEventChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlock'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDeclareWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDepositButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickGuildListButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOfferButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSelectGuildMarkButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSelectGuildSymbolButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWithdrawButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBankGolInfoButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseAbandon'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseAbandonButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseDeal'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': '__OnGuildGoldInDialog'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': '__OnGuildGoldInOutButton'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': '__OnGuildGoldOutDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildWarScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnHealGSP'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOpenHealGSPBoard'},
                     {'args': ['self', 'healGSP'], 'defaults': [], 'name': '__OnOpenHealGSPQuestionDialog'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnOutMember'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOutMemberStart'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnReQuestionEventChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollsmelterList'},
                     {'args': ['self', 'markFileName'], 'defaults': [], 'name': '__OnSelectMark'},
                     {'args': ['self', 'symbolFileName'], 'defaults': [], 'name': '__OnSelectSymbol'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnVoteCheck'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'EMPIRE_NAME', 'type': 'dict', 'value': {1: 'Shinsoo-Reich', 2: 'Chunjo-Reich', 3: 'Jinno-Reich'}},
                    {'name': 'EMPIRE_NAME_TO_MAPINDEX',
                     'type': 'dict',
                     'value': {1: 'Shinsoo-Reich', 3: 'Shinsoo-Reich', 4: 'Shinsoo-Reich', 6: 'Shinsoo-Reich', 21: 'Chunjo-Reich', 23: 'Chunjo-Reich', 24: 'Chunjo-Reich', 26: 'Chunjo-Reich', 41: 'Jinno-Reich', 43: 'Jinno-Reich', 44: 'Jinno-Reich', 46: 'Jinno-Reich'}},
                    {'name': 'GRADE_ADD_MEMBER_AUTHORITY', 'type': 'int', 'value': 1},
                    {'name': 'GRADE_BANK_AUTHORITY', 'type': 'int', 'value': 6},
                    {'name': 'GRADE_NOTICE_AUTHORITY', 'type': 'int', 'value': 3},
                    {'name': 'GRADE_REMOVE_MEMBER_AUTHORITY', 'type': 'int', 'value': 2},
                    {'name': 'GRADE_SKILL_AUTHORITY', 'type': 'int', 'value': 4},
                    {'name': 'GRADE_SLOT_NAME', 'type': 'int', 'value': 0},
                    {'name': 'GRADE_WAR_AUTHORITY', 'type': 'int', 'value': 5},
                    {'name': 'GUILD_SKILL_ACTIVE_SLOT', 'type': 'int', 'value': 1},
                    {'name': 'GUILD_SKILL_AFFECT_SLOT', 'type': 'int', 'value': 2},
                    {'name': 'GUILD_SKILL_PASSIVE_SLOT', 'type': 'int', 'value': 0},
                    {'name': 'JOB_NAME', 'type': 'dict', 'value': {0: 'Krieger', 1: 'Ninja', 2: 'Sura', 3: 'Schamane', 4: 'Lykaner'}},
                    {'name': 'MAP_NAME', 'type': 'dict', 'value': {0: '', 1: 'Gebiet Yongan', 3: 'Gebiet Jayang', 4: 'Jungrang', 6: 'Miryang', 21: 'Gebiet Joan', 23: 'Gebiet Bokjung', 24: 'Waryong', 26: 'Songpa', 41: 'Gebiet Pyungmoo', 43: 'Gebiet Bakra', 44: 'Imha', 46: 'Daeyami'}},
                    {'name': 'MEMBER_LINE_COUNT', 'type': 'int', 'value': 11},
                    {'name': 'PLUS_LEFT_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'PLUS_RIGHT_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'PLUS_WIDTH', 'type': 'int', 'value': 80},
                    {'name': 'WAR_NAME', 'type': 'dict', 'value': {0: 'Feldschlacht', 1: 'Arenakampf', 2: 'Flaggenkampf', 3: 'Vernichtungskampf', 4: 'Schildkampf', 5: 'Zeitangriff'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GuildWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetOpend'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildWarEnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'OppGuildId'], 'defaults': [], 'name': 'SetOppGuildName'},
                     {'args': ['self', 'gainGuildId', 'point', 'winpoint'], 'defaults': [], 'name': 'SetWarPoint'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWarScoreDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnTypeButtonClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'DeclearGuildWarSelectDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/public/Parameter_Slot_07.sub'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGuildName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGuildWarTypes'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetType'},
                     {'args': ['self', 'guildName', 'warType', 'winType', 'ScoreType', 'TimeType'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetCancelEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarScoreName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarTimeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarTypeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarWinName'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'AcceptGuildWarDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetType'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self'], 'defaults': [], 'name': '__AllWarButtonSetUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'buttonlist'], 'defaults': [], 'name': '__NotUseWarButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCancel'},
                     {'args': ['self', 'wartype', 'buttonlist'], 'defaults': [], 'name': '__OnClickTypeWarWin'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWarTypeSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOK'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'DeclareGuildWarDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self'], 'defaults': [], 'name': 'AllClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseQuestionDialog'},
                     {'args': ['self', 'race', 'objectx', 'objecty', 'rot_z'], 'defaults': [], 'name': 'CreateEmptyObject'},
                     {'args': ['self'], 'defaults': [], 'name': 'Delete'},
                     {'args': ['self'], 'defaults': [], 'name': 'DestoryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositionChangeMode'},
                     {'args': ['self', 'str', 'acceptevent'], 'defaults': [], 'name': 'MakeQuestionDialog'},
                     {'args': ['self', 'str1', 'str2', 'acceptevent'], 'defaults': [], 'name': 'MakeQuestionDialog2'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RealClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectList'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectObject'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetBuildGuildBuildingWindow'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetCameraSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChangeBuildingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Update'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeRotation'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBuildingList'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__SetBuildingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'LIST_BOX_BASE_WIDHT', 'type': 'int', 'value': 165},
                    {'name': 'SHOW_LIST_MAX', 'type': 'int', 'value': 10},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BuildGuildBuildingChangeWindow'}]}],
 'func': [{'args': ['srcGuildID', 'dstGuildID'], 'defaults': [], 'name': 'GetGVGKey'}, {'args': ['n'], 'defaults': [], 'name': 'NumberToMoneyString'}, {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}, {'args': ['n'], 'defaults': [], 'name': 'unsigned32'}],
 'import': ['miniMap',
            'app',
            'playerSettingModule',
            'uiPickMoney',
            'm2netm2g',
            'playerm2g2',
            'skill',
            'constInfo',
            'grp',
            'uiToolTip',
            'uiPickETC',
            'chr',
            'mouseModule',
            'uiScriptLocale',
            'localeInfo',
            'uiCommon',
            '__builtin__',
            'uiGuildPopup',
            'background',
            'wndMgr',
            'uiGuildList',
            'guild',
            'ui',
            'guildbank',
            'uiUploadMark',
            'uiGuildBank',
            'grpText'],
 'var': [{'name': 'BUILDING_DATA_LIST', 'type': 'list', 'value': []},
         {'name': 'DISABLE_DECLARE_WAR', 'type': 'bool', 'value': False},
         {'name': 'DISABLE_GUILD_SKILL', 'type': 'bool', 'value': False},
         {'name': 'MATERIAL_LOG_ID', 'type': 'int', 'value': 90011},
         {'name': 'MATERIAL_LOG_INDEX', 'type': 'int', 'value': 1},
         {'name': 'MATERIAL_PLYWOOD_ID', 'type': 'int', 'value': 90012},
         {'name': 'MATERIAL_PLYWOOD_INDEX', 'type': 'int', 'value': 2},
         {'name': 'MATERIAL_STONE_ID', 'type': 'int', 'value': 90010},
         {'name': 'MATERIAL_STONE_INDEX', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiGuild'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
