{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetNormalButton'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTitleBarText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAcceptEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildPopupDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscaptKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetAcceptText'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancleEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetCancleText'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetNormalButton'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTitleBarText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildVoteDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscaptKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetButtonText'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText3'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText4'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText5'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTitleBarText'},
                     {'args': ['self', 'width'], 'defaults': [], 'name': 'SetWidth'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildVoteResultDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscaptKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetAcceptText'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancleEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetCancleText'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetNormalButton'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText3'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTitleBarText'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildVoteDialog2'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscaptKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog__'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildLandDealDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscaptKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'text1'], 'defaults': [], 'name': 'SetText1'},
                     {'args': ['self', 'text2'], 'defaults': [], 'name': 'SetText2'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog__'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildLandDealVoteDialog'}]}],
 'func': [],
 'import': ['uiCommon', 'ime', '__builtin__', 'app', 'm2netm2g', 'ui', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiGuildPopup'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
