{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGradeName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGradeNumber'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'gradeNumber'], 'defaults': [], 'name': 'SetGradeNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChangeGradeNameDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'}, {'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': 'Up'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'MouseReflector'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'EditableTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'TEXT_LIMIT', 'type': 'int', 'value': 35}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'CommentSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self', 'allyGuildID', 'enemyGuildID'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'gainGuildID', 'opponetGuildID', 'point'], 'defaults': [], 'name': 'SetScore'},
                     {'args': ['self', 'guildID1', 'memberCount1', 'guildID2', 'memberCount2'], 'defaults': [], 'name': 'UpdateMemberCount'},
                     {'args': ['self', 'ID'], 'defaults': [], 'name': '__GetDataDict'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshName'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWarScoreBoard'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'page'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Build'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeWindowUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destory'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositioningMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'x', 'y', 'z'], 'defaults': [], 'name': 'SetBuildingPosition'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'SettleCurrentPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__AskExchangeTenth'},
                     {'args': ['self'], 'defaults': [], 'name': '__ChangeWindowOpen'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__CreateBuildInInstance'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__CreateInstance'},
                     {'args': ['self', 'race', 'x', 'y', 'rot'], 'defaults': [0.0], 'name': '__CreateWallBlock'},
                     {'args': ['self'], 'defaults': [], 'name': '__DeleteInstance'},
                     {'args': ['self'], 'defaults': [], 'name': '__DisablePCBlocker'},
                     {'args': ['self'], 'defaults': [], 'name': '__EnablePCBlocker'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetBuildInPosition'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__GetObjectSize'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialLog'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialPlywood'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialStone'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMoney'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsTenthEventObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LockCameraMoving'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeRotation'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnEnterPreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnLeavePreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBuildingList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectBuilding'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectCategory'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectPositioningMode'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__PopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__RestoreViewMode'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__SetBuildingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__TenthEventDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__UnlockCameraMoving'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUILDINGLIST_BASE_WIDTH', 'type': 'int', 'value': 135},
                    {'name': 'BUILDING_ALPHA', 'type': 'float', 'value': 0.55},
                    {'name': 'DISABLE_COLOR', 'type': 'int', 'value': -1738635},
                    {'name': 'ENABLE_COLOR', 'type': 'int', 'value': -4079167},
                    {'name': 'MODE_POSITIONING', 'type': 'int', 'value': 1},
                    {'name': 'MODE_PREVIEW', 'type': 'int', 'value': 2},
                    {'name': 'MODE_VIEW', 'type': 'int', 'value': 0},
                    {'name': 'START_INSTANCE_INDEX', 'type': 'int', 'value': 123450},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BuildGuildBuildingWindow'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetScriptFileName'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent', 'filename'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWindow.PageWindow'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGuildListDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePopUpDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteGuild'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'localPos'], 'defaults': [], 'name': 'GetMemberData'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildListDialogIsShow'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'GuildProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildWarEnd'},
                     {'args': ['self', 'guildSelf', 'Oppguild'], 'defaults': [], 'name': 'GuildWarOppGuildNameSetting'},
                     {'args': ['self', 'gainGuildID', 'guildOpp', 'point', 'winpoint'], 'defaults': [], 'name': 'GuildWarScoreSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeGradeName'},
                     {'args': ['self', 'lineIndex', 'gradeNumber'], 'defaults': [], 'name': 'OnChangeMemberGrade'},
                     {'args': ['self', 'argIndex', 'argAuthority'], 'defaults': [], 'name': 'OnCheckAuthority'},
                     {'args': ['self', 'Text1', 'Text2', 'TitleBar', 'Event'], 'defaults': [], 'name': 'OnCreateGuildPopUp'},
                     {'args': ['self', 'Text'], 'defaults': [], 'name': 'OnCreatePopUp'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'OnDeleteComment'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnDeposit'},
                     {'args': ['self', 'lineIndex'], 'defaults': [], 'name': 'OnEnableGeneral'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnEndGuildWar'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGuildBaseDealButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGuildBaseDealVoteButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDownInBoardPage'},
                     {'args': ['self', 'exp'], 'defaults': [], 'name': 'OnOffer'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnOpenChangeGradeName'},
                     {'args': ['self', 'skillSlotIndex', 'type'], 'defaults': [], 'name': 'OnPickUpGuildSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPostComment'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRefreshComments'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScrollMemberLine'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnStartGuildWar'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OnUpGuildSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OnUseGuildSkill'},
                     {'args': ['self', 'slotNumber', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnWithdraw'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': 'OpenGuildGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildListDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildScoreWindow'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPageBankGold'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBoardPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageGradeComboBox'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageMemberList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberSelectBox'},
                     {'args': ['self', 'issearch'], 'defaults': [], 'name': 'RefreshGuildRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildWarInfoPage'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self', 'tooltipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseAllGuildMemberPageGradeComboBox'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__GetGuildBoardCommentData'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__GuildAttendanceResult'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBoardPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAcceptEventChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlock'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickAttendanceButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDeclareWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDepositButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDonateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickGuildListButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOfferButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSelectGuildMarkButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSelectGuildSymbolButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWithdrawButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBankGolInfoButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseAbandon'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseAbandonButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseDeal'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': '__OnGuildGoldInDialog'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': '__OnGuildGoldInOutButton'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': '__OnGuildGoldOutDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildWarScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnHealGSP'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOpenHealGSPBoard'},
                     {'args': ['self', 'healGSP'], 'defaults': [], 'name': '__OnOpenHealGSPQuestionDialog'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnOutMember'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOutMemberStart'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnReQuestionEventChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollsmelterList'},
                     {'args': ['self', 'markFileName'], 'defaults': [], 'name': '__OnSelectMark'},
                     {'args': ['self', 'symbolFileName'], 'defaults': [], 'name': '__OnSelectSymbol'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnVoteCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverInOfferImg'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'GRADE_ADD_MEMBER_AUTHORITY', 'type': 'int', 'value': 1},
                    {'name': 'GRADE_NOTICE_AUTHORITY', 'type': 'int', 'value': 3},
                    {'name': 'GRADE_REMOVE_MEMBER_AUTHORITY', 'type': 'int', 'value': 2},
                    {'name': 'GRADE_SKILL_AUTHORITY', 'type': 'int', 'value': 4},
                    {'name': 'GRADE_SLOT_NAME', 'type': 'int', 'value': 0},
                    {'name': 'GUILD_SKILL_ACTIVE_SLOT', 'type': 'int', 'value': 1},
                    {'name': 'GUILD_SKILL_AFFECT_SLOT', 'type': 'int', 'value': 2},
                    {'name': 'GUILD_SKILL_PASSIVE_SLOT', 'type': 'int', 'value': 0},
                    {'name': 'MEMBER_LINE_COUNT', 'type': 'int', 'value': 11},
                    {'name': 'MEMBER_SLOT_INDEX_ATTENDANCE', 'type': 'int', 'value': 5},
                    {'name': 'MEMBER_SLOT_INDEX_GENERAL_ENABLE', 'type': 'int', 'value': 6},
                    {'name': 'MEMBER_SLOT_INDEX_GRADE', 'type': 'int', 'value': 1},
                    {'name': 'MEMBER_SLOT_INDEX_JOB', 'type': 'int', 'value': 2},
                    {'name': 'MEMBER_SLOT_INDEX_LEVEL', 'type': 'int', 'value': 3},
                    {'name': 'MEMBER_SLOT_INDEX_NAME', 'type': 'int', 'value': 0},
                    {'name': 'MEMBER_SLOT_INDEX_OFFERSLOT', 'type': 'int', 'value': 4},
                    {'name': 'PLUS_LEFT_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'PLUS_RIGHT_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'PLUS_WIDTH', 'type': 'int', 'value': 80},
                    {'name': '_GuildWindow__GUILD_ATTENDANCE_ALREADY', 'type': 'int', 'value': 3},
                    {'name': '_GuildWindow__GUILD_ATTENDANCE_FAIL_ERROR', 'type': 'int', 'value': 1},
                    {'name': '_GuildWindow__GUILD_ATTENDANCE_FAIL_JOIN_TIME', 'type': 'int', 'value': 2},
                    {'name': '_GuildWindow__GUILD_ATTENDANCE_SUCCESS', 'type': 'int', 'value': 0},
                    {'name': '_GuildWindow__GUILD_EXP_DONATE_LEVEL', 'type': 'int', 'value': 20},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GuildWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetOpend'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildWarEnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'OppGuildId'], 'defaults': [], 'name': 'SetOppGuildName'},
                     {'args': ['self', 'gainGuildId', 'point', 'winpoint'], 'defaults': [], 'name': 'SetWarPoint'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWarScoreDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnTypeButtonClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'DeclearGuildWarSelectDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/public/Parameter_Slot_07.sub'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGuildName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGuildWarTypes'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetType'},
                     {'args': ['self', 'guildName', 'warType', 'winType', 'ScoreType', 'TimeType'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetCancelEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarScoreName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarTimeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarTypeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarWinName'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'AcceptGuildWarDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'type', 'result'], 'defaults': [], 'name': 'GuildDonate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickDonateAcceptButton'},
                     {'args': ['self', 'selected_donate_type'], 'defaults': [], 'name': '__ClickDonateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickDonateCancelButton'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__GuildDonateResult'},
                     {'args': ['self', 'tooltip_object'], 'defaults': [], 'name': '__HideToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__OverInDonateItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutDonateItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshData'},
                     {'args': ['self'], 'defaults': [], 'name': '__SettingData'},
                     {'args': ['self', 'tooltip_object'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'available_level'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_GuildDonateDialog__DONATE_DATA_DICT', 'type': 'dict', 'value': {'high': {'exp': 30000, 'mh_count': 30, 'r_count': 15}, 'middle': {'exp': 10000, 'mh_count': 10, 'r_count': 5}, 'normal': {'exp': 1000, 'mh_count': 3, 'r_count': 3}}},
                    {'name': '_GuildDonateDialog__DONATE_ITEM_DATA_TUPLE', 'type': 'tuple', 'value': (90010, 90011, 90012)},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_COUNT_MAX', 'type': 'int', 'value': 3},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_ERROR', 'type': 'int', 'value': 1},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_NOT_ENOUGH_HIGH_ITEM', 'type': 'int', 'value': 5},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_NOT_ENOUGH_INVENTORY', 'type': 'int', 'value': 2},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_NOT_ENOUGH_LEVEL', 'type': 'int', 'value': 6},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_NOT_ENOUGH_MIDDLE_ITEM', 'type': 'int', 'value': 4},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_NOT_ENOUGH_YANG', 'type': 'int', 'value': 3},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_FAIL_TIME', 'type': 'int', 'value': 7},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_GET_ITEM_VNUM1', 'type': 'int', 'value': 90010},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_GET_ITEM_VNUM2', 'type': 'int', 'value': 90011},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_GET_ITEM_VNUM3', 'type': 'int', 'value': 90012},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_HIGH_EXP_AMOUNT', 'type': 'int', 'value': 30000},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_HIGH_GET_ITEM_RANDOM_COUNT', 'type': 'int', 'value': 15},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_HIGH_GET_MEDAL_OF_HONOR', 'type': 'int', 'value': 30},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_MIDDLE_EXP_AMOUNT', 'type': 'int', 'value': 10000},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_MIDDLE_GET_ITEM_RANDOM_COUNT', 'type': 'int', 'value': 5},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_MIDDLE_GET_MEDAL_OF_HONOR', 'type': 'int', 'value': 10},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_NORMAL_EXP_AMOUNT', 'type': 'int', 'value': 1000},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_NORMAL_GET_ITEM_RANDOM_COUNT', 'type': 'int', 'value': 3},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_NORMAL_GET_MEDAL_OF_HONOR', 'type': 'int', 'value': 3},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_SUCCESS', 'type': 'int', 'value': 0},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_TYPE_HIGH', 'type': 'int', 'value': 2},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_TYPE_MIDDLE', 'type': 'int', 'value': 1},
                    {'name': '_GuildDonateDialog__GUILD_DONATE_TYPE_NORMAL', 'type': 'int', 'value': 0},
                    {'name': '_GuildDonateDialog__available_level', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__available_level' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__cur_medal_of_honor_text', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__cur_medal_of_honor_text' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__donate_object_dict', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__donate_object_dict' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__donate_question_dlg', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__donate_question_dlg' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__donate_question_loca_dict', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__donate_question_loca_dict' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__guild_exp_tooltip', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__guild_exp_tooltip' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__high_donate_button', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__high_donate_button' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__is_loaded', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__is_loaded' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__is_requesting_donate', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__is_requesting_donate' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__item_tooltip', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__item_tooltip' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__medal_of_honor_tooltip', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__medal_of_honor_tooltip' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__middle_donate_button', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__middle_donate_button' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__my_medal_of_honor_tooltip', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__my_medal_of_honor_tooltip' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__normal_donate_button', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__normal_donate_button' of 'GuildDonateDialog' objects>},
                    {'name': '_GuildDonateDialog__remain_donate_text', 'type': 'member_descriptor', 'value': <member '_GuildDonateDialog__remain_donate_text' of 'GuildDonateDialog' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GuildDonateDialog'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__is_loaded',
                               '__available_level',
                               '__normal_donate_button',
                               '__middle_donate_button',
                               '__high_donate_button',
                               '__remain_donate_text',
                               '__donate_object_dict',
                               '__donate_question_loca_dict',
                               '__donate_question_dlg',
                               '__cur_medal_of_honor_text',
                               '__item_tooltip',
                               '__medal_of_honor_tooltip',
                               '__guild_exp_tooltip',
                               '__my_medal_of_honor_tooltip',
                               '__is_requesting_donate')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetType'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self'], 'defaults': [], 'name': '__AllWarButtonSetUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'buttonlist'], 'defaults': [], 'name': '__NotUseWarButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCancel'},
                     {'args': ['self', 'wartype', 'buttonlist'], 'defaults': [], 'name': '__OnClickTypeWarWin'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWarTypeSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOK'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'DeclareGuildWarDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self'], 'defaults': [], 'name': 'AllClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseQuestionDialog'},
                     {'args': ['self', 'race', 'objectx', 'objecty', 'rot_z'], 'defaults': [], 'name': 'CreateEmptyObject'},
                     {'args': ['self'], 'defaults': [], 'name': 'Delete'},
                     {'args': ['self'], 'defaults': [], 'name': 'DestoryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositionChangeMode'},
                     {'args': ['self', 'str', 'acceptevent'], 'defaults': [], 'name': 'MakeQuestionDialog'},
                     {'args': ['self', 'str1', 'str2', 'acceptevent'], 'defaults': [], 'name': 'MakeQuestionDialog2'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RealClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectList'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectObject'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetBuildGuildBuildingWindow'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetCameraSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChangeBuildingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Update'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeRotation'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBuildingList'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__SetBuildingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'LIST_BOX_BASE_WIDHT', 'type': 'int', 'value': 165},
                    {'name': 'SHOW_LIST_MAX', 'type': 'int', 'value': 10},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BuildGuildBuildingChangeWindow'}]}],
 'func': [{'args': ['srcGuildID', 'dstGuildID'], 'defaults': [], 'name': 'GetGVGKey'}, {'args': ['n'], 'defaults': [], 'name': 'NumberToMoneyString'}, {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}, {'args': ['n'], 'defaults': [], 'name': 'unsigned32'}],
 'import': ['miniMap',
            'chatm2g',
            'app',
            'playerSettingModule',
            'uiPickMoney',
            'm2netm2g',
            'playerm2g2',
            'skill',
            'constInfo',
            'grp',
            'uiToolTip',
            'uiPickETC',
            'chr',
            'mouseModule',
            'uiScriptLocale',
            'localeInfo',
            'uiCommon',
            '__builtin__',
            'uiGuildPopup',
            'background',
            'wndMgr',
            'uiGuildList',
            'guild',
            'ui',
            'guildbank',
            'uiUploadMark',
            'uiGuildBank',
            'grpText'],
 'var': [{'name': 'BUILDING_DATA_LIST',
          'type': 'list',
          'value': [{'LOCAL_NAME': 'Oficina [Armas]', 'MATERIAL': ['20', '30', '20'], 'NAME': 'jedan', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14013, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Oficina [Armaduras]', 'MATERIAL': ['20', '30', '20'], 'NAME': 'jedan', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14014, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Oficina [Acess\xf3rios]', 'MATERIAL': ['20', '30', '20'], 'NAME': 'jedan', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14015, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'local p/ treinamento', 'MATERIAL': ['25', '25', '25'], 'NAME': 'suryeonjang', 'PRICE': '20000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14033, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Diamante]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14043, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [F\xf3ssil]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14045, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Cobre]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14046, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Prata]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14047, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Ouro]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14048, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Jade]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14049, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [\xc9bano]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14050, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [P\xe9rola]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14051, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Ouro Branco]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14052, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Cristal]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14053, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [Ametista]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14054, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha [\xc1gata]', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14055, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Altar do Poder', 'MATERIAL': ['25', '25', '25'], 'NAME': 'himuijedan_01', 'PRICE': '25000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14061, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Altar do Poder', 'MATERIAL': ['50', '50', '50'], 'NAME': 'himuijedan_02', 'PRICE': '500000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14062, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Altar do Poder', 'MATERIAL': ['75', '75', '75'], 'NAME': 'himuijedan_03', 'PRICE': '750000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14063, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Banco', 'MATERIAL': ['25', '25', '25'], 'NAME': 'guildbank_01', 'PRICE': '25000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14071, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Banco', 'MATERIAL': ['50', '50', '50'], 'NAME': 'guildbank_02', 'PRICE': '500000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14072, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Banco', 'MATERIAL': ['75', '75', '75'], 'NAME': 'guildbank_03', 'PRICE': '750000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14073, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha (Cristal Negro)', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14074, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha (Rubi)', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14075, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha (Granada)', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14076, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha (Esmeralda)', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14077, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha (Safira)', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14078, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fornalha (Turmalina)', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14079, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Centro', 'MATERIAL': ['20', '30', '25'], 'NAME': 'a1-011-workhouse', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'HEADQUARTER', 'VNUM': 14100, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'a1-038-wall-corner', 'PRICE': '2000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14101, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'a1-038-wall-lin', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14102, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'a1-038-wall-lin2', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14103, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Port\xe3o ', 'MATERIAL': ['5', '15', '10'], 'NAME': 'a1-038-wall-door', 'PRICE': '2500000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14104, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['5', '15', '10'], 'NAME': 'a1-set', 'PRICE': '2500000', 'SHOW': True, 'TYPE': 'BUILDIN', 'VNUM': 14105, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Centro', 'MATERIAL': ['20', '30', '25'], 'NAME': 'b1-011-workhouse', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'HEADQUARTER', 'VNUM': 14110, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'b1-038-wall-corner', 'PRICE': '2000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14111, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'b1-038-wall-lin', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14112, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'b1-038-wall-lin2', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14113, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Port\xe3o ', 'MATERIAL': ['5', '15', '10'], 'NAME': 'b1-038-wall-door', 'PRICE': '2500000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14114, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['5', '15', '10'], 'NAME': 'b1-set', 'PRICE': '2500000', 'SHOW': True, 'TYPE': 'BUILDIN', 'VNUM': 14115, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Centro', 'MATERIAL': ['20', '30', '25'], 'NAME': 'c1-011-workhouse', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'HEADQUARTER', 'VNUM': 14120, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'c1-038-wall-corner', 'PRICE': '2000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14121, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'c1-038-wall-lin', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14122, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['15', '5', '5'], 'NAME': 'c1-038-wall-lin2', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14123, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Port\xe3o ', 'MATERIAL': ['5', '15', '10'], 'NAME': 'c1-038-wall-door', 'PRICE': '2500000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14124, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Muro', 'MATERIAL': ['5', '15', '10'], 'NAME': 'c1-set', 'PRICE': '2500000', 'SHOW': True, 'TYPE': 'BUILDIN', 'VNUM': 14125, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Emblema da Guilda', 'MATERIAL': ['0', '5', '5'], 'NAME': 'guild_symbol', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14200, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xb4\xe3\xc0\xe5\xb4\xeb\xb9\xae', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_door01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14201, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xb4\xe3\xc0\xe5\xb5\xde\xba\xae', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_back01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14202, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xb4\xe3\xc0\xe5\xbf\xde\xba\xae', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_left01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14203, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xb4\xe3\xc0\xe5\xbf\xc0\xb8\xa5\xba\xae', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_right01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14204, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['5', '0', '0'], 'NAME': 'general_obj_stone01', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14300, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['5', '0', '0'], 'NAME': 'general_obj_stone02', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14301, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['7', '0', '0'], 'NAME': 'general_obj_stone03', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14302, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['7', '0', '0'], 'NAME': 'general_obj_stone04', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14303, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['7', '0', '0'], 'NAME': 'general_obj_stone05', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14304, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['8', '0', '0'], 'NAME': 'general_obj_stone06', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14305, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['8', '0', '0'], 'NAME': 'general_obj_stone07', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14306, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['8', '0', '0'], 'NAME': 'general_obj_stone08', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14307, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['9', '0', '0'], 'NAME': 'general_obj_stone09', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14308, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Pedra', 'MATERIAL': ['9', '0', '0'], 'NAME': 'general_obj_stone10', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14309, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '5', '0'], 'NAME': 'B1_PagodaTree_RT', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14400, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '5', '0'], 'NAME': 'B1_PagodaTree_RT3', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14401, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '7', '0'], 'NAME': 'B1_Sassafras_RT_Fall', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14402, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '7', '0'], 'NAME': 'B1_Sassafras_RT_Fall2', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14403, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '7', '0'], 'NAME': 'B3_ShingleOak_RT2', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14404, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_IvySpy_RT', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14405, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_IvySpy_RT4', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14406, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_JapaneseMaple_RT_Fall', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14407, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc1rvore', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_JapaneseMaple_RT_Fall2', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14408, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Bandeira1', 'MATERIAL': ['0', '0', '0'], 'NAME': 'flag_a', 'PRICE': '1000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 20139, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Bandeira2', 'MATERIAL': ['0', '0', '0'], 'NAME': 'flag_b', 'PRICE': '1000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 20140, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Bandeira3', 'MATERIAL': ['0', '0', '0'], 'NAME': 'flag_c', 'PRICE': '1000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 20141, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360}]},
         {'name': 'DISABLE_DECLARE_WAR', 'type': 'bool', 'value': False},
         {'name': 'DISABLE_GUILD_SKILL', 'type': 'bool', 'value': False},
         {'name': 'MATERIAL_LOG_ID', 'type': 'int', 'value': 90011},
         {'name': 'MATERIAL_LOG_INDEX', 'type': 'int', 'value': 1},
         {'name': 'MATERIAL_PLYWOOD_ID', 'type': 'int', 'value': 90012},
         {'name': 'MATERIAL_PLYWOOD_INDEX', 'type': 'int', 'value': 2},
         {'name': 'MATERIAL_STONE_ID', 'type': 'int', 'value': 90010},
         {'name': 'MATERIAL_STONE_INDEX', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiGuild'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
