{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGradeName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGradeNumber'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'gradeNumber'], 'defaults': [], 'name': 'SetGradeNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChangeGradeNameDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'}, {'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': 'Up'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'MouseReflector'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'EditableTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}, {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'}, {'args': ['self', 'width', 'height'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'TEXT_LIMIT', 'type': 'int', 'value': 35}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'CommentSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self', 'allyGuildID', 'enemyGuildID'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'gainGuildID', 'opponetGuildID', 'point'], 'defaults': [], 'name': 'SetScore'},
                     {'args': ['self', 'guildID1', 'memberCount1', 'guildID2', 'memberCount2'], 'defaults': [], 'name': 'UpdateMemberCount'},
                     {'args': ['self', 'ID'], 'defaults': [], 'name': '__GetDataDict'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshName'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWarScoreBoard'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'page'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'SelectTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Build'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ChangeWindowUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destory'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositioningMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'x', 'y', 'z'], 'defaults': [], 'name': 'SetBuildingPosition'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'SettleCurrentPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__AskExchangeTenth'},
                     {'args': ['self'], 'defaults': [], 'name': '__ChangeWindowOpen'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__CreateBuildInInstance'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__CreateInstance'},
                     {'args': ['self', 'race', 'x', 'y', 'rot'], 'defaults': [0.0], 'name': '__CreateWallBlock'},
                     {'args': ['self'], 'defaults': [], 'name': '__DeleteInstance'},
                     {'args': ['self'], 'defaults': [], 'name': '__DisablePCBlocker'},
                     {'args': ['self'], 'defaults': [], 'name': '__EnablePCBlocker'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetBuildInPosition'},
                     {'args': ['self', 'race'], 'defaults': [], 'name': '__GetObjectSize'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialLog'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialPlywood'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMaterialStone'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsEnoughMoney'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsTenthEventObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LockCameraMoving'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeRotation'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnEnterPreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnLeavePreviewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBuildingList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectBuilding'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectCategory'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnSelectPositioningMode'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__PopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__RestoreViewMode'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__SetBuildingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__TenthEventDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__UnlockCameraMoving'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUILDINGLIST_BASE_WIDTH', 'type': 'int', 'value': 135},
                    {'name': 'BUILDING_ALPHA', 'type': 'float', 'value': 0.55},
                    {'name': 'DISABLE_COLOR', 'type': 'int', 'value': -1738635},
                    {'name': 'ENABLE_COLOR', 'type': 'int', 'value': -4079167},
                    {'name': 'GUILD_CATEGORY_LIST', 'type': 'tuple', 'value': (('HEADQUARTER', 'F\xf5\xe9p\xfclet'), ('FACILITY', 'Mell\xe9k\xe9p\xfclet'), ('OBJECT', 'T\xe1rgy'))},
                    {'name': 'MODE_POSITIONING', 'type': 'int', 'value': 1},
                    {'name': 'MODE_PREVIEW', 'type': 'int', 'value': 2},
                    {'name': 'MODE_VIEW', 'type': 'int', 'value': 0},
                    {'name': 'START_INSTANCE_INDEX', 'type': 'int', 'value': 123450},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BuildGuildBuildingWindow'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetScriptFileName'}, {'args': ['self', 'parent', 'filename'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWindow.PageWindow'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseGuildListDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClosePopUpDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteGuild'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'localPos'], 'defaults': [], 'name': 'GetMemberData'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildListDialogIsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildWarEnd'},
                     {'args': ['self', 'guildSelf', 'Oppguild'], 'defaults': [], 'name': 'GuildWarOppGuildNameSetting'},
                     {'args': ['self', 'gainGuildID', 'guildOpp', 'point', 'winpoint'], 'defaults': [], 'name': 'GuildWarScoreSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeGradeName'},
                     {'args': ['self', 'lineIndex', 'gradeNumber'], 'defaults': [], 'name': 'OnChangeMemberGrade'},
                     {'args': ['self', 'argIndex', 'argAuthority'], 'defaults': [], 'name': 'OnCheckAuthority'},
                     {'args': ['self', 'Text1', 'Text2', 'TitleBar', 'Event'], 'defaults': [], 'name': 'OnCreateGuildPopUp'},
                     {'args': ['self', 'Text'], 'defaults': [], 'name': 'OnCreatePopUp'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'OnDeleteComment'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnDeposit'},
                     {'args': ['self', 'lineIndex'], 'defaults': [], 'name': 'OnEnableGeneral'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnEndGuildWar'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGuildBaseDealButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGuildBaseDealVoteButton'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDownInBoardPage'},
                     {'args': ['self', 'exp'], 'defaults': [], 'name': 'OnOffer'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnOpenChangeGradeName'},
                     {'args': ['self', 'skillSlotIndex', 'type'], 'defaults': [], 'name': 'OnPickUpGuildSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPostComment'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRefreshComments'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScrollMemberLine'},
                     {'args': ['self', 'guildSelf', 'guildOpp'], 'defaults': [], 'name': 'OnStartGuildWar'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OnUpGuildSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OnUseGuildSkill'},
                     {'args': ['self', 'slotNumber', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnWithdraw'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': 'OpenGuildGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildListDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenGuildScoreWindow'},
                     {'args': ['self', 'slotNumber', 'type'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBaseInfoPageBankGold'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBoardPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageGradeComboBox'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberPageMemberList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildMemberSelectBox'},
                     {'args': ['self', 'issearch'], 'defaults': [], 'name': 'RefreshGuildRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildWarInfoPage'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self', 'tooltipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseAllGuildMemberPageGradeComboBox'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__GetGuildBoardCommentData'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBaseInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeBoardPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeGradePage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeMemberPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeSkillPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAcceptEventChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlock'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDeclareWarButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDepositButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickGuildListButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOfferButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSelectGuildMarkButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSelectGuildSymbolButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWithdrawButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseGoldInOutWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBankGolInfoButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseAbandon'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseAbandonButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildBaseDeal'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': '__OnGuildGoldInDialog'},
                     {'args': ['self', 'inout'], 'defaults': [], 'name': '__OnGuildGoldInOutButton'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': '__OnGuildGoldOutDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildWarScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnHealGSP'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOpenHealGSPBoard'},
                     {'args': ['self', 'healGSP'], 'defaults': [], 'name': '__OnOpenHealGSPQuestionDialog'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnOutMember'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOutMemberStart'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnReQuestionEventChangeMaster'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollsmelterList'},
                     {'args': ['self', 'markFileName'], 'defaults': [], 'name': '__OnSelectMark'},
                     {'args': ['self', 'symbolFileName'], 'defaults': [], 'name': '__OnSelectSymbol'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__OnVoteCheck'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'EMPIRE_NAME', 'type': 'dict', 'value': {1: 'Shinsoo birodalom', 2: 'Chunjo birodalom', 3: 'Jinno birodalom'}},
                    {'name': 'EMPIRE_NAME_TO_MAPINDEX',
                     'type': 'dict',
                     'value': {1: 'Shinsoo birodalom', 3: 'Shinsoo birodalom', 4: 'Shinsoo birodalom', 6: 'Shinsoo birodalom', 21: 'Chunjo birodalom', 23: 'Chunjo birodalom', 24: 'Chunjo birodalom', 26: 'Chunjo birodalom', 41: 'Jinno birodalom', 43: 'Jinno birodalom', 44: 'Jinno birodalom', 46: 'Jinno birodalom'}},
                    {'name': 'GRADE_ADD_MEMBER_AUTHORITY', 'type': 'int', 'value': 1},
                    {'name': 'GRADE_BANK_AUTHORITY', 'type': 'int', 'value': 6},
                    {'name': 'GRADE_NOTICE_AUTHORITY', 'type': 'int', 'value': 3},
                    {'name': 'GRADE_REMOVE_MEMBER_AUTHORITY', 'type': 'int', 'value': 2},
                    {'name': 'GRADE_SKILL_AUTHORITY', 'type': 'int', 'value': 4},
                    {'name': 'GRADE_SLOT_NAME', 'type': 'int', 'value': 0},
                    {'name': 'GRADE_WAR_AUTHORITY', 'type': 'int', 'value': 5},
                    {'name': 'GUILD_SKILL_ACTIVE_SLOT', 'type': 'int', 'value': 1},
                    {'name': 'GUILD_SKILL_AFFECT_SLOT', 'type': 'int', 'value': 2},
                    {'name': 'GUILD_SKILL_PASSIVE_SLOT', 'type': 'int', 'value': 0},
                    {'name': 'JOB_NAME', 'type': 'dict', 'value': {0: 'Harcos', 1: 'Nindzsa', 2: 'Sura', 3: 'S\xe1m\xe1n', 4: 'V\xe9rfarkas'}},
                    {'name': 'MAP_NAME', 'type': 'dict', 'value': {0: '', 1: 'Yongan-ter\xfclet', 3: 'Yayang Ter\xfclet', 4: 'Jungrang', 6: 'Miryang', 21: 'Joan-ter\xfclet', 23: 'Bokjung-ter\xfclet', 24: 'Waryong', 26: 'Songpa', 41: 'Pyungmoo-ter\xfclet', 43: 'Bakra-ter\xfclet', 44: 'Imha', 46: 'Daeyami'}},
                    {'name': 'MEMBER_LINE_COUNT', 'type': 'int', 'value': 11},
                    {'name': 'PLUS_LEFT_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'PLUS_RIGHT_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'PLUS_WIDTH', 'type': 'int', 'value': 80},
                    {'name': 'WAR_NAME', 'type': 'dict', 'value': {0: 'Mezei harc', 1: 'Ar\xe9na harc', 2: 'Kapd el a z\xe1szl\xf3t', 3: 'Megsemmis\xedt\xe9s', 4: 'Pajzs-harc', 5: 'T\xe1mad\xe1s id\xf5re'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GuildWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetOpend'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildWarEnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'OppGuildId'], 'defaults': [], 'name': 'SetOppGuildName'},
                     {'args': ['self', 'gainGuildId', 'point', 'winpoint'], 'defaults': [], 'name': 'SetWarPoint'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildWarScoreDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnTypeButtonClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'DeclearGuildWarSelectDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/public/Parameter_Slot_07.sub'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGuildName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGuildWarTypes'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetType'},
                     {'args': ['self', 'guildName', 'warType', 'winType', 'ScoreType', 'TimeType'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetCancelEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarScoreName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarTimeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarTypeName'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetGuildWarWinName'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'AcceptGuildWarDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetType'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCancelEvent'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetGuildWarType'},
                     {'args': ['self'], 'defaults': [], 'name': '__AllWarButtonSetUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDialog'},
                     {'args': ['self', 'buttonlist'], 'defaults': [], 'name': '__NotUseWarButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCancel'},
                     {'args': ['self', 'wartype', 'buttonlist'], 'defaults': [], 'name': '__OnClickTypeWarWin'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWarTypeSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOK'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuild'}, {'name': '__qualname__', 'type': 'str', 'value': 'DeclareGuildWarDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self'], 'defaults': [], 'name': 'AllClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseQuestionDialog'},
                     {'args': ['self', 'race', 'objectx', 'objecty', 'rot_z'], 'defaults': [], 'name': 'CreateEmptyObject'},
                     {'args': ['self'], 'defaults': [], 'name': 'Delete'},
                     {'args': ['self'], 'defaults': [], 'name': 'DestoryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'EndPositionChangeMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPositionChangeMode'},
                     {'args': ['self', 'str', 'acceptevent'], 'defaults': [], 'name': 'MakeQuestionDialog'},
                     {'args': ['self', 'str1', 'str2', 'acceptevent'], 'defaults': [], 'name': 'MakeQuestionDialog2'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RealClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectList'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectObject'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetBuildGuildBuildingWindow'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetCameraSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetChangeBuildingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Update'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeRotation'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollBuildingList'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__SetBuildingData'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'LIST_BOX_BASE_WIDHT', 'type': 'int', 'value': 165},
                    {'name': 'SHOW_LIST_MAX', 'type': 'int', 'value': 10},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuild'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BuildGuildBuildingChangeWindow'}]}],
 'func': [{'args': ['srcGuildID', 'dstGuildID'], 'defaults': [], 'name': 'GetGVGKey'}, {'args': ['n'], 'defaults': [], 'name': 'NumberToMoneyString'}, {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}, {'args': ['n'], 'defaults': [], 'name': 'unsigned32'}],
 'import': ['miniMap',
            'app',
            'playerSettingModule',
            'uiPickMoney',
            'm2netm2g',
            'playerm2g2',
            'skill',
            'constInfo',
            'grp',
            'uiToolTip',
            'uiPickETC',
            'chr',
            'mouseModule',
            'uiScriptLocale',
            'localeInfo',
            'uiCommon',
            '__builtin__',
            'uiGuildPopup',
            'background',
            'wndMgr',
            'uiGuildList',
            'guild',
            'ui',
            'guildbank',
            'uiUploadMark',
            'uiGuildBank',
            'grpText'],
 'var': [{'name': 'BUILDING_DATA_LIST',
          'type': 'list',
          'value': [{'LOCAL_NAME': 'Fegyvergy\xe1r', 'MATERIAL': ['20', '30', '20'], 'NAME': 'jedan', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14013, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'V\xe9rt-kov\xe1cs', 'MATERIAL': ['20', '30', '20'], 'NAME': 'jedan', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14014, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc9kszer\xe9sz', 'MATERIAL': ['20', '30', '20'], 'NAME': 'jedan', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14015, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Kik\xe9pz\xf5 k\xf6zpont', 'MATERIAL': ['25', '25', '25'], 'NAME': 'suryeonjang', 'PRICE': '20000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14033, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Gy\xe9m\xe1nt-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14043, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Megk\xf6v. fa-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14045, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'R\xe9z-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14046, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Ez\xfcst-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14047, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Arany-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14048, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'J\xe1de-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14049, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': '\xc9benfa-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14050, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Gy\xf6ngy-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14051, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Feh\xe9rarany-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14052, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Krist\xe1ly-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14053, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Ametiszt-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14054, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Mennyei k\xf6nny-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14055, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Az Er\xf5 olt\xe1ra', 'MATERIAL': ['25', '25', '25'], 'NAME': 'himuijedan_01', 'PRICE': '25000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14061, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Az Er\xf5 olt\xe1ra', 'MATERIAL': ['50', '50', '50'], 'NAME': 'himuijedan_02', 'PRICE': '500000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14062, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Az Er\xf5 olt\xe1ra', 'MATERIAL': ['75', '75', '75'], 'NAME': 'himuijedan_03', 'PRICE': '750000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14063, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9hrakt\xe1r', 'MATERIAL': ['25', '25', '25'], 'NAME': 'guildbank_01', 'PRICE': '25000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14071, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9hrakt\xe1r', 'MATERIAL': ['50', '50', '50'], 'NAME': 'guildbank_02', 'PRICE': '500000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14072, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9hrakt\xe1r', 'MATERIAL': ['75', '75', '75'], 'NAME': 'guildbank_03', 'PRICE': '750000000', 'SHOW': False, 'TYPE': 'FACILITY', 'VNUM': 14073, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'L\xe9lekkrist\xe1ly-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14074, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Rubin-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14075, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Gr\xe1n\xe1t-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14076, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Smaragd-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14077, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Zaf\xedr-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14078, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Turmalin-koh\xf3', 'MATERIAL': ['15', '20', '25'], 'NAME': 'yonggwangro', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'FACILITY', 'VNUM': 14079, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'H\xe1z (1)', 'MATERIAL': ['20', '30', '25'], 'NAME': 'a1-011-workhouse', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'HEADQUARTER', 'VNUM': 14100, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (1-1)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'a1-038-wall-corner', 'PRICE': '2000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14101, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (1-2)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'a1-038-wall-lin', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14102, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (1-3)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'a1-038-wall-lin2', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14103, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Kapu (1)', 'MATERIAL': ['5', '15', '10'], 'NAME': 'a1-038-wall-door', 'PRICE': '2500000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14104, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fal (1)', 'MATERIAL': ['5', '15', '10'], 'NAME': 'a1-set', 'PRICE': '2500000', 'SHOW': True, 'TYPE': 'BUILDIN', 'VNUM': 14105, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'H\xe1z (2)', 'MATERIAL': ['20', '30', '25'], 'NAME': 'b1-011-workhouse', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'HEADQUARTER', 'VNUM': 14110, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (2-1)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'b1-038-wall-corner', 'PRICE': '2000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14111, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (2-2)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'b1-038-wall-lin', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14112, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (2-3)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'b1-038-wall-lin2', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14113, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Kapu (2)', 'MATERIAL': ['5', '15', '10'], 'NAME': 'b1-038-wall-door', 'PRICE': '2500000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14114, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fal (2)', 'MATERIAL': ['5', '15', '10'], 'NAME': 'b1-set', 'PRICE': '2500000', 'SHOW': True, 'TYPE': 'BUILDIN', 'VNUM': 14115, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'H\xe1z (3)', 'MATERIAL': ['20', '30', '25'], 'NAME': 'c1-011-workhouse', 'PRICE': '20000000', 'SHOW': True, 'TYPE': 'HEADQUARTER', 'VNUM': 14120, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (3-1)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'c1-038-wall-corner', 'PRICE': '2000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14121, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (3-2)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'c1-038-wall-lin', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14122, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5fal (3-3)', 'MATERIAL': ['15', '5', '5'], 'NAME': 'c1-038-wall-lin2', 'PRICE': '1000000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14123, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Kapu (3)', 'MATERIAL': ['5', '15', '10'], 'NAME': 'c1-038-wall-door', 'PRICE': '2500000', 'SHOW': False, 'TYPE': 'OBJECT', 'VNUM': 14124, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fal (3)', 'MATERIAL': ['5', '15', '10'], 'NAME': 'c1-set', 'PRICE': '2500000', 'SHOW': True, 'TYPE': 'BUILDIN', 'VNUM': 14125, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9h-jelv\xe9ny', 'MATERIAL': ['0', '5', '5'], 'NAME': 'guild_symbol', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14200, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Homlokzati fal', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_door01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14201, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'H\xe1ts\xf3 fal', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_back01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14202, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Bal oldali fal', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_left01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14203, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Jobb oldali fal', 'MATERIAL': ['0', '0', '0'], 'NAME': 'fence01_right01', 'PRICE': '3000000', 'SHOW': True, 'TYPE': 'WALL', 'VNUM': 14204, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (1)', 'MATERIAL': ['5', '0', '0'], 'NAME': 'general_obj_stone01', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14300, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (2)', 'MATERIAL': ['5', '0', '0'], 'NAME': 'general_obj_stone02', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14301, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (3)', 'MATERIAL': ['7', '0', '0'], 'NAME': 'general_obj_stone03', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14302, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (4)', 'MATERIAL': ['7', '0', '0'], 'NAME': 'general_obj_stone04', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14303, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (5)', 'MATERIAL': ['7', '0', '0'], 'NAME': 'general_obj_stone05', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14304, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (6)', 'MATERIAL': ['8', '0', '0'], 'NAME': 'general_obj_stone06', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14305, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (7)', 'MATERIAL': ['8', '0', '0'], 'NAME': 'general_obj_stone07', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14306, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (8)', 'MATERIAL': ['8', '0', '0'], 'NAME': 'general_obj_stone08', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14307, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (9)', 'MATERIAL': ['9', '0', '0'], 'NAME': 'general_obj_stone09', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14308, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'K\xf5 (10)', 'MATERIAL': ['9', '0', '0'], 'NAME': 'general_obj_stone10', 'PRICE': '300000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14309, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (1)', 'MATERIAL': ['0', '5', '0'], 'NAME': 'B1_PagodaTree_RT', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14400, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (2)', 'MATERIAL': ['0', '5', '0'], 'NAME': 'B1_PagodaTree_RT3', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14401, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (3)', 'MATERIAL': ['0', '7', '0'], 'NAME': 'B1_Sassafras_RT_Fall', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14402, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (4)', 'MATERIAL': ['0', '7', '0'], 'NAME': 'B1_Sassafras_RT_Fall2', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14403, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (5)', 'MATERIAL': ['0', '7', '0'], 'NAME': 'B3_ShingleOak_RT2', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14404, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (6)', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_IvySpy_RT', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14405, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (7)', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_IvySpy_RT4', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14406, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (8)', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_JapaneseMaple_RT_Fall', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14407, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'Fa (9)', 'MATERIAL': ['0', '9', '0'], 'NAME': 'B2_JapaneseMaple_RT_Fall2', 'PRICE': '2000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 14408, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9h Lobog\xf3 (lila)', 'MATERIAL': ['0', '0', '0'], 'NAME': 'flag_a', 'PRICE': '1000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 20139, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9h Lobog\xf3 (k\xe9k/z\xf6ld)', 'MATERIAL': ['0', '0', '0'], 'NAME': 'flag_b', 'PRICE': '1000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 20140, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360},
                    {'LOCAL_NAME': 'C\xe9h Lobog\xf3 (piros/arany)', 'MATERIAL': ['0', '0', '0'], 'NAME': 'flag_c', 'PRICE': '1000000', 'SHOW': True, 'TYPE': 'OBJECT', 'VNUM': 20141, 'X_ROT_LIMIT': 0, 'Y_ROT_LIMIT': 0, 'Z_ROT_LIMIT': 360}]},
         {'name': 'DISABLE_DECLARE_WAR', 'type': 'bool', 'value': False},
         {'name': 'DISABLE_GUILD_SKILL', 'type': 'bool', 'value': False},
         {'name': 'MATERIAL_LOG_ID', 'type': 'int', 'value': 90011},
         {'name': 'MATERIAL_LOG_INDEX', 'type': 'int', 'value': 1},
         {'name': 'MATERIAL_PLYWOOD_ID', 'type': 'int', 'value': 90012},
         {'name': 'MATERIAL_PLYWOOD_INDEX', 'type': 'int', 'value': 2},
         {'name': 'MATERIAL_STONE_ID', 'type': 'int', 'value': 90010},
         {'name': 'MATERIAL_STONE_INDEX', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiGuild'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
