{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AllResultSlotButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'ApplicantGuild'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'ApplicantGuildDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearBase'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideItemButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HidePageButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': 'Pagebutton'},
                     {'args': ['self', 'issearch'], 'defaults': [], 'name': 'RefreshGuildRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'SearchGuildForName'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'SendRequestList'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetApplicantResultNameText'},
                     {'args': ['self', 'maxsize', 'page'], 'defaults': [], 'name': 'SetPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetRankingResultNameText'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowPromoteGuild'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeResultUI'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': '__SelectItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearPagebuttoncolor'},
                     {'args': ['self'], 'defaults': [], 'name': 'firstprevbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'lastnextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'nextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'prevbutton'}],
            'import': [],
            'var': [{'name': 'APPLICANT', 'type': 'int', 'value': 4},
                    {'name': 'CLICK_LIMIT_TIME', 'type': 'int', 'value': 3},
                    {'name': 'EMPIRE_ALL', 'type': 'int', 'value': 0},
                    {'name': 'M2JOBLIST', 'type': 'dict', 'value': {0: 'Warrior', 1: 'Ninja', 2: 'Sura', 3: 'Shaman', 4: 'Lycan'}},
                    {'name': 'MAX_LINE_COUNT', 'type': 'int', 'value': 8},
                    {'name': 'PAGEBUTTON_MAX_SIZE', 'type': 'int', 'value': 9},
                    {'name': 'PAGEBUTTON_NUMBER_SIZE', 'type': 'int', 'value': 5},
                    {'name': 'PAGEONE_MAX_SIZE', 'type': 'int', 'value': 50},
                    {'name': 'SPECIAL_TITLE_COLOR', 'type': 'long', 'value': 4283317552L},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuildList'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GuildListDialog'}]}],
 'func': [],
 'import': ['uiCommon', 'snd', 'guild', 'uiToolTip', '__builtin__', 'chatm2g', 'app', 'wndMgr', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiGuildList'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
