{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseGuildBank'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destory'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnPickMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenBankInfo'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBank'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBankInfo'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'SetTableSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'ShowWindow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'local'], 'defaults': [], 'name': '__LocalPosToGlobalPos'},
                     {'args': ['self', 'pageCount'], 'defaults': [], 'name': '__MakePageButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BOX_WIDTH', 'type': 'int', 'value': 176}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiGuildBank'}, {'name': '__qualname__', 'type': 'str', 'value': 'GuildBankDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'localPos'], 'defaults': [], 'name': 'GetInfoData'},
                     {'args': ['self'], 'defaults': [], 'name': 'MakeInfoList'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScrollInfoLine'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGuildBankInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'GUILD_GOLD_TYPE_BUY_GUILD_LAND', 'type': 'int', 'value': 7},
                    {'name': 'GUILD_GOLD_TYPE_CHANGE_SMELTER', 'type': 'int', 'value': 8},
                    {'name': 'GUILD_GOLD_TYPE_DEAL_GUILD_LAND', 'type': 'int', 'value': 11},
                    {'name': 'GUILD_GOLD_TYPE_DRAGON_SP_RECOVER', 'type': 'int', 'value': 6},
                    {'name': 'GUILD_GOLD_TYPE_IN', 'type': 'int', 'value': 0},
                    {'name': 'GUILD_GOLD_TYPE_OBJECT_CHANGE', 'type': 'int', 'value': 4},
                    {'name': 'GUILD_GOLD_TYPE_OBJECT_CREATE', 'type': 'int', 'value': 5},
                    {'name': 'GUILD_GOLD_TYPE_OUT', 'type': 'int', 'value': 1},
                    {'name': 'GUILD_GOLD_TYPE_PROMOTE', 'type': 'int', 'value': 2},
                    {'name': 'GUILD_GOLD_TYPE_PROMOTE_UPDATE', 'type': 'int', 'value': 3},
                    {'name': 'GUILD_GOLD_TYPE_UPGRADE_ALTEROFPOWER', 'type': 'int', 'value': 9},
                    {'name': 'GUILD_GOLD_TYPE_UPGRADE_GUILDBANK', 'type': 'int', 'value': 10},
                    {'name': 'SLOTLINECOUNTER', 'type': 'int', 'value': 12},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiGuildBank'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'GuildBankLogDialog'}]}],
 'func': [{'args': ['n'], 'defaults': [], 'name': 'NumberToMoneyString'}],
 'import': ['snd', 'ime', 'uiToolTip', '__builtin__', 'app', 'wndMgr', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'guildbank', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiGuildBank'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
