{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialogMultiPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialogSinglePage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnIMEReturn'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'OnKeyDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPage1'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPage2'},
                     {'args': ['self', 'pageIndex'], 'defaults': [], 'name': '__SelectPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiHelp'}, {'name': '__qualname__', 'type': 'str', 'value': 'HelpWindow'}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'ui', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': 'ENABLE_HELP_MULTIPAGE', 'type': 'int', 'value': 0}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiHelp'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
