{'class': [{'class': [],
            'func': [{'args': ['self', 'key', 'PREV', 'NEXT', 'dict_delitem'], 'defaults': [0, 1, <slot wrapper '__delitem__' of 'dict' objects>], 'name': '__delitem__'},
                     {'args': ['self', 'other'], 'defaults': [], 'name': '__eq__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': '__iter__'},
                     {'args': ['self', 'other'], 'defaults': [], 'name': '__ne__'},
                     {'args': ['self'], 'defaults': [], 'name': '__reduce__'},
                     {'args': ['self', '_repr_running'], 'defaults': [{}], 'name': '__repr__'},
                     {'args': ['self'], 'defaults': [], 'name': '__reversed__'},
                     {'args': ['self', 'key', 'value', 'PREV', 'NEXT', 'dict_setitem'], 'defaults': [0, 1, <slot wrapper '__setitem__' of 'dict' objects>], 'name': '__setitem__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'copy'},
                     {'args': ['self'], 'defaults': [], 'name': 'items'},
                     {'args': ['self'], 'defaults': [], 'name': 'iteritems'},
                     {'args': ['self'], 'defaults': [], 'name': 'iterkeys'},
                     {'args': ['self'], 'defaults': [], 'name': 'itervalues'},
                     {'args': ['self'], 'defaults': [], 'name': 'keys'},
                     {'args': ['self', 'key', 'default'], 'defaults': [<object object at 0x09B51548>], 'name': 'pop'},
                     {'args': ['self', 'last'], 'defaults': [True], 'name': 'popitem'},
                     {'args': ['self', 'key', 'default'], 'defaults': [None], 'name': 'setdefault'},
                     {'args': ['self'], 'defaults': [], 'name': 'values'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewitems'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewkeys'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewvalues'}],
            'import': [],
            'var': [{'name': '_OrderedDict__marker', 'type': 'object', 'value': <object object at 0x09B51548>},
                    {'name': '_OrderedDict__update', 'type': 'instancemethod', 'value': <unbound method MutableMapping.update>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'OrderedDict' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'Dictionary that remembers insertion order'},
                    {'name': '__module__', 'type': 'str', 'value': 'collections'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'OrderedDict' objects>},
                    {'name': 'fromkeys', 'type': 'classmethod', 'value': <classmethod object at 0x0A5F0090>},
                    {'name': 'update', 'type': 'instancemethod', 'value': <unbound method MutableMapping.update>}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Record'},
                     {'args': ['self'], 'defaults': [], 'name': 'Reload'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOff'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOn'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'root_parent_window', 'parent_object', 'main_topic_index'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_MainTopic__height', 'type': 'member_descriptor', 'value': <member '_MainTopic__height' of 'MainTopic' objects>},
                    {'name': '_MainTopic__is_on', 'type': 'member_descriptor', 'value': <member '_MainTopic__is_on' of 'MainTopic' objects>},
                    {'name': '_MainTopic__main_topic_index', 'type': 'member_descriptor', 'value': <member '_MainTopic__main_topic_index' of 'MainTopic' objects>},
                    {'name': '_MainTopic__onoff_button_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__onoff_button_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__question_button_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__question_button_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__root_parent_window', 'type': 'member_descriptor', 'value': <member '_MainTopic__root_parent_window' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_image_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_image_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_text', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_text' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_text_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_text_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_text_window', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_text_window' of 'MainTopic' objects>},
                    {'name': '_MainTopic__width', 'type': 'member_descriptor', 'value': <member '_MainTopic__width' of 'MainTopic' objects>},
                    {'name': '_MainTopic__x', 'type': 'member_descriptor', 'value': <member '_MainTopic__x' of 'MainTopic' objects>},
                    {'name': '_MainTopic__y', 'type': 'member_descriptor', 'value': <member '_MainTopic__y' of 'MainTopic' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MainTopic'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__root_parent_window', '__title_image_object', '__title_text_window', '__title_text_object', '__question_button_object', '__onoff_button_object', '__main_topic_index', '__title_text', '__x', '__y', '__width', '__height', '__is_on')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ArrangeObject'},
                     {'args': ['self', 'key', 'default'], 'defaults': [None], 'name': 'GetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetDict'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'Record'},
                     {'args': ['self'], 'defaults': [], 'name': 'Reload'},
                     {'args': ['self', 'key', 'record_file'], 'defaults': [], 'name': 'SaveData'},
                     {'args': ['self', 'key', 'value'], 'defaults': [], 'name': 'SetData'},
                     {'args': ['self', 'new_dict'], 'defaults': [], 'name': 'SetDict'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'root_parent_window', 'parent_object', 'main_topic_index', 'sub_topic_index_list'], 'defaults': [None], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_LootingTopic__data_dict', 'type': 'member_descriptor', 'value': <member '_LootingTopic__data_dict' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__height', 'type': 'member_descriptor', 'value': <member '_LootingTopic__height' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__main_topic', 'type': 'member_descriptor', 'value': <member '_LootingTopic__main_topic' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__main_topic_index', 'type': 'member_descriptor', 'value': <member '_LootingTopic__main_topic_index' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__root_parent_window', 'type': 'member_descriptor', 'value': <member '_LootingTopic__root_parent_window' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__sub_topic_list', 'type': 'member_descriptor', 'value': <member '_LootingTopic__sub_topic_list' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__width', 'type': 'member_descriptor', 'value': <member '_LootingTopic__width' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__x', 'type': 'member_descriptor', 'value': <member '_LootingTopic__x' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__y', 'type': 'member_descriptor', 'value': <member '_LootingTopic__y' of 'LootingTopic' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'LootingTopic'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__root_parent_window', '__main_topic', '__sub_topic_list', '__x', '__y', '__width', '__height', '__main_topic_index', '__data_dict')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'IsChecked'},
                                {'args': ['self', 'is_checked'], 'defaults': [], 'name': 'SetChecked'},
                                {'args': ['self'], 'defaults': [], 'name': '__OnClick'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent_object', 'text'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': 'HEIGHT', 'type': 'int', 'value': 19},
                               {'name': 'START_POSITION_X', 'type': 'int', 'value': 4},
                               {'name': 'WIDTH', 'type': 'int', 'value': 122},
                               {'name': 'WIDTH_GAP', 'type': 'int', 'value': 10},
                               {'name': '_CheckObject__TEXT_HEIGHT', 'type': 'int', 'value': 16},
                               {'name': '_CheckObject__TEXT_WIDTH', 'type': 'int', 'value': 122},
                               {'name': '_CheckObject__base_image', 'type': 'member_descriptor', 'value': <member '_CheckObject__base_image' of 'CheckObject' objects>},
                               {'name': '_CheckObject__check_box_image', 'type': 'member_descriptor', 'value': <member '_CheckObject__check_box_image' of 'CheckObject' objects>},
                               {'name': '_CheckObject__is_checked', 'type': 'member_descriptor', 'value': <member '_CheckObject__is_checked' of 'CheckObject' objects>},
                               {'name': '_CheckObject__textline', 'type': 'member_descriptor', 'value': <member '_CheckObject__textline' of 'CheckObject' objects>},
                               {'name': '_CheckObject__textline_window', 'type': 'member_descriptor', 'value': <member '_CheckObject__textline_window' of 'CheckObject' objects>},
                               {'name': '_CheckObject__uncheck_box_image', 'type': 'member_descriptor', 'value': <member '_CheckObject__uncheck_box_image' of 'CheckObject' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'SubTopic.CheckObject'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__base_image', '__uncheck_box_image', '__check_box_image', '__textline_window', '__textline', '__is_checked')}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'Record'},
                     {'args': ['self'], 'defaults': [], 'name': 'Reload'},
                     {'args': ['self'], 'defaults': [], 'name': '__AdjustMinMaxValue'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeCheckObject'},
                     {'args': ['self', 'root_parent_window', 'parent_object', 'main_topic_index', 'sub_topic_index'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateSelectObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__MaxValueTabEnterFunc'},
                     {'args': ['self'], 'defaults': [], 'name': '__MinValueTabEnterFunc'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetDefaultMinMaxValue'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'root_parent_window', 'parent_object', 'main_topic_index', 'sub_topic_index'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'INNER_OBJECT_START_POSITION_X', 'type': 'int', 'value': 3},
                    {'name': '_SubTopic__check_object_list', 'type': 'member_descriptor', 'value': <member '_SubTopic__check_object_list' of 'SubTopic' objects>},
                    {'name': '_SubTopic__height', 'type': 'member_descriptor', 'value': <member '_SubTopic__height' of 'SubTopic' objects>},
                    {'name': '_SubTopic__is_checked_assassin', 'type': 'member_descriptor', 'value': <member '_SubTopic__is_checked_assassin' of 'SubTopic' objects>},
                    {'name': '_SubTopic__is_checked_shaman', 'type': 'member_descriptor', 'value': <member '_SubTopic__is_checked_shaman' of 'SubTopic' objects>},
                    {'name': '_SubTopic__is_checked_sura', 'type': 'member_descriptor', 'value': <member '_SubTopic__is_checked_sura' of 'SubTopic' objects>},
                    {'name': '_SubTopic__is_checked_warrior', 'type': 'member_descriptor', 'value': <member '_SubTopic__is_checked_warrior' of 'SubTopic' objects>},
                    {'name': '_SubTopic__is_checked_wolfman', 'type': 'member_descriptor', 'value': <member '_SubTopic__is_checked_wolfman' of 'SubTopic' objects>},
                    {'name': '_SubTopic__main_topic_index', 'type': 'member_descriptor', 'value': <member '_SubTopic__main_topic_index' of 'SubTopic' objects>},
                    {'name': '_SubTopic__range_value_image_object', 'type': 'member_descriptor', 'value': <member '_SubTopic__range_value_image_object' of 'SubTopic' objects>},
                    {'name': '_SubTopic__range_value_max_editline_object', 'type': 'member_descriptor', 'value': <member '_SubTopic__range_value_max_editline_object' of 'SubTopic' objects>},
                    {'name': '_SubTopic__range_value_min_editline_object', 'type': 'member_descriptor', 'value': <member '_SubTopic__range_value_min_editline_object' of 'SubTopic' objects>},
                    {'name': '_SubTopic__root_parent_window', 'type': 'member_descriptor', 'value': <member '_SubTopic__root_parent_window' of 'SubTopic' objects>},
                    {'name': '_SubTopic__select_area_window', 'type': 'member_descriptor', 'value': <member '_SubTopic__select_area_window' of 'SubTopic' objects>},
                    {'name': '_SubTopic__sub_topic_index', 'type': 'member_descriptor', 'value': <member '_SubTopic__sub_topic_index' of 'SubTopic' objects>},
                    {'name': '_SubTopic__title_image_object', 'type': 'member_descriptor', 'value': <member '_SubTopic__title_image_object' of 'SubTopic' objects>},
                    {'name': '_SubTopic__title_text', 'type': 'member_descriptor', 'value': <member '_SubTopic__title_text' of 'SubTopic' objects>},
                    {'name': '_SubTopic__title_text_object', 'type': 'member_descriptor', 'value': <member '_SubTopic__title_text_object' of 'SubTopic' objects>},
                    {'name': '_SubTopic__title_text_window', 'type': 'member_descriptor', 'value': <member '_SubTopic__title_text_window' of 'SubTopic' objects>},
                    {'name': '_SubTopic__width', 'type': 'member_descriptor', 'value': <member '_SubTopic__width' of 'SubTopic' objects>},
                    {'name': '_SubTopic__x', 'type': 'member_descriptor', 'value': <member '_SubTopic__x' of 'SubTopic' objects>},
                    {'name': '_SubTopic__y', 'type': 'member_descriptor', 'value': <member '_SubTopic__y' of 'SubTopic' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SubTopic'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__root_parent_window',
                               '__title_image_object',
                               '__title_text_window',
                               '__title_text_object',
                               '__range_value_image_object',
                               '__range_value_min_editline_object',
                               '__range_value_max_editline_object',
                               '__main_topic_index',
                               '__sub_topic_index',
                               '__title_text',
                               '__is_checked_warrior',
                               '__is_checked_assassin',
                               '__is_checked_sura',
                               '__is_checked_shaman',
                               '__is_checked_wolfman',
                               '__x',
                               '__y',
                               '__width',
                               '__height',
                               '__select_area_window',
                               '__check_object_list')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ArrangeObject'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'LootingSystemProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'main_topic_index'], 'defaults': [], 'name': 'OverInQuestionButton'},
                     {'args': ['self', 'main_topic_index'], 'defaults': [], 'name': 'OverOutQuestionButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitTopic'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickInitButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSaveButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__SaveAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__SaveFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScrollEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendLootingSettings'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_LootingSystem__close_question_dialog', 'type': 'member_descriptor', 'value': <member '_LootingSystem__close_question_dialog' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__diff_height', 'type': 'member_descriptor', 'value': <member '_LootingSystem__diff_height' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__init_button__save_button', 'type': 'member_descriptor', 'value': <member '_LootingSystem__init_button__save_button' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__init_question_dialog', 'type': 'member_descriptor', 'value': <member '_LootingSystem__init_question_dialog' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__looting_topic_dict', 'type': 'member_descriptor', 'value': <member '_LootingSystem__looting_topic_dict' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__object_area_window', 'type': 'member_descriptor', 'value': <member '_LootingSystem__object_area_window' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__question_tooltip', 'type': 'member_descriptor', 'value': <member '_LootingSystem__question_tooltip' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__save_question_dialog', 'type': 'member_descriptor', 'value': <member '_LootingSystem__save_question_dialog' of 'LootingSystem' objects>},
                    {'name': '_LootingSystem__scrollbar', 'type': 'member_descriptor', 'value': <member '_LootingSystem__scrollbar' of 'LootingSystem' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'LootingSystem'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__object_area_window', '__scrollbar', '__init_button__save_button', '__question_tooltip', '__close_question_dialog', '__init_question_dialog', '__save_question_dialog', '__looting_topic_dict', '__diff_height')}]},
           {'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'GetMainTopicTitleLoca', 'type': 'classmethod', 'value': <classmethod object at 0x2E0E4ED0>},
                    {'name': 'GetQuestionTooltipDescList', 'type': 'classmethod', 'value': <classmethod object at 0x2E0E4EB0>},
                    {'name': 'GetSubTopicTitleLoca', 'type': 'classmethod', 'value': <classmethod object at 0x2E0E4EF0>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'LootingSystemLoca' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'LootingSystemLoca'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'LootingSystemLoca' objects>}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'grp', 'uiToolTip', 'uiScriptLocale', 'uiCommon', 'cPickle', '__builtin__', 'wndMgr', 'ui', 'os'],
 'var': [{'name': 'DEFAULT_ONOFF', 'type': 'bool', 'value': True},
         {'name': 'LOOTING_SYSTEM_IMG_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/looting/'},
         {'name': 'LOOTING_TOPIC_GAP', 'type': 'int', 'value': 6},
         {'name': 'MAIN_SUB_TOPIC_GAP', 'type': 'int', 'value': 6},
         {'name': 'MAIN_TOPIC_HEIGHT', 'type': 'int', 'value': 23},
         {'name': 'MAIN_TOPIC_INDEX_ARMOR', 'type': 'int', 'value': 1},
         {'name': 'MAIN_TOPIC_INDEX_COMMON', 'type': 'int', 'value': 3},
         {'name': 'MAIN_TOPIC_INDEX_CONSUMPTION', 'type': 'int', 'value': 7},
         {'name': 'MAIN_TOPIC_INDEX_COSTUME', 'type': 'int', 'value': 6},
         {'name': 'MAIN_TOPIC_INDEX_DS', 'type': 'int', 'value': 4},
         {'name': 'MAIN_TOPIC_INDEX_ETC', 'type': 'int', 'value': 9},
         {'name': 'MAIN_TOPIC_INDEX_EVENT', 'type': 'int', 'value': 10},
         {'name': 'MAIN_TOPIC_INDEX_HEAD', 'type': 'int', 'value': 2},
         {'name': 'MAIN_TOPIC_INDEX_MAX', 'type': 'int', 'value': 11},
         {'name': 'MAIN_TOPIC_INDEX_SKILL_BOOK', 'type': 'int', 'value': 8},
         {'name': 'MAIN_TOPIC_INDEX_UNIQUE', 'type': 'int', 'value': 5},
         {'name': 'MAIN_TOPIC_INDEX_WEAPON', 'type': 'int', 'value': 0},
         {'name': 'REFINE_MAX', 'type': 'int', 'value': 200},
         {'name': 'REFINE_MIN', 'type': 'int', 'value': 0},
         {'name': 'SCROLL_STEP', 'type': 'int', 'value': 18},
         {'name': 'SUB_TOPIC_HEIGHT', 'type': 'int', 'value': 18},
         {'name': 'SUB_TOPIC_INDEX_CATEGORY_COMMON', 'type': 'int', 'value': 4},
         {'name': 'SUB_TOPIC_INDEX_CATEGORY_COSTUME', 'type': 'int', 'value': 5},
         {'name': 'SUB_TOPIC_INDEX_CATEGORY_JOB', 'type': 'int', 'value': 0},
         {'name': 'SUB_TOPIC_INDEX_CATEGORY_SKILL_JOB', 'type': 'int', 'value': 1},
         {'name': 'SUB_TOPIC_INDEX_MAX', 'type': 'int', 'value': 6},
         {'name': 'SUB_TOPIC_INDEX_REFINE', 'type': 'int', 'value': 2},
         {'name': 'SUB_TOPIC_INDEX_WEARING_LEVEL', 'type': 'int', 'value': 3},
         {'name': 'TOPIC_WIDTH', 'type': 'int', 'value': 270},
         {'name': 'WEARING_LEVEL_MAX', 'type': 'int', 'value': 120},
         {'name': 'WEARING_LEVEL_MIN', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiLootingSystem'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
