{'class': [{'class': [],
            'func': [{'args': ['self', 'key', 'PREV', 'NEXT', 'dict_delitem'], 'defaults': [0, 1, <slot wrapper '__delitem__' of 'dict' objects>], 'name': '__delitem__'},
                     {'args': ['self', 'other'], 'defaults': [], 'name': '__eq__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': '__iter__'},
                     {'args': ['self', 'other'], 'defaults': [], 'name': '__ne__'},
                     {'args': ['self'], 'defaults': [], 'name': '__reduce__'},
                     {'args': ['self', '_repr_running'], 'defaults': [{}], 'name': '__repr__'},
                     {'args': ['self'], 'defaults': [], 'name': '__reversed__'},
                     {'args': ['self', 'key', 'value', 'PREV', 'NEXT', 'dict_setitem'], 'defaults': [0, 1, <slot wrapper '__setitem__' of 'dict' objects>], 'name': '__setitem__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'copy'},
                     {'args': ['self'], 'defaults': [], 'name': 'items'},
                     {'args': ['self'], 'defaults': [], 'name': 'iteritems'},
                     {'args': ['self'], 'defaults': [], 'name': 'iterkeys'},
                     {'args': ['self'], 'defaults': [], 'name': 'itervalues'},
                     {'args': ['self'], 'defaults': [], 'name': 'keys'},
                     {'args': ['self', 'key', 'default'], 'defaults': [<object object at 0x09901528>], 'name': 'pop'},
                     {'args': ['self', 'last'], 'defaults': [True], 'name': 'popitem'},
                     {'args': ['self', 'key', 'default'], 'defaults': [None], 'name': 'setdefault'},
                     {'args': ['self'], 'defaults': [], 'name': 'values'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewitems'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewkeys'},
                     {'args': ['self'], 'defaults': [], 'name': 'viewvalues'}],
            'import': [],
            'var': [{'name': '_OrderedDict__marker', 'type': 'object', 'value': <object object at 0x09901528>},
                    {'name': '_OrderedDict__update', 'type': 'instancemethod', 'value': <unbound method MutableMapping.update>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'OrderedDict' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'Dictionary that remembers insertion order'},
                    {'name': '__module__', 'type': 'str', 'value': 'collections'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'OrderedDict' objects>},
                    {'name': 'fromkeys', 'type': 'classmethod', 'value': <classmethod object at 0x0B34E0D0>},
                    {'name': 'update', 'type': 'instancemethod', 'value': <unbound method MutableMapping.update>}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Record'},
                     {'args': ['self'], 'defaults': [], 'name': 'Reload'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOff'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickOn'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'root_parent_window', 'parent_object', 'main_topic_index'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_MainTopic__height', 'type': 'member_descriptor', 'value': <member '_MainTopic__height' of 'MainTopic' objects>},
                    {'name': '_MainTopic__is_on', 'type': 'member_descriptor', 'value': <member '_MainTopic__is_on' of 'MainTopic' objects>},
                    {'name': '_MainTopic__main_topic_index', 'type': 'member_descriptor', 'value': <member '_MainTopic__main_topic_index' of 'MainTopic' objects>},
                    {'name': '_MainTopic__onoff_button_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__onoff_button_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__question_button_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__question_button_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__root_parent_window', 'type': 'member_descriptor', 'value': <member '_MainTopic__root_parent_window' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_image_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_image_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_text', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_text' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_text_object', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_text_object' of 'MainTopic' objects>},
                    {'name': '_MainTopic__title_text_window', 'type': 'member_descriptor', 'value': <member '_MainTopic__title_text_window' of 'MainTopic' objects>},
                    {'name': '_MainTopic__width', 'type': 'member_descriptor', 'value': <member '_MainTopic__width' of 'MainTopic' objects>},
                    {'name': '_MainTopic__x', 'type': 'member_descriptor', 'value': <member '_MainTopic__x' of 'MainTopic' objects>},
                    {'name': '_MainTopic__y', 'type': 'member_descriptor', 'value': <member '_MainTopic__y' of 'MainTopic' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MainTopic'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__root_parent_window', '__title_image_object', '__title_text_window', '__title_text_object', '__question_button_object', '__onoff_button_object', '__main_topic_index', '__title_text', '__x', '__y', '__width', '__height', '__is_on')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ArrangeObject'},
                     {'args': ['self', 'key', 'default'], 'defaults': [None], 'name': 'GetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetDict'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'Record'},
                     {'args': ['self'], 'defaults': [], 'name': 'Reload'},
                     {'args': ['self', 'key', 'record_file'], 'defaults': [], 'name': 'SaveData'},
                     {'args': ['self', 'key', 'value'], 'defaults': [], 'name': 'SetData'},
                     {'args': ['self', 'new_dict'], 'defaults': [], 'name': 'SetDict'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'root_parent_window', 'parent_object', 'main_topic_index', 'sub_topic_index_list'], 'defaults': [None], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_LootingTopic__data_dict', 'type': 'member_descriptor', 'value': <member '_LootingTopic__data_dict' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__height', 'type': 'member_descriptor', 'value': <member '_LootingTopic__height' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__main_topic', 'type': 'member_descriptor', 'value': <member '_LootingTopic__main_topic' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__main_topic_index', 'type': 'member_descriptor', 'value': <member '_LootingTopic__main_topic_index' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__root_parent_window', 'type': 'member_descriptor', 'value': <member '_LootingTopic__root_parent_window' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__sub_topic_list', 'type': 'member_descriptor', 'value': <member '_LootingTopic__sub_topic_list' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__width', 'type': 'member_descriptor', 'value': <member '_LootingTopic__width' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__x', 'type': 'member_descriptor', 'value': <member '_LootingTopic__x' of 'LootingTopic' objects>},
                    {'name': '_LootingTopic__y', 'type': 'member_descriptor', 'value': <member '_LootingTopic__y' of 'LootingTopic' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiLootingSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'LootingTopic'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__root_parent_window', '__main_topic', '__sub_topic_list', '__x', '__y', '__width', '__height', '__main_topic_index', '__data_dict')}]},