{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRecv'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRetry'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetTop'},
                     {'args': ['self', 'dwItemVnum', 'byItemCount', 'iNeedMoney', 'wSlotIndex'], 'defaults': [], 'name': 'ShowLuckyBoxWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': '__popUpDialogAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__popUpDialogCancel'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiLuckyBox'}, {'name': '__qualname__', 'type': 'str', 'value': 'LuckyBoxWindow'}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'playerm2g2', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiLuckyBox'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
