{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [1], 'name': 'CantPostItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseClear'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'is_distance_check'], 'defaults': [], 'name': 'MailBoxOpen'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MailBoxProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'ds_window'], 'defaults': [], 'name': 'SetDSWindow'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__AllPostButtonEnable'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAllDeleteButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAllGetItemsButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickNextButton'},
                     {'args': ['self', 'button_index', 'data_index'], 'defaults': [], 'name': '__ClickPost'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickPostWriteButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickPrevButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClosePostAllDeleteQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClosePostAllGetItemsQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreatePostList'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreatePostReadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreatePostWriteWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenAllGetItemsFailPopup'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenPostAllDeleteFailPopupDlg'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenPostAllDeleteQuestionDlg'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenPostAllGetItemsQuestionDlg'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__PostAllDeleteFail'},
                     {'args': ['self'], 'defaults': [], 'name': '__PostAllDeleteSuccess'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__PostAllGetItemsFail'},
                     {'args': ['self', 'getSuccessKeyList'], 'defaults': [], 'name': '__PostAllGetItemsSuccess'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__PostDeleteFail'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': '__PostDeleteSuccess'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__PostGetItemsFail'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': '__PostGetItemsSuccess'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': '__PostGetItemsSuccessNoRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__PostRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshMailBoxGMButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__RefreshPostButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendPostAllDelete'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendPostAllGetItems'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMailBox'}, {'name': '__qualname__', 'type': 'str', 'value': 'MailBox'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [1], 'name': 'CantPostItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'PostWriteConfirmResult'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'PostWriteResult'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'money', 'cheque'], 'defaults': [], 'name': 'SendMoneyAccept'},
                     {'args': ['self', 'ds_window'], 'defaults': [], 'name': 'SetDSWindow'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOnTopWindowNone'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearSlotItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickConfirmButton'},
                     {'args': ['self', 'i'], 'defaults': [], 'name': '__ClickFriendName'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickFriendSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRenderBox'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickWonYangWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClosePostWriteQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateFriendNameButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateSendMoneyDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__DSWindowUpdate'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__FriendNameOver'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__FriendNameOverOut'},
                     {'args': ['self', 'show'], 'defaults': [], 'name': '__FriendSelectWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__InvenUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MessageEditLineTabEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__NameModifyCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenPostWriteQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshFriendListText'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshFriendNameButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshMessageCount'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendPostWrite'},
                     {'args': ['self'], 'defaults': [], 'name': '__TitleEditLineTabEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ToEditLineTabEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMailBox'}, {'name': '__qualname__', 'type': 'str', 'value': 'PostWrite'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'time'], 'defaults': [], 'name': 'SecondToDH'},
                     {'args': ['self', 'is_confirm'], 'defaults': [], 'name': 'SetConfirmColor'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': 'SetDataIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetDisable'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetEnable'},
                     {'args': ['self', 'icon_type'], 'defaults': [], 'name': 'SetIcon'},
                     {'args': ['self', 'end_time'], 'defaults': [], 'name': 'SetRemainTime'},
                     {'args': ['self', 'title'], 'defaults': [], 'name': 'SetTitle'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ButtonClickFunc'},
                     {'args': ['self', 'button_index', 'parent'], 'defaults': [], 'name': '__CreatePost'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'button_index', 'parent', 'click_func'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMailBox'}, {'name': '__qualname__', 'type': 'str', 'value': 'Post'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetDataIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'cheque'], 'defaults': [], 'name': 'SetCheque'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': 'SetDataIndex'},
                     {'args': ['self', 'from_name'], 'defaults': [], 'name': 'SetFromName'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetItem'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': 'SetMessage'},
                     {'args': ['self', 'title'], 'defaults': [], 'name': 'SetTitle'},
                     {'args': ['self', 'yang'], 'defaults': [], 'name': 'SetYang'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__BlockName'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickBlockButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickDeleteButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRecvButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseBlockQuestionDlg'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseGetItemsQuestionDlg'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClosePostDeleteQuestionDlg'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendPostDelete'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendPostGetItems'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'close_call_back_func'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMailBox'}, {'name': '__qualname__', 'type': 'str', 'value': 'PostRead'}]}],
 'func': [{'args': ['self', 'fileName'], 'defaults': [], 'name': 'LoadScript'}, {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['chatm2g', 'app', 'uiPickMoney', 'm2netm2g', 'playerm2g2', 'constInfo', 'grp', 'messenger', 'mouseModule', 'uiScriptLocale', 'mail', 'localeInfo', 'math', 'uiCommon', '__builtin__', 'item', 'ui'],
 'var': [{'name': 'DIVISION_EMPTY', 'type': 'int', 'value': 0},
         {'name': 'DIVISION_GM', 'type': 'int', 'value': 3},
         {'name': 'DIVISION_ITEM', 'type': 'int', 'value': 2},
         {'name': 'DIVISION_POST', 'type': 'int', 'value': 1},
         {'name': 'EMPTY_ICON_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/mailbox/mailbox_icon_empty.sub'},
         {'name': 'FRIEND_SELECT_UI_SHOW_MAX', 'type': 'int', 'value': 10},
         {'name': 'GM_ICON_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/mailbox/mailbox_icon_gm.sub'},
         {'name': 'ITEM_ICON_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/mailbox/mailbox_icon_item.sub'},
         {'name': 'MAILBOX_MAX_DISTANCE', 'type': 'int', 'value': 1000},
         {'name': 'MAX_CHEQUE', 'type': 'int', 'value': 999},
         {'name': 'MAX_YANG', 'type': 'int', 'value': 9998999},
         {'name': 'POST_ICON_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/mailbox/mailbox_icon_post.sub'},
         {'name': 'POST_MAX', 'type': 'int', 'value': 9},
         {'name': 'POST_WRITE_COST', 'type': 'int', 'value': 1000},
         {'name': 'POST_WRITE_LIMIT_LEVEL', 'type': 'int', 'value': 20},
         {'name': 'TITLE_MAX_LEN', 'type': 'int', 'value': 25},
         {'name': 'WORD_MAX', 'type': 'int', 'value': 65535},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMailBox'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
