{'class': [{'class': [],
            'func': [{'args': ['self', 'mapName', 'x', 'y'], 'defaults': [], 'name': 'ShowMapName'},
                     {'args': ['self'], 'defaults': [], 'name': 'Update'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': '__GetDevilBase'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': '__GetDevilTowerFloor'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'MAP_NAME_IMAGE', 'type': 'dict', 'value': {}},
                    {'name': 'STATE_FADE_IN', 'type': 'int', 'value': 1},
                    {'name': 'STATE_FADE_OUT', 'type': 'int', 'value': 3},
                    {'name': 'STATE_HIDE', 'type': 'int', 'value': 0},
                    {'name': 'STATE_SHOW', 'type': 'int', 'value': 2},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMapNameShower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MapNameShower'}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'ui', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': 'LOCALE_PATH', 'type': 'str', 'value': 'locale/hu/ui/mapname/'}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiMapNameShower'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
