{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'CloseMercenaryToolTip', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A77D0>},
                    {'name': 'CloseQuestionDialog', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7750>},
                    {'name': 'CloseQuestionDialog2', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A76F0>},
                    {'name': 'GetMercenaryName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7510>},
                    {'name': 'GetMercenaryNameImgFileName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A73F0>},
                    {'name': 'GetMercenarySkillBenefitName_1', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A75F0>},
                    {'name': 'GetMercenarySkillBenefitName_2', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7630>},
                    {'name': 'GetMercenarySkillBenefitValue_1', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7610>},
                    {'name': 'GetMercenarySkillBenefitValue_2', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7650>},
                    {'name': 'GetMercenarySkillName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A75D0>},
                    {'name': 'GetMercenarySpecificityImgFileName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7410>},
                    {'name': 'GetMercenaryStateImgFileName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7430>},
                    {'name': 'GetMissionLocationName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A74B0>},
                    {'name': 'GetMissionName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7490>},
                    {'name': 'GetMissionStateImgFileName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7470>},
                    {'name': 'GetMissionStateName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A74D0>},
                    {'name': 'GetMissionSuggestionImgFileName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7450>},
                    {'name': 'GetMissionTypeName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A74F0>},
                    {'name': 'GetSpecificityBenefitFirstName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7550>},
                    {'name': 'GetSpecificityBenefitSecondtName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7570>},
                    {'name': 'GetSpecificityGainNextLevel', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7670>},
                    {'name': 'GetSpecificityGradeName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7590>},
                    {'name': 'GetSpecificityGradeValue', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A75B0>},
                    {'name': 'GetSpecificityName', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7530>},
                    {'name': 'HideNormalToolTip', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7810>},
                    {'name': 'MercenaryAppendChat', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7870>},
                    {'name': 'MercenaryUtilInit', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A73B0>},
                    {'name': 'MercenaryUtilSetLoca', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A73D0>},
                    {'name': 'OpenPopupDialog', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7690>},
                    {'name': 'OpenQuestionDialog', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7710>},
                    {'name': 'OpenQuestionDialog2', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A76D0>},
                    {'name': 'SetCloseQuestionPopupEvent', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7730>},
                    {'name': 'SetFinalToolTipWidth', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7850>},
                    {'name': 'ShowMercenarySpecificityToolTip', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7790>},
                    {'name': 'ShowMercenaryStateToolTip', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7770>},
                    {'name': 'ShowMercenaryToolTip', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A77B0>},
                    {'name': 'ShowNormalToolTip', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A77F0>},
                    {'name': 'ToolTipProgress', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A7830>},
                    {'name': '_MercenaryUtil__ClosePopupDialog', 'type': 'classmethod', 'value': <classmethod object at 0x1A5A76B0>},
                    {'name': '_MercenaryUtil__MERCENARY_NAME_IMG_FILENAME',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/game/mercenary/mercenary_name_normal.sub',
                               1: 'd:/ymir work/ui/game/mercenary/mercenary_name_nimble.sub',
                               2: 'd:/ymir work/ui/game/mercenary/mercenary_name_strong.sub',
                               3: 'd:/ymir work/ui/game/mercenary/mercenary_name_trained.sub',
                               4: 'd:/ymir work/ui/game/mercenary/mercenary_name_collector.sub',
                               5: 'd:/ymir work/ui/game/mercenary/mercenary_name_lucky.sub',
                               6: 'd:/ymir work/ui/game/mercenary/mercenary_name_exp.sub',
                               7: 'd:/ymir work/ui/game/mercenary/mercenary_name_empty.sub'}},
                    {'name': '_MercenaryUtil__MERCENARY_NAME_IMG_FILENAME__MERCENARY_SPECIFICITY_IMG_FILENAME__MERCENARY_STATE_IMG_FILENAME__MISSION_SUGGESTION_IMG_FILENAME__MISSION_STATE_IMG_FILENAME__MERCENARY_NAME_LOCA__MERCENARY_SPECIFICITY_LOCA__MERCENARY_SPECIFICITY_BENEFIT_1_LOCA__MERCENARY_SPECIFICITY_BENEFIT_2_LOCA__MERCENARY_SPECIFICITY_GRADE_LOWER_LOCA__MERCENARY_SKILL_NAME_LOCA__MERCENARY_SKILL_BENEFIT_LOCA_1__MERCENARY_SKILL_BENEFIT_VALUE_1__MERCENARY_SKILL_BENEFIT_LOCA_2__MERCENARY_SKILL_BENEFIT_VALUE_2__MISSION_TYPE_LOCA__MISSION_STATE_LOCA__MISSION_MAP_LOCA__MISSION_NAME_LOCA__MERCENARY_SPECIFICITY_VALUE__MERCENARY_SPECIFICITY_LEARN_LEVEL__accept_popup__question_popup__question_popup_2__mercenary_tooltip',
                     'type': 'member_descriptor',
                     'value': <member '_MercenaryUtil__MERCENARY_NAME_IMG_FILENAME__MERCENARY_SPECIFICITY_IMG_FILENAME__MERCENARY_STATE_IMG_FILENAME__MISSION_SUGGESTION_IMG_FILENAME__MISSION_STATE_IMG_FILENAME__MERCENARY_NAME_LOCA__MERCENARY_SPECIFICITY_LOCA__MERCENARY_SPECIFICITY_BENEFIT_1_LOCA__MERCENARY_SPECIFICITY_BENEFIT_2_LOCA__MERCENARY_SPECIFICITY_GRADE_LOWER_LOCA__MERCENARY_SKILL_NAME_LOCA__MERCENARY_SKILL_BENEFIT_LOCA_1__MERCENARY_SKILL_BENEFIT_VALUE_1__MERCENARY_SKILL_BENEFIT_LOCA_2__MERCENARY_SKILL_BENEFIT_VALUE_2__MISSION_TYPE_LOCA__MISSION_STATE_LOCA__MISSION_MAP_LOCA__MISSION_NAME_LOCA__MERCENARY_SPECIFICITY_VALUE__MERCENARY_SPECIFICITY_LEARN_LEVEL__accept_popup__question_popup__question_popup_2__mercenary_tooltip' of 'MercenaryUtil' objects>},
                    {'name': '_MercenaryUtil__MERCENARY_NAME_LOCA', 'type': 'dict', 'value': {0: '\xc1tlagos', 1: '\xdcgyes', 2: 'Er\xf5s', 3: 'Tapasztalt', 4: 'Begy\xfbjt\xf5', 5: 'Szerencs\xe9s', 6: 'Tan\xedt\xf3'}},
                    {'name': '_MercenaryUtil__MERCENARY_SKILL_BENEFIT_LOCA_1', 'type': 'dict', 'value': {1: 'Bevet\xe9s id\xf5tartama: %.1f%%', 2: 'Siker es\xe9lye: +%.1f%%', 3: 'S\xe9r\xfcl\xe9s es\xe9lye: %.1f%%', 4: 'S\xe9r\xfcl\xe9s es\xe9lye: +%.1f%%', 5: 'Bajnok EXP: %.1f%%', 6: 'Siker es\xe9lye: +%.1f%%'}},
                    {'name': '_MercenaryUtil__MERCENARY_SKILL_BENEFIT_LOCA_2', 'type': 'dict', 'value': {4: 'Siker es\xe9lye: +%.1f%%', 6: 'Siker es\xe9lye: +%.1f%%'}},
                    {'name': '_MercenaryUtil__MERCENARY_SKILL_BENEFIT_VALUE_1', 'type': 'dict', 'value': {0: 0.0, 1: 0.2, 2: 0.2, 3: 0.1, 4: 0.6, 5: 0.3, 6: 0.5}},
                    {'name': '_MercenaryUtil__MERCENARY_SKILL_BENEFIT_VALUE_2', 'type': 'dict', 'value': {4: 0.3}},
                    {'name': '_MercenaryUtil__MERCENARY_SKILL_NAME_LOCA',
                     'type': 'dict',
                     'value': {1: 'Cs\xf6kkenti a bevet\xe9s id\xf5tartam\xe1t.', 2: 'N\xf6veli a siker es\xe9ly\xe9t.', 3: 'Cs\xf6kkenti a megsebes\xfcl\xe9s es\xe9ly\xe9t.', 4: 'Kock\xe1zat el\xf5ny\xf6k', 5: 'Extra Bajnokszint EXP', 6: 'Egyedi'}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_BENEFIT_1_LOCA', 'type': 'dict', 'value': {1: 'Siker es\xe9lye: +%.1f%%', 2: 'Siker es\xe9lye: +%.1f%%', 3: 'Siker es\xe9lye: +%.1f%%', 4: 'Siker es\xe9lye: +%.1f%%', 5: 'Es\xe9ly extra jutalomra: +%.1f%%'}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_BENEFIT_2_LOCA', 'type': 'dict', 'value': {1: 'Bevet\xe9s id\xf5tartama: %.1f%%', 2: 'S\xe9r\xfcl\xe9s es\xe9lye: %.1f%%', 4: 'Es\xe9ly extra jutalomra: +%.1f%%'}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_GRADE_LOWER_LOCA', 'type': 'dict', 'value': {0: '(Alap)', 1: '(K\xf6zepes)', 2: '(Fejlett)'}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_IMG_FILENAME',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_none.sub',
                               1: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_spy.sub',
                               2: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_fighter.sub',
                               3: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_rescue.sub',
                               4: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_collector.sub',
                               5: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_lucky.sub'}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_LEARN_LEVEL', 'type': 'dict', 'value': {10: [1, 2, 3, 4, 5, 6, 7, 8, 9], 20: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 30: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_LOCA', 'type': 'dict', 'value': {0: 'Nincs', 1: 'Felder\xedt\xf5', 2: 'Harcos', 3: 'Megment\xf5', 4: 'Begy\xfbjt\xf5', 5: 'Szerencs\xe9s \xf6rd\xf6g'}},
                    {'name': '_MercenaryUtil__MERCENARY_SPECIFICITY_VALUE', 'type': 'dict', 'value': {1: {0: 1, 1: 3, 2: 5}, 2: {0: 1, 1: 3, 2: 5}, 3: {0: 1, 1: 3, 2: 5}, 4: {0: 1, 1: 3, 2: 5}, 5: {0: 1, 1: 3, 2: 7}}},
                    {'name': '_MercenaryUtil__MERCENARY_STATE_IMG_FILENAME', 'type': 'dict', 'value': {0: 'd:/ymir work/ui/game/mercenary/mercenary_specificity_none.sub', 1: 'd:/ymir work/ui/game/mercenary/mercenary_state_injure.sub', 2: 'd:/ymir work/ui/game/mercenary/mercenary_state_run.sub'}},
                    {'name': '_MercenaryUtil__MISSION_MAP_LOCA',
                     'type': 'dict',
                     'value': {0: 'Nincs',
                               1: 'Seungryong-v\xf6lgy',
                               2: 'Yongbi-sivatag',
                               3: 'Kuahlo Dong (p\xf3k kazamata)',
                               4: 'Hwang templom',
                               5: 'D\xe9mon-torony',
                               6: 'A Sz\xe1m\xfbz\xf6tt barlangja',
                               7: 'Az \xd6rd\xf6g katakomb\xe1ja',
                               8: 'Nemere \xf5rtornya',
                               9: 'Meley barlangja',
                               10: 'Elvar\xe1zsolt erd\xf5',
                               11: 'Dong Gwang s\xedks\xe1g',
                               12: 'Gnoll barlang',
                               13: 'Yilad h\xe1g\xf3',
                               14: 'Szerpent templom',
                               15: '\xc9szaksz\xe9l b\xfav\xf3hely'}},
                    {'name': '_MercenaryUtil__MISSION_NAME_LOCA', 'type': 'dict', 'value': {0: 'Nincs', 1: 'H\xf3d\xedt\xe1s (k\xf6nny\xfb)', 2: 'H\xf3d\xedt\xe1s (neh\xe9z)', 3: 'Puszt\xedt\xe1s', 4: 'Felder\xedt\xe9s'}},
                    {'name': '_MercenaryUtil__MISSION_STATE_IMG_FILENAME',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/game/mercenary/mercenary_mission_icon_complete.sub',
                               1: 'd:/ymir work/ui/game/mercenary/mercenary_mission_icon_none.sub',
                               2: 'd:/ymir work/ui/game/mercenary/mercenary_mission_icon_run.sub',
                               3: 'd:/ymir work/ui/game/mercenary/mercenary_mission_icon_end.sub',
                               4: 'd:/ymir work/ui/game/mercenary/mercenary_mission_icon_giveup.sub'}},
                    {'name': '_MercenaryUtil__MISSION_STATE_LOCA', 'type': 'dict', 'value': {0: 'Befejezve', 1: 'El\xe9rhet\xf5', 2: 'Kik\xfcldve', 3: 'Befejez', 4: 'M\xe9gse'}},
                    {'name': '_MercenaryUtil__MISSION_SUGGESTION_IMG_FILENAME',
                     'type': 'dict',
                     'value': {1: 'd:/ymir work/ui/game/mercenary/mercenary_mission_type_spy.sub',
                               2: 'd:/ymir work/ui/game/mercenary/mercenary_mission_type_fighter.sub',
                               3: 'd:/ymir work/ui/game/mercenary/mercenary_mission_type_rescue.sub',
                               4: 'd:/ymir work/ui/game/mercenary/mercenary_mission_type_collector.sub',
                               5: 'd:/ymir work/ui/game/mercenary/mercenary_mission_type_lucky.sub'}},
                    {'name': '_MercenaryUtil__MISSION_TYPE_LOCA', 'type': 'dict', 'value': {1: 'Felder\xedt\xf5', 2: 'Harcos', 3: 'Megment\xf5', 4: 'Begy\xfbjt\xf5', 5: 'Szerencs\xe9s \xf6rd\xf6g'}},
                    {'name': '_MercenaryUtil__accept_popup', 'type': 'NoneType', 'value': None},
                    {'name': '_MercenaryUtil__mercenary_tooltip', 'type': 'NoneType', 'value': None},
                    {'name': '_MercenaryUtil__question_popup', 'type': 'NoneType', 'value': None},
                    {'name': '_MercenaryUtil__question_popup_2', 'type': 'NoneType', 'value': None},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryUtil'},
                    {'name': '__slots__',
                     'type': 'str',
                     'value': '__MERCENARY_NAME_IMG_FILENAME__MERCENARY_SPECIFICITY_IMG_FILENAME__MERCENARY_STATE_IMG_FILENAME__MISSION_SUGGESTION_IMG_FILENAME__MISSION_STATE_IMG_FILENAME__MERCENARY_NAME_LOCA__MERCENARY_SPECIFICITY_LOCA__MERCENARY_SPECIFICITY_BENEFIT_1_LOCA__MERCENARY_SPECIFICITY_BENEFIT_2_LOCA__MERCENARY_SPECIFICITY_GRADE_LOWER_LOCA__MERCENARY_SKILL_NAME_LOCA__MERCENARY_SKILL_BENEFIT_LOCA_1__MERCENARY_SKILL_BENEFIT_VALUE_1__MERCENARY_SKILL_BENEFIT_LOCA_2__MERCENARY_SKILL_BENEFIT_VALUE_2__MISSION_TYPE_LOCA__MISSION_STATE_LOCA__MISSION_MAP_LOCA__MISSION_NAME_LOCA__MERCENARY_SPECIFICITY_VALUE__MERCENARY_SPECIFICITY_LEARN_LEVEL__accept_popup__question_popup__question_popup_2__mercenary_tooltip'}]},
           {'class': [],
            'func': [{'args': ['self', 'message'], 'defaults': [], 'name': 'AppendText'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetButtonPos'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BOARD_ADDITIONAL_HEIGHT_INTERVAL', 'type': 'int', 'value': 50},
                    {'name': 'BOARD_ADDITIONAL_WIDTH_INTERVAL', 'type': 'int', 'value': 40},
                    {'name': 'BUTTON_HEIGHT_INTERVAL', 'type': 'int', 'value': 42},
                    {'name': 'DEFAULT_BOARD_WIDTH', 'type': 'int', 'value': 40},
                    {'name': 'START_TEXT_POS_Y', 'type': 'int', 'value': 28},
                    {'name': 'TEXT_LINE_HEIGHT', 'type': 'int', 'value': 20},
                    {'name': 'TEXT_LINE_LEFT_INTERVAL', 'type': 'int', 'value': 20},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryMissionResultDialog'},
                    {'name': '__slots__', 'type': 'str', 'value': '__board__accept_button__text_list'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'skill_vnum', 'need_yang', 'window', 'slot_index'], 'defaults': [], 'name': 'MercenaryAddAsk'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'MercenaryAppendChat'},
                     {'args': ['self', 'mission_vid', 'map_number'], 'defaults': [], 'name': 'MercenaryDispatchSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryDrainResult'},
                     {'args': ['self', 'need_item_count', 'window', 'slot_index'], 'defaults': [], 'name': 'MercenaryExpandSlotItemUseAsk'},
                     {'args': ['self', 'mission_vid', 'map_number'], 'defaults': [], 'name': 'MercenaryGiveUpSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryMissionAllRefresh'},
                     {'args': ['self', 'mission_vid', 'mission_name', 'injure_count'], 'defaults': [], 'name': 'MercenaryResultFail'},
                     {'args': ['self', 'mission_vid', 'data'], 'defaults': [], 'name': 'MercenaryResultSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenMercenaryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshActiveText'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCurrentMercenaryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMercenaryManageList'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMission'},
                     {'args': ['self'], 'defaults': [], 'name': 'RequestMercenaryWindowOpen'},
                     {'args': ['self', 'mercenary_slot_index', 'data'], 'defaults': [], 'name': 'SetDispatchMercenary'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseItemUseAskPopup'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'need_yang'], 'defaults': [], 'name': '__MercenaryEmpoly'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryExpandSlotItemUse'},
                     {'args': ['self', 'tab_key'], 'defaults': [], 'name': '__SelectTab'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_Mercenary__tab_img__tab_btn__tab_wnd__current_tab__is_loaded__question_item_use_popup', 'type': 'member_descriptor', 'value': <member '_Mercenary__tab_img__tab_btn__tab_wnd__current_tab__is_loaded__question_item_use_popup' of 'Mercenary' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'Mercenary'},
                    {'name': '__slots__', 'type': 'str', 'value': '__tab_img__tab_btn__tab_wnd__current_tab__is_loaded__question_item_use_popup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryDelayCure'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryDrainResult'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryFire'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryImmediatelyCure'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInItemMainDrainSlot'},
                     {'args': ['self', 'sub_slot_index'], 'defaults': [], 'name': 'OverInItemSubDrainSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInMercenaryListslot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutslot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMercenaryInjuryEndTime'},
                     {'args': ['self', 'is_clear_levelup_info'], 'defaults': [True], 'name': 'RefreshMercenaryWindow'},
                     {'args': ['self', 'selected_slot_pos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'selected_slot_pos'], 'defaults': [], 'name': 'SetUnselectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetUnselectMainDrainSlot'},
                     {'args': ['self', 'sub_slot_index'], 'defaults': [], 'name': 'SetUnselectSubDrainSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckInjuryEndTime'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearDrainSubMercenarySlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearLevelUpInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearMercenaryInfoText'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDelayCureAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDrainNextLevelExpRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDrainStart'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDrainStartAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDrainSubRegist'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryFireAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryImmediatelyCureAsk'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__MercenaryInfoRefresh'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__MercenaryListArrowClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryRegistDrain'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshCureFireBtn'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshDrainSubMercenarySlot'},
                     {'args': ['self', 'selected_slot_pos'], 'defaults': [], 'name': '__SetSlotSecondCoverImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'MERCENARY_DRAIN_WARNING_LEVEL', 'type': 'int', 'value': 20},
                    {'name': 'MERCENARY_LIST_MAX_VIEW_SLOT', 'type': 'int', 'value': 24},
                    {'name': 'MERCENARY_LIST_SPECIFICITY_SLOT_START_INDEX', 'type': 'int', 'value': 24},
                    {'name': 'MERCENARY_LIST_STATE_SLOT_START_INDEX', 'type': 'int', 'value': 48},
                    {'name': '_MercenaryManage__manage_current_page_index__select_slot__main_drain_slot__sub_drain_slot_dict__sub_drain_slot_real_dict__mercenary_list_slot__drain_main_icon_slot__sub_mercenary_slot__mercenary_list_left_arrow__mercenary_list_right_arrow__mercenary_fire_btn__mercenary_immediately_cure_btn__mercenary_delay_cure_btn__mercenary_regist_drain_btn__drain_start_btn__mercenary_info_name_txt__mercenary_info_level_txt__mercenary_info_exp_txt__mercenary_info_skill_txt__mercenary_info_skill_effect_1_txt__mercenary_info_skill_effect_2_txt__mercenary_info_specificity_effect_1_txt__mercenary_info_specificity_effect_2_txt__mercenary_info_specificity_effect_3_txt__mercenary_next_level_edit_txt__mercenary_next_exp_edit_txt',
                     'type': 'member_descriptor',
                     'value': <member '_MercenaryManage__manage_current_page_index__select_slot__main_drain_slot__sub_drain_slot_dict__sub_drain_slot_real_dict__mercenary_list_slot__drain_main_icon_slot__sub_mercenary_slot__mercenary_list_left_arrow__mercenary_list_right_arrow__mercenary_fire_btn__mercenary_immediately_cure_btn__mercenary_delay_cure_btn__mercenary_regist_drain_btn__drain_start_btn__mercenary_info_name_txt__mercenary_info_level_txt__mercenary_info_exp_txt__mercenary_info_skill_txt__mercenary_info_skill_effect_1_txt__mercenary_info_skill_effect_2_txt__mercenary_info_specificity_effect_1_txt__mercenary_info_specificity_effect_2_txt__mercenary_info_specificity_effect_3_txt__mercenary_next_level_edit_txt__mercenary_next_exp_edit_txt' of 'MercenaryManage' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryManage'},
                    {'name': '__slots__',
                     'type': 'str',
                     'value': '__manage_current_page_index__select_slot__main_drain_slot__sub_drain_slot_dict__sub_drain_slot_real_dict__mercenary_list_slot__drain_main_icon_slot__sub_mercenary_slot__mercenary_list_left_arrow__mercenary_list_right_arrow__mercenary_fire_btn__mercenary_immediately_cure_btn__mercenary_delay_cure_btn__mercenary_regist_drain_btn__drain_start_btn__mercenary_info_name_txt__mercenary_info_level_txt__mercenary_info_exp_txt__mercenary_info_skill_txt__mercenary_info_skill_effect_1_txt__mercenary_info_skill_effect_2_txt__mercenary_info_specificity_effect_1_txt__mercenary_info_specificity_effect_2_txt__mercenary_info_specificity_effect_3_txt__mercenary_next_level_edit_txt__mercenary_next_exp_edit_txt'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'GetLevelLimit'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetMissionState'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetNeedActive'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetSlotIndex'},
                                {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'slot_index', 'level_limit', 'need_active', 'state'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryMission.SelectMissionData'},
                               {'name': '__slots__', 'type': 'str', 'value': '__slot_index__level_limit__need_active__mission_state'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'ClearData'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetLimitLevelText'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetNeedActiveText'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetSuccessPctText'},
                                {'args': ['self', 'text', 'type'], 'defaults': [], 'name': 'SetTypeText'},
                                {'args': ['self', 'event_type'], 'defaults': [], 'name': 'SuggestionImgEvent'},
                                {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                                {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                                {'args': ['self', 'parent'], 'defaults': [], 'name': '__LoadObject'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryMission.MissionInfo'},
                               {'name': '__slots__', 'type': 'str', 'value': '__mission_type_text__mission_limit_level_text__mission_need_active_text__mission_success_pct_text__mission_suggestion_img__mission_suggestion_tooltip__selected_mission_type'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'ClearData'},
                                {'args': ['self'], 'defaults': [], 'name': 'DefaultListImg'},
                                {'args': ['self'], 'defaults': [], 'name': 'DownListImg'},
                                {'args': ['self'], 'defaults': [], 'name': 'IsLock'},
                                {'args': ['self'], 'defaults': [], 'name': 'LockListImg'},
                                {'args': ['self', 'mission_index'], 'defaults': [], 'name': 'OverInListImg'},
                                {'args': ['self'], 'defaults': [], 'name': 'OverInListStateImg'},
                                {'args': ['self'], 'defaults': [], 'name': 'OverOutListImg'},
                                {'args': ['self'], 'defaults': [], 'name': 'OverOutListStateImg'},
                                {'args': ['self', 'fun', 'name', 'arg'], 'defaults': [], 'name': 'SetListImgEvent'},
                                {'args': ['self', 'fun', 'name', 'arg'], 'defaults': [], 'name': 'SetListStateImgEvent'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetMapText'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetNameText'},
                                {'args': ['self', 'text'], 'defaults': [], 'name': 'SetRunTimeText'},
                                {'args': ['self', 'state'], 'defaults': [], 'name': 'SetStateImg'},
                                {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                                {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                                {'args': ['self', 'parent', 'index'], 'defaults': [], 'name': '__LoadObject'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent', 'index'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': 'MERCENARY_MISSION_SHOW_MAX_COUNT', 'type': 'int', 'value': 4},
                               {'name': 'MISSION_GAIN_CONQUEROR_LEVEL_MUL', 'type': 'int', 'value': 5},
                               {'name': 'MISSION_INCREASE_FIRST_NEXT_LEVEL', 'type': 'int', 'value': 2},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryMission.MissionData'},
                               {'name': '__slots__', 'type': 'str', 'value': '__mission_map_text__mission_name_text__mission_state_img__mission_list_img__mission_run_time_text__is_lock_slot__tool_tip__state'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'ClearDispatchMercenaryBenefitText'},
                                {'args': ['self', 'success_pct', 'decrease_runtime', 'decrease_injure', 'exp_bonus', 'bonus_reward'], 'defaults': [], 'name': 'SetDisPatchBenefitText'},
                                {'args': ['self', 'parent'], 'defaults': [], 'name': '__LoadObject'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'},
                                {'args': ['self'], 'defaults': [], 'name': '__initialize'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryMission.MissionDispatchBenefit'},
                               {'name': '__slots__', 'type': 'str', 'value': '__mission_success_pct_edit_txt__mission_decreas_runtime_edit_txt__mission_decreas_injure_edit_txt__mission_exp_bonus_edit_txt__mission_bonus_reward_edit_txt'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'mission_vid', 'map_number'], 'defaults': [], 'name': 'MercenaryDispatchSuccess'},
                     {'args': ['self', 'mission_vid', 'map_number'], 'defaults': [], 'name': 'MercenaryGiveUpSuccess'},
                     {'args': ['self'], 'defaults': [], 'name': 'MercenaryMissionAllRefresh'},
                     {'args': ['self', 'mission_vid', 'mission_name', 'injure_count'], 'defaults': [], 'name': 'MercenaryResultFail'},
                     {'args': ['self', 'mission_vid', 'data'], 'defaults': [], 'name': 'MercenaryResultSuccess'},
                     {'args': ['self', 'event_type', 'index'], 'defaults': [], 'name': 'MissionListImgEvent'},
                     {'args': ['self', 'event_type', 'index'], 'defaults': [], 'name': 'MissionListStateImgEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInDisPatchSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInMissionMercenarySlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutMissionMercenarySlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshActiveText'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMercenaryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMission'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMissionRunTime'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'SelectMissionMercenarySlot'},
                     {'args': ['self', 'mercenary_slot_index', 'data'], 'defaults': [], 'name': 'SetDispatchMercenary'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'select_slot_index'], 'defaults': [], 'name': 'SetUnselectDisPatchSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'SetUnselectMissionMercenarySlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__AllCancleDispatchMercenary'},
                     {'args': ['self'], 'defaults': [], 'name': '__AutoDispatch'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearMercenaryInfoText'},
                     {'args': ['self'], 'defaults': [], 'name': '__GetScrollPos'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDispatch'},
                     {'args': ['self', 'check_item'], 'defaults': [], 'name': '__MercenaryDispatchAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDispatchUsingItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryDispatchUsingItemClose'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__MercenaryListArrowClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryMissionGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryMissionGiveUpAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryMissionResultRequest'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryMissionResultRequestAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryMissionResultRequestDontUsingItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__MercenaryMissionResultRequestUsingItem'},
                     {'args': ['self', 'event_type'], 'defaults': [], 'name': '__MercenaryPossibleCountImgEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__MissionJoin'},
                     {'args': ['self'], 'defaults': [], 'name': '__MissionRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__MissionRefreshAsk'},
                     {'args': ['self'], 'defaults': [], 'name': '__MissionRewardWindowOpen'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshAndShowMissionRewardWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshDispatchCountText'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshDispatchMercenaryBenefitText'},
                     {'args': ['self', 'check_except'], 'defaults': [True], 'name': '__RefreshDispatchSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__RefreshMercenaryInfoText'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshMercenaryList'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__RefreshMissionInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshMissionInfoNeedActiveSuccessPct'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshMissionList'},
                     {'args': ['self', 'state', 'data'], 'defaults': [None], 'name': '__RefreshMissionState'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshResultMissionProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScrollEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__SelectFirstMission'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetDisPatchEmptyAllSlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__SetDisPatchEmptySlot'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__SetMercenaryListSlotSecondCoverImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMissionListImgDeafult'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'MERCENARY_DISPATCH_MAX_SLOT', 'type': 'int', 'value': 6},
                    {'name': 'MERCENARY_DISPATCH_STATE_START_SLOT', 'type': 'int', 'value': 12},
                    {'name': 'MERCENARY_LIST_MAX_VIEW_SLOT', 'type': 'int', 'value': 8},
                    {'name': 'MERCENARY_LIST_SPECIFICITY_SLOT_START_INDEX', 'type': 'int', 'value': 8},
                    {'name': 'MERCENARY_LIST_STATE_SLOT_START_INDEX', 'type': 'int', 'value': 16},
                    {'name': 'MERCENARY_MISSION_MAX_COUNT', 'type': 'int', 'value': 10},
                    {'name': 'MERCENARY_MISSION_SHOW_MAX_COUNT', 'type': 'int', 'value': 4},
                    {'name': '_MercenaryMission__mission_list_data__mission_refresh_btn__mission_active_txt__mission_list_scrollbar__mercenary_mission_list_slot__mercenary_list_current_page__mercenary_list_left_btn__mercenary_list_right_btn__mission_join_btn__mission_auto_join_btn__mercenary_possible_count_txt__mercenary_possible_count_img__mercenary_info_name_text__mercenary_info_exp_text__mercenary_info_skill_text__mercenary_info_specificity_text__mission_info_data__reward_list_btn__mission_reward_list_window__current_reward_list_mission_index__mercenary_dispatch_slot__all_cancle_btn__mission_dispatch_benefit__current_state_text_1__current_state_text_2__mission_control_btn__dispatch_mercenary_dict__dispatch_mercenary_real_dict__mission_result_window__select_mission_info',
                     'type': 'member_descriptor',
                     'value': <member '_MercenaryMission__mission_list_data__mission_refresh_btn__mission_active_txt__mission_list_scrollbar__mercenary_mission_list_slot__mercenary_list_current_page__mercenary_list_left_btn__mercenary_list_right_btn__mission_join_btn__mission_auto_join_btn__mercenary_possible_count_txt__mercenary_possible_count_img__mercenary_info_name_text__mercenary_info_exp_text__mercenary_info_skill_text__mercenary_info_specificity_text__mission_info_data__reward_list_btn__mission_reward_list_window__current_reward_list_mission_index__mercenary_dispatch_slot__all_cancle_btn__mission_dispatch_benefit__current_state_text_1__current_state_text_2__mission_control_btn__dispatch_mercenary_dict__dispatch_mercenary_real_dict__mission_result_window__select_mission_info' of 'MercenaryMission' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMercenary'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MercenaryMission'},
                    {'name': '__slots__',
                     'type': 'str',
                     'value': '__mission_list_data__mission_refresh_btn__mission_active_txt__mission_list_scrollbar__mercenary_mission_list_slot__mercenary_list_current_page__mercenary_list_left_btn__mercenary_list_right_btn__mission_join_btn__mission_auto_join_btn__mercenary_possible_count_txt__mercenary_possible_count_img__mercenary_info_name_text__mercenary_info_exp_text__mercenary_info_skill_text__mercenary_info_specificity_text__mission_info_data__reward_list_btn__mission_reward_list_window__current_reward_list_mission_index__mercenary_dispatch_slot__all_cancle_btn__mission_dispatch_benefit__current_state_text_1__current_state_text_2__mission_control_btn__dispatch_mercenary_dict__dispatch_mercenary_real_dict__mission_result_window__select_mission_info'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'mercenary', 'uiToolTip', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'copy', 'exception', 'item', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiMercenary'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
