{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CanRemove'}, {'args': ['self'], 'defaults': [], 'name': 'OnRemove'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerBlockFriendItem'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CanRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanWarp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnWarp'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerGuildItem'}]},
           {'class': [],
            'func': [{'args': ['self', 'key', 'name'], 'defaults': [], 'name': 'AppendMember'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerBlockGroup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CanRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanWarp'},
                     {'args': ['self'], 'defaults': [], 'name': 'CanWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetStepWidth'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOnline'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDoubleClick'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnWarp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': 'Select'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'SetLovePoint'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetName'},
                     {'args': ['self'], 'defaults': [], 'name': 'UnSelect'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerItem'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerWindow.ResizeButton'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClearGuildMember'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearLoverInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetSelf'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAddFriend'},
                     {'args': ['self', 'name', 'lovePoint'], 'defaults': [], 'name': 'OnAddLover'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBlockFriend'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCancelAddFriend'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCancelBlockFriend'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseInputDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self', 'item'], 'defaults': [], 'name': 'OnDoubleClickItem'},
                     {'args': ['self', 'groupIndex', 'key', 'name'], 'defaults': [None], 'name': 'OnLogin'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnLoginLover'},
                     {'args': ['self', 'groupIndex', 'key', 'name'], 'defaults': [None], 'name': 'OnLogout'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnLogoutLover'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressAddFriendButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressBlockButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressGuildButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressRemoveButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressWhisperButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRefreshList'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRemove'},
                     {'args': ['self', 'groupIndex'], 'defaults': [], 'name': 'OnRemoveAllList'},
                     {'args': ['self', 'groupIndex', 'key'], 'defaults': [], 'name': 'OnRemoveList'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnResizeDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self', 'item'], 'defaults': [], 'name': 'OnSelectItem'},
                     {'args': ['self', 'lovePoint'], 'defaults': [], 'name': 'OnUpdateLovePoint'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMessenger'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetGuildButtonEvent'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetWhisperButtonEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__AddFamilyGroup'},
                     {'args': ['self'], 'defaults': [], 'name': '__AddGroup'},
                     {'args': ['self', 'groupIndex', 'key', 'name'], 'defaults': [], 'name': '__AddList'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LocateMember'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'START_POSITION', 'type': 'int', 'value': 40}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'key', 'name'], 'defaults': [], 'name': 'AppendMember'}, {'args': ['self'], 'defaults': [], 'name': 'GetLover'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerFamilyGroup'}]},
           {'class': [],
            'func': [{'args': ['self', 'key', 'name'], 'defaults': [], 'name': 'AppendMember'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerGuildGroup'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CanWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetStepWidth'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOnline'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'IsSameKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Offline'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': 'Online'},
                     {'args': ['self'], 'defaults': [], 'name': 'Select'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'SetKey'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'IMAGE_FILE_NAME', 'type': 'dict', 'value': {'OFFLINE': 'd:/ymir work/ui/game/windows/messenger_list_offline.sub', 'ONLINE': 'd:/ymir work/ui/game/windows/messenger_list_online.sub'}},
                    {'name': 'STATE_OFFLINE', 'type': 'int', 'value': 0},
                    {'name': 'STATE_ONLINE', 'type': 'int', 'value': 1},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MessengerMemberItem'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CanRemove'}, {'args': ['self'], 'defaults': [], 'name': 'OnRemove'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerFriendItem'}]},
           {'class': [],
            'func': [{'args': ['self', 'member', 'key', 'name'], 'defaults': [], 'name': 'AppendMember'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClearMember'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'FindMember'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLoginMemberList'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLogoutMemberList'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'item'], 'defaults': [], 'name': 'RemoveMember'},
                     {'args': ['self'], 'defaults': [], 'name': 'Select'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'IMAGE_FILE_NAME', 'type': 'dict', 'value': {'CLOSE': 'd:/ymir work/ui/game/windows/messenger_list_close.sub', 'OPEN': 'd:/ymir work/ui/game/windows/messenger_list_open.sub'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MessengerGroupItem'}]},
           {'class': [],
            'func': [{'args': ['self', 'key', 'name'], 'defaults': [], 'name': 'AppendMember'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'getParentEvent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMessenger'}, {'name': '__qualname__', 'type': 'str', 'value': 'MessengerFriendGroup'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['app', 'm2netm2g', 'constInfo', 'grp', 'uiToolTip', 'messenger', 'localeInfo', 'uiCommon', '__builtin__', 'uiGameOption', 'guild', 'ui'],
 'var': [{'name': 'BLOCK_FRIEND', 'type': 'int', 'value': 2},
         {'name': 'FRIEND', 'type': 'int', 'value': 0},
         {'name': 'GUILD', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMessenger'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
