{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'ShowRewardList'},
                     {'args': ['self', 'event_name', 'event_func', 'event_end_time', 'index'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'event_name', 'event_func', 'event_end_time', 'index'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_InGameRewardDialog__event_button', 'type': 'member_descriptor', 'value': <member '_InGameRewardDialog__event_button' of 'InGameRewardDialog' objects>},
                    {'name': '_InGameRewardDialog__event_reward_list_button__event_duration', 'type': 'member_descriptor', 'value': <member '_InGameRewardDialog__event_reward_list_button__event_duration' of 'InGameRewardDialog' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'InGameRewardDialog'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__event_button', '__event_reward_list_button__event_duration')}]},
           {'class': [],
            'func': [{'args': ['self', 'name', 'func'], 'defaults': [], 'name': 'AppendButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteAllButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'DeleteButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameDialog'}]},
           {'class': [],
            'func': [{'args': ['self', 'ingame_event_type'], 'defaults': [], 'name': 'AddInGameEvent'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BNWProcess'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BattleRoyaleProcess'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'InvenSlot'], 'defaults': [], 'name': 'CantFishEventSlot'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'CatchKingFlagProcess'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'CatchKingProcess'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'CheckRemoveEventWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMiniBossDungeon'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'ingame_event_type', 'subheader_type', 'data'], 'defaults': [None], 'name': 'InGameEventProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsLateSummerRouletteGameOpen'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'MiniGameAttendance'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameAttendanceRequestRewardList'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'MiniGameAttendanceSetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameEnd'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'MiniGameOkeyEvent'},
                     {'args': ['self', 'process_type', 'data'], 'defaults': [], 'name': 'MiniGameRumiFlagProcess'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'MiniGameRumiSetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'OtherWorldEventProcess'},
                     {'args': ['self', 'IsRefresh'], 'defaults': [], 'name': 'RefresInGameEvent'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'RouletteProcess'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOkeyNormalBG'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowInGameEvent'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'WorldBossProcess'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'YutnoriFlagProcess'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'YutnoriProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAttendanceButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickBattleRoyaleButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickCatchKingButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickFishEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickFlowerEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickGoldenLandButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickIceCreamEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMiniBossButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMiniGameBNW'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMonsterBackButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickNoWorkButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickOtherWorldButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRamadanEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRumiButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickWorldBossButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickYutnoriButton'},
                     {'args': ['self', 'except_game'], 'defaults': [15], 'name': '__CloseAll'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'hide_mini_game_dialog'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'name', 'func', 'event_end_time', 'index'], 'defaults': [], 'name': 'AppendButton'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickCalendarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseEventRewardList'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteAllButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshDialog'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'RefreshRewardList'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadRewardListWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': '__MoveRewardList'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollEventList'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshEventRewardDict'},
                     {'args': ['self', 'index', 'rewarddialog'], 'defaults': [], 'name': '__RefreshEventRewardListYPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'REWARD_LIST_POS_X', 'type': 'int', 'value': 330},
                    {'name': '_InGameEventDialog__cur_event_reward_list_index', 'type': 'member_descriptor', 'value': <member '_InGameEventDialog__cur_event_reward_list_index' of 'InGameEventDialog' objects>},
                    {'name': '_InGameEventDialog__event_reward_list_info', 'type': 'member_descriptor', 'value': <member '_InGameEventDialog__event_reward_list_info' of 'InGameEventDialog' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'InGameEventDialog'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__cur_event_reward_list_index', '__event_reward_list_info')}]}],
 'func': [],
 'import': ['uiGoldenLand',
            'chatm2g',
            'app',
            'm2netm2g',
            'playerm2g2',
            'uiMiniGameRumi',
            'goldenLand',
            'uiOtherWorld',
            'systemSetting',
            'abc',
            'constInfo',
            'uiBattleRoyale',
            'uiMiniBossDungeon',
            'uiMiniGameFishEvent',
            'uiScriptLocale',
            'ingameEventSystem',
            'localeInfo',
            'uiCommon',
            'uiMiniGameCatchKing',
            'uiMiniGameYutnori',
            '__builtin__',
            'background',
            'wndMgr',
            'uiMiniGameAttendance',
            'uiMiniGameRoulette',
            'uiWorldBoss',
            'uiMiniGameBNW',
            'ui'],
 'var': [{'name': 'BATTLE_ROYALE', 'type': 'int', 'value': 7},
         {'name': 'FLOWER_EVENT', 'type': 'int', 'value': 10},
         {'name': 'GOLDEN_LAND', 'type': 'int', 'value': 14},
         {'name': 'ICECREAM_EVENT', 'type': 'int', 'value': 13},
         {'name': 'InGameEvent', 'type': 'ABCMeta', 'value': <class 'uiMiniGame.InGameEvent'>},
         {'name': 'MINIGAME_ATTENDANCE', 'type': 'int', 'value': 1},
         {'name': 'MINIGAME_BNW', 'type': 'int', 'value': 6},
         {'name': 'MINIGAME_CATCHKING', 'type': 'int', 'value': 5},
         {'name': 'MINIGAME_FISH', 'type': 'int', 'value': 2},
         {'name': 'MINIGAME_MONSTERBACK', 'type': 'int', 'value': 3},
         {'name': 'MINIGAME_TYPE_MAX', 'type': 'int', 'value': 15},
         {'name': 'MINIGAME_TYPE_RUMI', 'type': 'int', 'value': 0},
         {'name': 'MINIGAME_YUTNORI', 'type': 'int', 'value': 4},
         {'name': 'OTHER_WORLD', 'type': 'int', 'value': 11},
         {'name': 'RAMADAN_EVENT', 'type': 'int', 'value': 12},
         {'name': 'RUMI_ROOT', 'type': 'str', 'value': 'd:/ymir work/ui/minigame/rumi/'},
         {'name': 'WORLD_BOSS', 'type': 'int', 'value': 9},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGame'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'button_gap', 'type': 'int', 'value': 47},
         {'name': 'button_height', 'type': 'int', 'value': 60}]}
