{'class': [{'class': [],
            'func': [{'args': ['self', 'add', 'type', 'time', 'value'], 'defaults': [], 'name': 'AddMessage'},
                     {'args': ['self', 'control_window'], 'defaults': [], 'name': 'BindControlWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'ReplaceLoca'},
                     {'args': ['self', 'score', 'rank', 'end_time'], 'defaults': [], 'name': 'SetInfo'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMistsIsland'}, {'name': '__qualname__', 'type': 'str', 'value': 'MistsIsland_RankWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'control_window'], 'defaults': [], 'name': 'BindControlWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'temple', 'score'], 'defaults': [], 'name': 'SetInfo'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'ToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMistsIsland'}, {'name': '__qualname__', 'type': 'str', 'value': 'MistsIsland_ScoreWindow'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                                {'args': ['self'], 'defaults': [], 'name': 'Open'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMistsIsland'}, {'name': '__qualname__', 'type': 'str', 'value': 'MistsIsland_AtlasWindow.AtlasRenderer'}]}],
            'func': [{'args': ['self', 'control_window'], 'defaults': [], 'name': 'BindControlWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'MistsIslandExit'},
                     {'args': ['self'], 'defaults': [], 'name': 'MistsIslandRank'},
                     {'args': ['self'], 'defaults': [], 'name': 'MistsIslandScore'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'mapName'], 'defaults': [], 'name': 'SetMapName'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceptMistsIslandExit'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMistsIsland'}, {'name': '__qualname__', 'type': 'str', 'value': 'MistsIsland_AtlasWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'empire', 'plus'], 'defaults': [0], 'name': 'SetEmpire'},
                     {'args': ['self', 'plus'], 'defaults': [], 'name': 'SetToolTip'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'ToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWindow'},
                     {'args': ['self', 'parent', 'pos', 'index'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'pos', 'index'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUFF_MSG', 'type': 'tuple', 'value': ('Energia +2', 'Taxa de drop de item +10%', 'For\xe7a, Intelig\xeancia, Vitalidade e Destreza +3', 'Taxa de drop de gold +10%', 'Aumento nos atributos de trajes em +3%')},
                    {'name': 'FLAG_HEIGHT', 'type': 'int', 'value': 19},
                    {'name': 'FLAG_WIDTH', 'type': 'int', 'value': 26},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMistsIsland'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MistsIsland_Flag'}]},
           {'class': [],
            'func': [{'args': ['self', 'add', 'type', 'time', 'value'], 'defaults': [], 'name': 'AddMistsIslandMessage'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShowWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'SaveIsOpen'},
                     {'args': ['self', 'mapName'], 'defaults': [], 'name': 'SetMapName'},
                     {'args': ['self', 'temple', 'score', 'rank', 'end_time'], 'defaults': [], 'name': 'SetMistsIslandInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'WindowOnOff'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMistsIsland'}, {'name': '__qualname__', 'type': 'str', 'value': 'MistsIsland'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['miniMap', 'chatm2g', 'app', 'm2netm2g', 'uiToolTip', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'ui', 'nonplayer'],
 'var': [{'name': 'BOSS_VNUM', 'type': 'tuple', 'value': (6415, 6416, 6417, 6418, 6419)},
         {'name': 'EMPIRE_NAME', 'type': 'tuple', 'value': ('-', 'Shinsu', 'Chunjo', 'Jinno')},
         {'name': 'TEMPLE_VNUM', 'type': 'tuple', 'value': (20702, 20703, 20704, 20705, 20706)},
         {'name': 'WINDOW_RANK', 'type': 'int', 'value': 2},
         {'name': 'WINDOW_SCORE', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMistsIsland'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
