{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetTextSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetHorizontalAlignLeft'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self', 'TextColor'], 'defaults': [], 'name': 'SetTextColor'},
                     {'args': ['self', 'PosX', 'PosY'], 'defaults': [], 'name': 'SetTooltipPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniMap'}, {'name': '__qualname__', 'type': 'str', 'value': 'MapTextToolTip'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'BindPartyMatchEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GuildTextUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideMiniMap'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideMiniMapInGameEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'HidePartyMatchButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'MailBoxGMButtonOverInEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'MailBoxGMButtonOverOutEvent'},
                     {'args': ['self', 'visible'], 'defaults': [], 'name': 'MailBoxGMButtonVisible'},
                     {'args': ['self'], 'defaults': [], 'name': 'MakeGmMailButton'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MiniMapMailProcess'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'MiniMapMailRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniMapMailSystemClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenInGameEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenbattleField'},
                     {'args': ['self', 'isFlash'], 'defaults': [True], 'name': 'RefrashBattleButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshServerInfo'},
                     {'args': ['self'], 'defaults': [], 'name': 'ScaleDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'ScaleUp'},
                     {'args': ['self', 'second'], 'defaults': [], 'name': 'SetGuildDragonLairFistGuildText'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGuildDragonLiarStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGuildDragonLiarSuccess'},
                     {'args': ['self', 'duration'], 'defaults': [], 'name': 'SetImprisonmentDuration'},
                     {'args': ['self', 'mapName'], 'defaults': [], 'name': 'SetMapName'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAtlas'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowMiniMap'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowMiniMapInGameEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowPartyMatchButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleAtlasWindow'},
                     {'args': ['self', 'observerCount'], 'defaults': [], 'name': 'UpdateObserverCount'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateImprisonmentDurationText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'isShowMiniMap'}],
            'import': [],
            'var': [{'name': 'CANNOT_SEE_INFO_MAP_DICT',
                     'type': 'dict',
                     'value': {'metin2_12zi_stage': False, 'metin2_map_devilsCatacomb': False, 'metin2_map_miniboss_01': False, 'metin2_map_miniboss_02': False, 'metin2_map_monkeydungeon': False, 'metin2_map_monkeydungeon_02': False, 'metin2_map_monkeydungeon_03': False}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniMap'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MiniMap'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'HideAtlas'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                                {'args': ['self'], 'defaults': [], 'name': 'ShowAtlas'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniMap'}, {'name': '__qualname__', 'type': 'str', 'value': 'AtlasWindow.AtlasRenderer'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShowWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'SetCenterPositionAdjust'},
                     {'args': ['self', 'mapName'], 'defaults': [], 'name': 'SetMapName'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniMap'}, {'name': '__qualname__', 'type': 'str', 'value': 'AtlasWindow'}]}],
 'func': [{'args': ['type', 'rgb'], 'defaults': [], 'name': '__RegisterMiniMapColor'}],
 'import': ['miniMap', 'app', 'm2netm2g', 'playerm2g2', 'constInfo', 'grp', 'uiToolTip', 'uiBattleField', 'uiScriptLocale', 'colorInfo', 'mail', 'localeInfo', '__builtin__', 'background', 'wndMgr', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiMiniMap'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
