{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRankingBoard'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__DonateAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenDonateQuestionDlg'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'control_window'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BNW_DONATE_RANKING_SHOW_COUNT', 'type': 'int', 'value': 10},
                    {'name': '_BNWRankPage__control_window', 'type': 'member_descriptor', 'value': <member '_BNWRankPage__control_window' of 'BNWRankPage' objects>},
                    {'name': '_BNWRankPage__donate_question_dlg', 'type': 'member_descriptor', 'value': <member '_BNWRankPage__donate_question_dlg' of 'BNWRankPage' objects>},
                    {'name': '_BNWRankPage__is_loaded', 'type': 'member_descriptor', 'value': <member '_BNWRankPage__is_loaded' of 'BNWRankPage' objects>},
                    {'name': '_BNWRankPage__my_rank_text_object_tuple', 'type': 'member_descriptor', 'value': <member '_BNWRankPage__my_rank_text_object_tuple' of 'BNWRankPage' objects>},
                    {'name': '_BNWRankPage__rank_text_object_tuple', 'type': 'member_descriptor', 'value': <member '_BNWRankPage__rank_text_object_tuple' of 'BNWRankPage' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameBNW'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BNWRankPage'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__is_loaded', '__control_window', '__rank_text_object_tuple', '__my_rank_text_object_tuple', '__donate_question_dlg')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': '__CardMouseOver'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': '__CardMouseOverOut'},
                     {'args': [], 'defaults': [], 'name': '__CardMoveCo'},
                     {'args': ['self', 'index', 'is_player1_turn', 'card_number'], 'defaults': [], 'name': '__CardMoveEndHandToField'},
                     {'args': ['self', 'is_player1_turn', 'card_number'], 'defaults': [], 'name': '__CardMoveHandToField'},
                     {'args': ['self', 'is_other_player_card', 'number'], 'defaults': [], 'name': '__CardThrow'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': '__ClickCard'},
                     {'args': ['self', 'is_player1_turn', 'card_number', 'end_func'], 'defaults': [None], 'name': '__CreateMoveImg'},
                     {'args': ['self', 'frist_text', 'second_text'], 'defaults': [], 'name': '__CreateMoveText'},
                     {'args': ['self'], 'defaults': [], 'name': '__CurCardHide'},
                     {'args': ['self', 'is_even_number'], 'defaults': [], 'name': '__GetPlayer2RandomNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveupAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'move_text_list_index', 'object_tuple_index', 'text_pos', 'text'], 'defaults': [], 'name': '__MoveTextEnd'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenGiveupQuestionDlg'},
                     {'args': ['self', 'result', 'reward_item_count', 'my_score'], 'defaults': [], 'name': '__OpenResultPopup'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': '__SetPlayer1CurCard'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': '__SetPlayer2CurCard'},
                     {'args': ['self', 'is_player1', 'score'], 'defaults': [], 'name': '__SetScore'},
                     {'args': ['self', 'result', 'player1_score', 'player2_score'], 'defaults': [], 'name': '__SetThrowCardResult'},
                     {'args': ['self', 'is_player1_turn'], 'defaults': [], 'name': '__SetTurn'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateCurCardFlash'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'control_window'], 'defaults': [], 'name': '__init__'},
                     {'args': ['original_func'], 'defaults': [], 'name': 'coroutine_wrapper'}],
            'import': [],
            'var': [{'name': 'BNW_ALARM_TEXT_GROUP_COUNT', 'type': 'int', 'value': 2},
                    {'name': 'BNW_CARD_EVEN_NUMBER_COUNT', 'type': 'int', 'value': 5},
                    {'name': 'BNW_CARD_NUMBER_COUNT_MAX', 'type': 'int', 'value': 9},
                    {'name': 'BNW_CARD_ODD_NUMBER_COUNT', 'type': 'int', 'value': 4},
                    {'name': 'BNW_PLAYER_MAX', 'type': 'int', 'value': 2},
                    {'name': 'CARD_MOVE_SPEED', 'type': 'float', 'value': 20.0},
                    {'name': 'EVENT_TYPE_CARD_FLASH_END', 'type': 'int', 'value': 10},
                    {'name': 'EVENT_TYPE_CARD_FLASH_PROCESS', 'type': 'int', 'value': 9},
                    {'name': 'EVENT_TYPE_CARD_RESULT', 'type': 'int', 'value': 5},
                    {'name': 'EVENT_TYPE_CARD_THROW', 'type': 'int', 'value': 4},
                    {'name': 'EVENT_TYPE_CUR_CARD_FLASH', 'type': 'int', 'value': 11},
                    {'name': 'EVENT_TYPE_CUR_CARD_HIDE', 'type': 'int', 'value': 6},
                    {'name': 'EVENT_TYPE_DELAY', 'type': 'int', 'value': 2},
                    {'name': 'EVENT_TYPE_END_PROCESS', 'type': 'int', 'value': 7},
                    {'name': 'EVENT_TYPE_INSERT_DELAY', 'type': 'int', 'value': 1},
                    {'name': 'EVENT_TYPE_SET_CARD_CLICK_LOCK', 'type': 'int', 'value': 8},
                    {'name': 'EVENT_TYPE_SET_TURN', 'type': 'int', 'value': 3},
                    {'name': 'TEXT_MOVE_SPEED', 'type': 'float', 'value': 3.0},
                    {'name': '_BNWGamePage__alarm_text_list', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__alarm_text_list' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__alarm_text_object_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__alarm_text_object_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__card_move_co', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__card_move_co' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__control_window', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__control_window' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__end_game', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__end_game' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__event_deque', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__event_deque' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__giveup_question_dlg', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__giveup_question_dlg' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__is_card_click_lock', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__is_card_click_lock' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__is_hand_card_flash', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__is_hand_card_flash' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__is_loaded', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__is_loaded' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__is_player1_turn', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__is_player1_turn' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__move_card_layer_window', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__move_card_layer_window' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__move_img_list', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__move_img_list' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__move_text_list', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__move_text_list' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player1_card_cross_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player1_card_cross_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player1_card_number_list', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player1_card_number_list' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player1_card_over_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player1_card_over_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player1_card_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player1_card_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player2_card_cross_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player2_card_cross_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player2_card_over_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player2_card_over_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player2_card_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player2_card_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player2_even_number_card_list', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player2_even_number_card_list' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player2_odd_number_card_list', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player2_odd_number_card_list' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player_cur_card_flash_data', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player_cur_card_flash_data' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player_cur_card_flash_time', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player_cur_card_flash_time' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player_cur_card_object_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player_cur_card_object_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player_cur_card_over_img_tuple', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player_cur_card_over_img_tuple' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__player_score_object_tupel', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__player_score_object_tupel' of 'BNWGamePage' objects>},
                    {'name': '_BNWGamePage__result_popup', 'type': 'member_descriptor', 'value': <member '_BNWGamePage__result_popup' of 'BNWGamePage' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameBNW'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BNWGamePage'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__is_loaded',
                               '__control_window',
                               '__player_score_object_tupel',
                               '__player_cur_card_object_tuple',
                               '__player_cur_card_over_img_tuple',
                               '__player_cur_card_flash_data',
                               '__player_cur_card_flash_time',
                               '__alarm_text_object_tuple',
                               '__alarm_text_list',
                               '__player1_card_tuple',
                               '__player1_card_over_tuple',
                               '__player1_card_cross_tuple',
                               '__player1_card_number_list',
                               '__player2_card_tuple',
                               '__player2_card_over_tuple',
                               '__player2_card_cross_tuple',
                               '__player2_even_number_card_list',
                               '__player2_odd_number_card_list',
                               '__is_player1_turn',
                               '__result_popup',
                               '__giveup_question_dlg',
                               '__end_game',
                               '__event_deque',
                               '__is_card_click_lock',
                               '__move_img_list',
                               '__card_move_co',
                               '__move_card_layer_window',
                               '__move_text_list',
                               '__is_hand_card_flash')}]},
           {'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_DescriptionBox__desc_index', 'type': 'member_descriptor', 'value': <member '_DescriptionBox__desc_index' of 'DescriptionBox' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameBNW'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'BNWWaitingPage.DescriptionBox'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__desc_index',)}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickGameStartButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRankButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRewardTradeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'control_window'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_BNWWaitingPage__VISIBLE_LINE_COUNT', 'type': 'int', 'value': 15},
                    {'name': '_BNWWaitingPage__control_window', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__control_window' of 'BNWWaitingPage' objects>},
                    {'name': '_BNWWaitingPage__desc_board', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__desc_board' of 'BNWWaitingPage' objects>},
                    {'name': '_BNWWaitingPage__desc_index', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__desc_index' of 'BNWWaitingPage' objects>},
                    {'name': '_BNWWaitingPage__desc_y', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__desc_y' of 'BNWWaitingPage' objects>},
                    {'name': '_BNWWaitingPage__description_box', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__description_box' of 'BNWWaitingPage' objects>},
                    {'name': '_BNWWaitingPage__is_loaded', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__is_loaded' of 'BNWWaitingPage' objects>},
                    {'name': '_BNWWaitingPage__start_question_dialog', 'type': 'member_descriptor', 'value': <member '_BNWWaitingPage__start_question_dialog' of 'BNWWaitingPage' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameBNW'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BNWWaitingPage'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__is_loaded', '__control_window', '__desc_board', '__description_box', '__desc_index', '__desc_y', '__start_question_dialog')}]},
           {'class': [],
            'func': [{'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BNWProcess'},
                     {'args': ['self', 'state'], 'defaults': [], 'name': 'ChangeState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_MiniGameBNW__cur_page', 'type': 'member_descriptor', 'value': <member '_MiniGameBNW__cur_page' of 'MiniGameBNW' objects>},
                    {'name': '_MiniGameBNW__game_page', 'type': 'member_descriptor', 'value': <member '_MiniGameBNW__game_page' of 'MiniGameBNW' objects>},
                    {'name': '_MiniGameBNW__is_loaded', 'type': 'member_descriptor', 'value': <member '_MiniGameBNW__is_loaded' of 'MiniGameBNW' objects>},
                    {'name': '_MiniGameBNW__rank_page', 'type': 'member_descriptor', 'value': <member '_MiniGameBNW__rank_page' of 'MiniGameBNW' objects>},
                    {'name': '_MiniGameBNW__state', 'type': 'member_descriptor', 'value': <member '_MiniGameBNW__state' of 'MiniGameBNW' objects>},
                    {'name': '_MiniGameBNW__waiting_page', 'type': 'member_descriptor', 'value': <member '_MiniGameBNW__waiting_page' of 'MiniGameBNW' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameBNW'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameBNW'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__is_loaded', '__state', '__cur_page', '__waiting_page', '__game_page', '__rank_page')}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}, {'args': ['wrapped', 'assigned', 'updated'], 'defaults': [('__module__', '__name__', '__doc__'), ('__dict__',)], 'name': 'wraps'}],
 'import': ['ranking', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'event', 'chr', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'ui'],
 'var': [{'name': 'DEFAULT_DESC_Y', 'type': 'int', 'value': 7},
         {'name': 'DESC_WIDTH_COUNT', 'type': 'int', 'value': 70},
         {'name': 'STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'STATE_PLAY', 'type': 'int', 'value': 2},
         {'name': 'STATE_RANK', 'type': 'int', 'value': 3},
         {'name': 'STATE_WAITING', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameBNW'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
