{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameAttendance'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameAttendance.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameAttendanceRequestRewardList'},
                     {'args': ['self', 'day'], 'defaults': [], 'name': 'MiniGameAttendanceSetDay'},
                     {'args': ['self', 'clear'], 'defaults': [], 'name': 'MiniGameAttendanceSetMissionClear'},
                     {'args': ['self', 'reward'], 'defaults': [], 'name': 'MiniGameAttendanceSetReward'},
                     {'args': ['self', 'value'], 'defaults': [], 'name': 'MiniGameAttendanceSetShowMax'},
                     {'args': ['self'], 'defaults': [], 'name': 'NumberButtonOverCheck'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': 'OpenPopupDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshAttendanceBoard'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': '__NumberFlash'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDescNextButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickDescPrevButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNextButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickNumberButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPrevButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RewardAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__RewardCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowCurPageNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameAttendance'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameAttendance'}]}],
 'func': [],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'event', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'item', 'ui'],
 'var': [{'name': 'DEFAULT_DESC_Y', 'type': 'int', 'value': 7},
         {'name': 'DEFAULT_SHOW_NUMBER_MAX', 'type': 'int', 'value': 14},
         {'name': 'NUMBER_PAGE_MAX', 'type': 'int', 'value': 2},
         {'name': 'NUMBER_RES_MAX', 'type': 'int', 'value': 14},
         {'name': 'ROOT_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/minigame/attendance/'},
         {'name': 'SHOW_LINE_COUNT_MAX', 'type': 'int', 'value': 7},
         {'name': 'SHOW_NUMBER_COUNT', 'type': 'int', 'value': 8},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameAttendance'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
