{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetCardVnum'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self', 'parent', 'pos', 'clickFunc', 'index', 'vnum'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'SetCard'},
                     {'args': ['self', 'show'], 'defaults': [True], 'name': 'SetCardSelect'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'pos', 'clickFunc', 'index', 'vnum'], 'defaults': [0], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CARD_HEIGHT', 'type': 'int', 'value': 51}, {'name': 'CARD_WIDTH', 'type': 'int', 'value': 41}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFindM'}, {'name': '__qualname__', 'type': 'str', 'value': 'FindMCard'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFindM'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameFindMDescription.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptStart'},
                     {'args': ['self', 'control_window'], 'defaults': [], 'name': 'BindControlWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickStartButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': 'OpenPopupMsg'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFindM'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameFindMDescription'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self', 'getFunc', 'upFunc', 'tooltip'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'vnum', 'money'], 'defaults': [], 'name': 'ShowUpgradeBox'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'getFunc', 'upFunc', 'tooltip'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFindM'}, {'name': '__qualname__', 'type': 'str', 'value': 'FindMUpgrade'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'AcceptHint'},
                     {'args': ['self'], 'defaults': [], 'name': 'AcceptUpgrade'},
                     {'args': ['self', 'control_window'], 'defaults': [], 'name': 'BindControlWindow'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'BindItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'CardUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckOpenCard'},
                     {'args': ['self'], 'defaults': [], 'name': 'CheckTime'},
                     {'args': ['self', 'type', 'index'], 'defaults': [], 'name': 'ClickCard'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickHintButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CountDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetReward'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': 'OpenPopupMsg'},
                     {'args': ['self'], 'defaults': [], 'name': 'PlayTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshHintCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetCardImage'},
                     {'args': ['self', 'rating'], 'defaults': [], 'name': 'SetComplete'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGiveUp'},
                     {'args': ['self', 'time'], 'defaults': [], 'name': 'SetStartTime'},
                     {'args': ['self', 'list'], 'defaults': [], 'name': 'SetUpgrade'},
                     {'args': ['self', 'list'], 'defaults': [], 'name': 'SetVnumIndex'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': 'ShowToolTipMsg'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowUpgrade'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpgradeReward'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'UseHint'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'toolTipProgress'}],
            'import': [],
            'var': [{'name': 'CARD_CLOSE', 'type': 'float', 'value': 0.3},
                    {'name': 'CARD_CLOSE2', 'type': 'float', 'value': 0.5},
                    {'name': 'COUNT_DOWN', 'type': 'int', 'value': 10},
                    {'name': 'HINT_CLOSE', 'type': 'int', 'value': 0},
                    {'name': 'HINT_OPEN', 'type': 'int', 'value': 2},
                    {'name': 'HINT_WAIT', 'type': 'int', 'value': 1},
                    {'name': 'NEXT_CARD_OPEN', 'type': 'float', 'value': 0.05},
                    {'name': 'NEXT_CARD_OPEN2', 'type': 'float', 'value': 0.1},
                    {'name': 'STATE_COMPLETE', 'type': 'int', 'value': 3},
                    {'name': 'STATE_END', 'type': 'int', 'value': 4},
                    {'name': 'STATE_INIT', 'type': 'int', 'value': 0},
                    {'name': 'STATE_LOAD', 'type': 'int', 'value': 1},
                    {'name': 'STATE_SET_CARD', 'type': 'int', 'value': 2},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFindM'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameFindMMainUI'}]},
           {'class': [],
            'func': [{'args': ['self', 'tooltip'], 'defaults': [], 'name': 'BindItemToolTip'},
                     {'args': ['self', 'state'], 'defaults': [], 'name': 'ChangeState'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'FindMProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsPlaying'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'ResultCheckCard'},
                     {'args': ['self', 'rating'], 'defaults': [], 'name': 'SetComplete'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetStartTime'},
                     {'args': ['self', 'list'], 'defaults': [], 'name': 'SetUpgrade'},
                     {'args': ['self', 'list'], 'defaults': [], 'name': 'SetVnumIndex'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': 'UseHint'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'STATE_DESC', 'type': 'int', 'value': 1},
                    {'name': 'STATE_MAIN', 'type': 'int', 'value': 2},
                    {'name': 'STATE_NONE', 'type': 'int', 'value': 0},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFindM'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameFindM'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'event', 'uiToolTip', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'item', 'ui'],
 'var': [{'name': 'PIECE_ITEM', 'type': 'int', 'value': 79510},
         {'name': 'PIECE_SET_ITEM', 'type': 'int', 'value': 79511},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameFindM'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
