{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'eventname', 'eventfunc', 'eventendtime', 'RewardItem1', 'ItemCnt1', 'RewardItem2', 'ItemCnt2', 'RewardItem3', 'ItemCnt3'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SlotOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__SlotOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'eventname', 'eventfunc', 'eventendtime', 'RewardItem1', 'ItemCnt1', 'RewardItem2', 'ItemCnt2', 'RewardItem3', 'ItemCnt3'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'InGameRewardDialog'}]},
           {'class': [],
            'func': [{'args': ['self', 'name', 'func'], 'defaults': [], 'name': 'AppendButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteAllButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'DeleteButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameDialog'}]},
           {'class': [],
            'func': [{'args': ['self', 'name', 'func', 'ExpiredTime', 'RewardItem1', 'ItemCnt1', 'RewardItem2', 'ItemCnt2', 'RewardItem3', 'ItemCnt3', 'index'], 'defaults': [], 'name': 'AppendButton'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickCalendarButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteAllButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshDialog'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScrollEventList'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshEventRewardDict'},
                     {'args': ['self', 'index', 'rewarddialog'], 'defaults': [], 'name': '__RefreshEventRewardListYPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'InGameEventDialog'}]},
           {'class': [],
            'func': [{'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'BNWProcess'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'InvenSlot'], 'defaults': [], 'name': 'CantFishEventSlot'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'CatchKingProcess'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'CheckRemoveEventWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'FindMBindItemToolTip'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'FindMProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMiniBossDungeon'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'MiniGameAttendance'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameAttendanceRequestRewardList'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'MiniGameAttendanceSetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameEnd'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'MiniGameOkeyEvent'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'MiniGameRumiSetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self', 'IsRefresh'], 'defaults': [], 'name': 'RefresInGameEvent'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'RouletteProcess'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOkeyNormalBG'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowInGameEvent'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'YutnoriProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAttendanceButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickCatchKingButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickFishEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMiniBossButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMiniGameBNW'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMiniGameFindMButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMonsterBackButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickNoWorkButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRumiButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickYutnoriButton'},
                     {'args': ['self', 'except_game'], 'defaults': [8], 'name': '__CloseAll'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'hide_mini_game_dialog'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameWindow'}]}],
 'func': [],
 'import': ['uiMiniGameFindM',
            'chatm2g',
            'app',
            'm2netm2g',
            'playerm2g2',
            'uiMiniGameRumi',
            'constInfo',
            'systemSetting',
            'uiMiniBossDungeon',
            'uiMiniGameFishEvent',
            'uiScriptLocale',
            'localeInfo',
            'uiMiniGameCatchKing',
            'uiMiniGameYutnori',
            '__builtin__',
            'background',
            'wndMgr',
            'uiMiniGameAttendance',
            'uiMiniGameRoulette',
            'uiMiniGameBNW',
            'ui'],
 'var': [{'name': 'MINIGAME_ATTENDANCE', 'type': 'int', 'value': 1},
         {'name': 'MINIGAME_BNW', 'type': 'int', 'value': 7},
         {'name': 'MINIGAME_CATCHKING', 'type': 'int', 'value': 5},
         {'name': 'MINIGAME_FINDM', 'type': 'int', 'value': 6},
         {'name': 'MINIGAME_FISH', 'type': 'int', 'value': 2},
         {'name': 'MINIGAME_MONSTERBACK', 'type': 'int', 'value': 3},
         {'name': 'MINIGAME_TYPE_MAX', 'type': 'int', 'value': 8},
         {'name': 'MINIGAME_TYPE_RUMI', 'type': 'int', 'value': 0},
         {'name': 'MINIGAME_YUTNORI', 'type': 'int', 'value': 4},
         {'name': 'RUMI_ROOT', 'type': 'str', 'value': 'd:/ymir work/ui/minigame/rumi/'},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGame'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'button_gap', 'type': 'int', 'value': 47},
         {'name': 'button_height', 'type': 'int', 'value': 60}]}
