{'class': [{'class': [],
            'func': [{'args': ['self', 'name', 'func'], 'defaults': [], 'name': 'AppendButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeleteAllButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'DeleteButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameDialog'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'InvenSlot'], 'defaults': [], 'name': 'CantFishEventSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'IntegrationMiniGame'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'MiniGameAttendance'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameAttendanceRequestRewardList'},
                     {'args': ['self', 'type', 'value'], 'defaults': [], 'name': 'MiniGameAttendanceSetData'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameEnd'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'MiniGameOkeyEvent'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'MiniGameRumiSetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'MiniGameStart'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOkeyNormalBG'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAttendanceButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickFishEventButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickIntegrationEventBannerButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMonsterBackButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRumiButton'},
                     {'args': ['self', 'except_game'], 'defaults': [4], 'name': '__CloseAll'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'hide_mini_game_dialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'show_mini_game_dialog'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGame'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameWindow'}]}],
 'func': [],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'uiMiniGameRumi', 'constInfo', 'uiMiniGameFishEvent', 'uiScriptLocale', 'localeInfo', '__builtin__', 'wndMgr', 'uiMiniGameAttendance', 'ui'],
 'var': [{'name': 'MINIGAME_ATTENDANCE', 'type': 'int', 'value': 1},
         {'name': 'MINIGAME_FISH', 'type': 'int', 'value': 2},
         {'name': 'MINIGAME_MONSTERBACK', 'type': 'int', 'value': 3},
         {'name': 'MINIGAME_TYPE_MAX', 'type': 'int', 'value': 4},
         {'name': 'MINIGAME_TYPE_RUMI', 'type': 'int', 'value': 0},
         {'name': 'RUMI_ROOT', 'type': 'str', 'value': 'd:/ymir work/ui/minigame/rumi/'},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGame'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'button_gap', 'type': 'int', 'value': 10},
         {'name': 'button_height', 'type': 'int', 'value': 25}]}
