{'class': [{'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameRumi'}, {'name': '__qualname__', 'type': 'str', 'value': 'RumiWaitingPage.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseStartDlg'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetConfirmWindowCheck'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickConfirmCheckButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickStartButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnDownScrollButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnUpScrollButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameRumi'}, {'name': '__qualname__', 'type': 'str', 'value': 'RumiWaitingPage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CardMoveEndEvnet'},
                     {'args': ['self'], 'defaults': [], 'name': 'CardMoveStartEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'Clear'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LButtonClickDeck'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'LButtonClickField'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'LButtonClickHand'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'MoveCardDeckToHand'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'MoveCardFieldToHand'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'MoveCardHandToField'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'MoveCardHandToGrave'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'RButtonClickHand'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self', 'bFlag'], 'defaults': [], 'name': 'SetConfirmWindowCheck'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'SetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOkeyNormalBG'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceptDiscard'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceptExit'},
                     {'args': ['self'], 'defaults': [], 'name': '__CancelDiscard'},
                     {'args': ['self'], 'defaults': [], 'name': '__CancelExit'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearDeckCardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearDeckFlushEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearFieldCardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearHandCardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearScoreCompletionEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseDiscardConfirmDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseExitQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__DeckFlushEffectCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__DeleteCardImg'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__DiscardConfirmDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__ExitButtonClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllDeckSlotBaseImage'},
                     {'args': ['self', 'card_pos', 'slot_index', 'color', 'number'], 'defaults': [], 'name': '__IsExistSlotIndex'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadCardImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreEffectEndFrameEvent1'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreEffectEndFrameEvent2'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreEffectEndFrameEvent3'},
                     {'args': ['self', 'cur_frame'], 'defaults': [], 'name': '__ScoreEffectKeyFrameEvent1'},
                     {'args': ['self', 'cur_frame'], 'defaults': [], 'name': '__ScoreEffectKeyFrameEvent2'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreTextEffectEndFrameEvent'},
                     {'args': ['self', 'deck_cnt'], 'defaults': [], 'name': '__SetDeckImg'},
                     {'args': ['self', 'score'], 'defaults': [], 'name': '__SetScore'},
                     {'args': ['self', 'total_score'], 'defaults': [], 'name': '__SetTotalScore'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ShowDeckSlotBaseImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartDeckFlushEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameRumi'}, {'name': '__qualname__', 'type': 'str', 'value': 'RumiGamePage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GameEnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'GameStart'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'score', 'total_score'], 'defaults': [], 'name': 'RumiIncreaseScore'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': 'RumiMoveCard'},
                     {'args': ['self', 'deck_card_count'], 'defaults': [], 'name': 'SetDeckCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOkeyNormalBG'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameRumi'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameRumi'}]}],
 'func': [{'args': ['self', 'fileName'], 'defaults': [], 'name': 'LoadScript'}],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'event', 'constInfo', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'grpImage', 'wndMgr', 'grp', 'ui'],
 'var': [{'name': 'BLUE_CARD', 'type': 'int', 'value': 20},
         {'name': 'CARD_COLOR_MAX', 'type': 'int', 'value': 3},
         {'name': 'CARD_IMG_DICT',
          'type': 'dict',
          'value': {11: 'd:/ymir work/ui/minigame/rumi/card/card_red_1.sub',
                    12: 'd:/ymir work/ui/minigame/rumi/card/card_red_2.sub',
                    13: 'd:/ymir work/ui/minigame/rumi/card/card_red_3.sub',
                    14: 'd:/ymir work/ui/minigame/rumi/card/card_red_4.sub',
                    15: 'd:/ymir work/ui/minigame/rumi/card/card_red_5.sub',
                    16: 'd:/ymir work/ui/minigame/rumi/card/card_red_6.sub',
                    17: 'd:/ymir work/ui/minigame/rumi/card/card_red_7.sub',
                    18: 'd:/ymir work/ui/minigame/rumi/card/card_red_8.sub',
                    21: 'd:/ymir work/ui/minigame/rumi/card/card_blue_1.sub',
                    22: 'd:/ymir work/ui/minigame/rumi/card/card_blue_2.sub',
                    23: 'd:/ymir work/ui/minigame/rumi/card/card_blue_3.sub',
                    24: 'd:/ymir work/ui/minigame/rumi/card/card_blue_4.sub',
                    25: 'd:/ymir work/ui/minigame/rumi/card/card_blue_5.sub',
                    26: 'd:/ymir work/ui/minigame/rumi/card/card_blue_6.sub',
                    27: 'd:/ymir work/ui/minigame/rumi/card/card_blue_7.sub',
                    28: 'd:/ymir work/ui/minigame/rumi/card/card_blue_8.sub',
                    31: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_1.sub',
                    32: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_2.sub',
                    33: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_3.sub',
                    34: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_4.sub',
                    35: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_5.sub',
                    36: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_6.sub',
                    37: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_7.sub',
                    38: 'd:/ymir work/ui/minigame/rumi/card/card_yellow_8.sub'}},
         {'name': 'CARD_IMG_HEIGHT', 'type': 'int', 'value': 52},
         {'name': 'CARD_IMG_WIDTH', 'type': 'int', 'value': 38},
         {'name': 'CARD_MOVE_SPEED', 'type': 'float', 'value': 25.0},
         {'name': 'CARD_NUMBER_END', 'type': 'int', 'value': 8},
         {'name': 'CARD_POS_MAX', 'type': 'int', 'value': 4},
         {'name': 'CARD_ROOT', 'type': 'str', 'value': 'd:/ymir work/ui/minigame/rumi/card/'},
         {'name': 'DECK_CARD', 'type': 'int', 'value': 1},
         {'name': 'DECK_CARD_INDEX_MAX', 'type': 'int', 'value': 3},
         {'name': 'DECK_COUNT_MAX', 'type': 'int', 'value': 24},
         {'name': 'DECK_FLUSH_IMG_GAP_X', 'type': 'int', 'value': 2},
         {'name': 'DECK_FLUSH_IMG_GAP_Y', 'type': 'int', 'value': 2},
         {'name': 'DECK_IMG_DICT', 'type': 'list', 'value': ['d:/ymir work/ui/minigame/rumi/deck/deck1.sub', 'd:/ymir work/ui/minigame/rumi/deck/deck2.sub', 'd:/ymir work/ui/minigame/rumi/deck/deck3.sub']},
         {'name': 'DEFAULT_DESC_Y', 'type': 'int', 'value': 7},
         {'name': 'EMPTY_CARD', 'type': 'int', 'value': 0},
         {'name': 'FIELD_CARD', 'type': 'int', 'value': 3},
         {'name': 'FIELD_CARD_INDEX_MAX', 'type': 'int', 'value': 3},
         {'name': 'HAND_CARD', 'type': 'int', 'value': 2},
         {'name': 'HAND_CARD_INDEX_MAX', 'type': 'int', 'value': 5},
         {'name': 'LOW_TOTAL_SCORE', 'type': 'int', 'value': 300},
         {'name': 'MID_TOTAL_SCORE', 'type': 'int', 'value': 400},
         {'name': 'NONE_POS', 'type': 'int', 'value': 0},
         {'name': 'RED_CARD', 'type': 'int', 'value': 10},
         {'name': 'RUMI_ROOT', 'type': 'str', 'value': 'd:/ymir work/ui/minigame/rumi/'},
         {'name': 'SHOW_LINE_COUNT_MAX', 'type': 'int', 'value': 18},
         {'name': 'STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'STATE_PLAY', 'type': 'int', 'value': 2},
         {'name': 'STATE_WAITING', 'type': 'int', 'value': 1},
         {'name': 'TOTAL_SCORE_HIGH_FONT_COLOR', 'type': 'int', 'value': -65536},
         {'name': 'TOTAL_SCORE_LOW_FONT_COLOR', 'type': 'int', 'value': -3750202},
         {'name': 'TOTAL_SCORE_MID_FONT_COLOR', 'type': 'int', 'value': -10141},
         {'name': 'YELLOW_CARD', 'type': 'int', 'value': 30},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameRumi'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
