{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFishEvent'}, {'name': '__qualname__', 'type': 'str', 'value': 'FishEventGameWaitingPage.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self', 'mini_game_fish'], 'defaults': [], 'name': 'SetMiniGameFish'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickStartButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFishEvent'}, {'name': '__qualname__', 'type': 'str', 'value': 'FishEventGameWaitingPage'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'type'], 'defaults': [3], 'name': 'ClearFishBoxSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'DeattachObject'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'DropQuestionDialog'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotIndex', 'type'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'slotIndex', 'type'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'mini_game_fish'], 'defaults': [], 'name': 'SetMiniGameFish'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetOnTopWindowNone'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddAccept'},
                     {'args': ['self', 'type', 'pos'], 'defaults': [], 'name': '__AddFishEventSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearCompletionEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickHelpButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__DropAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreEffectEndFrameEvent1'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreEffectEndFrameEvent2'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreEffectEndFrameEvent3'},
                     {'args': ['self'], 'defaults': [], 'name': '__ScoreTextEffectEndFrameEvent'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SelectEmptyGameSlot'},
                     {'args': ['self', 'slotIndex', 'type'], 'defaults': [], 'name': '__SelectEmptySlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__UnselectEmptyGameSlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__UnselectItemGameSlotEvent'},
                     {'args': ['self', 'slotIndex', 'type'], 'defaults': [], 'name': '__UnselectItemSlot'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__UseAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseAcceptCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFishEvent'}, {'name': '__qualname__', 'type': 'str', 'value': 'FishEventGamePage'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'InvenSlot'], 'defaults': [], 'name': 'CantFishEventSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishAdd'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'MiniGameFishCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'MiniGameFishReward'},
                     {'args': ['self', 'window', 'pos', 'shape'], 'defaults': [], 'name': 'MiniGameFishUse'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameFishEvent'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameFish'}]}],
 'func': [{'args': ['self', 'fileName'], 'defaults': [], 'name': 'LoadScript'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'event', 'constInfo', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'grpImage', 'wndMgr', 'grp', 'item', 'ui'],
 'var': [{'name': 'DEFAULT_DESC_Y', 'type': 'int', 'value': 7},
         {'name': 'FISH_EVENT_TYPE_MAX', 'type': 'int', 'value': 3},
         {'name': 'FISH_WAITING_PAGE_BOX_VISIBLE_LINE_COUNT', 'type': 'int', 'value': 8},
         {'name': 'ITEM_FISH_EVENT_BOX', 'type': 'int', 'value': 25106},
         {'name': 'ITEM_FISH_EVENT_BOX_SPECIAL', 'type': 'int', 'value': 25107},
         {'name': 'NORMAL_TYPE', 'type': 'int', 'value': 2},
         {'name': 'RESERVED_TYPE', 'type': 'int', 'value': 0},
         {'name': 'SPECIAL_TYPE', 'type': 'int', 'value': 1},
         {'name': 'STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'STATE_PLAY', 'type': 'int', 'value': 2},
         {'name': 'STATE_WAITING', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameFishEvent'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'fish_event_game_state', 'type': 'int', 'value': 0}]}
