{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClickSpinButton'},
                     {'args': ['self', 'is_force', 'is_send_packet'], 'defaults': [False, True], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': 'OverInSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutSlot'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'RouletteProcess'},
                     {'args': ['self', 'tooptip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'cur_time', 'pivot_time'], 'defaults': [], 'name': '__MoveNext'},
                     {'args': ['self', 'item_info'], 'defaults': [], 'name': '__Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__RangeCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__RouletteUpdate'},
                     {'args': ['self', 'cur_time'], 'defaults': [], 'name': '__RouletteUpdateAfterRequest'},
                     {'args': ['self', 'cur_time'], 'defaults': [], 'name': '__RouletteUpdateBeforeRequest'},
                     {'args': ['self', 'item_data_tuple'], 'defaults': [], 'name': '__SetItemList'},
                     {'args': ['self'], 'defaults': [], 'name': '__SlotIndexGenerator'},
                     {'args': ['self', 'result'], 'defaults': [], 'name': '__SpinEnd'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SpinFix'},
                     {'args': ['self'], 'defaults': [], 'name': '__SpinInitialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartSpin'},
                     {'args': ['self'], 'defaults': [], 'name': '__TitleUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'RESPONSE_TIME_OUT', 'type': 'int', 'value': 10000},
                    {'name': 'ROULETTE_SLOT_MAX', 'type': 'int', 'value': 20},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameRoulette'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RouletteWindow'},
                    {'name': 'beginning_spin_time_after_request', 'type': 'tuple', 'value': (60, 120)},
                    {'name': 'edge_effect_pos_tuple', 'type': 'tuple', 'value': ((25, 46), (69, 46), (113, 46), (157, 46), (201, 46), (245, 46), (245, 90), (245, 134), (245, 178), (245, 222), (245, 266), (201, 266), (157, 266), (113, 266), (69, 266), (25, 266), (25, 222), (25, 178), (25, 134), (25, 90))},
                    {'name': 'last_spin_time_after_request', 'type': 'tuple', 'value': (400, 600)},
                    {'name': 'middle_spin_time_after_request', 'type': 'tuple', 'value': ((160, 200, 240, 280, 320, 340, 350, 360, 370, 380), (160, 200, 240, 280, 320, 340, 340, 340, 340, 340))},
                    {'name': 'spin_count_before_request', 'type': 'tuple', 'value': ((20, 5), (20, 15, 5))},
                    {'name': 'spin_time_before_request', 'type': 'tuple', 'value': ((40, 60), (20, 40, 60))}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameRoulette'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
