{'class': [{'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'YutnoriProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameYutnori'}, {'name': '__qualname__', 'type': 'str', 'value': 'MiniGameYutnori'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameYutnori'}, {'name': '__qualname__', 'type': 'str', 'value': 'YutnoriWaitingPage.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseStartDlg'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickStartButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__StartCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameYutnori'}, {'name': '__qualname__', 'type': 'str', 'value': 'YutnoriWaitingPage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ArrowImgHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'ArrowImgShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'CatchPostProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'CatchPreProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'CharHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'DisableFlash'},
                     {'args': ['self'], 'defaults': [], 'name': 'FlashHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'FlashShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetAvailableIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetJoin'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetJoinMember'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLocalPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMove'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetPos'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsGoal'},
                     {'args': ['self', 'parent_x', 'parent_y'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetAvailableIndex'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetGoalMove'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetJoin'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetJoinMember'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'SetPosition'},
                     {'args': ['self', 'is_slow'], 'defaults': [], 'name': 'SetSlowMotion'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowExplosionEffect'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowGoalCoverImg'},
                     {'args': ['self', 'trace_index_list'], 'defaults': [], 'name': 'Start'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__CreateArrowImg'},
                     {'args': ['self', 'parent', 'func', 'num'], 'defaults': [], 'name': '__CreateChar'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__CreateCoverImg'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__CreateExplosionEffect'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__CreateSign'},
                     {'args': ['self'], 'defaults': [], 'name': '__ExplosionEffectEnd'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnMoveEnd'},
                     {'args': ['self', 'parent_x', 'parent_y'], 'defaults': [], 'name': '__UpdateMove'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'is_pc', 'parent', 'click_func', 'move_end_func', 'explosion_end_func', 'goal_score_func', 'num', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameYutnori'}, {'name': '__qualname__', 'type': 'str', 'value': 'Yut'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ArrowImgHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'ArrowImgShow'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'AvailableAreaShow'},
                     {'args': ['self', 'is_giveup'], 'defaults': [False], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'PushCatchYut'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'PushNextTurn'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SetProb'},
                     {'args': ['self', 'remain_count'], 'defaults': [], 'name': 'SetRemainCount'},
                     {'args': ['self', 'score'], 'defaults': [], 'name': 'SetScore'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetYut'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'ThrowResult'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'YutMove'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__CatchAniEndFrameEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__CatchCheck'},
                     {'args': ['self', 'is_pc_turn'], 'defaults': [], 'name': '__ChangeTextColor'},
                     {'args': ['self', 'is_pc'], 'defaults': [], 'name': '__ClearAvailableIndex'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearEffect'},
                     {'args': ['self', 'event_type', 'index'], 'defaults': [], 'name': '__ClickArea'},
                     {'args': ['self', 'event_type', 'index'], 'defaults': [], 'name': '__ClickChar'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ClickProbButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ClickProbButtonOver'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ClickProbButtonOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickProbSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickRewardButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickThrowButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ComWinPopup'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateArrowImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateCatchImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateChar'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateProbSelectButton'},
                     {'args': ['self', 'is_increase', 'score', 'start_x', 'start_y'], 'defaults': [], 'name': '__CreateScoreEffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateYutArea'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateYutImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__EffectEndCheck'},
                     {'args': ['self', 'unit'], 'defaults': [], 'name': '__GetMoveCount'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveupAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveupCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__GoalCoverCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__GoalEffectEndFrameEvent1'},
                     {'args': ['self'], 'defaults': [], 'name': '__GoalEffectEndFrameEvent2'},
                     {'args': ['self'], 'defaults': [], 'name': '__GoalEffectEndFrameEvent3'},
                     {'args': ['self', 'cur_frame'], 'defaults': [], 'name': '__GoalEffectKeyFrameEvent1'},
                     {'args': ['self', 'cur_frame'], 'defaults': [], 'name': '__GoalEffectKeyFrameEvent2'},
                     {'args': ['self', 'is_pc', 'is_join'], 'defaults': [], 'name': '__GoalScore'},
                     {'args': ['self'], 'defaults': [], 'name': '__GoalTextEffectEndFrameEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllUnitFlash'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideYut'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideYutArea'},
                     {'args': ['self'], 'defaults': [], 'name': '__JoinCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'is_pc', 'index', 'goal_effect'], 'defaults': [], 'name': '__MoveEnd'},
                     {'args': ['self'], 'defaults': [], 'name': '__OpenReThrowPopup'},
                     {'args': ['self'], 'defaults': [], 'name': '__PlayerWinPopup'},
                     {'args': ['self', 'open'], 'defaults': [], 'name': '__ProbSelectWindowOpen'},
                     {'args': ['self'], 'defaults': [], 'name': '__ProbTilteOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__ProbTilteOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshJoinMemberPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshScore'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ScoreEffectEndEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowGiveupDialog'},
                     {'args': ['self', 'is_pc'], 'defaults': [], 'name': '__ShowUnitFlash'},
                     {'args': ['self'], 'defaults': [], 'name': '__ThrowScoreCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__TurnCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateAlpha'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateChar'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__UpdateToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameYutnori'}, {'name': '__qualname__', 'type': 'str', 'value': 'YutnoriGamePage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ArrowImgHide'},
                     {'args': ['self'], 'defaults': [], 'name': 'ArrowImgShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGlobalPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetLocalPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetNextArea'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetPos'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetPrevArea'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetShortcutNextArea'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__CreateArrowImg'},
                     {'args': ['self', 'parent', 'func', 'index'], 'defaults': [], 'name': '__CreateSign'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'func', 'x', 'y', 'index', 'prev', 'next', 'shortcut_next'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMiniGameYutnori'}, {'name': '__qualname__', 'type': 'str', 'value': 'YutArea'}]}],
 'func': [{'args': ['self', 'fileName'], 'defaults': [], 'name': 'LoadScript'}, {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'event', 'constInfo', 'grp', 'uiToolTip', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'grpImage', 'wndMgr', 'ui'],
 'var': [{'name': 'DEFAULT_DESC_Y', 'type': 'int', 'value': 7},
         {'name': 'DESC_WIDTH_COUNT', 'type': 'int', 'value': 66},
         {'name': 'EVENT_TYPE_BUTTON_FLASH', 'type': 'int', 'value': 7},
         {'name': 'EVENT_TYPE_CALL_TURN_CHECK', 'type': 'int', 'value': 8},
         {'name': 'EVENT_TYPE_CHANGE_TEXT_COLOR', 'type': 'int', 'value': 4},
         {'name': 'EVENT_TYPE_COM_YUT_THROW', 'type': 'int', 'value': 3},
         {'name': 'EVENT_TYPE_DELAY', 'type': 'int', 'value': 2},
         {'name': 'EVENT_TYPE_INSER_DELAY', 'type': 'int', 'value': 1},
         {'name': 'EVENT_TYPE_NOTICE', 'type': 'int', 'value': 0},
         {'name': 'EVENT_TYPE_REQUEST_COM_ACTION', 'type': 'int', 'value': 6},
         {'name': 'EVENT_TYPE_SHOW_UNIT', 'type': 'int', 'value': 5},
         {'name': 'LOW_TOTAL_SCORE', 'type': 'int', 'value': 150},
         {'name': 'MID_TOTAL_SCORE', 'type': 'int', 'value': 220},
         {'name': 'REMAIN_COUNT_DEFAULT_FONT_COLOR', 'type': 'long', 'value': 4293830912L},
         {'name': 'REMAIN_COUNT_LOW_FONT_COLOR', 'type': 'int', 'value': -65536},
         {'name': 'STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'STATE_PLAY', 'type': 'int', 'value': 2},
         {'name': 'STATE_WAITING', 'type': 'int', 'value': 1},
         {'name': 'TOTAL_SCORE_HIGH_FONT_COLOR', 'type': 'long', 'value': 4294967193L},
         {'name': 'TOTAL_SCORE_LOW_FONT_COLOR', 'type': 'int', 'value': -3750202},
         {'name': 'TOTAL_SCORE_MID_FONT_COLOR', 'type': 'long', 'value': 4293830912L},
         {'name': 'VISIBLE_LINE_COUNT', 'type': 'int', 'value': 20},
         {'name': 'YUTNORI_AFTER_TURN_SELECT', 'type': 'int', 'value': 4},
         {'name': 'YUTNORI_BEFORE_TURN_SELECT', 'type': 'int', 'value': 3},
         {'name': 'YUTNORI_GOAL_AREA', 'type': 'int', 'value': 11},
         {'name': 'YUTNORI_IN_DE_CREASE_SCORE', 'type': 'int', 'value': 10},
         {'name': 'YUTNORI_STATE_END', 'type': 'int', 'value': 5},
         {'name': 'YUTNORI_STATE_MOVE', 'type': 'int', 'value': 2},
         {'name': 'YUTNORI_STATE_RE_THROW', 'type': 'int', 'value': 1},
         {'name': 'YUTNORI_STATE_THROW', 'type': 'int', 'value': 0},
         {'name': 'YUTNORI_YUTSEM1', 'type': 'int', 'value': 0},
         {'name': 'YUTNORI_YUTSEM2', 'type': 'int', 'value': 1},
         {'name': 'YUTNORI_YUTSEM3', 'type': 'int', 'value': 2},
         {'name': 'YUTNORI_YUTSEM4', 'type': 'int', 'value': 3},
         {'name': 'YUTNORI_YUTSEM5', 'type': 'int', 'value': 4},
         {'name': 'YUTNORI_YUTSEM6', 'type': 'int', 'value': 5},
         {'name': 'YUTNORI_YUTSEM_MAX', 'type': 'int', 'value': 6},
         {'name': 'YUYNORI_PLAYER_MAX', 'type': 'int', 'value': 2},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMiniGameYutnori'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'prob_name_tuple', 'type': 'tuple', 'value': ('Do', 'Ge', 'Geol', 'Yut', 'Mo', 'Back-do')},
         {'name': 'yut_img_path',
          'type': 'dict',
          'value': {0: ('d:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_front_img.sub'),
                    1: ('d:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_front_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_point_img.sub'),
                    2: ('d:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_front_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_point_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_front_img.sub'),
                    3: ('d:/ymir work/ui/minigame/yutnori/yut_front_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_front_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_point_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_front_img.sub'),
                    4: ('d:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub'),
                    5: ('d:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_point_img.sub', 'd:/ymir work/ui/minigame/yutnori/yut_back_img.sub')}}]}
