{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self', 'skill_vnum'], 'defaults': [], 'name': 'ClickMountSkillLevelUpButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'MountUpgradeSystemProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'state', 'skill_group'], 'defaults': [], 'name': 'OpenCharacterWindowWithState'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__DisableResultPopUpWindow'},
                     {'args': ['self', 'message'], 'defaults': [], 'name': '__EnableResultPopUpWindow'},
                     {'args': ['self', 'cur_level'], 'defaults': [], 'name': '__GetMountUpgradeCostData'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveFeedButtonDisable'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveFeedButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveFeedButtonEnable'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveFeedButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__LevelUpButtonDisable'},
                     {'args': ['self'], 'defaults': [], 'name': '__LevelUpButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': '__LevelUpButtonEnable'},
                     {'args': ['self'], 'defaults': [], 'name': '__LevelUpButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDataFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickGiveFeedButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickLevelUpButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__Open'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__ProgressMountUpgradeSystemGiveFeed'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__ProgressMountUpgradeSystemUILevelUp'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__ProgressMountUpgradeSystemUIOpen'},
                     {'args': ['self', 'is_max_mount_level'], 'defaults': [False], 'name': '__RefreshTextObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendMountUpgradeGiveFeed'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendMountUpgradeLevelUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendSkillLevelUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_MountUpgradeSystemWindow__MOUNT_UPGRADE_COST_TOKEN_SIZE', 'type': 'int', 'value': 5},
                    {'name': '_MountUpgradeSystemWindow__cost_gold_text_object', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__cost_gold_text_object' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__cur_exp_point', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__cur_exp_point' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__cur_level', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__cur_level' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__cur_level_text_object', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__cur_level_text_object' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__exp_gauge_bar', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__exp_gauge_bar' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__exp_gauge_text_object__popup_feed_window', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__exp_gauge_text_object__popup_feed_window' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__give_feed_button', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__give_feed_button' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__is_current_levelup_fail', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__is_current_levelup_fail' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__is_enable_levelup', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__is_enable_levelup' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__is_loaded', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__is_loaded' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__is_lock', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__is_lock' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__level_up_arrow_image', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__level_up_arrow_image' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__level_up_button', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__level_up_button' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__levelup_cost_feed', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__levelup_cost_feed' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__levelup_cost_yang', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__levelup_cost_yang' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__levelup_retry_cost_gem', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__levelup_retry_cost_gem' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__max_exp_point', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__max_exp_point' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__mount_upgrade_cost_dict', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__mount_upgrade_cost_dict' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__next_level', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__next_level' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__next_level_text_object', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__next_level_text_object' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__open_pos_x', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__open_pos_x' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__open_pos_y', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__open_pos_y' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__popup_level_up_window', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__popup_level_up_window' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__popup_skill_level_up_window', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__popup_skill_level_up_window' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__result_popup_window', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__result_popup_window' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__retry_cost_gem_text_object', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__retry_cost_gem_text_object' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '_MountUpgradeSystemWindow__skill_levelup_skill_vnum', 'type': 'member_descriptor', 'value': <member '_MountUpgradeSystemWindow__skill_levelup_skill_vnum' of 'MountUpgradeSystemWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMountUpgradeSystem'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MountUpgradeSystemWindow'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__mount_upgrade_cost_dict',
                               '__is_loaded',
                               '__cur_level',
                               '__next_level',
                               '__cur_exp_point',
                               '__max_exp_point',
                               '__levelup_cost_feed',
                               '__levelup_retry_cost_gem',
                               '__levelup_cost_yang',
                               '__is_current_levelup_fail',
                               '__is_enable_levelup',
                               '__is_lock',
                               '__open_pos_x',
                               '__open_pos_y',
                               '__give_feed_button',
                               '__level_up_button',
                               '__cur_level_text_object',
                               '__next_level_text_object',
                               '__retry_cost_gem_text_object',
                               '__cost_gold_text_object',
                               '__exp_gauge_text_object__popup_feed_window',
                               '__popup_level_up_window',
                               '__result_popup_window',
                               '__level_up_arrow_image',
                               '__exp_gauge_bar',
                               '__popup_skill_level_up_window',
                               '__skill_levelup_skill_vnum')}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'chatm2g', 'app', 'wndMgr', 'mount', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiMountUpgradeSystem'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
