{'class': [{'class': [],
            'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': '__new__'}],
            'import': [],
            'var': [{'name': '__copy__', 'type': 'method_descriptor', 'value': <method '__copy__' of 'collections.deque' objects>},
                    {'name': '__delitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__delitem__' of 'collections.deque' objects>},
                    {'name': '__doc__', 'type': 'str', 'value': 'deque(iterable[, maxlen]) --> deque object\n\nBuild an ordered collection with optimized access from its endpoints.'},
                    {'name': '__eq__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__eq__' of 'collections.deque' objects>},
                    {'name': '__ge__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ge__' of 'collections.deque' objects>},
                    {'name': '__getattribute__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getattribute__' of 'collections.deque' objects>},
                    {'name': '__getitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__getitem__' of 'collections.deque' objects>},
                    {'name': '__gt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__gt__' of 'collections.deque' objects>},
                    {'name': '__hash__', 'type': 'NoneType', 'value': None},
                    {'name': '__iadd__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iadd__' of 'collections.deque' objects>},
                    {'name': '__init__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__init__' of 'collections.deque' objects>},
                    {'name': '__iter__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__iter__' of 'collections.deque' objects>},
                    {'name': '__le__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__le__' of 'collections.deque' objects>},
                    {'name': '__len__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__len__' of 'collections.deque' objects>},
                    {'name': '__lt__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__lt__' of 'collections.deque' objects>},
                    {'name': '__ne__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__ne__' of 'collections.deque' objects>},
                    {'name': '__reduce__', 'type': 'method_descriptor', 'value': <method '__reduce__' of 'collections.deque' objects>},
                    {'name': '__repr__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__repr__' of 'collections.deque' objects>},
                    {'name': '__reversed__', 'type': 'method_descriptor', 'value': <method '__reversed__' of 'collections.deque' objects>},
                    {'name': '__setitem__', 'type': 'wrapper_descriptor', 'value': <slot wrapper '__setitem__' of 'collections.deque' objects>},
                    {'name': 'append', 'type': 'method_descriptor', 'value': <method 'append' of 'collections.deque' objects>},
                    {'name': 'appendleft', 'type': 'method_descriptor', 'value': <method 'appendleft' of 'collections.deque' objects>},
                    {'name': 'clear', 'type': 'method_descriptor', 'value': <method 'clear' of 'collections.deque' objects>},
                    {'name': 'count', 'type': 'method_descriptor', 'value': <method 'count' of 'collections.deque' objects>},
                    {'name': 'extend', 'type': 'method_descriptor', 'value': <method 'extend' of 'collections.deque' objects>},
                    {'name': 'extendleft', 'type': 'method_descriptor', 'value': <method 'extendleft' of 'collections.deque' objects>},
                    {'name': 'maxlen', 'type': 'getset_descriptor', 'value': <attribute 'maxlen' of 'collections.deque' objects>},
                    {'name': 'pop', 'type': 'method_descriptor', 'value': <method 'pop' of 'collections.deque' objects>},
                    {'name': 'popleft', 'type': 'method_descriptor', 'value': <method 'popleft' of 'collections.deque' objects>},
                    {'name': 'remove', 'type': 'method_descriptor', 'value': <method 'remove' of 'collections.deque' objects>},
                    {'name': 'reverse', 'type': 'method_descriptor', 'value': <method 'reverse' of 'collections.deque' objects>},
                    {'name': 'rotate', 'type': 'method_descriptor', 'value': <method 'rotate' of 'collections.deque' objects>}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'ButtonToolTipProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'CardMoveEndEvnet'},
                     {'args': ['self'], 'defaults': [], 'name': 'CardMoveStartEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'MonsterCardAchievRefresh'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MonsterCardIllustrationFail'},
                     {'args': ['self'], 'defaults': [], 'name': 'MonsterCardIllustrationRefresh'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'MonsterCardMissionFail'},
                     {'args': ['self', 'index', 'msg', 'is_detail_window'], 'defaults': [], 'name': 'OnClickAchievApplyRegistButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnRender'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'btnText'], 'defaults': [], 'name': 'OverInToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTipButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReciveMission'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMissionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RequestIllustration'},
                     {'args': ['self', 'type', 'name'], 'defaults': [], 'name': 'SelectedAchievImgOverIn'},
                     {'args': ['self', 'monster_vnum'], 'defaults': [], 'name': 'SetMonsterCardAchievModelText'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': 'SetPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAchievPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowPartyPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowSoloPage'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '_OpenAchievPopup'},
                     {'args': ['self', 'button'], 'defaults': [], 'name': '__AchievSortListOver'},
                     {'args': ['self'], 'defaults': [], 'name': '__AchievSortListOverOut'},
                     {'args': ['self', 'index', 'msg'], 'defaults': [], 'name': '__ApplyRegistMessageSend'},
                     {'args': ['self', 'index', 'msg'], 'defaults': [], 'name': '__AskRegistAchievMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'type', 'row', 'col'], 'defaults': [], 'name': '__CardImgClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearIllustrationButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearIllustrationPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseAchievPopup'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseAchievRegistQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__CloseQuestionDialog'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self', 'type', 'index'], 'defaults': [], 'name': '__EmergenceAreaOverIn'},
                     {'args': ['self', 'type', 'index'], 'defaults': [], 'name': '__EmergenceAreaOverOut'},
                     {'args': ['self', 'type', 'row', 'col'], 'defaults': [], 'name': '__IllustrationEmergenceAreaOverIn'},
                     {'args': ['self', 'type', 'row', 'col'], 'defaults': [], 'name': '__IllustrationEmergenceAreaOverOut'},
                     {'args': ['self', 'type', 'row', 'col'], 'defaults': [], 'name': '__IllustrationImgOverIn'},
                     {'args': ['self', 'type', 'row', 'col'], 'defaults': [], 'name': '__IllustrationImgOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitAccept'},
                     {'args': ['self', 'srcCard', 'dstCard'], 'defaults': [], 'name': '__InsertMoveCard'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeAchievList'},
                     {'args': ['self'], 'defaults': [], 'name': '__MissionPageClear'},
                     {'args': ['self'], 'defaults': [], 'name': '__ModelRotationProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__ModelUpDownCameraProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__ModelViewReset'},
                     {'args': ['self'], 'defaults': [], 'name': '__ModelZoomProgress'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAchievBonusListScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAchievListScroll'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickAchievChangeViewButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickExchangeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFirstPrevPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickLastNextPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickMissionInitButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickMotionButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNextPageButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPolyButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPrevPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPromotionButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickQuestionButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickReciveMissionButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickRewardCardButton'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__OnClickSelectAchievTypeButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickShowAchievDetailWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickShuffleCardButton'},
                     {'args': ['self', 'sort', 'text'], 'defaults': [], 'name': '__OnClickSortButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSortOpenwButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSummonButton'},
                     {'args': ['self', 'tabKey'], 'defaults': [], 'name': '__OnClickTabButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickWarpButton'},
                     {'args': ['self', 'msg', 'resize_width'], 'defaults': [False], 'name': '__OpenPopupDialog'},
                     {'args': ['self', 'mob_vnum'], 'defaults': [], 'name': '__PolyAccept'},
                     {'args': ['self', 'mob_vnum'], 'defaults': [], 'name': '__PromotionAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshMissionState'},
                     {'args': ['self'], 'defaults': [], 'name': '__RewardAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__SelectCellClear'},
                     {'args': ['self', 'type', 'index'], 'defaults': [], 'name': '__SelectedImgOverIn'},
                     {'args': ['self', 'type', 'index'], 'defaults': [], 'name': '__SelectedImgOverOut'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMissionProceeding'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMissionWait'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMonsterCardAchievBonusList'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMonsterCardAchievDungeonBonusList'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': '__ShowIllustrationPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowMissionPage'},
                     {'args': ['self', 'max_page', 'cur_page'], 'defaults': [], 'name': '__ShowPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShuffleAccept'},
                     {'args': ['self', 'mob_vnum'], 'defaults': [], 'name': '__TradeAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__WaitCellClear'},
                     {'args': ['self', 'mob_vnum'], 'defaults': [], 'name': '__WarpAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMonsterCard'}, {'name': '__qualname__', 'type': 'str', 'value': 'MonsterCardWindow'}]},
           {'class': [], 'func': [], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMonsterCard'}, {'name': '__qualname__', 'type': 'str', 'value': 'MissionPage'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'achiev_type', 'achiev_sort', 'achiev_index'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__AchievRankCountSetting'},
                     {'args': ['self'], 'defaults': [], 'name': '__BeforeSettingAchievDetailObject'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ClickMonsterCardAchievLineImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'type', 'key'], 'defaults': [], 'name': '__OnClickMonsterCardImg'},
                     {'args': ['self', 'key'], 'defaults': [], 'name': '__OnClickStarButton'},
                     {'args': ['self', 'type', 'key'], 'defaults': [], 'name': '__OnClickStarImg'},
                     {'args': ['self', 'achiev_type', 'achiev_sort', 'achiev_index'], 'defaults': [], 'name': '__SetAchievDetailWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'monster_card_window'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMonsterCard'}, {'name': '__qualname__', 'type': 'str', 'value': 'AchievDetailWindow'}]},
           {'class': [], 'func': [], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMonsterCard'}, {'name': '__qualname__', 'type': 'str', 'value': 'AchievPage'}]},
           {'class': [], 'func': [], 'import': [], 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMonsterCard'}, {'name': '__qualname__', 'type': 'str', 'value': 'IllustrationPage'}]}],
 'func': [{'args': ['n'], 'defaults': [], 'name': 'unsigned32'}],
 'import': ['emotion', 'chatm2g', 'app', 'uiPrivateShopBuilder', 'dbg', 'm2netm2g', 'playerm2g2', 'skill', 'constInfo', 'uiToolTip', 'chr', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'quest', 'playerSettingModule', 'wndMgr', 'uiAffectShower', 'item', 'ui', 'nonplayer'],
 'var': [{'name': 'CARD_IMG_DICT',
          'type': 'dict',
          'value': {0: 'd:/ymir work/ui/game/monster_card/empty_card.sub',
                    151: 'd:/ymir work/ui/game/monster_card/card/151.sub',
                    152: 'd:/ymir work/ui/game/monster_card/card/152.sub',
                    153: 'd:/ymir work/ui/game/monster_card/card/153.sub',
                    154: 'd:/ymir work/ui/game/monster_card/card/154.sub',
                    155: 'd:/ymir work/ui/game/monster_card/card/155.sub',
                    191: 'd:/ymir work/ui/game/monster_card/card/191.sub',
                    192: 'd:/ymir work/ui/game/monster_card/card/192.sub',
                    193: 'd:/ymir work/ui/game/monster_card/card/193.sub',
                    194: 'd:/ymir work/ui/game/monster_card/card/194.sub',
                    391: 'd:/ymir work/ui/game/monster_card/card/391.sub',
                    393: 'd:/ymir work/ui/game/monster_card/card/393.sub',
                    394: 'd:/ymir work/ui/game/monster_card/card/394.sub',
                    431: 'd:/ymir work/ui/game/monster_card/card/431.sub',
                    432: 'd:/ymir work/ui/game/monster_card/card/432.sub',
                    433: 'd:/ymir work/ui/game/monster_card/card/433.sub',
                    434: 'd:/ymir work/ui/game/monster_card/card/434.sub',
                    435: 'd:/ymir work/ui/game/monster_card/card/435.sub',
                    436: 'd:/ymir work/ui/game/monster_card/card/436.sub',
                    491: 'd:/ymir work/ui/game/monster_card/card/491.sub',
                    492: 'd:/ymir work/ui/game/monster_card/card/492.sub',
                    493: 'd:/ymir work/ui/game/monster_card/card/493.sub',
                    494: 'd:/ymir work/ui/game/monster_card/card/494.sub',
                    533: 'd:/ymir work/ui/game/monster_card/card/533.sub',
                    534: 'd:/ymir work/ui/game/monster_card/card/534.sub',
                    591: 'd:/ymir work/ui/game/monster_card/card/591.sub',
                    595: 'd:/ymir work/ui/game/monster_card/card/595.sub',
                    691: 'd:/ymir work/ui/game/monster_card/card/691.sub',
                    791: 'd:/ymir work/ui/game/monster_card/card/791.sub',
                    1091: 'd:/ymir work/ui/game/monster_card/card/1091.sub',
                    1093: 'd:/ymir work/ui/game/monster_card/card/1093.sub',
                    1192: 'd:/ymir work/ui/game/monster_card/card/1192.sub',
                    1304: 'd:/ymir work/ui/game/monster_card/card/1304.sub',
                    1901: 'd:/ymir work/ui/game/monster_card/card/1901.sub',
                    2092: 'd:/ymir work/ui/game/monster_card/card/2092.sub',
                    2191: 'd:/ymir work/ui/game/monster_card/card/2191.sub',
                    2206: 'd:/ymir work/ui/game/monster_card/card/2206.sub',
                    2306: 'd:/ymir work/ui/game/monster_card/card/2306.sub',
                    2402: 'd:/ymir work/ui/game/monster_card/card/2402.sub',
                    2492: 'd:/ymir work/ui/game/monster_card/card/2492.sub',
                    2493: 'd:/ymir work/ui/game/monster_card/card/2493.sub',
                    2597: 'd:/ymir work/ui/game/monster_card/card/2597.sub',
                    2752: 'd:/ymir work/ui/game/monster_card/card/2752.sub',
                    2762: 'd:/ymir work/ui/game/monster_card/card/2762.sub',
                    2772: 'd:/ymir work/ui/game/monster_card/card/2772.sub',
                    2782: 'd:/ymir work/ui/game/monster_card/card/2782.sub',
                    2792: 'd:/ymir work/ui/game/monster_card/card/2792.sub',
                    2802: 'd:/ymir work/ui/game/monster_card/card/2802.sub',
                    2812: 'd:/ymir work/ui/game/monster_card/card/2812.sub',
                    2822: 'd:/ymir work/ui/game/monster_card/card/2822.sub',
                    2832: 'd:/ymir work/ui/game/monster_card/card/2832.sub',
                    2842: 'd:/ymir work/ui/game/monster_card/card/2842.sub',
                    2852: 'd:/ymir work/ui/game/monster_card/card/2852.sub',
                    2862: 'd:/ymir work/ui/game/monster_card/card/2862.sub',
                    3091: 'd:/ymir work/ui/game/monster_card/card/3091.sub',
                    3191: 'd:/ymir work/ui/game/monster_card/card/3191.sub',
                    3291: 'd:/ymir work/ui/game/monster_card/card/3291.sub',
                    3491: 'd:/ymir work/ui/game/monster_card/card/3491.sub',
                    3591: 'd:/ymir work/ui/game/monster_card/card/3591.sub',
                    3596: 'd:/ymir work/ui/game/monster_card/card/3596.sub',
                    3791: 'd:/ymir work/ui/game/monster_card/card/3791.sub',
                    3891: 'd:/ymir work/ui/game/monster_card/card/3891.sub',
                    3910: 'd:/ymir work/ui/game/monster_card/card/3910.sub',
                    5161: 'd:/ymir work/ui/game/monster_card/card/5161.sub',
                    5162: 'd:/ymir work/ui/game/monster_card/card/5162.sub',
                    5163: 'd:/ymir work/ui/game/monster_card/card/5163.sub',
                    6009: 'd:/ymir work/ui/game/monster_card/card/6009.sub',
                    6091: 'd:/ymir work/ui/game/monster_card/card/6091.sub',
                    6109: 'd:/ymir work/ui/game/monster_card/card/6109.sub',
                    6116: 'd:/ymir work/ui/game/monster_card/card/6116.sub',
                    6191: 'd:/ymir work/ui/game/monster_card/card/6191.sub',
                    6192: 'd:/ymir work/ui/game/monster_card/card/6192.sub',
                    6392: 'd:/ymir work/ui/game/monster_card/card/6392.sub',
                    6405: 'd:/ymir work/ui/game/monster_card/card/6405.sub',
                    6407: 'd:/ymir work/ui/game/monster_card/card/6407.sub',
                    6408: 'd:/ymir work/ui/game/monster_card/card/6408.sub',
                    6699: 'd:/ymir work/ui/game/monster_card/card/6699.sub',
                    6705: 'd:/ymir work/ui/game/monster_card/card/6705.sub',
                    6706: 'd:/ymir work/ui/game/monster_card/card/6706.sub',
                    6723: 'd:/ymir work/ui/game/monster_card/card/6723.sub',
                    6724: 'd:/ymir work/ui/game/monster_card/card/6724.sub',
                    6749: 'd:/ymir work/ui/game/monster_card/card/6749.sub',
                    6756: 'd:/ymir work/ui/game/monster_card/card/6756.sub',
                    6764: 'd:/ymir work/ui/game/monster_card/card/6764.sub',
                    6776: 'd:/ymir work/ui/game/monster_card/card/6776.sub',
                    6783: 'd:/ymir work/ui/game/monster_card/card/6783.sub',
                    6789: 'd:/ymir work/ui/game/monster_card/card/6789.sub',
                    6791: 'd:/ymir work/ui/game/monster_card/card/6791.sub',
                    6797: 'd:/ymir work/ui/game/monster_card/card/6797.sub',
                    6805: 'd:/ymir work/ui/game/monster_card/card/6805.sub',
                    6815: 'd:/ymir work/ui/game/monster_card/card/6815.sub',
                    6820: 'd:/ymir work/ui/game/monster_card/card/6820.sub',
                    7609: 'd:/ymir work/ui/game/monster_card/card/7609.sub',
                    7610: 'd:/ymir work/ui/game/monster_card/card/7610.sub',
                    7611: 'd:/ymir work/ui/game/monster_card/card/7611.sub',
                    7612: 'd:/ymir work/ui/game/monster_card/card/7612.sub',
                    7613: 'd:/ymir work/ui/game/monster_card/card/7613.sub',
                    7614: 'd:/ymir work/ui/game/monster_card/card/7614.sub'}},
         {'name': 'CARD_MOVE_SPEED', 'type': 'float', 'value': 10.0},
         {'name': 'CARD_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/monster_card/card/'},
         {'name': 'CLASS_COUNT_MAX', 'type': 'dict', 'value': {0: 9, 1: 21, 2: 30, 3: 60, 4: 90, 5: 120}},
         {'name': 'FAILED_COUNT_MAX', 'type': 'int', 'value': 0},
         {'name': 'FAILED_ILLUSTRATION_MSG_MAX', 'type': 'int', 'value': 4},
         {'name': 'FAILED_MISSION_INIT_ITEM_FALL_SHORT', 'type': 'int', 'value': 1},
         {'name': 'FAILED_MISSION_MSG_MAX', 'type': 'int', 'value': 5},
         {'name': 'FAILED_MISSION_REWARD_INVEN_FULL', 'type': 'int', 'value': 2},
         {'name': 'FAILED_MISSION_REWARD_NO_CLEAR', 'type': 'int', 'value': 3},
         {'name': 'FAILED_MISSION_SHUFFLE_NO_ITEM', 'type': 'int', 'value': 0},
         {'name': 'FAILED_MSSION_COMMON_MSG', 'type': 'int', 'value': 4},
         {'name': 'FAILED_POLY_COOLTIME', 'type': 'int', 'value': 1},
         {'name': 'FAILED_WARP_LIMIT_LEVEL', 'type': 'int', 'value': 2},
         {'name': 'FAILED_WARP_TRADE', 'type': 'int', 'value': 3},
         {'name': 'ILLUSTRATED_ARRAY_HEIGHT', 'type': 'int', 'value': 2},
         {'name': 'ILLUSTRATED_ARRAY_WIDTH', 'type': 'int', 'value': 4},
         {'name': 'ILLUSTRATION_MODEL_RENDER', 'type': 'int', 'value': 1},
         {'name': 'ILLUSTRATION_MOTION_CALSS', 'type': 'int', 'value': 2},
         {'name': 'ILLUSTRATION_PAGE_MAX', 'type': 'int', 'value': 5},
         {'name': 'ILLUSTRATION_POLY_CLASS', 'type': 'int', 'value': 3},
         {'name': 'ILLUSTRATION_SUMMON_CLASS', 'type': 'int', 'value': 100},
         {'name': 'ILLUSTRATION_WARP_CLASS', 'type': 'int', 'value': 4},
         {'name': 'MAX_ACHIEV_BONUS_LINE_MAX_COUNT', 'type': 'int', 'value': 14},
         {'name': 'MAX_ACHIEV_LINE_MAX_COUNT', 'type': 'int', 'value': 10},
         {'name': 'MISSION_INDEX_MOB_CLEAR', 'type': 'int', 'value': 2},
         {'name': 'MISSION_INDEX_MOB_VNUM', 'type': 'int', 'value': 1},
         {'name': 'MISSION_INDEX_RESET_COUNT', 'type': 'int', 'value': 4},
         {'name': 'MISSION_INDEX_RESET_TIME', 'type': 'int', 'value': 3},
         {'name': 'MISSION_INDEX_SHUFFLE_COUNT', 'type': 'int', 'value': 5},
         {'name': 'MISSION_INDEX_STAGE', 'type': 'int', 'value': 0},
         {'name': 'MISSION_STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'MISSION_STATE_PROCEEDING', 'type': 'int', 'value': 2},
         {'name': 'MISSION_STATE_REWARD', 'type': 'int', 'value': 3},
         {'name': 'MISSION_STATE_WAIT', 'type': 'int', 'value': 1},
         {'name': 'ROOT_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/monster_card/'},
         {'name': 'SELECTED_ARRAY_WIDTH', 'type': 'int', 'value': 3},
         {'name': 'SHUFFLE_MAX', 'type': 'int', 'value': 1},
         {'name': 'STAR_COUNT', 'type': 'int', 'value': 5},
         {'name': 'TRADE_COUNT', 'type': 'int', 'value': 10},
         {'name': 'WAIT_ARRAY_HEIGHT', 'type': 'int', 'value': 2},
         {'name': 'WAIT_ARRAY_WIDTH', 'type': 'int', 'value': 8},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMonsterCard'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
