{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetInfo'}, {'args': ['self'], 'defaults': [], 'name': 'GetName'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'name', 'info', 'parent'], 'defaults': [None], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiMyShopDecoration'}, {'name': '__qualname__', 'type': 'str', 'value': 'DecoObj'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'min', 'value', 'max'], 'defaults': [], 'name': 'MINMAX'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'SelectButton'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'SelectShopModel'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'SelectTitleModel'},
                     {'args': ['self'], 'defaults': [], 'name': 'UseCompleteButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'UseNextButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'UsePrevButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__AllShopTitleHide'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadModelInfo'},
                     {'args': ['self', 'FileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshLeftBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShopModelListSetting'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShopTitleListSetting'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'MODE_MODEL_VIEW', 'type': 'int', 'value': 1},
                    {'name': 'MODE_TITLE_VIEW', 'type': 'int', 'value': 2},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiMyShopDecoration'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MyShopDecoration'}]}],
 'func': [],
 'import': ['__builtin__', 'uiScriptLocale', 'm2netm2g', 'playerm2g2', 'ui', 'wndMgr'],
 'var': [{'name': 'DECO_SHOP_MODEL_LIST', 'type': 'list', 'value': [['Alap\xe9rtelmezett', 30000], ['1001 \xe9jszaka', 30002], ['Grillkir\xe1ly', 30003], ['Kincsvad\xe1sz', 30004], ['Takar\xe9kl\xe1ng', 30005], ['Fegyverkeresked\xf5', 30006], ['P\xe1nc\xe9l-m\xe1rkeszerviz', 30007], ['Alkimista', 30008]]},
         {'name': 'DECO_SHOP_TITLE_LIST',
          'type': 'list',
          'value': [['Pokol', 'd:/ymir work/ui/pattern/myshop/fire/p_fire', '0xFF976D'],
                    ['J\xe9gkorszak', 'd:/ymir work/ui/pattern/myshop/ice/p_ice', '0xF9F4FF'],
                    ['Pergamen', 'd:/ymir work/ui/pattern/myshop/paper/p_paper', '0xFFBF8B'],
                    ['Harci z\xe1szl\xf3', 'd:/ymir work/ui/pattern/myshop/ribon/p_ribon', '0xFFECD1'],
                    ['Sz\xe1rnyak', 'd:/ymir work/ui/pattern/myshop/wing/p_wing', '0xF1ECE1']]},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiMyShopDecoration'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
