{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCostumeSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'wndInventory'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'}, {'name': '__qualname__', 'type': 'str', 'value': 'CostumeWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'ActivateSlot'},
                     {'args': ['self', 'metinSlotWindow', 'metinSlotPos', 'targetSlotWindow', 'targetSlotPos'], 'defaults': [], 'name': 'AttachMetinToItem'},
                     {'args': ['self', 'equipment_window'], 'defaults': [], 'name': 'BindEquipmentWindow'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelDlgQuestion'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'ClearActivatedSlots'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'ClickExtendInvenButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'metin_slot_pos', 'target_slot_pos'], 'defaults': [], 'name': 'CloseAttachMetinWindow'},
                     {'args': ['self', 'slotPos', 'count', 'itemtype'], 'defaults': [], 'name': 'CreateSecondConfirmQuestionDialog'},
                     {'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'DeactivateSlot'},
                     {'args': ['self', 'inventorylocalslot'], 'defaults': [], 'name': 'DelHighlightSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'scrollSlotWindow', 'scrollSlotPos', 'targetSlotWindow', 'targetSlotPos'], 'defaults': [], 'name': 'DetachMetinFromItem'},
                     {'args': ['self', 'event_type', 'idx'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self', 'item_vnum', 'msg', 'enough_count'], 'defaults': [], 'name': 'ExInvenItemUseMsg'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': 'GetConfirmQuestion'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetInventoryPageIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'HighlightSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsDlgQuestionShow'},
                     {'args': ['self', 'slotWindow', 'slotIndex'], 'defaults': [], 'name': 'ItemMoveFeedWindow'},
                     {'args': ['self', 'slotIndex', 'AcceSlot'], 'defaults': [], 'name': 'OnAcceAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAcceCloseEvent'},
                     {'args': ['self', 'slotPos', 'count', 'itemtype'], 'defaults': [], 'name': 'OnAcceptSellItem'},
                     {'args': ['self', 'slotIndex', 'AuraSlot'], 'defaults': [], 'name': 'OnAuraAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAuraCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseDetachMetinFromItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseSecondConfirmQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDenySellItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDetachMetinFromItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnGameOver'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'OnPickItem'},
                     {'args': ['self', 'money', 'cheque'], 'defaults': [], 'name': 'OnPickMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self', 'focus_idx'], 'defaults': [0], 'name': 'OpenPickMoneyDialog'},
                     {'args': ['self', 'overSlotPos', 'window_type'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'scrollSlotWindow', 'scrollSlotPos', 'targetSlotWindow', 'targetSlotPos'], 'defaults': [], 'name': 'RefineItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBagSlotWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'selectedSlotPos', 'selectedSlotWindow'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'itemSlotIndex', 'window_type'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SellItem'},
                     {'args': ['self', 'inven_slot_index'], 'defaults': [], 'name': 'SetCanMouseEventSlot'},
                     {'args': ['self', 'inven_slot_index'], 'defaults': [], 'name': 'SetCantMouseEventSlot'},
                     {'args': ['self', 'DragonSoulRefine'], 'defaults': [], 'name': 'SetDragonSoulRefineWindow'},
                     {'args': ['self', 'wndBar'], 'defaults': [], 'name': 'SetExpandedMoneyBar'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetInventoryPage'},
                     {'args': ['self', 'tooltipItemvalue'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetPetFeedWindow'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetPetHatchingWindow'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetPetNameChangeWindow'},
                     {'args': ['self', 'bUse'], 'defaults': [], 'name': 'SetUseItemMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'cur_stage'], 'defaults': [], 'name': 'ShowExtendInvenButton'},
                     {'args': ['self', 'slotIndex', 'window_type'], 'defaults': [], 'name': 'ShowToolTip'},
                     {'args': ['self', 'slotIndex', 'window'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self', 'fee', 'index'], 'defaults': [], 'name': '__AccecptGotoMistsIslandImmediately'},
                     {'args': ['self'], 'defaults': [], 'name': '__Accept'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceptExInvenItemUse'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': '__ActivePetHighlightSlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddHighlightSlotAcce'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddHighlightSlotAura'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddHighlightSlotChangeLook'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddHighlightSlotCube'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanAddAccessorySocket'},
                     {'args': ['self', 'dest_slot_window', 'dest_slot_pos'], 'defaults': [], 'name': '__CanAddAttr'},
                     {'args': ['self', 'dest_slot_window', 'dest_slot_pos'], 'defaults': [], 'name': '__CanAddAttrBewitch'},
                     {'args': ['self', 'dest_slot_window', 'dest_slot_pos'], 'defaults': [], 'name': '__CanAddAttrBless'},
                     {'args': ['self', 'dest_slot_window', 'dest_slot_pos'], 'defaults': [], 'name': '__CanAddAttrBlessing'},
                     {'args': ['self', 'dest_slot_window', 'dest_slot_pos'], 'defaults': [], 'name': '__CanAddAttrGreen'},
                     {'args': ['self', 'itemVNum', 'itemSlotIndex'], 'defaults': [], 'name': '__CanAttachGrowthPetItem'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanChangeCostumeAttrList'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanChangeItemAttr67List'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanChangeItemAttrList'},
                     {'args': ['self', 'dest_slot_window', 'dest_slot_pos'], 'defaults': [], 'name': '__CanChangeItemAttrListGreen'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanCleanBrokenMetinStone'},
                     {'args': ['self', 'dst_slot_window', 'dst_slot_pos'], 'defaults': [], 'name': '__CanCleanMetinStone'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos', 'mtrlVnum'], 'defaults': [], 'name': '__CanPutAccessorySocket'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanResetCostumeAttr'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__CanUseGrowthPet'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__CanUsePetBagItem'},
                     {'args': ['self', 'srcItemVNum', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanUseSrcItemToDstItem'},
                     {'args': ['self', 'srcItemVNum', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanUseSrcPetItemToDstPetItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__Cancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__CancelExInvenItemUse'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckAttrOrMetinSocketAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckAttrOrMetinSocketCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateExtendInvenButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__DelHighlightSlotAcce'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__DelHighlightSlotAura'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__DelHighlightSlotChangeLook'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__DelHighlightSlotCube'},
                     {'args': ['self', 'srcItemVID', 'srcItemSlotWindow', 'srcItemSlotPos', 'dstItemSlotWindow', 'dstItemSlotPos'], 'defaults': [], 'name': '__DropSrcItemToDestItemInInventory'},
                     {'args': ['self'], 'defaults': [], 'name': '__GotoMistsIsland'},
                     {'args': ['self', 'fee', 'index'], 'defaults': [], 'name': '__GotoMistsIslandImmediately'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllExtendInvenButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HighlightSlot_Clear'},
                     {'args': ['self'], 'defaults': [], 'name': '__HighlightSlot_Refresh'},
                     {'args': ['self', 'local', 'window_type'], 'defaults': [1], 'name': '__InventoryLocalSlotPosToGlobalSlotPos'},
                     {'args': ['self', 'srcItemVID'], 'defaults': [], 'name': '__IsPetItem'},
                     {'args': ['self', 'srcItemVNum', 'srcSlotPos'], 'defaults': [], 'name': '__IsUsableItemToItem'},
                     {'args': ['self', 'srcItemVNum'], 'defaults': [], 'name': '__IsUsablePetItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self', 'dstItemWindow', 'dstItemPos'], 'defaults': [], 'name': '__OpenCheckAttrOrMetinSocketQuestionDialog'},
                     {'args': ['self', 'enough_count'], 'defaults': [], 'name': '__OpenExInvenFallShortCountMsgDlg'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__OpenExInvenMsgDlg'},
                     {'args': ['self', 'enough_count'], 'defaults': [], 'name': '__OpenExInvenQuestionDlg'},
                     {'args': ['self', 'srcItemSlotPos', 'dstItemSlotPos'], 'defaults': [], 'name': '__OpenPetBagQuestionDialog'},
                     {'args': ['self', 'srcItemWindow', 'srcItemPos', 'dstItemWindow', 'dstItemPos'], 'defaults': [], 'name': '__OpenPetItemQuestionDialog'},
                     {'args': ['self', 'srcItemWindow', 'srcItemPos', 'dstItemWindow', 'dstItemPos'], 'defaults': [], 'name': '__OpenQuestionDialog'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OpenQuestionDialog2'},
                     {'args': ['self', 'srcItemWindow', 'srcItemPos', 'dstItemWindow', 'dstItemPos'], 'defaults': [], 'name': '__OpenSetClearItemQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetBagTakeOutDialogAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetBagTakeOutDialogCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetItemAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetItemCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetSkillDeleteQuestionDialogAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetSkillDeleteQuestionDialogCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionDialog2Accept'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionDialog2Cancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshExinvenCoverSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshExinvenSlotState'},
                     {'args': ['self', 'window_type', 'itemSlotPos'], 'defaults': [], 'name': '__SellItem'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos', 'srcItemCount'], 'defaults': [], 'name': '__SendMoveItemPacket'},
                     {'args': ['self', 'slotPos', 'slotWindow'], 'defaults': [1], 'name': '__SendUseItemPacket'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__SendUseItemToItemPacket'},
                     {'args': ['self', 'srcItemVID', 'srcItemSlotWindow', 'srcItemSlotPos', 'dstItemSlotWindow', 'dstItemSlotPos'], 'defaults': [], 'name': '__SendUsePetItemToItemPacket'},
                     {'args': ['self', 'use_type', 'src_window', 'src_pos', 'dst_window', 'dst_pos'], 'defaults': [], 'name': '__SendUseTypeItemToItemPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetClearItemAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetClearItemCancel'},
                     {'args': ['self', 'slotNumber', 'itemVnum'], 'defaults': [], 'name': '__SetCollTimePetItemSlot'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': '__UseItem'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': '__UseItemAcce'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': '__UseItemAura'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': '__UseItemConfirmByVnum'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemMonsterCardOnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemMonsterCardOnCancel'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__UseItemPet'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__UseItemPetNameChange'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemQuestionDialog_OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemQuestionDialog_OnCancel'},
                     {'args': ['self', 'slot_index', 'slot_window'], 'defaults': [], 'name': '__UseSkillBook'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'USE_TYPE_TUPLE',
                     'type': 'tuple',
                     'value': ('USE_CLEAN_SOCKET',
                               'USE_CHANGE_ATTRIBUTE',
                               'USE_ADD_ATTRIBUTE',
                               'USE_ADD_ATTRIBUTE2',
                               'USE_ADD_ACCESSORY_SOCKET',
                               'USE_PUT_INTO_ACCESSORY_SOCKET',
                               'USE_PUT_INTO_BELT_SOCKET',
                               'USE_PUT_INTO_RING_SOCKET',
                               'USE_CHANGE_COSTUME_ATTR',
                               'USE_RESET_COSTUME_ATTR',
                               'USE_SELECT_ATTRIBUTE',
                               'USE_CHANGE_ATTRIBUTE2',
                               'USE_ELEMENT_UPGRADE',
                               'USE_ELEMENT_DOWNGRADE',
                               'USE_ELEMENT_CHANGE')},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'InventoryWindow'},
                    {'name': 'dlgPickETC', 'type': 'NoneType', 'value': None},
                    {'name': 'dlgPickMoney', 'type': 'NoneType', 'value': None},
                    {'name': 'interface', 'type': 'NoneType', 'value': None},
                    {'name': 'isLoaded', 'type': 'int', 'value': 0},
                    {'name': 'isOpenedBeltWindowWhenClosingInventory', 'type': 'int', 'value': 0},
                    {'name': 'isOpenedCostumeWindowWhenClosingInventory', 'type': 'int', 'value': 0},
                    {'name': 'petFeedWindow', 'type': 'NoneType', 'value': None},
                    {'name': 'petHatchingWindow', 'type': 'NoneType', 'value': None},
                    {'name': 'petNameChangeWindow', 'type': 'NoneType', 'value': None},
                    {'name': 'pop', 'type': 'NoneType', 'value': None},
                    {'name': 'questionDialog', 'type': 'NoneType', 'value': None},
                    {'name': 'sellingSlotNumber', 'type': 'int', 'value': -1},
                    {'name': 'sellingSlotWindow', 'type': 'int', 'value': 1},
                    {'name': 'tooltipItem', 'type': 'NoneType', 'value': None},
                    {'name': 'wndBelt', 'type': 'NoneType', 'value': None},
                    {'name': 'wndCostume', 'type': 'NoneType', 'value': None}]},
           {'class': [],
            'func': [{'args': ['self', 'index'], 'defaults': [], 'name': 'ClickExtendInvenButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickMallButton'},
                     {'args': ['self', 'cur_stage'], 'defaults': [], 'name': 'ShowExtendInvenButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'}, {'name': '__qualname__', 'type': 'str', 'value': 'BattleRoyaleInventoryWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'AdjustPosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpeningInventory'},
                     {'args': ['self', 'is_open_belt_slot'], 'defaults': [True], 'name': 'IsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSlot'},
                     {'args': ['self', 'move_window'], 'defaults': [], 'name': 'SetMoveParentWindow'},
                     {'args': ['self', 'is_open_belt_slot'], 'defaults': [True], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshEquipmentSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'wndInventory'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CheckItemStateToMoveBeltInventory', 'type': 'classmethod', 'value': <classmethod object at 0x0B3A3270>},
                    {'name': 'CheckWindowOpenWhenUseBeltInventory', 'type': 'classmethod', 'value': <classmethod object at 0x0B3A3250>},
                    {'name': 'IsItemMovableWhenUseBeltInventory', 'type': 'classmethod', 'value': <classmethod object at 0x0B3A3290>},
                    {'name': '_BeltInventoryWindow__move_parent_window', 'type': 'member_descriptor', 'value': <member '_BeltInventoryWindow__move_parent_window' of 'BeltInventoryWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BeltInventoryWindow'},
                    {'name': '__slots__', 'type': 'str', 'value': '__move_parent_window'}]},
           {'class': [],
            'func': [{'args': ['self', 'page_index'], 'defaults': [], 'name': 'AdditionalEquipmentPageSetting'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'inventory_window'], 'defaults': [], 'name': 'BindInventoryWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'page_index'], 'defaults': [], 'name': 'EquipmentPageTabSetting'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetBeltWnd'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsActiveAdditionalEquipmentPage'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowCostumeInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleEquipmentPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickCostumeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickDSSButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMallButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickPremiumPrivateShopButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateCostumeWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshEquipmentSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshUniqueSlot'},
                     {'args': ['self', 'page_index'], 'defaults': [], 'name': '__RequestChangeEquipmentpage'},
                     {'args': ['self', 'page_index'], 'defaults': [], 'name': '__UseChangeEquipmentPageSkill'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'EQUIPMENT_CHANGE_COOLTIME', 'type': 'int', 'value': 3},
                    {'name': 'EXPANSION_CHANGE_HEIGHT_SIZE', 'type': 'int', 'value': 20},
                    {'name': '_EquipmentWindow__wnd_inventory__equipment_slot__unique_slot__tab_btn__tab_img__current_page__wnd_belt__wnd_costume__is_open_costume_window__is_enable_additional_page__dragon_soul_button__mall_button__premium_private_shop_button__costume_button__interface__additional_tab__base_tab',
                     'type': 'member_descriptor',
                     'value': <member '_EquipmentWindow__wnd_inventory__equipment_slot__unique_slot__tab_btn__tab_img__current_page__wnd_belt__wnd_costume__is_open_costume_window__is_enable_additional_page__dragon_soul_button__mall_button__premium_private_shop_button__costume_button__interface__additional_tab__base_tab' of 'EquipmentWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'EquipmentWindow'},
                    {'name': '__slots__',
                     'type': 'str',
                     'value': '__wnd_inventory__equipment_slot__unique_slot__tab_btn__tab_img__current_page__wnd_belt__wnd_costume__is_open_costume_window__is_enable_additional_page__dragon_soul_button__mall_button__premium_private_shop_button__costume_button__interface__additional_tab__base_tab'}]}],
 'func': [{'args': ['window'], 'defaults': [], 'name': 'ReprGetItemCount'}, {'args': ['window'], 'defaults': [], 'name': 'ReprGetItemIndex'}],
 'import': ['chatm2g',
            'app',
            'uiPrivateShopBuilder',
            'uiPickMoney',
            'm2netm2g',
            'playerm2g2',
            'uiRefine',
            'battleRoyaleMgr',
            'constInfo',
            'grp',
            'mercenary',
            'uiToolTip',
            'uiAttachMetin',
            'uiPickETC',
            'mouseModule',
            'uiScriptLocale',
            'localeInfo',
            'uiCommon',
            'snd',
            '__builtin__',
            'ime',
            'background',
            'wndMgr',
            'uiPetInfo',
            'mount',
            'item',
            'ui'],
 'var': [{'name': 'ADD_ATTRIBUTE_BLESSING_ATTR_COUNT', 'type': 'int', 'value': 4},
         {'name': 'ADD_ATTRIBUTE_LIMIT_ATTR_COUNT', 'type': 'int', 'value': 4},
         {'name': 'ADD_GREEN_STRENGTH_LIMIT_ATTR_COUNT', 'type': 'int', 'value': 4},
         {'name': 'ADD_GREEN_STRENGTH_LIMIT_LEVEL', 'type': 'int', 'value': 40},
         {'name': 'BEWITCH_ITEM_LIMIT_RARE_ATTR_COUNT', 'type': 'int', 'value': 2},
         {'name': 'CHANGE_ATTR_GREEN_STRENGTH_LIMIT_LEVEL', 'type': 'int', 'value': 40},
         {'name': 'EX_INVEN_COVER_IMG_CLOSE', 'type': 'str', 'value': 'd:/ymir work/ui/game/windows/ex_inven_cover_button_close.sub'},
         {'name': 'EX_INVEN_COVER_IMG_OPEN', 'type': 'str', 'value': 'd:/ymir work/ui/game/windows/ex_inven_cover_button_open.sub'},
         {'name': 'ITEM_FLAG_APPLICABLE', 'type': 'int', 'value': 8192},
         {'name': 'ITEM_VNUM_LIST_TIGER_COIN_VOUCHER', 'type': 'tuple', 'value': (38015, 38016, 38017, 38018)},
         {'name': 'ITEM_VNUM_OPEN_GLOVE_SLOT_TICKET', 'type': 'int', 'value': 72352},
         {'name': 'ITEM_VNUM_RING_OF_ELEMENTAL_100', 'type': 'int', 'value': 39116},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiNewInventory'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
