{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshCostumeSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'wndInventory'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'}, {'name': '__qualname__', 'type': 'str', 'value': 'CostumeWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'ActivateSlot'},
                     {'args': ['self', 'metinSlotWindow', 'metinSlotPos', 'targetSlotWindow', 'targetSlotPos'], 'defaults': [], 'name': 'AttachMetinToItem'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterfaceClass'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelDlgQuestion'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickCostumeButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickDSSButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickMallButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'slotindex', 'type'], 'defaults': [], 'name': 'DeactivateSlot'},
                     {'args': ['self', 'inventorylocalslot'], 'defaults': [], 'name': 'DelHighlightSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'scrollSlotWindow', 'scrollSlotPos', 'targetSlotWindow', 'targetSlotPos'], 'defaults': [], 'name': 'DetachMetinFromItem'},
                     {'args': ['self', 'event_type', 'idx'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self', 'item_vnum', 'msg', 'enough_count'], 'defaults': [], 'name': 'ExInvenItemUseMsg'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetInventoryPageIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'slot'], 'defaults': [], 'name': 'HighlightSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsDlgQuestionShow'},
                     {'args': ['self', 'slotWindow', 'slotIndex'], 'defaults': [], 'name': 'ItemMoveFeedWindow'},
                     {'args': ['self', 'slotIndex', 'AcceSlot'], 'defaults': [], 'name': 'OnAcceAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAcceCloseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDetachMetinFromItem'},
                     {'args': ['self', 'x', 'y'], 'defaults': [], 'name': 'OnMoveWindow'},
                     {'args': ['self', 'count'], 'defaults': [], 'name': 'OnPickItem'},
                     {'args': ['self', 'money', 'cheque'], 'defaults': [], 'name': 'OnPickMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self', 'focus_idx'], 'defaults': [0], 'name': 'OpenPickMoneyDialog'},
                     {'args': ['self', 'overSlotPos', 'window_type'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'scrollSlotWindow', 'scrollSlotPos', 'targetSlotWindow', 'targetSlotPos'], 'defaults': [], 'name': 'RefineItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBagSlotWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshEquipSlotWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'selectedSlotPos', 'selectedSlotWindow'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'itemSlotIndex', 'window_type'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SellItem'},
                     {'args': ['self', 'inven_slot_index'], 'defaults': [], 'name': 'SetCanMouseEventSlot'},
                     {'args': ['self', 'inven_slot_index'], 'defaults': [], 'name': 'SetCantMouseEventSlot'},
                     {'args': ['self', 'isclick'], 'defaults': [], 'name': 'SetClickBeltInventory'},
                     {'args': ['self', 'DragonSoulRefine'], 'defaults': [], 'name': 'SetDragonSoulRefineWindow'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetEquipmentPage'},
                     {'args': ['self', 'wndBar'], 'defaults': [], 'name': 'SetExpandedMoneyBar'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetInventoryPage'},
                     {'args': ['self', 'tooltipItemvalue'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetPetFeedWindow'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetPetHatchingWindow'},
                     {'args': ['self', 'window'], 'defaults': [], 'name': 'SetPetNameChangeWindow'},
                     {'args': ['self', 'bUse'], 'defaults': [], 'name': 'SetUseItemMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowCostumeInventory'},
                     {'args': ['self', 'slotIndex', 'window_type'], 'defaults': [], 'name': 'ShowToolTip'},
                     {'args': ['self', 'slotIndex', 'window'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__Accept'},
                     {'args': ['self'], 'defaults': [], 'name': '__AcceptExInvenItemUse'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': '__ActivePetHighlightSlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddHighlightSlotAcce'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__AddHighlightSlotChangeLook'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanAddAccessorySocket'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanAddItemAttr'},
                     {'args': ['self', 'itemVNum', 'itemSlotIndex'], 'defaults': [], 'name': '__CanAttachGrowthPetItem'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanChangeCostumeAttrList'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanChangeItemAttrList'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanCleanBrokenMetinStone'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos', 'mtrlVnum'], 'defaults': [], 'name': '__CanPutAccessorySocket'},
                     {'args': ['self', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanResetCostumeAttr'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__CanUseGrowthPet'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__CanUsePetBagItem'},
                     {'args': ['self', 'srcItemVNum', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanUseSrcItemToDstItem'},
                     {'args': ['self', 'srcItemVNum', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__CanUseSrcPetItemToDstPetItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__Cancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__CancelExInvenItemUse'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__ClickExtendInvenButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateExtendInvenButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__DelHighlightSlotAcce'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__DelHighlightSlotChangeLook'},
                     {'args': ['self', 'srcItemVID', 'srcItemSlotWindow', 'srcItemSlotPos', 'dstItemSlotWindow', 'dstItemSlotPos'], 'defaults': [], 'name': '__DropSrcItemToDestItemInInventory'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllExtendInvenButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HighlightSlot_Clear'},
                     {'args': ['self'], 'defaults': [], 'name': '__HighlightSlot_Refresh'},
                     {'args': ['self', 'local', 'window_type'], 'defaults': [1], 'name': '__InventoryLocalSlotPosToGlobalSlotPos'},
                     {'args': ['self', 'srcItemVID'], 'defaults': [], 'name': '__IsPetItem'},
                     {'args': ['self', 'srcItemVNum', 'srcSlotPos'], 'defaults': [], 'name': '__IsUsableItemToItem'},
                     {'args': ['self', 'srcItemVNum'], 'defaults': [], 'name': '__IsUsablePetItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self', 'enough_count'], 'defaults': [], 'name': '__OpenExInvenFallShortCountMsgDlg'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__OpenExInvenMsgDlg'},
                     {'args': ['self', 'enough_count'], 'defaults': [], 'name': '__OpenExInvenQuestionDlg'},
                     {'args': ['self', 'srcItemSlotPos', 'dstItemSlotPos'], 'defaults': [], 'name': '__OpenPetBagQuestionDialog'},
                     {'args': ['self', 'srcItemWindow', 'srcItemPos', 'dstItemWindow', 'dstItemPos'], 'defaults': [], 'name': '__OpenPetItemQuestionDialog'},
                     {'args': ['self', 'srcItemWindow', 'srcItemPos', 'dstItemWindow', 'dstItemPos'], 'defaults': [], 'name': '__OpenQuestionDialog'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__OpenQuestionDialog2'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetItemAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetItemCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetSkillDeleteQuestionDialogAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__PetSkillDeleteQuestionDialogCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionDialog2Accept'},
                     {'args': ['self'], 'defaults': [], 'name': '__QuestionDialog2Cancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshExinvenCoverSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshExinvenSlotState'},
                     {'args': ['self', 'window_type', 'itemSlotPos'], 'defaults': [], 'name': '__SellItem'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos', 'srcItemCount'], 'defaults': [], 'name': '__SendMoveItemPacket'},
                     {'args': ['self', 'slotPos', 'slotWindow'], 'defaults': [1], 'name': '__SendUseItemPacket'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__SendUseItemToItemPacket'},
                     {'args': ['self', 'srcItemVID', 'srcItemSlotWindow', 'srcItemSlotPos', 'dstItemSlotWindow', 'dstItemSlotPos'], 'defaults': [], 'name': '__SendUsePetItemToItemPacket'},
                     {'args': ['self', 'slotNumber', 'itemVnum'], 'defaults': [], 'name': '__SetCollTimePetItemSlot'},
                     {'args': ['self', 'cur_stage'], 'defaults': [], 'name': '__ShowExtendInvenButton'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': '__UseItem'},
                     {'args': ['self', 'slotIndex', 'slotWindow'], 'defaults': [], 'name': '__UseItemAcce'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemMonsterCardOnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemMonsterCardOnCancel'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__UseItemPet'},
                     {'args': ['self', 'srcSlotWindow', 'srcSlotPos', 'dstSlotWindow', 'dstSlotPos'], 'defaults': [], 'name': '__UseItemPetNameChange'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemQuestionDialog_OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': '__UseItemQuestionDialog_OnCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'USE_TYPE_TUPLE',
                     'type': 'tuple',
                     'value': ('USE_CLEAN_SOCKET', 'USE_CHANGE_ATTRIBUTE', 'USE_ADD_ATTRIBUTE', 'USE_ADD_ATTRIBUTE2', 'USE_ADD_ACCESSORY_SOCKET', 'USE_PUT_INTO_ACCESSORY_SOCKET', 'USE_PUT_INTO_BELT_SOCKET', 'USE_PUT_INTO_RING_SOCKET', 'USE_CHANGE_COSTUME_ATTR', 'USE_RESET_COSTUME_ATTR', 'USE_SELECT_ATTRIBUTE')},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'InventoryWindow'},
                    {'name': 'dlgPickETC', 'type': 'NoneType', 'value': None},
                    {'name': 'dlgPickMoney', 'type': 'NoneType', 'value': None},
                    {'name': 'interface', 'type': 'NoneType', 'value': None},
                    {'name': 'isLoaded', 'type': 'int', 'value': 0},
                    {'name': 'isOpenedBeltWindowWhenClosingInventory', 'type': 'int', 'value': 0},
                    {'name': 'isOpenedCostumeWindowWhenClosingInventory', 'type': 'int', 'value': 0},
                    {'name': 'petFeedWindow', 'type': 'NoneType', 'value': None},
                    {'name': 'petHatchingWindow', 'type': 'NoneType', 'value': None},
                    {'name': 'petNameChangeWindow', 'type': 'NoneType', 'value': None},
                    {'name': 'pop', 'type': 'NoneType', 'value': None},
                    {'name': 'questionDialog', 'type': 'NoneType', 'value': None},
                    {'name': 'sellingSlotNumber', 'type': 'int', 'value': -1},
                    {'name': 'sellingSlotWindow', 'type': 'int', 'value': 1},
                    {'name': 'tooltipItem', 'type': 'NoneType', 'value': None},
                    {'name': 'wndBelt', 'type': 'NoneType', 'value': None},
                    {'name': 'wndCostume', 'type': 'NoneType', 'value': None}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AdjustPositionAndSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CloseInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetBasePosition'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOpeningInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenInventory'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSlot'},
                     {'args': ['self', 'openBeltSlot'], 'defaults': [0], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'wndInventory'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiNewInventory'}, {'name': '__qualname__', 'type': 'str', 'value': 'BeltInventoryWindow'}]}],
 'func': [{'args': ['window'], 'defaults': [], 'name': 'ReprGetItemCount'}, {'args': ['window'], 'defaults': [], 'name': 'ReprGetItemIndex'}],
 'import': ['chatm2g', 'app', 'uiPrivateShopBuilder', 'uiPickMoney', 'm2netm2g', 'playerm2g2', 'uiRefine', 'constInfo', 'grp', 'uiToolTip', 'uiAttachMetin', 'uiPickETC', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'ime', 'wndMgr', 'uiPetInfo', 'item', 'ui'],
 'var': [{'name': 'EX_INVEN_COVER_IMG_CLOSE', 'type': 'str', 'value': 'd:/ymir work/ui/game/windows/ex_inven_cover_button_close.sub'},
         {'name': 'EX_INVEN_COVER_IMG_OPEN', 'type': 'str', 'value': 'd:/ymir work/ui/game/windows/ex_inven_cover_button_open.sub'},
         {'name': 'ITEM_FLAG_APPLICABLE', 'type': 'int', 'value': 16384},
         {'name': 'ITEM_MALL_BUTTON_ENABLE', 'type': 'bool', 'value': True},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiNewInventory'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
