{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': 'OnBlockMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeMusicVolume'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangePKMode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeSoundVolume'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseInputDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDeleteMobile'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnInputMobileAuthorityCode'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnInputMobilePhoneNumber'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMobileAuthority'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshBlock'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMobile'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckPvPProtectedLevelPlayer'},
                     {'args': ['self', 'buttonList', 'buttonIndex'], 'defaults': [], 'name': '__ClickRadioButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnChangeMobilePhoneNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickBlockExchangeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickBlockFriendButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickBlockGuildButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickBlockPartyButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickBlockWhisperButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickCameraModeLongButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickCameraModeShortButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeLevel0Button'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeLevel1Button'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeLevel2Button'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNameColorModeEmpireButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNameColorModeNormalButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPvPModeFreeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPvPModeGuildButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPvPModePeaceButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPvPModeRevengeButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickTargetBoardNoViewButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickTargetBoardViewButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnDeleteMobilePhoneNumber'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshPVPButtonList'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetCameraMode'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetFogLevel'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetNameColorMode'},
                     {'args': ['self', 'mode'], 'defaults': [], 'name': '__SetPKMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetPeacePKMode'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': '__SetTargetBoardViewMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiOption'}, {'name': '__qualname__', 'type': 'str', 'value': 'OptionDialog'}]}],
 'func': [],
 'import': ['snd', 'constInfo', '__builtin__', 'chatm2g', 'app', 'chrmgrm2g', 'systemSetting', 'm2netm2g', 'playerm2g2', 'ui', 'localeInfo'],
 'var': [{'name': 'MOBILE', 'type': 'bool', 'value': False},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiOption'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'blockMode', 'type': 'int', 'value': 0}]}
