{'class': [{'class': [],
            'func': [{'args': ['self', 'minimap'], 'defaults': [], 'name': 'BindMiniMap'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'Off'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'PartyMatchResult'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'map_index'], 'defaults': [], 'name': '__ClickDungeonButtonOver'},
                     {'args': ['self', 'map_index'], 'defaults': [], 'name': '__ClickDungeonButtonOverOut'},
                     {'args': ['self', 'map_index'], 'defaults': [], 'name': '__ClickDungeonSelect'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickDungeonSelectButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickMatchingButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateDungeonNameButton'},
                     {'args': ['self', 'show'], 'defaults': [], 'name': '__DungeonSelectWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__Init'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__PartyMatchMinimapButton'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__PartyMatchMsg'},
                     {'args': ['self', 'level'], 'defaults': [], 'name': '__SetEntreeLevel'},
                     {'args': ['self', 'map_index'], 'defaults': [], 'name': '__SetInfo'},
                     {'args': ['self', 'map_index'], 'defaults': [], 'name': '__SetInfoMember'},
                     {'args': ['self', 'slotIndex', 'item_vnum', 'item_count'], 'defaults': [], 'name': '__SetSlotRequiredItem'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SlotOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__SlotOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPartyMatch'}, {'name': '__qualname__', 'type': 'str', 'value': 'PartyMatch'}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'constInfo', 'chrmgrm2g', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'item', 'ui'],
 'var': [{'name': 'MATCH_STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'MATCH_STATE_SEARCHING', 'type': 'int', 'value': 1},
         {'name': 'PARTY_MEMBER_MAX', 'type': 'int', 'value': 8},
         {'name': 'REQUIRED_ITEM_MAX', 'type': 'int', 'value': 3},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiPartyMatch'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
