{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'FadeIn'},
                     {'args': ['self', 'event', 'args'], 'defaults': [-1], 'name': 'FadeOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'event', 'args'], 'defaults': [-1], 'name': 'SAFE_FadeOut'},
                     {'args': ['self', 'alpha'], 'defaults': [], 'name': 'SetAlpha'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPhaseCurtain'}, {'name': '__qualname__', 'type': 'str', 'value': 'PhaseCurtain'}]}],
 'func': [],
 'import': ['grp', '__builtin__', 'app', 'ui', 'wndMgr'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPhaseCurtain'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
