{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAccept'},
                     {'args': ['self', 'maxValue', 'chequeMaxValue'], 'defaults': [0], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetAcceptEvent'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetCloseEvent'},
                     {'args': ['self', 'focus_idx'], 'defaults': [], 'name': 'SetFocus'},
                     {'args': ['self', 'max'], 'defaults': [], 'name': 'SetMax'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTitleName'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickChequeEditLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickValueEditLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPickMoney'}, {'name': '__qualname__', 'type': 'str', 'value': 'PickMoneyDialog'}]}],
 'func': [],
 'import': ['ime', '__builtin__', 'app', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPickMoney'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
