{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'DisableShowAlways'},
                     {'args': ['self'], 'defaults': [], 'name': 'EnableShowAlways'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshGauge'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPlayerGauge'}, {'name': '__qualname__', 'type': 'str', 'value': 'PlayerGauge'}]}],
 'func': [],
 'import': ['textTail', '__builtin__', 'chr', 'playerm2g2', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPlayerGauge'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
