{'class': [{'class': [],
            'func': [{'args': ['self', 'game_button_window'], 'defaults': [], 'name': 'BindGameButtonWindow'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetPopupNoticeEventFlagValue'},
                     {'args': ['self'], 'defaults': [], 'name': 'InitWebPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnClickPopupNoticeUIOpen'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'url', 'is_checked'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'type', 'is_checked', 'url'], 'defaults': [], 'name': 'PopupNoticeProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'flag_value', 'is_enter'], 'defaults': [], 'name': 'SetPopupNoticeEventFlag'},
                     {'args': ['self', 'title'], 'defaults': [], 'name': 'SetTitle'},
                     {'args': ['self', 'event_type'], 'defaults': [], 'name': '__OnClickCheckBox'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCloseButtonClick'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_PopupNoticeWindow__check_image', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__check_image' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__checkbox', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__checkbox' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__game_button_window', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__game_button_window' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__interface', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__interface' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__is_hide_when_quest_open', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__is_hide_when_quest_open' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__is_not_show_checked', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__is_not_show_checked' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__popup_event_flag_value', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__popup_event_flag_value' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__prev_pos', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__prev_pos' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__title_bar', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__title_bar' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__title_name', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__title_name' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__url', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__url' of 'PopupNoticeWindow' objects>},
                    {'name': '_PopupNoticeWindow__web_box', 'type': 'member_descriptor', 'value': <member '_PopupNoticeWindow__web_box' of 'PopupNoticeWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiPopupNotice'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'PopupNoticeWindow'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__web_box', '__prev_pos', '__popup_event_flag_value', '__is_not_show_checked', '__checkbox', '__check_image', '__interface', '__title_bar', '__title_name', '__url', '__is_hide_when_quest_open', '__game_button_window')}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'm2netm2g', 'playerm2g2', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPopupNotice'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
