{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/privatesearch/private_checkboxImg.sub'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Buy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HidePageButton'},
                     {'args': ['self', 'n'], 'defaults': [], 'name': 'NumberToMoneyString'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuyAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuyCloseEvent'},
                     {'args': ['self', 'Masksubtypenumber'], 'defaults': [], 'name': 'OnChangeItemSubTypeSlot'},
                     {'args': ['self', 'Masktypenumber'], 'defaults': [], 'name': 'OnChangeItemTypeSlot'},
                     {'args': ['self', 'jobnumber'], 'defaults': [], 'name': 'OnChangeJobSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'iscash'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': 'Pagebutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Search'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'maxsize', 'page'], 'defaults': [], 'name': 'ShowPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearItemSlotButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeResultSlot'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': '__SelectItem'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SelectItemSlotButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearEffectEtc'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearPagebuttoncolor'},
                     {'args': ['self'], 'defaults': [], 'name': 'firstprevbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'lastnextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'nextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'prevbutton'}],
            'import': [],
            'var': [{'name': 'ARMOR_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'R\xfcstungen', 1: 'Helme', 2: 'Schilde'}},
                    {'name': 'CLICK_LIMIT_TIME', 'type': 'int', 'value': 3},
                    {'name': 'COSTUMES_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Waffenskins', 1: 'Kost\xfcme', 2: 'Frisuren', 3: 'Schulterb\xe4nder', 4: 'Sonstiges'}},
                    {'name': 'DRAGON_STONE_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Diamant', 1: 'Rubin', 2: 'Jade', 3: 'Saphir', 4: 'Granat', 5: 'Onyx', 6: 'Sonstiges'}},
                    {'name': 'ETC_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Truhen | Boxen', 1: 'Hochzeit', 2: 'Eventitems', 3: 'Seelenbindung', 4: 'Kriegskunstb\xfccher', 5: 'Verwandlungskugeln', 6: 'Trankherstellung', 7: 'Sonstiges'}},
                    {'name': 'FISHING_PICK_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Angelruten', 1: 'Spitzhacken', 2: 'Fische', 3: 'Erze', 4: 'Sonstiges'}},
                    {'name': 'ITEM_MASK_MASK_SUBTYPE_DICS',
                     'type': 'dict',
                     'value': {1: {0: 'Mounts', 1: 'Pets', 2: 'Levelbare Pets', 3: 'Pet-Eier'},
                               2: {0: {0: 'Einhandwaffen', 3: 'Zweihandwaffen'}, 1: {0: 'Einhandwaffen', 1: 'Dolche', 2: 'B\xf6gen', 8: 'Pfeile', 9: 'K\xf6cher'}, 2: {0: 'Einhandwaffen'}, 3: {4: 'Glocken', 6: 'F\xe4cher'}, 4: {5: 'Klauen'}},
                               3: {0: 'R\xfcstungen', 1: 'Helme', 2: 'Schilde'},
                               4: {0: 'Armb\xe4nder', 1: 'Schuhe', 2: 'Halsketten', 3: 'Ohrringe', 4: 'G\xfcrtel'},
                               5: {0: 'Materialien', 1: 'Geiststeine', 2: 'Sonstiges'},
                               6: {0: 'Verbrauchsg\xfcter', 1: 'Haarfarben', 2: 'Sonstiges'},
                               7: {0: 'Angelruten', 1: 'Spitzhacken', 2: 'Fische', 3: 'Erze', 4: 'Sonstiges'},
                               8: {0: 'Diamant', 1: 'Rubin', 2: 'Jade', 3: 'Saphir', 4: 'Granat', 5: 'Onyx', 6: 'Sonstiges'},
                               9: {0: 'Waffenskins', 1: 'Kost\xfcme', 2: 'Frisuren', 3: 'Schulterb\xe4nder', 4: 'Sonstiges'},
                               10: {0: 'Konter | Boost', 1: 'Fertigkeitsb\xfccher', 2: 'B\xfccher des Vergessens', 3: 'Sonstiges'},
                               11: {0: 'Konsumg\xfcter', 1: 'Sonstiges'},
                               12: {0: 'Truhen | Boxen', 1: 'Hochzeit', 2: 'Eventitems', 3: 'Seelenbindung', 4: 'Kriegskunstb\xfccher', 5: 'Verwandlungskugeln', 6: 'Trankherstellung', 7: 'Sonstiges'}}},
                    {'name': 'ITEM_MASK_TYPE_DIC', 'type': 'dict', 'value': {1: 'Mounts | Pets', 2: 'Waffen', 3: 'Ausr\xfcstungen', 4: 'Schmuck', 5: 'Verbesserungen', 6: 'Tr\xe4nke', 7: 'Angeln | Bergbau', 8: 'Drachensteinalchemie', 9: 'Kost\xfcme', 10: 'Fertigkeiten', 11: 'Sonderitems', 12: 'Sonstiges'}},
                    {'name': 'JEWELRY_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Armb\xe4nder', 1: 'Schuhe', 2: 'Halsketten', 3: 'Ohrringe', 4: 'G\xfcrtel'}},
                    {'name': 'JOB_MAX_COUNT', 'type': 'int', 'value': 5},
                    {'name': 'JOB_NAME_DIC', 'type': 'dict', 'value': {0: 'Krieger', 1: 'Ninja', 2: 'Sura', 3: 'Schamane', 4: 'Lykaner'}},
                    {'name': 'MAX_CHAR_LEVEL', 'type': 'int', 'value': 105},
                    {'name': 'MAX_LINE_COUNT', 'type': 'int', 'value': 10},
                    {'name': 'MOUNT_PET_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Mounts', 1: 'Pets', 2: 'Levelbare Pets', 3: 'Pet-Eier'}},
                    {'name': 'PAGEBUTTON_MAX_SIZE', 'type': 'int', 'value': 9},
                    {'name': 'PAGEBUTTON_NUMBER_SIZE', 'type': 'int', 'value': 5},
                    {'name': 'PAGEONE_MAX_SIZE', 'type': 'int', 'value': 50},
                    {'name': 'POTION_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Verbrauchsg\xfcter', 1: 'Haarfarben', 2: 'Sonstiges'}},
                    {'name': 'SKILL_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Konter | Boost', 1: 'Fertigkeitsb\xfccher', 2: 'B\xfccher des Vergessens', 3: 'Sonstiges'}},
                    {'name': 'SPECIAL_TITLE_COLOR', 'type': 'long', 'value': 4283317552L},
                    {'name': 'TUNING_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Materialien', 1: 'Geiststeine', 2: 'Sonstiges'}},
                    {'name': 'UNIQUE_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Konsumg\xfcter', 1: 'Sonstiges'}},
                    {'name': 'WEAPON_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: {0: 'Einhandwaffen', 3: 'Zweihandwaffen'}, 1: {0: 'Einhandwaffen', 1: 'Dolche', 2: 'B\xf6gen', 8: 'Pfeile', 9: 'K\xf6cher'}, 2: {0: 'Einhandwaffen'}, 3: {4: 'Glocken', 6: 'F\xe4cher'}, 4: {5: 'Klauen'}}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopSeachWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'ActionTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'}, {'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': 'Up'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'MouseReflector'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['shop', 'uiCommon', 'grp', '__builtin__', 'chatm2g', 'app', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'background', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
