{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/privatesearch/private_checkboxImg.sub'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Buy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HidePageButton'},
                     {'args': ['self', 'n'], 'defaults': [], 'name': 'NumberToMoneyString'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuyAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuyCloseEvent'},
                     {'args': ['self', 'Masksubtypenumber'], 'defaults': [], 'name': 'OnChangeItemSubTypeSlot'},
                     {'args': ['self', 'Masktypenumber'], 'defaults': [], 'name': 'OnChangeItemTypeSlot'},
                     {'args': ['self', 'jobnumber'], 'defaults': [], 'name': 'OnChangeJobSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'iscash'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': 'Pagebutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Search'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'maxsize', 'page'], 'defaults': [], 'name': 'ShowPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearItemSlotButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeResultSlot'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': '__SelectItem'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SelectItemSlotButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearEffectEtc'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearPagebuttoncolor'},
                     {'args': ['self'], 'defaults': [], 'name': 'firstprevbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'lastnextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'nextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'prevbutton'}],
            'import': [],
            'var': [{'name': 'CLICK_LIMIT_TIME', 'type': 'int', 'value': 3},
                    {'name': 'MAX_CHAR_LEVEL', 'type': 'int', 'value': 105},
                    {'name': 'MAX_LINE_COUNT', 'type': 'int', 'value': 10},
                    {'name': 'PAGEBUTTON_MAX_SIZE', 'type': 'int', 'value': 9},
                    {'name': 'PAGEBUTTON_NUMBER_SIZE', 'type': 'int', 'value': 5},
                    {'name': 'PAGEONE_MAX_SIZE', 'type': 'int', 'value': 50},
                    {'name': 'SPECIAL_TITLE_COLOR', 'type': 'long', 'value': 4283317552L},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopSeachWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'ActionTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'}, {'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': 'Up'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'MouseReflector'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['shop', 'uiCommon', 'grp', '__builtin__', 'chatm2g', 'app', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'background', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
