{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'flag'], 'defaults': [], 'name': 'SetCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y', 'event', 'filename'], 'defaults': ['d:/ymir work/ui/privatesearch/private_checkboxImg.sub'], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'CheckBox'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Buy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HidePageButton'},
                     {'args': ['self', 'n'], 'defaults': [], 'name': 'NumberToMoneyString'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuyAcceptEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuyCloseEvent'},
                     {'args': ['self', 'Masksubtypenumber'], 'defaults': [], 'name': 'OnChangeItemSubTypeSlot'},
                     {'args': ['self', 'Masktypenumber'], 'defaults': [], 'name': 'OnChangeItemTypeSlot'},
                     {'args': ['self', 'jobnumber'], 'defaults': [], 'name': 'OnChangeJobSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'iscash'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInToolTip'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverOutToolTip'},
                     {'args': ['self', 'number'], 'defaults': [], 'name': 'Pagebutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Search'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'maxsize', 'page'], 'defaults': [], 'name': 'ShowPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearItemSlotButtonList'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeResultSlot'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': '__SelectItem'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SelectItemSlotButtonList'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearEffectEtc'},
                     {'args': ['self'], 'defaults': [], 'name': 'clearPagebuttoncolor'},
                     {'args': ['self'], 'defaults': [], 'name': 'firstprevbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'lastnextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'nextbutton'},
                     {'args': ['self'], 'defaults': [], 'name': 'prevbutton'}],
            'import': [],
            'var': [{'name': 'ARMOR_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'V\xe9rtek', 1: 'Sisakok', 2: 'Pajzsok'}},
                    {'name': 'CLICK_LIMIT_TIME', 'type': 'int', 'value': 3},
                    {'name': 'COSTUMES_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Fegyver-kin\xe9zetek', 1: '\xd6lt\xf6z\xe9kek', 2: 'Frizur\xe1k', 3: 'V\xe1llp\xe1ntok', 4: 'Egy\xe9b'}},
                    {'name': 'DRAGON_STONE_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Gy\xe9m\xe1nt', 1: 'Rubin', 2: 'J\xe1de', 3: 'Zaf\xedr', 4: 'Gr\xe1n\xe1t', 5: '\xd3nix', 6: 'Egy\xe9b'}},
                    {'name': 'ETC_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'L\xe1d\xe1k | Dobozok', 1: 'H\xe1zass\xe1g', 2: 'Esem\xe9nyt\xe1rgyak', 3: 'L\xe9lekhez k\xf6t\xe9s', 4: 'Harcm\xfbv\xe9szeti k\xf6nyvek', 5: '\xc1tv\xe1ltoztat\xf3 g\xf6mb\xf6k', 6: 'B\xe1jital-k\xe9sz\xedt\xe9s', 7: 'Egy\xe9b'}},
                    {'name': 'FISHING_PICK_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Horg\xe1szbotok', 1: 'Cs\xe1k\xe1nyok', 2: 'Hal', 3: '\xc9rcek', 4: 'Egy\xe9b'}},
                    {'name': 'ITEM_MASK_MASK_SUBTYPE_DICS',
                     'type': 'dict',
                     'value': {1: {0: 'H\xe1tasok', 1: 'H\xe1zikedvencek', 2: 'Nevelhet\xf5 h\xe1zikedvencek', 3: 'H\xe1zikedvenc toj\xe1sok'},
                               2: {0: {0: 'Egykezes fegyverek', 3: 'K\xe9tkezes fegyverek'}, 1: {0: 'Egykezes fegyverek', 1: 'T\xf5r\xf6k', 2: '\xcdjak', 8: 'Nyilak', 9: 'Tegezek'}, 2: {0: 'Egykezes fegyverek'}, 3: {4: 'Harangok', 6: 'Legyez\xf5k'}, 4: {5: 'Karmok'}},
                               3: {0: 'V\xe9rtek', 1: 'Sisakok', 2: 'Pajzsok'},
                               4: {0: 'Kark\xf6t\xf5k', 1: 'Cip\xf5k', 2: 'Nyakl\xe1ncok', 3: 'F\xfclbeval\xf3k', 4: '\xd6vek'},
                               5: {0: 'Anyagok', 1: 'Szellemk\xf6vek', 2: 'Egy\xe9b'},
                               6: {0: 'Kell\xe9kek', 1: 'Hajfest\xe9kek', 2: 'Egy\xe9b'},
                               7: {0: 'Horg\xe1szbotok', 1: 'Cs\xe1k\xe1nyok', 2: 'Hal', 3: '\xc9rcek', 4: 'Egy\xe9b'},
                               8: {0: 'Gy\xe9m\xe1nt', 1: 'Rubin', 2: 'J\xe1de', 3: 'Zaf\xedr', 4: 'Gr\xe1n\xe1t', 5: '\xd3nix', 6: 'Egy\xe9b'},
                               9: {0: 'Fegyver-kin\xe9zetek', 1: '\xd6lt\xf6z\xe9kek', 2: 'Frizur\xe1k', 3: 'V\xe1llp\xe1ntok', 4: 'Egy\xe9b'},
                               10: {0: 'Cs\xf6kkent\xf5 | Fokoz\xf3', 1: 'K\xe9szs\xe9gk\xf6nyvek', 2: 'Feled\xe9s k\xf6nyvek', 3: 'Egy\xe9b'},
                               11: {0: 'Kell\xe9kek', 1: 'Egy\xe9b'},
                               12: {0: 'L\xe1d\xe1k | Dobozok', 1: 'H\xe1zass\xe1g', 2: 'Esem\xe9nyt\xe1rgyak', 3: 'L\xe9lekhez k\xf6t\xe9s', 4: 'Harcm\xfbv\xe9szeti k\xf6nyvek', 5: '\xc1tv\xe1ltoztat\xf3 g\xf6mb\xf6k', 6: 'B\xe1jital-k\xe9sz\xedt\xe9s', 7: 'Egy\xe9b'}}},
                    {'name': 'ITEM_MASK_TYPE_DIC',
                     'type': 'dict',
                     'value': {1: 'H\xe1tasok | H\xe1zikedvencek',
                               2: 'Fegyverek',
                               3: 'Felszerel\xe9s',
                               4: '\xc9kszer',
                               5: 'Fejleszt\xe9sek',
                               6: 'Italok',
                               7: 'Horg\xe1szat | B\xe1ny\xe1szat',
                               8: 'S\xe1rk\xe1nyk\xf5-alk\xedmia',
                               9: '\xd6lt\xf6z\xe9kek',
                               10: 'K\xe9szs\xe9gek',
                               11: 'K\xfcl\xf6nleges t\xe1rgyak',
                               12: 'Egy\xe9b'}},
                    {'name': 'JEWELRY_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Kark\xf6t\xf5k', 1: 'Cip\xf5k', 2: 'Nyakl\xe1ncok', 3: 'F\xfclbeval\xf3k', 4: '\xd6vek'}},
                    {'name': 'JOB_MAX_COUNT', 'type': 'int', 'value': 5},
                    {'name': 'JOB_NAME_DIC', 'type': 'dict', 'value': {0: 'Harcos', 1: 'Nindzsa', 2: 'Sura', 3: 'S\xe1m\xe1n', 4: 'V\xe9rfarkas'}},
                    {'name': 'MAX_CHAR_LEVEL', 'type': 'int', 'value': 105},
                    {'name': 'MAX_LINE_COUNT', 'type': 'int', 'value': 10},
                    {'name': 'MOUNT_PET_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'H\xe1tasok', 1: 'H\xe1zikedvencek', 2: 'Nevelhet\xf5 h\xe1zikedvencek', 3: 'H\xe1zikedvenc toj\xe1sok'}},
                    {'name': 'PAGEBUTTON_MAX_SIZE', 'type': 'int', 'value': 9},
                    {'name': 'PAGEBUTTON_NUMBER_SIZE', 'type': 'int', 'value': 5},
                    {'name': 'PAGEONE_MAX_SIZE', 'type': 'int', 'value': 50},
                    {'name': 'POTION_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Kell\xe9kek', 1: 'Hajfest\xe9kek', 2: 'Egy\xe9b'}},
                    {'name': 'SKILL_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Cs\xf6kkent\xf5 | Fokoz\xf3', 1: 'K\xe9szs\xe9gk\xf6nyvek', 2: 'Feled\xe9s k\xf6nyvek', 3: 'Egy\xe9b'}},
                    {'name': 'SPECIAL_TITLE_COLOR', 'type': 'long', 'value': 4283317552L},
                    {'name': 'TUNING_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Anyagok', 1: 'Szellemk\xf6vek', 2: 'Egy\xe9b'}},
                    {'name': 'UNIQUE_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: 'Kell\xe9kek', 1: 'Egy\xe9b'}},
                    {'name': 'WEAPON_MASK_SUBTYPE_DIC', 'type': 'dict', 'value': {0: {0: 'Egykezes fegyverek', 3: 'K\xe9tkezes fegyverek'}, 1: {0: 'Egykezes fegyverek', 1: 'T\xf5r\xf6k', 2: '\xcdjak', 8: 'Nyilak', 9: 'Tegezek'}, 2: {0: 'Egykezes fegyverek'}, 3: {4: 'Harangok', 6: 'Legyez\xf5k'}, 4: {5: 'Karmok'}}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopSeachWindow'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Disable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'},
                     {'args': ['self', 'event', 'arg'], 'defaults': [], 'name': 'SetEvent'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent', 'x', 'y'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'ActionTextSlot'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Down'}, {'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': 'Up'}, {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__qualname__', 'type': 'str', 'value': 'MouseReflector'}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['shop', 'uiCommon', 'grp', '__builtin__', 'chatm2g', 'app', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'background', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiPrivateShopSearch'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
