{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'vid', 'text'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopBuilder'}, {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopAdvertisementBoard'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptInputPrice'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelInputPrice'},
                     {'args': ['self', 'slotIndex', 'type'], 'defaults': [1], 'name': 'CantTradableItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'winType', 'SlotPos'], 'defaults': [], 'name': 'GetItemDataSocketValue'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnOk'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'OnSelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'OnSelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'title'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrvShopTabRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'type', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'bCashItem'], 'defaults': [], 'name': 'SetIsCashItem'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetPrivateShopPage'},
                     {'args': ['self', 'tabCnt'], 'defaults': [], 'name': 'SetTabCount'},
                     {'args': ['self', 'i'], 'defaults': [], 'name': '__GetRealIndex'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetDefaultShopDecoPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMyShopDecoPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopBuilder'}, {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopBuilder'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'vid', 'text'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__CalcFontColor'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopBuilder'}, {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopTitleBar'}]}],
 'func': [{'args': [], 'defaults': [], 'name': 'Clear'},
          {'args': ['vid'], 'defaults': [], 'name': 'DeleteADBoard'},
          {'args': ['itemVNum'], 'defaults': [], 'name': 'GetPrivateShopItemCheque'},
          {'args': ['itemVNum'], 'defaults': [], 'name': 'GetPrivateShopItemPrice'},
          {'args': [], 'defaults': [], 'name': 'IsBuildingPrivateShop'},
          {'args': [], 'defaults': [], 'name': 'IsPrivateShopItemPriceList'},
          {'args': ['itemVNum', 'itemPrice', 'itemCheque'], 'defaults': [], 'name': 'SetPrivateShopItemPrice'},
          {'args': [], 'defaults': [], 'name': 'UpdateADBoard'}],
 'import': ['shop', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'systemSetting', 'chr', 'mouseModule', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'item', 'ui'],
 'var': [{'name': 'INVENTORY_PAGE_SIZE', 'type': 'int', 'value': 45},
         {'name': 'PRIVATE_SHOP_WON', 'type': 'int', 'value': 1},
         {'name': 'PRIVATE_SHOP_YANG', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiPrivateShopBuilder'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'g_isBuildingPrivateShop', 'type': 'bool', 'value': False},
         {'name': 'g_itemPriceDict', 'type': 'dict', 'value': {}},
         {'name': 'g_privateShopAdvertisementBoardDict',
          'type': 'dict',
          'value': {53479: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29C30>,
                    57835: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C66890>,
                    61622: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C837F0>,
                    67809: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83370>,
                    73677: <uiPrivateShopBuilder.PrivateShopTitleBar object at 0x26C83670>,
                    85845: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C97550>,
                    93884: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C97D70>,
                    101746: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83FF0>,
                    108018: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C97130>,
                    125327: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29190>,
                    157043: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C3E070>,
                    163748: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29AB0>,
                    169258: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C66330>,
                    174109: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29530>,
                    352195: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C97ED0>,
                    370075: <uiPrivateShopBuilder.PrivateShopTitleBar object at 0x26C97810>,
                    379780: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29ED0>,
                    394683: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83390>,
                    396874: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29810>,
                    411743: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83510>,
                    432075: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83690>,
                    439083: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C97A90>,
                    457656: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83FD0>,
                    459780: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29830>,
                    461548: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29C10>,
                    462339: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29030>,
                    478296: <uiPrivateShopBuilder.PrivateShopTitleBar object at 0x26C66610>,
                    480960: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C973F0>,
                    481255: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C973D0>,
                    484305: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C29690>,
                    487144: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C97C10>,
                    493440: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C7BAB0>,
                    493945: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C977F0>,
                    494267: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C7BAD0>,
                    498011: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C66070>,
                    503456: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C66090>,
                    505065: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C665F0>,
                    505591: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C83A70>,
                    510059: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x26C66490>}}]}
