{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'vid', 'text'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopBuilder'}, {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopAdvertisementBoard'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptInputPrice'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelInputPrice'},
                     {'args': ['self', 'slotIndex', 'type'], 'defaults': [1], 'name': 'CantTradableItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'winType', 'SlotPos'], 'defaults': [], 'name': 'GetItemDataSocketValue'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnOk'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OnOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'OnSelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'OnSelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'title'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrvShopTabRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'type', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self', 'bCashItem'], 'defaults': [], 'name': 'SetIsCashItem'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'page'], 'defaults': [], 'name': 'SetPrivateShopPage'},
                     {'args': ['self', 'tabCnt'], 'defaults': [], 'name': 'SetTabCount'},
                     {'args': ['self', 'i'], 'defaults': [], 'name': '__GetRealIndex'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetDefaultShopDecoPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetMyShopDecoPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopBuilder'}, {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopBuilder'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'vid', 'text'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__CalcFontColor'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiPrivateShopBuilder'}, {'name': '__qualname__', 'type': 'str', 'value': 'PrivateShopTitleBar'}]}],
 'func': [{'args': [], 'defaults': [], 'name': 'Clear'},
          {'args': ['vid'], 'defaults': [], 'name': 'DeleteADBoard'},
          {'args': ['itemVNum'], 'defaults': [], 'name': 'GetPrivateShopItemCheque'},
          {'args': ['itemVNum'], 'defaults': [], 'name': 'GetPrivateShopItemPrice'},
          {'args': [], 'defaults': [], 'name': 'IsBuildingPrivateShop'},
          {'args': [], 'defaults': [], 'name': 'IsPrivateShopItemPriceList'},
          {'args': ['itemVNum', 'itemPrice', 'itemCheque'], 'defaults': [], 'name': 'SetPrivateShopItemPrice'},
          {'args': [], 'defaults': [], 'name': 'UpdateADBoard'}],
 'import': ['shop', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'systemSetting', 'chr', 'mouseModule', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'item', 'ui'],
 'var': [{'name': 'INVENTORY_PAGE_SIZE', 'type': 'int', 'value': 45},
         {'name': 'PRIVATE_SHOP_WON', 'type': 'int', 'value': 1},
         {'name': 'PRIVATE_SHOP_YANG', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiPrivateShopBuilder'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'g_isBuildingPrivateShop', 'type': 'bool', 'value': False},
         {'name': 'g_itemPriceDict', 'type': 'dict', 'value': {}},
         {'name': 'g_privateShopAdvertisementBoardDict',
          'type': 'dict',
          'value': {44200: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD590>,
                    117726: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E12570>,
                    129495: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E12AF0>,
                    132581: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E25090>,
                    408504: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD9B0>,
                    705862: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBC7B0>,
                    706498: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23966950>,
                    721747: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCDB10>,
                    965566: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x08D70310>,
                    968995: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBC910>,
                    985610: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD2D0>,
                    1044092: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBC510>,
                    1126996: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD850>,
                    1164393: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E12F10>,
                    1188309: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBCE90>,
                    1207440: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E12C50>,
                    1211942: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E126D0>,
                    1212670: <uiPrivateShopBuilder.PrivateShopTitleBar object at 0x23E12430>,
                    1215282: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E25350>,
                    1219120: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E12DB0>,
                    1224392: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBC390>,
                    1229756: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD6F0>,
                    1242954: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBCFF0>,
                    1271659: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23E12830>,
                    1297773: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CDFAD0>,
                    1311997: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD170>,
                    1326330: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBCA70>,
                    1331091: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBCBD0>,
                    1335696: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CBCD30>,
                    1336344: <uiPrivateShopBuilder.PrivateShopAdvertisementBoard object at 0x23CCD430>}}]}
