{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'event_type', 'slot'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self', 'event_type'], 'defaults': [], 'name': 'MyEventProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'type', 'category'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeRankingUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotCoverUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotUI'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetUIColumnName'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'M2JOBLIST', 'type': 'dict', 'value': {0: 'Harcos', 1: 'Nindzsa', 2: 'Sura', 3: 'S\xe1m\xe1n', 4: 'V\xe9rfarkas'}},
                    {'name': 'PARTY_RANK_BOARD_NAME',
                     'type': 'dict',
                     'value': {0: ('\xd6sszes\xedtett rangsor', 'Id\xf5', 'Tagok'),
                               1: ('Heti rangsor', 'Id\xf5', 'Tagok'),
                               2: ('El\xf5z\xf5 rangsor', 'Id\xf5', 'Tagok'),
                               3: ('Zi \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               4: ('Chou \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               5: ('Yin \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               6: ('Mao \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               7: ('Chen \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               8: ('Si \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               9: ('Wu \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               10: ('Wei \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               11: ('Shen \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               12: ('You \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               13: ('Xu \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               14: ('Hai \xd5rz\xf5 ranglista', 'Szint', 'Id\xf5'),
                               15: ('Haj\xf3 megv\xe9d\xe9se', 'Id\xf5', 'Tagok')}},
                    {'name': 'RANK_1', 'type': 'int', 'value': 0},
                    {'name': 'RANK_2', 'type': 'int', 'value': 1},
                    {'name': 'RANK_3', 'type': 'int', 'value': 2},
                    {'name': 'SOLO_RANK_BOARD_NAME', 'type': 'dict', 'value': {0: ('', '', ''), 1: ('', '', ''), 2: ('', '', ''), 3: ('', '', ''), 7: ('Battle Royale', 'Gy\xf5zelmek', '')}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRankingBoard'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RankingBoardWindow'}]}],
 'func': [],
 'import': ['ranking', 'uiToolTip', '__builtin__', 'app', 'playerm2g2', 'ui', 'mouseModule', 'colorInfo', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRankingBoard'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
