{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'event_type', 'slot'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self', 'event_type'], 'defaults': [], 'name': 'MyEventProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'type', 'category'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeRankingUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotCoverUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotUI'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetUIColumnName'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'M2JOBLIST', 'type': 'dict', 'value': {0: 'Guerreiro', 1: 'Ninja', 2: 'Shura', 3: 'Shaman', 4: 'Lycan'}},
                    {'name': 'PARTY_RANK_BOARD_NAME',
                     'type': 'dict',
                     'value': {0: ("Meley's Lair Party (Total)", 'Clear Time', 'Member'),
                               1: ("Meley's Lair Party (now)", 'Clear Time', 'Member'),
                               2: ("Meley's Lair Party (Past)", 'Clear Time', 'Member'),
                               3: ('Ranking da masmorra do Guardi\xe3o Zi', 'Andar', 'Tempo'),
                               4: ('Ranking da masmorra do Guardi\xe3o Chou', 'Andar', 'Tempo'),
                               5: ('Ranking da masmorra do Guardi\xe3o Yin', 'Andar', 'Tempo'),
                               6: ('Ranking da masmorra da Guardi\xe3 Mao', 'Andar', 'Tempo'),
                               7: ('Ranking da masmorra do Guardi\xe3o Chen', 'Andar', 'Tempo'),
                               8: ('Ranking da masmorra da Guardi\xe3 Si', 'Andar', 'Tempo'),
                               9: ('Ranking da masmorra do Guardi\xe3o Wu', 'Andar', 'Tempo'),
                               10: ('Ranking da masmorra do Guardi\xe3o Wei', 'Andar', 'Tempo'),
                               11: ('Ranking da masmorra do Guardi\xe3o Shen', 'Andar', 'Tempo'),
                               12: ('Ranking da masmorra do Guardi\xe3o Yu', 'Andar', 'Tempo'),
                               13: ('Ranking da masmorra do Guardi\xe3o Xu', 'Andar', 'Tempo'),
                               14: ('Ranking da masmorra do Guardi\xe3o Hai', 'Andar', 'Tempo'),
                               15: ('Onda de Defesa', 'Tempo', 'Member')}},
                    {'name': 'RANK_1', 'type': 'int', 'value': 0},
                    {'name': 'RANK_2', 'type': 'int', 'value': 1},
                    {'name': 'RANK_3', 'type': 'int', 'value': 2},
                    {'name': 'SOLO_RANK_BOARD_NAME', 'type': 'dict', 'value': {0: ('', '', ''), 1: ('', '', ''), 2: ('', '', ''), 3: ('', '', ''), 6: ('Battle Royale', 'Vit\xf3rias', '')}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRankingBoard'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RankingBoardWindow'}]}],
 'func': [],
 'import': ['ranking', 'uiToolTip', '__builtin__', 'app', 'playerm2g2', 'ui', 'mouseModule', 'colorInfo', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRankingBoard'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
