{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'IsRamadanEventEnd', 'type': 'classmethod', 'value': <classmethod object at 0x2E13DEB0>},
                    {'name': 'RamadanEventGetItemMessage', 'type': 'classmethod', 'value': <classmethod object at 0x2E13DDB0>},
                    {'name': 'RamadanEventMessage', 'type': 'classmethod', 'value': <classmethod object at 0x2E13D470>},
                    {'name': '_RamadanEventUtil__GET_ITEM_MESSAGE_TYPE', 'type': 'dict', 'value': {0: 0, 1: 1}},
                    {'name': '_RamadanEventUtil__GET_ITEM_MESSAGE_TYPE__RAMADAN_EVENT_LOCA', 'type': 'member_descriptor', 'value': <member '_RamadanEventUtil__GET_ITEM_MESSAGE_TYPE__RAMADAN_EVENT_LOCA' of 'RamadanEventUtil' objects>},
                    {'name': '_RamadanEventUtil__RAMADAN_EVENT_LOCA',
                     'type': 'dict',
                     'value': {0: 'Szerezt\xe9l 1 Kenyeret.',
                               1: 'Szerezt\xe9l 1 \xc1ld\xe1s gy\xfcm\xf6lcs\xf6t.',
                               2: 'M\xe1r a maxim\xe1lis mennyis\xe9g\xfb Keny\xe9r van n\xe1lad.',
                               3: 'M\xe1r a maxim\xe1lis mennyis\xe9g\xfb \xc1ld\xe1s gy\xfcm\xf6lcs van n\xe1lad.',
                               4: 'Sz\xfcks\xe9ged van tov\xe1bbi 10 Keny\xe9rre.'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRamadanEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RamadanEventUtil'},
                    {'name': '__slots__', 'type': 'str', 'value': '__GET_ITEM_MESSAGE_TYPE__RAMADAN_EVENT_LOCA'}]}],
 'func': [],
 'import': ['event', '__builtin__', 'chatm2g', 'app', 'item', 'playerm2g2', 'ui', 'uiScriptLocale', 'ingameEventSystem', 'localeInfo', 'uiMiniGame'],
 'var': [{'name': 'RamadanEvent', 'type': 'ABCMeta', 'value': <class 'uiRamadanEvent.RamadanEvent'>},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiRamadanEvent'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
