{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'event_type', 'slot'], 'defaults': [], 'name': 'EventProgress'},
                     {'args': ['self', 'event_type'], 'defaults': [], 'name': 'MyEventProgress'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'type', 'category'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'title', 'descList'], 'defaults': [], 'name': '__CreateGameTypeToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeRankingUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotCoverUI'},
                     {'args': ['self', 'yPos'], 'defaults': [], 'name': '__MakeResultSlotUI'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetUIColumnName'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'M2JOBLIST', 'type': 'dict', 'value': {0: 'Krieger', 1: 'Ninja', 2: 'Sura', 3: 'Schamane', 4: 'Lykaner'}},
                    {'name': 'PARTY_RANK_BOARD_NAME', 'type': 'dict', 'value': {0: ('', 'Ebene', 'Zeit')}},
                    {'name': 'RANK_1', 'type': 'int', 'value': 0},
                    {'name': 'RANK_2', 'type': 'int', 'value': 1},
                    {'name': 'RANK_3', 'type': 'int', 'value': 2},
                    {'name': 'SOLO_RANK_BOARD_NAME', 'type': 'dict', 'value': {0: ('', '', ''), 1: ('', '', '')}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRankingBoard'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RankingBoardWindow'}]}],
 'func': [],
 'import': ['ranking', 'uiToolTip', '__builtin__', 'app', 'ui', 'colorInfo', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRankingBoard'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
