{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_DescriptionBox__desc_index', 'type': 'member_descriptor', 'value': <member '_DescriptionBox__desc_index' of 'DescriptionBox' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiRamadanEvent'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'RamadanEvent.DescriptionBox'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__desc_index',)}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'InGameEventProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevDescriptionPage'},
                     {'args': ['self', 'flag_type', 'count'], 'defaults': [], 'name': '__RamadanEventUpdateItemCount'},
                     {'args': ['self', 'vnum'], 'defaults': [], 'name': '__SlotOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__SlotOverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESC_LINE_LIMIT_COUNT', 'type': 'int', 'value': 10},
                    {'name': '_RamadanEvent__board', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__board' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__desc_board', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__desc_board' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__desc_index', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__desc_index' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__desc_next_button', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__desc_next_button' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__desc_prev_button', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__desc_prev_button' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__desc_y', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__desc_y' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__description_box', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__description_box' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__is_loaded', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__is_loaded' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__item_count_text_list__item_count', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__item_count_text_list__item_count' of 'RamadanEvent' objects>},
                    {'name': '_RamadanEvent__tooltip', 'type': 'member_descriptor', 'value': <member '_RamadanEvent__tooltip' of 'RamadanEvent' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRamadanEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RamadanEvent'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__is_loaded', '__board', '__desc_board', '__desc_prev_button', '__desc_next_button', '__description_box', '__tooltip', '__desc_index', '__desc_y', '__item_count_text_list__item_count')}]},
           {'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'IsRamadanEventEnd', 'type': 'classmethod', 'value': <classmethod object at 0x0B5BD430>},
                    {'name': 'RamadanEventGetItemMessage', 'type': 'classmethod', 'value': <classmethod object at 0x0B5BD3F0>},
                    {'name': 'RamadanEventMessage', 'type': 'classmethod', 'value': <classmethod object at 0x0B5BD410>},
                    {'name': '_RamadanEventUtil__GET_ITEM_MESSAGE_TYPE', 'type': 'dict', 'value': {0: 0, 1: 1}},
                    {'name': '_RamadanEventUtil__GET_ITEM_MESSAGE_TYPE__RAMADAN_EVENT_LOCA', 'type': 'member_descriptor', 'value': <member '_RamadanEventUtil__GET_ITEM_MESSAGE_TYPE__RAMADAN_EVENT_LOCA' of 'RamadanEventUtil' objects>},
                    {'name': '_RamadanEventUtil__RAMADAN_EVENT_LOCA',
                     'type': 'dict',
                     'value': {0: 'Szerezt\xe9l 1 Kenyeret.',
                               1: 'Szerezt\xe9l 1 \xc1ld\xe1s gy\xfcm\xf6lcs\xf6t.',
                               2: 'M\xe1r a maxim\xe1lis mennyis\xe9g\xfb Keny\xe9r van n\xe1lad.',
                               3: 'M\xe1r a maxim\xe1lis mennyis\xe9g\xfb \xc1ld\xe1s gy\xfcm\xf6lcs van n\xe1lad.',
                               4: 'Sz\xfcks\xe9ged van tov\xe1bbi 10 Keny\xe9rre.'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRamadanEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RamadanEventUtil'},
                    {'name': '__slots__', 'type': 'str', 'value': '__GET_ITEM_MESSAGE_TYPE__RAMADAN_EVENT_LOCA'}]}],
 'func': [],
 'import': ['event', '__builtin__', 'chatm2g', 'app', 'item', 'playerm2g2', 'ui', 'uiScriptLocale', 'ingameEventSystem', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRamadanEvent'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
