{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self', 'mapidx'], 'defaults': [], 'name': 'OpenDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartHere'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartImmediately'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartTown'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CAN_IMMEDIATE_RESTART_ZONE', 'type': 'set', 'value': set([357])}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiRestart'}, {'name': '__qualname__', 'type': 'str', 'value': 'RestartDialog'}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'dbg', 'm2netm2g', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRestart'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
