{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'AcceptRestartHere'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAll'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self', 'map_index', 'dialog_type'], 'defaults': [0, 1], 'name': 'OpenDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartHere'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartImmediately'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartTown'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAll'},
                     {'args': ['self', 'map_index', 'dialog_type'], 'defaults': [], 'name': 'ShowDialogButton'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__GiveUpPopupDialogOpen'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__RestartHerePopupDialogOpen'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CAN_GIVEUP_RESTART_ZONE', 'type': 'list', 'value': [358]},
                    {'name': 'CAN_IMMEDIATE_RESTART_ZONE', 'type': 'list', 'value': [357]},
                    {'name': 'DEAD_DIALOG_GIVE_UP_POPUP_TEXT', 'type': 'dict', 'value': {402: 'A karaktered halott. \\nHamarosan a v\xe1rosba leszel teleport\xe1lva.'}},
                    {'name': 'ONLY_GIVEUP_POPUP_ZONE',
                     'type': 'dict',
                     'value': {360: 'Meg\xf6ltek az \xf6t szent\xe9ly csat\xe1j\xe1ban.\\nMost visszaker\xfclsz a faluba.',
                               378: 'Meghalt\xe1l. \\nVisszat\xe9rsz az Element\xe1lok birodalm\xe1b\xf3l!',
                               379: 'Meghalt\xe1l. \\nVisszat\xe9rsz az Element\xe1lok birodalm\xe1b\xf3l!',
                               380: 'Meghalt\xe1l. \\nVisszat\xe9rsz az Element\xe1lok birodalm\xe1b\xf3l!',
                               381: 'Meghalt\xe1l. \\nVisszat\xe9rsz az Element\xe1lok birodalm\xe1b\xf3l!',
                               387: 'Keser\xfb veres\xe9g! A kalandod itt v\xe9get \xe9r.',
                               400: 'A karaktered halott. \\nHamarosan a v\xe1rosba leszel teleport\xe1lva.'}},
                    {'name': 'ONLY_RESTART_HERE_ZONE_BUTTON_TEXT',
                     'type': 'dict',
                     'value': {404: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               405: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               406: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               407: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               408: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               409: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               410: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               411: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s',
                               412: 'V\xe9letlenszer\xfb \xfajra\xe9led\xe9s'}},
                    {'name': 'ONLY_RESTART_HERE_ZONE_POPUP_TEXT',
                     'type': 'dict',
                     'value': {404: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               405: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               406: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               407: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               408: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               409: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               410: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               411: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.',
                               412: 'Egy v\xe9letlenszer\xfb helyen \xe9ledsz \xfajra ezen a ter\xfcleten.'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRestart'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RestartDialog'}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'app', 'dbg', 'm2netm2g', 'playerm2g2', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRestart'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
