{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'scrollSlotIndex', 'itemSlotIndex'], 'defaults': [], 'name': 'GetRefineSuccessPercentage'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'scrollItemPos', 'targetItemPos'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRefine'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RefineDialog'},
                    {'name': 'makeSocketSuccessPercentage', 'type': 'tuple', 'value': (100, 33, 20, 15, 10, 5, 0)},
                    {'name': 'upgradeAccessorySuccessPercentage', 'type': 'tuple', 'value': (99, 88, 77, 66, 33, 33, 33, 33, 33)},
                    {'name': 'upgradeArmorSuccessPercentage', 'type': 'tuple', 'value': (99, 66, 33, 33, 33, 33, 33, 33, 33)},
                    {'name': 'upgradeStoneSuccessPercentage', 'type': 'tuple', 'value': (30, 29, 28, 27, 26, 25, 24, 23, 22)},
                    {'name': 'upgradeSuccessPercentage', 'type': 'tuple', 'value': (99, 66, 33, 33, 33, 33, 33, 33, 33)}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Accept'},
                     {'args': ['self', 'vnum', 'count'], 'defaults': [], 'name': 'AppendMaterial'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelRefine'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'targetItemPos', 'nextGradeItemVnum', 'cost', 'prob', 'type'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdateDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeItemImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__MakeThinBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiRefine'}, {'name': '__qualname__', 'type': 'str', 'value': 'RefineDialogNew'}]}],
 'func': [],
 'import': ['uiCommon', 'constInfo', 'uiToolTip', '__builtin__', 'app', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRefine'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
