{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAll'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self', 'mapidx'], 'defaults': [0], 'name': 'OpenDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartGiveUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartHere'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartImmediately'},
                     {'args': ['self'], 'defaults': [], 'name': 'RestartTown'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowAll'},
                     {'args': ['self', 'mapidx'], 'defaults': [], 'name': 'ShowDialogButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'CAN_GIVEUP_RESTART_ZONE', 'type': 'list', 'value': [358]},
                    {'name': 'CAN_IMMEDIATE_RESTART_ZONE', 'type': 'list', 'value': [357]},
                    {'name': 'ONLY_GIVEUP_POPUP_ZONE', 'type': 'dict', 'value': {360: 'Voc\xea foi derrotado na Guerra dos Santu\xe1rios!\\nSer\xe1 movido para a vila.'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiRestart'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'RestartDialog'}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'app', 'dbg', 'm2netm2g', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiRestart'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
