{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCancel'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseMessageDialog'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': 'OnNextFocus'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'old', 'new', 'newRe'], 'defaults': [], 'name': 'PasswordCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self', 'str', 'limit', 'pattern'], 'defaults': [], 'name': 'findPattern'}],
            'import': [],
            'var': [{'name': 'MIN_LEN', 'type': 'int', 'value': 3}, {'name': 'PATTERN_LIMIT', 'type': 'int', 'value': 3}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSafebox'}, {'name': '__qualname__', 'type': 'str', 'value': 'ChangePasswordDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CloseDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self', 'password'], 'defaults': [], 'name': 'IsPasswordAvailable'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAccept'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCancel'},
                     {'args': ['self', 'msg', 'event'], 'defaults': [], 'name': 'OpenPopupEvent'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': 'SetSendMessage'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'SetSendType'},
                     {'args': ['self', 'title'], 'defaults': [], 'name': 'SetTitle'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSafebox'}, {'name': '__qualname__', 'type': 'str', 'value': 'PasswordDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseMall'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshMall'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'SetTableSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'ShowWindow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'local'], 'defaults': [], 'name': '__LocalPosToGlobalPos'},
                     {'args': ['self', 'pageCount'], 'defaults': [], 'name': '__MakePageButton'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BOX_WIDTH', 'type': 'int', 'value': 176},
                    {'name': 'PAGE_TEXT', 'type': 'tuple', 'value': ('I', 'II', 'III', 'IV', 'V')},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSafebox'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MallWindow'}]},
           {'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'CantCheckInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'CommandCloseSafebox'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangePassword'},
                     {'args': ['self', 'money'], 'defaults': [], 'name': 'OnPickMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenPickMoneyDialog'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSafebox'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSafeboxMoney'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': 'SelectPage'},
                     {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'SetTableSize'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'size'], 'defaults': [], 'name': 'ShowWindow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'UseItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self', 'local'], 'defaults': [], 'name': '__LocalPosToGlobalPos'},
                     {'args': ['self', 'pageCount'], 'defaults': [], 'name': '__MakePageButton'},
                     {'args': ['self', 'slotNumber', 'itemVnum'], 'defaults': [], 'name': '__SetCollTimePetItemSlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BOX_WIDTH', 'type': 'int', 'value': 176}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSafebox'}, {'name': '__qualname__', 'type': 'str', 'value': 'SafeboxWindow'}]}],
 'func': [],
 'import': ['uiCommon', 'snd', '__builtin__', 'chatm2g', 'app', 'uiScriptLocale', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'safebox', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiSafebox'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
