{'class': [{'class': [],
            'func': [{'args': ['self', 'msg'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__Bind'},
                     {'args': ['self'], 'defaults': [], 'name': '__Load'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOK'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'parent'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSelectMusic'}, {'name': '__qualname__', 'type': 'str', 'value': 'PopupDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'GetText'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetSize'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__CreateTextLine'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSelectMusic'}, {'name': '__qualname__', 'type': 'str', 'value': 'Item'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SAFE_SetSelectEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__AppendFile'},
                     {'args': ['self', 'filter'], 'defaults': [], 'name': '__AppendFileList'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClearFileList'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateFileListBox'},
                     {'args': ['self'], 'defaults': [], 'name': '__Load'},
                     {'args': ['self'], 'defaults': [], 'name': '__Load_BindObject'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__Load_LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCancel'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnOK'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnRefresh'},
                     {'args': ['self', 'msg'], 'defaults': [], 'name': '__PopupMessage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshFileList'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSelectMusic'}, {'name': '__qualname__', 'type': 'str', 'value': 'FileListDialog'}]}],
 'func': [],
 'import': ['__builtin__', 'app', 'ui', 'uiScriptLocale', 'localeInfo'],
 'var': [{'name': 'DEFAULT_THEMA', 'type': 'str', 'value': 'Metin2 Standard music'},
         {'name': 'FILE_NAME_LEN', 'type': 'int', 'value': 20},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiSelectMusic'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
