{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'answer', 'party_leader_vid', 'reward_time'], 'defaults': [], 'name': 'DungeonEnterRequestAnswer'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'SecretDungeonProcess'},
                     {'args': ['self', 'item_vid', 'answer'], 'defaults': [], 'name': 'SendCreateDungeonRequestAnswer'},
                     {'args': ['self', 'answer', 'party_leader_vid', 'reward_time'], 'defaults': [], 'name': 'SendDungeonEnterReRequestAnswer'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__CreateDungeonProcess'},
                     {'args': ['self', 'item_vid', 'remain_time'], 'defaults': [], 'name': '__CreateSecretDungeonDialog'},
                     {'args': ['self', 'party_leader_vid', 'reward_time'], 'defaults': [], 'name': '__DungeonEnterReRequestDialog'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': '__EnterDungeonProcess'},
                     {'args': ['self', 'party_leader_vid', 'reward_time'], 'defaults': [], 'name': '__SecretDungeonEnterDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSecretDungeon'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SecretDungeon'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__dungeon_create_dialog', '__dungeon_enter_question_dialog', '__dungeon_enter_re_question_dialog')}]}],
 'func': [],
 'import': ['uiCommon', '__builtin__', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiSecretDungeon'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
