{'class': [{'class': [],
            'func': [{'args': ['self', 'flag'], 'defaults': [], 'name': 'AnswerBuyItem'},
                     {'args': ['self', 'slotPos'], 'defaults': [], 'name': 'AskBuyItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'AskClosePrivateShop'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'CancelShopping'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'CantSellInvenItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'slotPos', 'count', 'itemtype'], 'defaults': [], 'name': 'CreateSecondConfirmQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'DropToInventory'},
                     {'args': ['self', 'slotPos'], 'defaults': [], 'name': 'GetIndexFromSlotPos'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self', 'slotPos', 'count', 'itemtype'], 'defaults': [], 'name': 'OnAcceptSellItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBuy'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'OnClickTabButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnClosePrivateShop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseSecondConfirmQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnDenySellItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressExitKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnSell'},
                     {'args': ['self', 'slotPos', 'count', 'itemtype'], 'defaults': [], 'name': 'OnSellItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'coin_type'], 'defaults': [], 'name': 'ResetUsablePoint'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'SellAttachedItem'},
                     {'args': ['self', 'pos', 'itemID', 'itemCount', 'itemPrice'], 'defaults': [], 'name': 'SetItemData'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'selected_shop_pos'], 'defaults': [], 'name': 'ShopToInventory'},
                     {'args': ['self', 'selectedSlotPos'], 'defaults': [], 'name': 'UnselectItemSlot'},
                     {'args': ['self', 'i'], 'defaults': [], 'name': '__GetRealIndex'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideBuySellButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideMiddleTabs'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideSmallTabs'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClosePopupDialog'},
                     {'args': ['self', 'coin_type'], 'defaults': [], 'name': '__RefreshSubBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetTabNames'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowBuySellButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowMiddleTabs'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowSmallTabs'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUY_QUESTION_DIALOG_MIN_YANG', 'type': 'int', 'value': 500000}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiShop'}, {'name': '__qualname__', 'type': 'str', 'value': 'ShopDialog'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiShop'}, {'name': '__qualname__', 'type': 'str', 'value': 'MallPageDialog'}]}],
 'func': [],
 'import': ['shop', 'chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'constInfo', 'item', 'mouseModule', 'localeInfo', 'uiCommon', 'snd', '__builtin__', 'wndMgr', 'ui'],
 'var': [{'name': 'BUY_BUTTON_BASE_X', 'type': 'int', 'value': 21},
         {'name': 'BUY_BUTTON_BASE_Y', 'type': 'int', 'value': 295},
         {'name': 'BUY_BUTTON_CENTER_X', 'type': 'int', 'value': 61},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiShop'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
