{'class': [{'class': [],
            'func': [{'args': ['self', 'idx'], 'defaults': [], 'name': 'ClearSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickAcceptButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'type'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'SetCanMouseEventSlot'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheckCantMouseEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__RangeCheck'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendClosePacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendCombinationPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendOpenPacket'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetLoca'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSkillBookCombination'}, {'name': '__qualname__', 'type': 'str', 'value': 'SkillBookCombinationWindow'}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'uiToolTip', 'mouseModule', 'uiScriptLocale', 'localeInfo', '__builtin__', 'types', 'item', 'ui'],
 'var': [{'name': 'FRAGMENT_COMBI_COMB', 'type': 'int', 'value': 5},
         {'name': 'FRAGMENT_COMBI_UI_CLOSE', 'type': 'int', 'value': 3},
         {'name': 'FRAGMENT_COMBI_UI_OPEN', 'type': 'int', 'value': 4},
         {'name': 'FRAGMENT_NEED_MONEY', 'type': 'int', 'value': 100000},
         {'name': 'INVENTORY_PAGE_SIZE', 'type': 'int', 'value': 45},
         {'name': 'SKILLBOOK_COMBINATION_TYPE_FRAGMENT', 'type': 'int', 'value': 2},
         {'name': 'SKILLBOOK_COMBINATION_TYPE_NONE', 'type': 'int', 'value': 0},
         {'name': 'SKILLBOOK_COMBINATION_TYPE_SKILLBOOK', 'type': 'int', 'value': 1},
         {'name': 'SKILLBOOK_COMBI_COMB', 'type': 'int', 'value': 2},
         {'name': 'SKILLBOOK_COMBI_UI_CLOSE', 'type': 'int', 'value': 0},
         {'name': 'SKILLBOOK_COMBI_UI_OPEN', 'type': 'int', 'value': 1},
         {'name': 'SKILLBOOK_NEED_MONEY', 'type': 'int', 'value': 1000000},
         {'name': 'SKILLBOOK_SLOT_MAX', 'type': 'int', 'value': 10},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiSkillBookCombination'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
