{'class': [{'class': [],
            'func': [{'args': ['self', 'idx'], 'defaults': [], 'name': 'ClearSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickAcceptButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'SelectEmptySlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'SelectItemSlot'},
                     {'args': ['self', 'idx'], 'defaults': [], 'name': 'SetCanMouseEventSlot'},
                     {'args': ['self', 'inven'], 'defaults': [], 'name': 'SetInven'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSkillBookCombination'}, {'name': '__qualname__', 'type': 'str', 'value': 'SkillBookCombinationWindow'}]}],
 'func': [],
 'import': ['__builtin__', 'chatm2g', 'uiToolTip', 'item', 'm2netm2g', 'playerm2g2', 'ui', 'mouseModule', 'app', 'localeInfo', 'types'],
 'var': [{'name': 'INVENTORY_PAGE_SIZE', 'type': 'int', 'value': 45},
         {'name': 'SKILLBOOK_COMBI_START', 'type': 'int', 'value': 2},
         {'name': 'SKILLBOOK_COMBI_UI_CLOSE', 'type': 'int', 'value': 0},
         {'name': 'SKILLBOOK_COMBI_UI_OPEN', 'type': 'int', 'value': 1},
         {'name': 'SKILLBOOK_SLOT_MAX', 'type': 'int', 'value': 10},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiSkillBookCombination'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
