{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'AppendChat', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF710>},
                    {'name': 'CommandProcess', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF7B0>},
                    {'name': 'GetSportsMatchWinTeamId', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF790>},
                    {'name': 'InitializeLoca', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF6F0>},
                    {'name': 'IsSportsMatchEventMatchBlock', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF770>},
                    {'name': 'IsSportsMatchEventOff', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF730>},
                    {'name': 'IsSportsMatchEventTimeEnd', 'type': 'classmethod', 'value': <classmethod object at 0x2CEDF750>},
                    {'name': '_SportsMatchUtil__SPORTS_MATCH_EVENT_LOCA',
                     'type': 'dict',
                     'value': {0: SPORTS_MATCH_WORLDCUP_EVENT_ON,
                               1: SPORTS_MATCH_WORLDCUP_EVENT_OFF,
                               2: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_RESULT_ITEM_FLAG_MAX,
                               3: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_INVENTORY_FULL_MSG,
                               4: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_COOLTIME_NOT_END_MSG,
                               5: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_APPOINT_ITEM_NOT_ENOUGH,
                               6: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_CHEER_ITEM_NOT_ENOUGH,
                               7: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_MIN_LEVEL_MSG,
                               8: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_TICKET_PIECE_ITEM_ADD,
                               9: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_TICKET_ITEM_ADD,
                               10: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_TICKET_ITEM_LACK,
                               11: SPORTS_MATCH_EVENT_WORLDCUP_CHAT_TYPE_CHEER_MAX,
                               12: SPORTS_MATCH_TICKET_COUNT_NOT_ENOUGH,
                               13: SPORTS_MATCH_PREDICT_GET_REWARD,
                               14: SPORTS_MATCH_EVENT_TIME_END,
                               15: SPORTS_MATCH_PREDICT_EVENT_OFF,
                               16: SPORTS_MATCH_PREDICT_ENABLE_REWARD}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSportsMatch'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SportsMatchUtil'},
                    {'name': '__slots__', 'type': 'str', 'value': '__SPORTS_MATCH_EVENT_LOCA'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '_DescriptionBox__desc_index', 'type': 'member_descriptor', 'value': <member '_DescriptionBox__desc_index' of 'DescriptionBox' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiSportsMatch'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'SportsMatchPredictWindow.DescriptionBox'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__desc_index',)}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsCheerCoolTimeEnd'},
                     {'args': ['self', 'is_appointed', 'cheer_count'], 'defaults': [], 'name': 'IsEnableAppoint'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsNetworkLock'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'PredictProcess'},
                     {'args': ['self', 'team_id', 'enable'], 'defaults': [], 'name': 'RefreshEnableGetRewardState'},
                     {'args': ['self', 'team_id'], 'defaults': [], 'name': 'SendCheerRequest'},
                     {'args': ['self'], 'defaults': [], 'name': 'SendGiveRewardRequest'},
                     {'args': ['self', 'is_lock'], 'defaults': [], 'name': 'SetNetworkLock'},
                     {'args': ['self', 'team_id', 'team_name'], 'defaults': [], 'name': 'ShowAppointPopupWindow'},
                     {'args': ['self', 'team_id'], 'defaults': [], 'name': '__AppointSuccessProcess'},
                     {'args': ['self', 'team_id', 'cheer_count'], 'defaults': [], 'name': '__CheerSuccessProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateTeamWindows'},
                     {'args': ['self'], 'defaults': [], 'name': '__DestroyTeamWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveRewardSuccessProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFirstPrevPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickLastNextPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNextPageButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__OnClickPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickPrevPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevDescriptionPage'},
                     {'args': ['self', 'max_list_count', 'cur_page'], 'defaults': [], 'name': '__RefreshPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshTeamWindowButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RenderDescription'},
                     {'args': ['self', 'is_request_answer', 'arg'], 'defaults': [], 'name': '__SendAppointRequest'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetEvent'},
                     {'args': ['self', 'max_info_count', 'cur_page_button_number'], 'defaults': [], 'name': '__ShowPageButton'},
                     {'args': ['self', 'cur_page_button_number'], 'defaults': [], 'name': '__ShowTeamInfoPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__SortParticipatedTeamList'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DESC_LINE_LIMIT_COUNT', 'type': 'int', 'value': 4},
                    {'name': 'PAGE_MAX', 'type': 'int', 'value': 5},
                    {'name': 'SMALL_HEIGHT_GAP', 'type': 'int', 'value': 4},
                    {'name': 'TEAM_BG_HEIGHT', 'type': 'int', 'value': 31},
                    {'name': 'TEAM_LIST_MAX_COUNT_AT_ONE_PAGE', 'type': 'int', 'value': 8},
                    {'name': '_SportsMatchPredictWindow__cur_open_page', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__cur_open_page' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__cur_page_button_index', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__cur_page_button_index' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__desc_board', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__desc_board' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__desc_index', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__desc_index' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__desc_y', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__desc_y' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__description_box', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__description_box' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__first_prev_button', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__first_prev_button' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__is_load_data_file_success', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__is_load_data_file_success' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__is_lock', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__is_lock' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__last_next_button', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__last_next_button' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__next_button', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__next_button' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__page_button_list', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__page_button_list' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__page_button_max_index', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__page_button_max_index' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__participate_teams_info', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__participate_teams_info' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__prev_button', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__prev_button' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__prev_cheer_time', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__prev_cheer_time' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__sorted_team_info_list', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__sorted_team_info_list' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__team_info_window_pos', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__team_info_window_pos' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__team_list_window', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__team_list_window' of 'SportsMatchPredictWindow' objects>},
                    {'name': '_SportsMatchPredictWindow__team_popup_window', 'type': 'member_descriptor', 'value': <member '_SportsMatchPredictWindow__team_popup_window' of 'SportsMatchPredictWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSportsMatch'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SportsMatchPredictWindow'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__desc_board',
                               '__description_box',
                               '__desc_index',
                               '__desc_y',
                               '__participate_teams_info',
                               '__team_list_window',
                               '__team_info_window_pos',
                               '__page_button_list',
                               '__first_prev_button',
                               '__prev_button',
                               '__next_button',
                               '__last_next_button',
                               '__cur_page_button_index',
                               '__page_button_max_index',
                               '__is_lock',
                               '__cur_open_page',
                               '__team_popup_window',
                               '__prev_cheer_time',
                               '__sorted_team_info_list',
                               '__is_load_data_file_success')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AppointSuccessProcess'},
                     {'args': ['self', 'cheer_count'], 'defaults': [], 'name': 'CheerSuccessProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetCheerCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetOrderIdx'},
                     {'args': ['self'], 'defaults': [], 'name': 'GiveRewardSuccessProcess'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsAppointed'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsWinningTeam'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetButton'},
                     {'args': ['self', 'win_team_id'], 'defaults': [], 'name': 'SetButtonAfterResult'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetButtonWhenEventTimeEnd'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'SetEnableGetReward'},
                     {'args': ['self', 'name', 'order_idx', 'is_appointed', 'cheer_count', 'is_reward_enable'], 'defaults': [], 'name': 'SetInformation'},
                     {'args': ['self'], 'defaults': [], 'name': '__AppointProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__CheerProcess'},
                     {'args': ['self', 'team_id'], 'defaults': [], 'name': '__ClickTeamButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__GiveRewardProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitWindowObject'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'predict_ui_handler', 'parent_obj', 'team_id'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FLAG_IMG_PATH', 'type': 'str', 'value': 'locale/hu/ui/sports_match/'},
                    {'name': 'TEAM_BG_HEIGHT', 'type': 'int', 'value': 31},
                    {'name': 'TEAM_BG_WIDTH', 'type': 'int', 'value': 276},
                    {'name': '_TeamInfoWindow__bg_img', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__bg_img' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__button', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__button' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__cheer_count', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__cheer_count' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__cheer_count_text_obj', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__cheer_count_text_obj' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__cheer_count_window', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__cheer_count_window' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__image', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__image' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__is_appointed', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__is_appointed' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__is_enable_get_reward', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__is_enable_get_reward' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__is_winning_team', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__is_winning_team' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__order_idx', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__order_idx' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__order_number', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__order_number' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__predict_ui_handler', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__predict_ui_handler' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__team_id', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__team_id' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__team_name', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__team_name' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__team_name_text_obj', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__team_name_text_obj' of 'TeamInfoWindow' objects>},
                    {'name': '_TeamInfoWindow__team_name_window', 'type': 'member_descriptor', 'value': <member '_TeamInfoWindow__team_name_window' of 'TeamInfoWindow' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSportsMatch'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'TeamInfoWindow'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__team_id',
                               '__team_name',
                               '__team_name_text_obj',
                               '__is_appointed',
                               '__cheer_count',
                               '__cheer_count_text_obj',
                               '__image',
                               '__button',
                               '__is_enable_get_reward',
                               '__order_number',
                               '__bg_img',
                               '__predict_ui_handler',
                               '__team_name_window',
                               '__cheer_count_window',
                               '__order_idx',
                               '__is_winning_team')}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'playerm2g2', 'event', 'grp', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'sportsMatch', 'ingameEventSystem', 'item', 'ui', 'uiMiniGame'],
 'var': [{'name': 'SportsMatchWindow', 'type': 'ABCMeta', 'value': <class 'uiSportsMatch.SportsMatchWindow'>},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiSportsMatch'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
