{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'vnum', 'day', 'win', 'cell'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAcceptButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAwardNextButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickAwardPrevButton'},
                     {'args': ['self', 'day'], 'defaults': [], 'name': '__ClickDayButton'},
                     {'args': ['self', 'i'], 'defaults': [], 'name': '__ClickDayPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__MainSlotOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__NumberFlash'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshDaysButton'},
                     {'args': ['self', 'time'], 'defaults': [], 'name': '__SecondToHMTime'},
                     {'args': ['self', 'minIdx', 'maxIdx'], 'defaults': [], 'name': '__ShowItemAward'},
                     {'args': ['self'], 'defaults': [], 'name': '__SlotOverOutItem'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': '__SubSlotOverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSpecialGacha'}, {'name': '__qualname__', 'type': 'str', 'value': 'SpecialGachaAward'}]}],
 'func': [],
 'import': ['uiToolTip', '__builtin__', 'specialgacha', 'app', 'item', 'playerm2g2', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiSpecialGacha'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
