{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'IceCreamEventMessage', 'type': 'classmethod', 'value': <classmethod object at 0x2C1912B0>},
                    {'name': 'IsIceCreamEventEnd', 'type': 'classmethod', 'value': <classmethod object at 0x2C1912D0>},
                    {'name': '_IceCreamEventUtil__ICECREAM_EVENT_LOCA', 'type': 'dict', 'value': {0: 'Kapt\xe1l egy Fagylaltgomb\xf3cot.', 1: 'Nem kaphatsz t\xf6bb Fagylaltgomb\xf3cot.', 2: '\xc1tvitt\xe9l %d Fagylaltgomb\xf3cot az \xfaj rendezv\xe9ny men\xfcbe.'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSummerIceCreamEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'IceCreamEventUtil'},
                    {'name': '__slots__', 'type': 'str', 'value': '__ICECREAM_EVENT_LOCA'}]}],
 'func': [],
 'import': ['event', '__builtin__', 'chatm2g', 'app', 'item', 'playerm2g2', 'ui', 'uiScriptLocale', 'ingameEventSystem', 'localeInfo', 'uiMiniGame'],
 'var': [{'name': 'IceCreamEvent', 'type': 'ABCMeta', 'value': <class 'uiSummerIceCreamEvent.IceCreamEvent'>},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiSummerIceCreamEvent'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
