{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'FloorButtonDisable'},
                                {'args': ['self'], 'defaults': [], 'name': 'FloorButtonDown'},
                                {'args': ['self'], 'defaults': [], 'name': 'FloorButtonEnable'},
                                {'args': ['self'], 'defaults': [], 'name': 'FloorButtonUp'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetFloor'},
                                {'args': ['self'], 'defaults': [], 'name': 'HideClearIcon'},
                                {'args': ['self', 'rank', 'clear_time_second'], 'defaults': [], 'name': 'SetRankData'},
                                {'args': ['self'], 'defaults': [], 'name': 'ShowClearIcon'},
                                {'args': ['self'], 'defaults': [], 'name': '__OnClickButton'},
                                {'args': ['self'], 'defaults': [], 'name': '__OverInClearIcon'},
                                {'args': ['self'], 'defaults': [], 'name': '__OverOutClearIcon'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'root_parent_window', 'parent_object', 'floor_number', 'tooltip'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': 'BUTTON_IMG_HEIGHT', 'type': 'int', 'value': 28},
                               {'name': 'BUTTON_IMG_WIDTH', 'type': 'int', 'value': 126},
                               {'name': '_SungmaheeTowerFloorButton__BUTTON_IMG_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/sungmahee_tower/'},
                               {'name': '_SungmaheeTowerFloorButton__button_object', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__button_object' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__clear_icon_object', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__clear_icon_object' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__clear_time_second', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__clear_time_second' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__floor', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__floor' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__is_request_data', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__is_request_data' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__rank', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__rank' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__root_parent_window', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__root_parent_window' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '_SungmaheeTowerFloorButton__tooltip', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerFloorButton__tooltip' of '__SungmaheeTowerFloorButton' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiSungmaheeTower'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'SungmaheeTowerEnter.__SungmaheeTowerFloorButton'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__root_parent_window', '__floor', '__rank', '__clear_time_second', '__is_request_data', '__button_object', '__clear_icon_object', '__tooltip')}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'is_request_data', 'click_floor', 'rank', 'clear_time_second'], 'defaults': [], 'name': 'OnClickFloorButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseWheelButtonUp'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'tooltip_item'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'SungmaheeTowerEnterPacketProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'floor'], 'defaults': [], 'name': '__CalculScrollPos'},
                     {'args': ['self', 'clear_top_floor'], 'defaults': [], 'name': '__ClearIconRefresh'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateFloorObject'},
                     {'args': ['self', 'enter_result_type'], 'defaults': [], 'name': '__DungeonEnterResultProcess'},
                     {'args': ['self', 'down_floor'], 'defaults': [], 'name': '__FloorButtonRefresh'},
                     {'args': ['self', 'group_name', 'source_text'], 'defaults': [], 'name': '__GetTextLinesFromGroupUseRegex'},
                     {'args': ['self'], 'defaults': [], 'name': '__IsPossibleSungmaheeTowerEnter'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadDataFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadElementFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadRewardFile'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickEnterButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverInElementText'},
                     {'args': ['self', 'slot_index'], 'defaults': [], 'name': '__OverInRewardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutElementText'},
                     {'args': ['self'], 'defaults': [], 'name': '__OverOutRewardSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshFloorList'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendSungmaheeTowerDungeonEnter'},
                     {'args': ['self', 'floor'], 'defaults': [], 'name': '__SetElementText'},
                     {'args': ['self', 'floor', 'rank', 'clear_time_second'], 'defaults': [], 'name': '__SetFloorDisplay'},
                     {'args': ['self', 'floor'], 'defaults': [], 'name': '__SetFloorReward'},
                     {'args': ['self', 'floor', 'rank', 'clear_time_second'], 'defaults': [], 'name': '__SetRankData'},
                     {'args': ['self', 'rank', 'clear_time_second'], 'defaults': [], 'name': '__SetRankText'},
                     {'args': ['self', 'result_type', 'orgin_clear_top_floor', 'last_clear_floor_rank', 'last_clear_floor_clear_time_second'], 'defaults': [], 'name': '__UIOpenResultProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'PACKET_PROCESS_KIND_TUPLE', 'type': 'tuple', 'value': (0, 1, 2)},
                    {'name': '_SungmaheeTowerEnter__ELEMENT_TABLE_TOKEN_SIZE', 'type': 'int', 'value': 2},
                    {'name': '_SungmaheeTowerEnter__FLOOR_BUTTON_GAP', 'type': 'int', 'value': 3},
                    {'name': '_SungmaheeTowerEnter__FLOOR_BUTTON_VIEW_COUNT', 'type': 'int', 'value': 5},
                    {'name': '_SungmaheeTowerEnter__RANKING_SHOW_MAX', 'type': 'int', 'value': 99},
                    {'name': '_SungmaheeTowerEnter__REWARD_ITEM_SIZE', 'type': 'int', 'value': 5},
                    {'name': '_SungmaheeTowerEnter__REWARD_TABLE_TOKEN_SIZE', 'type': 'int', 'value': 11},
                    {'name': '_SungmaheeTowerEnter__clear_top_floor', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__clear_top_floor' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__element_text', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__element_text' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__element_text_window', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__element_text_window' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__enter_question_popup', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__enter_question_popup' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__floor_element_table_dict', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__floor_element_table_dict' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__floor_list_max', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__floor_list_max' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__floor_list_window', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__floor_list_window' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__floor_object_tuple', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__floor_object_tuple' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__floor_reward_slot__enter_button', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__floor_reward_slot__enter_button' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__floor_reward_table_dict', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__floor_reward_table_dict' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__is_loaded', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__is_loaded' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__is_requesting_enter', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__is_requesting_enter' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__is_requesting_floor_data', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__is_requesting_floor_data' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__my_rank_text', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__my_rank_text' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__my_rank_time_text', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__my_rank_time_text' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__open_pos_x', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__open_pos_x' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__open_pos_y', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__open_pos_y' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__scrollbar', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__scrollbar' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__selected_floor', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__selected_floor' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__tooltip', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__tooltip' of 'SungmaheeTowerEnter' objects>},
                    {'name': '_SungmaheeTowerEnter__tooltip_item', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerEnter__tooltip_item' of 'SungmaheeTowerEnter' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSungmaheeTower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SungmaheeTowerEnter'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__is_loaded',
                               '__floor_list_window',
                               '__scrollbar',
                               '__my_rank_text',
                               '__my_rank_time_text',
                               '__floor_reward_slot__enter_button',
                               '__element_text',
                               '__element_text_window',
                               '__tooltip',
                               '__tooltip_item',
                               '__floor_element_table_dict',
                               '__floor_reward_table_dict',
                               '__enter_question_popup',
                               '__floor_object_tuple',
                               '__floor_list_max',
                               '__selected_floor',
                               '__clear_top_floor',
                               '__is_requesting_floor_data',
                               '__is_requesting_enter',
                               '__open_pos_x',
                               '__open_pos_y')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Hide'},
                     {'args': ['self', 'tooltip_item'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'SungmaheeTowerProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_SungmaheeTowerInterface__sungmahee_tower_enter_object__sungmahee_tower_information_board', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInterface__sungmahee_tower_enter_object__sungmahee_tower_information_board' of 'SungmaheeTowerInterface' objects>},
                    {'name': '_SungmaheeTowerInterface__tooltip_item', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInterface__tooltip_item' of 'SungmaheeTowerInterface' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSungmaheeTower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SungmaheeTowerInterface'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__tooltip_item', '__sungmahee_tower_enter_object__sungmahee_tower_information_board')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                                {'args': ['self'], 'defaults': [], 'name': 'RefreshClippingMaskRect'},
                                {'args': ['self'], 'defaults': [], 'name': '__AffectTextUpdate'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self', 'parent_object', 'affect_type', 'affect_text'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': 'AFFECT_TEXT_WINDOW_HEIGHT', 'type': 'int', 'value': 24},
                               {'name': 'AFFECT_TEXT_WINDOW_WIDTH', 'type': 'int', 'value': 119},
                               {'name': '_SungmaheeTowerAffect__AFFECT_TEXT_MOVE_X', 'type': 'int', 'value': 1},
                               {'name': '_SungmaheeTowerAffect__affect_text__affect_img', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerAffect__affect_text__affect_img' of '__SungmaheeTowerAffect' objects>},
                               {'name': '_SungmaheeTowerAffect__affect_type', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerAffect__affect_type' of '__SungmaheeTowerAffect' objects>},
                               {'name': '_SungmaheeTowerAffect__text_img', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerAffect__text_img' of '__SungmaheeTowerAffect' objects>},
                               {'name': '_SungmaheeTowerAffect__text_object', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerAffect__text_object' of '__SungmaheeTowerAffect' objects>},
                               {'name': '_SungmaheeTowerAffect__text_object_horizontal_scroll_length', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerAffect__text_object_horizontal_scroll_length' of '__SungmaheeTowerAffect' objects>},
                               {'name': '_SungmaheeTowerAffect__text_window', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerAffect__text_window' of '__SungmaheeTowerAffect' objects>},
                               {'name': '__doc__', 'type': 'NoneType', 'value': None},
                               {'name': '__module__', 'type': 'str', 'value': 'uiSungmaheeTower'},
                               {'name': '__qualname__', 'type': 'str', 'value': 'SungmaheeTowerInformationBoard.__SungmaheeTowerAffect'},
                               {'name': '__slots__', 'type': 'tuple', 'value': ('__affect_type', '__affect_text__affect_img', '__text_window', '__text_img', '__text_object', '__text_object_horizontal_scroll_length')}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'tooltip_item'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'type', 'data'], 'defaults': [], 'name': 'SungmaheeTowerInfoBoardPacketProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeAffectList'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'exit_result_type'], 'defaults': [], 'name': '__DungeonExitResultProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__MissionTypeTextUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickExitButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__SendSungmaheeTowerDungeonExit'},
                     {'args': ['self', 'floor'], 'defaults': [], 'name': '__SetFloorText'},
                     {'args': ['self', 'mission_type'], 'defaults': [], 'name': '__SetMissionText'},
                     {'args': ['self', 'cur_gauge', 'max_gauge'], 'defaults': [], 'name': '__SetTimeGauge'},
                     {'args': ['self', 'stage_limit_time', 'stage_clear_time'], 'defaults': [], 'name': '__SetTimeText'},
                     {'args': ['self'], 'defaults': [], 'name': '__SettingData'},
                     {'args': ['self', 'last_clear_stage'], 'defaults': [], 'name': '__StageClearIconRefresh'},
                     {'args': ['self', 'affect_type', 'point_type', 'point_value', 'duration', 'flag'], 'defaults': [], 'name': '__SungmaheeTowerAddAffect'},
                     {'args': ['self', 'erase_affect_type', 'erase_point_type', 'erase_flag'], 'defaults': [], 'name': '__SungmaheeTowerRemoveAffect'},
                     {'args': ['self'], 'defaults': [], 'name': '__TimeTextUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'AFFECT_GAP', 'type': 'int', 'value': 3},
                    {'name': 'AFFECT_START_GAP', 'type': 'int', 'value': 10},
                    {'name': 'BOARD_HEIGHT', 'type': 'int', 'value': 135},
                    {'name': 'BOARD_WIDTH', 'type': 'int', 'value': 136},
                    {'name': 'PACKET_PROCESS_KIND_TUPLE', 'type': 'tuple', 'value': (3, 4, 5, 6)},
                    {'name': '_SungmaheeTowerInformationBoard__MISSION_TEXT_MOVE_X', 'type': 'int', 'value': 1},
                    {'name': '_SungmaheeTowerInformationBoard__MISSION_TYPE_TEXT_WINDOW_WIDTH', 'type': 'int', 'value': 93},
                    {'name': '_SungmaheeTowerInformationBoard__alarm_text', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__alarm_text' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__alarm_text_horizontal_scroll_length', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__alarm_text_horizontal_scroll_length' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__cur_stage_end_time', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__cur_stage_end_time' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__cur_stage_limit_time_second', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__cur_stage_limit_time_second' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__exit_button', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__exit_button' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__exit_question_dialog', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__exit_question_dialog' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__floor_text', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__floor_text' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__is_loaded', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__is_loaded' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__is_requesting_exit', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__is_requesting_exit' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__stage_clear_img_tuple', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__stage_clear_img_tuple' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__sungmahee_tower_affect', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__sungmahee_tower_affect' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__time_gauge', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__time_gauge' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__time_text', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__time_text' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '_SungmaheeTowerInformationBoard__tooltip_item', 'type': 'member_descriptor', 'value': <member '_SungmaheeTowerInformationBoard__tooltip_item' of 'SungmaheeTowerInformationBoard' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiSungmaheeTower'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'SungmaheeTowerInformationBoard'},
                    {'name': '__slots__',
                     'type': 'tuple',
                     'value': ('__is_loaded',
                               '__is_requesting_exit',
                               '__cur_stage_end_time',
                               '__cur_stage_limit_time_second',
                               '__alarm_text_horizontal_scroll_length',
                               '__floor_text',
                               '__alarm_text',
                               '__time_text',
                               '__time_gauge',
                               '__exit_button',
                               '__exit_question_dialog',
                               '__stage_clear_img_tuple',
                               '__tooltip_item',
                               '__sungmahee_tower_affect')}]}],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'proxy'}],
 'import': ['chatm2g', 'app', 'm2netm2g', 'playerm2g2', 'uiToolTip', 're', 'chr', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'item', 'ui'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiSungmaheeTower'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
