{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeMusicVolume'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeShadowQuality'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnChangeSoundVolume'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseInputDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnCloseQuestionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self', 'buttonList', 'buttonIndex'], 'defaults': [], 'name': '__ClickRadioButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__DayMode_OnCompleteChangeToDark'},
                     {'args': ['self'], 'defaults': [], 'name': '__DayMode_OnCompleteChangeToLight'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitNightModeOption'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitSnowModeOption'},
                     {'args': ['self'], 'defaults': [], 'name': '__InitSnowTextureModeOption'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__Load'},
                     {'args': ['self'], 'defaults': [], 'name': '__Load_BindObject'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__Load_LoadScript'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__NotifyChatLine'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__OnChangeMusic'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickCameraModeLongButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickCameraModeShortButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickChangeMusicButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeLevel0Button'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeLevel1Button'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeLevel2Button'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeOffButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickFogModeOnButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNightModeOffButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickNightModeOnButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSnowModeOffButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSnowModeOnButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSnowTextureModeOffButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickSnowTextureModeOnButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickTilingApplyButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickTilingModeCPUButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickTilingModeGPUButton'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetCameraMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetCurTilingMode'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetFogLevel'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetNightMode'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetSnowMode'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetSnowTextureMode'},
                     {'args': ['self', 'index'], 'defaults': [], 'name': '__SetTilingMode'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiSystemOption'}, {'name': '__qualname__', 'type': 'str', 'value': 'OptionDialog'}]}],
 'func': [],
 'import': ['chatm2g', 'app', 'dbg', 'm2netm2g', 'playerm2g2', 'constInfo', 'systemSetting', 'chrmgrm2g', 'ui', 'localeInfo', 'snd', '__builtin__', 'background', 'uiSelectMusic', 'uiPhaseCurtain', 'musicInfo'],
 'var': [{'name': 'MUSIC_FILENAME_MAX_LEN', 'type': 'int', 'value': 25},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiSystemOption'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'blockMode', 'type': 'int', 'value': 0}]}
