{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTargetName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTargetVID'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAllButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShowButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAppendToMessenger'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBlockRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBlockRemoveClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnExchange'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPVP'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPartyExit'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPartyInvite'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPartyRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressedCloseButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnWhisper'},
                     {'args': ['self', 'vid', 'name'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'RefreshAccumulateCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RefreshByName'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'RefreshByVID'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetTargetBoard'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'SetEnemyVID'},
                     {'args': ['self', 'hpPercentage'], 'defaults': [], 'name': 'SetHP'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetTargetName'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'SetTargetVID'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetWhisperEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowDefaultButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdatePosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeButtonPosition'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__HideButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlock'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlockRemove'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnDestroyBuilding'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnDismount'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnEmotionAllow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnExitObserver'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildAddMember'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnRequestParty'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnViewEquipment'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnVoteBlockChat'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__ShowButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowMainCharacterMenu'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowNameOnlyMenu'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUTTON_NAME_LIST',
                     'type': 'tuple',
                     'value': ('Fl\xfcstern',
                               'Handeln',
                               'Duell',
                               'Zustimmen',
                               'Rache',
                               'Freund',
                               'Gruppeneinlad.',
                               'Gruppe verlassen',
                               'Ausschlie\xdfen',
                               'Gildeneinlad.',
                               'Absitzen',
                               'Zuschauermodus beenden',
                               'Ausr\xfcstung',
                               'Gruppe beitreten',
                               'Zerst\xf6ren',
                               'Emotionen',
                               'Blockieren',
                               'Entsperren',
                               'VOTE_BLOCK_CHAT')},
                    {'name': 'EXCHANGE_LIMIT_RANGE', 'type': 'int', 'value': 3000},
                    {'name': 'GRADE_NAME', 'type': 'dict', 'value': {0: 'Stufe 1.', 1: 'Stufe 2.', 2: 'Stufe 3.', 3: 'Stufe 4.', 4: 'Boss', 5: 'Stufe 5.'}},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTarget'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'TargetBoard'}]}],
 'func': [],
 'import': ['uiCommon', 'guild', '__builtin__', 'app', 'constInfo', 'chr', 'm2netm2g', 'playerm2g2', 'ui', 'messenger', 'wndMgr', 'localeInfo', 'nonplayer'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiTarget'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
