{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AdjustPositionElementImage'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTargetName'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTargetVID'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideAllButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsShowButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnAppendToMessenger'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBlockRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnBlockRemoveClose'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnExchange'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPVP'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPartyExit'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPartyInvite'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPartyRemove'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressedCloseButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnQuestionDialogClose'},
                     {'args': ['self', 'virId'], 'defaults': [], 'name': 'OnRivive'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnWhisper'},
                     {'args': ['self', 'vid', 'name'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'vid', 'itemcount'], 'defaults': [], 'name': 'OpenReviveDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Refresh'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'RefreshAccumulateCount'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshButton'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'RefreshByName'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'RefreshByVID'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetTargetBoard'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'SetEnemyVID'},
                     {'args': ['self', 'hpPercentage'], 'defaults': [], 'name': 'SetHP'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetTargetName'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'SetTargetVID'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'SetWhisperEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowDefaultButton'},
                     {'args': ['self', 'element_enchants_dict'], 'defaults': [], 'name': 'ShowElementImg'},
                     {'args': ['self'], 'defaults': [], 'name': 'UpdatePosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__ArrangeButtonPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__ElementBuffImgOverInEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__ElementBuffImgOverOutEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllElementImg'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__HideButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlock'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlockRemove'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnDestroyBuilding'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnDismount'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnEmotionAllow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnExitObserver'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnGuildAddMember'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnRequestParty'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnReviveQustionDialog'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnViewEquipment'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnVoteBlockChat'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': '__ShowAdditionalInfoIcons'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': '__ShowButton'},
                     {'args': ['self', 'current_index', 'vid'], 'defaults': [], 'name': '__ShowElementBuffImg'},
                     {'args': ['self', 'current_index', 'vid'], 'defaults': [], 'name': '__ShowElementImg'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowMainCharacterMenu'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowNameOnlyMenu'},
                     {'args': ['self', 'img', 'index'], 'defaults': [], 'name': '__ShowSingleIcon'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'ADDITIONAL_INFO_ICON_HEIGHT', 'type': 'int', 'value': 39},
                    {'name': 'ADDITIONAL_INFO_ICON_SCALE', 'type': 'float', 'value': 0.8},
                    {'name': 'ADDITIONAL_INFO_ICON_WIDTH', 'type': 'int', 'value': 39},
                    {'name': 'ELEMENT_BUFF_IMG_PATH', 'type': 'str', 'value': 'd:/ymir work/ui/game/sungmahee_gate/element_buff.sub'},
                    {'name': 'ELEMENT_BUFF_TOOLTIP',
                     'type': 'dict',
                     'value': {26: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a K\xf6z\xf6ns\xe9ges er\xf5vir\xe1g hat\xe1s\xe1val.',
                               27: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a T\xfbz er\xf5vir\xe1g hat\xe1s\xe1val.',
                               28: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a J\xe9g er\xf5vir\xe1g hat\xe1s\xe1val.',
                               29: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a Vill\xe1m er\xf5vir\xe1g hat\xe1s\xe1val.',
                               30: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a Sz\xe9l er\xf5vir\xe1g hat\xe1s\xe1val.',
                               31: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a F\xf6ld er\xf5vir\xe1g hat\xe1s\xe1val.',
                               32: 'Tov\xe1bbi sebz\xe9st \xe9rhetsz el a S\xf6t\xe9ts\xe9g er\xf5vir\xe1g hat\xe1s\xe1val.'}},
                    {'name': 'ELEMENT_ENCHANT_ICON_SCALE', 'type': 'float', 'value': 0.8},
                    {'name': 'ELEMENT_IMG_PATH',
                     'type': 'dict',
                     'value': {0: 'd:/ymir work/ui/game/12zi/element/elect.sub',
                               1: 'd:/ymir work/ui/game/12zi/element/fire.sub',
                               2: 'd:/ymir work/ui/game/12zi/element/ice.sub',
                               3: 'd:/ymir work/ui/game/12zi/element/wind.sub',
                               4: 'd:/ymir work/ui/game/12zi/element/earth.sub',
                               5: 'd:/ymir work/ui/game/12zi/element/dark.sub'}},
                    {'name': 'EXCHANGE_LIMIT_RANGE', 'type': 'int', 'value': 3000},
                    {'name': '_TargetBoard__element_buff_image', 'type': 'member_descriptor', 'value': <member '_TargetBoard__element_buff_image' of 'TargetBoard' objects>},
                    {'name': '_TargetBoard__tooltip_element_buff_image', 'type': 'member_descriptor', 'value': <member '_TargetBoard__tooltip_element_buff_image' of 'TargetBoard' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTarget'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'TargetBoard'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__element_buff_image', '__tooltip_element_buff_image')}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTarget'}, {'name': '__qualname__', 'type': 'str', 'value': 'AllianceTargetBoard.TextToolTip'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetTargetVID'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsIn'},
                     {'args': ['self'], 'defaults': [], 'name': 'IsOut'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResetTargetBoard'},
                     {'args': ['self', 'hp', 'hpMax'], 'defaults': [], 'name': 'SetHP'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetMouseEvent'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'SetTarget'},
                     {'args': ['self', 'name'], 'defaults': [], 'name': 'SetTargetName'},
                     {'args': ['self', 'vid'], 'defaults': [], 'name': 'SetTargetVID'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTarget'}, {'name': '__qualname__', 'type': 'str', 'value': 'AllianceTargetBoard'}]}],
 'func': [],
 'import': ['app', 'm2netm2g', 'playerm2g2', 'constInfo', 'uiToolTip', 'chrmgrm2g', 'chr', 'messenger', 'localeInfo', 'uiCommon', '__builtin__', 'background', 'wndMgr', 'guild', 'ui', 'nonplayer'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiTarget'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
