{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'GiftBox.TextToolTip'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Destroy'}, {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'GiftBox'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self', 'coolTime'], 'defaults': [], 'name': 'Activate'},
                                {'args': ['self'], 'defaults': [], 'name': 'Deactivate'},
                                {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetSkillIndex'},
                                {'args': ['self'], 'defaults': [], 'name': 'GetSlotIndex'},
                                {'args': ['self', 'dummy'], 'defaults': [], 'name': 'OnOverInItem'},
                                {'args': ['self'], 'defaults': [], 'name': 'OnOverOutItem'},
                                {'args': ['self', 'dummy'], 'defaults': [], 'name': 'OnSelectItemSlot'},
                                {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                                {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                                {'args': ['self', 'skillSlotNumber'], 'defaults': [], 'name': 'SetSkill'},
                                {'args': ['self', 'event', 'arg'], 'defaults': [0], 'name': 'SetSkillEvent'},
                                {'args': ['self', 'tooltip'], 'defaults': [], 'name': 'SetSkillToolTip'},
                                {'args': ['self'], 'defaults': [], 'name': '__del__'},
                                {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'TaskBar.SkillButton'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'TaskBar.TextToolTip'}]}],
            'func': [{'args': ['self', 'localSlotIndex'], 'defaults': [], 'name': 'AddQuickSlot'},
                     {'args': ['self', 'slotIndex'], 'defaults': [-1], 'name': 'CloseSelectSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'HideGift'},
                     {'args': ['self'], 'defaults': [], 'name': 'LeftMouseButtonIsShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self', 'usedSlotIndex'], 'defaults': [], 'name': 'OnActivateSkill'},
                     {'args': ['self', 'skillSlotNumber'], 'defaults': [], 'name': 'OnChangeCurrentSkill'},
                     {'args': ['self', 'usedSlotIndex'], 'defaults': [], 'name': 'OnDeactivateSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'usedSlotIndex', 'coolTime'], 'defaults': [], 'name': 'OnUseSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'OpenSelectSkill'},
                     {'args': ['self', 'slotNumber'], 'defaults': [], 'name': 'OverInItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'OverOutItem'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshQuickSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkill'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshSkillCoolTime'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStamina'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'RemoveQuickSlotIndex'},
                     {'args': ['self'], 'defaults': [], 'name': 'RightMouseButtonIsShow'},
                     {'args': ['self', 'slotIndex'], 'defaults': [], 'name': 'SelectEmptyQuickSlot'},
                     {'args': ['self', 'localQuickSlotIndex'], 'defaults': [], 'name': 'SelectItemQuickSlot'},
                     {'args': ['self', 'dir', 'event'], 'defaults': [], 'name': 'SelectMouseButtonEvent'},
                     {'args': ['self', 'curPoint', 'maxPoint'], 'defaults': [], 'name': 'SetExperience'},
                     {'args': ['self', 'curPoint', 'recoveryPoint', 'maxPoint'], 'defaults': [], 'name': 'SetHP'},
                     {'args': ['self', 'tooltipItem'], 'defaults': [], 'name': 'SetItemToolTip'},
                     {'args': ['self', 'curPoint', 'recoveryPoint', 'maxPoint'], 'defaults': [], 'name': 'SetSP'},
                     {'args': ['self', 'curPoint', 'maxPoint'], 'defaults': [], 'name': 'SetST'},
                     {'args': ['self', 'tooltipSkill'], 'defaults': [], 'name': 'SetSkillToolTip'},
                     {'args': ['self', 'eButton', 'kEventFunc'], 'defaults': [], 'name': 'SetToggleButtonEvent'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowGift'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleLeftMouseButtonModeWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'ToggleRightMouseButtonModeWindow'},
                     {'args': ['self', 'localSlotIndex'], 'defaults': [], 'name': 'UnselectItemQuickSlot'},
                     {'args': ['self', 'arg'], 'defaults': [], 'name': '__IsInSafeMouseButtonSettingRange'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadMouseSettings'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickQuickPageDownButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnClickQuickPageUpButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RampageGauge_Click'},
                     {'args': ['self'], 'defaults': [], 'name': '__RampageGauge_OverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__RampageGauge_OverOut'},
                     {'args': ['self', 'slot', 'window', 'Position', 'slotNumber', 'itemVnum'], 'defaults': [], 'name': '__SetCollTimePetItemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'},
                     {'args': ['self', 'Type', 'slotNumber'], 'defaults': [], 'name': 'canAddQuickSlot'}],
            'import': [],
            'var': [{'name': 'BUTTON_CHARACTER', 'type': 'int', 'value': 0},
                    {'name': 'BUTTON_CHAT', 'type': 'int', 'value': 4},
                    {'name': 'BUTTON_EXPAND', 'type': 'int', 'value': 4},
                    {'name': 'BUTTON_EXPAND_MONEY', 'type': 'int', 'value': 5},
                    {'name': 'BUTTON_INVENTORY', 'type': 'int', 'value': 1},
                    {'name': 'BUTTON_MESSENGER', 'type': 'int', 'value': 2},
                    {'name': 'BUTTON_SYSTEM', 'type': 'int', 'value': 3},
                    {'name': 'EVENT_ATTACK', 'type': 'int', 'value': 1},
                    {'name': 'EVENT_AUTO', 'type': 'int', 'value': 5},
                    {'name': 'EVENT_CAMERA', 'type': 'int', 'value': 3},
                    {'name': 'EVENT_MOVE', 'type': 'int', 'value': 0},
                    {'name': 'EVENT_MOVE_AND_ATTACK', 'type': 'int', 'value': 2},
                    {'name': 'EVENT_SKILL', 'type': 'int', 'value': 4},
                    {'name': 'GAUGE_HEIGHT', 'type': 'int', 'value': 13},
                    {'name': 'GAUGE_WIDTH', 'type': 'int', 'value': 95},
                    {'name': 'IS_EXPANDED', 'type': 'bool', 'value': True},
                    {'name': 'MOUSE_BUTTON_LEFT', 'type': 'int', 'value': 0},
                    {'name': 'MOUSE_BUTTON_RIGHT', 'type': 'int', 'value': 1},
                    {'name': 'NONE', 'type': 'int', 'value': 255},
                    {'name': 'QUICKPAGE_NUMBER_FILENAME', 'type': 'list', 'value': ['d:/ymir work/ui/game/taskbar/1.sub', 'd:/ymir work/ui/game/taskbar/2.sub', 'd:/ymir work/ui/game/taskbar/3.sub', 'd:/ymir work/ui/game/taskbar/4.sub']},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'TaskBar'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetCheque'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetChequeIcon'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetChequeSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGem'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGemIcon'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetGemSlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMoney'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMoneyIcon'},
                     {'args': ['self'], 'defaults': [], 'name': 'GetMoneySlot'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'ExpandedMoneyTaskBar'}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'enable'], 'defaults': [], 'name': 'EnableAutoButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self', 'off'], 'defaults': [], 'name': 'PartyMatchOff'},
                     {'args': ['self'], 'defaults': [], 'name': 'RePositionButton'},
                     {'args': ['self', 'eButton', 'kEventFunc'], 'defaults': [], 'name': 'SetToggleButtonEvent'},
                     {'args': ['self', 'eButton', 'text'], 'defaults': [], 'name': 'SetToolTipText'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetTop'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BUTTON_AUTO_WINDOW', 'type': 'int', 'value': 2},
                    {'name': 'BUTTON_DRAGON_SOUL', 'type': 'int', 'value': 0},
                    {'name': 'BUTTON_MERCENARY_WINDOW', 'type': 'int', 'value': 6},
                    {'name': 'BUTTON_MONSTER_CARD_WINDOW', 'type': 'int', 'value': 3},
                    {'name': 'BUTTON_PARTY_MATCH_WINDOW', 'type': 'int', 'value': 4},
                    {'name': 'BUTTON_PET_INFO', 'type': 'int', 'value': 1},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ExpandedTaskBar'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'text'], 'defaults': [], 'name': 'SetText'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'EnergyBar.TextToolTip'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshStatus'},
                     {'args': ['self', 'point', 'leftTime', 'maxTime'], 'defaults': [], 'name': 'SetEnergy'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__qualname__', 'type': 'str', 'value': 'EnergyBar'}]}],
 'func': [{'args': [], 'defaults': [], 'name': 'GetMouseButtonSettings'},
          {'args': ['left', 'right'], 'defaults': [], 'name': 'InitMouseButtonSettings'},
          {'args': [], 'defaults': [], 'name': 'LoadMouseButtonSettings'},
          {'args': [], 'defaults': [], 'name': 'SaveMouseButtonSettings'},
          {'args': ['dir', 'event'], 'defaults': [], 'name': 'SetMouseButtonSetting'},
          {'args': ['n'], 'defaults': [], 'name': 'unsigned32'}],
 'import': ['emotion', 'app', 'm2netm2g', 'playerm2g2', 'skill', 'constInfo', 'uiToolTip', 'mouseModule', 'uiScriptLocale', 'localeInfo', 'uiCommon', '__builtin__', 'wndMgr', 'item', 'ui'],
 'var': [{'name': 'MOUSE_SETTINGS', 'type': 'list', 'value': [5, 3]}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiTaskBar'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
