{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshClippingMaskRect'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTip'},
                     {'args': ['self', 'curTime', 'text'], 'defaults': [], 'name': '__AppendText'},
                     {'args': ['self'], 'defaults': [], 'name': '__CleanOldTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateTextBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadFrameImages'},
                     {'args': ['self', 'x', 'y', 'fileName'], 'defaults': [], 'name': '__LoadImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BIGBOARD_WINDOW_POS_X', 'type': 'int', 'value': 0},
                    {'name': 'BIGBOARD_WINDOW_POS_Y', 'type': 'int', 'value': 40},
                    {'name': 'BIGBOARD_WINDOW_SIZE_HEIGHT', 'type': 'int', 'value': 55},
                    {'name': 'BIGBOARD_WINDOW_SIZE_WIDTH', 'type': 'int', 'value': 512},
                    {'name': 'CLIPPING_MASK_BLANK', 'type': 'int', 'value': 8},
                    {'name': 'FONT_HEIGHT', 'type': 'int', 'value': 18},
                    {'name': 'FONT_WIDTH', 'type': 'int', 'value': 18},
                    {'name': 'FRAME_BASE_X', 'type': 'int', 'value': -20},
                    {'name': 'FRAME_BASE_Y', 'type': 'int', 'value': -12},
                    {'name': 'FRAME_IMAGE_FILE_NAME_LIST', 'type': 'list', 'value': ['d:/ymir work/ui/oxevent/frame_0.sub', 'd:/ymir work/ui/oxevent/frame_1.sub', 'd:/ymir work/ui/oxevent/frame_2.sub']},
                    {'name': 'FRAME_IMAGE_STEP', 'type': 'int', 'value': 256},
                    {'name': 'HIDE_UI_TIME_SECOND', 'type': 'int', 'value': 2},
                    {'name': 'LINE_CHANGE_LIMIT_WIDTH', 'type': 'int', 'value': 470},
                    {'name': 'LINE_HEIGHT', 'type': 'int', 'value': 22},
                    {'name': 'LINE_WIDTH', 'type': 'int', 'value': 500},
                    {'name': 'SCROLL_WAIT_TIME_SECOND', 'type': 'float', 'value': 5.0},
                    {'name': 'STEP_HEIGHT', 'type': 'int', 'value': 44},
                    {'name': 'TEXT_WINDOW_INIT_POS_X', 'type': 'int', 'value': 6},
                    {'name': 'TEXT_WINDOW_INIT_POS_Y', 'type': 'int', 'value': 18},
                    {'name': 'TIP_DURATION', 'type': 'float', 'value': 10.0},
                    {'name': '_BigBoard__all_text_line_count', 'type': 'member_descriptor', 'value': <member '_BigBoard__all_text_line_count' of 'BigBoard' objects>},
                    {'name': '_BigBoard__big_board_codepage_font', 'type': 'member_descriptor', 'value': <member '_BigBoard__big_board_codepage_font' of 'BigBoard' objects>},
                    {'name': '_BigBoard__clean_pos_y', 'type': 'member_descriptor', 'value': <member '_BigBoard__clean_pos_y' of 'BigBoard' objects>},
                    {'name': '_BigBoard__cur_pos_y', 'type': 'member_descriptor', 'value': <member '_BigBoard__cur_pos_y' of 'BigBoard' objects>},
                    {'name': '_BigBoard__dst_pos_y', 'type': 'member_descriptor', 'value': <member '_BigBoard__dst_pos_y' of 'BigBoard' objects>},
                    {'name': '_BigBoard__hide_ui_time__is_first_one_line', 'type': 'member_descriptor', 'value': <member '_BigBoard__hide_ui_time__is_first_one_line' of 'BigBoard' objects>},
                    {'name': '_BigBoard__img_list', 'type': 'member_descriptor', 'value': <member '_BigBoard__img_list' of 'BigBoard' objects>},
                    {'name': '_BigBoard__next_scroll_time', 'type': 'member_descriptor', 'value': <member '_BigBoard__next_scroll_time' of 'BigBoard' objects>},
                    {'name': '_BigBoard__set_pos_y', 'type': 'member_descriptor', 'value': <member '_BigBoard__set_pos_y' of 'BigBoard' objects>},
                    {'name': '_BigBoard__text_line', 'type': 'member_descriptor', 'value': <member '_BigBoard__text_line' of 'BigBoard' objects>},
                    {'name': '_BigBoard__text_window', 'type': 'member_descriptor', 'value': <member '_BigBoard__text_window' of 'BigBoard' objects>},
                    {'name': '_BigBoard__tip_list', 'type': 'member_descriptor', 'value': <member '_BigBoard__tip_list' of 'BigBoard' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTip'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BigBoard'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__tip_list', '__img_list', '__cur_pos_y', '__dst_pos_y', '__next_scroll_time', '__text_window', '__text_line', '__all_text_line_count', '__set_pos_y', '__clean_pos_y', '__hide_ui_time__is_first_one_line', '__big_board_codepage_font')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshClippingMaskRect'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTip'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__AppendText'},
                     {'args': ['self'], 'defaults': [], 'name': '__CleanOldTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateExitButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateTextBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadFrameImages'},
                     {'args': ['self', 'x', 'y', 'fileName'], 'defaults': [], 'name': '__LoadImage'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'BIG_TEXTBAR_MAX_HIGHT', 'type': 'int', 'value': 1000},
                    {'name': 'FONT_HEIGHT', 'type': 'int', 'value': 18},
                    {'name': 'FONT_WIDTH', 'type': 'int', 'value': 18},
                    {'name': 'FRAME_BASE_X', 'type': 'int', 'value': -20},
                    {'name': 'FRAME_BASE_Y', 'type': 'int', 'value': -12},
                    {'name': 'FRAME_IMAGE_FILE_NAME_LIST', 'type': 'list', 'value': ['d:/ymir work/ui/oxevent/frame_new_0.sub', 'd:/ymir work/ui/oxevent/frame_new_1.sub']},
                    {'name': 'FRAME_IMAGE_STEP', 'type': 'int', 'value': 256},
                    {'name': 'LINE_CHANGE_LIMIT_WIDTH', 'type': 'int', 'value': 450},
                    {'name': 'LINE_HEIGHT', 'type': 'int', 'value': 23},
                    {'name': 'LINE_WIDTH', 'type': 'int', 'value': 500},
                    {'name': 'STEP_HEIGHT', 'type': 'int', 'value': 46},
                    {'name': '_BigBoardControl__text_line', 'type': 'member_descriptor', 'value': <member '_BigBoardControl__text_line' of 'BigBoardControl' objects>},
                    {'name': '_BigBoardControl__text_window', 'type': 'member_descriptor', 'value': <member '_BigBoardControl__text_window' of 'BigBoardControl' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTip'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'BigBoardControl'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__text_window', '__text_line')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshClippingMaskRect'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CleanOldTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateTextBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'SCROLL_WAIT_TIME', 'type': 'float', 'value': 3.0},
                    {'name': 'STEP_HEIGHT', 'type': 'int', 'value': 17},
                    {'name': 'TIP_DURATION', 'type': 'float', 'value': 5.0},
                    {'name': '_TipBoard__text_line', 'type': 'member_descriptor', 'value': <member '_TipBoard__text_line' of 'TipBoard' objects>},
                    {'name': '_TipBoard__text_window', 'type': 'member_descriptor', 'value': <member '_TipBoard__text_window' of 'TipBoard' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTip'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'TipBoard'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__text_window', '__text_line')}]},
           {'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'CleanMission'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshClippingMaskRect'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetMission'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': 'SetSubMission'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__AppendText'},
                     {'args': ['self'], 'defaults': [], 'name': '__CreateTextBar'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshBoard'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'FONT_HEIGHT', 'type': 'int', 'value': 15},
                    {'name': 'LINE_HEIGHT', 'type': 'int', 'value': 20},
                    {'name': 'LONG_TEXT_START_X', 'type': 'int', 'value': 300},
                    {'name': 'SCREEN_WIDTH', 'type': 'int', 'value': 1600},
                    {'name': 'STEP_HEIGHT', 'type': 'int', 'value': 25},
                    {'name': '_MissionBoard__text_line', 'type': 'member_descriptor', 'value': <member '_MissionBoard__text_line' of 'MissionBoard' objects>},
                    {'name': '_MissionBoard__text_window', 'type': 'member_descriptor', 'value': <member '_MissionBoard__text_window' of 'MissionBoard' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiTip'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'MissionBoard'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__text_window', '__text_line')}]}],
 'func': [],
 'import': ['grp', '__builtin__', 'app', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiTip'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
