{'class': [{'class': [],
            'func': [{'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self', 'data'], 'defaults': [], 'name': 'OpenUserSituationShow'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshUserSituation'},
                     {'args': ['self'], 'defaults': [], 'name': 'Show'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindEvent'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__ButtonOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__ButtonOverOut'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': '__ClickButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__ClickGiftBoxButton'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': '__CreateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__HideAllButton'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadUserSituationData'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnUpdateBoxButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnUpdateButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshButtonPosition'},
                     {'args': ['self'], 'defaults': [], 'name': '__RequestUserSituationData'},
                     {'args': ['self'], 'defaults': [], 'name': '__ShowAllButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiUserSituationNotice'}, {'name': '__qualname__', 'type': 'str', 'value': 'UserSituationNotice'}]}],
 'func': [],
 'import': ['app', 'dbg', 'm2netm2g', 'playerm2g2', 'uiToolTip', 'uiScriptLocale', '__builtin__', 'wndMgr', 'ui'],
 'var': [{'name': 'AUTO_CLOSE_TIME', 'type': 'int', 'value': 10},
         {'name': 'BUTTON_COUNT_MAX', 'type': 'int', 'value': 3},
         {'name': 'BUTTON_HEIGHT', 'type': 'int', 'value': 21},
         {'name': 'DEFAULT_START_X', 'type': 'int', 'value': 152},
         {'name': 'DEFAULT_UI_SIZE_HEIGHT', 'type': 'int', 'value': 43},
         {'name': 'DEFAULT_UI_SIZE_WIDTH', 'type': 'int', 'value': 111},
         {'name': 'REQUEST_TIME', 'type': 'int', 'value': 10800},
         {'name': 'TASKBAR_HEIGHT', 'type': 'int', 'value': 37},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiUserSituationNotice'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}},
         {'name': 'icon_path_dict', 'type': 'dict', 'value': {1: 'd:/ymir work/ui/game/user_alram/icon_payment.sub', 2: 'd:/ymir work/ui/game/user_alram/icon_promotion.sub', 3: 'd:/ymir work/ui/game/user_alram/icon_event.sub', 4: 'd:/ymir work/ui/game/user_alram/icon_sales.sub'}}]}
