{'class': [{'class': [],
            'func': [],
            'import': [],
            'var': [{'name': 'AppendChat', 'type': 'classmethod', 'value': <classmethod object at 0x2D1BF9D0>},
                    {'name': 'IsValentineDayEventEnd', 'type': 'classmethod', 'value': <classmethod object at 0x2D1BF530>},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'ValentineDayEventUtil' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiValentineDayEvent'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'ValentineDayEventUtil'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'ValentineDayEventUtil' objects>}]}],
 'func': [],
 'import': ['event', 'uiCommon', 'exception', 'valentineDayModule', 'exchange', '__builtin__', 'chatm2g', 'app', 'item', 'playerm2g2', 'ui', 'uiScriptLocale', 'ingameEventSystem', 'localeInfo', 'uiMiniGame'],
 'var': [{'name': 'ValentineDayEvent', 'type': 'ABCMeta', 'value': <class 'uiValentineDayEvent.ValentineDayEvent'>},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'uiValentineDayEvent'},
         {'name': '__package__', 'type': 'NoneType', 'value': None},
         {'name': '__test__', 'type': 'dict', 'value': {}}]}
