{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': '__BindObject'},
                     {'args': ['self', 'text'], 'defaults': [], 'name': '__ButtonOverIn'},
                     {'args': ['self'], 'defaults': [], 'name': '__ButtonOverOut'},
                     {'args': ['self', 'data_index'], 'defaults': [], 'name': '__ClickButton'},
                     {'args': ['self', 'banner_index'], 'defaults': [], 'name': '__CreateBannerButton'},
                     {'args': ['self', 'fileName'], 'defaults': [], 'name': '__LoadScript'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWebLinkedBannerData'},
                     {'args': ['self'], 'defaults': [], 'name': '__LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': '__RefreshButtonLineUp'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'DEFAULT_BANNER_IMAGE_DOWN', 'type': 'str', 'value': 'locale/de/ui/web_linked_banner/btn_strame_long_003.tga'},
                    {'name': 'DEFAULT_BANNER_IMAGE_OVER', 'type': 'str', 'value': 'locale/de/ui/web_linked_banner/btn_strame_long_002.tga'},
                    {'name': 'DEFAULT_BANNER_IMAGE_UP', 'type': 'str', 'value': 'locale/de/ui/web_linked_banner/btn_strame_long_001.tga'},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiWebLinkedBanner'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'WebLinkedBannerWindow'}]}],
 'func': [],
 'import': ['grp', 'uiToolTip', '__builtin__', 'uiWeb', 'app', 'wndMgr', 'dbg', 'm2netm2g', 'ui', 'uiScriptLocale'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiWebLinkedBanner'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
