{'class': [{'class': [],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'HideToolTip'},
                     {'args': ['self', 'text', 'x', 'y'], 'defaults': [0, 32], 'name': 'SetToolTipText'},
                     {'args': ['self', 'text', 'color', 'x', 'y'], 'defaults': [0, 32], 'name': 'SetToolTipTextWithColor'},
                     {'args': ['self'], 'defaults': [], 'name': 'ShowToolTip'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiWhisper'}, {'name': '__qualname__', 'type': 'str', 'value': 'WhisperButton'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'targetName'], 'defaults': [], 'name': 'SetTargetName'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiWhisper'}, {'name': '__qualname__', 'type': 'str', 'value': 'WhisperDialog.TextRenderer'}]},
                      {'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnMouseOverIn'}, {'args': ['self'], 'defaults': [], 'name': 'OnMouseOverOut'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiWhisper'}, {'name': '__qualname__', 'type': 'str', 'value': 'WhisperDialog.ResizeButton'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'AcceptTarget'},
                     {'args': ['self', 'interface'], 'defaults': [], 'name': 'BindInterface'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Destroy'},
                     {'args': ['self'], 'defaults': [], 'name': 'IgnoreTarget'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'Minimize'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnMouseLeftButtonDown'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnScroll'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnTop'},
                     {'args': ['self', 'targetName'], 'defaults': [], 'name': 'OpenWithTarget'},
                     {'args': ['self', 'event'], 'defaults': [], 'name': 'OpenWithoutTarget'},
                     {'args': ['self'], 'defaults': [], 'name': 'ReportViolentWhisper'},
                     {'args': ['self'], 'defaults': [], 'name': 'ResizeWhisperDialog'},
                     {'args': ['self'], 'defaults': [], 'name': 'SendWhisper'},
                     {'args': ['self', 'max'], 'defaults': [], 'name': 'SetChatLineMax'},
                     {'args': ['self'], 'defaults': [], 'name': 'SetGameMasterLook'},
                     {'args': ['self', 'width', 'height'], 'defaults': [], 'name': 'SetWhisperDialogSize'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnAddFriend'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnBlockFriend'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCancelAddFriend'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnCancelBlockFriend'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnPressAddFriendButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__OnPressBlockButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self', 'eventMinimize', 'eventClose'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': '_WhisperDialog__add_friend_button', 'type': 'member_descriptor', 'value': <member '_WhisperDialog__add_friend_button' of 'WhisperDialog' objects>},
                    {'name': '_WhisperDialog__block_button', 'type': 'member_descriptor', 'value': <member '_WhisperDialog__block_button' of 'WhisperDialog' objects>},
                    {'name': '_WhisperDialog__block_friend_name_board', 'type': 'member_descriptor', 'value': <member '_WhisperDialog__block_friend_name_board' of 'WhisperDialog' objects>},
                    {'name': '_WhisperDialog__friend_name_board', 'type': 'member_descriptor', 'value': <member '_WhisperDialog__friend_name_board' of 'WhisperDialog' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiWhisper'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'WhisperDialog'},
                    {'name': '__slots__', 'type': 'tuple', 'value': ('__add_friend_button', '__block_button', '__block_friend_name_board', '__friend_name_board')}]}],
 'func': [],
 'import': ['uiCommon', 'ime', '__builtin__', 'chatm2g', 'app', 'chr', 'm2netm2g', 'playerm2g2', 'ui', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiWhisper'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
