{'class': [{'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self', 'rank', 'name', 'guild_name', 'empire_img', 'tier'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiWorldBoss'}, {'name': '__qualname__', 'type': 'str', 'value': 'WorldBossRanking.ItemInfo'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self', 'rank'], 'defaults': [], 'name': 'GetTierFromRank'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self', 'page_button_index'], 'defaults': [0], 'name': 'RefreshRankingList'},
                     {'args': ['self'], 'defaults': [], 'name': '__FirstButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__LastButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__NextButton'},
                     {'args': ['self', 'button_index'], 'defaults': [], 'name': '__OnClickPageButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__PrevButton'},
                     {'args': ['self', 'page_index'], 'defaults': [], 'name': '__SelectPage'},
                     {'args': ['self'], 'defaults': [], 'name': '__SetButton'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'M2EMPIRE_ICON', 'type': 'dict', 'value': {0: 'd:/ymir work/ui/public/battle/empire_empty.sub', 1: 'd:/ymir work/ui/public/battle/empire_shinsu.sub', 2: 'd:/ymir work/ui/public/battle/empire_chunjo.sub', 3: 'd:/ymir work/ui/public/battle/empire_jinno.sub'}},
                    {'name': 'MAX_PAGE_BUTTON_SHOW', 'type': 'int', 'value': 5},
                    {'name': 'MAX_RANKING_PAGE', 'type': 'int', 'value': 10},
                    {'name': 'PAGE_NORMAL_TEXT_COLOR', 'type': 'long', 'value': 4294967295L},
                    {'name': 'PAGE_SELECT_TEXT_COLOR', 'type': 'long', 'value': 4283317552L},
                    {'name': 'SHOW_ITEM_COUNT', 'type': 'int', 'value': 10},
                    {'name': 'WORLD_BOSS_RANK_1_MAX', 'type': 'int', 'value': 10},
                    {'name': 'WORLD_BOSS_RANK_1_MIN', 'type': 'int', 'value': 1},
                    {'name': 'WORLD_BOSS_RANK_2_MAX', 'type': 'int', 'value': 25},
                    {'name': 'WORLD_BOSS_RANK_2_MIN', 'type': 'int', 'value': 11},
                    {'name': 'WORLD_BOSS_RANK_3_MAX', 'type': 'int', 'value': 100},
                    {'name': 'WORLD_BOSS_RANK_3_MIN', 'type': 'int', 'value': 26},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiWorldBoss'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'WorldBossRanking'}]},
           {'class': [{'class': [],
                       'func': [{'args': ['self'], 'defaults': [], 'name': 'OnRender'}, {'args': ['self', 'index'], 'defaults': [], 'name': 'SetIndex'}, {'args': ['self'], 'defaults': [], 'name': '__del__'}, {'args': ['self'], 'defaults': [], 'name': '__init__'}],
                       'import': [],
                       'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__module__', 'type': 'str', 'value': 'uiWorldBoss'}, {'name': '__qualname__', 'type': 'str', 'value': 'WorldBoss.DescriptionBox'}]}],
            'func': [{'args': ['self'], 'defaults': [], 'name': 'ClickRankingButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'ClickRewardButton'},
                     {'args': ['self'], 'defaults': [], 'name': 'Close'},
                     {'args': ['self'], 'defaults': [], 'name': 'Initialize'},
                     {'args': ['self'], 'defaults': [], 'name': 'LoadWindow'},
                     {'args': ['self'], 'defaults': [], 'name': 'NextDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnPressEscapeKey'},
                     {'args': ['self'], 'defaults': [], 'name': 'OnUpdate'},
                     {'args': ['self'], 'defaults': [], 'name': 'Open'},
                     {'args': ['self'], 'defaults': [], 'name': 'PrevDescriptionPage'},
                     {'args': ['self'], 'defaults': [], 'name': 'RefreshRankingList'},
                     {'args': ['self', 'type', 'data'], 'defaults': [None], 'name': 'WorldBossProcess'},
                     {'args': ['self'], 'defaults': [], 'name': '__del__'},
                     {'args': ['self'], 'defaults': [], 'name': '__init__'}],
            'import': [],
            'var': [{'name': 'STATE_TEXT_COLOR', 'type': 'long', 'value': 4290945094L},
                    {'name': 'WORLD_BOSS_STATE_BOSS_KILLED', 'type': 'int', 'value': 3},
                    {'name': 'WORLD_BOSS_STATE_BOSS_SPAWNED', 'type': 'int', 'value': 2},
                    {'name': 'WORLD_BOSS_STATE_BREAK_TIME', 'type': 'int', 'value': 4},
                    {'name': 'WORLD_BOSS_STATE_END_CYCLE', 'type': 'int', 'value': 5},
                    {'name': 'WORLD_BOSS_STATE_NONE', 'type': 'int', 'value': 0},
                    {'name': 'WORLD_BOSS_STATE_WAIT_FOR_SPAWN', 'type': 'int', 'value': 1},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'uiWorldBoss'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'WorldBoss'}]}],
 'func': [],
 'import': ['event', 'uiCommon', 'ranking', '__builtin__', 'chatm2g', 'app', 'uiScriptLocale', 'm2netm2g', 'playerm2g2', 'ui', 'wndMgr', 'localeInfo'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'uiWorldBoss'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
