{'class': [{'class': [],
            'func': [{'args': ['self', 'prevent_imported_modules', 'allowed_modules', 'prevented_modules', 'allowed_paths'], 'defaults': [False, [], [], []], 'name': '__init__'},
                     {'args': ['self', 'allowed_modules'], 'defaults': [], 'name': 'add_allowed_modules'},
                     {'args': ['self', 'prevented_modules'], 'defaults': [], 'name': 'add_prevented_modules'},
                     {'args': ['self', 'filename', 'dic'], 'defaults': [], 'name': 'execfile'}],
            'import': [],
            'var': [{'name': 'WHITE_LIST', 'type': 'list', 'value': ['__builtin__', 'types', 'utils', '__main__', 'sys']},
                    {'name': '__dict__', 'type': 'getset_descriptor', 'value': <attribute '__dict__' of 'Sandbox' objects>},
                    {'name': '__doc__', 'type': 'NoneType', 'value': None},
                    {'name': '__module__', 'type': 'str', 'value': 'utils'},
                    {'name': '__qualname__', 'type': 'str', 'value': 'Sandbox'},
                    {'name': '__weakref__', 'type': 'getset_descriptor', 'value': <attribute '__weakref__' of 'Sandbox' objects>}]}],
 'func': [],
 'import': ['__builtin__'],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'utils'}, {'name': '__package__', 'type': 'NoneType', 'value': None}, {'name': '__test__', 'type': 'dict', 'value': {}}]}
