{'Console': <consoleModule.Console object at 0x2D399630>,
 'EditLine': <consoleModule.ConsoleEditLine object at 0x2D399CF0>,
 'ResizingButton': <consoleModule.ResizingButton object at 0x2D399D90>,
 'TextList': [],
 'functionDict': {'hidecursor': <unbound method Console.HideCursor>,
                  'hideui': <unbound method Console.HideUI>,
                  'loadcmr': <unbound method Console.LoadCameraSetting>,
                  'restorerm': <unbound method Console.RestoreCharacterRenderModeType>,
                  'savecmr': <unbound method Console.SaveCameraSetting>,
                  'setcmrz': <unbound method Console.SetcmrZ>,
                  'setcspd': <unbound method Console.SetCameraSpeed>,
                  'setdefcmr': <unbound method Console.SetDefaultCamera>,
                  'setrmadd': <unbound method Console.SetCharacterRenderModeTypeAdd>,
                  'setrmaddrgb': <unbound method Console.SetCharacterRenderModeTypeAddRGB>,
                  'setrmmod': <unbound method Console.SetCharacterRenderModeTypeMod>,
                  'setrmmodrgb': <unbound method Console.SetCharacterRenderModeTypeModRGB>,
                  'setspec': <unbound method Console.SetCharacterRenderModeSpecular>,
                  'shadowquality': <unbound method Console.SetShadowQualityLevel>,
                  'shadowtarget': <unbound method Console.SetShadowTargetLevel>,
                  'showcursor': <unbound method Console.ShowCursor>,
                  'showui': <unbound method Console.ShowUI>,
                  'splat': <unbound method Console.SetSplatLimit>},
 'game': 0,
 'gx': 0,
 'gxButton': 100,
 'gxEditLine': 7,
 'gy': 0,
 'gyButton': 100,
 'gyEditLine': -20,
 'hWnd': 740727656,
 'height': 0,
 'heightButton': 15,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'width': 0,
 'widthButton': 15,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
