{'Children': [<ui.BoardWithTitleBar object at 0x2D399BF0>],
 'ElementDictionary': {'base_pattern': <ui.ScriptWindow object at 0x2D399C30>,
                       'board': <ui.BoardWithTitleBar object at 0x2D399BF0>,
                       'init_button': <ui.Button object at 0x2D399890>,
                       'message_bg': <ui.ImageBox object at 0x2D116050>,
                       'message_text': <ui.TextLine object at 0x2D116070>,
                       'message_window': <ui.ScriptWindow object at 0x2D116030>,
                       'object_area_window': <ui.ScriptWindow object at 0x2D399810>,
                       'pattern_bottom_center_img': <ui.ExpandedImageBox object at 0x2D399D30>,
                       'pattern_center_img': <ui.ExpandedImageBox object at 0x2D399690>,
                       'pattern_left_bottom_img': <ui.ImageBox object at 0x2D399FD0>,
                       'pattern_left_center_img': <ui.ExpandedImageBox object at 0x2D399C90>,
                       'pattern_left_top_img': <ui.ImageBox object at 0x2D399DB0>,
                       'pattern_right_bottom_img': <ui.ImageBox object at 0x2D399CB0>,
                       'pattern_right_center_img': <ui.ExpandedImageBox object at 0x2D3997D0>,
                       'pattern_right_top_img': <ui.ImageBox object at 0x2D399770>,
                       'pattern_top_cetner_img': <ui.ExpandedImageBox object at 0x2D399FB0>,
                       'save_button': <ui.Button object at 0x2D3993F0>,
                       'scroll_bar': <ui.ScrollBar object at 0x2D399930>},
 '_LootingSystem__init_button': <ui.Button object at 0x2D399890>,
 '_LootingSystem__save_button': <ui.Button object at 0x2D3993F0>,
 'hWnd': 740728488,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
