{'Children': [<ui.BoardWithTitleBar object at 0x2E152870>],
 'ElementDictionary': {'base_pattern': <ui.ScriptWindow object at 0x2E152DD0>,
                       'board': <ui.BoardWithTitleBar object at 0x2E152870>,
                       'init_button': <ui.Button object at 0x2E074FD0>,
                       'message_bg': <ui.ImageBox object at 0x2E074EF0>,
                       'message_text': <ui.TextLine object at 0x2E15E030>,
                       'message_window': <ui.ScriptWindow object at 0x2E074E50>,
                       'object_area_window': <ui.ScriptWindow object at 0x2E152C90>,
                       'pattern_bottom_center_img': <ui.ExpandedImageBox object at 0x2E152F10>,
                       'pattern_center_img': <ui.ExpandedImageBox object at 0x2E152A90>,
                       'pattern_left_bottom_img': <ui.ImageBox object at 0x2E152E30>,
                       'pattern_left_center_img': <ui.ExpandedImageBox object at 0x2E1523B0>,
                       'pattern_left_top_img': <ui.ImageBox object at 0x2E1526B0>,
                       'pattern_right_bottom_img': <ui.ImageBox object at 0x2E152750>,
                       'pattern_right_center_img': <ui.ExpandedImageBox object at 0x2E152430>,
                       'pattern_right_top_img': <ui.ImageBox object at 0x2E152F50>,
                       'pattern_top_cetner_img': <ui.ExpandedImageBox object at 0x2E1528F0>,
                       'save_button': <ui.Button object at 0x2E074CF0>,
                       'scroll_bar': <ui.ScrollBar object at 0x2E074C10>},
 '_LootingSystem__init_button': <ui.Button object at 0x2E074FD0>,
 '_LootingSystem__save_button': <ui.Button object at 0x2E074CF0>,
 'hWnd': 756600032,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
