{'UseCodePage': True,
 'bCodePage': False,
 'candidateWindow': <ui.EmptyCandidateWindow object at 0x2B0F4210>,
 'candidateWindowClass': <class 'ui.EmptyCandidateWindow'>,
 'eventEscape': <bound method type.NoneMethod of <class 'ui.Window'>>,
 'eventReturn': <bound method type.NoneMethod of <class 'ui.Window'>>,
 'eventTab': None,
 'hWnd': 680631240,
 'horizontal_align': 1,
 'is_movable': False,
 'max': 0,
 'numberMode': False,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pos_interval_x': 0,
 'pos_interval_y': 0,
 'readingWnd': <ui.ReadingWnd object at 0x2B0F4F70>,
 'useIME': True,
 'vertical_align': 16,
 'widthcheckenable': False,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
