{'eventArgs': {'mouse_click': None, 'mouse_down': None, 'mouse_over_in': None, 'mouse_over_out': None},
 'eventDict': {},
 'eventFunc': {'mouse_click': None, 'mouse_down': None, 'mouse_over_in': None, 'mouse_over_out': None},
 'filePath': '',
 'hWnd': 755015440,
 'lovePoint': 0,
 'loverName': '',
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'potionType': 0,
 'toolTip': <uiToolTip.ToolTip object at 0x26DA0FD0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
