{'Children': [<ui.Board object at 0x2B000110>],
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x2B000430>,
                       'AttachMetinArrow': <ui.ImageBox object at 0x2B000390>,
                       'Board': <ui.Board object at 0x2B000110>,
                       'CancelButton': <ui.Button object at 0x2B000470>,
                       'MetinImage': <ui.ImageBox object at 0x2B0003F0>,
                       'MetinSlot': <ui.ImageBox object at 0x2B000190>,
                       'Question': <ui.TextLine object at 0x2B000410>,
                       'TitleBar': <ui.TitleBar object at 0x2B000370>,
                       'TitleName': <ui.TextLine object at 0x2B0001D0>},
 '_AttachMetinDialog__wnd_inventory': None,
 'board': <ui.Board object at 0x2B000110>,
 'hWnd': 821326472,
 'metinImage': <ui.ImageBox object at 0x2B0003F0>,
 'metinItemPos': 0,
 'metinItemWindow': None,
 'newToolTip': <uiToolTip.ItemToolTip object at 0x2B000590>,
 'oldToolTip': <uiToolTip.ItemToolTip object at 0x2B042DD0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'targetItemPos': 0,
 'targetItemWindow': None,
 'titleBar': <ui.TitleBar object at 0x2B000370>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
