{'Children': [<ui.Board object at 0x2D0F9050>],
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x2D0F9C70>,
                       'AttachMetinArrow': <ui.ImageBox object at 0x2D0F93D0>,
                       'Board': <ui.Board object at 0x2D0F9050>,
                       'CancelButton': <ui.Button object at 0x2D0F9190>,
                       'MetinImage': <ui.ImageBox object at 0x2D0F9370>,
                       'MetinSlot': <ui.ImageBox object at 0x2D0F9350>,
                       'Question': <ui.TextLine object at 0x2D0F9D10>,
                       'TitleBar': <ui.TitleBar object at 0x2D0F9230>,
                       'TitleName': <ui.TextLine object at 0x2D0F99D0>},
 '_AttachMetinDialog__wnd_inventory': None,
 'board': <ui.Board object at 0x2D0F9050>,
 'hWnd': 744846176,
 'metinImage': <ui.ImageBox object at 0x2D0F9370>,
 'metinItemPos': 0,
 'metinItemWindow': None,
 'newToolTip': <uiToolTip.ItemToolTip object at 0x2D0F92B0>,
 'oldToolTip': <uiToolTip.ItemToolTip object at 0x2D0F9E30>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'targetItemPos': 0,
 'targetItemWindow': None,
 'titleBar': <ui.TitleBar object at 0x2D0F9230>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
