{'Children': [<ui.Board object at 0x2E278B90>],
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x2E278770>,
                       'AttachMetinArrow': <ui.ImageBox object at 0x2E2781D0>,
                       'Board': <ui.Board object at 0x2E278B90>,
                       'CancelButton': <ui.Button object at 0x2E278370>,
                       'MetinImage': <ui.ImageBox object at 0x2E278970>,
                       'MetinSlot': <ui.ImageBox object at 0x2E2785F0>,
                       'Question': <ui.TextLine object at 0x2E278490>,
                       'TitleBar': <ui.TitleBar object at 0x2E278410>,
                       'TitleName': <ui.TextLine object at 0x2E278F50>},
 '_AttachMetinDialog__wnd_inventory': None,
 'board': <ui.Board object at 0x2E278B90>,
 'hWnd': 701789136,
 'metinImage': <ui.ImageBox object at 0x2E278970>,
 'metinItemPos': 0,
 'metinItemWindow': None,
 'newToolTip': <uiToolTip.ItemToolTip object at 0x2E278DD0>,
 'oldToolTip': <uiToolTip.ItemToolTip object at 0x2E047050>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'targetItemPos': 0,
 'targetItemWindow': None,
 'titleBar': <ui.TitleBar object at 0x2E278410>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
