{'Children': [<ui.BoardWithTitleBar object at 0x2E0FF110>],
 'ElementDictionary': {'AutoAllClearButton': <ui.Button object at 0x1B35EAB0>,
                       'AutoAttackButton': <ui.ToggleButton object at 0x1B35E870>,
                       'AutoPotionButton': <ui.ToggleButton object at 0x1B35E910>,
                       'AutoPotionClearButton': <ui.Button object at 0x1B35E130>,
                       'AutoRangeButton': <ui.ToggleButton object at 0x1B35E8D0>,
                       'AutoRestartHereButton': <ui.ToggleButton object at 0x1B35E990>,
                       'AutoSaveOnButton': <ui.Button object at 0x1B35E9D0>,
                       'AutoSkillButton': <ui.ToggleButton object at 0x1B35E950>,
                       'AutoSkillClearButton': <ui.Button object at 0x2E0FF390>,
                       'AutoStartOffButton': <ui.Button object at 0x1B35EA50>,
                       'AutoStartOnButton': <ui.Button object at 0x1B35EA10>,
                       'AutoToolTipButton': <ui.Button object at 0x1B35EA90>,
                       'Auto_Active_Skill_Slot_Table': <ui.SlotWindow object at 0x2E0FF230>,
                       'BaseInfo': <ui.TextLine object at 0x1B35E890>,
                       'HorizontalBar1': <ui.HorizontalBar object at 0x1B35E150>,
                       'attack_text_bar': <ui.ImageBox object at 0x1B35E710>,
                       'board': <ui.BoardWithTitleBar object at 0x2E0FF110>,
                       'cool_time_Image0': <ui.ImageBox object at 0x2E0FF3B0>,
                       'cool_time_Image1': <ui.ImageBox object at 0x2E0FF8F0>,
                       'cool_time_Image10': <ui.ImageBox object at 0x2E0FFB50>,
                       'cool_time_Image11': <ui.ImageBox object at 0x2E0FFB90>,
                       'cool_time_Image12': <ui.ImageBox object at 0x2E0FFCB0>,
                       'cool_time_Image13': <ui.ImageBox object at 0x2E0FFF10>,
                       'cool_time_Image14': <ui.ImageBox object at 0x2E0FFFB0>,
                       'cool_time_Image15': <ui.ImageBox object at 0x2E0FF710>,
                       'cool_time_Image16': <ui.ImageBox object at 0x2E0FFA70>,
                       'cool_time_Image17': <ui.ImageBox object at 0x2E0FFDD0>,
                       'cool_time_Image18': <ui.ImageBox object at 0x2E0FFC90>,
                       'cool_time_Image19': <ui.ImageBox object at 0x2E0FFE50>,
                       'cool_time_Image2': <ui.ImageBox object at 0x2E0FF650>,
                       'cool_time_Image20': <ui.ImageBox object at 0x2E0FFD90>,
                       'cool_time_Image21': <ui.ImageBox object at 0x1B35E230>,
                       'cool_time_Image22': <ui.ImageBox object at 0x1B35E3F0>,
                       'cool_time_Image23': <ui.ImageBox object at 0x1B35E2F0>,
                       'cool_time_Image3': <ui.ImageBox object at 0x2E0FF830>,
                       'cool_time_Image4': <ui.ImageBox object at 0x2E0FFBD0>,
                       'cool_time_Image5': <ui.ImageBox object at 0x2E0FFDB0>,
                       'cool_time_Image6': <ui.ImageBox object at 0x2E0FF730>,
                       'cool_time_Image7': <ui.ImageBox object at 0x2E0FFD30>,
                       'cool_time_Image8': <ui.ImageBox object at 0x2E0FFA90>,
                       'cool_time_Image9': <ui.ImageBox object at 0x2E0FF4F0>,
                       'editline0': <ui.EditLine object at 0x2E0FF670>,
                       'editline1': <ui.EditLine object at 0x2E0FF610>,
                       'editline10': <ui.EditLine object at 0x2E0FFB10>,
                       'editline11': <ui.EditLine object at 0x2E0FF550>,
                       'editline12': <ui.EditLine object at 0x2E0FFE90>,
                       'editline13': <ui.EditLine object at 0x2E0FFF30>,
                       'editline14': <ui.EditLine object at 0x2E0FFFD0>,
                       'editline15': <ui.EditLine object at 0x2E0FFB30>,
                       'editline16': <ui.EditLine object at 0x2E0FFE30>,
                       'editline17': <ui.EditLine object at 0x2E0FF9D0>,
                       'editline18': <ui.EditLine object at 0x2E0FF3D0>,
                       'editline19': <ui.EditLine object at 0x2E0FF970>,
                       'editline2': <ui.EditLine object at 0x2E0FF590>,
                       'editline20': <ui.EditLine object at 0x2E0FF210>,
                       'editline21': <ui.EditLine object at 0x1B35E250>,
                       'editline22': <ui.EditLine object at 0x1B35E410>,
                       'editline23': <ui.EditLine object at 0x1B35E350>,
                       'editline3': <ui.EditLine object at 0x2E0FF470>,
                       'editline4': <ui.EditLine object at 0x2E0FFAF0>,
                       'editline5': <ui.EditLine object at 0x2E0FF950>,
                       'editline6': <ui.EditLine object at 0x2E0FF7F0>,
                       'editline7': <ui.EditLine object at 0x2E0FF770>,
                       'editline8': <ui.EditLine object at 0x2E0FFA10>,
                       'editline9': <ui.EditLine object at 0x2E0FF990>,
                       'potion_text_bar': <ui.ImageBox object at 0x1B35E030>,
                       'range_text_bar': <ui.ImageBox object at 0x1B35E750>,
                       'restart_text_bar': <ui.ImageBox object at 0x1B35E850>,
                       'skill_text_bar': <ui.ImageBox object at 0x1B35E7D0>},
 'hWnd': 787427392,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
