{'Children': [<ui.BoardWithTitleBar object at 0x2DE89970>],
 'ElementDictionary': {'AutoAllClearButton': <ui.Button object at 0x2E15DAD0>,
                       'AutoAttackButton': <ui.ToggleButton object at 0x2E15D030>,
                       'AutoPotionButton': <ui.ToggleButton object at 0x2E15DF50>,
                       'AutoPotionClearButton': <ui.Button object at 0x2E15DFF0>,
                       'AutoRangeButton': <ui.ToggleButton object at 0x2E15D390>,
                       'AutoRestartHereButton': <ui.ToggleButton object at 0x2E15DC50>,
                       'AutoSaveOnButton': <ui.Button object at 0x2E15D790>,
                       'AutoSkillButton': <ui.ToggleButton object at 0x2E15DA50>,
                       'AutoSkillClearButton': <ui.Button object at 0x2E15E490>,
                       'AutoStartOffButton': <ui.Button object at 0x2E15D9D0>,
                       'AutoStartOnButton': <ui.Button object at 0x2E15DED0>,
                       'AutoToolTipButton': <ui.Button object at 0x2E15DF90>,
                       'Auto_Active_Skill_Slot_Table': <ui.SlotWindow object at 0x2E15E9F0>,
                       'BaseInfo': <ui.TextLine object at 0x2E15D110>,
                       'HorizontalBar1': <ui.HorizontalBar object at 0x2E15D310>,
                       'attack_text_bar': <ui.ImageBox object at 0x2E15D330>,
                       'board': <ui.BoardWithTitleBar object at 0x2DE89970>,
                       'cool_time_Image0': <ui.ImageBox object at 0x2E15E290>,
                       'cool_time_Image1': <ui.ImageBox object at 0x2E15E3D0>,
                       'cool_time_Image10': <ui.ImageBox object at 0x2E15E2D0>,
                       'cool_time_Image11': <ui.ImageBox object at 0x2E15EFB0>,
                       'cool_time_Image12': <ui.ImageBox object at 0x2E15E5B0>,
                       'cool_time_Image13': <ui.ImageBox object at 0x2E15E150>,
                       'cool_time_Image14': <ui.ImageBox object at 0x2E15E310>,
                       'cool_time_Image15': <ui.ImageBox object at 0x2E152C70>,
                       'cool_time_Image16': <ui.ImageBox object at 0x2E152A50>,
                       'cool_time_Image17': <ui.ImageBox object at 0x2E1528F0>,
                       'cool_time_Image18': <ui.ImageBox object at 0x2E152410>,
                       'cool_time_Image19': <ui.ImageBox object at 0x2E152F30>,
                       'cool_time_Image2': <ui.ImageBox object at 0x2E15E370>,
                       'cool_time_Image20': <ui.ImageBox object at 0x2E152570>,
                       'cool_time_Image21': <ui.ImageBox object at 0x2E1523F0>,
                       'cool_time_Image22': <ui.ImageBox object at 0x2E15DE90>,
                       'cool_time_Image23': <ui.ImageBox object at 0x2E15D2B0>,
                       'cool_time_Image3': <ui.ImageBox object at 0x2E15E130>,
                       'cool_time_Image4': <ui.ImageBox object at 0x2E15E230>,
                       'cool_time_Image5': <ui.ImageBox object at 0x2E15EEB0>,
                       'cool_time_Image6': <ui.ImageBox object at 0x2E15EDB0>,
                       'cool_time_Image7': <ui.ImageBox object at 0x2E15ECF0>,
                       'cool_time_Image8': <ui.ImageBox object at 0x2E15EB70>,
                       'cool_time_Image9': <ui.ImageBox object at 0x2E15E110>,
                       'editline0': <ui.EditLine object at 0x2E15EA50>,
                       'editline1': <ui.EditLine object at 0x2E15E1D0>,
                       'editline10': <ui.EditLine object at 0x2E15E510>,
                       'editline11': <ui.EditLine object at 0x2E15EFD0>,
                       'editline12': <ui.EditLine object at 0x2E15EBD0>,
                       'editline13': <ui.EditLine object at 0x2E15EA10>,
                       'editline14': <ui.EditLine object at 0x2E152950>,
                       'editline15': <ui.EditLine object at 0x2E152290>,
                       'editline16': <ui.EditLine object at 0x2E152BB0>,
                       'editline17': <ui.EditLine object at 0x2E152EB0>,
                       'editline18': <ui.EditLine object at 0x2E152990>,
                       'editline19': <ui.EditLine object at 0x2E152C90>,
                       'editline2': <ui.EditLine object at 0x2E15E8B0>,
                       'editline20': <ui.EditLine object at 0x2E152B50>,
                       'editline21': <ui.EditLine object at 0x2E152430>,
                       'editline22': <ui.EditLine object at 0x2E15D9B0>,
                       'editline23': <ui.EditLine object at 0x2E15D590>,
                       'editline3': <ui.EditLine object at 0x2E15E750>,
                       'editline4': <ui.EditLine object at 0x2E15E990>,
                       'editline5': <ui.EditLine object at 0x2E15EC90>,
                       'editline6': <ui.EditLine object at 0x2E15E6F0>,
                       'editline7': <ui.EditLine object at 0x2E15E810>,
                       'editline8': <ui.EditLine object at 0x2E15E0D0>,
                       'editline9': <ui.EditLine object at 0x2E15E450>,
                       'potion_text_bar': <ui.ImageBox object at 0x2E15D0B0>,
                       'range_text_bar': <ui.ImageBox object at 0x2E15DA70>,
                       'restart_text_bar': <ui.ImageBox object at 0x2E15D3D0>,
                       'skill_text_bar': <ui.ImageBox object at 0x2E15DFD0>},
 'hWnd': 701794752,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
