{'Children': [<ui.ThinBoard object at 0x2E45A210>],
 'ElementDictionary': {'board': <ui.ThinBoard object at 0x2E45A210>, 'dead_by_text': <ui.TextLine object at 0x2E083A10>, 'personal_rank_text': <ui.TextLine object at 0x2E083990>, 'return_village_button': <ui.Button object at 0x2E083ED0>},
 'board': <ui.ThinBoard object at 0x2E45A210>,
 'hWnd': 851299632,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'personal_rank_text': <ui.TextLine object at 0x2E083990>,
 'return_village_button': <ui.Button object at 0x2E083ED0>,
 'who_killed_text': <ui.TextLine object at 0x2E083A10>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
