{'Children': [<ui.ThinBoard object at 0x2B0E14D0>],
 'ElementDictionary': {'board': <ui.ThinBoard object at 0x2B0E14D0>, 'dead_by_text': <ui.TextLine object at 0x2B00B670>, 'personal_rank_text': <ui.TextLine object at 0x2B00BFB0>, 'return_village_button': <ui.Button object at 0x2B00B250>},
 'board': <ui.ThinBoard object at 0x2B0E14D0>,
 'hWnd': 821348272,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'personal_rank_text': <ui.TextLine object at 0x2B00BFB0>,
 'return_village_button': <ui.Button object at 0x2B00B250>,
 'who_killed_text': <ui.TextLine object at 0x2B00B670>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
