{'CHAT_MODE_NAME': {0: 'Norm\xe1lis', 3: 'Csoport', 4: 'C\xe9h', 6: 'H\xedv\xe1s'},
 'UseCodePage': True,
 'bCodePage': True,
 'candidateWindow': <ui.EmptyCandidateWindow object at 0x30A3D950>,
 'candidateWindowClass': <class 'ui.EmptyCandidateWindow'>,
 'chatMode': 0,
 'eventEscape': <cyfunction ChatLine.__init__.<locals>.<lambda> at 0x30A31190>,
 'eventReturn': <cyfunction ChatLine.__init__.<locals>.<lambda> at 0x30A31558>,
 'eventTab': None,
 'hWnd': 733464392,
 'horizontal_align': 1,
 'lastSentencePos': 0,
 'lastSentenceStack': [],
 'lastShoutTime': 0,
 'max': 0,
 'numberMode': False,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'overTextLine': <ui.TextLine object at 0x30A3DA50>,
 'parentWindow': 0,
 'pos_interval_x': 0,
 'pos_interval_y': 0,
 'readingWnd': <ui.ReadingWnd object at 0x30A3D910>,
 'useIME': True,
 'vertical_align': 16,
 'widthcheckenable': False,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
