{'Children': [<ui.BoardWithTitleBar object at 0x2B258E90>],
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x2AFFF150>,
                       'CancelButton': <ui.Button object at 0x2AFFF190>,
                       'ChequeValue': <ui.TextLine object at 0x2AFFF110>,
                       'Cheque_Icon': <ui.ImageBox object at 0x2B2587D0>,
                       'InputSlot': <ui.SlotBar object at 0x2AFFF030>,
                       'InputSlot_Cheque': <ui.SlotBar object at 0x2B2582D0>,
                       'InputValue': <ui.EditLine object at 0x2AFFF070>,
                       'InputValue_Cheque': <ui.EditLine object at 0x2B258BB0>,
                       'MoneyValue': <ui.TextLine object at 0x2AFFF130>,
                       'Money_Icon': <ui.ImageBox object at 0x2AFFF050>,
                       'SellInfoText': <ui.TextLine object at 0x2AFFF0F0>,
                       'board': <ui.BoardWithTitleBar object at 0x2B258E90>},
 'acceptButton': <ui.Button object at 0x2AFFF150>,
 'board': <ui.BoardWithTitleBar object at 0x2B258E90>,
 'cancelButton': <ui.Button object at 0x2AFFF190>,
 'chequeText': <ui.TextLine object at 0x2AFFF110>,
 'hWnd': 821382872,
 'inputChequeValue': <ui.EditLine object at 0x2B258BB0>,
 'inputValue': <ui.EditLine object at 0x2AFFF070>,
 'moneyHeaderText': 'Elad\xe1si \xe1ra:',
 'moneyText': <ui.TextLine object at 0x2AFFF130>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
