{'Children': [<ui.BoardWithTitleBar object at 0x2DEDE470>],
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x2E49EB30>,
                       'CancelButton': <ui.Button object at 0x2E49EB70>,
                       'ChequeValue': <ui.TextLine object at 0x2E49EAF0>,
                       'Cheque_Icon': <ui.ImageBox object at 0x2E49E970>,
                       'InputSlot': <ui.SlotBar object at 0x2E49E9F0>,
                       'InputSlot_Cheque': <ui.SlotBar object at 0x2E49E950>,
                       'InputValue': <ui.EditLine object at 0x2E49EA30>,
                       'InputValue_Cheque': <ui.EditLine object at 0x2E49E990>,
                       'MoneyValue': <ui.TextLine object at 0x2E49EB10>,
                       'Money_Icon': <ui.ImageBox object at 0x2E49EA10>,
                       'SellInfoText': <ui.TextLine object at 0x2E49EAD0>,
                       'board': <ui.BoardWithTitleBar object at 0x2DEDE470>},
 'acceptButton': <ui.Button object at 0x2E49EB30>,
 'board': <ui.BoardWithTitleBar object at 0x2DEDE470>,
 'cancelButton': <ui.Button object at 0x2E49EB70>,
 'chequeText': <ui.TextLine object at 0x2E49EAF0>,
 'hWnd': 701761216,
 'inputChequeValue': <ui.EditLine object at 0x2E49E990>,
 'inputValue': <ui.EditLine object at 0x2E49EA30>,
 'moneyHeaderText': 'Elad\xe1si \xe1ra:',
 'moneyText': <ui.TextLine object at 0x2E49EB10>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
