{'Children': [<ui.Board object at 0x308CD410>],
 'ElementDictionary': {'MallOpenButton': <ui.Button object at 0x30A3CD90>, 'TitleBar': <ui.TitleBar object at 0x30A3C8B0>, 'TitleName': <ui.TextLine object at 0x30A3CE50>, 'board': <ui.Board object at 0x308CD410>},
 'hWnd': 731198112,
 'interface': None,
 'isShow': False,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'saveUrl': '',
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
