{'Children': [<ui.Board object at 0x2D3C19F0>],
 'ElementDictionary': {'MallOpenButton': <ui.Button object at 0x2D0ECCB0>, 'TitleBar': <ui.TitleBar object at 0x2D0EC730>, 'TitleName': <ui.TextLine object at 0x2D0ECFD0>, 'board': <ui.Board object at 0x2D3C19F0>},
 'hWnd': 745385224,
 'interface': None,
 'isShow': False,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'saveUrl': '',
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
