{'Children': [<ui.Board object at 0x2E152410>],
 'ElementDictionary': {'MallOpenButton': <ui.Button object at 0x2E152750>, 'TitleBar': <ui.TitleBar object at 0x2E152F50>, 'TitleName': <ui.TextLine object at 0x2E1523D0>, 'board': <ui.Board object at 0x2E152410>},
 'hWnd': 758348504,
 'interface': None,
 'isShow': False,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'saveUrl': '',
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
