{'Children': [<ui.BoardWithTitleBar object at 0x2BED0F70>],
 'ElementDictionary': {'Board': <ui.BoardWithTitleBar object at 0x2BED0F70>, 'EquipmentBaseImage': <ui.ImageBox object at 0x2C0486D0>, 'EquipmentSlot': <ui.SlotWindow object at 0x2C0483B0>},
 'board': <ui.BoardWithTitleBar object at 0x2BED0F70>,
 'eventClose': None,
 'hWnd': 788241040,
 'itemDataDict': {},
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'slotWindow': <ui.SlotWindow object at 0x2C0483B0>,
 'tooltipItem': None,
 'vid': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
