{'Children': [<ui.BoardWithTitleBar object at 0x2E9B1BF0>],
 'ElementDictionary': {'Board': <ui.BoardWithTitleBar object at 0x2E9B1BF0>, 'EquipmentBaseImage': <ui.ImageBox object at 0x2E99D110>, 'EquipmentSlot': <ui.SlotWindow object at 0x2E99D0B0>},
 'board': <ui.BoardWithTitleBar object at 0x2E9B1BF0>,
 'eventClose': None,
 'hWnd': 708273568,
 'itemDataDict': {},
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'slotWindow': <ui.SlotWindow object at 0x2E99D0B0>,
 'tooltipItem': None,
 'vid': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
