{'Children': [<ui.BoardWithTitleBar object at 0x2E095250>],
 'ElementDictionary': {'Board': <ui.BoardWithTitleBar object at 0x2E095250>, 'EquipmentBaseImage': <ui.ImageBox object at 0x2E095C10>, 'EquipmentSlot': <ui.SlotWindow object at 0x2E095C50>},
 'board': <ui.BoardWithTitleBar object at 0x2E095250>,
 'eventClose': None,
 'hWnd': 701761744,
 'itemDataDict': {},
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'slotWindow': <ui.SlotWindow object at 0x2E095C50>,
 'tooltipItem': None,
 'vid': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
