{'Children': [<ui.BoardWithTitleBar object at 0x2D1020D0>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x2D1020D0>,
                       'debug_text_circle_pos': <ui.TextLine object at 0x2D3ABDD0>,
                       'debug_text_fish_pos': <ui.TextLine object at 0x2D3ABE10>,
                       'debug_text_mouse_pos': <ui.TextLine object at 0x2D3ABE50>,
                       'fishing_background_water': <ui.ImageBox object at 0x2D3ABE70>,
                       'fishing_goal_circle': <ui.ImageBox object at 0x2D3ABD30>,
                       'fishing_goal_count': <ui.ExpandedImageBox object at 0x2D3ABC50>,
                       'fishing_goal_count_text': <ui.TextLine object at 0x2D3ABDF0>,
                       'fishing_timer_baseImg': <ui.ImageBox object at 0x2D3ABCF0>,
                       'fishing_timer_gauge': <ui.ExpandedImageBox object at 0x2D3ABE90>,
                       'fishing_water_navArea': <ui.Box object at 0x2D3AB190>},
 'FISHING_TIME_LIMIT': 15,
 'backGroundWater': <ui.ImageBox object at 0x2D3ABE70>,
 'board': <ui.BoardWithTitleBar object at 0x2D1020D0>,
 'debugText_fish_pos_Local': <ui.TextLine object at 0x2D3ABE10>,
 'debugText_goal_pos_Local': <ui.TextLine object at 0x2D3ABDD0>,
 'debugText_mouse_pos_Local': <ui.TextLine object at 0x2D3ABE50>,
 'fishImage': <ui.AniImageBox object at 0x2D3ABC10>,
 'goalCircle': <ui.ImageBox object at 0x2D3ABD30>,
 'hWnd': 745380648,
 'hitCount': <ui.ExpandedImageBox object at 0x2D3ABC50>,
 'hitCountText': <ui.TextLine object at 0x2D3ABDF0>,
 'hit_image_list': [],
 'miss_image_list': [],
 'navigationArea': <ui.Box object at 0x2D3AB190>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'timerGauge': <ui.ExpandedImageBox object at 0x2D3ABE90>,
 'timerGaugeVal': 15,
 'wave_image_list': [],
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
