{'Children': [<ui.BoardWithTitleBar object at 0x2E2B1D30>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x2E2B1D30>,
                       'debug_text_circle_pos': <ui.TextLine object at 0x2E2B1C70>,
                       'debug_text_fish_pos': <ui.TextLine object at 0x2E2B1FD0>,
                       'debug_text_mouse_pos': <ui.TextLine object at 0x2E2B1050>,
                       'fishing_background_water': <ui.ImageBox object at 0x2E2B1F50>,
                       'fishing_goal_circle': <ui.ImageBox object at 0x2E2B1CD0>,
                       'fishing_goal_count': <ui.ExpandedImageBox object at 0x2E2B1D90>,
                       'fishing_goal_count_text': <ui.TextLine object at 0x2E2B1E90>,
                       'fishing_timer_baseImg': <ui.ImageBox object at 0x2E2B1DF0>,
                       'fishing_timer_gauge': <ui.ExpandedImageBox object at 0x2E2B1BD0>,
                       'fishing_water_navArea': <ui.Box object at 0x2E2B1B30>},
 'FISHING_TIME_LIMIT': 15,
 'backGroundWater': <ui.ImageBox object at 0x2E2B1F50>,
 'board': <ui.BoardWithTitleBar object at 0x2E2B1D30>,
 'debugText_fish_pos_Local': <ui.TextLine object at 0x2E2B1FD0>,
 'debugText_goal_pos_Local': <ui.TextLine object at 0x2E2B1C70>,
 'debugText_mouse_pos_Local': <ui.TextLine object at 0x2E2B1050>,
 'fishImage': <ui.AniImageBox object at 0x1B342D10>,
 'goalCircle': <ui.ImageBox object at 0x2E2B1CD0>,
 'hWnd': 788264808,
 'hitCount': <ui.ExpandedImageBox object at 0x2E2B1D90>,
 'hitCountText': <ui.TextLine object at 0x2E2B1E90>,
 'hit_image_list': [],
 'miss_image_list': [],
 'navigationArea': <ui.Box object at 0x2E2B1B30>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'timerGauge': <ui.ExpandedImageBox object at 0x2E2B1BD0>,
 'timerGaugeVal': 15,
 'wave_image_list': [],
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
