{'Children': [<ui.BoardWithTitleBar object at 0x28FEEED0>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x28FEEED0>,
                       'debug_text_circle_pos': <ui.TextLine object at 0x28EE92D0>,
                       'debug_text_fish_pos': <ui.TextLine object at 0x28EE92B0>,
                       'debug_text_mouse_pos': <ui.TextLine object at 0x28EE92F0>,
                       'fishing_background_water': <ui.ImageBox object at 0x28EE9090>,
                       'fishing_goal_circle': <ui.ImageBox object at 0x28EE9230>,
                       'fishing_goal_count': <ui.ExpandedImageBox object at 0x28EE91D0>,
                       'fishing_goal_count_text': <ui.TextLine object at 0x28EE9290>,
                       'fishing_timer_baseImg': <ui.ImageBox object at 0x28EE9310>,
                       'fishing_timer_gauge': <ui.ExpandedImageBox object at 0x28EE9330>,
                       'fishing_water_navArea': <ui.Box object at 0x28EE90B0>},
 'FISHING_TIME_LIMIT': 15,
 'backGroundWater': <ui.ImageBox object at 0x28EE9090>,
 'board': <ui.BoardWithTitleBar object at 0x28FEEED0>,
 'debugText_fish_pos_Local': <ui.TextLine object at 0x28EE92B0>,
 'debugText_goal_pos_Local': <ui.TextLine object at 0x28EE92D0>,
 'debugText_mouse_pos_Local': <ui.TextLine object at 0x28EE92F0>,
 'fishImage': <ui.AniImageBox object at 0x28FEECB0>,
 'goalCircle': <ui.ImageBox object at 0x28EE9230>,
 'hWnd': 759764872,
 'hitCount': <ui.ExpandedImageBox object at 0x28EE91D0>,
 'hitCountText': <ui.TextLine object at 0x28EE9290>,
 'hit_image_list': [],
 'miss_image_list': [],
 'navigationArea': <ui.Box object at 0x28EE90B0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'timerGauge': <ui.ExpandedImageBox object at 0x28EE9330>,
 'timerGaugeVal': 15,
 'wave_image_list': [],
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
