{'Children': [<ui.BoardWithTitleBar object at 0x2E2A2C70>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2E2A2C90>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2E2A2F50>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2E2A2CF0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2E2A2E30>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2E2A2F90>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2E2A2CB0>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2E2A2FF0>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2E2A2F10>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2E2A2DB0>,
                       'board': <ui.BoardWithTitleBar object at 0x2E2A2C70>,
                       'down_arrow_image': <ui.ImageBox object at 0x2E299DB0>,
                       'list_bg_image_1': <ui.ImageBox object at 0x2E2997B0>,
                       'list_bg_image_2': <ui.ImageBox object at 0x2E299770>,
                       'list_bg_image_3': <ui.ImageBox object at 0x2E2991D0>,
                       'list_bg_image_4': <ui.ImageBox object at 0x2E152290>,
                       'list_bg_image_5': <ui.ImageBox object at 0x2E152A50>,
                       'main_exchange_button': <ui.Button object at 0x2E2A2D50>,
                       'main_shoot_count_bg': <ui.ImageBox object at 0x2E2A2C10>,
                       'main_shoot_count_text': <ui.TextLine object at 0x2E2A2E90>,
                       'main_window': <ui.ScriptWindow object at 0x2E2A2BF0>,
                       'shoot_count_text_1': <ui.TextLine object at 0x2E299710>,
                       'shoot_count_text_2': <ui.TextLine object at 0x2E299DF0>,
                       'shoot_count_text_3': <ui.TextLine object at 0x2E1525D0>,
                       'shoot_count_text_4': <ui.TextLine object at 0x2E152870>,
                       'shoot_count_text_5': <ui.TextLine object at 0x2E152FB0>,
                       'shoot_count_text_window_1': <ui.ScriptWindow object at 0x2E299DD0>,
                       'shoot_count_text_window_2': <ui.ScriptWindow object at 0x2E299210>,
                       'shoot_count_text_window_3': <ui.ScriptWindow object at 0x2E152E10>,
                       'shoot_count_text_window_4': <ui.ScriptWindow object at 0x2E152F50>,
                       'shoot_count_text_window_5': <ui.ScriptWindow object at 0x2E152F30>,
                       'shoot_list_exchange_button_1': <ui.Button object at 0x2E152AB0>,
                       'shoot_list_exchange_button_2': <ui.Button object at 0x2E152410>,
                       'shoot_list_exchange_button_3': <ui.Button object at 0x2E152DB0>,
                       'shoot_list_exchange_button_4': <ui.Button object at 0x2E152F10>,
                       'shoot_list_exchange_button_5': <ui.Button object at 0x2E152430>,
                       'shoot_name_text_1': <ui.TextLine object at 0x2E2997D0>,
                       'shoot_name_text_2': <ui.TextLine object at 0x2E299A90>,
                       'shoot_name_text_3': <ui.TextLine object at 0x2E1526B0>,
                       'shoot_name_text_4': <ui.TextLine object at 0x2E152750>,
                       'shoot_name_text_5': <ui.TextLine object at 0x2E152990>,
                       'shoot_name_text_window_1': <ui.ScriptWindow object at 0x2E299150>,
                       'shoot_name_text_window_2': <ui.ScriptWindow object at 0x2E299CB0>,
                       'shoot_name_text_window_3': <ui.ScriptWindow object at 0x2E047050>,
                       'shoot_name_text_window_4': <ui.ScriptWindow object at 0x2E152C70>,
                       'shoot_name_text_window_5': <ui.ScriptWindow object at 0x2E152BB0>,
                       'slot_image': <ui.ImageBox object at 0x2E2A2F30>},
 'exchange_button_list': [<ui.Button object at 0x2E2A2D50>, <ui.Button object at 0x2E152AB0>, <ui.Button object at 0x2E152410>, <ui.Button object at 0x2E152DB0>, <ui.Button object at 0x2E152F10>, <ui.Button object at 0x2E152430>],
 'hWnd': 758345592,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'prev_exchange_time': 0,
 'questionDialog': None,
 'shoot_count_text_list': [<ui.TextLine object at 0x2E2A2E90>, <ui.TextLine object at 0x2E299710>, <ui.TextLine object at 0x2E299DF0>, <ui.TextLine object at 0x2E1525D0>, <ui.TextLine object at 0x2E152870>, <ui.TextLine object at 0x2E152FB0>],
 'shoot_envelope_img': <ui.ImageBox object at 0x2E2A2F30>,
 'shoot_name_text_list': [<ui.TextLine object at 0x2E2997D0>, <ui.TextLine object at 0x2E299A90>, <ui.TextLine object at 0x2E1526B0>, <ui.TextLine object at 0x2E152750>, <ui.TextLine object at 0x2E152990>],
 'tool_tip': <uiToolTip.ToolTip object at 0x2E299C30>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
