{'Children': [<ui.BoardWithTitleBar object at 0x2B1CA810>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2B1CA350>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2B1CA370>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2B1CA2B0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2B1CA310>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2B1CA270>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2B1CA330>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2B1CA290>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2B1CA2F0>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2B1CA2D0>,
                       'board': <ui.BoardWithTitleBar object at 0x2B1CA810>,
                       'down_arrow_image': <ui.ImageBox object at 0x2B1CA430>,
                       'list_bg_image_1': <ui.ImageBox object at 0x2B1CA450>,
                       'list_bg_image_2': <ui.ImageBox object at 0x2B1CA4F0>,
                       'list_bg_image_3': <ui.ImageBox object at 0x2B1CA590>,
                       'list_bg_image_4': <ui.ImageBox object at 0x2B1CA630>,
                       'list_bg_image_5': <ui.ImageBox object at 0x2B1CA6D0>,
                       'main_exchange_button': <ui.Button object at 0x2B1CA3F0>,
                       'main_shoot_count_bg': <ui.ImageBox object at 0x2B1CA3B0>,
                       'main_shoot_count_text': <ui.TextLine object at 0x2B1CA3D0>,
                       'main_window': <ui.ScriptWindow object at 0x2B1CA250>,
                       'shoot_count_text_1': <ui.TextLine object at 0x2B1CA4D0>,
                       'shoot_count_text_2': <ui.TextLine object at 0x2B1CA570>,
                       'shoot_count_text_3': <ui.TextLine object at 0x2B1CA610>,
                       'shoot_count_text_4': <ui.TextLine object at 0x2B1CA6B0>,
                       'shoot_count_text_5': <ui.TextLine object at 0x2B1CA750>,
                       'shoot_count_text_window_1': <ui.ScriptWindow object at 0x2B1CA4B0>,
                       'shoot_count_text_window_2': <ui.ScriptWindow object at 0x2B1CA550>,
                       'shoot_count_text_window_3': <ui.ScriptWindow object at 0x2B1CA5F0>,
                       'shoot_count_text_window_4': <ui.ScriptWindow object at 0x2B1CA690>,
                       'shoot_count_text_window_5': <ui.ScriptWindow object at 0x2B1CA730>,
                       'shoot_list_exchange_button_1': <ui.Button object at 0x2B1CA770>,
                       'shoot_list_exchange_button_2': <ui.Button object at 0x2B1CA7B0>,
                       'shoot_list_exchange_button_3': <ui.Button object at 0x2B1CA7F0>,
                       'shoot_list_exchange_button_4': <ui.Button object at 0x2B1CA850>,
                       'shoot_list_exchange_button_5': <ui.Button object at 0x2B1CA890>,
                       'shoot_name_text_1': <ui.TextLine object at 0x2B1CA490>,
                       'shoot_name_text_2': <ui.TextLine object at 0x2B1CA530>,
                       'shoot_name_text_3': <ui.TextLine object at 0x2B1CA5D0>,
                       'shoot_name_text_4': <ui.TextLine object at 0x2B1CA670>,
                       'shoot_name_text_5': <ui.TextLine object at 0x2B1CA710>,
                       'shoot_name_text_window_1': <ui.ScriptWindow object at 0x2B1CA470>,
                       'shoot_name_text_window_2': <ui.ScriptWindow object at 0x2B1CA510>,
                       'shoot_name_text_window_3': <ui.ScriptWindow object at 0x2B1CA5B0>,
                       'shoot_name_text_window_4': <ui.ScriptWindow object at 0x2B1CA650>,
                       'shoot_name_text_window_5': <ui.ScriptWindow object at 0x2B1CA6F0>,
                       'slot_image': <ui.ImageBox object at 0x2B1CA390>},
 'exchange_button_list': [<ui.Button object at 0x2B1CA3F0>, <ui.Button object at 0x2B1CA770>, <ui.Button object at 0x2B1CA7B0>, <ui.Button object at 0x2B1CA7F0>, <ui.Button object at 0x2B1CA850>, <ui.Button object at 0x2B1CA890>],
 'hWnd': 821390672,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'prev_exchange_time': 0,
 'questionDialog': None,
 'shoot_count_text_list': [<ui.TextLine object at 0x2B1CA3D0>, <ui.TextLine object at 0x2B1CA4D0>, <ui.TextLine object at 0x2B1CA570>, <ui.TextLine object at 0x2B1CA610>, <ui.TextLine object at 0x2B1CA6B0>, <ui.TextLine object at 0x2B1CA750>],
 'shoot_envelope_img': <ui.ImageBox object at 0x2B1CA390>,
 'shoot_name_text_list': [<ui.TextLine object at 0x2B1CA490>, <ui.TextLine object at 0x2B1CA530>, <ui.TextLine object at 0x2B1CA5D0>, <ui.TextLine object at 0x2B1CA670>, <ui.TextLine object at 0x2B1CA710>],
 'tool_tip': <uiToolTip.ToolTip object at 0x2B25BF70>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
