{'Children': [<ui.BoardWithTitleBar object at 0x2D6A25F0>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2D6A2A70>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2D4D6AB0>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2D6A22B0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2D6A22D0>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2D6A2FF0>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2D6A2770>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2D6A2610>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2D6A25D0>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2D6A2970>,
                       'board': <ui.BoardWithTitleBar object at 0x2D6A25F0>,
                       'down_arrow_image': <ui.ImageBox object at 0x2D4D61F0>,
                       'list_bg_image_1': <ui.ImageBox object at 0x2D4D6210>,
                       'list_bg_image_2': <ui.ImageBox object at 0x2D4D62B0>,
                       'list_bg_image_3': <ui.ImageBox object at 0x2D4D6350>,
                       'list_bg_image_4': <ui.ImageBox object at 0x2D4D6430>,
                       'list_bg_image_5': <ui.ImageBox object at 0x2D4D64D0>,
                       'main_exchange_button': <ui.Button object at 0x2D4D61B0>,
                       'main_shoot_count_bg': <ui.ImageBox object at 0x2D4D6130>,
                       'main_shoot_count_text': <ui.TextLine object at 0x2D4D6150>,
                       'main_window': <ui.ScriptWindow object at 0x2D6A2C30>,
                       'shoot_count_text_1': <ui.TextLine object at 0x2D4D6290>,
                       'shoot_count_text_2': <ui.TextLine object at 0x2D4D6330>,
                       'shoot_count_text_3': <ui.TextLine object at 0x2D4D6410>,
                       'shoot_count_text_4': <ui.TextLine object at 0x2D4D64B0>,
                       'shoot_count_text_5': <ui.TextLine object at 0x2D4D6570>,
                       'shoot_count_text_window_1': <ui.ScriptWindow object at 0x2D4D6270>,
                       'shoot_count_text_window_2': <ui.ScriptWindow object at 0x2D4D6310>,
                       'shoot_count_text_window_3': <ui.ScriptWindow object at 0x2D4D63F0>,
                       'shoot_count_text_window_4': <ui.ScriptWindow object at 0x2D4D6490>,
                       'shoot_count_text_window_5': <ui.ScriptWindow object at 0x2D4D6550>,
                       'shoot_list_exchange_button_1': <ui.Button object at 0x2D4D6590>,
                       'shoot_list_exchange_button_2': <ui.Button object at 0x2D4D65D0>,
                       'shoot_list_exchange_button_3': <ui.Button object at 0x2D4D6610>,
                       'shoot_list_exchange_button_4': <ui.Button object at 0x2D4D6650>,
                       'shoot_list_exchange_button_5': <ui.Button object at 0x2D4D6690>,
                       'shoot_name_text_1': <ui.TextLine object at 0x2D4D6250>,
                       'shoot_name_text_2': <ui.TextLine object at 0x2D4D62F0>,
                       'shoot_name_text_3': <ui.TextLine object at 0x2D4D63B0>,
                       'shoot_name_text_4': <ui.TextLine object at 0x2D4D6470>,
                       'shoot_name_text_5': <ui.TextLine object at 0x2D4D6510>,
                       'shoot_name_text_window_1': <ui.ScriptWindow object at 0x2D4D6230>,
                       'shoot_name_text_window_2': <ui.ScriptWindow object at 0x2D4D62D0>,
                       'shoot_name_text_window_3': <ui.ScriptWindow object at 0x2D4D6370>,
                       'shoot_name_text_window_4': <ui.ScriptWindow object at 0x2D4D6450>,
                       'shoot_name_text_window_5': <ui.ScriptWindow object at 0x2D4D64F0>,
                       'slot_image': <ui.ImageBox object at 0x2D4D6E50>},
 'exchange_button_list': [<ui.Button object at 0x2D4D61B0>, <ui.Button object at 0x2D4D6590>, <ui.Button object at 0x2D4D65D0>, <ui.Button object at 0x2D4D6610>, <ui.Button object at 0x2D4D6650>, <ui.Button object at 0x2D4D6690>],
 'hWnd': 841395456,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'prev_exchange_time': 0,
 'questionDialog': None,
 'shoot_count_text_list': [<ui.TextLine object at 0x2D4D6150>, <ui.TextLine object at 0x2D4D6290>, <ui.TextLine object at 0x2D4D6330>, <ui.TextLine object at 0x2D4D6410>, <ui.TextLine object at 0x2D4D64B0>, <ui.TextLine object at 0x2D4D6570>],
 'shoot_envelope_img': <ui.ImageBox object at 0x2D4D6E50>,
 'shoot_name_text_list': [<ui.TextLine object at 0x2D4D6250>, <ui.TextLine object at 0x2D4D62F0>, <ui.TextLine object at 0x2D4D63B0>, <ui.TextLine object at 0x2D4D6470>, <ui.TextLine object at 0x2D4D6510>],
 'tool_tip': <uiToolTip.ToolTip object at 0x2D6B5ED0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
