{'Children': [<ui.Button object at 0x2E299130>,
              <ui.Button object at 0x2E299710>,
              <ui.Button object at 0x2E299DB0>,
              <ui.Button object at 0x2E299150>,
              <ui.Button object at 0x2E299DD0>,
              <ui.Button object at 0x2E299A90>,
              <ui.Button object at 0x2E2991D0>,
              <ui.Button object at 0x2E299E10>,
              <ui.Button object at 0x2E299790>,
              <ui.AniImageBox object at 0x2E299CD0>],
 'ElementDictionary': {'BuildGuildBuilding': <ui.Button object at 0x2E299A90>,
                       'BuildGuildBuildingButtonName': <ui.TextLine object at 0x2E299210>,
                       'ExitObserver': <ui.Button object at 0x2E299DD0>,
                       'ExitObserverButtonName': <ui.TextLine object at 0x2E299CB0>,
                       'GuildWarButton': <ui.Button object at 0x2E2991D0>,
                       'GuildWarButtonName': <ui.TextLine object at 0x2E299C30>,
                       'HelpButton': <ui.Button object at 0x2E299130>,
                       'HelpButtonLabel': <ui.TextLine object at 0x2E299770>,
                       'MistIslandWarpLabel': <ui.TextLine object at 0x2E299C50>,
                       'MistsIslandWarpButton': <ui.Button object at 0x2E299E10>,
                       'PopupNoticeAnimImage': <ui.AniImageBox object at 0x2E299CD0>,
                       'PopupNoticeButton': <ui.Button object at 0x2E299790>,
                       'QuestButton': <ui.Button object at 0x2E299710>,
                       'QuestButtonLabel': <ui.TextLine object at 0x2E299DF0>,
                       'SkillPlusButton': <ui.Button object at 0x2E299150>,
                       'SkillPlusLabel': <ui.TextLine object at 0x2E2997D0>,
                       'StatusPlusButton': <ui.Button object at 0x2E299DB0>,
                       'StatusPlusLabel': <ui.TextLine object at 0x2E2997B0>},
 'gameButtonDict': {'BUILD': <ui.Button object at 0x2E299A90>,
                    'EXIT_OBSERVER': <ui.Button object at 0x2E299DD0>,
                    'GUILDWAR': <ui.Button object at 0x2E2991D0>,
                    'HELP': <ui.Button object at 0x2E299130>,
                    'POPUP_NOTICE': <ui.Button object at 0x2E299790>,
                    'QUEST': <ui.Button object at 0x2E299710>,
                    'SKILL': <ui.Button object at 0x2E299150>,
                    'STATUS': <ui.Button object at 0x2E299DB0>,
                    'WARP_MI': <ui.Button object at 0x2E299E10>},
 'hWnd': 758346632,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'popup': None,
 'timer': {},
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
