{'Children': [<ui.Board object at 0x2E32A030>],
 'ElementDictionary': {'always_show_name': <ui.TextLine object at 0x2E32A7B0>,
                       'always_show_name_off_button': <ui.RadioButton object at 0x2E32A810>,
                       'always_show_name_on_button': <ui.RadioButton object at 0x2E32A7D0>,
                       'block': <ui.TextLine object at 0x2E32A570>,
                       'block_exchange_button': <ui.ToggleButton object at 0x2E32A590>,
                       'block_friend_button': <ui.ToggleButton object at 0x2E32A690>,
                       'block_guild_button': <ui.ToggleButton object at 0x2E32A610>,
                       'block_party_button': <ui.ToggleButton object at 0x2E32A5D0>,
                       'block_party_request_button': <ui.ToggleButton object at 0x2E32A6D0>,
                       'block_whisper_button': <ui.ToggleButton object at 0x2E32A650>,
                       'board': <ui.Board object at 0x2E32A030>,
                       'chat': <ui.TextLine object at 0x2E32A710>,
                       'effect_on_off': <ui.TextLine object at 0x2E32A850>,
                       'key_setting_show': <ui.TextLine object at 0x2E32AA30>,
                       'key_setting_show_button': <ui.Button object at 0x2E32AA50>,
                       'looting_system_button': <ui.Button object at 0x2E32AAB0>,
                       'looting_system_text': <ui.TextLine object at 0x2E32AA90>,
                       'name_color': <ui.TextLine object at 0x2E32A270>,
                       'name_color_empire': <ui.RadioButton object at 0x2E32A2D0>,
                       'name_color_normal': <ui.RadioButton object at 0x2E32A290>,
                       'pvp_free': <ui.RadioButton object at 0x2E32A510>,
                       'pvp_guild': <ui.RadioButton object at 0x2E32A4B0>,
                       'pvp_mode': <ui.TextLine object at 0x2E32A3B0>,
                       'pvp_peace': <ui.RadioButton object at 0x2E32A3D0>,
                       'pvp_revenge': <ui.RadioButton object at 0x2E32A430>,
                       'salestext_off_button': <ui.RadioButton object at 0x2E32A950>,
                       'salestext_on_button': <ui.RadioButton object at 0x2E32A910>,
                       'salestext_on_off': <ui.TextLine object at 0x2E32A8F0>,
                       'show_damage_off_button': <ui.RadioButton object at 0x2E32A8B0>,
                       'show_damage_on_button': <ui.RadioButton object at 0x2E32A870>,
                       'show_mob_AI_flag_button': <ui.ToggleButton object at 0x2E32A9F0>,
                       'show_mob_info': <ui.TextLine object at 0x2E32A990>,
                       'show_mob_level_button': <ui.ToggleButton object at 0x2E32A9B0>,
                       'structure_view_mode': <ui.TextLine object at 0x2E32AAF0>,
                       'structure_view_mode_button': <ui.ToggleButton object at 0x2E32AB10>,
                       'target_board': <ui.TextLine object at 0x2E32A310>,
                       'target_board_no_view': <ui.RadioButton object at 0x2E32A330>,
                       'target_board_view': <ui.RadioButton object at 0x2E32A370>,
                       'titlebar': <ui.TitleBar object at 0x2E32A190>,
                       'titlename': <ui.TextLine object at 0x2E32A250>,
                       'view_chat_off_button': <ui.RadioButton object at 0x2E32A770>,
                       'view_chat_on_button': <ui.RadioButton object at 0x2E32A730>},
 'IsShow': False,
 'StructureViewButtonList': [<ui.ToggleButton object at 0x2E32AB10>],
 'alwaysShowNameButtonList': [<ui.RadioButton object at 0x2E32A7D0>, <ui.RadioButton object at 0x2E32A810>],
 'blockButtonList': [<ui.ToggleButton object at 0x2E32A590>, <ui.ToggleButton object at 0x2E32A5D0>, <ui.ToggleButton object at 0x2E32A610>, <ui.ToggleButton object at 0x2E32A650>, <ui.ToggleButton object at 0x2E32A690>, <ui.ToggleButton object at 0x2E32A6D0>],
 'hWnd': 758352664,
 'interface': None,
 'nameColorModeButtonList': [<ui.RadioButton object at 0x2E32A290>, <ui.RadioButton object at 0x2E32A2D0>],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pvpModeButtonDict': {0: <ui.RadioButton object at 0x2E32A3D0>, 1: <ui.RadioButton object at 0x2E32A430>, 2: <ui.RadioButton object at 0x2E32A510>, 4: <ui.RadioButton object at 0x2E32A4B0>},
 'showDamageButtonList': [<ui.RadioButton object at 0x2E32A870>, <ui.RadioButton object at 0x2E32A8B0>],
 'showMobInfoButtonList': [<ui.ToggleButton object at 0x2E32A9B0>, <ui.ToggleButton object at 0x2E32A9F0>],
 'showsalesTextButtonList': [<ui.RadioButton object at 0x2E32A910>, <ui.RadioButton object at 0x2E32A950>],
 'titleBar': <ui.TitleBar object at 0x2E32A190>,
 'viewChatButtonList': [<ui.RadioButton object at 0x2E32A730>, <ui.RadioButton object at 0x2E32A770>],
 'viewTargetBoardButtonList': [<ui.RadioButton object at 0x2E32A330>, <ui.RadioButton object at 0x2E32A370>],
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
