{'Children': [<ui.Button object at 0x2E9B1FF0>, <ui.Button object at 0x2E9B13D0>, <ui.Button object at 0x2E9B19F0>, <ui.Button object at 0x2E9B18D0>, <ui.Button object at 0x2E9B1ED0>, <ui.Button object at 0x23EA0D30>, <ui.Button object at 0x23EA09D0>, <ui.Button object at 0x2E99D0B0>],
 'ElementDictionary': {'BuildGuildBuilding': <ui.Button object at 0x23EA0D30>,
                       'BuildGuildBuildingButtonName': <ui.TextLine object at 0x23EA08B0>,
                       'ExitObserver': <ui.Button object at 0x2E9B1ED0>,
                       'ExitObserverButtonName': <ui.TextLine object at 0x23EA0BF0>,
                       'GuildWarButton': <ui.Button object at 0x23EA09D0>,
                       'GuildWarButtonName': <ui.TextLine object at 0x2E99D790>,
                       'HelpButton': <ui.Button object at 0x2E9B1FF0>,
                       'HelpButtonLabel': <ui.TextLine object at 0x2E9B1770>,
                       'MistIslandWarpLabel': <ui.TextLine object at 0x2E99D890>,
                       'MistsIslandWarpButton': <ui.Button object at 0x2E99D0B0>,
                       'QuestButton': <ui.Button object at 0x2E9B13D0>,
                       'QuestButtonLabel': <ui.TextLine object at 0x2E9B1AF0>,
                       'SkillPlusButton': <ui.Button object at 0x2E9B18D0>,
                       'SkillPlusLabel': <ui.TextLine object at 0x2E9B11D0>,
                       'StatusPlusButton': <ui.Button object at 0x2E9B19F0>,
                       'StatusPlusLabel': <ui.TextLine object at 0x2E9B1970>},
 'gameButtonDict': {'BUILD': <ui.Button object at 0x23EA0D30>,
                    'EXIT_OBSERVER': <ui.Button object at 0x2E9B1ED0>,
                    'GUILDWAR': <ui.Button object at 0x23EA09D0>,
                    'HELP': <ui.Button object at 0x2E9B1FF0>,
                    'QUEST': <ui.Button object at 0x2E9B13D0>,
                    'SKILL': <ui.Button object at 0x2E9B18D0>,
                    'STATUS': <ui.Button object at 0x2E9B19F0>,
                    'WARP_MI': <ui.Button object at 0x2E99D0B0>},
 'hWnd': 708269872,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'popup': None,
 'timer': {},
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
