{'Children': [<ui.Board object at 0x2DBFB2F0>],
 'ElementDictionary': {'always_show_name': <ui.TextLine object at 0x2DD38770>,
                       'always_show_name_off_button': <ui.RadioButton object at 0x2DD387D0>,
                       'always_show_name_on_button': <ui.RadioButton object at 0x2DD38790>,
                       'block': <ui.TextLine object at 0x2DD38530>,
                       'block_exchange_button': <ui.ToggleButton object at 0x2DD38550>,
                       'block_friend_button': <ui.ToggleButton object at 0x2DD38650>,
                       'block_guild_button': <ui.ToggleButton object at 0x2DD385D0>,
                       'block_party_button': <ui.ToggleButton object at 0x2DD38590>,
                       'block_party_request_button': <ui.ToggleButton object at 0x2DD38690>,
                       'block_whisper_button': <ui.ToggleButton object at 0x2DD38610>,
                       'board': <ui.Board object at 0x2DBFB2F0>,
                       'chat': <ui.TextLine object at 0x2DD386D0>,
                       'effect_on_off': <ui.TextLine object at 0x2DD38810>,
                       'key_setting_show': <ui.TextLine object at 0x2DD38A10>,
                       'key_setting_show_button': <ui.Button object at 0x2DD38A30>,
                       'name_color': <ui.TextLine object at 0x2DD38250>,
                       'name_color_empire': <ui.RadioButton object at 0x2DD382B0>,
                       'name_color_normal': <ui.RadioButton object at 0x2DD38270>,
                       'pvp_free': <ui.RadioButton object at 0x2DD384D0>,
                       'pvp_guild': <ui.RadioButton object at 0x2DD38470>,
                       'pvp_mode': <ui.TextLine object at 0x2DD38390>,
                       'pvp_peace': <ui.RadioButton object at 0x2DD383B0>,
                       'pvp_revenge': <ui.RadioButton object at 0x2DD38410>,
                       'salestext_off_button': <ui.RadioButton object at 0x2DD38930>,
                       'salestext_on_button': <ui.RadioButton object at 0x2DD388F0>,
                       'salestext_on_off': <ui.TextLine object at 0x2DD388D0>,
                       'show_damage_off_button': <ui.RadioButton object at 0x2DD38890>,
                       'show_damage_on_button': <ui.RadioButton object at 0x2DD38830>,
                       'show_mob_AI_flag_button': <ui.ToggleButton object at 0x2DD389D0>,
                       'show_mob_info': <ui.TextLine object at 0x2DD38970>,
                       'show_mob_level_button': <ui.ToggleButton object at 0x2DD38990>,
                       'structure_view_mode': <ui.TextLine object at 0x2DD38A70>,
                       'structure_view_mode_button': <ui.ToggleButton object at 0x2DD38A90>,
                       'target_board': <ui.TextLine object at 0x2DD382F0>,
                       'target_board_no_view': <ui.RadioButton object at 0x2DD38310>,
                       'target_board_view': <ui.RadioButton object at 0x2DD38350>,
                       'titlebar': <ui.TitleBar object at 0x2DD38170>,
                       'titlename': <ui.TextLine object at 0x2DD38230>,
                       'view_chat_off_button': <ui.RadioButton object at 0x2DD38730>,
                       'view_chat_on_button': <ui.RadioButton object at 0x2DD386F0>},
 'IsShow': False,
 'StructureViewButtonList': [<ui.ToggleButton object at 0x2DD38A90>],
 'alwaysShowNameButtonList': [<ui.RadioButton object at 0x2DD38790>, <ui.RadioButton object at 0x2DD387D0>],
 'blockButtonList': [<ui.ToggleButton object at 0x2DD38550>, <ui.ToggleButton object at 0x2DD38590>, <ui.ToggleButton object at 0x2DD385D0>, <ui.ToggleButton object at 0x2DD38610>, <ui.ToggleButton object at 0x2DD38650>, <ui.ToggleButton object at 0x2DD38690>],
 'hWnd': 717751208,
 'nameColorModeButtonList': [<ui.RadioButton object at 0x2DD38270>, <ui.RadioButton object at 0x2DD382B0>],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pvpModeButtonDict': {0: <ui.RadioButton object at 0x2DD383B0>, 1: <ui.RadioButton object at 0x2DD38410>, 2: <ui.RadioButton object at 0x2DD384D0>, 4: <ui.RadioButton object at 0x2DD38470>},
 'showDamageButtonList': [<ui.RadioButton object at 0x2DD38830>, <ui.RadioButton object at 0x2DD38890>],
 'showMobInfoButtonList': [<ui.ToggleButton object at 0x2DD38990>, <ui.ToggleButton object at 0x2DD389D0>],
 'showsalesTextButtonList': [<ui.RadioButton object at 0x2DD388F0>, <ui.RadioButton object at 0x2DD38930>],
 'titleBar': <ui.TitleBar object at 0x2DD38170>,
 'viewChatButtonList': [<ui.RadioButton object at 0x2DD386F0>, <ui.RadioButton object at 0x2DD38730>],
 'viewTargetBoardButtonList': [<ui.RadioButton object at 0x2DD38310>, <ui.RadioButton object at 0x2DD38350>],
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
