{'Children': [<ui.Board object at 0x2E32ADF0>],
 'ElementDictionary': {'BuyRefreshTime': <ui.TextLine object at 0x2E32AD50>,
                       'BuyRefreshTimeName': <ui.TextLine object at 0x2E32ADD0>,
                       'RefreshButton': <ui.Button object at 0x2E1525D0>,
                       'SellItemSlot': <ui.SlotWindow object at 0x2E32AD30>,
                       'TitleBar': <ui.TitleBar object at 0x2E32AE10>,
                       'TitleName': <ui.TextLine object at 0x2E32ABB0>,
                       'board': <ui.Board object at 0x2E32ADF0>,
                       'gemshopbackimg': <ui.ImageBox object at 0x2E32ACF0>,
                       'slot_1_Icon': <ui.ImageBox object at 0x2E32AEF0>,
                       'slot_1_price': <ui.TextLine object at 0x2E32AE30>,
                       'slot_2_Icon': <ui.ImageBox object at 0x2E32ACD0>,
                       'slot_2_price': <ui.TextLine object at 0x2E32AF30>,
                       'slot_3_Icon': <ui.ImageBox object at 0x2E32AB70>,
                       'slot_3_price': <ui.TextLine object at 0x2E32AED0>,
                       'slot_4_Icon': <ui.ImageBox object at 0x2E32AFD0>,
                       'slot_4_price': <ui.TextLine object at 0x2E32AE50>,
                       'slot_5_Icon': <ui.ImageBox object at 0x2E32AC10>,
                       'slot_5_price': <ui.TextLine object at 0x2E32AC50>,
                       'slot_6_Icon': <ui.ImageBox object at 0x2E32AFB0>,
                       'slot_6_price': <ui.TextLine object at 0x2E32AF70>,
                       'slot_7_Icon': <ui.ImageBox object at 0x2E152BB0>,
                       'slot_7_price': <ui.TextLine object at 0x2E32AEB0>,
                       'slot_8_Icon': <ui.ImageBox object at 0x2E152410>,
                       'slot_8_price': <ui.TextLine object at 0x2E152C70>,
                       'slot_9_Icon': <ui.ImageBox object at 0x2E1526B0>,
                       'slot_9_price': <ui.TextLine object at 0x2E152E10>},
 'IsOpen': False,
 'RefreshTimeValue': <ui.TextLine object at 0x2E32AD50>,
 'gemshoprefreshtime': 0,
 'hWnd': 758354952,
 'itempricelist': [<ui.TextLine object at 0x2E32AE30>,
                   <ui.TextLine object at 0x2E32AF30>,
                   <ui.TextLine object at 0x2E32AED0>,
                   <ui.TextLine object at 0x2E32AE50>,
                   <ui.TextLine object at 0x2E32AC50>,
                   <ui.TextLine object at 0x2E32AF70>,
                   <ui.TextLine object at 0x2E32AEB0>,
                   <ui.TextLine object at 0x2E152C70>,
                   <ui.TextLine object at 0x2E152E10>],
 'itemslottoprice': [],
 'itemslottovnum': [],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pop': None,
 'tooltipitem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndSellItemSlot': <ui.SlotWindow object at 0x2E32AD30>,
 'xGemWindowStart': 0,
 'yGemWindowStart': 0}
