{'Children': [<ui.Board object at 0x2DF7FB30>],
 'ElementDictionary': {'BuyRefreshTime': <ui.TextLine object at 0x2DF7FA30>,
                       'BuyRefreshTimeName': <ui.TextLine object at 0x2DF7F9D0>,
                       'RefreshButton': <ui.Button object at 0x2DF7FDB0>,
                       'SellItemSlot': <ui.SlotWindow object at 0x2DF7F6F0>,
                       'TitleBar': <ui.TitleBar object at 0x2DF7FA70>,
                       'TitleName': <ui.TextLine object at 0x2DF7FC90>,
                       'board': <ui.Board object at 0x2DF7FB30>,
                       'gemshopbackimg': <ui.ImageBox object at 0x2DF7FBB0>,
                       'slot_1_Icon': <ui.ImageBox object at 0x2DF7F7D0>,
                       'slot_1_price': <ui.TextLine object at 0x2DF7F890>,
                       'slot_2_Icon': <ui.ImageBox object at 0x2DF7F4B0>,
                       'slot_2_price': <ui.TextLine object at 0x2DF7FE30>,
                       'slot_3_Icon': <ui.ImageBox object at 0x2DF7F5B0>,
                       'slot_3_price': <ui.TextLine object at 0x2DF7F7F0>,
                       'slot_4_Icon': <ui.ImageBox object at 0x2DF7F710>,
                       'slot_4_price': <ui.TextLine object at 0x2DF7FCD0>,
                       'slot_5_Icon': <ui.ImageBox object at 0x2DF7F830>,
                       'slot_5_price': <ui.TextLine object at 0x2DF7FD50>,
                       'slot_6_Icon': <ui.ImageBox object at 0x2DF7FD90>,
                       'slot_6_price': <ui.TextLine object at 0x2DF7FCB0>,
                       'slot_7_Icon': <ui.ImageBox object at 0x2DF7FD70>,
                       'slot_7_price': <ui.TextLine object at 0x2DF7F7B0>,
                       'slot_8_Icon': <ui.ImageBox object at 0x2DF7FF50>,
                       'slot_8_price': <ui.TextLine object at 0x2DF7FB70>,
                       'slot_9_Icon': <ui.ImageBox object at 0x2DF7FDF0>,
                       'slot_9_price': <ui.TextLine object at 0x2DF7FC10>},
 'IsOpen': False,
 'RefreshTimeValue': <ui.TextLine object at 0x2DF7FA30>,
 'gemshoprefreshtime': 0,
 'hWnd': 701767552,
 'itempricelist': [<ui.TextLine object at 0x2DF7F890>,
                   <ui.TextLine object at 0x2DF7FE30>,
                   <ui.TextLine object at 0x2DF7F7F0>,
                   <ui.TextLine object at 0x2DF7FCD0>,
                   <ui.TextLine object at 0x2DF7FD50>,
                   <ui.TextLine object at 0x2DF7FCB0>,
                   <ui.TextLine object at 0x2DF7F7B0>,
                   <ui.TextLine object at 0x2DF7FB70>,
                   <ui.TextLine object at 0x2DF7FC10>],
 'itemslottoprice': [],
 'itemslottovnum': [],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pop': None,
 'tooltipitem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndSellItemSlot': <ui.SlotWindow object at 0x2DF7F6F0>,
 'xGemWindowStart': 0,
 'yGemWindowStart': 0}
