{'Children': [<ui.Board object at 0x2E95AD70>],
 'ElementDictionary': {'BuyRefreshTime': <ui.TextLine object at 0x2E95AD50>,
                       'BuyRefreshTimeName': <ui.TextLine object at 0x2E95AE30>,
                       'RefreshButton': <ui.Button object at 0x2E99D430>,
                       'SellItemSlot': <ui.SlotWindow object at 0x2E95ACD0>,
                       'TitleBar': <ui.TitleBar object at 0x2E95ABF0>,
                       'TitleName': <ui.TextLine object at 0x2E95AF90>,
                       'board': <ui.Board object at 0x2E95AD70>,
                       'gemshopbackimg': <ui.ImageBox object at 0x2E95AB50>,
                       'slot_1_Icon': <ui.ImageBox object at 0x2E95ADD0>,
                       'slot_1_price': <ui.TextLine object at 0x2E95ACB0>,
                       'slot_2_Icon': <ui.ImageBox object at 0x2E95AC70>,
                       'slot_2_price': <ui.TextLine object at 0x2E95AE70>,
                       'slot_3_Icon': <ui.ImageBox object at 0x2E95ADB0>,
                       'slot_3_price': <ui.TextLine object at 0x2E95ABD0>,
                       'slot_4_Icon': <ui.ImageBox object at 0x2E95AC50>,
                       'slot_4_price': <ui.TextLine object at 0x2E95AEB0>,
                       'slot_5_Icon': <ui.ImageBox object at 0x2E95AE50>,
                       'slot_5_price': <ui.TextLine object at 0x2E95AFD0>,
                       'slot_6_Icon': <ui.ImageBox object at 0x2E95AF50>,
                       'slot_6_price': <ui.TextLine object at 0x2E95ADF0>,
                       'slot_7_Icon': <ui.ImageBox object at 0x2E95AB70>,
                       'slot_7_price': <ui.TextLine object at 0x2E95ABB0>,
                       'slot_8_Icon': <ui.ImageBox object at 0x2E95AFF0>,
                       'slot_8_price': <ui.TextLine object at 0x2E95AEF0>,
                       'slot_9_Icon': <ui.ImageBox object at 0x2E99DB50>,
                       'slot_9_price': <ui.TextLine object at 0x2E95AF30>},
 'IsOpen': False,
 'RefreshTimeValue': <ui.TextLine object at 0x2E95AD50>,
 'gemshoprefreshtime': 0,
 'hWnd': 708278848,
 'itempricelist': [<ui.TextLine object at 0x2E95ACB0>,
                   <ui.TextLine object at 0x2E95AE70>,
                   <ui.TextLine object at 0x2E95ABD0>,
                   <ui.TextLine object at 0x2E95AEB0>,
                   <ui.TextLine object at 0x2E95AFD0>,
                   <ui.TextLine object at 0x2E95ADF0>,
                   <ui.TextLine object at 0x2E95ABB0>,
                   <ui.TextLine object at 0x2E95AEF0>,
                   <ui.TextLine object at 0x2E95AF30>],
 'itemslottoprice': [],
 'itemslottovnum': [],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pop': None,
 'tooltipitem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndSellItemSlot': <ui.SlotWindow object at 0x2E95ACD0>,
 'xGemWindowStart': 0,
 'yGemWindowStart': 0}
