{'Children': [<ui.Board object at 0x26C83A90>],
 'ElementDictionary': {'DealGuildName': <ui.TextLine object at 0x3EE85630>,
                       'Lbutton': <ui.Button object at 0x3EE85910>,
                       'Rbutton': <ui.Button object at 0x3EE855B0>,
                       'board': <ui.Board object at 0x26C83A90>,
                       'dealguildname_slot': <ui.EditLine object at 0x3EE85390>,
                       'message1': <ui.TextLine object at 0x3EE85570>,
                       'message2': <ui.TextLine object at 0x3EE85A90>,
                       'titlebar': <ui.TitleBar object at 0x3EE85650>,
                       'titlename': <ui.TextLine object at 0x3EE858F0>},
 'LeftButton': <ui.Button object at 0x3EE85910>,
 'acceptEvent': <cyfunction GuildLandDealVoteDialog.__init__.<locals>.<lambda> at 0x26C95A28>,
 'dealguildname': <ui.EditLine object at 0x3EE85390>,
 'hWnd': 763565304,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'text1': <ui.TextLine object at 0x3EE85570>,
 'text2': <ui.TextLine object at 0x3EE85A90>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
