{'AcceptButton': <ui.Button object at 0x378017D0>,
 'BuildGuildBuildingWindow': None,
 'CancelButton': <ui.Button object at 0x37801810>,
 'ChangeBuildingList': <ui.ListBox object at 0x377F56F0>,
 'ChangePositionBaseX': 0,
 'ChangePositionBaseY': 0,
 'Children': [<ui.BoardWithTitleBar object at 0x377F55F0>],
 'DeleteButton': <ui.Button object at 0x378016D0>,
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x378017D0>,
                       'Board': <ui.BoardWithTitleBar object at 0x377F55F0>,
                       'BuildingListBar': <ui.SlotBar object at 0x377F56D0>,
                       'BuildingRotationZ': <ui.SliderBar object at 0x37801750>,
                       'BuildingRotationZTitle': <ui.TextLine object at 0x37801730>,
                       'CancelButton': <ui.Button object at 0x37801810>,
                       'ChangeBuildingList': <ui.ListBox object at 0x377F56F0>,
                       'ChangeListScrollBar': <ui.ScrollBar object at 0x37801C10>,
                       'DeleteButton': <ui.Button object at 0x378016D0>,
                       'InBuildingListTitle': <ui.TextLine object at 0x377F5870>,
                       'PositionButton': <ui.Button object at 0x37801670>,
                       'temp_window': <ui.ScriptWindow object at 0x377F5730>},
 'IsOpen': False,
 'PositionButton': <ui.Button object at 0x37801670>,
 'PositionChangeMode': False,
 'Scrollbar': <ui.ScrollBar object at 0x37801C10>,
 'SelectObjectIndex': 0,
 'ctrlRotationZ': <ui.SliderBar object at 0x37801750>,
 'emptyindex': 0,
 'hWnd': 717186824,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'questionDialog': None,
 'rot_x': 0,
 'rot_x_limit': 0,
 'rot_y': 0,
 'rot_y_limit': 0,
 'rot_z': 0,
 'rot_z_limit': 0,
 'selectindexlist': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'x': 0,
 'y': 0,
 'z': 0}
