{'AcceptButton': <ui.Button object at 0x3EE852D0>,
 'BuildGuildBuildingWindow': None,
 'CancelButton': <ui.Button object at 0x3EE85310>,
 'ChangeBuildingList': <ui.ListBox object at 0x3ED80470>,
 'ChangePositionBaseX': 0,
 'ChangePositionBaseY': 0,
 'Children': [<ui.BoardWithTitleBar object at 0x3ED80530>],
 'DeleteButton': <ui.Button object at 0x3EE851F0>,
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x3EE852D0>,
                       'Board': <ui.BoardWithTitleBar object at 0x3ED80530>,
                       'BuildingListBar': <ui.SlotBar object at 0x3ED80650>,
                       'BuildingRotationZ': <ui.SliderBar object at 0x3EE85250>,
                       'BuildingRotationZTitle': <ui.TextLine object at 0x3EE85230>,
                       'CancelButton': <ui.Button object at 0x3EE85310>,
                       'ChangeBuildingList': <ui.ListBox object at 0x3ED80470>,
                       'ChangeListScrollBar': <ui.ScrollBar object at 0x3ED80710>,
                       'DeleteButton': <ui.Button object at 0x3EE851F0>,
                       'InBuildingListTitle': <ui.TextLine object at 0x3ED80510>,
                       'PositionButton': <ui.Button object at 0x3EE85170>,
                       'temp_window': <ui.ScriptWindow object at 0x3ED80450>},
 'IsOpen': False,
 'PositionButton': <ui.Button object at 0x3EE85170>,
 'PositionChangeMode': False,
 'Scrollbar': <ui.ScrollBar object at 0x3ED80710>,
 'SelectObjectIndex': 0,
 'ctrlRotationZ': <ui.SliderBar object at 0x3EE85250>,
 'emptyindex': 0,
 'hWnd': 761668912,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'questionDialog': None,
 'rot_x': 0,
 'rot_x_limit': 0,
 'rot_y': 0,
 'rot_y_limit': 0,
 'rot_z': 0,
 'rot_z_limit': 0,
 'selectindexlist': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'x': 0,
 'y': 0,
 'z': 0}
