{'AcceptButton': <ui.Button object at 0x2EB85270>,
 'BuildGuildBuildingWindow': None,
 'CancelButton': <ui.Button object at 0x2EB852B0>,
 'ChangeBuildingList': <ui.ListBox object at 0x2E95AF30>,
 'ChangePositionBaseX': 0,
 'ChangePositionBaseY': 0,
 'Children': [<ui.BoardWithTitleBar object at 0x2EB8C490>],
 'DeleteButton': <ui.Button object at 0x2EB85190>,
 'ElementDictionary': {'AcceptButton': <ui.Button object at 0x2EB85270>,
                       'Board': <ui.BoardWithTitleBar object at 0x2EB8C490>,
                       'BuildingListBar': <ui.SlotBar object at 0x2E95AEF0>,
                       'BuildingRotationZ': <ui.SliderBar object at 0x2EB851F0>,
                       'BuildingRotationZTitle': <ui.TextLine object at 0x2EB851D0>,
                       'CancelButton': <ui.Button object at 0x2EB852B0>,
                       'ChangeBuildingList': <ui.ListBox object at 0x2E95AF30>,
                       'ChangeListScrollBar': <ui.ScrollBar object at 0x2E95AB10>,
                       'DeleteButton': <ui.Button object at 0x2EB85190>,
                       'InBuildingListTitle': <ui.TextLine object at 0x2E95ADD0>,
                       'PositionButton': <ui.Button object at 0x2EB85110>,
                       'temp_window': <ui.ScriptWindow object at 0x2E95ADF0>},
 'IsOpen': False,
 'PositionButton': <ui.Button object at 0x2EB85110>,
 'PositionChangeMode': False,
 'Scrollbar': <ui.ScrollBar object at 0x2E95AB10>,
 'SelectObjectIndex': 0,
 'ctrlRotationZ': <ui.SliderBar object at 0x2EB851F0>,
 'emptyindex': 0,
 'hWnd': 709583384,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'questionDialog': None,
 'rot_x': 0,
 'rot_x_limit': 0,
 'rot_y': 0,
 'rot_y_limit': 0,
 'rot_z': 0,
 'rot_z_limit': 0,
 'selectindexlist': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'x': 0,
 'y': 0,
 'z': 0}
