{'Children': [<ui.Board object at 0x30C62F30>],
 'DSSButton': <ui.Button object at 0x30A3CCD0>,
 'ElementDictionary': {'Cheque': <ui.TextLine object at 0x30A6B630>,
                       'Cheque_Icon': <ui.ImageBox object at 0x30A6B590>,
                       'Cheque_Slot': <ui.Button object at 0x30A6B3D0>,
                       'CostumeButton': <ui.Button object at 0x30A3C6B0>,
                       'DSSButton': <ui.Button object at 0x30A3CCD0>,
                       'EquipmentSlot': <ui.SlotWindow object at 0x30A3C7B0>,
                       'Equipment_Base': <ui.ImageBox object at 0x30A3CCF0>,
                       'Equipment_Tab_01': <ui.RadioButton object at 0x309FFB90>,
                       'Equipment_Tab_01_Print': <ui.TextLine object at 0x30A74C30>,
                       'Equipment_Tab_02': <ui.RadioButton object at 0x30A74C50>,
                       'Equipment_Tab_02_Print': <ui.TextLine object at 0x30A6B210>,
                       'Inventory_Tab_01': <ui.RadioButton object at 0x30A6B4B0>,
                       'Inventory_Tab_01_Print': <ui.TextLine object at 0x30A6B5F0>,
                       'Inventory_Tab_02': <ui.RadioButton object at 0x30A6B190>,
                       'Inventory_Tab_02_Print': <ui.TextLine object at 0x30A6B650>,
                       'Inventory_Tab_03': <ui.RadioButton object at 0x30A6B170>,
                       'Inventory_Tab_03_Print': <ui.TextLine object at 0x30A6B2D0>,
                       'Inventory_Tab_04': <ui.RadioButton object at 0x30A6B510>,
                       'Inventory_Tab_04_Print': <ui.TextLine object at 0x30A6B530>,
                       'ItemSlot': <ui.GridSlotWindow object at 0x30A6B290>,
                       'MallButton': <ui.Button object at 0x30A3C770>,
                       'Money': <ui.TextLine object at 0x30A6B370>,
                       'Money_Icon': <ui.ImageBox object at 0x30A6B250>,
                       'Money_Slot': <ui.Button object at 0x30A6B110>,
                       'TitleBar': <ui.TitleBar object at 0x308CDE30>,
                       'TitleName': <ui.TextLine object at 0x30A3CAD0>,
                       'board': <ui.Board object at 0x30C62F30>,
                       'premium_private_shop_button': <ui.Button object at 0x30A6B0F0>},
 'PetItemQuestionDlg': <uiCommon.QuestionDialog object at 0x30C57110>,
 'attachMetinDialog': <uiAttachMetin.AttachMetinDialog object at 0x30C57EB0>,
 'costumeButton': <ui.Button object at 0x30A3C6B0>,
 'dlgPickETC': <uiPickETC.PickETCDialog object at 0x30A6B1B0>,
 'dlgPickMoney': <uiPickMoney.PickMoneyDialog object at 0x30C57290>,
 'dlgQuestion': <uiCommon.QuestionDialog2 object at 0x30C57030>,
 'equipmentPageIndex': 0,
 'equipmentTab': [<ui.RadioButton object at 0x309FFB90>, <ui.RadioButton object at 0x30A74C50>],
 'hWnd': 733006912,
 'inventoryPageIndex': 0,
 'inventoryTab': [<ui.RadioButton object at 0x30A6B4B0>, <ui.RadioButton object at 0x30A6B190>],
 'isLoaded': 1,
 'isOpenedBeltWindowWhenClosingInventory': 0,
 'listHighlightedAcceSlot': [],
 'listHighlightedSlot': [],
 'mallButton': <ui.Button object at 0x30A3C770>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'refineDialog': <uiRefine.RefineDialog object at 0x30C570F0>,
 'toolTip': <uiToolTip.ToolTip object at 0x30A6B150>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndBelt': <uiInventory.BeltInventoryWindow object at 0x30C57050>,
 'wndCheque': <ui.TextLine object at 0x30A6B630>,
 'wndChequeIcon': <ui.ImageBox object at 0x30A6B590>,
 'wndChequeSlot': <ui.Button object at 0x30A6B3D0>,
 'wndCostume': None,
 'wndEquip': <ui.SlotWindow object at 0x30A3C7B0>,
 'wndItem': <ui.GridSlotWindow object at 0x30A6B290>,
 'wndMoney': <ui.TextLine object at 0x30A6B370>,
 'wndMoneyIcon': <ui.ImageBox object at 0x30A6B250>,
 'wndMoneySlot': <ui.Button object at 0x30A6B110>}
