{'Children': [<ui.ScriptWindow object at 0x2CF6C130>],
 'ElementDictionary': {'mini_game_window': <ui.ScriptWindow object at 0x2CF6C130>, 'minigame_rumi_button': <ui.Button object at 0x2CF6C690>, 'minigame_rumi_button_effect': <ui.AniImageBox object at 0x2D0AB090>},
 'attendance_game': None,
 'battle_royale_application': None,
 'catchking_game': None,
 'fish_game': None,
 'flower_event': None,
 'game_type': 12,
 'hWnd': 837533448,
 'interface': None,
 'inven': None,
 'isLoaded': 1,
 'isshow_mini_game_dialog': False,
 'main_game': None,
 'mini_boss_dungeon': None,
 'mini_game_bnw': None,
 'mini_game_dialog': <uiMiniGame.InGameEventDialog object at 0x2D0CD8D0>,
 'mini_game_roulette': None,
 'minigame_rumi_button': <ui.Button object at 0x2CF6C690>,
 'minigame_rumi_button_effect': <ui.AniImageBox object at 0x2D0AB090>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'other_world': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'rumi_game': None,
 'tooltipitem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'world_boss': None,
 'yutnori_game': None}
