{'Children': [<ui.Board object at 0x2DD3E530>],
 'ElementDictionary': {'BottomCenterImg': <ui.ExpandedImageBox object at 0x2DDABB10>,
                       'CenterImg': <ui.ExpandedImageBox object at 0x2DDABCF0>,
                       'LeftBottom': <ui.ImageBox object at 0x2DDAB790>,
                       'LeftCenterImg': <ui.ExpandedImageBox object at 0x2DDAB450>,
                       'LeftTop': <ui.ImageBox object at 0x2DDAB410>,
                       'RightBottom': <ui.ImageBox object at 0x2DDAB2D0>,
                       'RightCenterImg': <ui.ExpandedImageBox object at 0x2DDABB70>,
                       'RightTop': <ui.ImageBox object at 0x2DDAB690>,
                       'TitleName': <ui.TextLine object at 0x2DDABDB0>,
                       'TopCenterImg': <ui.ExpandedImageBox object at 0x2DDABA90>,
                       'board': <ui.Board object at 0x2DD3E530>,
                       'bottom_line': <ui.Line object at 0x2DDAB2B0>,
                       'desc_board': <ui.Bar object at 0x2DDAB810>,
                       'desc_next_button': <ui.Button object at 0x2DDAB390>,
                       'desc_prev_button': <ui.Button object at 0x2DDABE50>,
                       'disable_number_button1': <ui.Button object at 0x2DDABDF0>,
                       'disable_number_button10': <ui.Button object at 0x2DDABE10>,
                       'disable_number_button11': <ui.Button object at 0x2DDAB510>,
                       'disable_number_button12': <ui.Button object at 0x2DDAB3D0>,
                       'disable_number_button13': <ui.Button object at 0x2DDAB750>,
                       'disable_number_button14': <ui.Button object at 0x2DDABE30>,
                       'disable_number_button2': <ui.Button object at 0x2DDAB6B0>,
                       'disable_number_button3': <ui.Button object at 0x2DDABC30>,
                       'disable_number_button4': <ui.Button object at 0x2DDAB950>,
                       'disable_number_button5': <ui.Button object at 0x2DDABAB0>,
                       'disable_number_button6': <ui.Button object at 0x2DDAB370>,
                       'disable_number_button7': <ui.Button object at 0x2DDAB4F0>,
                       'disable_number_button8': <ui.Button object at 0x2DDAB7B0>,
                       'disable_number_button9': <ui.Button object at 0x2DDABAF0>,
                       'left_line': <ui.Line object at 0x2DDABC10>,
                       'next_button': <ui.Button object at 0x2DDABBD0>,
                       'number_board_window': <ui.ScriptWindow object at 0x2DDAB9F0>,
                       'number_effect': <ui.AniImageBox object at 0x2DDABB30>,
                       'prev_button': <ui.Button object at 0x2DDAB5D0>,
                       'right_line': <ui.Line object at 0x2DDAB7D0>,
                       'titlebar': <ui.TitleBar object at 0x2DDAB8D0>,
                       'top_line': <ui.Line object at 0x2DDABEB0>},
 'cur_attendance_number': 0,
 'cur_effect_number': 0,
 'cur_page': 0,
 'descBoard': <ui.Bar object at 0x2DDAB810>,
 'descIndex': 0,
 'desc_next_button': <ui.Button object at 0x2DDAB390>,
 'desc_prev_button': <ui.Button object at 0x2DDABE50>,
 'desc_y': 7,
 'descriptionBox': <uiMiniGameAttendance.DescriptionBox object at 0x2DDABA10>,
 'get_reward': 0,
 'hWnd': 719702968,
 'isLoaded': 1,
 'mission_clear': 0,
 'next_button': <ui.Button object at 0x2DDABBD0>,
 'number_board': <ui.ScriptWindow object at 0x2DDAB9F0>,
 'number_button': [None,
                   <ui.Button object at 0x2DDABDF0>,
                   <ui.Button object at 0x2DDAB6B0>,
                   <ui.Button object at 0x2DDABC30>,
                   <ui.Button object at 0x2DDAB950>,
                   <ui.Button object at 0x2DDABAB0>,
                   <ui.Button object at 0x2DDAB370>,
                   <ui.Button object at 0x2DDAB4F0>,
                   <ui.Button object at 0x2DDAB7B0>,
                   <ui.Button object at 0x2DDABAF0>,
                   <ui.Button object at 0x2DDABE10>,
                   <ui.Button object at 0x2DDAB510>,
                   <ui.Button object at 0x2DDAB3D0>,
                   <ui.Button object at 0x2DDAB750>,
                   <ui.Button object at 0x2DDABE30>,
                   None,
                   None],
 'number_effect': <ui.AniImageBox object at 0x2DDABB30>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'popup': None,
 'prev_button': <ui.Button object at 0x2DDAB5D0>,
 'reward_dict': {},
 'reward_question_dialog': None,
 'show_max': 14,
 'show_tooltip': False,
 'tooltipitem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
