{'cur_page': None,
 'game_page': <uiMiniGameCatchKing.CatchKingGamePage object at 0x3F19EA90>,
 'hWnd': 764882072,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'simple_waiting_page': <uiMiniGameCatchKing.CatchKingSimpleWaitingPage object at 0x3F17DE50>,
 'state': 1,
 'waiting_page': <uiMiniGameCatchKing.CatchKingWaitingPage object at 0x3ED85D10>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
