{'atlasWindow': None,
 'hWnd': 762554760,
 'isOpen': {1: True, 2: True},
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'rankWindow': None,
 'scoreWindow': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
