{'Children': [<ui.BoardWithTitleBar object at 0x30DE1B50>],
 'ElementDictionary': {'BoardImg': <ui.ExpandedImageBox object at 0x30DE1AF0>,
                       'BottomCenterImg': <ui.ExpandedImageBox object at 0x30DE1F30>,
                       'CenterImg': <ui.ExpandedImageBox object at 0x30DE1F50>,
                       'LeftBottom': <ui.ImageBox object at 0x30DE1590>,
                       'LeftCenterImg': <ui.ExpandedImageBox object at 0x30DE1EF0>,
                       'LeftTop': <ui.ImageBox object at 0x30DE1EB0>,
                       'RightBottom': <ui.ImageBox object at 0x30DE1550>,
                       'RightCenterImg': <ui.ExpandedImageBox object at 0x30DE1F10>,
                       'RightTop': <ui.ImageBox object at 0x30DE1ED0>,
                       'TopCenterImg': <ui.ExpandedImageBox object at 0x30DE15B0>,
                       'board': <ui.BoardWithTitleBar object at 0x30DE1B50>,
                       'board_window': <ui.ScriptWindow object at 0x30DE1E90>,
                       'end_img': <ui.ImageBox object at 0x30DE1B30>,
                       'enemy_img_bg': <ui.ExpandedImageBox object at 0x30E5B030>,
                       'enemy_img_bg2': <ui.ExpandedImageBox object at 0x30E5B050>,
                       'enemy_text': <ui.TextLine object at 0x30E5B0D0>,
                       'enemy_text_cover_img': <ui.ExpandedImageBox object at 0x30E5B090>,
                       'enemy_text_cover_over_img': <ui.ExpandedImageBox object at 0x30E5B0B0>,
                       'enemy_text_window': <ui.ScriptWindow object at 0x30E5B070>,
                       'etc_window': <ui.ScriptWindow object at 0x30DE1FF0>,
                       'goal_effect1': <ui.AniImageBox object at 0x30E5B150>,
                       'goal_effect2': <ui.AniImageBox object at 0x30E5B170>,
                       'goal_effect3': <ui.AniImageBox object at 0x30E5B190>,
                       'goal_text_effect': <ui.AniImageBox object at 0x30E5B1B0>,
                       'model_view': <ui.RenderTarget object at 0x30DE1BD0>,
                       'mouse_over_image': <ui.ExpandedImageBox object at 0x30DE1E30>,
                       'notice_img': <ui.ExpandedImageBox object at 0x30DE1F90>,
                       'notice_text': <ui.TextLine object at 0x30DE1FD0>,
                       'notice_window': <ui.ScriptWindow object at 0x30DE1FB0>,
                       'player_img_bg': <ui.ExpandedImageBox object at 0x30DE1030>,
                       'player_img_bg2': <ui.ExpandedImageBox object at 0x30DE1050>,
                       'player_text': <ui.TextLine object at 0x30DE10D0>,
                       'player_text_cover_img': <ui.ExpandedImageBox object at 0x30DE1090>,
                       'player_text_cover_over_img': <ui.ExpandedImageBox object at 0x30DE10B0>,
                       'player_text_window': <ui.ScriptWindow object at 0x30DE1070>,
                       'prob_select_button': <ui.Button object at 0x30DE1E50>,
                       'prob_select_window': <ui.ScriptWindow object at 0x30DE1E10>,
                       'probability_img': <ui.ExpandedImageBox object at 0x30DE1D70>,
                       'probability_text': <ui.TextLine object at 0x30DE1DF0>,
                       'probability_text_window': <ui.ScriptWindow object at 0x30DE1DD0>,
                       'probability_title': <ui.TextLine object at 0x30DE1DB0>,
                       'probability_title_window': <ui.ScriptWindow object at 0x30DE1D90>,
                       'remain_count_text': <ui.TextLine object at 0x30DE1D50>,
                       'remain_count_text_window': <ui.ScriptWindow object at 0x30DE1D30>,
                       'remain_count_title': <ui.TextLine object at 0x30DE1D10>,
                       'remain_count_title_window': <ui.ScriptWindow object at 0x30DE1CF0>,
                       'remain_img': <ui.ExpandedImageBox object at 0x30DE1CD0>,
                       'reward_button': <ui.Button object at 0x30E5B0F0>,
                       'score_img': <ui.ExpandedImageBox object at 0x30DE1BF0>,
                       'score_text': <ui.TextLine object at 0x30DE1CB0>,
                       'score_text_window': <ui.ScriptWindow object at 0x30DE1C90>,
                       'score_title': <ui.TextLine object at 0x30DE1C50>,
                       'score_title_window': <ui.ScriptWindow object at 0x30DE1C30>,
                       'yut_result_img': <ui.ExpandedImageBox object at 0x30DE1BB0>,
                       'yut_throw_button': <ui.Button object at 0x30DE1B70>},
 'area_dict': {1: <uiMiniGameYutnori.YutArea instance at 0x30DE2210>,
               2: <uiMiniGameYutnori.YutArea instance at 0x30DE2198>,
               3: <uiMiniGameYutnori.YutArea instance at 0x30DE2120>,
               4: <uiMiniGameYutnori.YutArea instance at 0x30DE20A8>,
               5: <uiMiniGameYutnori.YutArea instance at 0x30DE2030>,
               6: <uiMiniGameYutnori.YutArea instance at 0x30AA7F80>,
               7: <uiMiniGameYutnori.YutArea instance at 0x30AA7F08>,
               8: <uiMiniGameYutnori.YutArea instance at 0x30AA7E90>,
               9: <uiMiniGameYutnori.YutArea instance at 0x30AA7E18>,
               10: <uiMiniGameYutnori.YutArea instance at 0x30AA7DA0>,
               11: <uiMiniGameYutnori.YutArea instance at 0x30AA7D28>,
               12: <uiMiniGameYutnori.YutArea instance at 0x30DE2648>,
               13: <uiMiniGameYutnori.YutArea instance at 0x30DE25D0>,
               14: <uiMiniGameYutnori.YutArea instance at 0x30DE2558>,
               15: <uiMiniGameYutnori.YutArea instance at 0x30DE24E0>,
               16: <uiMiniGameYutnori.YutArea instance at 0x30DE2468>,
               17: <uiMiniGameYutnori.YutArea instance at 0x30DE23F0>,
               18: <uiMiniGameYutnori.YutArea instance at 0x30DE2378>,
               19: <uiMiniGameYutnori.YutArea instance at 0x30DE2300>,
               20: <uiMiniGameYutnori.YutArea instance at 0x30DE2288>,
               21: <uiMiniGameYutnori.YutArea instance at 0x30DE26C0>,
               22: <uiMiniGameYutnori.YutArea instance at 0x30DE2738>,
               23: <uiMiniGameYutnori.YutArea instance at 0x30DE27B0>,
               24: <uiMiniGameYutnori.YutArea instance at 0x30DE2828>,
               25: <uiMiniGameYutnori.YutArea instance at 0x30DE28A0>,
               26: <uiMiniGameYutnori.YutArea instance at 0x30DE2918>,
               27: <uiMiniGameYutnori.YutArea instance at 0x30DE2990>,
               28: <uiMiniGameYutnori.YutArea instance at 0x30DE2A08>,
               29: <uiMiniGameYutnori.YutArea instance at 0x30DE2A80>},
 'arrow_img': <ui.AniImageBox object at 0x30E5BDD0>,
 'before_score': 250,
 'board': <ui.BoardWithTitleBar object at 0x30DE1B50>,
 'catch_ani': <ui.AniImageBox object at 0x30E5B470>,
 'catch_deque': deque([]),
 'com_text': <ui.TextLine object at 0x30E5B0D0>,
 'com_text_cover_over_img': <ui.ExpandedImageBox object at 0x30E5B0B0>,
 'com_win_popup': None,
 'end_img': <ui.ImageBox object at 0x30DE1B30>,
 'enemy_list': [<uiMiniGameYutnori.Yut instance at 0x30AA7B70>, <uiMiniGameYutnori.Yut instance at 0x30AA7C38>],
 'event_deque': deque([]),
 'giveup_dialog': None,
 'goal_effect1': <ui.AniImageBox object at 0x30E5B150>,
 'goal_effect2': <ui.AniImageBox object at 0x30E5B170>,
 'goal_effect3': <ui.AniImageBox object at 0x30E5B190>,
 'goal_effect_end_frame_func': None,
 'goal_text_effect': <ui.AniImageBox object at 0x30E5B1B0>,
 'hWnd': 734972072,
 'isLoaded': 1,
 'is_actionable': True,
 'is_goal_text_effect': False,
 'model_view': <ui.RenderTarget object at 0x30DE1BD0>,
 'move_text_dict': {},
 'next_turn': True,
 'notice_text': <ui.TextLine object at 0x30DE1FD0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pc_turn': True,
 'pc_win_popup': None,
 'player_index': -1,
 'player_list': [<uiMiniGameYutnori.Yut instance at 0x30AA75F8>, <uiMiniGameYutnori.Yut instance at 0x30AA79E0>],
 'player_text': <ui.TextLine object at 0x30DE10D0>,
 'player_text_cover_over_img': <ui.ExpandedImageBox object at 0x30DE10B0>,
 'prob_index': 0,
 'prob_select_button': <ui.Button object at 0x30DE1E50>,
 'prob_select_button_list': [<ui.Button object at 0x30E5B270>, <ui.Button object at 0x30E5B2B0>, <ui.Button object at 0x30E5B2F0>, <ui.Button object at 0x30E5B330>, <ui.Button object at 0x30E5B370>, <ui.Button object at 0x30E5B3B0>],
 'prob_select_list_open': False,
 'prob_select_over_img': <ui.ExpandedImageBox object at 0x30DE1E30>,
 'prob_select_text': <ui.TextLine object at 0x30DE1DF0>,
 'prob_select_window': <ui.ScriptWindow object at 0x30DE1E10>,
 'prob_text_window': <ui.ScriptWindow object at 0x30DE1DD0>,
 'prob_title_widow': <ui.ScriptWindow object at 0x30DE1D90>,
 're_throw_popup': None,
 'remain_count_text': <ui.TextLine object at 0x30DE1D50>,
 'reward_button': <ui.Button object at 0x30E5B0F0>,
 'score': 250,
 'score_effect': None,
 'score_text': <ui.TextLine object at 0x30DE1CB0>,
 'toolTip': <uiToolTip.ToolTip object at 0x30A95070>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'yut_alpha_update': False,
 'yut_cur_alpha': 0.0,
 'yut_img': [<ui.ImageBox object at 0x30E5B3F0>, <ui.ImageBox object at 0x30E5B410>, <ui.ImageBox object at 0x30E5B430>, <ui.ImageBox object at 0x30E5B450>],
 'yut_result_com': 6,
 'yut_result_pc': 6,
 'yut_throw_button': <ui.Button object at 0x30DE1B70>,
 'yutnori_state': 3}
