{'Children': [<ui.BoardWithTitleBar object at 0x379A9FF0>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x379A9FF0>,
                       'item_slot': <ui.SlotWindow object at 0x379A3150>,
                       'main_bg': <ui.ImageBox object at 0x379A32F0>,
                       'slot_edge_effect': <ui.ImageBox object at 0x379A3750>,
                       'spin_button': <ui.Button object at 0x379A33D0>,
                       'spin_button_text1': <ui.TextLine object at 0x379A3650>,
                       'spin_button_text2': <ui.TextLine object at 0x379A37F0>,
                       'spin_button_text3': <ui.TextLine object at 0x379A3090>,
                       'spin_button_text_window1': <ui.ScriptWindow object at 0x379A3130>,
                       'spin_button_text_window2': <ui.ScriptWindow object at 0x379A3490>,
                       'spin_button_text_window3': <ui.ScriptWindow object at 0x379A3070>},
 'board': <ui.BoardWithTitleBar object at 0x379A9FF0>,
 'cur_index': 0,
 'hWnd': 718680920,
 'index_generator': <generator object at 0x376759F0>,
 'is_loaded': True,
 'is_request': False,
 'is_spin': False,
 'item_data_tuple': None,
 'item_slot': <ui.SlotWindow object at 0x379A3150>,
 'item_tooltip': None,
 'move_time': 0,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'once': False,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'popup_dlg': <uiCommon.PopupDialog object at 0x37989D50>,
 'request_time': 0,
 'reward_index': -1,
 'slot_edge_effect': <ui.ImageBox object at 0x379A3750>,
 'special_end_time': 0,
 'spin_button': <ui.Button object at 0x379A33D0>,
 'spin_data': None,
 'spin_lock': False,
 'start_pos_x': 0,
 'start_pos_y': 0,
 'start_spin_time': 0,
 'total_gap': 0,
 'update_gap': 0,
 'update_time': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
