{'cur_page': None,
 'game_page': <uiMiniGameRumi.RumiGamePage object at 0x30E3D090>,
 'hWnd': 735030680,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'state': 1,
 'waiting_page': <uiMiniGameRumi.RumiWaitingPage object at 0x30A95B90>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
