{'AtlasMainWindow': None,
 'Children': [],
 'ElementDictionary': {},
 'IsShowWindowValue': False,
 'board': 0,
 'hWnd': 848612672,
 'infoGuildMark': <ui.MarkBox object at 0x2DF834B0>,
 'mapName': '',
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'tooltipInfo': <uiMiniMap.MapTextToolTip object at 0x2E0B30D0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
