{'Children': [<ui.Board object at 0x2E88D7F0>],
 'ElementDictionary': {'BottomCenterImg': <ui.ExpandedImageBox object at 0x2EDAE7D0>,
                       'CenterImg': <ui.ExpandedImageBox object at 0x2EDAEC50>,
                       'LeftBottom': <ui.ImageBox object at 0x2EDAE1D0>,
                       'LeftCenterImg': <ui.ExpandedImageBox object at 0x2EDAEB10>,
                       'LeftTop': <ui.ImageBox object at 0x2EDAE470>,
                       'RightBottom': <ui.ImageBox object at 0x2EDAE7B0>,
                       'RightCenterImg': <ui.ExpandedImageBox object at 0x2EDAE8B0>,
                       'RightTop': <ui.ImageBox object at 0x2EDAE270>,
                       'TitleName': <ui.TextLine object at 0x2EDAECB0>,
                       'TopCenterImg': <ui.ExpandedImageBox object at 0x2EDAE8D0>,
                       'board': <ui.Board object at 0x2E88D7F0>,
                       'bottom_line': <ui.Line object at 0x2EDAE1F0>,
                       'desc_board': <ui.Bar object at 0x2EDAE650>,
                       'desc_next_button': <ui.Button object at 0x2EDAE350>,
                       'desc_prev_button': <ui.Button object at 0x2EDAE330>,
                       'disable_number_button1': <ui.Button object at 0x2EDAE4D0>,
                       'disable_number_button10': <ui.Button object at 0x2EDAE550>,
                       'disable_number_button11': <ui.Button object at 0x2EDAE570>,
                       'disable_number_button12': <ui.Button object at 0x2EDAE630>,
                       'disable_number_button13': <ui.Button object at 0x2EDAE590>,
                       'disable_number_button14': <ui.Button object at 0x2EDAE5B0>,
                       'disable_number_button2': <ui.Button object at 0x2EDAE870>,
                       'disable_number_button3': <ui.Button object at 0x2EDAE750>,
                       'disable_number_button4': <ui.Button object at 0x2EDAE510>,
                       'disable_number_button5': <ui.Button object at 0x2EDAE1B0>,
                       'disable_number_button6': <ui.Button object at 0x2EDAE850>,
                       'disable_number_button7': <ui.Button object at 0x2EDAE0D0>,
                       'disable_number_button8': <ui.Button object at 0x2EDAE3D0>,
                       'disable_number_button9': <ui.Button object at 0x2EDAE6D0>,
                       'left_line': <ui.Line object at 0x2EDAE2B0>,
                       'next_button': <ui.Button object at 0x2EDAE5F0>,
                       'number_board_window': <ui.ScriptWindow object at 0x2EDAE070>,
                       'number_effect': <ui.AniImageBox object at 0x2EDAE610>,
                       'prev_button': <ui.Button object at 0x2EDAE5D0>,
                       'right_line': <ui.Line object at 0x2EDAE670>,
                       'titlebar': <ui.TitleBar object at 0x2EDAE830>,
                       'top_line': <ui.Line object at 0x2EDAE2D0>},
 'cur_attendance_number': 0,
 'cur_effect_number': 0,
 'cur_page': 0,
 'descBoard': <ui.Bar object at 0x2EDAE650>,
 'descIndex': 0,
 'desc_next_button': <ui.Button object at 0x2EDAE350>,
 'desc_prev_button': <ui.Button object at 0x2EDAE330>,
 'desc_y': 7,
 'descriptionBox': <uiMiniGameAttendance.DescriptionBox object at 0x23E25870>,
 'get_reward': 0,
 'hWnd': 709616824,
 'isLoaded': 1,
 'mission_clear': 0,
 'next_button': <ui.Button object at 0x2EDAE5F0>,
 'number_board': <ui.ScriptWindow object at 0x2EDAE070>,
 'number_button': [None,
                   <ui.Button object at 0x2EDAE4D0>,
                   <ui.Button object at 0x2EDAE870>,
                   <ui.Button object at 0x2EDAE750>,
                   <ui.Button object at 0x2EDAE510>,
                   <ui.Button object at 0x2EDAE1B0>,
                   <ui.Button object at 0x2EDAE850>,
                   <ui.Button object at 0x2EDAE0D0>,
                   <ui.Button object at 0x2EDAE3D0>,
                   <ui.Button object at 0x2EDAE6D0>,
                   <ui.Button object at 0x2EDAE550>,
                   <ui.Button object at 0x2EDAE570>,
                   <ui.Button object at 0x2EDAE630>,
                   <ui.Button object at 0x2EDAE590>,
                   <ui.Button object at 0x2EDAE5B0>,
                   None,
                   None],
 'number_effect': <ui.AniImageBox object at 0x2EDAE610>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'popup': None,
 'prev_button': <ui.Button object at 0x2EDAE5D0>,
 'reward_dict': {},
 'reward_question_dialog': None,
 'show_max': 14,
 'show_tooltip': False,
 'tooltipitem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
