{'Children': [<ui.ExpandedImageBox object at 0x2E35EDB0>],
 'ElementDictionary': {'LeftTime': <ui.TextLine object at 0x2E35EE30>, 'TimerBG': <ui.ExpandedImageBox object at 0x2E35EDB0>},
 'hWnd': 789792288,
 'isLoad': 1,
 'leftTime': <ui.TextLine object at 0x2E35EE30>,
 'limitTime': 0,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'timerBG': <ui.ExpandedImageBox object at 0x2E35EDB0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
