{'cur_page': None,
 'game_page': <uiMiniGameCatchKing.CatchKingGamePage object at 0x30AC5AD0>,
 'hWnd': 734154696,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'simple_waiting_page': <uiMiniGameCatchKing.CatchKingSimpleWaitingPage object at 0x30AA07F0>,
 'state': 1,
 'waiting_page': <uiMiniGameCatchKing.CatchKingWaitingPage object at 0x30C57970>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
