{'cur_page': None,
 'game_page': <uiMiniGameCatchKing.CatchKingGamePage object at 0x2B479DD0>,
 'hWnd': 823383560,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'simple_waiting_page': <uiMiniGameCatchKing.CatchKingSimpleWaitingPage object at 0x2B2E2F50>,
 'state': 1,
 'waiting_page': <uiMiniGameCatchKing.CatchKingWaitingPage object at 0x2B2D7C90>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
