{'Children': [<ui.BoardWithTitleBar object at 0x30AC3B50>],
 'ElementDictionary': {'BoardImg': <ui.ExpandedImageBox object at 0x30AC3AF0>,
                       'BottomCenterImg': <ui.ExpandedImageBox object at 0x30AC3F30>,
                       'CenterImg': <ui.ExpandedImageBox object at 0x30AC3F50>,
                       'LeftBottom': <ui.ImageBox object at 0x30AC3590>,
                       'LeftCenterImg': <ui.ExpandedImageBox object at 0x30AC3EF0>,
                       'LeftTop': <ui.ImageBox object at 0x30AC3EB0>,
                       'RightBottom': <ui.ImageBox object at 0x30AC3550>,
                       'RightCenterImg': <ui.ExpandedImageBox object at 0x30AC3F10>,
                       'RightTop': <ui.ImageBox object at 0x30AC3ED0>,
                       'TopCenterImg': <ui.ExpandedImageBox object at 0x30AC35B0>,
                       'board': <ui.BoardWithTitleBar object at 0x30AC3B50>,
                       'board_window': <ui.ScriptWindow object at 0x30AC3E90>,
                       'end_img': <ui.ImageBox object at 0x30AC3B30>,
                       'enemy_img_bg': <ui.ExpandedImageBox object at 0x30B42030>,
                       'enemy_img_bg2': <ui.ExpandedImageBox object at 0x30B42050>,
                       'enemy_text': <ui.TextLine object at 0x30B420D0>,
                       'enemy_text_cover_img': <ui.ExpandedImageBox object at 0x30B42090>,
                       'enemy_text_cover_over_img': <ui.ExpandedImageBox object at 0x30B420B0>,
                       'enemy_text_window': <ui.ScriptWindow object at 0x30B42070>,
                       'etc_window': <ui.ScriptWindow object at 0x30AC3FF0>,
                       'goal_effect1': <ui.AniImageBox object at 0x30B42150>,
                       'goal_effect2': <ui.AniImageBox object at 0x30B42170>,
                       'goal_effect3': <ui.AniImageBox object at 0x30B42190>,
                       'goal_text_effect': <ui.AniImageBox object at 0x30B421B0>,
                       'model_view': <ui.RenderTarget object at 0x30AC3BD0>,
                       'mouse_over_image': <ui.ExpandedImageBox object at 0x30AC3E30>,
                       'notice_img': <ui.ExpandedImageBox object at 0x30AC3F90>,
                       'notice_text': <ui.TextLine object at 0x30AC3FD0>,
                       'notice_window': <ui.ScriptWindow object at 0x30AC3FB0>,
                       'player_img_bg': <ui.ExpandedImageBox object at 0x30AC3030>,
                       'player_img_bg2': <ui.ExpandedImageBox object at 0x30AC3050>,
                       'player_text': <ui.TextLine object at 0x30AC30D0>,
                       'player_text_cover_img': <ui.ExpandedImageBox object at 0x30AC3090>,
                       'player_text_cover_over_img': <ui.ExpandedImageBox object at 0x30AC30B0>,
                       'player_text_window': <ui.ScriptWindow object at 0x30AC3070>,
                       'prob_select_button': <ui.Button object at 0x30AC3E50>,
                       'prob_select_window': <ui.ScriptWindow object at 0x30AC3E10>,
                       'probability_img': <ui.ExpandedImageBox object at 0x30AC3D70>,
                       'probability_text': <ui.TextLine object at 0x30AC3DF0>,
                       'probability_text_window': <ui.ScriptWindow object at 0x30AC3DD0>,
                       'probability_title': <ui.TextLine object at 0x30AC3DB0>,
                       'probability_title_window': <ui.ScriptWindow object at 0x30AC3D90>,
                       'remain_count_text': <ui.TextLine object at 0x30AC3D50>,
                       'remain_count_text_window': <ui.ScriptWindow object at 0x30AC3D30>,
                       'remain_count_title': <ui.TextLine object at 0x30AC3D10>,
                       'remain_count_title_window': <ui.ScriptWindow object at 0x30AC3CF0>,
                       'remain_img': <ui.ExpandedImageBox object at 0x30AC3CD0>,
                       'reward_button': <ui.Button object at 0x30B420F0>,
                       'score_img': <ui.ExpandedImageBox object at 0x30AC3BF0>,
                       'score_text': <ui.TextLine object at 0x30AC3CB0>,
                       'score_text_window': <ui.ScriptWindow object at 0x30AC3C90>,
                       'score_title': <ui.TextLine object at 0x30AC3C50>,
                       'score_title_window': <ui.ScriptWindow object at 0x30AC3C30>,
                       'yut_result_img': <ui.ExpandedImageBox object at 0x30AC3BB0>,
                       'yut_throw_button': <ui.Button object at 0x30AC3B70>},
 'area_dict': {1: <uiMiniGameYutnori.YutArea instance at 0x30B53468>,
               2: <uiMiniGameYutnori.YutArea instance at 0x30B533F0>,
               3: <uiMiniGameYutnori.YutArea instance at 0x30B53378>,
               4: <uiMiniGameYutnori.YutArea instance at 0x30B53300>,
               5: <uiMiniGameYutnori.YutArea instance at 0x30B53288>,
               6: <uiMiniGameYutnori.YutArea instance at 0x30B53210>,
               7: <uiMiniGameYutnori.YutArea instance at 0x30B53198>,
               8: <uiMiniGameYutnori.YutArea instance at 0x30B53120>,
               9: <uiMiniGameYutnori.YutArea instance at 0x30B530A8>,
               10: <uiMiniGameYutnori.YutArea instance at 0x30B53030>,
               11: <uiMiniGameYutnori.YutArea instance at 0x308B6F80>,
               12: <uiMiniGameYutnori.YutArea instance at 0x30B538A0>,
               13: <uiMiniGameYutnori.YutArea instance at 0x30B53828>,
               14: <uiMiniGameYutnori.YutArea instance at 0x30B537B0>,
               15: <uiMiniGameYutnori.YutArea instance at 0x30B53738>,
               16: <uiMiniGameYutnori.YutArea instance at 0x30B536C0>,
               17: <uiMiniGameYutnori.YutArea instance at 0x30B53648>,
               18: <uiMiniGameYutnori.YutArea instance at 0x30B535D0>,
               19: <uiMiniGameYutnori.YutArea instance at 0x30B53558>,
               20: <uiMiniGameYutnori.YutArea instance at 0x30B534E0>,
               21: <uiMiniGameYutnori.YutArea instance at 0x30B53918>,
               22: <uiMiniGameYutnori.YutArea instance at 0x30B53990>,
               23: <uiMiniGameYutnori.YutArea instance at 0x30B53A08>,
               24: <uiMiniGameYutnori.YutArea instance at 0x30B53A80>,
               25: <uiMiniGameYutnori.YutArea instance at 0x30B53AF8>,
               26: <uiMiniGameYutnori.YutArea instance at 0x30B53B70>,
               27: <uiMiniGameYutnori.YutArea instance at 0x30B53BE8>,
               28: <uiMiniGameYutnori.YutArea instance at 0x30B53C60>,
               29: <uiMiniGameYutnori.YutArea instance at 0x30B53CD8>},
 'arrow_img': <ui.AniImageBox object at 0x30B42DB0>,
 'before_score': 250,
 'board': <ui.BoardWithTitleBar object at 0x30AC3B50>,
 'catch_ani': <ui.AniImageBox object at 0x30B42450>,
 'catch_deque': deque([]),
 'com_text': <ui.TextLine object at 0x30B420D0>,
 'com_text_cover_over_img': <ui.ExpandedImageBox object at 0x30B420B0>,
 'com_win_popup': None,
 'end_img': <ui.ImageBox object at 0x30AC3B30>,
 'enemy_list': [<uiMiniGameYutnori.Yut instance at 0x308B6DC8>, <uiMiniGameYutnori.Yut instance at 0x308B6E90>],
 'event_deque': deque([]),
 'giveup_dialog': None,
 'goal_effect1': <ui.AniImageBox object at 0x30B42150>,
 'goal_effect2': <ui.AniImageBox object at 0x30B42170>,
 'goal_effect3': <ui.AniImageBox object at 0x30B42190>,
 'goal_effect_end_frame_func': None,
 'goal_text_effect': <ui.AniImageBox object at 0x30B421B0>,
 'hWnd': 715700552,
 'isLoaded': 1,
 'is_actionable': True,
 'is_goal_text_effect': False,
 'model_view': <ui.RenderTarget object at 0x30AC3BD0>,
 'move_text_dict': {},
 'next_turn': True,
 'notice_text': <ui.TextLine object at 0x30AC3FD0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pc_turn': True,
 'pc_win_popup': None,
 'player_index': -1,
 'player_list': [<uiMiniGameYutnori.Yut instance at 0x308B6AF8>, <uiMiniGameYutnori.Yut instance at 0x308B6C38>],
 'player_text': <ui.TextLine object at 0x30AC30D0>,
 'player_text_cover_over_img': <ui.ExpandedImageBox object at 0x30AC30B0>,
 'prob_index': 0,
 'prob_select_button': <ui.Button object at 0x30AC3E50>,
 'prob_select_button_list': [<ui.Button object at 0x30B42250>, <ui.Button object at 0x30B42290>, <ui.Button object at 0x30B422D0>, <ui.Button object at 0x30B42310>, <ui.Button object at 0x30B42350>, <ui.Button object at 0x30B42390>],
 'prob_select_list_open': False,
 'prob_select_over_img': <ui.ExpandedImageBox object at 0x30AC3E30>,
 'prob_select_text': <ui.TextLine object at 0x30AC3DF0>,
 'prob_select_window': <ui.ScriptWindow object at 0x30AC3E10>,
 'prob_text_window': <ui.ScriptWindow object at 0x30AC3DD0>,
 'prob_title_widow': <ui.ScriptWindow object at 0x30AC3D90>,
 're_throw_popup': None,
 'remain_count_text': <ui.TextLine object at 0x30AC3D50>,
 'reward_button': <ui.Button object at 0x30B420F0>,
 'score': 250,
 'score_effect': None,
 'score_text': <ui.TextLine object at 0x30AC3CB0>,
 'toolTip': <uiToolTip.ToolTip object at 0x30AC3B10>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'yut_alpha_update': False,
 'yut_cur_alpha': 0.0,
 'yut_img': [<ui.ImageBox object at 0x30B423D0>, <ui.ImageBox object at 0x30B423F0>, <ui.ImageBox object at 0x30B42410>, <ui.ImageBox object at 0x30B42430>],
 'yut_result_com': 6,
 'yut_result_pc': 6,
 'yut_throw_button': <ui.Button object at 0x30AC3B70>,
 'yutnori_state': 3}
