{'cur_page': None,
 'game_page': <uiMiniGameFishEvent.FishEventGamePage object at 0x2C26B9D0>,
 'hWnd': 714739632,
 'inven': None,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'tooltipitem': None,
 'waiting_page': <uiMiniGameFishEvent.FishEventGameWaitingPage object at 0x2C26DE90>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
