{'Children': [<ui.BoardWithTitleBar object at 0x28CDC810>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x28CDC810>,
                       'item_slot': <ui.SlotWindow object at 0x28CDC9F0>,
                       'main_bg': <ui.ImageBox object at 0x28CDCA30>,
                       'slot_edge_effect': <ui.ImageBox object at 0x28CDCAD0>,
                       'spin_button': <ui.Button object at 0x28CDC8F0>,
                       'spin_button_text1': <ui.TextLine object at 0x28CDC7F0>,
                       'spin_button_text2': <ui.TextLine object at 0x28CDCA90>,
                       'spin_button_text3': <ui.TextLine object at 0x28CDC910>,
                       'spin_button_text_window1': <ui.ScriptWindow object at 0x28CDCA50>,
                       'spin_button_text_window2': <ui.ScriptWindow object at 0x28CDC9D0>,
                       'spin_button_text_window3': <ui.ScriptWindow object at 0x28CDC7B0>},
 'board': <ui.BoardWithTitleBar object at 0x28CDC810>,
 'cur_index': 0,
 'hWnd': 759398600,
 'index_generator': <generator object at 0x288E5670>,
 'is_loaded': True,
 'is_request': False,
 'is_spin': False,
 'item_data_tuple': None,
 'item_slot': <ui.SlotWindow object at 0x28CDC9F0>,
 'item_tooltip': None,
 'move_time': 0,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'once': False,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'popup_dlg': <uiCommon.PopupDialog object at 0x28CB3D30>,
 'request_time': 0,
 'reward_index': -1,
 'slot_edge_effect': <ui.ImageBox object at 0x28CDCAD0>,
 'special_end_time': 0,
 'spin_button': <ui.Button object at 0x28CDC8F0>,
 'spin_data': None,
 'spin_lock': False,
 'start_pos_x': 0,
 'start_pos_y': 0,
 'start_spin_time': 0,
 'total_gap': 0,
 'update_gap': 0,
 'update_time': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
