{'Children': [<ui.BoardWithTitleBar object at 0x37BA0230>],
 'ElementDictionary': {'BoardImg': <ui.ExpandedImageBox object at 0x37BA0270>,
                       'BottomCenterImg': <ui.ExpandedImageBox object at 0x37BA0670>,
                       'CenterImg': <ui.ExpandedImageBox object at 0x37BA0690>,
                       'LeftBottom': <ui.ImageBox object at 0x37BA05D0>,
                       'LeftCenterImg': <ui.ExpandedImageBox object at 0x37BA0630>,
                       'LeftTop': <ui.ImageBox object at 0x37BA0590>,
                       'RightBottom': <ui.ImageBox object at 0x37BA05F0>,
                       'RightCenterImg': <ui.ExpandedImageBox object at 0x37BA0650>,
                       'RightTop': <ui.ImageBox object at 0x37BA05B0>,
                       'TopCenterImg': <ui.ExpandedImageBox object at 0x37BA0610>,
                       'board': <ui.BoardWithTitleBar object at 0x37BA0230>,
                       'board_window': <ui.ScriptWindow object at 0x37BA0570>,
                       'end_img': <ui.ImageBox object at 0x37BA0290>,
                       'enemy_img_bg': <ui.ExpandedImageBox object at 0x37BA07F0>,
                       'enemy_img_bg2': <ui.ExpandedImageBox object at 0x37BA0810>,
                       'enemy_text': <ui.TextLine object at 0x37BA0890>,
                       'enemy_text_cover_img': <ui.ExpandedImageBox object at 0x37BA0850>,
                       'enemy_text_cover_over_img': <ui.ExpandedImageBox object at 0x37BA0870>,
                       'enemy_text_window': <ui.ScriptWindow object at 0x37BA0830>,
                       'etc_window': <ui.ScriptWindow object at 0x37BA0710>,
                       'goal_effect1': <ui.AniImageBox object at 0x37BA08F0>,
                       'goal_effect2': <ui.AniImageBox object at 0x37BA0910>,
                       'goal_effect3': <ui.AniImageBox object at 0x37BA0930>,
                       'goal_text_effect': <ui.AniImageBox object at 0x37BA0950>,
                       'model_view': <ui.RenderTarget object at 0x37BA0310>,
                       'mouse_over_image': <ui.ExpandedImageBox object at 0x37BA0530>,
                       'notice_img': <ui.ExpandedImageBox object at 0x37BA06B0>,
                       'notice_text': <ui.TextLine object at 0x37BA06F0>,
                       'notice_window': <ui.ScriptWindow object at 0x37BA06D0>,
                       'player_img_bg': <ui.ExpandedImageBox object at 0x37BA0730>,
                       'player_img_bg2': <ui.ExpandedImageBox object at 0x37BA0750>,
                       'player_text': <ui.TextLine object at 0x37BA07D0>,
                       'player_text_cover_img': <ui.ExpandedImageBox object at 0x37BA0790>,
                       'player_text_cover_over_img': <ui.ExpandedImageBox object at 0x37BA07B0>,
                       'player_text_window': <ui.ScriptWindow object at 0x37BA0770>,
                       'prob_select_button': <ui.Button object at 0x37BA0550>,
                       'prob_select_window': <ui.ScriptWindow object at 0x37BA0510>,
                       'probability_img': <ui.ExpandedImageBox object at 0x37BA0470>,
                       'probability_text': <ui.TextLine object at 0x37BA04F0>,
                       'probability_text_window': <ui.ScriptWindow object at 0x37BA04D0>,
                       'probability_title': <ui.TextLine object at 0x37BA04B0>,
                       'probability_title_window': <ui.ScriptWindow object at 0x37BA0490>,
                       'remain_count_text': <ui.TextLine object at 0x37BA0450>,
                       'remain_count_text_window': <ui.ScriptWindow object at 0x37BA0430>,
                       'remain_count_title': <ui.TextLine object at 0x37BA0410>,
                       'remain_count_title_window': <ui.ScriptWindow object at 0x37BA03F0>,
                       'remain_img': <ui.ExpandedImageBox object at 0x37BA03D0>,
                       'reward_button': <ui.Button object at 0x37BA08B0>,
                       'score_img': <ui.ExpandedImageBox object at 0x37BA0330>,
                       'score_text': <ui.TextLine object at 0x37BA03B0>,
                       'score_text_window': <ui.ScriptWindow object at 0x37BA0390>,
                       'score_title': <ui.TextLine object at 0x37BA0370>,
                       'score_title_window': <ui.ScriptWindow object at 0x37BA0350>,
                       'yut_result_img': <ui.ExpandedImageBox object at 0x37BA02F0>,
                       'yut_throw_button': <ui.Button object at 0x37BA02B0>},
 'area_dict': {1: <uiMiniGameYutnori.YutArea instance at 0x37BDB8C8>,
               2: <uiMiniGameYutnori.YutArea instance at 0x37BDB850>,
               3: <uiMiniGameYutnori.YutArea instance at 0x37BDB7D8>,
               4: <uiMiniGameYutnori.YutArea instance at 0x37BDB760>,
               5: <uiMiniGameYutnori.YutArea instance at 0x37BDB6E8>,
               6: <uiMiniGameYutnori.YutArea instance at 0x37BDB670>,
               7: <uiMiniGameYutnori.YutArea instance at 0x37BDB5F8>,
               8: <uiMiniGameYutnori.YutArea instance at 0x37BDB580>,
               9: <uiMiniGameYutnori.YutArea instance at 0x37BDB508>,
               10: <uiMiniGameYutnori.YutArea instance at 0x37BDB490>,
               11: <uiMiniGameYutnori.YutArea instance at 0x37BDB418>,
               12: <uiMiniGameYutnori.YutArea instance at 0x37BDBD00>,
               13: <uiMiniGameYutnori.YutArea instance at 0x37BDBC88>,
               14: <uiMiniGameYutnori.YutArea instance at 0x37BDBC10>,
               15: <uiMiniGameYutnori.YutArea instance at 0x37BDBB98>,
               16: <uiMiniGameYutnori.YutArea instance at 0x37BDBB20>,
               17: <uiMiniGameYutnori.YutArea instance at 0x37BDBAA8>,
               18: <uiMiniGameYutnori.YutArea instance at 0x37BDBA30>,
               19: <uiMiniGameYutnori.YutArea instance at 0x37BDB9B8>,
               20: <uiMiniGameYutnori.YutArea instance at 0x37BDB940>,
               21: <uiMiniGameYutnori.YutArea instance at 0x37BDBD78>,
               22: <uiMiniGameYutnori.YutArea instance at 0x37BDBDF0>,
               23: <uiMiniGameYutnori.YutArea instance at 0x37BDBE68>,
               24: <uiMiniGameYutnori.YutArea instance at 0x37BDBEE0>,
               25: <uiMiniGameYutnori.YutArea instance at 0x37BDBF58>,
               26: <uiMiniGameYutnori.YutArea instance at 0x37BDBFD0>,
               27: <uiMiniGameYutnori.YutArea instance at 0x37BE6080>,
               28: <uiMiniGameYutnori.YutArea instance at 0x37BE60F8>,
               29: <uiMiniGameYutnori.YutArea instance at 0x37BE6170>},
 'arrow_img': <ui.AniImageBox object at 0x379D1390>,
 'before_score': 250,
 'board': <ui.BoardWithTitleBar object at 0x37BA0230>,
 'catch_ani': <ui.AniImageBox object at 0x37BA0C90>,
 'catch_deque': deque([]),
 'com_text': <ui.TextLine object at 0x37BA0890>,
 'com_text_cover_over_img': <ui.ExpandedImageBox object at 0x37BA0870>,
 'com_win_popup': None,
 'end_img': <ui.ImageBox object at 0x37BA0290>,
 'enemy_list': [<uiMiniGameYutnori.Yut instance at 0x37BDB260>, <uiMiniGameYutnori.Yut instance at 0x37BDB328>],
 'event_deque': deque([]),
 'giveup_dialog': None,
 'goal_effect1': <ui.AniImageBox object at 0x37BA08F0>,
 'goal_effect2': <ui.AniImageBox object at 0x37BA0910>,
 'goal_effect3': <ui.AniImageBox object at 0x37BA0930>,
 'goal_effect_end_frame_func': None,
 'goal_text_effect': <ui.AniImageBox object at 0x37BA0950>,
 'hWnd': 718698168,
 'isLoaded': 1,
 'is_actionable': True,
 'is_goal_text_effect': False,
 'model_view': <ui.RenderTarget object at 0x37BA0310>,
 'move_text_dict': {},
 'next_turn': True,
 'notice_text': <ui.TextLine object at 0x37BA06F0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'pc_turn': True,
 'pc_win_popup': None,
 'player_index': -1,
 'player_list': [<uiMiniGameYutnori.Yut instance at 0x3798DCB0>, <uiMiniGameYutnori.Yut instance at 0x37BDB0D0>],
 'player_text': <ui.TextLine object at 0x37BA07D0>,
 'player_text_cover_over_img': <ui.ExpandedImageBox object at 0x37BA07B0>,
 'prob_index': 0,
 'prob_select_button': <ui.Button object at 0x37BA0550>,
 'prob_select_button_list': [<ui.Button object at 0x37BA0A90>, <ui.Button object at 0x37BA0AD0>, <ui.Button object at 0x37BA0B10>, <ui.Button object at 0x37BA0B50>, <ui.Button object at 0x37BA0B90>, <ui.Button object at 0x37BA0BD0>],
 'prob_select_list_open': False,
 'prob_select_over_img': <ui.ExpandedImageBox object at 0x37BA0530>,
 'prob_select_text': <ui.TextLine object at 0x37BA04F0>,
 'prob_select_window': <ui.ScriptWindow object at 0x37BA0510>,
 'prob_text_window': <ui.ScriptWindow object at 0x37BA04D0>,
 'prob_title_widow': <ui.ScriptWindow object at 0x37BA0490>,
 're_throw_popup': None,
 'remain_count_text': <ui.TextLine object at 0x37BA0450>,
 'reward_button': <ui.Button object at 0x37BA08B0>,
 'score': 250,
 'score_effect': None,
 'score_text': <ui.TextLine object at 0x37BA03B0>,
 'toolTip': <uiToolTip.ToolTip object at 0x37BA00D0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'yut_alpha_update': False,
 'yut_cur_alpha': 0.0,
 'yut_img': [<ui.ImageBox object at 0x37BA0C10>, <ui.ImageBox object at 0x37BA0C30>, <ui.ImageBox object at 0x37BA0C50>, <ui.ImageBox object at 0x37BA0C70>],
 'yut_result_com': 6,
 'yut_result_pc': 6,
 'yut_throw_button': <ui.Button object at 0x37BA02B0>,
 'yutnori_state': 3}
