{'Children': [<ui.ExpandedImageBox object at 0x3F0C30D0>],
 'ElementDictionary': {'LeftTime': <ui.TextLine object at 0x3F0C30F0>, 'TimerBG': <ui.ExpandedImageBox object at 0x3F0C30D0>},
 'hWnd': 763589768,
 'isLoad': 1,
 'leftTime': <ui.TextLine object at 0x3F0C30F0>,
 'limitTime': 0,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'timerBG': <ui.ExpandedImageBox object at 0x3F0C30D0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
