{'Children': [<ui.ExpandedImageBox object at 0x28B1A510>],
 'ElementDictionary': {'LeftTime': <ui.TextLine object at 0x28B1A530>, 'TimerBG': <ui.ExpandedImageBox object at 0x28B1A510>},
 'hWnd': 758208504,
 'isLoad': 1,
 'leftTime': <ui.TextLine object at 0x28B1A530>,
 'limitTime': 0,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'timerBG': <ui.ExpandedImageBox object at 0x28B1A510>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
