{'Children': [<ui.BoardWithTitleBar object at 0x2B896350>],
 'ElementDictionary': {'base_pattern': <ui.ScriptWindow object at 0x2B8960B0>,
                       'board': <ui.BoardWithTitleBar object at 0x2B896350>,
                       'cur_level_text': <ui.TextLine object at 0x2B896470>,
                       'cur_level_text_bg': <ui.ImageBox object at 0x2B896450>,
                       'cur_level_window': <ui.ScriptWindow object at 0x2B896430>,
                       'exp_gauge_bar': <ui.ExpandedImageBox object at 0x2B896550>,
                       'exp_gauge_bg': <ui.ImageBox object at 0x2B896530>,
                       'exp_gauge_text': <ui.TextLine object at 0x2B896570>,
                       'exp_gauge_window': <ui.ScriptWindow object at 0x2B896510>,
                       'feed_button': <ui.Button object at 0x2B896590>,
                       'gem_icon': <ui.ImageBox object at 0x2B896610>,
                       'gem_text': <ui.TextLine object at 0x2B896670>,
                       'gem_text_bg': <ui.ImageBox object at 0x2B896650>,
                       'gem_text_window': <ui.ScriptWindow object at 0x2B896630>,
                       'level_up_arrow': <ui.ImageBox object at 0x2B8964F0>,
                       'level_up_button': <ui.Button object at 0x2B8965D0>,
                       'mount_upgrade_system_bg': <ui.ScriptWindow object at 0x2B896410>,
                       'next_level_text': <ui.TextLine object at 0x2B8964D0>,
                       'next_level_text_bg': <ui.ImageBox object at 0x2B8964B0>,
                       'next_level_window': <ui.ScriptWindow object at 0x2B896490>,
                       'pattern_bottom_center_img': <ui.ExpandedImageBox object at 0x2B8963D0>,
                       'pattern_center_img': <ui.ExpandedImageBox object at 0x2B8963F0>,
                       'pattern_left_bottom_img': <ui.ImageBox object at 0x2B8960D0>,
                       'pattern_left_center_img': <ui.ExpandedImageBox object at 0x2B896390>,
                       'pattern_left_top_img': <ui.ImageBox object at 0x2B8962D0>,
                       'pattern_right_bottom_img': <ui.ImageBox object at 0x2B896250>,
                       'pattern_right_center_img': <ui.ExpandedImageBox object at 0x2B8963B0>,
                       'pattern_right_top_img': <ui.ImageBox object at 0x2B8961B0>,
                       'pattern_top_cetner_img': <ui.ExpandedImageBox object at 0x2B8961D0>,
                       'yang_icon': <ui.ImageBox object at 0x2B896690>,
                       'yang_text': <ui.TextLine object at 0x2B8966F0>,
                       'yang_text_bg': <ui.ImageBox object at 0x2B8966D0>,
                       'yang_window': <ui.ScriptWindow object at 0x2B8966B0>},
 '_MountUpgradeSystemWindow__exp_gauge_text_object': <ui.TextLine object at 0x2B896570>,
 '_MountUpgradeSystemWindow__popup_feed_window': <uiCommon.QuestionDialog object at 0x2B4F6890>,
 'hWnd': 823461960,
 'interface': None,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
