{'Children': [<ui.BoardWithTitleBar object at 0x2C4A5430>],
 'ElementDictionary': {'base_pattern': <ui.ScriptWindow object at 0x2C7D73F0>,
                       'board': <ui.BoardWithTitleBar object at 0x2C4A5430>,
                       'cur_level_text': <ui.TextLine object at 0x2C7D7CF0>,
                       'cur_level_text_bg': <ui.ImageBox object at 0x2C7D7890>,
                       'cur_level_window': <ui.ScriptWindow object at 0x2C7D78F0>,
                       'exp_gauge_bar': <ui.ExpandedImageBox object at 0x2C7D7CD0>,
                       'exp_gauge_bg': <ui.ImageBox object at 0x2C7D7FB0>,
                       'exp_gauge_text': <ui.TextLine object at 0x2C7D71B0>,
                       'exp_gauge_window': <ui.ScriptWindow object at 0x2C7D7CB0>,
                       'feed_button': <ui.Button object at 0x2C7D7FF0>,
                       'gem_icon': <ui.ImageBox object at 0x2C7D7770>,
                       'gem_text': <ui.TextLine object at 0x2C7D7690>,
                       'gem_text_bg': <ui.ImageBox object at 0x2C7D7D70>,
                       'gem_text_window': <ui.ScriptWindow object at 0x2C7D7B30>,
                       'level_up_arrow': <ui.ImageBox object at 0x2C7D76D0>,
                       'level_up_button': <ui.Button object at 0x2C7D7A50>,
                       'mount_upgrade_system_bg': <ui.ScriptWindow object at 0x2C7D7830>,
                       'next_level_text': <ui.TextLine object at 0x2C7D7790>,
                       'next_level_text_bg': <ui.ImageBox object at 0x2C7D7E10>,
                       'next_level_window': <ui.ScriptWindow object at 0x2C7D74D0>,
                       'pattern_bottom_center_img': <ui.ExpandedImageBox object at 0x2C7D7910>,
                       'pattern_center_img': <ui.ExpandedImageBox object at 0x2C7D7390>,
                       'pattern_left_bottom_img': <ui.ImageBox object at 0x2C7D7A90>,
                       'pattern_left_center_img': <ui.ExpandedImageBox object at 0x2C7D79F0>,
                       'pattern_left_top_img': <ui.ImageBox object at 0x2C7D77D0>,
                       'pattern_right_bottom_img': <ui.ImageBox object at 0x2C7D7550>,
                       'pattern_right_center_img': <ui.ExpandedImageBox object at 0x2C7D7F70>,
                       'pattern_right_top_img': <ui.ImageBox object at 0x2C7D7AD0>,
                       'pattern_top_cetner_img': <ui.ExpandedImageBox object at 0x2C7D7290>,
                       'yang_icon': <ui.ImageBox object at 0x2C7D7950>,
                       'yang_text': <ui.TextLine object at 0x2C7D71F0>,
                       'yang_text_bg': <ui.ImageBox object at 0x2C7D7EF0>,
                       'yang_window': <ui.ScriptWindow object at 0x2C7D7ED0>},
 '_MountUpgradeSystemWindow__exp_gauge_text_object': <ui.TextLine object at 0x2C7D71B0>,
 '_MountUpgradeSystemWindow__popup_feed_window': <uiCommon.QuestionDialog object at 0x2C7D7230>,
 'hWnd': 714781032,
 'interface': None,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
