{'Children': [<ui.BoardWithTitleBar object at 0x2D9311D0>],
 'ElementDictionary': {'base_pattern': <ui.ScriptWindow object at 0x2D9312D0>,
                       'board': <ui.BoardWithTitleBar object at 0x2D9311D0>,
                       'cur_level_text': <ui.TextLine object at 0x2D931470>,
                       'cur_level_text_bg': <ui.ImageBox object at 0x2D931450>,
                       'cur_level_window': <ui.ScriptWindow object at 0x2D931430>,
                       'exp_gauge_bar': <ui.ExpandedImageBox object at 0x2D931550>,
                       'exp_gauge_bg': <ui.ImageBox object at 0x2D931530>,
                       'exp_gauge_text': <ui.TextLine object at 0x2D931570>,
                       'exp_gauge_window': <ui.ScriptWindow object at 0x2D931510>,
                       'feed_button': <ui.Button object at 0x2D931590>,
                       'gem_icon': <ui.ImageBox object at 0x2D931610>,
                       'gem_text': <ui.TextLine object at 0x2D931670>,
                       'gem_text_bg': <ui.ImageBox object at 0x2D931650>,
                       'gem_text_window': <ui.ScriptWindow object at 0x2D931630>,
                       'level_up_arrow': <ui.ImageBox object at 0x2D9314F0>,
                       'level_up_button': <ui.Button object at 0x2D9315D0>,
                       'mount_upgrade_system_bg': <ui.ScriptWindow object at 0x2D931410>,
                       'next_level_text': <ui.TextLine object at 0x2D9314D0>,
                       'next_level_text_bg': <ui.ImageBox object at 0x2D9314B0>,
                       'next_level_window': <ui.ScriptWindow object at 0x2D931490>,
                       'pattern_bottom_center_img': <ui.ExpandedImageBox object at 0x2D9313D0>,
                       'pattern_center_img': <ui.ExpandedImageBox object at 0x2D9313F0>,
                       'pattern_left_bottom_img': <ui.ImageBox object at 0x2D931330>,
                       'pattern_left_center_img': <ui.ExpandedImageBox object at 0x2D931390>,
                       'pattern_left_top_img': <ui.ImageBox object at 0x2D9312F0>,
                       'pattern_right_bottom_img': <ui.ImageBox object at 0x2D931350>,
                       'pattern_right_center_img': <ui.ExpandedImageBox object at 0x2D9313B0>,
                       'pattern_right_top_img': <ui.ImageBox object at 0x2D931310>,
                       'pattern_top_cetner_img': <ui.ExpandedImageBox object at 0x2D931370>,
                       'yang_icon': <ui.ImageBox object at 0x2D931690>,
                       'yang_text': <ui.TextLine object at 0x2D9316F0>,
                       'yang_text_bg': <ui.ImageBox object at 0x2D9316D0>,
                       'yang_window': <ui.ScriptWindow object at 0x2D9316B0>},
 '_MountUpgradeSystemWindow__exp_gauge_text_object': <ui.TextLine object at 0x2D931570>,
 '_MountUpgradeSystemWindow__popup_feed_window': <uiCommon.QuestionDialog object at 0x2D931710>,
 'hWnd': 749522360,
 'interface': None,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
