{'Children': [<ui.BoardWithTitleBar object at 0x2D854AF0>],
 'ElementDictionary': {'additional_tab': <ui.ScriptWindow object at 0x2D854D30>,
                       'base_tab': <ui.ImageBox object at 0x2D854D10>,
                       'board': <ui.BoardWithTitleBar object at 0x2D854AF0>,
                       'costume_button': <ui.Button object at 0x2D854F50>,
                       'dragon_soul_button': <ui.Button object at 0x2D854E90>,
                       'equipment_base_image': <ui.ImageBox object at 0x2D854E30>,
                       'equipment_slot': <ui.SlotWindow object at 0x2D854E50>,
                       'equipment_window': <ui.ScriptWindow object at 0x2D854E10>,
                       'mall_button': <ui.Button object at 0x2D854ED0>,
                       'premium_private_shop_button': <ui.Button object at 0x2D854F10>,
                       'tab_btn_01': <ui.Button object at 0x2D854D90>,
                       'tab_btn_02': <ui.Button object at 0x2D854DD0>,
                       'tab_img_01': <ui.ImageBox object at 0x2D854D50>,
                       'tab_img_02': <ui.ImageBox object at 0x2D854D70>,
                       'unique_slot': <ui.SlotWindow object at 0x2D854E70>},
 '_EquipmentWindow__additional_tab': <ui.ScriptWindow object at 0x2D854D30>,
 '_EquipmentWindow__base_tab': <ui.ImageBox object at 0x2D854D10>,
 '_EquipmentWindow__costume_button': <ui.Button object at 0x2D854F50>,
 '_EquipmentWindow__current_page': 2,
 '_EquipmentWindow__dragon_soul_button': <ui.Button object at 0x2D854E90>,
 '_EquipmentWindow__equipment_slot': <ui.SlotWindow object at 0x2D854E50>,
 '_EquipmentWindow__interface': None,
 '_EquipmentWindow__is_enable_additional_page': False,
 '_EquipmentWindow__is_open_costume_window': False,
 '_EquipmentWindow__mall_button': <ui.Button object at 0x2D854ED0>,
 '_EquipmentWindow__premium_private_shop_button': <ui.Button object at 0x2D854F10>,
 '_EquipmentWindow__tab_btn': {0: <ui.Button object at 0x2D854D90>, 1: <ui.Button object at 0x2D854DD0>},
 '_EquipmentWindow__tab_img': {0: <ui.ImageBox object at 0x2D854D50>, 1: <ui.ImageBox object at 0x2D854D70>},
 '_EquipmentWindow__unique_slot': <ui.SlotWindow object at 0x2D854E70>,
 '_EquipmentWindow__wnd_belt': None,
 '_EquipmentWindow__wnd_costume': None,
 '_EquipmentWindow__wnd_inventory': None,
 'hWnd': 749539000,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
