{'Children': [<ui.BoardWithTitleBar object at 0x2E6F4B10>],
 'ElementDictionary': {'additional_tab': <ui.ScriptWindow object at 0x2E6F4D50>,
                       'base_tab': <ui.ImageBox object at 0x2E6F4D30>,
                       'board': <ui.BoardWithTitleBar object at 0x2E6F4B10>,
                       'costume_button': <ui.Button object at 0x2E6F4F70>,
                       'dragon_soul_button': <ui.Button object at 0x2E6F4EB0>,
                       'equipment_base_image': <ui.ImageBox object at 0x2E6F4E50>,
                       'equipment_slot': <ui.SlotWindow object at 0x2E6F4E70>,
                       'equipment_window': <ui.ScriptWindow object at 0x2E6F4E30>,
                       'mall_button': <ui.Button object at 0x2E6F4EF0>,
                       'premium_private_shop_button': <ui.Button object at 0x2E6F4F30>,
                       'tab_btn_01': <ui.Button object at 0x2E6F4DB0>,
                       'tab_btn_02': <ui.Button object at 0x2E6F4DF0>,
                       'tab_img_01': <ui.ImageBox object at 0x2E6F4D70>,
                       'tab_img_02': <ui.ImageBox object at 0x2E6F4D90>,
                       'unique_slot': <ui.SlotWindow object at 0x2E6F4E90>},
 '_EquipmentWindow__additional_tab': <ui.ScriptWindow object at 0x2E6F4D50>,
 '_EquipmentWindow__base_tab': <ui.ImageBox object at 0x2E6F4D30>,
 '_EquipmentWindow__costume_button': <ui.Button object at 0x2E6F4F70>,
 '_EquipmentWindow__current_page': 2,
 '_EquipmentWindow__dragon_soul_button': <ui.Button object at 0x2E6F4EB0>,
 '_EquipmentWindow__equipment_slot': <ui.SlotWindow object at 0x2E6F4E70>,
 '_EquipmentWindow__interface': None,
 '_EquipmentWindow__is_enable_additional_page': False,
 '_EquipmentWindow__is_open_costume_window': False,
 '_EquipmentWindow__mall_button': <ui.Button object at 0x2E6F4EF0>,
 '_EquipmentWindow__premium_private_shop_button': <ui.Button object at 0x2E6F4F30>,
 '_EquipmentWindow__tab_btn': {0: <ui.Button object at 0x2E6F4DB0>, 1: <ui.Button object at 0x2E6F4DF0>},
 '_EquipmentWindow__tab_img': {0: <ui.ImageBox object at 0x2E6F4D70>, 1: <ui.ImageBox object at 0x2E6F4D90>},
 '_EquipmentWindow__unique_slot': <ui.SlotWindow object at 0x2E6F4E90>,
 '_EquipmentWindow__wnd_belt': None,
 '_EquipmentWindow__wnd_costume': None,
 '_EquipmentWindow__wnd_inventory': None,
 'hWnd': 762588040,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
