{'Children': [<ui.BoardWithTitleBar object at 0x2C9D0A10>],
 'ElementDictionary': {'additional_tab': <ui.ScriptWindow object at 0x2C9D0C50>,
                       'base_tab': <ui.ImageBox object at 0x2C9D0C30>,
                       'board': <ui.BoardWithTitleBar object at 0x2C9D0A10>,
                       'costume_button': <ui.Button object at 0x2C9D0E70>,
                       'dragon_soul_button': <ui.Button object at 0x2C9D0DB0>,
                       'equipment_base_image': <ui.ImageBox object at 0x2C9D0D50>,
                       'equipment_slot': <ui.SlotWindow object at 0x2C9D0D70>,
                       'equipment_window': <ui.ScriptWindow object at 0x2C9D0D30>,
                       'mall_button': <ui.Button object at 0x2C9D0DF0>,
                       'premium_private_shop_button': <ui.Button object at 0x2C9D0E30>,
                       'tab_btn_01': <ui.Button object at 0x2C9D0CB0>,
                       'tab_btn_02': <ui.Button object at 0x2C9D0CF0>,
                       'tab_img_01': <ui.ImageBox object at 0x2C9D0C70>,
                       'tab_img_02': <ui.ImageBox object at 0x2C9D0C90>,
                       'unique_slot': <ui.SlotWindow object at 0x2C9D0D90>},
 '_EquipmentWindow__additional_tab': <ui.ScriptWindow object at 0x2C9D0C50>,
 '_EquipmentWindow__base_tab': <ui.ImageBox object at 0x2C9D0C30>,
 '_EquipmentWindow__costume_button': <ui.Button object at 0x2C9D0E70>,
 '_EquipmentWindow__current_page': 2,
 '_EquipmentWindow__dragon_soul_button': <ui.Button object at 0x2C9D0DB0>,
 '_EquipmentWindow__equipment_slot': <ui.SlotWindow object at 0x2C9D0D70>,
 '_EquipmentWindow__interface': None,
 '_EquipmentWindow__is_enable_additional_page': False,
 '_EquipmentWindow__is_open_costume_window': False,
 '_EquipmentWindow__mall_button': <ui.Button object at 0x2C9D0DF0>,
 '_EquipmentWindow__premium_private_shop_button': <ui.Button object at 0x2C9D0E30>,
 '_EquipmentWindow__tab_btn': {0: <ui.Button object at 0x2C9D0CB0>, 1: <ui.Button object at 0x2C9D0CF0>},
 '_EquipmentWindow__tab_img': {0: <ui.ImageBox object at 0x2C9D0C70>, 1: <ui.ImageBox object at 0x2C9D0C90>},
 '_EquipmentWindow__unique_slot': <ui.SlotWindow object at 0x2C9D0D90>,
 '_EquipmentWindow__wnd_belt': None,
 '_EquipmentWindow__wnd_costume': None,
 '_EquipmentWindow__wnd_inventory': None,
 'hWnd': 714789832,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
