{'Children': [<ui.BoardWithTitleBar object at 0x2E8137F0>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2E800370>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2E800390>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2E8002B0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2E800330>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2E800270>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2E800350>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2E800290>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2E800310>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2E8002F0>,
                       'board': <ui.BoardWithTitleBar object at 0x2E8137F0>,
                       'desc_board': <ui.Bar object at 0x2E8003B0>,
                       'desc_window': <ui.ScriptWindow object at 0x2E800250>,
                       'eve_event_time_label_text': <ui.TextLine object at 0x2E8003F0>,
                       'eve_event_time_label_text_window': <ui.ScriptWindow object at 0x2E8003D0>,
                       'eve_event_time_text': <ui.TextLine object at 0x2E800430>,
                       'eve_event_time_text_bg': <ui.ImageBox object at 0x2E800410>,
                       'event_time_label_text': <ui.TextLine object at 0x2E800470>,
                       'event_time_label_text_window': <ui.ScriptWindow object at 0x2E800450>,
                       'event_time_text': <ui.TextLine object at 0x2E8004B0>,
                       'event_time_text_bg': <ui.ImageBox object at 0x2E800490>,
                       'next_button': <ui.Button object at 0x2E8004F0>,
                       'prev_button': <ui.Button object at 0x2E8004D0>,
                       'wisp_button': <ui.Button object at 0x2E800510>},
 'hWnd': 764724856,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
