{'Children': [<ui.BoardWithTitleBar object at 0x2D854D90>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2D854DF0>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2D854E30>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2D854AB0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2D854F50>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2D854E50>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2D854CF0>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2D854DD0>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2D854ED0>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2D854BB0>,
                       'board': <ui.BoardWithTitleBar object at 0x2D854D90>,
                       'desc_board': <ui.Bar object at 0x2D854BF0>,
                       'desc_window': <ui.ScriptWindow object at 0x2D854CB0>,
                       'eve_event_time_label_text': <ui.TextLine object at 0x2D854E10>,
                       'eve_event_time_label_text_window': <ui.ScriptWindow object at 0x2D854DB0>,
                       'eve_event_time_text': <ui.TextLine object at 0x2D854C10>,
                       'eve_event_time_text_bg': <ui.ImageBox object at 0x2D854FB0>,
                       'event_time_label_text': <ui.TextLine object at 0x2D854F10>,
                       'event_time_label_text_window': <ui.ScriptWindow object at 0x2D854BD0>,
                       'event_time_text': <ui.TextLine object at 0x2D854E90>,
                       'event_time_text_bg': <ui.ImageBox object at 0x2D854F70>,
                       'next_button': <ui.Button object at 0x2D854F90>,
                       'prev_button': <ui.Button object at 0x2D854C70>,
                       'wisp_button': <ui.Button object at 0x2D854FD0>},
 'hWnd': 749547528,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
