{'Children': [<ui.BoardWithTitleBar object at 0x2C63A970>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2C63A050>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2C63ADD0>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2C63A1B0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2C63A210>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2C63AE70>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2C63A870>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2C63AD10>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2C63A3F0>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2C63A9B0>,
                       'board': <ui.BoardWithTitleBar object at 0x2C63A970>,
                       'desc_board': <ui.Bar object at 0x2C63AB30>,
                       'desc_window': <ui.ScriptWindow object at 0x2C63AFF0>,
                       'eve_event_time_label_text': <ui.TextLine object at 0x2C63A2B0>,
                       'eve_event_time_label_text_window': <ui.ScriptWindow object at 0x2C63A2F0>,
                       'eve_event_time_text': <ui.TextLine object at 0x2C63AA90>,
                       'eve_event_time_text_bg': <ui.ImageBox object at 0x2C63A990>,
                       'event_time_label_text': <ui.TextLine object at 0x2C63A4F0>,
                       'event_time_label_text_window': <ui.ScriptWindow object at 0x2C63A1F0>,
                       'event_time_text': <ui.TextLine object at 0x2C193FF0>,
                       'event_time_text_bg': <ui.ImageBox object at 0x2C193E90>,
                       'next_button': <ui.Button object at 0x2C1930D0>,
                       'prev_button': <ui.Button object at 0x2C1930B0>,
                       'wisp_button': <ui.Button object at 0x2C1937F0>},
 'hWnd': 792756696,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
