{'Children': [<ui.BoardWithTitleBar object at 0x2C7D7250>],
 'ElementDictionary': {'ActivateButton': <ui.ToggleButton object at 0x2C8301F0>,
                       'AddButton': <ui.Button object at 0x2C830630>,
                       'ChargeButton': <ui.Button object at 0x2C830770>,
                       'bg': <ui.ImageBox object at 0x2C830710>,
                       'board': <ui.BoardWithTitleBar object at 0x2C7D7250>,
                       'deck_button1': <ui.RadioButton object at 0x2C830670>,
                       'deck_button2': <ui.RadioButton object at 0x2C830750>,
                       'passive_attr_sub_slot': <ui.SlotWindow object at 0x2C8307B0>,
                       'passive_job_down_slot': <ui.SlotWindow object at 0x2C8306D0>,
                       'passive_job_up_slot': <ui.SlotWindow object at 0x2C8306F0>},
 '_PassiveAttr__activate_page': 0,
 '_PassiveAttr__charge_popup': <uiCommon.QuestionDialog object at 0x2C7C8C70>,
 '_PassiveAttr__destroy_popup': <uiCommon.QuestionDialog object at 0x2C7C89B0>,
 '_PassiveAttr__passive_job_slot_dict': {1: <ui.SlotWindow object at 0x2C8306F0>, 2: <ui.SlotWindow object at 0x2C8306D0>},
 'hWnd': 717417232,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
