{'Children': [<ui.BoardWithTitleBar object at 0x2E4604F0>],
 'ElementDictionary': {'ActivateButton': <ui.ToggleButton object at 0x18209B50>,
                       'AddButton': <ui.Button object at 0x18209970>,
                       'ChargeButton': <ui.Button object at 0x2DECBF70>,
                       'bg': <ui.ImageBox object at 0x2DECBB30>,
                       'board': <ui.BoardWithTitleBar object at 0x2E4604F0>,
                       'deck_button1': <ui.RadioButton object at 0x2DECB8F0>,
                       'deck_button2': <ui.RadioButton object at 0x2DECBB70>,
                       'passive_attr_sub_slot': <ui.SlotWindow object at 0x2DECBC90>,
                       'passive_job_down_slot': <ui.SlotWindow object at 0x2DECBA70>,
                       'passive_job_up_slot': <ui.SlotWindow object at 0x2DECBEB0>},
 '_PassiveAttr__activate_page': 0,
 '_PassiveAttr__charge_popup': <uiCommon.QuestionDialog object at 0x2DDA71D0>,
 '_PassiveAttr__destroy_popup': <uiCommon.QuestionDialog object at 0x2E460E10>,
 '_PassiveAttr__passive_job_slot_dict': {1: <ui.SlotWindow object at 0x2DECBEB0>, 2: <ui.SlotWindow object at 0x2DECBA70>},
 'hWnd': 851301392,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
