{'Children': [<ui.BoardWithTitleBar object at 0x2D6A25F0>],
 'ElementDictionary': {'ActivateButton': <ui.ToggleButton object at 0x2D4D6410>,
                       'AddButton': <ui.Button object at 0x2D4D6890>,
                       'ChargeButton': <ui.Button object at 0x2D4D6850>,
                       'bg': <ui.ImageBox object at 0x2D4D67D0>,
                       'board': <ui.BoardWithTitleBar object at 0x2D6A25F0>,
                       'deck_button1': <ui.RadioButton object at 0x2D4D60F0>,
                       'deck_button2': <ui.RadioButton object at 0x2D4D6810>,
                       'passive_attr_sub_slot': <ui.SlotWindow object at 0x2D4D67F0>,
                       'passive_job_down_slot': <ui.SlotWindow object at 0x2D4D6170>,
                       'passive_job_up_slot': <ui.SlotWindow object at 0x2D4D6390>},
 '_PassiveAttr__activate_page': 0,
 '_PassiveAttr__charge_popup': <uiCommon.QuestionDialog object at 0x2D6A2C30>,
 '_PassiveAttr__destroy_popup': <uiCommon.QuestionDialog object at 0x2D6A2A70>,
 '_PassiveAttr__passive_job_slot_dict': {1: <ui.SlotWindow object at 0x2D4D6390>, 2: <ui.SlotWindow object at 0x2D4D6170>},
 'hWnd': 841405664,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
