{'AFFECT_STRING_DICT': {0: <cyfunction SA.<locals>.f at 0x0B15EEF8>,
                        1: <cyfunction SA.<locals>.f at 0x0B15ED98>,
                        2: <cyfunction SA.<locals>.f at 0x0B15EDF0>,
                        3: <cyfunction SA.<locals>.f at 0x0B15EFA8>,
                        4: <cyfunction SA.<locals>.f at 0x0B15EE48>,
                        5: <cyfunction SA.<locals>.f at 0x0B15EF50>,
                        6: <cyfunction SA.<locals>.f at 0x0B15EEA0>,
                        7: <cyfunction SNA.<locals>.f at 0x0B17D088>,
                        8: <cyfunction SNA.<locals>.f at 0x0B17D0E0>},
 'Children': [<ui.Button object at 0x2B8968F0>,
              <ui.Bar object at 0x2B8963D0>,
              <ui.Gauge object at 0x2B895D90>,
              <ui.ImageBox object at 0x2B895E90>,
              <ui.ImageBox object at 0x2B895FB0>,
              <ui.ImageBox object at 0x2B895F30>,
              <ui.ImageBox object at 0x2B895DF0>,
              <ui.ImageBox object at 0x2B895E30>,
              <ui.ImageBox object at 0x2B895EB0>,
              <ui.ImageBox object at 0x2B706570>,
              <ui.ImageBox object at 0x2B7065F0>,
              <ui.ImageBox object at 0x2B706050>],
 'ElementDictionary': {'AttackerImage': <ui.ImageBox object at 0x2B895FB0>,
                       'BufferImage': <ui.ImageBox object at 0x2B895E30>,
                       'DefenderImage': <ui.ImageBox object at 0x2B895DF0>,
                       'ExperienceImage': <ui.ImageBox object at 0x2B895E90>,
                       'Gauge': <ui.Gauge object at 0x2B895D90>,
                       'IncreaseArea150': <ui.ImageBox object at 0x2B7065F0>,
                       'IncreaseArea200': <ui.ImageBox object at 0x2B706050>,
                       'NamePrint': <ui.TextLine object at 0x2B895F50>,
                       'NameSlot': <ui.Bar object at 0x2B8963D0>,
                       'RegenBonus': <ui.ImageBox object at 0x2B706570>,
                       'SkillMasterImage': <ui.ImageBox object at 0x2B895EB0>,
                       'StateButton': <ui.Button object at 0x2B8968F0>,
                       'TimeBonusImage': <ui.ImageBox object at 0x2B895F30>},
 'MEMBER_BUTTON_EXPEL': 12,
 'MEMBER_BUTTON_IMAGE_FILE_NAME_DICT': {1: 'party_state_leader', 2: 'party_state_attacker', 3: 'party_state_berserker', 4: 'party_state_tanker', 5: 'party_state_buffer', 6: 'party_state_skill_master', 7: 'party_state_defender', 10: 'party_state_normal', 11: 'party_skill_warp', 12: 'party_expel'},
 'MEMBER_BUTTON_NORMAL': 10,
 'MEMBER_BUTTON_PATH': 'd:/ymir work/ui/game/windows/',
 'MEMBER_BUTTON_WARP': 11,
 'PARTY_AFFECT_ATTACKER': 1,
 'PARTY_AFFECT_BERSERKER': 2,
 'PARTY_AFFECT_BUFFER': 4,
 'PARTY_AFFECT_DEFENDER': 6,
 'PARTY_AFFECT_EXPERIENCE': 0,
 'PARTY_AFFECT_INCREASE_AREA_150': 7,
 'PARTY_AFFECT_INCREASE_AREA_200': 8,
 'PARTY_AFFECT_SKILL_MASTER': 5,
 'PARTY_AFFECT_TANKER': 3,
 'PARTY_SKILL_HEAL': 1,
 'PARTY_SKILL_WARP': 2,
 'STATE_NAME_DICT': {2: 'T\xe1mad\xf3nak kinevez.', 3: 'D\xfch\xf6ng\xf5nek kinevez.', 4: 'T\xf5rharcos be\xe1ll\xedt\xe1s.', 5: 'Blokkol\xf3nak kinevez.', 6: 'K\xe9szs\xe9g mesternek kinevez.', 7: 'V\xe9d\xf5nek kinevez.'},
 'affectToolTip': <uiToolTip.ToolTip object at 0x2B318FD0>,
 'affectValueDict': {},
 'gauge': <ui.Gauge object at 0x2B895D90>,
 'hWnd': 823493360,
 'isShowStateButton': False,
 'nameTextLine': <ui.TextLine object at 0x2B895F50>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'partyAffectImageList': [<ui.ImageBox object at 0x2B895E90>,
                          <ui.ImageBox object at 0x2B895FB0>,
                          <ui.ImageBox object at 0x2B895F30>,
                          <ui.ImageBox object at 0x2B895DF0>,
                          <ui.ImageBox object at 0x2B895E30>,
                          <ui.ImageBox object at 0x2B895EB0>,
                          <ui.ImageBox object at 0x2B706570>,
                          <ui.ImageBox object at 0x2B7065F0>,
                          <ui.ImageBox object at 0x2B706050>],
 'pid': None,
 'state': -1,
 'stateButton': <ui.Button object at 0x2B8968F0>,
 'stateButtonDict': {2: <ui.Button object at 0x2B706E50>,
                     3: <ui.Button object at 0x2B706E70>,
                     4: <ui.Button object at 0x2B706C90>,
                     5: <ui.Button object at 0x2B706C50>,
                     6: <ui.Button object at 0x2B706CF0>,
                     7: <ui.Button object at 0x2B706D10>,
                     10: <ui.Button object at 0x2B706D30>,
                     11: <ui.Button object at 0x2B706D70>,
                     12: <ui.Button object at 0x2B706D90>},
 'tooltipMapName': <uiParty.TextToolTip object at 0x2B706E10>,
 'vid': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
