{'AFFECT_STRING_DICT': {0: <cyfunction SA.<locals>.f at 0x0A402B88>,
                        1: <cyfunction SA.<locals>.f at 0x0A402A28>,
                        2: <cyfunction SA.<locals>.f at 0x0A402A80>,
                        3: <cyfunction SA.<locals>.f at 0x0A402C38>,
                        4: <cyfunction SA.<locals>.f at 0x0A402AD8>,
                        5: <cyfunction SA.<locals>.f at 0x0A402BE0>,
                        6: <cyfunction SA.<locals>.f at 0x0A402B30>,
                        7: <cyfunction SNA.<locals>.f at 0x0A402C90>,
                        8: <cyfunction SNA.<locals>.f at 0x0A402CE8>},
 'Children': [<ui.Button object at 0x2E5A0AD0>,
              <ui.Bar object at 0x2E5A0AF0>,
              <ui.Gauge object at 0x2E5A0AB0>,
              <ui.ImageBox object at 0x2E5A09B0>,
              <ui.ImageBox object at 0x2E5A0610>,
              <ui.ImageBox object at 0x2E5A09F0>,
              <ui.ImageBox object at 0x2E5A05D0>,
              <ui.ImageBox object at 0x2E5A08D0>,
              <ui.ImageBox object at 0x2E5A0910>,
              <ui.ImageBox object at 0x2E5A0690>,
              <ui.ImageBox object at 0x2E5A0230>,
              <ui.ImageBox object at 0x2E5A0890>],
 'ElementDictionary': {'AttackerImage': <ui.ImageBox object at 0x2E5A0610>,
                       'BufferImage': <ui.ImageBox object at 0x2E5A08D0>,
                       'DefenderImage': <ui.ImageBox object at 0x2E5A05D0>,
                       'ExperienceImage': <ui.ImageBox object at 0x2E5A09B0>,
                       'Gauge': <ui.Gauge object at 0x2E5A0AB0>,
                       'IncreaseArea150': <ui.ImageBox object at 0x2E5A0230>,
                       'IncreaseArea200': <ui.ImageBox object at 0x2E5A0890>,
                       'NamePrint': <ui.TextLine object at 0x2E5A0A30>,
                       'NameSlot': <ui.Bar object at 0x2E5A0AF0>,
                       'RegenBonus': <ui.ImageBox object at 0x2E5A0690>,
                       'SkillMasterImage': <ui.ImageBox object at 0x2E5A0910>,
                       'StateButton': <ui.Button object at 0x2E5A0AD0>,
                       'TimeBonusImage': <ui.ImageBox object at 0x2E5A09F0>},
 'MEMBER_BUTTON_EXPEL': 12,
 'MEMBER_BUTTON_IMAGE_FILE_NAME_DICT': {1: 'party_state_leader', 2: 'party_state_attacker', 3: 'party_state_berserker', 4: 'party_state_tanker', 5: 'party_state_buffer', 6: 'party_state_skill_master', 7: 'party_state_defender', 10: 'party_state_normal', 11: 'party_skill_warp', 12: 'party_expel'},
 'MEMBER_BUTTON_NORMAL': 10,
 'MEMBER_BUTTON_PATH': 'd:/ymir work/ui/game/windows/',
 'MEMBER_BUTTON_WARP': 11,
 'PARTY_AFFECT_ATTACKER': 1,
 'PARTY_AFFECT_BERSERKER': 2,
 'PARTY_AFFECT_BUFFER': 4,
 'PARTY_AFFECT_DEFENDER': 6,
 'PARTY_AFFECT_EXPERIENCE': 0,
 'PARTY_AFFECT_INCREASE_AREA_150': 7,
 'PARTY_AFFECT_INCREASE_AREA_200': 8,
 'PARTY_AFFECT_SKILL_MASTER': 5,
 'PARTY_AFFECT_TANKER': 3,
 'PARTY_SKILL_HEAL': 1,
 'PARTY_SKILL_WARP': 2,
 'STATE_NAME_DICT': {2: 'T\xe1mad\xf3nak kinevez.', 3: 'D\xfch\xf6ng\xf5nek kinevez.', 4: 'T\xf5rharcos be\xe1ll\xedt\xe1s.', 5: 'Blokkol\xf3nak kinevez.', 6: 'K\xe9szs\xe9g mesternek kinevez.', 7: 'V\xe9d\xf5nek kinevez.'},
 'affectToolTip': <uiToolTip.ToolTip object at 0x2E71E4D0>,
 'affectValueDict': {},
 'gauge': <ui.Gauge object at 0x2E5A0AB0>,
 'hWnd': 791840208,
 'isShowStateButton': False,
 'nameTextLine': <ui.TextLine object at 0x2E5A0A30>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'partyAffectImageList': [<ui.ImageBox object at 0x2E5A09B0>,
                          <ui.ImageBox object at 0x2E5A0610>,
                          <ui.ImageBox object at 0x2E5A09F0>,
                          <ui.ImageBox object at 0x2E5A05D0>,
                          <ui.ImageBox object at 0x2E5A08D0>,
                          <ui.ImageBox object at 0x2E5A0910>,
                          <ui.ImageBox object at 0x2E5A0690>,
                          <ui.ImageBox object at 0x2E5A0230>,
                          <ui.ImageBox object at 0x2E5A0890>],
 'pid': None,
 'state': -1,
 'stateButton': <ui.Button object at 0x2E5A0AD0>,
 'stateButtonDict': {2: <ui.Button object at 0x2E5A0CD0>,
                     3: <ui.Button object at 0x2E5A0C90>,
                     4: <ui.Button object at 0x2E5A0D30>,
                     5: <ui.Button object at 0x2E5A0D50>,
                     6: <ui.Button object at 0x2E5A0D70>,
                     7: <ui.Button object at 0x2E5A0D90>,
                     10: <ui.Button object at 0x2E5A0DB0>,
                     11: <ui.Button object at 0x2E5A0DD0>,
                     12: <ui.Button object at 0x2E5A0E10>},
 'tooltipMapName': <uiParty.TextToolTip object at 0x2E5A0E90>,
 'vid': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
