{'Children': [<ui.Board object at 0x2D863E30>],
 'ElementDictionary': {'TitleBar': <ui.TitleBar object at 0x2D9523B0>,
                       'TitleName': <ui.TextLine object at 0x2D952350>,
                       'board': <ui.Board object at 0x2D863E30>,
                       'checkbox': <ui.ImageBox object at 0x2D952270>,
                       'checkbox_bg': <ui.ImageBox object at 0x2D9521D0>,
                       'checkbox_text': <ui.TextLine object at 0x2D952D90>,
                       'webBox': <ui.Box object at 0x2D952490>},
 'hWnd': 749572488,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
