{'Children': [],
 'ConfirmDialog': <ui.ScriptWindow object at 0x2D84EE30>,
 'ElementDictionary': {},
 'hWnd': 749571656,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
