{'Children': [<ui.BoardWithTitleBar object at 0x2B6E25B0>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x2B6E25B0>,
                       'item_slot': <ui.GridSlotWindow object at 0x2B6E2C50>,
                       'modify_button': <ui.Button object at 0x2B6E2A90>,
                       'position_icon': <ui.ImageBox object at 0x2B6E2E50>,
                       'remain_time_text': <ui.TextLine object at 0x2B6E2F30>,
                       'remain_time_text_bg': <ui.ImageBox object at 0x2B6E28D0>,
                       'remain_time_text_window': <ui.ScriptWindow object at 0x2B6E2B30>,
                       'reopen_button': <ui.Button object at 0x2B6E2C90>,
                       'sandglass_icon': <ui.ImageBox object at 0x2B6E2550>,
                       'shop_close_button': <ui.Button object at 0x2B6E2AB0>,
                       'shop_name_text': <ui.TextLine object at 0x2B6E2CD0>,
                       'shop_name_text_bg': <ui.ImageBox object at 0x2B6E2F90>,
                       'shop_name_text_window': <ui.ScriptWindow object at 0x2B6E22B0>,
                       'shop_notice_bg': <ui.ImageBox object at 0x2B6E24D0>,
                       'shop_notice_text': <ui.TextLine object at 0x2B6E29D0>,
                       'shop_notice_window': <ui.ScriptWindow object at 0x2B6E2BD0>,
                       'tab1': <ui.RadioButton object at 0x2B6E2C30>,
                       'tab2': <ui.RadioButton object at 0x2B6E2D30>,
                       'tax_adjustment_button': <ui.Button object at 0x2B6E2EF0>,
                       'won_icon': <ui.ImageBox object at 0x2B6E27F0>,
                       'won_text': <ui.TextLine object at 0x2B6E2990>,
                       'won_text_bg': <ui.ImageBox object at 0x2B6E2FB0>,
                       'won_text_window': <ui.ScriptWindow object at 0x2B6E2AF0>,
                       'yang_icon': <ui.ImageBox object at 0x2B6E2790>,
                       'yang_text': <ui.TextLine object at 0x2B6E2870>,
                       'yang_text_bg': <ui.ImageBox object at 0x2B6E2E70>,
                       'yang_text_window': <ui.ScriptWindow object at 0x2B6E2CB0>},
 '_PremiumPrivateShopDialog__price_input_dialog': None,
 '_PremiumPrivateShopDialog__private_shop_close_question_dialog': None,
 '_PremiumPrivateShopDialog__tax_adjustment_dialog': None,
 'hWnd': 825731592,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
