{'Children': [<ui.BoardWithTitleBar object at 0x28E28490>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x28E28490>,
                       'item_slot': <ui.GridSlotWindow object at 0x28FF8FD0>,
                       'modify_button': <ui.Button object at 0x28FF8B50>,
                       'position_icon': <ui.ImageBox object at 0x28FF8CB0>,
                       'remain_time_text': <ui.TextLine object at 0x28FF8D90>,
                       'remain_time_text_bg': <ui.ImageBox object at 0x28FF8EF0>,
                       'remain_time_text_window': <ui.ScriptWindow object at 0x28FF8BF0>,
                       'reopen_button': <ui.Button object at 0x28FF8C10>,
                       'sandglass_icon': <ui.ImageBox object at 0x28FF8CD0>,
                       'shop_close_button': <ui.Button object at 0x28FF8810>,
                       'shop_name_text': <ui.TextLine object at 0x28FF8E30>,
                       'shop_name_text_bg': <ui.ImageBox object at 0x28FF88D0>,
                       'shop_name_text_window': <ui.ScriptWindow object at 0x28FF8D50>,
                       'shop_notice_bg': <ui.ImageBox object at 0x28FF87F0>,
                       'shop_notice_text': <ui.TextLine object at 0x28FF88B0>,
                       'shop_notice_window': <ui.ScriptWindow object at 0x28FF8BD0>,
                       'tab1': <ui.RadioButton object at 0x28FF8950>,
                       'tab2': <ui.RadioButton object at 0x28FF8970>,
                       'tax_adjustment_button': <ui.Button object at 0x28FF8D70>,
                       'won_icon': <ui.ImageBox object at 0x28FF8B90>,
                       'won_text': <ui.TextLine object at 0x28FF8E50>,
                       'won_text_bg': <ui.ImageBox object at 0x28FF8EB0>,
                       'won_text_window': <ui.ScriptWindow object at 0x28FF8E90>,
                       'yang_icon': <ui.ImageBox object at 0x28FF8DB0>,
                       'yang_text': <ui.TextLine object at 0x28FF8FF0>,
                       'yang_text_bg': <ui.ImageBox object at 0x28FF8C50>,
                       'yang_text_window': <ui.ScriptWindow object at 0x28FF8ED0>},
 '_PremiumPrivateShopDialog__price_input_dialog': None,
 '_PremiumPrivateShopDialog__private_shop_close_question_dialog': None,
 '_PremiumPrivateShopDialog__tax_adjustment_dialog': None,
 'hWnd': 759728616,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
