{'Children': [<ui.BoardWithTitleBar object at 0x2D4C35F0>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x2D4C35F0>,
                       'item_slot': <ui.GridSlotWindow object at 0x2D6B5B50>,
                       'modify_button': <ui.Button object at 0x2D6B5D90>,
                       'position_icon': <ui.ImageBox object at 0x2D6B53F0>,
                       'remain_time_text': <ui.TextLine object at 0x2D6B5F90>,
                       'remain_time_text_bg': <ui.ImageBox object at 0x2D6B5E50>,
                       'remain_time_text_window': <ui.ScriptWindow object at 0x2D6B5CB0>,
                       'reopen_button': <ui.Button object at 0x2D6B5790>,
                       'sandglass_icon': <ui.ImageBox object at 0x2D6B5A50>,
                       'shop_close_button': <ui.Button object at 0x2D6B5BB0>,
                       'shop_name_text': <ui.TextLine object at 0x2D6B5AF0>,
                       'shop_name_text_bg': <ui.ImageBox object at 0x2D6B5BF0>,
                       'shop_name_text_window': <ui.ScriptWindow object at 0x2D6B5EB0>,
                       'shop_notice_bg': <ui.ImageBox object at 0x2D6B58F0>,
                       'shop_notice_text': <ui.TextLine object at 0x2D6B5B70>,
                       'shop_notice_window': <ui.ScriptWindow object at 0x2D6B51F0>,
                       'tab1': <ui.RadioButton object at 0x2D6B5B90>,
                       'tab2': <ui.RadioButton object at 0x2D6B5DF0>,
                       'tax_adjustment_button': <ui.Button object at 0x2D6B59B0>,
                       'won_icon': <ui.ImageBox object at 0x2D6B5710>,
                       'won_text': <ui.TextLine object at 0x2D6B5ED0>,
                       'won_text_bg': <ui.ImageBox object at 0x2D6B5FF0>,
                       'won_text_window': <ui.ScriptWindow object at 0x2D6B5A10>,
                       'yang_icon': <ui.ImageBox object at 0x2D6B58B0>,
                       'yang_text': <ui.TextLine object at 0x2D6B5BD0>,
                       'yang_text_bg': <ui.ImageBox object at 0x2D6B5FB0>,
                       'yang_text_window': <ui.ScriptWindow object at 0x2D6B56B0>},
 '_PremiumPrivateShopDialog__price_input_dialog': None,
 '_PremiumPrivateShopDialog__private_shop_close_question_dialog': None,
 '_PremiumPrivateShopDialog__tax_adjustment_dialog': None,
 'hWnd': 841355152,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
