{'Children': [<ui.Board object at 0x2D6B5550>],
 'ElementDictionary': {'ChangePasswordButton': <ui.Button object at 0x2D6BA430>, 'ExitButton': <ui.Button object at 0x2D6BA490>, 'TitleBar': <ui.TitleBar object at 0x2D6BA370>, 'TitleName': <ui.TextLine object at 0x2D6BA1F0>, 'board': <ui.Board object at 0x2D6B5550>},
 'curPageIndex': 0,
 'dlgChangePassword': <uiSafebox.ChangePasswordDialog object at 0x2D6BA690>,
 'dlgPickMoney': <uiPickMoney.PickMoneyDialog object at 0x2D6BA090>,
 'hWnd': 841363600,
 'interface': None,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'pageButtonList': [<ui.RadioButton object at 0x2D6BAD70>],
 'parentWindow': 0,
 'sellingSlotNumber': -1,
 'timeSendClosePacket': 0,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndBoard': <ui.Board object at 0x2D6B5550>,
 'wndItem': <ui.GridSlotWindow object at 0x2D6B5E10>,
 'xSafeBoxStart': 0,
 'ySafeBoxStart': 0}
