{'Children': [<ui.Board object at 0x30D9C130>],
 'ElementDictionary': {'ChangePasswordButton': <ui.Button object at 0x30D9CF90>, 'ExitButton': <ui.Button object at 0x30D9C5F0>, 'TitleBar': <ui.TitleBar object at 0x30D9C810>, 'TitleName': <ui.TextLine object at 0x30D9C1D0>, 'board': <ui.Board object at 0x30D9C130>},
 'curPageIndex': 0,
 'dlgChangePassword': <uiSafebox.ChangePasswordDialog object at 0x30D9C3D0>,
 'dlgPickMoney': <uiPickMoney.PickMoneyDialog object at 0x30D9C270>,
 'hWnd': 715885984,
 'interface': None,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'pageButtonList': [<ui.RadioButton object at 0x30D8E610>],
 'parentWindow': 0,
 'sellingSlotNumber': -1,
 'timeSendClosePacket': 0,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndBoard': <ui.Board object at 0x30D9C130>,
 'wndItem': <ui.GridSlotWindow object at 0x30D9C8B0>,
 'xSafeBoxStart': 0,
 'ySafeBoxStart': 0}
