{'Children': [<ui.Board object at 0x2E56A710>],
 'ElementDictionary': {'ChangePasswordButton': <ui.Button object at 0x2E56A950>, 'ExitButton': <ui.Button object at 0x2E56A550>, 'TitleBar': <ui.TitleBar object at 0x2E56A890>, 'TitleName': <ui.TextLine object at 0x2E56A4D0>, 'board': <ui.Board object at 0x2E56A710>},
 'curPageIndex': 0,
 'dlgChangePassword': <uiSafebox.ChangePasswordDialog object at 0x2E56A5B0>,
 'dlgPickMoney': <uiPickMoney.PickMoneyDialog object at 0x2E56A3F0>,
 'hWnd': 791871360,
 'interface': None,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'pageButtonList': [<ui.RadioButton object at 0x2E56A530>],
 'parentWindow': 0,
 'sellingSlotNumber': -1,
 'timeSendClosePacket': 0,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'wndBoard': <ui.Board object at 0x2E56A710>,
 'wndItem': <ui.GridSlotWindow object at 0x2E540F70>,
 'xSafeBoxStart': 0,
 'ySafeBoxStart': 0}
