{'Children': [<ui.Board object at 0x30D8BFB0>],
 'ElementDictionary': {'ExitButton': <ui.Button object at 0x30D8EED0>, 'ItemSlot': <ui.GridSlotWindow object at 0x30D8ED90>, 'TitleBar': <ui.TitleBar object at 0x30D8EDD0>, 'TitleName': <ui.TextLine object at 0x30D8EE10>, 'board': <ui.Board object at 0x30D8BFB0>},
 'board': <ui.Board object at 0x30D8BFB0>,
 'btnExit': <ui.Button object at 0x30D8EED0>,
 'hWnd': 715902352,
 'inventorySlotPosDict': {},
 'itemSlot': <ui.GridSlotWindow object at 0x30D8ED90>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'select_item_window_start_position_x': 0,
 'select_item_window_start_position_y': 0,
 'titleBar': <ui.TitleBar object at 0x30D8EDD0>,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
