{'Children': [<ui.Board object at 0x2E4E28D0>],
 'ElementDictionary': {'ExitButton': <ui.Button object at 0x2E4EAEB0>, 'ItemSlot': <ui.GridSlotWindow object at 0x2E4EA8B0>, 'TitleBar': <ui.TitleBar object at 0x2E4EAD90>, 'TitleName': <ui.TextLine object at 0x2E4EA8F0>, 'board': <ui.Board object at 0x2E4E28D0>},
 'board': <ui.Board object at 0x2E4E28D0>,
 'btnExit': <ui.Button object at 0x2E4EAEB0>,
 'hWnd': 909066104,
 'inventorySlotPosDict': {},
 'itemSlot': <ui.GridSlotWindow object at 0x2E4EA8B0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'select_item_window_start_position_x': 0,
 'select_item_window_start_position_y': 0,
 'titleBar': <ui.TitleBar object at 0x2E4EAD90>,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
