{'Children': [<ui.Board object at 0x2D952350>],
 'ElementDictionary': {'ExitButton': <ui.Button object at 0x2D941030>, 'ItemSlot': <ui.GridSlotWindow object at 0x2D9398B0>, 'TitleBar': <ui.TitleBar object at 0x2D952E10>, 'TitleName': <ui.TextLine object at 0x2D9399F0>, 'board': <ui.Board object at 0x2D952350>},
 'board': <ui.Board object at 0x2D952350>,
 'btnExit': <ui.Button object at 0x2D941030>,
 'hWnd': 751191312,
 'inventorySlotPosDict': {},
 'itemSlot': <ui.GridSlotWindow object at 0x2D9398B0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'select_item_window_start_position_x': 0,
 'select_item_window_start_position_y': 0,
 'titleBar': <ui.TitleBar object at 0x2D952E10>,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
