{'Children': [<ui.Board object at 0x2D6B5530>],
 'ElementDictionary': {'ExitButton': <ui.Button object at 0x2D6A2770>, 'ItemSlot': <ui.GridSlotWindow object at 0x2D6A2B50>, 'TitleBar': <ui.TitleBar object at 0x2D6A29F0>, 'TitleName': <ui.TextLine object at 0x2D6A2910>, 'board': <ui.Board object at 0x2D6B5530>},
 'board': <ui.Board object at 0x2D6B5530>,
 'btnExit': <ui.Button object at 0x2D6A2770>,
 'hWnd': 841385424,
 'inventorySlotPosDict': {},
 'itemSlot': <ui.GridSlotWindow object at 0x2D6A2B50>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'select_item_window_start_position_x': 0,
 'select_item_window_start_position_y': 0,
 'titleBar': <ui.TitleBar object at 0x2D6A29F0>,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
