{'Children': [<ui.Board object at 0x2E933A10>],
 'ElementDictionary': {'ExitButton': <ui.Button object at 0x2E826050>, 'ItemSlot': <ui.GridSlotWindow object at 0x2E826030>, 'TitleBar': <ui.TitleBar object at 0x2E9331D0>, 'TitleName': <ui.TextLine object at 0x2E91F330>, 'board': <ui.Board object at 0x2E933A10>},
 'board': <ui.Board object at 0x2E933A10>,
 'btnExit': <ui.Button object at 0x2E826050>,
 'hWnd': 764771240,
 'inventorySlotPosDict': {},
 'itemSlot': <ui.GridSlotWindow object at 0x2E826030>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'select_item_window_start_position_x': 0,
 'select_item_window_start_position_y': 0,
 'titleBar': <ui.TitleBar object at 0x2E9331D0>,
 'tooltipItem': None,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
