{'Children': [],
 'ElementDictionary': {},
 'hWnd': 851264608,
 'inven': None,
 'itemToolTip': <uiToolTip.ItemToolTip object at 0x2E45AA50>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
