{'Children': [],
 'ElementDictionary': {},
 'accept_button': None,
 'cancel_button': None,
 'hWnd': 764766456,
 'inven': None,
 'is_loaded': False,
 'item_tooltip': <uiToolTip.ItemToolTip object at 0x2E933AF0>,
 'need_money_loca': None,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'skillbook_list': [None, None, None, None, None, None, None, None, None, None],
 'slot': None,
 'start_pos_x': 0,
 'start_pos_y': 0,
 'title_loca': None,
 'type': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
