{'Children': [<ui.ImageBox object at 0x30D45350>,
              <ui.ScriptWindow object at 0x30D6A0F0>,
              <ui.ImageBox object at 0x30D6A130>,
              <ui.ImageBox object at 0x30D6A1B0>,
              <ui.ImageBox object at 0x30D6A190>,
              <ui.ScriptWindow object at 0x30D6A1D0>,
              <ui.ExpandedImageBox object at 0x30D6A1F0>,
              <ui.ScriptWindow object at 0x30D6A230>,
              <ui.Button object at 0x30D6A250>],
 'ElementDictionary': {'1stage_clear_icon': <ui.ImageBox object at 0x30D6A130>,
                       '2stage_clear_icon': <ui.ImageBox object at 0x30D6A1B0>,
                       '3stage_clear_icon': <ui.ImageBox object at 0x30D6A190>,
                       'alarm_text': <ui.TextLine object at 0x30D6A210>,
                       'alarm_text_window': <ui.ScriptWindow object at 0x30D6A1D0>,
                       'exit_button': <ui.Button object at 0x30D6A250>,
                       'floor_text': <ui.TextLine object at 0x30D6A150>,
                       'floor_text_window': <ui.ScriptWindow object at 0x30D6A0F0>,
                       'information_bg': <ui.ImageBox object at 0x30D45350>,
                       'time_gauge': <ui.ExpandedImageBox object at 0x30D6A1F0>,
                       'time_text': <ui.TextLine object at 0x30D6A270>,
                       'time_text_window': <ui.ScriptWindow object at 0x30D6A230>},
 '_SungmaheeTowerInformationBoard__is_time_stopped': True,
 'hWnd': 717629960,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
