{'Children': [<ui.ImageBox object at 0x2E91F330>,
              <ui.ScriptWindow object at 0x2E91FC90>,
              <ui.ImageBox object at 0x2E91FF90>,
              <ui.ImageBox object at 0x2E91FBD0>,
              <ui.ImageBox object at 0x2E91FB50>,
              <ui.ScriptWindow object at 0x2E91F1B0>,
              <ui.ExpandedImageBox object at 0x2E776090>,
              <ui.ScriptWindow object at 0x2E776110>,
              <ui.Button object at 0x2E776170>],
 'ElementDictionary': {'1stage_clear_icon': <ui.ImageBox object at 0x2E91FF90>,
                       '2stage_clear_icon': <ui.ImageBox object at 0x2E91FBD0>,
                       '3stage_clear_icon': <ui.ImageBox object at 0x2E91FB50>,
                       'alarm_text': <ui.TextLine object at 0x2E91FC30>,
                       'alarm_text_window': <ui.ScriptWindow object at 0x2E91F1B0>,
                       'exit_button': <ui.Button object at 0x2E776170>,
                       'floor_text': <ui.TextLine object at 0x2E91F990>,
                       'floor_text_window': <ui.ScriptWindow object at 0x2E91FC90>,
                       'information_bg': <ui.ImageBox object at 0x2E91F330>,
                       'time_gauge': <ui.ExpandedImageBox object at 0x2E776090>,
                       'time_text': <ui.TextLine object at 0x2E7760F0>,
                       'time_text_window': <ui.ScriptWindow object at 0x2E776110>},
 '_SungmaheeTowerInformationBoard__is_time_stopped': True,
 'hWnd': 764789336,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
