{'Children': [<ui.ImageBox object at 0x2C6E3970>,
              <ui.ScriptWindow object at 0x2C1B5170>,
              <ui.ImageBox object at 0x2C1B5290>,
              <ui.ImageBox object at 0x2C1B52B0>,
              <ui.ImageBox object at 0x2C1B5330>,
              <ui.ScriptWindow object at 0x2C1B5310>,
              <ui.ExpandedImageBox object at 0x2C1B53D0>,
              <ui.ScriptWindow object at 0x2C1B53B0>,
              <ui.Button object at 0x2C1B5470>],
 'ElementDictionary': {'1stage_clear_icon': <ui.ImageBox object at 0x2C1B5290>,
                       '2stage_clear_icon': <ui.ImageBox object at 0x2C1B52B0>,
                       '3stage_clear_icon': <ui.ImageBox object at 0x2C1B5330>,
                       'alarm_text': <ui.TextLine object at 0x2C1B5350>,
                       'alarm_text_window': <ui.ScriptWindow object at 0x2C1B5310>,
                       'exit_button': <ui.Button object at 0x2C1B5470>,
                       'floor_text': <ui.TextLine object at 0x2C1B5210>,
                       'floor_text_window': <ui.ScriptWindow object at 0x2C1B5170>,
                       'information_bg': <ui.ImageBox object at 0x2C6E3970>,
                       'time_gauge': <ui.ExpandedImageBox object at 0x2C1B53D0>,
                       'time_text': <ui.TextLine object at 0x2C1B53F0>,
                       'time_text_window': <ui.ScriptWindow object at 0x2C1B53B0>},
 '_SungmaheeTowerInformationBoard__is_time_stopped': True,
 'hWnd': 792747368,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
