{'Children': [<ui.Board object at 0x37C8BFD0>],
 'ElementDictionary': {'bgm_button': <ui.Button object at 0x37C8BE10>,
                       'bgm_file': <ui.TextLine object at 0x37C8BD70>,
                       'board': <ui.Board object at 0x37C8BFD0>,
                       'camera_long': <ui.RadioButton object at 0x37DFBA10>,
                       'camera_mode': <ui.TextLine object at 0x37C8BD30>,
                       'camera_short': <ui.RadioButton object at 0x37C8B6B0>,
                       'cur_language_text': <ui.TextLine object at 0x37D88F30>,
                       'cur_language_text_window': <ui.ScriptWindow object at 0x37D88F10>,
                       'dropItem_apply': <ui.Button object at 0x37D88CB0>,
                       'dropItem_level': <ui.TextLine object at 0x37D88A90>,
                       'dropItem_level1': <ui.RadioButton object at 0x37D88AB0>,
                       'dropItem_level2': <ui.RadioButton object at 0x37D88B10>,
                       'dropItem_level3': <ui.RadioButton object at 0x37D88B90>,
                       'dropItem_level4': <ui.RadioButton object at 0x37D88BF0>,
                       'dropItem_level5': <ui.RadioButton object at 0x37D88C50>,
                       'effect_apply': <ui.Button object at 0x37D88810>,
                       'effect_level': <ui.TextLine object at 0x37D88610>,
                       'effect_level1': <ui.RadioButton object at 0x37D88630>,
                       'effect_level2': <ui.RadioButton object at 0x37D88690>,
                       'effect_level3': <ui.RadioButton object at 0x37D886F0>,
                       'effect_level4': <ui.RadioButton object at 0x37D88750>,
                       'effect_level5': <ui.RadioButton object at 0x37D887B0>,
                       'fog_mode': <ui.TextLine object at 0x37DFB330>,
                       'fog_off': <ui.RadioButton object at 0x37C8D590>,
                       'fog_on': <ui.RadioButton object at 0x37C8DF70>,
                       'graphic_on_off_window': <ui.ScriptWindow object at 0x37D885F0>,
                       'language_change_button': <ui.Button object at 0x37D88F70>,
                       'language_change_window': <ui.ScriptWindow object at 0x37D88EB0>,
                       'language_select_button': <ui.Button object at 0x37D88F50>,
                       'language_select_img': <ui.ImageBox object at 0x37D88EF0>,
                       'language_select_pivot_window': <ui.ScriptWindow object at 0x37D88FB0>,
                       'language_select_text': <ui.TextLine object at 0x37D88ED0>,
                       'music_name': <ui.TextLine object at 0x37C8BD90>,
                       'music_volume_controller': <ui.SliderBar object at 0x37C8BCF0>,
                       'night_mode': <ui.TextLine object at 0x37C8D170>,
                       'night_mode_off': <ui.RadioButton object at 0x37C8DD50>,
                       'night_mode_on': <ui.RadioButton object at 0x37C8D490>,
                       'npcName_off': <ui.RadioButton object at 0x37D88E50>,
                       'npcName_on': <ui.RadioButton object at 0x37D88DF0>,
                       'npcName_status': <ui.TextLine object at 0x37D88DD0>,
                       'pet_off': <ui.RadioButton object at 0x37D88D70>,
                       'pet_on': <ui.RadioButton object at 0x37D88D10>,
                       'pet_status': <ui.TextLine object at 0x37D88CF0>,
                       'privateShop_apply': <ui.Button object at 0x37D88A50>,
                       'privateShop_level': <ui.TextLine object at 0x37D88850>,
                       'privateShop_level1': <ui.RadioButton object at 0x37D88870>,
                       'privateShop_level2': <ui.RadioButton object at 0x37D888D0>,
                       'privateShop_level3': <ui.RadioButton object at 0x37D88930>,
                       'privateShop_level4': <ui.RadioButton object at 0x37D88990>,
                       'privateShop_level5': <ui.RadioButton object at 0x37D889F0>,
                       'shadow_quality': <ui.TextLine object at 0x37D884B0>,
                       'shadow_quality_average': <ui.RadioButton object at 0x37D88530>,
                       'shadow_quality_bad': <ui.RadioButton object at 0x37D884D0>,
                       'shadow_quality_good': <ui.RadioButton object at 0x37D88590>,
                       'shadow_target': <ui.TextLine object at 0x37D882D0>,
                       'shadow_target_all': <ui.RadioButton object at 0x37D88450>,
                       'shadow_target_ground': <ui.RadioButton object at 0x37D88350>,
                       'shadow_target_ground_and_solo': <ui.RadioButton object at 0x37D883B0>,
                       'shadow_target_none': <ui.RadioButton object at 0x37D882F0>,
                       'snow_mode': <ui.TextLine object at 0x37D88B70>,
                       'snow_mode_off': <ui.RadioButton object at 0x37D881F0>,
                       'snow_mode_on': <ui.RadioButton object at 0x37D88170>,
                       'snow_texture_mode': <ui.TextLine object at 0x37D88230>,
                       'snow_texture_mode_off': <ui.RadioButton object at 0x37D88290>,
                       'snow_texture_mode_on': <ui.RadioButton object at 0x37D88250>,
                       'sound_name': <ui.TextLine object at 0x37C8B6D0>,
                       'sound_volume_controller': <ui.SliderBar object at 0x37C8BC70>,
                       'titlebar': <ui.TitleBar object at 0x37C8BD50>,
                       'titlename': <ui.TextLine object at 0x37C8BF10>},
 'IsShow': False,
 'NightModeOn': 0,
 'SnowModeOn': 0,
 'SnowTextureModeOn': 0,
 'cameraModeButtonList': [<ui.RadioButton object at 0x37C8B6B0>, <ui.RadioButton object at 0x37DFBA10>],
 'changeMusicButton': <ui.Button object at 0x37C8BE10>,
 'ctrlMusicVolume': <ui.SliderBar object at 0x37C8BCF0>,
 'ctrlShadowQuality': 0,
 'ctrlSoundVolume': <ui.SliderBar object at 0x37C8BC70>,
 'cur_code_page': '1250',
 'cur_key': '',
 'cur_language_text': <ui.TextLine object at 0x37D88F30>,
 'cur_locale': 'hu',
 'curtain': <uiPhaseCurtain.PhaseCurtain object at 0x37CAC470>,
 'dropItemApplyButton': <ui.Button object at 0x37D88CB0>,
 'dropItemLevelIndex': 0,
 'dropItemOnOffButtonList': [<ui.RadioButton object at 0x37D88AB0>, <ui.RadioButton object at 0x37D88B10>, <ui.RadioButton object at 0x37D88B90>, <ui.RadioButton object at 0x37D88BF0>, <ui.RadioButton object at 0x37D88C50>],
 'effectApplyButton': <ui.Button object at 0x37D88810>,
 'effectLevelIndex': 0,
 'effectOnOffButtonList': [<ui.RadioButton object at 0x37D88630>, <ui.RadioButton object at 0x37D88690>, <ui.RadioButton object at 0x37D886F0>, <ui.RadioButton object at 0x37D88750>, <ui.RadioButton object at 0x37D887B0>],
 'fogButtonList': [<ui.RadioButton object at 0x37C8D590>, <ui.RadioButton object at 0x37C8DF70>],
 'fogModeButtonList': [],
 'hWnd': 947889928,
 'language_button_list': [<ui.Button object at 0x37C8BF30>, <ui.Button object at 0x37CAC250>, <ui.Button object at 0x37CAC290>, <ui.Button object at 0x37CAC2D0>, <ui.Button object at 0x37CAC310>],
 'language_change_button': <ui.Button object at 0x37D88F70>,
 'language_change_window': <ui.ScriptWindow object at 0x37D88EB0>,
 'language_change_window_open': False,
 'language_mouse_over_img': <ui.ImageBox object at 0x37CAC350>,
 'language_select_button': <ui.Button object at 0x37D88F50>,
 'language_select_pivot_window': <ui.ScriptWindow object at 0x37D88FB0>,
 'language_select_scroll': <ui.ScrollBar object at 0x37CAC370>,
 'language_select_scroll_diff': 11,
 'language_select_scroll_pos': 0,
 'language_select_window': <ui.Window object at 0x37D88130>,
 'locale_list': [('LANGUAGE_EN', '1252', 'en'),
                 ('LANGUAGE_AE', '1256', 'ae'),
                 ('LANGUAGE_CZ', '1250', 'cz'),
                 ('LANGUAGE_DK', '1252', 'dk'),
                 ('LANGUAGE_FR', '1252', 'fr'),
                 ('LANGUAGE_GR', '1253', 'gr'),
                 ('LANGUAGE_NL', '1252', 'nl'),
                 ('LANGUAGE_PL', '1250', 'pl'),
                 ('LANGUAGE_HU', '1250', 'hu'),
                 ('LANGUAGE_DE', '1252', 'de'),
                 ('LANGUAGE_IT', '1252', 'it'),
                 ('LANGUAGE_RU', '1251', 'ru'),
                 ('LANGUAGE_PT', '1252', 'pt'),
                 ('LANGUAGE_RO', '1250', 'ro'),
                 ('LANGUAGE_ES', '1252', 'es'),
                 ('LANGUAGE_TR', '1254', 'tr')],
 'musicListDlg': 0,
 'nightModeButtonList': [<ui.RadioButton object at 0x37C8DD50>, <ui.RadioButton object at 0x37C8D490>],
 'npcNameOnOffButtonList': [<ui.RadioButton object at 0x37D88DF0>, <ui.RadioButton object at 0x37D88E50>],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'petOnOffButtonList': [<ui.RadioButton object at 0x37D88D10>, <ui.RadioButton object at 0x37D88D70>],
 'privateShopApplyButton': <ui.Button object at 0x37D88A50>,
 'privateShopLevelIndex': 0,
 'privateShopOnOffButtonList': [<ui.RadioButton object at 0x37D88870>, <ui.RadioButton object at 0x37D888D0>, <ui.RadioButton object at 0x37D88930>, <ui.RadioButton object at 0x37D88990>, <ui.RadioButton object at 0x37D889F0>],
 'selectMusicFile': <ui.TextLine object at 0x37C8BD70>,
 'shadowQualityButtonList': [<ui.RadioButton object at 0x37D884D0>, <ui.RadioButton object at 0x37D88530>, <ui.RadioButton object at 0x37D88590>],
 'shadowTargetButtonList': [<ui.RadioButton object at 0x37D882F0>, <ui.RadioButton object at 0x37D88350>, <ui.RadioButton object at 0x37D883B0>, <ui.RadioButton object at 0x37D88450>],
 'snowModeButtonList': [<ui.RadioButton object at 0x37D881F0>, <ui.RadioButton object at 0x37D88170>],
 'snowTextureModeButtonList': [<ui.RadioButton object at 0x37D88290>, <ui.RadioButton object at 0x37D88250>],
 'titleBar': <ui.TitleBar object at 0x37C8BD50>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
