{'Children': [<ui.Board object at 0x2F029BF0>],
 'ElementDictionary': {'bgm_button': <ui.Button object at 0x2F0A0590>,
                       'bgm_file': <ui.TextLine object at 0x2F0A05D0>,
                       'board': <ui.Board object at 0x2F029BF0>,
                       'camera_long': <ui.RadioButton object at 0x2F0A06D0>,
                       'camera_mode': <ui.TextLine object at 0x2F0A0670>,
                       'camera_short': <ui.RadioButton object at 0x2F0A0690>,
                       'cur_language_text': <ui.TextLine object at 0x2EFC11B0>,
                       'cur_language_text_window': <ui.ScriptWindow object at 0x2EFC1190>,
                       'dropItem_apply': <ui.Button object at 0x2F0A0390>,
                       'dropItem_level': <ui.TextLine object at 0x2F0A0190>,
                       'dropItem_level1': <ui.RadioButton object at 0x2F0A01B0>,
                       'dropItem_level2': <ui.RadioButton object at 0x2F0A0210>,
                       'dropItem_level3': <ui.RadioButton object at 0x2F0A0270>,
                       'dropItem_level4': <ui.RadioButton object at 0x2F0A02D0>,
                       'dropItem_level5': <ui.RadioButton object at 0x2F0A0330>,
                       'effect_apply': <ui.Button object at 0x2F0A0EF0>,
                       'effect_level': <ui.TextLine object at 0x2F0A0CD0>,
                       'effect_level1': <ui.RadioButton object at 0x2F0A0CF0>,
                       'effect_level2': <ui.RadioButton object at 0x2F0A0D50>,
                       'effect_level3': <ui.RadioButton object at 0x2F0A0DB0>,
                       'effect_level4': <ui.RadioButton object at 0x2F0A0E10>,
                       'effect_level5': <ui.RadioButton object at 0x2F0A0E70>,
                       'fog_mode': <ui.TextLine object at 0x2F0A0710>,
                       'fog_off': <ui.RadioButton object at 0x2F0A07B0>,
                       'fog_on': <ui.RadioButton object at 0x2F0A0750>,
                       'graphic_on_off_window': <ui.ScriptWindow object at 0x2F0A0CB0>,
                       'language_change_button': <ui.Button object at 0x2EFC11F0>,
                       'language_change_window': <ui.ScriptWindow object at 0x2EFC1130>,
                       'language_select_button': <ui.Button object at 0x2EFC11D0>,
                       'language_select_img': <ui.ImageBox object at 0x2EFC1170>,
                       'language_select_pivot_window': <ui.ScriptWindow object at 0x2EFC1230>,
                       'language_select_text': <ui.TextLine object at 0x2EFC1150>,
                       'music_name': <ui.TextLine object at 0x2F0A04D0>,
                       'music_volume_controller': <ui.SliderBar object at 0x2F0A04F0>,
                       'night_mode': <ui.TextLine object at 0x2F0A07F0>,
                       'night_mode_off': <ui.RadioButton object at 0x2F0A0850>,
                       'night_mode_on': <ui.RadioButton object at 0x2F0A0810>,
                       'npcName_off': <ui.RadioButton object at 0x2EFC10D0>,
                       'npcName_on': <ui.RadioButton object at 0x2EFC1070>,
                       'npcName_status': <ui.TextLine object at 0x2EFC1050>,
                       'pet_off': <ui.RadioButton object at 0x2F0A0450>,
                       'pet_on': <ui.RadioButton object at 0x2F0A03F0>,
                       'pet_status': <ui.TextLine object at 0x2F0A03D0>,
                       'privateShop_apply': <ui.Button object at 0x2F0A0150>,
                       'privateShop_level': <ui.TextLine object at 0x2F0A0F30>,
                       'privateShop_level1': <ui.RadioButton object at 0x2F0A0F50>,
                       'privateShop_level2': <ui.RadioButton object at 0x2F0A0FB0>,
                       'privateShop_level3': <ui.RadioButton object at 0x2F0A0030>,
                       'privateShop_level4': <ui.RadioButton object at 0x2F0A0090>,
                       'privateShop_level5': <ui.RadioButton object at 0x2F0A00F0>,
                       'shadow_quality': <ui.TextLine object at 0x2F0A0B70>,
                       'shadow_quality_average': <ui.RadioButton object at 0x2F0A0BF0>,
                       'shadow_quality_bad': <ui.RadioButton object at 0x2F0A0B90>,
                       'shadow_quality_good': <ui.RadioButton object at 0x2F0A0C50>,
                       'shadow_target': <ui.TextLine object at 0x2F0A09D0>,
                       'shadow_target_all': <ui.RadioButton object at 0x2F0A0B10>,
                       'shadow_target_ground': <ui.RadioButton object at 0x2F0A0A50>,
                       'shadow_target_ground_and_solo': <ui.RadioButton object at 0x2F0A0AB0>,
                       'shadow_target_none': <ui.RadioButton object at 0x2F0A09F0>,
                       'snow_mode': <ui.TextLine object at 0x2F0A0890>,
                       'snow_mode_off': <ui.RadioButton object at 0x2F0A08F0>,
                       'snow_mode_on': <ui.RadioButton object at 0x2F0A08B0>,
                       'snow_texture_mode': <ui.TextLine object at 0x2F0A0930>,
                       'snow_texture_mode_off': <ui.RadioButton object at 0x2F0A0990>,
                       'snow_texture_mode_on': <ui.RadioButton object at 0x2F0A0950>,
                       'sound_name': <ui.TextLine object at 0x2F0A05F0>,
                       'sound_volume_controller': <ui.SliderBar object at 0x2F0A0610>,
                       'titlebar': <ui.TitleBar object at 0x2EFACFF0>,
                       'titlename': <ui.TextLine object at 0x2F0A0ED0>},
 'IsShow': False,
 'NightModeOn': 0,
 'SnowModeOn': 0,
 'SnowTextureModeOn': 0,
 'cameraModeButtonList': [<ui.RadioButton object at 0x2F0A0690>, <ui.RadioButton object at 0x2F0A06D0>],
 'changeMusicButton': <ui.Button object at 0x2F0A0590>,
 'ctrlMusicVolume': <ui.SliderBar object at 0x2F0A04F0>,
 'ctrlShadowQuality': 0,
 'ctrlSoundVolume': <ui.SliderBar object at 0x2F0A0610>,
 'cur_code_page': 1252,
 'cur_key': '',
 'cur_language_text': <ui.TextLine object at 0x2EFC11B0>,
 'cur_locale': 'br',
 'curtain': <uiPhaseCurtain.PhaseCurtain object at 0x2EF46150>,
 'dropItemApplyButton': <ui.Button object at 0x2F0A0390>,
 'dropItemLevelIndex': 0,
 'dropItemOnOffButtonList': [<ui.RadioButton object at 0x2F0A01B0>, <ui.RadioButton object at 0x2F0A0210>, <ui.RadioButton object at 0x2F0A0270>, <ui.RadioButton object at 0x2F0A02D0>, <ui.RadioButton object at 0x2F0A0330>],
 'effectApplyButton': <ui.Button object at 0x2F0A0EF0>,
 'effectLevelIndex': 0,
 'effectOnOffButtonList': [<ui.RadioButton object at 0x2F0A0CF0>, <ui.RadioButton object at 0x2F0A0D50>, <ui.RadioButton object at 0x2F0A0DB0>, <ui.RadioButton object at 0x2F0A0E10>, <ui.RadioButton object at 0x2F0A0E70>],
 'fogButtonList': [<ui.RadioButton object at 0x2F0A07B0>, <ui.RadioButton object at 0x2F0A0750>],
 'fogModeButtonList': [],
 'hWnd': 713128304,
 'language_button_list': [],
 'language_change_button': <ui.Button object at 0x2EFC11F0>,
 'language_change_window': <ui.ScriptWindow object at 0x2EFC1130>,
 'language_change_window_open': False,
 'language_mouse_over_img': None,
 'language_select_button': <ui.Button object at 0x2EFC11D0>,
 'language_select_pivot_window': <ui.ScriptWindow object at 0x2EFC1230>,
 'language_select_scroll': None,
 'language_select_scroll_diff': 0.0,
 'language_select_scroll_pos': 0,
 'language_select_window': None,
 'locale_list': [],
 'musicListDlg': 0,
 'nightModeButtonList': [<ui.RadioButton object at 0x2F0A0850>, <ui.RadioButton object at 0x2F0A0810>],
 'npcNameOnOffButtonList': [<ui.RadioButton object at 0x2EFC1070>, <ui.RadioButton object at 0x2EFC10D0>],
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'petOnOffButtonList': [<ui.RadioButton object at 0x2F0A03F0>, <ui.RadioButton object at 0x2F0A0450>],
 'privateShopApplyButton': <ui.Button object at 0x2F0A0150>,
 'privateShopLevelIndex': 0,
 'privateShopOnOffButtonList': [<ui.RadioButton object at 0x2F0A0F50>, <ui.RadioButton object at 0x2F0A0FB0>, <ui.RadioButton object at 0x2F0A0030>, <ui.RadioButton object at 0x2F0A0090>, <ui.RadioButton object at 0x2F0A00F0>],
 'selectMusicFile': <ui.TextLine object at 0x2F0A05D0>,
 'shadowQualityButtonList': [<ui.RadioButton object at 0x2F0A0B90>, <ui.RadioButton object at 0x2F0A0BF0>, <ui.RadioButton object at 0x2F0A0C50>],
 'shadowTargetButtonList': [<ui.RadioButton object at 0x2F0A09F0>, <ui.RadioButton object at 0x2F0A0A50>, <ui.RadioButton object at 0x2F0A0AB0>, <ui.RadioButton object at 0x2F0A0B10>],
 'snowModeButtonList': [<ui.RadioButton object at 0x2F0A08F0>, <ui.RadioButton object at 0x2F0A08B0>],
 'snowTextureModeButtonList': [<ui.RadioButton object at 0x2F0A0990>, <ui.RadioButton object at 0x2F0A0950>],
 'titleBar': <ui.TitleBar object at 0x2EFACFF0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
