{'Children': [],
 'ElementDictionary': {},
 'hWnd': 764801400,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'tooltipEnergy': <uiTaskBar.TextToolTip object at 0x2E80A9D0>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
