{'Base': <ui.Bar object at 0x2E4EAD30>,
 'Corners': [<ui.ExpandedImageBox object at 0x2E4EA350>, <ui.ExpandedImageBox object at 0x2E4EAB30>, <ui.ExpandedImageBox object at 0x2E4EAF50>, <ui.ExpandedImageBox object at 0x2E4EAFB0>],
 'Lines': [<ui.ExpandedImageBox object at 0x2E4EAE10>, <ui.ExpandedImageBox object at 0x2E4EAE90>, <ui.ExpandedImageBox object at 0x2E4EAC70>, <ui.ExpandedImageBox object at 0x2E4EA930>],
 'hWnd': 909060824,
 'hp': 0,
 'hpGauge': <ui.Gauge object at 0x2E4EAB90>,
 'hpMax': 0,
 'hpPer': 0,
 'name': <ui.TextLine object at 0x2E4EA8D0>,
 'nameLength': 0,
 'nameString': '',
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'tooltipHP': <uiTarget.TextToolTip object at 0x2E4F6050>,
 'vid': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
