{'Base': <ui.Bar object at 0x2D6A2470>,
 'Corners': [<ui.ExpandedImageBox object at 0x2D6A24B0>, <ui.ExpandedImageBox object at 0x2D6A2F70>, <ui.ExpandedImageBox object at 0x2D6A2A50>, <ui.ExpandedImageBox object at 0x2D6A21F0>],
 'Lines': [<ui.ExpandedImageBox object at 0x2D6A2B70>, <ui.ExpandedImageBox object at 0x2D6A2430>, <ui.ExpandedImageBox object at 0x2D6A2EF0>, <ui.ExpandedImageBox object at 0x2D6A2DB0>],
 'hWnd': 841375392,
 'hp': 0,
 'hpGauge': <ui.Gauge object at 0x2D6A28D0>,
 'hpMax': 0,
 'hpPer': 0,
 'name': <ui.TextLine object at 0x2D6A2890>,
 'nameLength': 0,
 'nameString': '',
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'tooltipHP': <uiTarget.TextToolTip object at 0x2D6A2E30>,
 'vid': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
