{'Base': <ui.Bar object at 0x2C83F4F0>,
 'Corners': [<ui.ExpandedImageBox object at 0x2C802990>, <ui.ExpandedImageBox object at 0x2C802F30>, <ui.ExpandedImageBox object at 0x2C83F250>, <ui.ExpandedImageBox object at 0x2C83FF10>],
 'Lines': [<ui.ExpandedImageBox object at 0x2C83FFB0>, <ui.ExpandedImageBox object at 0x2C83F4B0>, <ui.ExpandedImageBox object at 0x2C83FD50>, <ui.ExpandedImageBox object at 0x2C83F150>],
 'childrenList': [],
 'defFontName': 'Tahoma:12',
 'followFlag': True,
 'hWnd': 717485832,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'toolTipHeight': 12,
 'toolTipWidth': 190,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'xPos': -1,
 'yPos': -1}
