{'Base': <ui.Bar object at 0x2D6A2D30>,
 'Corners': [<ui.ExpandedImageBox object at 0x2D6BA0D0>, <ui.ExpandedImageBox object at 0x2D6BAA70>, <ui.ExpandedImageBox object at 0x2D6A2E70>, <ui.ExpandedImageBox object at 0x2D6A2B90>],
 'Lines': [<ui.ExpandedImageBox object at 0x2D6A2930>, <ui.ExpandedImageBox object at 0x2D6A25D0>, <ui.ExpandedImageBox object at 0x2D6A29F0>, <ui.ExpandedImageBox object at 0x2D6A2C70>],
 'childrenList': [],
 'defFontName': 'Tahoma:12',
 'followFlag': True,
 'hWnd': 841384896,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'toolTipHeight': 12,
 'toolTipWidth': 190,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'xPos': -1,
 'yPos': -1}
