{'Children': [<ui.BoardWithTitleBar object at 0x2D8697D0>],
 'ElementDictionary': {'board': <ui.BoardWithTitleBar object at 0x2D8697D0>,
                       'chocolate_cur_count_bg': <ui.ImageBox object at 0x2D8C3190>,
                       'chocolate_cur_count_menu_bg': <ui.ImageBox object at 0x2D8C3650>,
                       'chocolate_cur_count_menu_text': <ui.TextLine object at 0x2D8C3490>,
                       'chocolate_cur_count_text': <ui.TextLine object at 0x2D8C30F0>,
                       'chocolate_max_count_bg': <ui.ImageBox object at 0x2D8C3DF0>,
                       'chocolate_max_count_bg_text': <ui.TextLine object at 0x2D8C3570>,
                       'chocolate_max_count_text': <ui.TextLine object at 0x2D8C37D0>,
                       'chocolate_slot': <ui.SlotWindow object at 0x2D8C3450>,
                       'chocolate_slot_bg': <ui.ImageBox object at 0x2D8C3DB0>,
                       'chocolate_use_button': <ui.Button object at 0x2D8C3470>,
                       'chocolate_wrap_button': <ui.Button object at 0x2D8C3810>,
                       'desc_window': <ui.ScriptWindow object at 0x2D8C3D90>,
                       'main_bg_window': <ui.ScriptWindow object at 0x2D8C32D0>,
                       'main_boundary_bottom_line': <ui.ImageBox object at 0x2D8C3DD0>,
                       'main_boundary_top_line': <ui.ImageBox object at 0x2D8C3510>,
                       'main_center_line': <ui.ExpandedImageBox object at 0x2D8C34F0>,
                       'main_outline': <ui.OutlineWindow object at 0x2D83FF30>,
                       'rose_cur_count_bg': <ui.ImageBox object at 0x2D8C3730>,
                       'rose_cur_count_menu_bg': <ui.ImageBox object at 0x2D8C3D10>,
                       'rose_cur_count_menu_text': <ui.TextLine object at 0x2D8C3110>,
                       'rose_cur_count_text': <ui.TextLine object at 0x2D8C35F0>,
                       'rose_max_count_bg': <ui.ImageBox object at 0x2D8C3410>,
                       'rose_max_count_bg_text': <ui.TextLine object at 0x2D8C3530>,
                       'rose_max_count_text': <ui.TextLine object at 0x2D8C36D0>,
                       'rose_slot': <ui.SlotWindow object at 0x2D8C3130>,
                       'rose_slot_bg': <ui.ImageBox object at 0x2D8C3430>,
                       'rose_use_button': <ui.Button object at 0x2D8C3230>,
                       'rose_wrap_button': <ui.Button object at 0x2D8C3D70>,
                       'status_window': <ui.ScriptWindow object at 0x2D8C3A50>},
 'hWnd': 751254336,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'window_horizontal_align': 0,
 'window_vertical_align': 0}
