{'Children': [],
 'ElementDictionary': {},
 'bannerList': [],
 'banner_data': [(2, 'K\xf6sd \xf6ssze Metin2 fi\xf3kod a Steam-mel most!', '', '', '', 'https://hu.metin2.gameforge.com/steam/moveingame', False)],
 'banner_horizontal': 2,
 'banner_vertical': 3,
 'bannertype': [],
 'hWnd': 715899712,
 'isLoaded': 1,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'startX': 801,
 'startY': 430,
 'toolTip': <uiToolTip.ToolTip object at 0x30AB3490>,
 'window_horizontal': 2,
 'window_horizontal_align': 0,
 'window_vertical': 3,
 'window_vertical_align': 0}
