{'Children': [<ui.BoardWithTitleBar object at 0x310D1D90>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x310D1F30>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x310D1430>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x310D1A10>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x310D1950>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x310D1A50>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x310D1C30>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x310D1A70>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x310D13F0>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x310D1C70>,
                       'board': <ui.BoardWithTitleBar object at 0x310D1D90>,
                       'break_time_label_text': <ui.TextLine object at 0x310D1B70>,
                       'break_time_label_text_window': <ui.ScriptWindow object at 0x310D1C10>,
                       'break_time_text': <ui.TextLine object at 0x310D1BD0>,
                       'break_time_text_bg': <ui.ImageBox object at 0x310D1370>,
                       'current_state_text': <ui.TextLine object at 0x310D1FB0>,
                       'desc_board': <ui.Bar object at 0x310D1FF0>,
                       'desc_window': <ui.ScriptWindow object at 0x310D1C90>,
                       'dividing_line_image': <ui.ImageBox object at 0x310D16B0>,
                       'min_damage_label_text': <ui.TextLine object at 0x310D1CF0>,
                       'min_damage_label_text_window': <ui.ScriptWindow object at 0x310D1AB0>,
                       'min_damage_text': <ui.TextLine object at 0x310D1CB0>,
                       'min_damage_text_bg': <ui.ImageBox object at 0x310D1F10>,
                       'next_button': <ui.Button object at 0x310D1AD0>,
                       'prev_button': <ui.Button object at 0x310D1BF0>,
                       'ranking_button': <ui.Button object at 0x310D1330>,
                       'reward_button': <ui.Button object at 0x310D1CD0>,
                       'run_time_label_text': <ui.TextLine object at 0x310D1B10>,
                       'run_time_label_text_window': <ui.ScriptWindow object at 0x310D1B90>,
                       'run_time_text': <ui.TextLine object at 0x310D1F70>,
                       'run_time_text_bg': <ui.ImageBox object at 0x310D1B50>,
                       'total_damage_label_text': <ui.TextLine object at 0x310D1D10>,
                       'total_damage_label_text_window': <ui.ScriptWindow object at 0x310D1E10>,
                       'total_damage_text': <ui.TextLine object at 0x310D1A30>,
                       'total_damage_text_bg': <ui.ImageBox object at 0x310D1E90>},
 'break_time_end_time': None,
 'break_time_text': <ui.TextLine object at 0x310D1BD0>,
 'button_next': <ui.Button object at 0x310D1AD0>,
 'button_prev': <ui.Button object at 0x310D1BF0>,
 'current_state_text': <ui.TextLine object at 0x310D1FB0>,
 'desc_board': <ui.Bar object at 0x310D1FF0>,
 'desc_index': -1,
 'desc_line_count': 11,
 'desc_y': 7,
 'descriptionBox': None,
 'description_box': <uiWorldBoss.DescriptionBox object at 0x310D1B30>,
 'hWnd': 939373056,
 'min_damage_text': <ui.TextLine object at 0x310D1CB0>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'questionDialog': None,
 'ranking_board': None,
 'ranking_button': <ui.Button object at 0x310D1330>,
 'reward_button': <ui.Button object at 0x310D1CD0>,
 'run_time_end_time': None,
 'run_time_text': <ui.TextLine object at 0x310D1F70>,
 'total_damage_text': <ui.TextLine object at 0x310D1A30>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'world_boss_state': None}
