{'Children': [<ui.BoardWithTitleBar object at 0x2D665030>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2D665350>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2D665370>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2D6652B0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2D665310>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2D665270>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2D665330>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2D665290>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2D6652F0>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2D6652D0>,
                       'board': <ui.BoardWithTitleBar object at 0x2D665030>,
                       'break_time_label_text': <ui.TextLine object at 0x2D6654D0>,
                       'break_time_label_text_window': <ui.ScriptWindow object at 0x2D6654B0>,
                       'break_time_text': <ui.TextLine object at 0x2D665510>,
                       'break_time_text_bg': <ui.ImageBox object at 0x2D6654F0>,
                       'current_state_text': <ui.TextLine object at 0x2D6653B0>,
                       'desc_board': <ui.Bar object at 0x2D665390>,
                       'desc_window': <ui.ScriptWindow object at 0x2D665250>,
                       'dividing_line_image': <ui.ImageBox object at 0x2D665410>,
                       'min_damage_label_text': <ui.TextLine object at 0x2D6655D0>,
                       'min_damage_label_text_window': <ui.ScriptWindow object at 0x2D6655B0>,
                       'min_damage_text': <ui.TextLine object at 0x2D665610>,
                       'min_damage_text_bg': <ui.ImageBox object at 0x2D6655F0>,
                       'next_button': <ui.Button object at 0x2D6653F0>,
                       'prev_button': <ui.Button object at 0x2D6653D0>,
                       'ranking_button': <ui.Button object at 0x2D665630>,
                       'reward_button': <ui.Button object at 0x2D665670>,
                       'run_time_label_text': <ui.TextLine object at 0x2D665450>,
                       'run_time_label_text_window': <ui.ScriptWindow object at 0x2D665430>,
                       'run_time_text': <ui.TextLine object at 0x2D665490>,
                       'run_time_text_bg': <ui.ImageBox object at 0x2D665470>,
                       'total_damage_label_text': <ui.TextLine object at 0x2D665550>,
                       'total_damage_label_text_window': <ui.ScriptWindow object at 0x2D665530>,
                       'total_damage_text': <ui.TextLine object at 0x2D665590>,
                       'total_damage_text_bg': <ui.ImageBox object at 0x2D665570>},
 'break_time_end_time': None,
 'break_time_text': <ui.TextLine object at 0x2D665510>,
 'button_next': <ui.Button object at 0x2D6653F0>,
 'button_prev': <ui.Button object at 0x2D6653D0>,
 'current_state_text': <ui.TextLine object at 0x2D6653B0>,
 'desc_board': <ui.Bar object at 0x2D665390>,
 'desc_index': -1,
 'desc_line_count': 11,
 'desc_y': 7,
 'descriptionBox': None,
 'description_box': <uiWorldBoss.DescriptionBox object at 0x2D6A2B90>,
 'hWnd': 841400032,
 'min_damage_text': <ui.TextLine object at 0x2D665610>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'questionDialog': None,
 'ranking_board': None,
 'ranking_button': <ui.Button object at 0x2D665630>,
 'reward_button': <ui.Button object at 0x2D665670>,
 'run_time_end_time': None,
 'run_time_text': <ui.TextLine object at 0x2D665490>,
 'total_damage_text': <ui.TextLine object at 0x2D665590>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'world_boss_state': None}
