{'Children': [<ui.BoardWithTitleBar object at 0x2E4EA8B0>],
 'ElementDictionary': {'DescWindowBottomCenterImg': <ui.ExpandedImageBox object at 0x2E63F1B0>,
                       'DescWindowCenterImg': <ui.ExpandedImageBox object at 0x2E63F1D0>,
                       'DescWindowLeftBottom': <ui.ImageBox object at 0x2E4EAED0>,
                       'DescWindowLeftCenterImg': <ui.ExpandedImageBox object at 0x2E63F130>,
                       'DescWindowLeftTop': <ui.ImageBox object at 0x2E4EAEF0>,
                       'DescWindowRightCenterImg': <ui.ExpandedImageBox object at 0x2E63F190>,
                       'DescWindowRightTop': <ui.ImageBox object at 0x2E4EA250>,
                       'DescWindowTopCenterImg': <ui.ExpandedImageBox object at 0x2E63F110>,
                       'ListWindowRightBottom': <ui.ImageBox object at 0x2E4EAA70>,
                       'board': <ui.BoardWithTitleBar object at 0x2E4EA8B0>,
                       'break_time_label_text': <ui.TextLine object at 0x2E63F330>,
                       'break_time_label_text_window': <ui.ScriptWindow object at 0x2E63F310>,
                       'break_time_text': <ui.TextLine object at 0x2E63F390>,
                       'break_time_text_bg': <ui.ImageBox object at 0x2E63F350>,
                       'current_state_text': <ui.TextLine object at 0x2E63F210>,
                       'desc_board': <ui.Bar object at 0x2E63F1F0>,
                       'desc_window': <ui.ScriptWindow object at 0x2E4EACF0>,
                       'dividing_line_image': <ui.ImageBox object at 0x2E63F270>,
                       'min_damage_label_text': <ui.TextLine object at 0x2E63F450>,
                       'min_damage_label_text_window': <ui.ScriptWindow object at 0x2E63F430>,
                       'min_damage_text': <ui.TextLine object at 0x2E63F490>,
                       'min_damage_text_bg': <ui.ImageBox object at 0x2E63F470>,
                       'next_button': <ui.Button object at 0x2E63F250>,
                       'prev_button': <ui.Button object at 0x2E63F230>,
                       'ranking_button': <ui.Button object at 0x2E63F4B0>,
                       'reward_button': <ui.Button object at 0x2E63F4F0>,
                       'run_time_label_text': <ui.TextLine object at 0x2E63F2B0>,
                       'run_time_label_text_window': <ui.ScriptWindow object at 0x2E63F290>,
                       'run_time_text': <ui.TextLine object at 0x2E63F2F0>,
                       'run_time_text_bg': <ui.ImageBox object at 0x2E63F2D0>,
                       'total_damage_label_text': <ui.TextLine object at 0x2E63F3D0>,
                       'total_damage_label_text_window': <ui.ScriptWindow object at 0x2E63F3B0>,
                       'total_damage_text': <ui.TextLine object at 0x2E63F410>,
                       'total_damage_text_bg': <ui.ImageBox object at 0x2E63F3F0>},
 'break_time_end_time': None,
 'break_time_text': <ui.TextLine object at 0x2E63F390>,
 'button_next': <ui.Button object at 0x2E63F250>,
 'button_prev': <ui.Button object at 0x2E63F230>,
 'current_state_text': <ui.TextLine object at 0x2E63F210>,
 'desc_board': <ui.Bar object at 0x2E63F1F0>,
 'desc_index': -1,
 'desc_line_count': 11,
 'desc_y': 7,
 'descriptionBox': None,
 'description_box': <uiWorldBoss.DescriptionBox object at 0x2E4E28D0>,
 'hWnd': 909085112,
 'min_damage_text': <ui.TextLine object at 0x2E63F490>,
 'onMouseLeftButtonUpEvent': None,
 'onMouseLeftButtonUpEventArgs': None,
 'overArgs': None,
 'overFunc': None,
 'overOutArgs': None,
 'overOutFunc': None,
 'parentWindow': 0,
 'questionDialog': None,
 'ranking_board': None,
 'ranking_button': <ui.Button object at 0x2E63F4B0>,
 'reward_button': <ui.Button object at 0x2E63F4F0>,
 'run_time_end_time': None,
 'run_time_text': <ui.TextLine object at 0x2E63F2F0>,
 'total_damage_text': <ui.TextLine object at 0x2E63F410>,
 'window_horizontal_align': 0,
 'window_vertical_align': 0,
 'world_boss_state': None}
