{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'LogBox'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RegisterExceptionString'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Trace'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'TraceError'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Tracen'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'dbg'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
