{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'AddEventSetLocalYPosition'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'AllProcesseEventSet'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ClearEventSet'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Destroy'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'EndEventProcess'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetEventSetLocalYPosition'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetLineCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetLineHeight'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetProcessedLineCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetTotalLineCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetVisibleStartLine'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'InsertTextInline'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsWait'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'QuestButtonClick'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RegisterEventSet'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderEventSet'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SelectAnswer'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetEventHandler'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetEventSetWidth'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetFontColor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetInterfaceWindow'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetLeftTimeString'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetRestrictedCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetVisibleLineCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetVisibleStartLine'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetYPosition'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Skip'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'UpdateEventSet'}],
 'import': [],
 'var': [{'name': 'BOX_VISIBLE_LINE_COUNT', 'type': 'int', 'value': 15},
         {'name': 'BUTTON_TYPE_CANCEL', 'type': 'int', 'value': 2},
         {'name': 'BUTTON_TYPE_DONE', 'type': 'int', 'value': 1},
         {'name': 'BUTTON_TYPE_NEXT', 'type': 'int', 'value': 0},
         {'name': 'DEFAULT_LINE_HEIGHT', 'type': 'int', 'value': 16},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'event'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
