{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetAcceptFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetAcceptFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetChangeLookVnumFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetChangeLookVnumFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetChequeFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetChequeFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetElkFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetElkFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemAttributeFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemAttributeFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemCountFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemCountFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemMetinSocketFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemMetinSocketFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemVnumFromSelf'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemVnumFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetLevelFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetNameFromTarget'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'InitTrading'}],
 'import': [],
 'var': [{'name': 'EXCHANGE_ITEM_MAX_NUM', 'type': 'int', 'value': 12}, {'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'exchange'}, {'name': '__package__', 'type': 'NoneType', 'value': None}]}
