{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ClearDepthBuffer'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ClearTextBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'CreateBigTextBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'CreateTextBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'DestroyTextBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GenerateColor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetDropItemOnOffLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetEffectOnOffLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetNPCNameOnOffStatus'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetPetOnOffStatus'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetPrivateShopOnOffLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'InitScreenEffect'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PopState'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PushState'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderBox'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderGradationBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderLine'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderRoundBox'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderTextBar'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RestoreViewport'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SaveScreenShot'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SaveScreenShotToPath'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetColor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetCursorPosition'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetDropItemOnOffLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetEffectOnOffLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetGameRenderState'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetInterfaceRenderState'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetNPCNameOnOffStatus'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetOmniLight'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetPerspective'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetPetOnOffStatus'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetPrivateShopOnOffLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetTextBarClipRect'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetViewport'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'TextBarGetTextExtent'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'TextBarSetTextColor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'TextBarTextOut'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'grp'}, {'name': '__package__', 'type': 'NoneType', 'value': None}]}
