{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Delete'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Generate'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GenerateFromHandle'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetGraphicImagePointer'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetHeight'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetWidth'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Render'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetDiffuseColor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetPosition'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'grpImage'}, {'name': '__package__', 'type': 'NoneType', 'value': None}]}
