{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSplitingTextLine'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSplitingTextLineCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetFontColor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetFontName'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetOutline'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'PDnfKAG'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
