{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetCurrentSafeboxSize'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetGuildBankInfoData'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetGuildBankInfoSize'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemAttribute'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemChangeLookVnum'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemFlags'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemID'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemMetinSocket'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemRefineElement'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetItemSetValue'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'OpenGuildBank'}],
 'import': [],
 'var': [{'name': 'GUILDBANK_PAGE_SIZE', 'type': 'int', 'value': 40},
         {'name': 'GUILDBANK_SLOT_X_COUNT', 'type': 'int', 'value': 5},
         {'name': 'GUILDBANK_SLOT_Y_COUNT', 'type': 'int', 'value': 8},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'guildbank'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
