{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'AddExceptKey'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ClearExceptKey'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Delete'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'DisableCaptureInput'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'DisableIME'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'EnableCaptureInput'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'EnableIME'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'EnablePaste'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetCandidate'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetCandidateCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetCandidateSelection'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetCodePage'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetReading'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetReadingError'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetText'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'MoveEnd'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'MoveHome'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'MoveLeft'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'MoveRight'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PasteBackspace'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PasteReturn'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PasteString'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PasteTextFromClipBoard'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetCheckWidth'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetCursorPosition'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetMax'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetMovableEditLineMode'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetNumberMode'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetStringMode'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetText'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetUserMax'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'PYL'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
