{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Destroy'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsBlockFriendByName'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsFriendByName'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RefreshGuildMember'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RemoveBlockFriend'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RemoveFriend'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetMessengerHandler'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'messenger'}, {'name': '__package__', 'type': 'NoneType', 'value': None}]}
