{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Create'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Destroy'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetAtlasInfo'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetAtlasSize'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetGuildAreaID'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetGuildAuctionTime'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetInfo'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Hide'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'HideAtlas'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsAtlas'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RegisterAtlasWindow'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Render'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RenderAtlas'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ScaleDown'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ScaleUp'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetGuildSiteAuctionArea'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetScale'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Show'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ShowAtlas'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'UnregisterAtlasWindow'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Update'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'UpdateAtlas'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'isShow'}],
 'import': [],
 'var': [{'name': 'TYPE_EMPIRE', 'type': 'int', 'value': 8},
         {'name': 'TYPE_MONSTER', 'type': 'int', 'value': 4},
         {'name': 'TYPE_NPC', 'type': 'int', 'value': 3},
         {'name': 'TYPE_OPC', 'type': 'int', 'value': 0},
         {'name': 'TYPE_OPCPVP', 'type': 'int', 'value': 1},
         {'name': 'TYPE_OPCPVPSELF', 'type': 'int', 'value': 2},
         {'name': 'TYPE_PARTY', 'type': 'int', 'value': 7},
         {'name': 'TYPE_WARP', 'type': 'int', 'value': 5},
         {'name': 'TYPE_WAYPOINT', 'type': 'int', 'value': 6},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'AvsvCIc'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
