{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsMountUpgradeUIOpen'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsMountingHorse'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendMountUpgradeSystemClose'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendMountUpgradeSystemGiveFeed'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendMountUpgradeSystemLevelUp'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendMountUpgradeSystemSkillLevelUp'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetMountHandler'}],
 'import': [],
 'var': [{'name': 'MOUNT_UPGRADE_SKILL_LEVELUP_COST_GEM', 'type': 'int', 'value': 1000},
         {'name': 'MOUNT_UPGRADE_SKILL_LEVELUP_COST_YANG', 'type': 'int', 'value': 20000000},
         {'name': 'MOUNT_UPGRADE_SYSTEM_GC_SUBHEADER_GIVE_FEED', 'type': 'int', 'value': 1},
         {'name': 'MOUNT_UPGRADE_SYSTEM_GC_SUBHEADER_HORSE_LEVEL_UP', 'type': 'int', 'value': 2},
         {'name': 'MOUNT_UPGRADE_SYSTEM_GC_SUBHEADER_OPEN', 'type': 'int', 'value': 0},
         {'name': 'MOUNT_UPGRADE_SYSTEM_HORSE_LEVEL_MAX', 'type': 'int', 'value': 40},
         {'name': 'MOUNT_UPGRADE_SYSTEM_HORSE_MIN_LEVEL_CONQUEROR', 'type': 'int', 'value': 30},
         {'name': 'MOUNT_UPGRADE_SYSTEM_HORSE_SKILL_LEVEL_MAX', 'type': 'int', 'value': 20},
         {'name': 'MOUNT_UPGRADE_SYSTEM_LEVEL_UP_RESULT_PERCENT_FAIL', 'type': 'int', 'value': 1},
         {'name': 'MOUNT_UPGRADE_SYSTEM_LEVEL_UP_RESULT_PERCENT_SUCCESS', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'TyBDv'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
