{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Clear'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSellingWon'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSellingYang'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetTotalSellingPrice'}],
 'import': [],
 'var': [{'name': 'PREMIUM_PRIVATE_SHOP_STATE_CLOSE', 'type': 'int', 'value': 1},
         {'name': 'PREMIUM_PRIVATE_SHOP_STATE_MODIFY', 'type': 'int', 'value': 3},
         {'name': 'PREMIUM_PRIVATE_SHOP_STATE_NONE', 'type': 'int', 'value': 0},
         {'name': 'PREMIUM_PRIVATE_SHOP_STATE_OPEN', 'type': 'int', 'value': 2},
         {'name': 'PREMIUM_PRIVATE_SHOP_SUBHEADER_GC_INFO', 'type': 'int', 'value': 3},
         {'name': 'PREMIUM_PRIVATE_SHOP_SUBHEADER_GC_ITEM_MOVE', 'type': 'int', 'value': 5},
         {'name': 'PREMIUM_PRIVATE_SHOP_SUBHEADER_GC_ITEM_SET', 'type': 'int', 'value': 4},
         {'name': 'PREMIUM_PRIVATE_SHOP_SUBHEADER_GC_UI_CLOSE', 'type': 'int', 'value': 0},
         {'name': 'PREMIUM_PRIVATE_SHOP_SUBHEADER_GC_UI_OPEN', 'type': 'int', 'value': 2},
         {'name': 'PREMIUM_PRIVATE_SHOP_SUBHEADER_GC_UI_OPEN_READY', 'type': 'int', 'value': 1},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'premiumPrivateShop'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
