{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Clear'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetQuestButtonNoticeCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetQuestCount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetQuestCounterData'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetQuestData'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetQuestIndex'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetQuestLastTime'}],
 'import': [],
 'var': [{'name': 'QUEST_MAX_NUM', 'type': 'int', 'value': 5},
         {'name': 'QUEST_TYPE_COLLECTION', 'type': 'int', 'value': 4},
         {'name': 'QUEST_TYPE_DAILY', 'type': 'int', 'value': 7},
         {'name': 'QUEST_TYPE_EVENT', 'type': 'int', 'value': 3},
         {'name': 'QUEST_TYPE_LEVELUP', 'type': 'int', 'value': 2},
         {'name': 'QUEST_TYPE_MAIN', 'type': 'int', 'value': 0},
         {'name': 'QUEST_TYPE_MAX', 'type': 'int', 'value': 9},
         {'name': 'QUEST_TYPE_SCROLL', 'type': 'int', 'value': 6},
         {'name': 'QUEST_TYPE_SUB', 'type': 'int', 'value': 1},
         {'name': 'QUEST_TYPE_SYSTEM', 'type': 'int', 'value': 5},
         {'name': 'QUEST_TYPE_UNEXPOSED', 'type': 'int', 'value': 8},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'quest'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
