{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetHighRankingInfoParty'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetHighRankingInfoSolo'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetMyPartyMemberName'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetMyRankingInfoParty'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetMyRankingInfoSolo'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetPartyMemberName'}],
 'import': [],
 'var': [{'name': 'HIGH_RANK_VIEW_MAX', 'type': 'int', 'value': 10},
         {'name': 'PARTY_RK_CATEGORY_CZ_CHICKEN', 'type': 'int', 'value': 12},
         {'name': 'PARTY_RK_CATEGORY_CZ_COW', 'type': 'int', 'value': 4},
         {'name': 'PARTY_RK_CATEGORY_CZ_DOG', 'type': 'int', 'value': 13},
         {'name': 'PARTY_RK_CATEGORY_CZ_DRAGON', 'type': 'int', 'value': 7},
         {'name': 'PARTY_RK_CATEGORY_CZ_HORSE', 'type': 'int', 'value': 9},
         {'name': 'PARTY_RK_CATEGORY_CZ_MONKEY', 'type': 'int', 'value': 11},
         {'name': 'PARTY_RK_CATEGORY_CZ_MOUSE', 'type': 'int', 'value': 3},
         {'name': 'PARTY_RK_CATEGORY_CZ_PIG', 'type': 'int', 'value': 14},
         {'name': 'PARTY_RK_CATEGORY_CZ_RABBIT', 'type': 'int', 'value': 6},
         {'name': 'PARTY_RK_CATEGORY_CZ_SHEEP', 'type': 'int', 'value': 10},
         {'name': 'PARTY_RK_CATEGORY_CZ_SNAKE', 'type': 'int', 'value': 8},
         {'name': 'PARTY_RK_CATEGORY_CZ_TIGER', 'type': 'int', 'value': 5},
         {'name': 'PARTY_RK_CATEGORY_DEFENSE_WAVE', 'type': 'int', 'value': 15},
         {'name': 'PARTY_RK_CATEGORY_GUILD_DRAGONLAIR_RED_ALL', 'type': 'int', 'value': 0},
         {'name': 'PARTY_RK_CATEGORY_GUILD_DRAGONLAIR_RED_NOW_WEEK', 'type': 'int', 'value': 1},
         {'name': 'PARTY_RK_CATEGORY_GUILD_DRAGONLAIR_RED_PAST_WEEK', 'type': 'int', 'value': 2},
         {'name': 'PARTY_RK_CATEGORY_MAX', 'type': 'int', 'value': 16},
         {'name': 'SOLO_RK_CATEGORY_BATTLE_ROYALE', 'type': 'int', 'value': 6},
         {'name': 'SOLO_RK_CATEGORY_BF_TOTAL', 'type': 'int', 'value': 1},
         {'name': 'SOLO_RK_CATEGORY_BF_WEAK', 'type': 'int', 'value': 0},
         {'name': 'SOLO_RK_CATEGORY_BNW', 'type': 'int', 'value': 5},
         {'name': 'SOLO_RK_CATEGORY_CHALLENGE', 'type': 'int', 'value': 7},
         {'name': 'SOLO_RK_CATEGORY_MAX', 'type': 'int', 'value': 8},
         {'name': 'SOLO_RK_CATEGORY_MD_BLUE', 'type': 'int', 'value': 3},
         {'name': 'SOLO_RK_CATEGORY_MD_RED', 'type': 'int', 'value': 2},
         {'name': 'TYPE_RK_MAX', 'type': 'int', 'value': 2},
         {'name': 'TYPE_RK_PARTY', 'type': 'int', 'value': 1},
         {'name': 'TYPE_RK_SOLO', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'ranking'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
