{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'FadeInMusic'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'FadeLimitOutMusic'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'FadeOutAllMusic'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'FadeOutMusic'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PlaySound'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'PlaySound3D'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetAmbienceSoundScale'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetMusicVolume'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetSoundScale'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetSoundVolume'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetSoundVolumef'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'StopAllSound'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'snd'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
