{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSnowflakeStickUseTime'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendSnowflakeStickEventRequestExchangeMount'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendSnowflakeStickEventRequestExchangePet'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendSnowflakeStickEventRequestExchangeStick'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SendSnowflakeStickEventRequestInfo'}],
 'import': [],
 'var': [{'name': 'SNOWFLAKE_STICK_EVENT_ENABLE', 'type': 'int', 'value': 12},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_ADD_SNOW_BALL', 'type': 'int', 'value': 1},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_ADD_TREE_BRANCH', 'type': 'int', 'value': 2},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_EVENT_INFO', 'type': 'int', 'value': 0},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_EXCHANGE_MOUNT_SUCCESS', 'type': 'int', 'value': 7},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_EXCHANGE_PET_SUCCESS', 'type': 'int', 'value': 6},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_EXCHANGE_STICK_SUCCESS', 'type': 'int', 'value': 5},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_MESSAGE_GET_RANK_BUFF', 'type': 'int', 'value': 10},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_MESSAGE_GET_SNOWFLAKE_BUFF', 'type': 'int', 'value': 11},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_MESSAGE_SNOW_BALL_MAX', 'type': 'int', 'value': 3},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_MESSAGE_TREE_BRANCH_MAX', 'type': 'int', 'value': 4},
         {'name': 'SNOWFLAKE_STICK_EVENT_GC_SUBHEADER_MESSAGE_USE_STICK_FAILED', 'type': 'int', 'value': 8},
         {'name': 'SNOWFLAKE_STICK_EVENT_RANK_BUFF_TYPE_KNIGHT', 'type': 'int', 'value': 1},
         {'name': 'SNOWFLAKE_STICK_EVENT_RANK_BUFF_TYPE_STONE', 'type': 'int', 'value': 3},
         {'name': 'SNOWFLAKE_STICK_EVENT_RANK_BUFF_TYPE_S_KNIGHT', 'type': 'int', 'value': 2},
         {'name': 'SNOWFLAKE_STICK_EVENT_RANK_BUFF_TYPE_S_PAWN', 'type': 'int', 'value': 0},
         {'name': 'SNOWFLAKE_STICK_EVENT_REFERENCE_LEVEL', 'type': 'int', 'value': 60},
         {'name': 'SNOWFLAKE_STICK_USE_COOLTIME', 'type': 'int', 'value': 1800},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'snowflakeStickEvent'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
