{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'DestroyInterfaceHandler'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetHeight'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetMusicVolume'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetNightModeOption'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetShadowLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSnowModeOption'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSnowTextureModeOption'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetSoundVolume'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetStructureViewMode'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetWidth'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsAlwaysShowName'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsDiceChatShow'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsShowDamage'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsShowMobAIFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsShowMobLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsShowSalesText'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsSoftwareCursor'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsViewChat'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetAlwaysShowNameFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetDiceChatShow'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetInterfaceHandler'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetMusicVolume'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetNightModeOption'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetShadowLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetShowDamageFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetShowMobAIFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetShowMobLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetShowSalesTextFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetSnowModeOption'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetSnowTextureModeOption'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetSoundVolumef'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetStructureViewMode'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SetViewChatFlag'}],
 'import': [],
 'var': [{'name': 'WINDOW_ABILITY', 'type': 'int', 'value': 2},
         {'name': 'WINDOW_CHAT', 'type': 'int', 'value': 9},
         {'name': 'WINDOW_COMMAND', 'type': 'int', 'value': 5},
         {'name': 'WINDOW_GAUGE', 'type': 'int', 'value': 7},
         {'name': 'WINDOW_INVENTORY', 'type': 'int', 'value': 1},
         {'name': 'WINDOW_JOURNAL', 'type': 'int', 'value': 4},
         {'name': 'WINDOW_MINIMAP', 'type': 'int', 'value': 8},
         {'name': 'WINDOW_QUICK', 'type': 'int', 'value': 6},
         {'name': 'WINDOW_SOCIETY', 'type': 'int', 'value': 3},
         {'name': 'WINDOW_STATUS', 'type': 'int', 'value': 0},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'systemSetting'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
