{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ArrangeTextTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Clear'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'EnablePKTitle'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetPosition'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'HideAllTextTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Initialize'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsChat'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Pick'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RegisterInfoTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'Render'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'SelectItemName'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ShowAllTextTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ShowCharacterTextTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'ShowItemTextTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'UpdateAllTextTail'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'UpdateShowingTextTail'}],
 'import': [],
 'var': [{'name': '__doc__', 'type': 'NoneType', 'value': None}, {'name': '__name__', 'type': 'str', 'value': 'textTail'}, {'name': '__package__', 'type': 'NoneType', 'value': None}]}
