{'class': [],
 'func': [{'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'GetLimitFlagCountByLevel'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'IsValentineDayEventFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RequestStatusInfo'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RequestUseQuestFlag'},
          {'args': ['bad-module'], 'defaults': ['bad-module'], 'name': 'RequestWrapQuestFlag'}],
 'import': [],
 'var': [{'name': 'VALENTINE_DAY_EVENT_ENABLE', 'type': 'int', 'value': 6},
         {'name': 'VALENTINE_DAY_EVENT_FALG_TYPE_CHOCOLATE', 'type': 'int', 'value': 1},
         {'name': 'VALENTINE_DAY_EVENT_FALG_TYPE_MAX', 'type': 'int', 'value': 2},
         {'name': 'VALENTINE_DAY_EVENT_FALG_TYPE_ROSE', 'type': 'int', 'value': 0},
         {'name': 'VALENTINE_DAY_EVENT_GC_SUBHEADER_ADD_QUEST_FLAG', 'type': 'int', 'value': 1},
         {'name': 'VALENTINE_DAY_EVENT_GC_SUBHEADER_FAIL_USE_WRAP_ITEM', 'type': 'int', 'value': 5},
         {'name': 'VALENTINE_DAY_EVENT_GC_SUBHEADER_REMIND_FLAG_MAX', 'type': 'int', 'value': 2},
         {'name': 'VALENTINE_DAY_EVENT_GC_SUBHEADER_STATUS_INFO', 'type': 'int', 'value': 0},
         {'name': 'VALENTINE_DAY_EVENT_GC_SUBHEADER_USE_FLAG_SUCCESS', 'type': 'int', 'value': 3},
         {'name': 'VALENTINE_DAY_EVENT_GC_SUBHEADER_WRAP_FLAG_SUCCESS', 'type': 'int', 'value': 4},
         {'name': 'VALENTINE_DAY_EVENT_USE_BUTTON_COOLTIME_MS', 'type': 'int', 'value': 500},
         {'name': 'VALENTINE_DAY_EVENT_USE_FLAG_NEED_COUNT', 'type': 'int', 'value': 1},
         {'name': 'VALENTINE_DAY_EVENT_USE_INEVENTORY_EMPTY_NEED_COUNT', 'type': 'int', 'value': 1},
         {'name': 'VALENTINE_DAY_EVENT_WRAP_BUTTON_COOLTIME_MS', 'type': 'int', 'value': 500},
         {'name': 'VALENTINE_DAY_EVENT_WRAP_FLAG_NEED_COUNT', 'type': 'int', 'value': 50},
         {'name': 'VALENTINE_DAY_EVENT_WRAP_INEVENTORY_EMPTY_NEED_COUNT', 'type': 'int', 'value': 1},
         {'name': 'VALENTINE_DAY_EVENT_WRAP_POSSIBLE_LEVEL', 'type': 'int', 'value': 90},
         {'name': '__doc__', 'type': 'NoneType', 'value': None},
         {'name': '__name__', 'type': 'str', 'value': 'valentineDayModule'},
         {'name': '__package__', 'type': 'NoneType', 'value': None}]}
